### ISSUE TITLE
DOC for ' Rerun one execution stream '

### ISSUE THREAD

**Issue by JohnHuahuaZhan** [getgauge/gauge#1002]
it is all about how to run in groups ,nothing about " Rerun one execution stream "
<img width="1249" alt="2018-04-07 12 54 10" src="https://user-images.githubusercontent.com/11831897/38451483-39e16200-3a63-11e8-87db-6a62ef42a777.png">

**Comment by sriv** [comment]
The description below the command states:

> This creates 4 groups (provided by -n flag) of specification and selects the 2nd group (provided by -g flag) for execution.

So, if you run `gauge run -n=4 -g=2 specs`, it will divide your specs into 4 groups, and run the 2nd group.

Can you please clarify what is missing as per you?

**Comment by zabil** [comment]
Closing as stale.
