### ISSUE TITLE
running gauge with maven/gradle build tool  works well at linux/windows platform but failed at Mac OS(10.13.4)

### ISSUE THREAD

**Issue by JohnHuahuaZhan** [getgauge/gauge#1004]
gradle or java was already installed 
<img width="1077" alt="2018-04-09 16 37 51" src="https://user-images.githubusercontent.com/11831897/38488511-487243b6-3c16-11e8-91e8-2566d69453e2.png">

**Comment by nehashri** [comment]
@JohnHuahuaZhan can you please tell us which version of Gauge you are using. You can run `gauge version` to find the version of gauge and its plugins. 
Run `gradle buildEnvironment` to find out the gradle version. 
Please paste the output of the commands here. It would help us debug the issue further.

**Comment by sriv** [comment]
@JohnHuahuaZhan - is this issue still persisting for you? If so, can you please share some information? Thanks.

**Comment by zabil** [comment]
Closing this as stale
