### ISSUE TITLE
Should be able to read file content when the file is given as a Special Parameter inside a table

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge#1006]
_From @osandadeshan on January 22, 2018 9:45_

### Expected behavior
Should be able to read file content when the file is given as a Special Parameter inside a table

### Actual behavior
Cannot read file content when the file is given as a Special Parameter inside a table

### Steps to reproduce
1. Create a step with a table
2. Inside that table pass a file to read it as a string
3. Run the step
4. You will get the below error
[ParseWarning] C:\Users\UnimaOs\IdeaProjects\projectname\project_test_automation\specs\sample spec.spec:42 Dynamic param <file:/resources/deck_title.txt> could not be resolved, Treating it as static param
5. That file path will be read as the string
Here I have attached the related spec file.
[sample.zip](https://github.com/getgauge/gauge-java/files/1651457/sample.zip)
![capture](https://user-images.githubusercontent.com/9147189/35214418-16e12734-ff87-11e7-8398-90837fd89b54.PNG)

### Gauge version
```
Gauge version: 0.9.3
Commit Hash: 724e6d3

Plugins
-------
csharp (0.10.1)
flash (0.0.1)
html-report (4.0.2)
java (0.6.5)
ruby (0.4.2)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

_Copied from original issue: getgauge/gauge-java#129_

**Comment by zabil** [comment]
_From @riju91 on January 22, 2018 11:39_

Hello @osandadeshan, this seems like a nice feature to have but since gauge team is preoccupied with some other features, we do not plan to pick this up immediately. If you are willing to contribute we would appreciate a pull request from your end. Thanks

**Comment by zabil** [comment]
_From @osandadeshan on January 22, 2018 15:53_

@riju91 @zabil @kaustavdm @sriv 
Ok. I am actually using Gauge for the past 2 years. It is the best test
automation framework I have ever used. This feature will definitely be
fixed the ability to use several test designing techniques related to QA
such as boundry value analysis. So we were waiting for this feature.

Good luck Gauge Team!

Note: I'll also try to solve this issue and send you a pull request from my
end. But I am not good at Go language. Will try anyway.

**Comment by zabil** [comment]
_From @jackperalta on April 5, 2018 23:42_

I think this is an issue for https://github.com/getgauge/gauge itself, as the parsing of parameters/steps is a core feature and not a responsibility of the runner

**Comment by Apoorva-GA** [comment]
Should be available in gauge nightly >=19/06/18
