### ISSUE TITLE
When IDEA gauge plugin is enabled, IF statements have extra blank line in them

### ISSUE THREAD

**Issue by mstralka** [getgauge/gauge#101]
I opened a ticket with JetBrains because I'm using IDEA to write JavaScript.  When I create an IF statement and press the return key, the IDE always inserts 2 blank lines, instead of just one blank line. When I finish writing the code in the IF statement, I then have to manually remove the blank line at the end. See the attached screenshots. It is currently working like "2-spaces.png" but I want it to work like "1-space.png". 

After removing all IDEA plugins and re-enabling them one by one, I identified the Gauge plugin as the one causing the double-blank line problem.  Disabling the plugin removes the problem.  

Is this a bug in the Gauge plugin or intended behavior?

Thanks

![1-space](https://cloud.githubusercontent.com/assets/439680/6349946/9cd7cabc-bbfd-11e4-8b39-540cce87e9bb.png)
![2-spaces](https://cloud.githubusercontent.com/assets/439680/6349947/9f1bb6f8-bbfd-11e4-91b0-e413e15b1bed.png)

**Comment by sriv** [comment]
Possibly the same issue that caused getgauge/Intellij-plugin#39, will verify and push a fix.

Sorry about that.

**Comment by ApoorvaM** [comment]
Fixed in this [commit](https://github.com/getgauge/Intellij-Plugin/commit/05229d9774db8d77285009a48411dc54378cf489).
