### ISSUE TITLE
[LSP] A newly added parameter should appear in the list after file save

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1011]
**Expected behavior**
A newly added parameter should be available after file save

**Actual behavior**
In the test, the following events happen in the given order
* notification didChange is sent with parameters
```
{"textDocument":{"uri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/specs/edit_codecomplete_param.spec"},"contentChanges":[{"text":"Parameter Code Complete\n=======================\ntable:./csv.csv\nGauge LSP 2\n-----------\n* one \"something\"\n* start \"s\"\n* blah \"more\"\n* two \"another\" \"parameter\"\n* start one \u003cone\u003e\n"}]}
```
* The file is saved on the disk
* `notif: textDocument/didSave:` with parameters ```
{"textDocument":{"uri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/specs/edit_codecomplete_param.spec"}}
```
* `Wait for 1 second`
* However, the codecomplete parameters list does not have the parameter `more` added while editing the file

The full log
```
01:12:46.631 LangServer: reading on stdin, writing on stdout
01:12:46.632 --> request #0: initialize: {"processId":14551,"rootPath":"/Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete","rootUri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete","capabilities":{"workspace":{"applyEdit":true,"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true}},"textDocument":{"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true}},"hover":{"dynamicRegistration":true},"signatureHelp":{"dynamicRegistration":true},"definition":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true},"codeAction":{"dynamicRegistration":true},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true}}},"trace":"off","experimental":{}}
01:12:46.633 <-- result #0: initialize: {"capabilities":{"textDocumentSync":1,"completionProvider":{"resolveProvider":true,"triggerCharacters":["*","* ","\"","\u003c",":",","]},"definitionProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":true,"codeLensProvider":{},"documentFormattingProvider":true,"renameProvider":true}}
01:12:46.634 --> notif: initialized: {}
01:12:46.634 <-- request #0: client/registerCapability: {"registrations":[{"id":"gauge-fileWatcher","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"/Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/**/*{.cpt,.spec,.md}","kind":5}]}}]}
01:12:46.636 --> result #0: client/registerCapability: null
01:12:46.654 <-- request #1: client/registerCapability: {"registrations":[{"id":"gauge-runner-didOpen","method":"textDocument/didOpen","registerOptions":{"documentSelector":[{"scheme":"file","language":"ruby","pattern":"/Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/step_implementations/**/*.rb"}]}},{"id":"gauge-runner-didClose","method":"textDocument/didClose","registerOptions":{"documentSelector":[{"scheme":"file","language":"ruby","pattern":"/Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/step_implementations/**/*.rb"}]}},{"id":"gauge-runner-didChange","method":"textDocument/didChange","registerOptions":{"documentSelector":[{"scheme":"file","language":"ruby","pattern":"/Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/step_implementations/**/*.rb"}],"syncKind":1}},{"id":"gauge-runner-codelens","method":"textDocument/codeLens","registerOptions":{"documentSelector":[{"scheme":"file","language":"ruby","pattern":"/Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/step_implementations/**/*.rb"}]}},{"id":"gauge-runner-fileWatcher","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"/Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/step_implementations/**/*.rb","kind":5}]}}]}
01:12:46.657 --> result #1: client/registerCapability: null
01:12:46.663 --> request #1: gauge/getRunnerLanguage: null
01:12:46.663 <-- result #1: gauge/getRunnerLanguage: "ruby"
01:12:46.670 --> notif: textDocument/didOpen: {"textDocument":{"uri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/specs/edit_codecomplete_param.spec","languageId":"markdown","version":1,"text":"Parameter Code Complete\n=======================\ntable:./csv.csv\nGauge LSP 2\n-----------\n* one \"something\"\n* start \"s\"\n* two \"another\" \"parameter\"\n* start one \u003cone\u003e\n"}}
01:12:46.676 --> notif: textDocument/didChange: {"textDocument":{"uri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/specs/edit_codecomplete_param.spec"},"contentChanges":[{"text":"Parameter Code Complete\n=======================\ntable:./csv.csv\nGauge LSP 2\n-----------\n* one \"something\"\n* start \"s\"\n* blah \"more\"\n* two \"another\" \"parameter\"\n* start one \u003cone\u003e\n"}]}
01:12:46.676 --> notif: textDocument/didSave: {"textDocument":{"uri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/specs/edit_codecomplete_param.spec"}}
01:12:46.691 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/specs/someTags/tagAtSpecLevel.spec","diagnostics":[{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":10000}},"severity":1,"code":"step 'start' do ||\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"}]}
01:12:46.692 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/specs/someTags/tagCompletion.spec","diagnostics":[{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":10000}},"severity":1,"code":"step 'one \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"}]}
01:12:46.692 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/specs/someTags/tagInMultipleLines.spec","diagnostics":[{"range":{"start":{"line":10,"character":0},"end":{"line":10,"character":10000}},"severity":1,"code":"step 'one \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":11,"character":0},"end":{"line":11,"character":10000}},"severity":1,"code":"step 'start \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":12,"character":0},"end":{"line":12,"character":10000}},"severity":1,"code":"step 'two \u003carg0\u003e \u003carg1\u003e' do |arg0, arg1|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":16,"character":0},"end":{"line":16,"character":10000}},"severity":1,"code":"step 'one \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":17,"character":0},"end":{"line":17,"character":10000}},"severity":1,"code":"step 'start \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":18,"character":0},"end":{"line":18,"character":10000}},"severity":1,"code":"step 'two \u003carg0\u003e \u003carg1\u003e' do |arg0, arg1|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"}]}
01:12:46.692 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/specs/codecomplete_param.spec","diagnostics":[{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":10000}},"severity":1,"code":"step 'one \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":10000}},"severity":1,"code":"step 'start \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":7,"character":0},"end":{"line":7,"character":10000}},"severity":1,"code":"step 'two \u003carg0\u003e \u003carg1\u003e' do |arg0, arg1|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":8,"character":0},"end":{"line":8,"character":10000}},"severity":1,"code":"step 'start one \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"}]}
01:12:46.693 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/specs/edit_codecomplete_param.spec","diagnostics":[{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":17}},"severity":1,"code":"step 'one \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":11}},"severity":1,"code":"step 'start \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":7,"character":0},"end":{"line":7,"character":13}},"severity":1,"code":"step 'two \u003carg0\u003e \u003carg1\u003e' do |arg0, arg1|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":8,"character":0},"end":{"line":8,"character":27}},"severity":1,"code":"step 'start one \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"}]}
01:12:46.693 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/specs/someTags/tagAtScenarioLevel.spec","diagnostics":[{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":10000}},"severity":1,"code":"step 'one \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":10000}},"severity":1,"code":"step 'start \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":7,"character":0},"end":{"line":7,"character":10000}},"severity":1,"code":"step 'two \u003carg0\u003e \u003carg1\u003e' do |arg0, arg1|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":12,"character":0},"end":{"line":12,"character":10000}},"severity":1,"code":"step 'one \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":13,"character":0},"end":{"line":13,"character":10000}},"severity":1,"code":"step 'start \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":14,"character":0},"end":{"line":14,"character":10000}},"severity":1,"code":"step 'two \u003carg0\u003e \u003carg1\u003e' do |arg0, arg1|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"}]}
01:12:46.710 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/specs/codecomplete_param.spec","diagnostics":[{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":10000}},"severity":1,"code":"step 'one \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":10000}},"severity":1,"code":"step 'start \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":7,"character":0},"end":{"line":7,"character":10000}},"severity":1,"code":"step 'two \u003carg0\u003e \u003carg1\u003e' do |arg0, arg1|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":8,"character":0},"end":{"line":8,"character":10000}},"severity":1,"code":"step 'start one \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"}]}
01:12:46.710 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/specs/edit_codecomplete_param.spec","diagnostics":[{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":17}},"severity":1,"code":"step 'one \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":11}},"severity":1,"code":"step 'start \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":7,"character":0},"end":{"line":7,"character":13}},"severity":1,"code":"step 'blah \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":8,"character":0},"end":{"line":8,"character":27}},"severity":1,"code":"step 'two \u003carg0\u003e \u003carg1\u003e' do |arg0, arg1|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":9,"character":0},"end":{"line":9,"character":17}},"severity":1,"code":"step 'start one \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"}]}
01:12:47.682 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/specs/someTags/tagAtScenarioLevel.spec","diagnostics":[{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":10000}},"severity":1,"code":"step 'one \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":10000}},"severity":1,"code":"step 'start \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":7,"character":0},"end":{"line":7,"character":10000}},"severity":1,"code":"step 'two \u003carg0\u003e \u003carg1\u003e' do |arg0, arg1|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":12,"character":0},"end":{"line":12,"character":10000}},"severity":1,"code":"step 'one \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":13,"character":0},"end":{"line":13,"character":10000}},"severity":1,"code":"step 'start \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":14,"character":0},"end":{"line":14,"character":10000}},"severity":1,"code":"step 'two \u003carg0\u003e \u003carg1\u003e' do |arg0, arg1|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"}]}
01:12:47.682 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/specs/someTags/tagAtSpecLevel.spec","diagnostics":[{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":10000}},"severity":1,"code":"step 'start' do ||\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"}]}
01:12:47.682 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/specs/someTags/tagCompletion.spec","diagnostics":[{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":10000}},"severity":1,"code":"step 'one \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"}]}
01:12:47.682 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/specs/someTags/tagInMultipleLines.spec","diagnostics":[{"range":{"start":{"line":10,"character":0},"end":{"line":10,"character":10000}},"severity":1,"code":"step 'one \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":11,"character":0},"end":{"line":11,"character":10000}},"severity":1,"code":"step 'start \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":12,"character":0},"end":{"line":12,"character":10000}},"severity":1,"code":"step 'two \u003carg0\u003e \u003carg1\u003e' do |arg0, arg1|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":16,"character":0},"end":{"line":16,"character":10000}},"severity":1,"code":"step 'one \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":17,"character":0},"end":{"line":17,"character":10000}},"severity":1,"code":"step 'start \u003carg0\u003e' do |arg0|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"},{"range":{"start":{"line":18,"character":0},"end":{"line":18,"character":10000}},"severity":1,"code":"step 'two \u003carg0\u003e \u003carg1\u003e' do |arg0, arg1|\n\traise 'Unimplemented Step'\nend","message":"Step implementation not found"}]}
01:12:47.693 --> request #2: textDocument/completion: {"position":{"line":5,"character":15},"textDocument":{"uri":"file:///Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/data/codecomplete/specs/edit_codecomplete_param.spec"}}
01:12:47.694 <-- result #2: textDocument/completion: {"isIncomplete":false,"items":[{"label":"something","kind":6,"detail":"static","filterText":"something\"","textEdit":{"range":{"start":{"line":5,"character":7},"end":{"line":5,"character":17}},"newText":"something\""},"insertTextFormat":1},{"label":"s","kind":6,"detail":"static","filterText":"s\"","textEdit":{"range":{"start":{"line":5,"character":7},"end":{"line":5,"character":17}},"newText":"s\""},"insertTextFormat":1},{"label":"another","kind":6,"detail":"static","filterText":"another\"","textEdit":{"range":{"start":{"line":5,"character":7},"end":{"line":5,"character":17}},"newText":"another\""},"insertTextFormat":1},{"label":"parameter","kind":6,"detail":"static","filterText":"parameter\"","textEdit":{"range":{"start":{"line":5,"character":7},"end":{"line":5,"character":17}},"newText":"parameter\""},"insertTextFormat":1}]}
01:12:47.714 --> request #3: shutdown: null
01:12:48.754 <-- result #3: shutdown: null
01:12:48.755 --> notif: exit: null
01:12:48.756 Connection closed
```
**Version**
```
Gauge version: 0.9.8
Commit Hash: 61d692c

Plugins
-------
ruby (0.5.0.nightly-2018-04-11)
```

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
