### ISSUE TITLE
When a plugin version folder is empty, uninstall should be handled

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1018]
**Current Behavior**
Sometimes while uninstalling a plugin only an empty folder remains.

When `gauge version` is invoked, the plugin name is still shown.

When gauge tries to uninstall the plugin we get error
```
Failed to uninstall plugin <plugin> . File /tmp/plugins/<plugin>/0.3.0/plugin.json doesn't exist.
Failed to uninstall plugin <plugin> . File /tmp/plugins/<plugin>/0.3.0/skel/plugin.json doesn't exist.
Failed to uninstall plugin <plugin> . File /tmp/plugins/<plugin>/0.3.0/skel/step_impl/plugin.json doesn't exist.
```
Observed on https://build.getgauge.io/go/tab/build/detail/python-lsp-tests/140/lsp-tests/1/osx

**Suggestion**
If the folder is empty, uninstall deletes the plugin version folder.

**Comment by sriv** [comment]
fix should be available in nightly >= 24/4/18

**Comment by sguptatw** [comment]
On Windows python-lsp-tests CI when trying to uninstall python getting
```
Unable to read plugin's metadata, removing C:\gauge_plugins\plugins\python\0.3.0
Failed to uninstall plugin python . remove C:\gauge_plugins\plugins\python\0.3.0: The process cannot access the file because it is being used by another process.
```
Not sure if this related.
> The uninstall step is after installing gauge.

**Comment by nehashri** [comment]
This seemed to be a issue on the Go Agent machine. This has been fixed.
