### ISSUE TITLE
Error starting plugin

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1020]
**Expected behavior**
Should be to start and connect to a plugin

**Actual behavior**
Error starting plugin Html Report 4.0.3. Failed to connect to plugin. Timed out connecting to 127.0.0.1:55761

**Observed on**
https://travis-ci.org/getgauge/gauge/jobs/370531058

**Version**
```
0.9.8.nightly.2018-04-24
```

**Comment by sguptatw** [comment]
Can this be because  backlog of pending connections is full?

[Common reasons why connections are refused](https://stackoverflow.com/questions/2333400/what-can-be-the-reasons-of-connection-refused-errors)

**Comment by sriv** [comment]
hasn't happened in a while. Also, it should be using html-report 4.0.4 since it uses the nightly channel to install.
