### ISSUE TITLE
With re-run user must be able to change verbosity

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1021]
**Proposed behavior**
The user should be able to specify `gauge run --repeat -v`. In this case the repeated run in the verbose mode.

**Current behavior**
The verbosity is what is specified in the previous run.

**Comment by nehashri** [comment]
Is this still valid?

**Comment by sguptatw** [comment]
This has been fixed with
```
Gauge version: 0.9.8.nightly-2018-05-01
Commit Hash: 765d3e7

Plugins
-------
js (2.3.0.nightly-2018-05-08)
```
