### ISSUE TITLE
Diagnostics should not be published after a shutdown request is sent

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#1022]
### Expected Behaviour
After a shutdown request is sent from the client to gauge lsp server, Gauge should stop all subprocesses. No other request should be sent the client.

### Actual Behaviour
Gauge is stopping the runner, but not all go routines spawned by gauge itself is not stopped. 
Gauge is still sending publishDiagnostics notification to the client.

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
