### ISSUE TITLE
Gauge installation should fail if install commands fail

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#1024]
Gauge runs a few commands to install plugins. If a plugin installation fails or post installation commands fail, gauge should fail the installation.

Dev Notes :
To fix this, Gauge should unzip the plugin in OS temp directory, run the installation commands. Only if installation is successful, it should copy over the files to the Gauge plugin folder.

**Comment by NivedhaSenthil** [comment]
Fix should be available in nightly >= 2018-05-09

**Comment by sguptatw** [comment]
**Actual behavior**
The directory contains gauge project related folders even when initialization is incomplete
```
d-----        5/14/2018   1:11 AM                env
d-----        5/14/2018   1:11 AM                logs
d-----        5/14/2018   1:11 AM                Properties
```
**Expected behavior**
Should contain gauge project files/folders only when the initialization succeeds

**Steps to replicate**
* `gauge init csharp` when offline
