### ISSUE TITLE
the gradle log is incorrect when i run gauge using gradle with Property 'specsDir' not set

### ISSUE THREAD

**Issue by JohnHuahuaZhan** [getgauge/gauge#1028]
![_ _20180508105720](https://user-images.githubusercontent.com/11831897/39735537-9cc9316e-52ae-11e8-9887-e0e57532e2f4.png)

```log
Property 'specsDir' not set. Using default value => '%s'
```
'%s' should have been replaced by the default spec directory

### gauge
Gauge version: 0.9.8
Plugins:
java (0.6.7)
### gradle
version:4.6
### jdk
version:9

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
