### ISSUE TITLE
Diagnostics is wrong when the same unimplemented step is used twice in a specification

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1035]
**Expected behavior**
Diagnostics should be displayed correctly

**Actual behavior**
`Undefined step` is displayed the first time. The second occurrence is marked as defined

**Steps to replicate**
* Create a `gauge-js` project
* Add an unimplemented step in the specification to the 1st scenario
* Add the same unimplemented step in the 2nd scenario.
> The second occurrence of the unimplemented step is marked as implemented

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-11
Commit Hash: fcb9e9d

Plugins
-------
js (2.3.1.nightly-2018-05-08)
```

**Comment by Apoorva-GA** [comment]
Should be available in gauge-vscode nightly >= 15/05/18

**Comment by Apoorva-GA** [comment]
Should be available in gauge nightly >= 15/05/18
