### ISSUE TITLE
Should be able to install getgauge for pip

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1037]
**Expected behavior**
Installing gauge-python should install corresponding getgauge version in pip

**Actual behavior**
```
Gauge version: 0.9.9.nightly-2018-05-15
Commit Hash: f4e155e

Plugins
-------
python (0.3.2.nightly-2018-05-15)
```
**Steps to replicate**
> Point to nightly repository
* Install `gauge-python`

Check the pip getgauge version
```
pip show getgauge
Name: getgauge
Version: 0.3.0.dev20180501
Summary: Enables Python support for Gauge
Home-page: https://github.com/getgauge/gauge-python
Author: Gauge Team
Author-email: getgauge@outlook.com
License: MIT
Location: .../python2.7/site-packages
Requires: ptvsd, redBaron, futures, grpcio
...@ubuntu:~$ gauge version
Gauge version: 0.9.9.nightly-2018-05-11
Commit Hash: fcb9e9d

Plugins
-------
python (0.3.2.nightly-2018-05-15)
```

**Comment by sguptatw** [comment]
During installation of `gauge-python` pip installation of getgauge is taken care of internally. So, when updating the version this has to be taken care of.

**Comment by NivedhaSenthil** [comment]
Fix should be available in nightly >= 17/05/2018
