### ISSUE TITLE
Find Usage statistics of a step created from a concept should show correct should be correct

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1038]
**Expected behavior**
The number of usages should reflect in the statistics

**Actual behavior**
Statistics always displays 0 references

**Steps to replicate**
* Create a new `gauge-js` project
* Create a concept
```
# open project <projectPath>
* create project <projectPath>
* setup data required by runner
* open the project in the temporary directory
* verify gauge runner

# open <projectPath> and verify diagnostics <diagnostics>
* create project <projectPath>
* setup data required by runner
* open the project <projectPath> and verify diagnostics <diagnostics>
```
* Implement the step `verify gauge runner`
* The find usage statistics is 0
> The Usage statistics is displayed correctly when created from a specification

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-15
Commit Hash: 8db625f

Plugins
-------
js (2.3.1.nightly-2018-05-16)
```

**Comment by Apoorva-GA** [comment]
**Steps to replicate**
* Create a new `gauge-js` project
* Create a concept
```
#concept1
* step1

#concept2
*step2
```
* Where `step1` is unimplemented.
* Use `concept1` from any spec file.
* `concept2` not used in any of the spec/cpt file.
* implement `step1` as step.

Find reference of `step1` shows `0 reference`.

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge nightly >= 21/05/18
