### ISSUE TITLE
Plugin install fails for non-sudo users

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#104]
When installing a plugin, without write access to `/tmp`, the install fails.

Log:

```
go@gauge-demo-agent:/home/gauge$ gauge --install ruby
Downloading using wget => &{/usr/bin/wget [wget --no-check-certificate http://raw.github.com/getgauge/gauge-repository/master/ruby-install.json -O /tmp/gauge_temp/ruby-install.json] []  <nil> <nil> <nil> [] %!s(*syscall.SysProcAttr=<nil>) %!s(*os.Process=<nil>) <nil> ?reflect.Value? %!s(bool=false) [] [] [] [] %!s(chan error=<nil>)}
/tmp/gauge_temp/ruby-install.json: Permission denied
17:27:04.776 [WARN] Failed to install plugin ruby : Could not download ruby-install.json file. Invalid plugin name
```

**Comment by prateekbaheti** [comment]
It is a case where the temp directory does not have write permissions. Gauge uses [os.TempDir()](https://golang.org/pkg/os/#TempDir) to find the location and assumes it has write access.

According to [this](http://unix.stackexchange.com/questions/71622/what-are-common-rights-for-tmp-i-unintentionnally-set-it-all-public-recursive), the assumption is justified.

**Comment by sriv** [comment]
Closing this, seems to work now.

**Comment by ketan** [comment]
@sriv - I'd like to re-open this issue. While you're right in that `os.TempDir` does return the OS temp directory, however the problem arises when gauge is executed by multiple users on a machine and the directory `/tmp/gauge_temp` is owned by the first user that creates the directory.

The correct way to do this would be to to create a new unique tmpdir every run and delete it at exit.

**Comment by sriv** [comment]
Thanks @ketan. That makes sense. Reopening this.
