### ISSUE TITLE
Getting an error while installing using choco - non admin user

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1042]
**Expected behavior**
Should not get an error

**Actual behavior**
Getting the RemoteException error with a warning
```
System.Management.Automation.RemoteException
WARNING: The data being saved is truncated to 1024 characters.
```
> The Gauge version is installed

**Steps to replicate**
* Login as a non-admin user
* Install gauge using choco
> The warning is displayed

**Version**
```
Gauge version: 0.9.9
Commit Hash: 8db625f
```

**Comment by sriv** [comment]
Please check if your PATH exceeds 1024 character. This is a limitation on windows. 

See [this](https://superuser.com/questions/387619/overcoming-the-1024-character-limit-with-setx) for explanation and potential fix.

**Comment by sguptatw** [comment]
Yes, the PATH is exceeding 1024 characters. 

However here is my observation.
The Environment variables can be System variables or User variables. When gauge is installed using choco, the User variables are also getting copied onto the System variables.
So it exceeds the limit faster.

**Comment by sguptatw** [comment]
This issue was moved to getgauge/chocolatey-packages#7
