### ISSUE TITLE
Post with example of non-Western language

### ISSUE THREAD

**Issue by binkley** [getgauge/gauge#1045]
Reading https://blog.getgauge.io/why-we-built-gauge-6e31bb4848cd, I am excited!

However, I wish you'd post an example with a non-Western language.  See ISO 8859 and  15924 for examples.  An example beyond 8-bit encoding (say, Mandarin) would illuminate better, I think, the point you are conveying.

**Comment by zabil** [comment]
Ah yes, we do that towards the end in this article https://blog.getgauge.io/why-write-tests-in-plain-text-d9a54ccdc41b

Will rework this.

**Comment by binkley** [comment]
Thanks.  I read that, so my remarks should have been more clear.  Yep, would like to see more I18N and L10N upfront.  :)

**Comment by zabil** [comment]
Also @binkley I18N and L10N aside, we are trying to explain Gauge's choice of Markdown and it's keyword-less syntax (like the other pickled vegetable).
