### ISSUE TITLE
Alternative to double quote marks for marking parameters in markdown

### ISSUE THREAD

**Issue by binkley** [getgauge/gauge#1046]
I can easily spot gauge parameters in markdown with double quote marks:
```
# Search for movies
## Search for blockbusters
* Search for theaters playing "Avengers" in "Bangalore"
## Search 2017 Oscar winners
* Search for theaters playing "The shape of water" in "Bangalore"
```
(From https://blog.getgauge.io/why-we-built-gauge-6e31bb4848cd)

However, that is not how'd I'd normally write markdown.  For examples and exemplars, I'd use emphasis:
```
* Search for theaters playing _The shape of water_ in _Bangalore_
```
It would be nice for gauge to recognize these as parameters, or document it better if this is a hidden feature.

**Comment by ajoecker** [comment]
I have to admit that I do not really like the `_parameter_` version. As you said, double quotes make the identification of parameters easy and personally I do think this is the case for underscore.

I do not know so much about standard markdown, but why would you use `_` for this ? Is it also a personal decision ?

**Comment by binkley** [comment]
@ajoecker I use underscore for vars and params to achieve italics in the produced HTML.  This matches the result of the `<var>x</var>` tag from standard HTML.

**Comment by zabil** [comment]
For consistency and clarity Gauge will use only double quotes for parameters.
