### ISSUE TITLE
gauge.hook deprecated 0.9.9

### ISSUE THREAD

**Issue by chrdoud** [getgauge/gauge#1048]
### Expected behavior
a normal run without keyword gauge

### Actual behavior
[DEPRECATED] gauge.beforeStep() will be removed soon, use beforeStep() instead.
[DEPRECATED] gauge.beforeSuite() will be removed soon, use beforeSuite() instead.
#################################################################

```
gauge.hooks.beforeSuite(function () {
cl.SHOW_MODE_AND_URL();
});
```
without gauge ,
hooks not found

### Gauge version
0.9.9

**Comment by NivedhaSenthil** [comment]
Can you try with the latest gauge-js plugin ?

**Comment by sriv** [comment]
Updated the docs to reflect the correct usage. 

Closing this. Feel free to comment if this is still an issue.
