### ISSUE TITLE
gpa required to install gauge

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1050]
**Expected behavior**
Should be able to install by following the instructions in documentation

**Actual behavior**
Getting error `gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
The command '/bin/sh -c apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B' returned a non-zero code: 255`

**Steps to replicate**
* On a docker container install gauge
```
RUN apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B
RUN echo deb https://dl.bintray.com/gauge/gauge-deb stable main | sudo tee -a /etc/apt/sources.list
RUN apt-get update
RUN apt-get install gauge
ENV PATH=$HOME/.gauge:$PATH
```
> Refer build without explicit gpa installation https://travis-ci.org/getgauge-examples/ci-docker/builds/382475732

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-21
Commit Hash: f7d0def
```

**Comment by sriv** [comment]
The error seems very clear to me. To run `apt-key` command, Gnu Privacy Guard (aka gnupg) is a pre-requisite of `apt-key`. Ref: https://manpages.debian.org/stretch/apt/apt-key.8.en.html#DESCRIPTION

**Comment by sguptatw** [comment]
Thanks for the clarification. Assuming things have changed in implementation,

'cause earlier without gnup installed gauge installation with key used to succeed Refer the Dockerfile in https://github.com/getgauge-examples/ci-docker/tree/41665b57c3734119fc16e36a023e7ab5ea33d297

Have fixed the ci-docker example to now install gpa
