### ISSUE TITLE
Rerun flag broken

### ISSUE THREAD

**Issue by olejkavn** [getgauge/gauge#1051]
### Expected behavior
rerun works fine

 with maven plugin

### Actual behavior
rerun doesn't work

### Steps to reproduce
sample project: [ioc-spring-master.zip](https://github.com/getgauge/gauge/files/2030229/ioc-spring-master.zip)
1.mvn clean install
2.mvn gauge:execute
3.mvn gauge:execute -Dflags="f"

### Gauge version
```
Gauge version: 0.9.9
Commit Hash: 8db625f

Plugins
-------
html-report (4.0.4)
java (0.6.7)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

### Maven version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T21:49:05+02:00)
Maven home: C:\apache-maven-3.5.5\bin\..
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: C:\Java\jdk1.8.0_131\jre
Default locale: en_US, platform encoding: Cp1251
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by zabil** [comment]
Refer discussion on Gitter [May 23, 2018 2:12 PM](https://gitter.im/getgauge/chat?at=5b05298baaafa25932abf87b)

**Comment by sguptatw** [comment]
This issue was moved to getgauge/gauge-maven-plugin#30
