### ISSUE TITLE
gauge_specs_dir should be added to the default properties on init

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1057]
**Current behavior**
It is not added to the project, internally it is defaulted to specs

This property is currently not discoverable by the user. If gauge_specs_dir = specs is already present in the default property file, it will be more disoverable

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-24
Commit Hash: 2150e31
```

Related to issue https://github.com/getgauge/gauge-vscode/issues/222

**Comment by nehashri** [comment]
Added to all templates, online and offline installation.
Should be available in gauge >=  30-5-18.
