### ISSUE TITLE
spec file extension is case sensitive

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge#1058]
_From @ocary on May 22, 2018 15:59_

On Windows, the .spec extension is case sensitive.  Files without .spec as the extension are not seen as specs that can be run.  Example:   .Spec instead of .spec

This caused confusion as the IntelliJ plugin sees .Spec as a valid Gauge spec for the plugin, but the run command does not see the file as a spec.

Other OSes have not been tested - I think OS X handles file case sensitivity different than Windows does.

### Expected behavior
Any case combination of .spec will be run by Gauge (EG:  .spec, .Spec, .SPEC, .SpEc, etc) provided the file matches the arguments passed to the run command.

### Actual behavior
Running a spec with a file extension other than .spec, gives _No specifications found in {supplied path to specs}_

If a directory is passed as the spec path, then only specs with extension .spec are run.

### Steps to reproduce
1.  Make a new directory
2.  Run `gauge init java` in the new directory
3.  In new directory\specs, copy example.spec to example2.Spec
4.  Open a command prompt to the new directory
5.  Run _gauge run specs\example2.Spec_
6.  Observe message _No specifications found in specs/example2.Spec._

### Gauge version
```
Windows7 Enterprise - Service Pack 1

Gauge version: 0.9.7
Commit Hash: bc9784c

Plugins
-------
csharp (0.10.3)
flash (0.0.1)
html-report (4.0.3)
java (0.6.6)
json-report (0.2.1)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.1.nightly-2018-05-07)```


_Copied from original issue: getgauge/gauge-java#158_

**Comment by BugDiver** [comment]
_From @ocary on May 22, 2018 16:0_

Interestingly, the filename part of the file does not appear to be case sensitive.   Example.spec and EXAMPLE.spec will run successfully.

**Comment by BugDiver** [comment]
_From @ajoecker on May 22, 2018 17:41_

to my surprise this seems normal windows behavior. Changing the exentions of eg. `doc` to `DOc` or `dOC` etc does not make it ignorant to the respective programs (in this case word).

btw this is a `gauge` project issue, not the runner

**Comment by Apoorva-GA** [comment]
should be available in gauge nightly>=31/05/18

**Comment by sguptatw** [comment]
**Question**
What is the expected behavior on VSCode. Currently the file associations are only for .spec.

**Comment by sguptatw** [comment]
Casing matters for [VSCode file associations](https://code.visualstudio.com/docs/languages/identifiers)
