### ISSUE TITLE
Gauge Processes still alive after closing/completing gauge tasks

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1059]
**Expected behavior**
All related process should be killed after closing/completing gauge actions

**Actual behavior**
Process `gauge`, `python`, `NodeJS` are around even after closing all terminals and IDEs

**Steps to replicate**
* Yet to find the pattern

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-23
Commit Hash: 2150e31

Plugins
-------
js (2.3.1.nightly-2018-05-23)
python (0.3.3.nightly-2018-05-23)
```

**Comment by sriv** [comment]
Is this still relevant @sguptatw ?

**Comment by sguptatw** [comment]
Have not seen this for a while now
