### ISSUE TITLE
The generated annotation text placeholders should not use values

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1061]
**Expected behavior**
Place holder names should be generated for the annotation text.

**Current behavior**
The values provided by the user is being used directrly

**Steps to replicate**
* Create a new `gauge-js` project
* Refactor a step and add a new parameter
> The generated step annotation has values that is entered by the user. 
Note: This value remains in code even when user changes/removes it from the specification

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-24
Commit Hash: 2150e31

Plugins
-------
js (2.3.1.nightly-2018-05-24)
```

**Comment by nehashri** [comment]
This doesn't seem to break the user flow/experience. Hence de-prioritizing this

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
