### ISSUE TITLE
Refactoring a step in specification file should retain the cursor position on IDE

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1062]
**Actual behavior**
Refactoring a step takes the user to the last position

**Steps to replicate**
* Create a `gauge-js` project
* Rename a step
> The cursor position is now the last line of the file

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-24
Commit Hash: 2150e31

Plugins
-------
js (2.3.1.nightly-2018-05-24)
```
Related to https://github.com/getgauge/gauge-vscode/issues/81

**Comment by BugDiver** [comment]
Should be available in nightly >= 2018-06-19

**Comment by sguptatw** [comment]
Blocker https://github.com/getgauge/gauge/issues/1094
