### ISSUE TITLE
Refactoring a concept with a file parameter is replacing the contents of the file as placeholder name

### ISSUE THREAD

**Issue by shubhamsc** [getgauge/gauge#1063]
_From @sguptatw on May 26, 2018 11:48_

**Expected behavior**
The placeholder name should be independent of the value

**Actual behavior**
It is being replaced with the value

**Steps to replicate**
* Create a file 'something.txt`
```
sfsdf
sdfsdf
sdfsdf
```
* Create a new concept with `a new concept`
* Refactor the concept to `a new concept <file:... the new file>
> The concept name now has the contents of the file

This is applicable to any value being passed.
The value name should not be used

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-24
Commit Hash: 2150e31

Plugins
-------
js (2.3.1.nightly-2018-05-24)
```

_Copied from original issue: getgauge/gauge-js#155_

Related to https://github.com/getgauge/gauge-vscode/issues/81

**Comment by shubhamsc** [comment]
Contents of text file are not showing  in concept args,
 it's replaced with arg0.

**Comment by sguptatw** [comment]
The parameter placeholder is the path of the file name and not the placeholder arg0.
This is causing an error `Concept Heading can have only Dynamic parameters`

**Comment by sguptatw** [comment]
This is an issue on concept creation - tracking this as a part of https://github.com/getgauge/gauge/issues/1071
