### ISSUE TITLE
Creating a concept with file parameter should generate a valid header

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1071]
**Expected behavior**
When a concept is implemented, the header should not have issues

**Actual behavior**
Getting `Concept Heading can have only Dynamic parameters`

**Steps to replicate**
* Create a `gauge-js` project
* Create a file something.txt
* create a step `something with <file:something.txt>`
* implement a concept
> The concept header has the above error

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-29
Commit Hash: 1a15b83
```

**Comment by sguptatw** [comment]
The issue is similar when <table:something.csv> is used.

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge nightly >= 31/05/18
