### ISSUE TITLE
Bad character in comment breaks Python parsing

### ISSUE THREAD

**Issue by opendragon** [getgauge/gauge#1074]
### Expected behaviour
A simple step should execute.

### Actual behaviour
The Python plugin fails to parse code containing a comment with a special character in it.

### Steps to reproduce
1. Create the following specification file:
[001_short_test.spec.txt](https://github.com/getgauge/gauge/files/2073833/001_short_test.spec.txt)
2. Create the following Python file:
[Funcs.py.txt](https://github.com/getgauge/gauge/files/2073808/Funcs.py.txt)
Note the special character in the comment.
3. Run gauge against the specification file.

### Gauge version
Gauge version: 0.9.9
Commit Hash: 8db625f

Plugins
-------
go (0.1.2)
html-report (4.0.4)
java (0.6.7)
js (2.3.0)
json-report (0.2.2)
python (0.3.2)
ruby (0.5.0)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)

**Comment by BugDiver** [comment]
This issue was moved to getgauge/gauge-python#86
