### ISSUE TITLE
Gauge 0.9.9 Failed to update plugins

### ISSUE THREAD

**Issue by pustelnik** [getgauge/gauge#1075]
After update from Gauge 0.9.7 to Gauge 0.9.9 gauge fails to update any plugins. (environment behind proxy, before gauge update, updating plugins worked as expected).

gauge update -a
Failed to update plugin 'html-report'.
Reason: Invalid plugin. Could not download html-report-install.json file.
Failed to update plugin 'java'.
Reason: Invalid plugin. Could not download java-install.json file.
Failed to update plugin 'screenshot'.
Reason: Invalid plugin. Could not download screenshot-install.json file.
Failed to update plugin 'spectacle'.
Reason: Invalid plugin. Could not download spectacle-install.json file.
Failed to update plugin 'xml-report'.
Reason: Invalid plugin. Could not download xml-report-install.json file.
Error ----------------------------------

Failed to update 'html-report, java, screenshot, spectacle, xml-report' plugins.

Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
        windows, 0.9.9, 8db625f
        html-report (4.0.4), java (0.6.6), screenshot (0.0.1), spectacle (0.1.0), xml-report (0.2.0)

### Expected behavior
java plugin should be updated

### Actual behavior
Nothing was updated

### Steps to reproduce
1. Update gauge 0.9.7 to gauge 0.9.9
2. Run "gauge update -a"

### Gauge versionGauge version: 0.9.9
Commit Hash: 8db625f

Plugins
-------
html-report (4.0.4)
java (0.6.7)
screenshot (0.0.1)
spectacle (0.1.0)
xml-report (0.2.0)

**Comment by BugDiver** [comment]
@pustelnik  IF you are behind a proxy make sure you have set the `HTTP_PROXY` env variable. Please refer to [documentation](https://docs.gauge.org/latest/configuration.html#http-proxy).

**Comment by pustelnik** [comment]
@BugDiver I've HTTP_PROXY and HTTPS_PROXY env variables set as described in documentation. Problem occurs on my Windows and Linux systems. With Gauge 0.9.7 it worked without problems with my proxy settings.

**Comment by pustelnik** [comment]
@BugDiver gauge config gauge_repository_url returns https://
downloads.getgauge.io/plugin. Curl request to https://downloads.getgauge.io/plugin is successful:
curl -i -X GET https://downloads.getgauge.io/plugin/java.json

I get a json file HTTP/1.1 200 OK
Date: Thu, 07 Jun 2018 13:18:08 GMT
Server: Apache
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
ETag: "8ae114ed7a96ea1fd673c6b0551e42b71af0869a"
Content-Type: text/plain; charset=utf-8
Cache-Control: max-age=300
X-Geo-Block-List:
X-GitHub-Request-Id: A642:544C:4E0643B:51B03BC:5B19308F
Content-Length: 35262
Accept-Ranges: bytes
Via: 1.1 varnish
X-Served-By: cache-sjc3649-SJC
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1528377488.237261,VS0,VE20
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 543e47b00868b607318b714aa2856d8da2759ef7
Expires: Thu, 07 Jun 2018 13:23:08 GMT
Source-Age: 0
Via: 1.1 downloads.getgauge.io
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

{
    "name": "java",
    "description": "Java language runner for gauge",
    "versions": [
        {
            "version": "0.6.8",
            "gaugeVersionSupport": {
                "minimum": "0.9.0",
                "maximum": ""
            },

            "install": {
                "windows": [],
                "linux": [],
                "darwin": []
            },
....

curl request to java-install.json fails:
HTTP/1.1 200 Connection established

HTTP/1.1 404 Not Found
Date: Thu, 07 Jun 2018 13:20:13 GMT
Server: Apache
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 1ADA:9CC1:3A5CEC2:3DE72C0:5B19310D
Content-Length: 15
Accept-Ranges: bytes
Via: 1.1 varnish
X-Served-By: cache-sjc3642-SJC
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1528377614.671897,VS0,VE110
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: fbe3437c127aeee1ed2acaf8d29dd03e9ed6d40c
Expires: Thu, 07 Jun 2018 13:25:13 GMT
Source-Age: 0
Via: 1.1 downloads.getgauge.io
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Content-Type: application/json

**Comment by BugDiver** [comment]
@pustelnik Gauge uses `https://downloads.getgauge.io/plugin/java.json` URL to get the version descriptions, And you are able to `curl` it and get the contents. I'm not quite sure why it is not able to update the plugins :(.

Can you run the `gauge update` command with debug logs and see if you find something which can help us?
To enable debug logs, run `gauge update <plugin-name> -l debug` .

Meanwhile, you can try to download the plugin from the GitHub release (https://github.com/getgauge/gauge-java/release for java) and perform an offline installation.

**Comment by pustelnik** [comment]
@BugDiver I've updated my plugins using release files. For now it's enough, but it would be good for future to have online update :)

gauge update java -l debug

Gathering metadata for java
Failed to download java-install.json file: Get https://downloads.getgauge.io/plugin/java?l=&p=html-report,java,screenshot,spectacle,xml-report&o=windows&a=amd64: proxyconnect tcp: tls: oversized record received with length 20527
Failed to update plugin 'java'.
Reason: Invalid plugin. Could not download java-install.json file.

**Comment by pustelnik** [comment]
I'm still unable to update with Gauge 1.0.0. Curl is working without problems but "gauge update java -l debug" output is same as before:

Gathering metadata for java
Failed to download java-install.json file: Get https://downloads.getgauge.io/plugin/java?l=&p=html-report,java,screenshot,spectacle,xml-report&o=windows&a=amd64: proxyconnect tcp: tls: oversized record received with length 20527
Failed to update plugin 'java'.
Reason: Invalid plugin. Could not download java-install.json file.

**Comment by sriv** [comment]
Thanks for the update, glad you got this sorted.
