### ISSUE TITLE
cannot find concept definition file outside working directory

### ISSUE THREAD

**Issue by lchrennew** [getgauge/gauge#1078]
### Expected behavior
The concept definition should be found when I specified "gauge_specs_dir" to an outside directory
![image](https://user-images.githubusercontent.com/1522365/41274771-322d822e-6e51-11e8-9803-7c1dbad202d2.png)
![image](https://user-images.githubusercontent.com/1522365/41274793-491dde84-6e51-11e8-8b3a-9f5d410bf74a.png)

### Actual behavior
The concept definitions cannot be found.

### Steps to reproduce
1. Create a maven-gauge-java project under `$/dir0/`  and configure `gauge_specs_dir = $/dir1/`
2. Implement a Step named `Say Hi`
`    @Step("Say Hi")
    public void sayHi() {
        // do nothing
    }`
3. Create a cpt file named `1.cpt` and a spec file named `1.spec` under `$/dir1/`
4. Define a concept in `1.cpt`
`# Do something`
`* Say Hi`
5.  Define a Scenario in `1.spec`
`# Some Scenarios`
`## Scenario1`
`* Do something`
6. under "$/dir0/" and execute command `gauge run $/dir1/1.spec`

### Gauge version
```
0.9.9
```

**Comment by sguptatw** [comment]
Thanks for your interest in gauge.

Currently, the `gauge_specs_dir` is used to configure where the `specifications` can be defined and `not concepts`.

Can you tell us more about your use-case.

PS: Though gauge_specs_dir allows directories outside the current working directory, it is recommended to have the specifications within the current project directory.

**Comment by lchrennew** [comment]
My use-case is to implement a suite of DSL to invoke http web api, so that testers could 
1. write api tests in markdown & DSL instead of java. 
2. write api invokes in markdown & DSL into conceptions in order to reference them in UAT spec files.

**Comment by jbadeau** [comment]
what about using git submodule

**Comment by knysh** [comment]
Hi there
I also faced a similar issue.
I have a project with several modules (java), so some of them contain the duplicates of concepts now and I would like to move them to some common module.

When I did it, I got an error that steps are not implemented.

**Comment by nikolaishields** [comment]
Hello!
I have encountered this same issue where there is different behavior between specifying a given specs directory with the gauge_specs_directory with an arbitrary path. It would really be great if we could ensure that the same functionality when defining arbitrary specs directories.
As an added inconvenience it doesn't function when symlinking directories into default locations either.
Let me know how I can help resolve this issue.

**Comment by BugDiver** [comment]
@nikolaishields I can replicate this issue. We will try to fix it very soon.
