### ISSUE TITLE
CSV files are not moving to desired resource directory when using before_suite or before_scenario

### ISSUE THREAD

**Issue by florinalex24** [getgauge/gauge#1083]
Related to
getgauge/gauge#586

> sriv commented on Mar 7, 2017
@aredz - you need to have a dummy csv_path file present, else gauge is unable to parse the spec file.
Just to summarize:

> keep a .csv file in the location you desire, (this need not have the actual data you need)
In BeforeSutie hook move the csv from the location you desire to this path.
Specs can continue to refer to <table:csv_path>
This should work, please post back if you have issues.

Ok, so i have multiple environments with multiple resource files and I need to run the scenarios based on the given environment
EX:
`resources/dev/data.csv`
`resources/dev/other.csv`

`resources/local/data.csv`
`resources/local/other.csv`
.........................................
### Steps to reproduce

1. `Add different parameters from <table:resources/current_env/data.csv>` - i'm using the csv files as a step parameter
2. Create a directory to store environment resources (dev, local, production ...)
2. `Create a current_env directory with some dummy data`
3. in @before_suite (tried also @before_scenario) i'm copying the files from the env (dev, local,...) to current_env

### Actual behavior
So the problem is that, instead of having the data from the selected environment, i have the dummy data. After the second run of the tests, the correct files are loaded (the copy operation is made after the files are read)
The same test fails also if changing between envs

If first i run the tests for Dev env and after that i'm running the tests for Local env, the content is taken from Dev env not from the Local Env
It seems that the files are loaded before @before_suite

### Expected behavior
The resource files should be read after they are copied to resource directory 

### Gauge version
> Name:
 getgauge
Version: 0.3.2
Summary: Enables Python support for Gauge
Home-page: https://github.com/getgauge/gauge-python
Author: Gauge Team
Author-email: getgauge@outlook.com
License: MIT
Location: /home/usera/automation/venv_api_tests/lib/python3.5/site-packages
Requires: protobuf, ptvsd, redBaron, grpcio
Required-by: 

> Gauge version: 0.9.9
Commit Hash: 8db625f

> Plugins
> -------
>flash (0.0.1)
html-report (4.0.3)
python (0.3.2)
screenshot (0.0.1)
spectacle (0.1.2)

**Comment by vinodbhardwaj1** [comment]
Hi Team,
Any workaround for the time being to refresh loaded csv data  ??

**Comment by zabil** [comment]
Please refer issues linked to this on reasons why Gauge won't support this feature.
