### ISSUE TITLE
Find Usage statistics should not have references to deleted files

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1084]
**Expected behavior**
If a file is deleted/renamed the usage statistics should show only the latest references.

**Actual behavior**
The statistics shows the deleted file statistics as well

**Steps to replicate**
* Create a new `gauge-js` project
* Create a new concept in a new file
* Add a step
* Implement the step
* Check the usage of the step
* Goto the specification
* Rename the concept file
* Check the usage of the step used in the concept again
> The usage shows the new/old name. Delete the concept file. This still shows the reference of the deleted file

**Version**
```
Gauge version: 0.9.9.nightly-2018-06-13
Commit Hash: d728b62
```

**Comment by sguptatw** [comment]
The usage statistics displayed on concepts also have a similar issue

**Steps to replicate**
* Create a new `gauge-js` project
* Create a step `ConceptOne`
* Implement it as a concept
```
# ConceptOne
* ConceptTwo
```
* Implement the step `ConceptTwo` as a concept in the `same file`
```
# ConceptTwo
* ConceptThree
```
* Implement `ConceptThree` as a concept in a different file
* Rename  both the concept files
* Check the usages of concept `ConceptTwo`. Clicking on the reference opens the deleted concept file.

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge nightly >= 14/06/18
