### ISSUE TITLE
List command should list scenarios with same name

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#1090]
From @sguptatw 

### Expected behavior
The same scenario name can be used in multiple specs. It should not be listed just once.
Scenarios should be listed grouped by specs.

### Current behavior
Currently gauge list --scenarios lists same scenario name in multiple specs is listed only once.

This issue is part/ child of #1007

**Comment by ajoecker** [comment]
can you align this with @zabil 

from the original issue https://github.com/getgauge/gauge/issues/1007 the proposa was to have "Alphabetically sorted and unique list"

**Comment by zabil** [comment]
@sguptatw 

The current behavior of alphabetical unique sorting is fine. 
Grouping by scenarios by spec is similar to output of `dry-run` https://github.com/getgauge/gauge/issues/655
