### ISSUE TITLE
Fix broken link in README.md

### ISSUE THREAD

**Issue by edilsonalves** [getgauge/gauge#1093]
Gauge Badge link is broken.

[![Gauge Badge](https://gauge.org/Gauge_Badge.svg)](https://gauge.org)
```
[![Gauge Badge](https://gauge.org/Gauge_Badge.svg)](https://gauge.org)
```

**Comment by zabil** [comment]
Pushed https://github.com/getgauge/gauge.org/commit/144ecb4f812a5ed065a96476fee1cfbd45512908 to fix this
