### ISSUE TITLE
Refactoring a nested concept is creating a new concept with the new name

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1094]
**Expected behavior**
It should just change the concept name

**Actual behavior**
The step is getting changed to a new concept

**Steps to replicate**
* Create a new `gauge-js` project
* Create a new step implementation for step `something`
* Create a new conceptfile concept.cpt
```
# concept1 <ABC>
* something
* concept2

# concept2
* something
```
* Use `concept2` in specification
* Refactor `concept2` to something else
> Check the file concept.cpt. This now has a duplicate concept error

**Version**
```
Gauge version: 1.0.1.nightly-2018-06-19
Commit Hash: 583ef1d

Plugins
-------
html-report (4.0.5.nightly-2018-05-14)
js (2.3.2.nightly-2018-06-19)
```
Blocks #1062

**Comment by BugDiver** [comment]
The Fix should be available in nightly >= 27 June 2018
