### ISSUE TITLE
Request some new features

### ISSUE THREAD

**Issue by lchrennew** [getgauge/gauge#1095]
# Feature 1:
Context Steps in spec level, e.g:
```
# my spec
### this is a spec context step just run once

* this is a scenario context step

## scenario1
* step1

## scenario2
* step2
___
* this is a tear down step
```

Expected execution:
```
Start "my spec"
1. ### this is a spec context step just run once
Start "## scenario1"
2. * this is a scenario context step
3. * step1
Start "## scenario2"
4. * this is a scenario context step
5. * step2
Start tear down
6. * this is a tear down step
```
If only run scenario1, the expected execution is:
```
Start "my spec"
1. ### this is a spec context step just run once
Start "## scenario1"
2. * this is a scenario context step
3. * step1
Start tear down
4. * this is a tear down step
```

# Feature 2
 (java) Custom interceptors for step implementations' invocations
There's no way to intercept step invocations now. For some reason, I need to intercept step invocations to do some pre/post-processes to the arguements to be passed into the methods.

 # Feature 3
Extensible special parameters
There are two build-in special parameters now(<file:> & <table:>) by now, but I need some other special parameters customized by myself.

**Comment by lchrennew** [comment]
For feature 1:
If only run scenario1, the expected execution is:
```
Start "my spec"
1. ### this is a spec context step just run once
Start "## scenario1"
2. * this is a scenario context step
3. * step1
Start tear down
4. * this is a tear down step
```

**Comment by ajoecker** [comment]
i would suggest to open a ticket per feature request, makes commenting and discussing and even more tracking easier and feasible

**Comment by nehashri** [comment]
@lchrennew 
For Feature 1,
You may be looking at something similar to [this issue](https://github.com/getgauge/gauge/issues/805). Please add your view on the approach suggested.

For Feature 2,
Please let us know what kind of pre/post process you would like to do on the method arguments. A sample example would be useful to understand this
PS: Please raise that as another issue. It would be easier to track smaller issues with one feature request.

For Feature 3,
There is already a custom parameter parser in Java. You can refer [this](https://github.com/getgauge/gauge-java/issues/140) issue for more details. A sample example is project can be found [here](https://github.com/BugDiver/custom_parser_sample). 
If you are looking for something similar in another language, please raise a request in the corresponding repository.

**Comment by nehashri** [comment]
I am closing this issue. Please raise separate issues (or add comments on issues pointed out) for further discussion.
