### ISSUE TITLE
New feature: dynamic data driven tests

### ISSUE THREAD

**Issue by MolineroUA** [getgauge/gauge#1096]
It would be great to have ability to use table data and have result representation not like a table result, but the separate tests. And also each test will have unique name generated dynamically. It will be something similar to [Spock data driven test with @Unroll annotation](http://spockframework.org/spock/docs/1.1/all_in_one.html#_method_unrolling).

>@Unroll
>def "Should open game #gameName"() {
> loginFrom(clientType);
> openGame(gameName);
> where:
> gameName << ["Farm Fortune", "Cleopatra"]
> clientType << ["Facebook Web", "Android"]
>}

_How specification will look:_
># Games verification
>     |gameName    |clientType  |
>     |------------|------------|
>     |Farm Fortune|Facebook Web|
>     |Cleopatra   |Android     |
>
>## Should open game \<gameName\>
>* User logins from client \<clientType\>
>* User opens game \<gameName\>

_How report will look:_
>Should open game "Farm Fortune"
>- User logins from client "Facebook Web"
>- User opens game "Farm Fortune"
>
>Should open game "Cleopatra"
>- User logins from client "Android"
>- User opens game "Cleopatra"

**Comment by FerryOPT** [comment]
Many test suites are just combinations of input data and the test steps of different test cases are actually identical.
I suggest to support data driven testing like below.  Every row in this table are treat as separate case, and they could be executed parallelly just like the regular step based test cases. In the report they also be counted as separated cases.
`# Data driven test
| Test Case No. | condition 1| condition 2| condition 3 | condition4 |
| ----------------| ------------| -------------| -------------| -------------|
|  1                    |   a              |        b          |      c            |         d         |
|  2                    |   b             |        a        |      d            |         c         |
|  3                    |   c              |        d         |     b            |         a         |
|  4                    |   d              |        c          |      a            |         b       |

* test step against condition 1
* test step against condition 2
* test step against condition 3
* test step against condition 4`

**Comment by jbadeau** [comment]
This feature is very important for looking at test reports and understanding at a glance what row(s) failed. Any update on this?

**Comment by nehashri** [comment]
@jbadeau @FerryOPT @MolineroUA This is currently not possible. However, it looks like an enhancement that can be done on Gauge so that reports can be read better. 

However, this is not quite feasible at a specification level, but maybe possible at a scenario level.

Is readability on the reports the only advantage you see? Is there any other advantage you see?

**Comment by jbadeau** [comment]
Yes, reporting on the scenario would be sufficient for me.

**Comment by nehashri** [comment]
@jbadeau Any other advantage you see with this feature request, it will help us prioritise this issue.

**Comment by jbadeau** [comment]
Well there are 2 features here.

.1 This issue which is an enhancement to the dsl and allows for parameterized scenarios. This would be very useful and a big plus over cucumber. High priority but also complex
2. Update reporting to provide more info on data passed to scenarios. Very high priority as data driven scenario reporting is “almost” useless for a human.

**Comment by nehashri** [comment]
@jbadeau The reports do point to the data row which failed the scenario. So you can see the failure according to the data passed. (In case you haven't noticed, clicking on the data row shows the scenarios and steps according to that data row).

Having dynamic scenarios makes the scenario non deterministic. Hence, we have decided not to implement this.
