### ISSUE TITLE
Add support for Internet Proxy Settings

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#110]
Some users are behind an internet proxy and the plugin install fails because of this.

Add support to allow Gauge to pass the proxy username/password while doing a `wget` for 

- The plugin's `install.json`
- The plugin artifact.

While setting `http_proxy` environment variable can tell Gauge (and in turn `wget`) the proxy settings to use, there needs to be a mechanism to encrypt/set it such that the credentials are not plain text.

**Comment by vishnukarthikl** [comment]
We actually try to use wget, curl and go itself to download the plugin in that order, so we should handle them as well.
