### ISSUE TITLE
file parameter inside the table should show diagnostic error if file not found

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1102]
**Expected behavior**
If the file is not available, the diagnostic error should be displayed

**Actual behavior**
File parameter inside the table does not show diagnostic error

**Steps to replicate**
* Create a gauge-js project
* Add a step with table. In the value use a file parameter value that does not exist
> The diagnostic error should be displayed

**Version**
```
Gauge version: 1.0.1.nightly-2018-06-27
Commit Hash: 0e3c1fc
```
Blocks #1006

**Comment by sguptatw** [comment]
If the user tries to execute the spec with invalid file parameter inside a table, the execution hangs.

**Comment by shubhamsc** [comment]
The fix should be available in nightly >= 23-07-2018
