### ISSUE TITLE
Allow --env to accept multiple environments

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/gauge#1109]
In our projects, we are using [Gauge environments (`--env`)](https://docs.gauge.org/latest/configuration.html#environments) to set different variables. However, we have been frustrated by the fact that you can only use one environment. We would like to be able to choose more than one.

For instance, we need to specify:

 - The web browser to test on
 - The environment to test on
 - Whether or not to use experimental features

### Expected behavior
We would like to be able to have subfolders of `env` for each of these things we need to specify, like so:

 - `chrome`
 - `firefox`
 - `devServer`
 - `testServer1`
 - `testServer2`
 - `experimental`

Then we would like to be able to multiple environments. So for example, we might call:

    > gauge run --env "chrome, devServer, experimental" specs

And then it would load first the `chrome` environment folder, then the `dev`, then `experimental`, and finally the `default` environment folder and the rest of the ones in the normal load sequence.

### Actual behavior
There is no syntax that allows this and only one environment can be loaded. Therefore, we have to create composite environments in our `env` folder like so:

 - `chrome_devServer`
 - `chrome_devServer_experimental`
 - `chrome_testServer1`
 - `chrome_testServer1_experimental`
 - `chrome_testServer2`
 - `chrome_testServer2_experimental`
 - `firefox_dev`
 - `firefox_dev_experimental`
 - ...and so on

### Gauge version
```
Gauge version: 1.0.0
```

**Comment by sriv** [comment]
related: https://github.com/getgauge/gauge/issues/510. @Thunderforge , please feel free to add to the existing discussion as well. Thanks.

**Comment by Thunderforge** [comment]
@nehashri What does the [community] label mean?

**Comment by ajoecker** [comment]
who wins when different env have the same properties ? First come, first serve?

**Comment by Thunderforge** [comment]
> who wins when different env have the same properties ? First come, first serve?
@ajoecker Yes, I presume first come, first serve would be the best way. That's pretty much how it is right now, where any properties in an environment take precedence over default.

**Comment by NivedhaSenthil** [comment]
@Thunderforge community label is added to issues created for support from the gauge community, which will enable us to better track and priorities support.

**Comment by sriv** [comment]
Merging discussions from https://github.com/getgauge/gauge/pull/1137

@sriv [proposed](https://github.com/getgauge/gauge/pull/1137#issuecomment-410113169):

> Perhaps have composable environments, so that
> `foo_bar` would contain `foo` `union` `bar` + extra if needed. We still need to explore which takes precedence, but you get the idea.
> Some benefits (IMO) : 
> -  the meta environments are also part of the project (i.e. checked in with tests) and can be replicated to other machines.
> - allow extra properties to be defined (or even override property explicitly)
>
> #### Example
> Say the project's `env` looks like this:
>
> ```
> env
> ├── bar
> │   ├── default.properties
> │   └── java.properties
> ├── default
> │   ├── default.properties
> │   └── java.properties
> ├── foo
> │   ├── default.properties
> │   └── java.properties
> └── foo_bar
>     └── inherited.properties
> ```
> 
> And the `foo_bar/inherited.properties` looks like this:
> 
> ```
> # include foo
> # include bar
> 
> i_am_a_new_property = hello
> ```
> 
> Then `gauge run specs --env=foo_bar` should use the properties specified in `foo` and `bar`, as well as the new `i_am_a_new_property`

@ajoecker commented:

> First, naiv thought.... if I look at the original issue, Thunderforge complains, that they must create additional folders/files to have a combination of environments available.
> 
> With your solution, I do not see a gain from that. If I want to combine `bar` and `foo`, I would again need to have additional work to do so. 
> If you again look at Thunderforge's example, where he combines a lot of several environments, it would mean for each combination to have a union folder with different includes etc ?
>
> Maybe I do not see the idea behind that right now, but to be able to combine on the fly, without much additional work, this does not seem so appealing.
> 
> I dont say that the idea in general is bad, this might be a interesting thought, but it does not help for this problem in my eyes (@Thunderforge might be able to add more to this ?!)

**Comment by zabil** [comment]
> With your solution, I do not see a gain from that. If I want to combine bar and foo, I would again need to have additional work to do so.

I agree with this. It's more useful to make it a run-time combination that specifying it before hand. 

Also is this
```
# include foo
# include bar

i_am_a_new_property = hello
```
a valid property file syntax?

**Comment by Thunderforge** [comment]
@sriv We are currently doing composite folders (e.g. `foo_bar`, as you suggested) and are not happy with that solution. We would like runtime composite environments. In one project, we have five browsers we need to test (choose one), three environments (choose one), and an optional "experimental" flag. 

Since you must choose one browser and one environment, but may or may not include the experimental flag, we have `5 x 3 x 2= 30` combinations. If Gauge were to allow runtime composite environments (e.g. `> gauge run --env "chrome, devServer, experimental" specs`), then we have nine folders. Easy.

If we use composite folders as you are suggested, then we need 30 folders. That's a nightmare to maintain. If we want to change a property for Chrome, we have to change it in multiple folders.

**Comment by sriv** [comment]
I see, thanks for explaining the scenario @Thunderforge. I guess we will go with @ajoecker's PR then.

**Comment by sguptatw** [comment]
Updating the Documentation will be tracked as a part of getgauge/docs.gauge.org#92

**Comment by haroon-sheikh** [comment]
@ajoecker unless I’m missing something here. Surely, I want second environment to override first which overrides default. Is that what’s implemented?

**Comment by haroon-sheikh** [comment]
Also why did we decide for comma separated envs over passing in multiple `—env` which is much nicer and standard way of doing something similar?
