### ISSUE TITLE
Rerun with -Dflags="-f" trigger tests with previous parameters if @AfterSuite fails

### ISSUE THREAD

**Issue by olejkavn** [getgauge/gauge#1110]
I have some cleanup actions in @AfterSuite if it is fails rerun triggered with same parameters as usual run.

### Expected behavior
Rerun should be triggered with parameters frome failures.json if some actions in @AfterSuite fails

### Actual behavior
Tests triggered with same parameters 

### Steps to reproduce
1. mvn gauge:execute
2. make some broken test and set something like assert false in @AfterSuite
3. mvn gauge:execute -Dflags="-f"

as result will be rerun of all executed tests instead of broken test

### Gauge version
```
Gauge version: 0.9.9
Commit Hash: 8db625f

Plugins
-------
html-report (4.0.4)
java (0.6.8)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

**Comment by olejkavn** [comment]
@NivedhaSenthil Hi, where we can place some not scenario/spec specific rollback steps?
Here is my case:
1)I have suite with 50 spec(3 of them flaky)
2)For one of my test I have broken data, and I make call to this broken data in rollback
3)All broken tests reruns due to fail of rollback

**Comment by nehashri** [comment]
@olejkavn You can also consider using `@afterScenario` to clean up your data. Or have a look at [tear down steps](https://docs.gauge.org/latest/writing-specifications.html#tear-down-steps) which can do any cleanup needed. 
In both the cases, as well as the one mentioned by @NivedhaSenthil ensure that only those flaky tests fail.

**Comment by olejkavn** [comment]
@nehashri I can't use it in such case, becasue I want to do bulk rollback in multithread tests
Few scenario/specs can change one entity in my environment, so if i will perform rollback for one of them in multithread tests, I can catch some concurency issues, thats why I preffer to do it in AfterSuite

**Comment by nehashri** [comment]
@olejkavn It is not recommended to use `@beforeSuite` and `@afterSuite` hooks to perform tasks which can affect multiple tests when running in parallel.
Both the hooks are executed once per parallel stream that is started. (i.e., if your tests run in two parallel threads; the hooks are executed twice, once in each thread). Are you sure that the reason for the hook failing is not because of this?

**Comment by olejkavn** [comment]
@nehashri but we add synchroinzation for those tasks)
counter for threads and last executed thread execute this method in @AfterSuite
so from this side it's ok for us
