### ISSUE TITLE
Should honor the debug level mentioned in the current command

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1112]
**Actual behavior**
Running command with -l debug and switching to info is not working as expected

**Steps to replicate**
* `gauge run specs -l debug` with a failing test
* `gauge run --failed`
* `gauge run --failed -l info`
> Debug information is still printed.

**Version**
```
Gauge version: 1.0.1.nightly-2018-07-09
Commit Hash: 72109fa
```
Blocks #1009

**Comment by sriv** [comment]
Is this expected for `--repeat` as well?
i.e. should I be able to override the log level when running `gauge run --repeat` ?

**Comment by sguptatw** [comment]
Yes this is applicable to repeat as well.

**Comment by sguptatw** [comment]
For maven, the following command can be used
`mvn gauge:execute -Dflags="--failed,-l=debug"`
