### ISSUE TITLE
Gauge appears to freeze when an alert triggered by window.onbeforeunload is present

### ISSUE THREAD

**Issue by Tyler-Wayman** [getgauge/gauge#1115]
### Expected behavior
Gauge should be able to handle any alerts that are opened by the browser

### Actual behavior
A number of options are available through Selenium that should allow interaction with any alert that is opened by the browser.  None of these appear to be viable through the Gauge platform because as far as I can tell Gauge seems to freeze after an alert triggered by window.onbeforeunload is opened.
The alert has the title "Leave site?", the message "Changes you made may not be saved", and the buttons to "Leave" or "Cancel"
The error in the gauge report indicates:
--------------------------------------------
unexpected alert open: {Alert text : }
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.15063 x86_64)
--------------------------------------------

### Steps to reproduce
1. Inside the application in test there must be a page for which there is a window.onbeforeunload alert that is triggered.
2.  In my particular application it is closing the page or navigating away from the page where the alert needs to be tested for proper operation.
3.  To make sure that it was Gauge and not the way in which I entered the potential fixes I placed a GaugeMessage immediately after the code which would navigate away from the page.  This GaugeMessage does not fire leading me to believe that Gauge is frozen up waiting for the alert to be dealt with.

### Potential fixes attempted
1 - Including a wait to ensure that nothing else was hanging and preventing Gauge from moving on
2 - new Actions(DriverFactory.Driver).SendKeys(Keys.Return);
3 - DriverFactory.Driver.SwitchTo().Alert().Accept();
4 - sending keys to the body SendKeys(Keys.Return);

### Gauge version
Gauge version: 1.0.0
Commit Hash: 5a99965
-  This issue was also observed in 0.9.7 and 0.9.5.  I was never able to get gauge to interact with this alert.

**Comment by sriv** [comment]
Closing this, ref https://stackoverflow.com/a/51327295/326543
