### ISSUE TITLE
Add acceptable failure rate option to prevent constant execution failure

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#1116]
_From @andrew041 on July 17, 2018 20:26_

Currently, whenever there is a failure in any test, the execution will fail. When conducting UI testing, it is common to have some level of failure that is considered acceptable.

It would be great if an optional flag could be added to set an acceptable failure rate so that if the percentage of scenarios that failed was higher, the build/execution would be marked as a failure, but if it was higher, than it would be marked as passed. 

I believe this change would need to be made in the "GaugeExecutionMojo.java" file around line 118.

_Copied from original issue: getgauge/gauge-maven-plugin#33_

**Comment by sriv** [comment]
This isn't something that would be difficult to implement,  but I would say that this could mask potential issue(s).

Some initial thoughts:

- what is the right percentage (could be configurable, but that would be like code coverage and I don't think we would like gauge to be like that)
- what if the same scenario keeps failing?
- how does one determine that scenario A is a must-pass (crucial flow) whereas scenario B is tolerable?

I mentioned this in [another comment](https://github.com/getgauge/gauge/issues/1092#issuecomment-402340597). If I am testing an app, the principle I'd look at is:

>  if I am a user of the app being tested, would I be ok to retry X times for the feature to work? Most likely not. If that is true for an actual user, I think the same (if not stricter norms) should be expected from the test as well.


Thoughts?

**Comment by andrew041** [comment]
Those are some good points. I think this change would help give a better indicator if there is a critical/system wide issue vs a small portion of the tests failing. The results would always need to be checked to verify any failures, but at least a build would be able to complete and/or Jenkins wouldn't be constantly failing (as we all know how inconsistent Selenium/Appium tests can be) when running a larger test suite. 

I think it should be left to the user to determine the percentage when executing via command line. As long as it is labeled clearly, I don't think people would see it as a code coverage number.

If a scenario keeps failing, I think it would be fine. Maybe at some point there could be a 'test health' report that could be generated to more easily identify frequently failing tests. (And honestly, I think a test that has passed forever and suddenly fails is more concerning than a test that has been failing forever.)

I don't think Gauge should get into marking tests as more important. That could be taken care of by running tests without the suggested percentage passed flag and run their smoke test scenarios.

**Comment by zabil** [comment]
From Gitter chat at https://gitter.im/getgauge/chat?at=5b5846c95301255724c3debe

> My opinion on this is that the tests need to be able to tell you with certainty if the feature works (or not). Masking failures does not solve anything. If I were you, I'd look at fixing the application (and/or tests). Because if your tests can break the feature, it may also be broken for your real users. If fixing is not feasible, quarantine the tests (ex. filter using a tag), run only the tests that will give you guaranteed results, then perhaps manually verify that the feature is OK.

From Gitter chat at https://gitter.im/getgauge/chat?at=5b58a6a9c0fa8016e7381480

> There definitely is a point to saying that all the tests should pass, but I think that way of thought is really only applicable to unit tests. In all the teams I have worked with, there has been an acceptable level of UI and API test failures and QA always reviews a full report before saying a build is acceptable. For DevOps people, I can imagine it would get really annoying seeing a build constantly fail and needing to always look at the run to see if it was just a test that failed, or if there is a system issue. Even if it isn’t ideal, many organizations check the reports regardless and it would be helpful for the devops team to have the feature. Another reason for adding that feature is that it is common to continue running bugged tests for teams using agile and/or continuous integration as an issue can be found in the morning and in the afternoon it may be fixed (plus managers like to see increasing percentages of passing tests and it helps give an idea of how healthy an app is and when a release can happen).
As for quarantining tests, in my opinion, that is a very bad practice as then valid tests are not being run all the time. Plus, the whole point of autmation is to reduce the human interaction with the application and if tests are quarantined, then they would have to be run separately by a person, meaning an app can’t be released automatically.
I have seen some companies with custom dashboards to track all of their tests, keep a history on how they perform, and where they go to see if a build is ready for release. They want a jenkins job to only fail when there is some type of server error or a sudden drop in the pass rate for their tests so a devops person can be notified and investigate immediately.

**Comment by zabil** [comment]
The common theme maybe allowing the user to handle the result of the run. However implementing something like an "acceptable failure rate" is tough. 

How about adding something like

```
$ gauge run specs --report-only
```

To generate a report (without failures). A tester can parse the report(html, xml, json etc) and decide what to do.

**Comment by smathistad** [comment]
We treat the gauge results as "raw data".  We want **ALL** possible data to be collected and available. Then we can process/analyze the results as you see fit.

For example, we have one project where we run 2000+ spec files nightly (multiply that by a number of different browsers/OS versions). After each execution, we parse the xml report file and save the results into a DB.  We then have reports auto-generated from the DB results emailed to the appropriate teams for further analysis.  We generally don't look at whether the build failed or not unless the DB is missing results from the previous night.

I don't mean to sound harsh, but it appears that you want the Gauge team to do some of the "post-processing of data" for you.

**Comment by zabil** [comment]
Closing in favor of https://github.com/getgauge/gauge/issues/1126
