### ISSUE TITLE
Inform the user that we are collecting telemetry data on gauge run

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge#1121]
As telemetry is opt-out inform the user about data collection on every run and provide a configuration to turn the warning off for e.g.

```
$ gauge run specs
INFO: This installation of Gauge automatically sends telemetry data. 
To turn this warning off opt-in or opt out. For more information read https://manpage.gauge.org/gauge_telemetry.html
```

To hide this warning.

```
$ gauge telemetry on
```

or 

```
$ gauge telemetry off
```

or set the environment variable `GAUGE_TELEMETRY_ENABLED`

**Comment by zabil** [comment]
@ajoecker GDPR is not applicable for anonymized date.
Consent is only required when collecting personally identifiable information.

Recital 26 of the Data Protection Directive (95/46/EC) provides that:
 
“…to determine whether a person is identifiable, account should be taken of all the means likely reasonably to be used either by the controller or by any other person to identify the said person… the principles of [data] protection shall not apply to data .rendered anonymous in such a way that the data subject is no longer identifiable…”

**Comment by ajoecker** [comment]
ok - then i would nevertheless advise to have https://manpage.gauge.org/gauge_telemetry.html a bit more concrete about what data exactly is sent to whom etc

**Comment by zabil** [comment]
The page has instructions to see what data and where it's posted

```
$ gauge telemetry log true
```
https://manpage.gauge.org/gauge_telemetry_log.html

Perhaps link to https://preview.gauge.org/2017/07/20/why-we-collect-data/ ?

**Comment by ajoecker** [comment]
yeah i think that would be great to have the link to the second link

**Comment by zabil** [comment]
Fix is available in nightly  >= 30-07-18
