### ISSUE TITLE
Add report mode of execution to Gauge

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge#1126]
## Current behavior

When a spec/scenario fails Gauge fails the entire test suite. On a CI/CD this marks the build red, a feedback to teams about failures. 

However, there are a few cases where teams parse the results of the test run to decide if the suite fails or not.

As discussed here https://github.com/getgauge/gauge/issues/1116

The workaround is adding a wrapper script to  call and handle failure/exit codes by Gauge.

## Expected 

add a new option 

```
$ gauge report-mode
```

This will not fail the build. This allows the user to parse the results of html/xml/json reports and take action.

**Comment by sriv** [comment]
I still feel the flag can be `--no-exit-code` so that it is explicit. `report-mode` semantically indicates that a report is generated, but that is optional, since the project may have no reporting plugin.

**Comment by sriv** [comment]
added via #1151
