### ISSUE TITLE
Not able to execute "gauge run" with multiple tags

### ISSUE THREAD

**Issue by dunk3l** [getgauge/gauge#1131]
### Expected behavior
Execute scenarios labeled with selected tags.

### Actual behavior
Get message: "No specifications found in specs."

### Steps to reproduce
1. Execute command: gauge run --tags tagA,tagB

### Notes:
* tagA (for scenario 1) and tagB (for scenario2) exists and i able to execute tests with each of the tags as well as using a common tag for both scenarios.
* I also tried: gauge run --tags "tagA & tagB" and "tagA, tagB"

### Gauge version
```
Gauge version: 1.0.0

Plugins
-------
csharp (0.10.2)
```

### OS version:
```
Windows NT 10.0.17134.165
```

**Comment by BugDiver** [comment]
@dunk3l Currently `gauge` does not support comma separated tags.
* Executing `--tags="tagA,tagB"` will try find scenarios with `"tagA,tagB"` not `tagA` and "tagB".
* Executing `--tags="tagA & tagB"` will try to find scenarios which are tagged with `tagA` and `tagB` both.

In your case, you might use the `I` operator.
`gauge run --tags="tagA | tagB"`
This will find the scenarios which are tagged with any one of the tags from `tagA` and `tagB`.

**Comment by Apoorva-GA** [comment]
Closing the issue for now. 
Feel free to reopen if you face the issue again.
