### ISSUE TITLE
Should be able to work Gauge IDE features seamlessly

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1132]
**Expected behavior**
Should be able to work with Gauge IDE features seamlessly

**Actual behavior**
Gauge features are not working

**Steps to replicate**
* Create a new project
```
gauge init js
```
* Open the project in the VSCode IDE
> The markdown highlighting, Gauge commands are not available
Things are working as expected with 
```
Gauge version: 1.0.1.nightly-2018-07-27
Commit Hash: fd5cdd2
```

**Version**
```
Gauge version: 1.0.1.nightly-2018-07-31
Commit Hash: 4ae7c9a

Plugins
-------
html-report (4.0.4)
js (2.3.1)
screenshot (0.0.1)
```

**Comment by BugDiver** [comment]
@sguptatw Is this issue still valid?

**Comment by sguptatw** [comment]
Working as expected in
```
Gauge version: 1.0.1.nightly-2018-08-06
Commit Hash: 8281d03

Plugins
-------
html-report (4.0.4)
js (2.3.1)
```
