### ISSUE TITLE
Telemetry message should not be displayed if GAUGE_TELEMETRY_ENABLED

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1133]
_From @sguptatw on August 1, 2018 8:43_

**Expected behavior**
If the env var GAUGE_TELEMETRY_ENABLED is explicitly set, this means the user has explicitly decided about telemetry. Hence the message is not to be shown when the env value is set.

**Steps to replicate**
* Delete the gauge configuration folder
* Set the GAUGE_TELEMETRY_ENABLED value to false
* Install gauge
* gauge version
> The telemetry message is displayed

**Version**
```
Gauge version: 1.0.1.nightly-2018-07-31
Commit Hash: 4ae7c9a
```

Related to https://github.com/getgauge/gauge/issues/1121

_Copied from original issue: getgauge/gauge-csharp#146_

**Comment by sriv** [comment]
Which OS?

**Comment by sguptatw** [comment]
Had a typo in env var. Working as expected.
