### ISSUE TITLE
Goto definition of partial text of multi-line step text should not take the user to the step implementation

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1139]
**Expected behavior**
Goto definition should work only for valid steps.

**Actual behavior**
When the first line of multi-line step is pasted else where in the specification, Goto-definition is still taking the user to the step implementation of the multi-line step. However this is actually an unimplemented step. 

**Steps to replicate**
* Create a `gauge-js` project
* Create a 2-line step. Give the implementation.
* Cut the first line and paste it else where
* Goto definition on the pasted line
> This takes the user to the step definition of the multi-line step

Child of https://github.com/getgauge/gauge/issues/265

**Comment by nehashri** [comment]
@sguptatw this seems to be working as expected now. Please check again.

**Comment by sguptatw** [comment]
Working as expected
```
Gauge version: 1.0.2.nightly-2018-09-10
Commit Hash: 7b588a4
```
