### ISSUE TITLE
Unexpected Failed to start gauge API is displayed sometimes

### ISSUE THREAD

**Issue by texnichnyi** [getgauge/gauge#1146]
Hi guys,
Thanks for gauge framework. I'm using this tool for half a year and like it.
A few days ago during CI integration, I have faced with issue Failed to start gauge API: Timed out connecting to 127.0.0.1:port_number. I wasn't able to reproduce it but today I have faced with the same issue. I started specs by standard command and get the error. After a few seconds, I started the specs again and everything was ok.
![ci_issue](https://user-images.githubusercontent.com/16348425/43902220-2b61041a-9bf2-11e8-86e7-613e791f5d66.png)
![reproduce_issue](https://user-images.githubusercontent.com/16348425/43902221-2b884bc4-9bf2-11e8-819c-d59d1b6f9c44.png)

The question is:
How to fix this issue? Is it depends on internet connection? 
Is it possible to disable calling of API programmatically or by some command?

Gauge version: 1.0.0
Commit Hash: 5a99965

Plugins
-------
html-report (4.0.4)
python (0.3.2)
screenshot (0.0.1)
xml-report (0.2.0)

**Comment by Apoorva-GA** [comment]
Could you please update the gauge version to 1.0.0. You can follow these [instructions](https://docs.gauge.org/latest/installation.html).
Note : Your Environment information in the screenshot you have provided shows gauge version as 0.9.9.

Also please update the gauge-python plugin to the latest. Using commands `gauge install python` and `pip install getgauge` also ensure that the `pip show getguage` shows version 0.3.3.

**Comment by texnichnyi** [comment]
@Apoorva-GA  It's solved. Thanks.
