### ISSUE TITLE
consecutive step and scenarios: incorrect validation

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#1153]
### Expected behavior

For this spec:

```
Specification 1
===============

* step 1
Scenario 1
----------
* step 2
```

The context step is read as `step 1 Scenario 1` and this is ok (ref: #1147)

However, gauge should now throw a parse error stating that the scenario name cannot be empty.
Also, the scenario underline should not be part of the step text.

### Actual behavior

- the scenario underline is also part of the step text now.
- no parse error for scenario

### Steps to reproduce
1. `gauge init js`
2. Copy the content of the above spec into a spec file.
3. `gauge validate specs`
4. Observe the suggested step text in the output. 
5. Note the validation errors do not account for empty scenario names

### Gauge version
```
Run gauge -v on your system and paste the results here.
```

**Comment by sriv** [comment]
Consecutive step and scenario will lead to scenario text being part of step  (multiline). Scenario underline will be treated as a comment. No warnings/errors explicitly for this. 

In the above case:

```
Specification 1
===============

* step 1
Scenario 1
----------
* step 2
```

the step text will be read as `step 1 Scenario 1` and `--------` is a comment. Thus making `step 2` also a context step.

This is consistent with condition like this:

```
## scenario1
-------------
```
where the underlines are taken as comment.

**Comment by sguptatw** [comment]
Getting parse error `Spec should have atleast one scenario`

**Version**
```
Gauge version: 1.0.2.nightly-2018-09-10
Commit Hash: 7b588a4
```

<img width="398" alt="screen shot 2018-09-11 at 10 50 44 am" src="https://user-images.githubusercontent.com/6310197/45339680-3e11e880-b5b1-11e8-856f-56cc7b67f73e.png">

**Comment by sguptatw** [comment]
In the command line however am getting validation errors along with parse error. Since there is a parse error other validation errrors are not displayed in the UI.

Here is the parse error expected?
```
[ParseError] .../work/gauge/FT/gauge-lsp-tests/specs/one.spec:1 Spec should have atleast one scenario => ''
[ValidationError] .../work/gauge/FT/gauge-lsp-tests/specs/one.spec:4 Step implementation not found => 'step 1'
[ValidationError] .../work/gauge/FT/gauge-lsp-tests/specs/one.spec:5 Step implementation not found => 'edit content "" Scenario 1'
[ValidationError] .../work/gauge/FT/gauge-lsp-tests/specs/one.spec:8 Step implementation not found => 'step 2'
```

**Comment by sriv** [comment]
@sguptatw  https://github.com/getgauge/gauge/issues/1153#issuecomment-420151255 is valid. To gauge there is no scenario defined. since it reads the text such that:

- a context step, text: `step 1 scenario 1`
- comment `----------`
- `step 2` is also read as a context

As for [errors](https://github.com/getgauge/gauge/issues/1153#issuecomment-420153388) cli and UI should be consistent, however please check if this works without this change, I suspect this could be an unrelated issue.
