### ISSUE TITLE
Create an npm/yarn installer for Gauge

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge#1157]
### Current behavior

* Install gauge binaries
* Install node and npm
* `gauge init js` which installs a few more npm packages

JavaScript users prefer npm or yarn taking care of the whole installation. Also in some platforms `npm` is not installed by default causing `gauge init js` to fail.

### Expected behavior

* Install node and npm
* `npm install -g gauge-cli` or `yarn global add gauge-cli` 

This must install the gauge binary and the gauge Javascript plugins and the default [Taiko](https://github.com/getgauge/taiko) template project.

**Comment by sriv** [comment]
`npm install @getgauge/cli` should now install gauge in `node_modules/.bin`.

`-g` should install globally.

**Comment by sguptatw** [comment]
**Question**
With gauge installed from within npm it is not available as an independent command. I mean `npm run test` will run gauge if scripts has `gauge run`. However it is not available as an independent command on the command line. How can a user use gauge commands. Something like `disable telemetry` or check `gauge config` or `gauge help` etc?

**Comment by sriv** [comment]
npm `bin` are installed into `node_modules/bin` which is probably not in your `PATH`. This is standard with npm. You can use [`npx`](https://www.npmjs.com/package/npx) to invoke `gauge` to execute binaries installed via npm.

**Comment by sguptatw** [comment]
The installation of npm and yarn work as expected. However Gauge has issues with local installation. Using package manager the gauge version can be locked to a given project. This will however continue to use the latest of the required plugins.
This may have some issues. 
This is tracked as a part of https://github.com/getgauge/gauge/issues/1184.
