### ISSUE TITLE
OSX and IntelliJ - project creation fails

### ISSUE THREAD

**Issue by rogergl** [getgauge/gauge#116]
On OSX with IntelliJ project creation fails with the following error message: 
Error adding module to project: Cold not find executable in PATH or GAUGE_ROOT. Gauge is not installed.

BTW: I installed gauge with brew.

**Comment by prateekbaheti** [comment]
Did you reinstall IntelliJ idea after gauge installation via brew ?

**Comment by rogergl** [comment]
No I just restarted it.

Von:  Prateek <notifications@github.com>
Antworten an:  getgauge/gauge
<reply+00017f28d6d1d8d4e60c5a79ae8977d8777c786e9b107a0e92cf00000001111fac7a9
2a169ce03b6ee15@reply.github.com>
Datum:  Dienstag, 17. März 2015 09:48
An:  getgauge/gauge <gauge@noreply.github.com>
Cc:  Roger Gilliar <roger@gilliar.de>
Betreff:  Re: [gauge] OSX and IntelliJ - project creation fails (#116)


Did you reinstall IntelliJ idea after gauge installation via brew ?

‹
Reply to this email directly or view it on GitHub
<https://github.com/getgauge/gauge/issues/116#issuecomment-82206124> .

**Comment by prateekbaheti** [comment]
What version of the IntelliJ idea plugin you using ? Could you update to
the latest 0.0.5 and ensure you can run `gauge --v` from the terminal
before starting Intellij.

**Comment by rogergl** [comment]
I'm using the latest and gauge –v displays:
0.0.5

Von:  Prateek <notifications@github.com>
Antworten an:  getgauge/gauge
<reply+00017f280730134a312bc13068e416c8d732bcd7e068857d92cf00000001111fad8d9
2a169ce03b6ee15@reply.github.com>
Datum:  Dienstag, 17. März 2015 09:53
An:  getgauge/gauge <gauge@noreply.github.com>
Cc:  Roger Gilliar <roger@gilliar.de>
Betreff:  Re: [gauge] OSX and IntelliJ - project creation fails (#116)

What version of the IntelliJ idea plugin you using ? Could you update to
the latest 0.0.5 and ensure you can run `gauge --v` from the terminal
before starting Intellij.

On Tue, Mar 17, 2015 at 2:21 PM, Roger Gilliar <notifications@github.com>
wrote:

> No I just restarted it.
>
> Von: Prateek <notifications@github.com>
> Antworten an: getgauge/gauge
>
> <reply+00017f28d6d1d8d4e60c5a79ae8977d8777c786e9b107a0e92cf00000001111fac7a9
> 2a169ce03b6ee15@reply.github.com>
> Datum: Dienstag, 17. März 2015 09:48
> An: getgauge/gauge <gauge@noreply.github.com>
> Cc: Roger Gilliar <roger@gilliar.de>
> Betreff: Re: [gauge] OSX and IntelliJ - project creation fails (#116)
>
>
> Did you reinstall IntelliJ idea after gauge installation via brew ?
>
> ‹
> Reply to this email directly or view it on GitHub
> <https://github.com/getgauge/gauge/issues/116#issuecomment-82206124> .
>
>
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getgauge/gauge/issues/116#issuecomment-82206795>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/getgauge/gauge/issues/116#issuecomment-82209001> .

**Comment by prateekbaheti** [comment]
Could you run `echo $PATH` on the terminal and ensure `/usr/local/bin` is in PATH. 
Also can you try starting idea from command line.
Run `open "/Applications/IntelliJ IDEA 14.app"`

**Comment by rogergl** [comment]
It works if I start IntelliJ from the command line.

Von:  Prateek <notifications@github.com>
Antworten an:  getgauge/gauge
<reply+00017f2865e81d045b82b8378e7f8a9f8dd3965e591efa6692cf00000001111fb1e19
2a169ce03b6ee15@reply.github.com>
Datum:  Dienstag, 17. März 2015 10:12
An:  getgauge/gauge <gauge@noreply.github.com>
Cc:  Roger Gilliar <roger@gilliar.de>
Betreff:  Re: [gauge] OSX and IntelliJ - project creation fails (#116)


Could you run echo $PATH on the terminal and ensure /usr/local/bin is in
PATH. 
Also can you try starting idea from command line.
Run open "/Applications/IntelliJ IDEA 14.app"

‹
Reply to this email directly or view it on GitHub
<https://github.com/getgauge/gauge/issues/116#issuecomment-82222531> .
