### ISSUE TITLE
The screenshot of failing example is just the desktop

### ISSUE THREAD

**Issue by aligit** [getgauge/gauge#1160]
### Expected behavior
Include Screenshot of browser in the reports when specification fails.

### Actual behavior
Includes Screenshot of Desktop in the reports when specification fails.

### Steps to reproduce
1. Launch Browser
2. Go to Google.com
3. Assert that when you search for Twitter, the result is TOTO (Which will cause the example to fail)

### Gauge version
```
Run gauge -v on your system and paste the results here.
```

**Comment by zabil** [comment]
To get browser screenshots please implement a [custom screenshot handler](https://docs.gauge.org/latest/writing-specifications.html#taking-custom-screenshots)
