### ISSUE TITLE
use table component with the file parameter

### ISSUE THREAD

**Issue by heidiks** [getgauge/gauge#1161]
### Expected behavior
Would be possible to combine table component with a file parameter? For example:
```
   |MY_TABLE      |FILE                       |
   |--------------|---------------------------|
   |My table      |<file:resources/myfile.txt>|
```
So then, in the html-report, this file would be visible and in the iteration of the table, we didn't need to convert manually.

### Gauge version
```
$ gauge version
Gauge version: 1.0.0
Commit Hash: 5a99965

Plugins
-------
html-report (4.0.5)
java (0.6.8)
screenshot (0.0.1)
```

**Comment by sriv** [comment]
Gauge does not have support for nested tables yet, but it is a feature we would like to build. What you propose is an extension to that, i.e. have nested table linked via a file parameter.

sidenote: the `file` parameter is not interpreted as a table, you may want to use `table` instead.

**Comment by zabil** [comment]
Closing this as Gauge will not be implementing this feature.
