### ISSUE TITLE
Formatting a multi line text should retain multi-line

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1168]
**Expected behavior**
Formatting a multi line text should retain multi line

**Actual behavior**
The formatted step becomes a single line

**Steps to replicate**
* Add a multi-line step in the specification.
* Format the spec.
> The step now becomes a single line

**Version**
```
Gauge version: 1.0.1.nightly-2018-08-22
Commit Hash: 3750b26
```
Child of https://github.com/getgauge/gauge/issues/265

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
