### ISSUE TITLE
Refactoring a multi-line step should retain the step in multiple lines

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1169]
**Expected behavior**
Refactoring a multi-line step should retain the step in multiple lines

**Actual behavior**
After refactoring the step is in single line

**Steps to replicate**
* Create a multi-line step in a spec
* Refactor it
> The multi-line format must be retained

**Version**
```
Gauge version: 1.0.1.nightly-2018-08-22
Commit Hash: 3750b26
```
Child of https://github.com/getgauge/gauge/issues/265

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
