### ISSUE TITLE
Find references usage should be listed with the complete multi-line text

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1171]
**Expected behavior**
Find references usage should be listed with the complete multi-line text

**Actual behavior**
Find references usage lists the text partially when the spec uses the step in multiple lines

**Steps to replicate**
* Create a step in multiple lines
* Create an implementation
* Goto the definition
* Click on references
> The listed reference should have the entire text. Currently the text displayed is incomplete

**Version**
```
Gauge version: 1.0.1.nightly-2018-08-22
Commit Hash: 3750b26
```
Child of https://github.com/getgauge/gauge/issues/265

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
