### ISSUE TITLE
Console Stacktrace with failure in a multi-line step must be in multiple lines

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1172]
**Expected behavior**
stacktrace with failure in a multi-line step must be in multiple lines

**Actual behavior**
The step is shown in a single line.

**Steps to replicate**
* Create a multi-line step in a spec
* Give an implementation to it with a failure
* Run the spec
> The output console does not show the step in multiple lines

**Version**
```
Gauge version: 1.0.1.nightly-2018-08-22
Commit Hash: 3750b26
```
Child of https://github.com/getgauge/gauge/issues/265

**Comment by zabil** [comment]
Closing this as Gauge will not be implementing this feature.
