### ISSUE TITLE
Make multiline step text configurable

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#1173]
### Expected behavior
#265's implementation should be configurable. i.e. user should be able to configure if a particular project can have step implementations across lines.

### Actual behavior

#265's implementation caused a regression for a few users. Specifically, this was a valid step prior to gauge v1.0.1:

```
* a valid step
and some comment in the next line
```

and v1.0.1 reads the two lines as a single step, i.e. `a valid step and some comment in the next line`, which causes gauge to mark the step as unimplemented.

### Gauge version
```
v1.0.1
```

**Comment by smathistad** [comment]
Thanks for making this feature configurable.  I appreciate it, as do several people where I work.

I do have a concern about how #265 and this issue will affect the [IntelliJ-Gauge plugin](https://github.com/getgauge/Intellij-Plugin).
I will be posting an issue with that project shortly.

**Comment by nehashri** [comment]
Multiline steps are disabled by default now. To enable them set `allow_multiline_step` to `true` in your properties file.

**Comment by smathistad** [comment]
> The fix should be available in nightly >= 11-8-2018

Aug 11th, 2018 ???

**Comment by sriv** [comment]
The bot is wrong. It should be 11-Sep-2018.
