### ISSUE TITLE
Access current row from a data table as step argument

### ISSUE THREAD

**Issue by jameshd** [getgauge/gauge#1174]
### Expected behavior

I'm using Gauge to test a REST API returns the expected values. I have a set of pre-determined values in a CSV, and I'm using that to push data into the API request and also assett they're present in the API response. Here's the Spec: 

```
# API Enpoint

table:fixtures/test_records.csv

## Simple Calls ID
* When I hit the endpoint with an <ID>
* I should get back the expected record with: <ID>, <Make>, <Model>

```
Ideally, Instead of passive each field I want to asset agains as dynamic parameters, it would be really useful to have access to the "current row" that was being executed. Making my spec file read like so: 

```
# API Enpoint

table:fixtures/test_records.csv

## Simple Calls ID
* When I hit the endpoint with an <ID>
* I should get back the expected record matching: <current-table-row>

```
This way, I can handle the assertions inside my step definition nicely, and write custom logic to verify everything matches etc. I've achieved something similar using Postman and Iteration Data previously. However, I wanted to have more control over the request/response and have readable docs for my team.

### Actual behavior
As above.

### Steps to reproduce
See above.

### Gauge version
```
Gauge version: 1.0.0

Plugins
-------
html-report (4.0.5)
js (2.3.1)
screenshot (0.0.1)
```

**Comment by zabil** [comment]
Thanks for the suggestions @jameshd 

However, this is difficult to implement for the following reasons.
* Steps will need additional syntax. Gauge minimizes syntax to increase readability
* Steps implemented this way is not re-usable across other scenarios without the external csv or table declaration.

For these reasons Gauge prefers being explicit about parameters for a step.

**Comment by jameshd** [comment]
Hi, that's absolutely fine. No worries!

**Comment by alpha1592** [comment]
Hello,
This is a feature that i really need. 
We have Soap requests that have up to 50 columns in a csv and a 1,000 rows that need to be looped thru. We cannot add a step for every column in the spec file. it would be too verbose and too difficult to manage. Can we not get access to the current row being executed inside our step implementation so we can do whatever we want with it?

you could do something like...
* some step <table:some.csv>

@Step("some step <table>")
public void step(Table table)
{
    TableRow row = table.getCurrentRow();
    // do whatever with row. 
}

Thanks

Azhar
inside java implementation, you have a Table

**Comment by BugDiver** [comment]
@alpha1592 This is currently not possible, because of the table parameter is passed to the `Step` method while executing, the execution is done via the language runner (a method invoke), The `table` is passed to the user code. Neither `gauge` nor the `runner` has information about which row needs to be accessed.
