### ISSUE TITLE
Gauge is not compatible with freebsd

### ISSUE THREAD

**Issue by rajeshvaran** [getgauge/gauge#1178]
### Expected behavior
Gauge should start and run after download using curl in a freebsd box. gauge -v should display the version information

### Actual behavior
Executing ./gauge throws the below exception

ELF binary type "0" not known.
-bash: ./gauge: cannot execute binary file: Exec format error
FreeBSD 11.1
### Steps to reproduce
1.
2.
3.

### Gauge version
```
Gauge version: 1.0.0
```

**Comment by sriv** [comment]
Gauge is not (yet) compiled for FreeBSD. Works only on Windows, macOS and Linux.

**Comment by zabil** [comment]
Golang has support for cross compiling to freebsd. But this needs to be a part of our release process.

@rajeshvaran to understand this better. Can we understand why you are running tests on FreeBSD? Are you using FreeBSD's jails for managing containers?

**Comment by rajeshvaran** [comment]
Fix working as expected. Hence closing this request.
