### ISSUE TITLE
Should be able to execute specifications with compatible versions of plugins

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1184]
**Expected behavior**
Should be able to execute specifications with compatible versions of plugins

**Actual behavior**
Getting error `Failed to start gauge API: Compatibility error. Incompatible version. Minimum support version a.b.c is higher than current version x.y.z`

**Steps to replicate**
* Install Gauge `gauge 1.0.1` with js plugin `2.3.1`
* Create a `gauge-js` project
* Downgrade Gauge version to `0.9.8`
* `gauge run specs` on the project
> It recognizes that a compatible version is not available and installs js version `2.3.0` which is compatible with `0.9.8`. However the execution phase fails with the following error
```
Compatible version of plugin js not found. Installing plugin js...
........
[grpc] Success: ".../.gauge/plugins/js/2.3.0/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node" is installed via remote
added 169 packages from 148 contributors and audited 684 packages in 4.917s
found 12 vulnerabilities (10 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
Successfully installed plugin 'js'.
Error ----------------------------------

Failed to start gauge API: Compatibility error. Incompatible version. Minimum support version 1.0.0 is higher than current version 0.9.8

Get Support ----------------------------
    Docs:          https://docs.gauge.org
    Bugs:          https://github.com/getgauge/gauge/issues
    Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
    darwin, 0.9.8, c23df9f
    html-report (4.0.5), java (0.6.8), js (2.3.1), screenshot (0.0.1)
```

Blocks #1157
> Though this is not related to npm installer directly. This fix is required for npm local installations to work seamlessly. This issue will occur when user downloads different Gauge binary per project and they have plugins that are incompatible with both Gauge binaries.

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
