### ISSUE TITLE
`SuiteExecutionResult` is missing exact start/end time

### ISSUE THREAD

**Issue by nvborisenko** [getgauge/gauge#1189]
Report doesn't contain something related to timings. I see "timestamp": "Sep 20, 2018 at 1:34pm", but what this means... report generation date... or when execution started...

I would like to see when exactly execution started and finished. Moreover please don't store formatted time, it would be easier to make 3rd party integrations.

The same for specs/scenarios/steps... We don't have timings, only duration.
```
"executionTime": "1002"
```
It's confusing. In terms of gauge it is duration in milliseconds.

**Comment by nehashri** [comment]
@nvborisenko The timestamp that is shown is the time when execution started.
Your suggestions seem helpful to have. Although this is an issue in the [html-report](https://github.com/getgauge/html-report) plugin and not directly related to Gauge core itself. I will be moving this issue there.
Also it would really help us if you could contribute this to Gauge through a PR.

**Comment by nehashri** [comment]
This issue was moved to getgauge/html-report#196

**Comment by nvborisenko** [comment]
This issue is not related to html report. The gauge core doesn't provide data about when executtion was started and ended.

I see proto message:
https://github.com/getgauge/gauge-proto/blob/master/doc/gauge-proto-doc.md#protosuiteresult

And I see only duration. So any plugin doesn't know about timings.

**Comment by nehashri** [comment]
@nvborisenko We have not added any field in gauge-proto unless it is absolutely needed by a plugin. That is the reason I have moved it to html-report. 
If you see a need to add a field to it, it can be done. Unfortunately, the Gauge team is working on other features right now. It would really help us if you can contribute via a PR.

**Comment by sriv** [comment]
`timestamp` in [`protosuiteresult`](https://github.com/getgauge/gauge-proto/blob/master/doc/gauge-proto-doc.md#protosuiteresult) is the start time (although it is formatted to string). 

`executionTime` in `protosuiteresult` is the total time in milliseconds for the suite execution. 

Would changing `timestamp` to be in form of unix timestamp be enough for your usecase "start timestamp" and "end timestamp" @nvborisenko ?
