### ISSUE TITLE
Javascript plugin

### ISSUE THREAD

**Issue by jamesdwilson** [getgauge/gauge#119]
Is there plans to write a javascript plugin? Thank you, would very much appreciate. This project looks awesome.

**Comment by sriv** [comment]
We do aim to, but we have our hands full at the moment unfortunately :(. However, there is an interest expressed in the [community forum](https://groups.google.com/forum/#!topic/getgauge/hAwHJyeNXvI), and we would definitely appreciate any contributions. We (the Gauge Team) can definitely commit time to help any contributor get started with the project. 

Thanks for checking Gauge out, really welcome the appreciation!

**Comment by jamesdwilson** [comment]
That's great. I understand you're busy and it will take some time, just
wanted to make sure it is on the list somewhere.
Cheers and keep up the great work.

On Wed, Mar 18, 2015 at 10:27 AM, Srikanth <notifications@github.com> wrote:

> We do aim to, but we have our hands full at the moment unfortunately :(.
> However, there is an interest expressed in the community forum
> <https://groups.google.com/forum/#!topic/getgauge/hAwHJyeNXvI>, and we
> would definitely appreciate any contributions. We (the Gauge Team) can
> definitely commit time to help any contributor get started with the
> project.
>
> Thanks for checking Gauge out, really welcome the appreciation!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getgauge/gauge/issues/119#issuecomment-83021113>.
>



-- 
Thank you!

**Comment by mahendrakariya** [comment]
I will close this issue. We can track it at #145.

**Comment by mahendrakariya** [comment]
Just an update, @renjithgr is working on a javascript plugin for Gauge.
More details at https://github.com/renjithgr/gauge-js
