### ISSUE TITLE
Can you allow gauge to skip optional parameters

### ISSUE THREAD

**Issue by waymantc** [getgauge/gauge#1191]
Can you build in the behavior such that gauge can use methods with a step attribute that have an optional parameter?

Something along the lines of this:
- If a method with the step attribute has an optional parameter you have to include a step alias that can handle the optional parameter and one that does not require it.

I realize this is not a simple request.

Thanks,

### Gauge version
1.0.0

**Comment by zabil** [comment]
Unfortunately this change is tricky and will affect other areas like refactoring etc.
It's unlikely that Gauge will implement this and prefer to keep this functionality simple.
