### ISSUE TITLE
Can you implement Concepts in a way that allows logic to be placed around them?

### ISSUE THREAD

**Issue by waymantc** [getgauge/gauge#1192]
Is there a way to implement Concepts in a way that allows logic to be placed around/in them?

Currently I am building the equivalent of a Concept as a Step which allows me to enter logic into the "Concept" definition.

I was just wondering if such an improvement would be considered?

### Gauge version
1.0.0

**Comment by Apoorva-GA** [comment]
Concepts are to combine re-usable logical groups of steps into a one unit. 
Could you give an example as to what exactly you are expecting?

**Comment by nehashri** [comment]
@waymantc I think your issue is similar to making a step as optional. Currently we do not support such behaviour. If you have any idea as to how to accomplish this in the spec file, please let us know
