### ISSUE TITLE
Custom Log Dir not accepting/using path provided

### ISSUE THREAD

**Issue by mgraffx** [getgauge/gauge#1198]
Per chat
I changed the location in the default.properties file to the following but logs still write to project-root/logs
logs_directory = /usr/local/var/www/logs
I am running gauge as a user that has write privileges to this location.
Shouldn't I be able to write logs to a full path in this way?

### Expected behavior
Setting logs_directory  in default.properties file should accept path provided and log should appear at configured path.

### Actual behavior
Set the property but log still appears in default location

### Steps to reproduce
1. Change logs_directory = /some/path
2. Run gauge to completion of test
3. Check  /some/path upon run completion but log not present

### Gauge version
Gauge version: 1.0.0

**Comment by BugDiver** [comment]
The logs are getting generated to the custom dir, but the custom dir is getting generated inside the `Gauge Project Root`.
So in case of `logs_directory = /some/path` the logs will be generated in `GAUGE_PROJECT_ROOT/some/path`.

gauge should be able to figure out if the logs_dir is absolute path its should not append Project root in filepath.

**Comment by nehashri** [comment]
This still need testing.

**Comment by mgraffx** [comment]
Thanks all.
