### ISSUE TITLE
make a step optional

### ISSUE THREAD

**Issue by TzurAnv** [getgauge/gauge#1200]
### Expected behavior
the ability to create a step in an optional status which mean that in case the step fail the scenario will not stop nor marked as a fail scenario (maybe the step could receive a different color in the gauge console such as yellow)

**Comment by sguptatw** [comment]
@TzurAnv In Gauge there is a feature called continue on failure - https://docs.gauge.org/latest/writing-specifications.html#continue-on-failure. Here the execution of the next step is continued even when there is a failure on a step marked to continue-on-failure.
However all the steps that fail are marked as failures.

Does this help your use-case?

**Comment by sriv** [comment]
Gauge can [Continue on step failure](https://docs.gauge.org/latest/writing-specifications.html#continue-on-failure). The step implementations can definitely what exception to ignore.

Are you looking for something better?

**Comment by TzurAnv** [comment]
the continue as a failure is a great feature which i use but as it marking the scenario is a failure its not really the optional ability which i seek, currently im handling this case in the code itself but it could be nice if i would have the ability to let the gauge handle it

**Comment by nehashri** [comment]
@TzurAnv it may be a good feature to have but adding this in the spec file may make it non readable. If you have any suggestion as to how to handle this in the spec file, please let us know.

**Comment by zabil** [comment]
It's better to handle this in code. Specifications are for capturing user behavior. 
For that reason, it needs to be simple and readable.
