### ISSUE TITLE
Comments in spec files are throwing unimplemented error

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge#1201]
### Expected behavior
When you have a comment in a spec file. E.g

```markdown
## As a gauge user, I should be able to add comments in spec files

* Given I navigate to a page
// This is just a comment
// This is another comment
```
The validation (unimplemented) error should not be thrown.

### Actual behavior
The Unimplemented error is thrown.

```bash
@Step("Given I navigate to a page // This is just a comment // This is another comment")
	public void givenINavigateTo//ThisIsJustAComment//ThisIsAnotherComment(){
		throw new UnsupportedOperationException("Provide custom implementation");
	}
```

### Steps to reproduce
1. Add the above scenario,
2. Implement the first step

### Gauge version
```
Gauge version: 1.0.2

Plugins
-------
flash (0.0.1)
html-report (4.0.5)
java (0.6.8)
js (2.3.1)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.0)
```

**Comment by hraynaud** [comment]
having this issue as well.

**Comment by haroon-sheikh** [comment]
Looks like the env var `allow_multiline_step ` is being set by default to `false.`
If I run `allow_multiline_step=false gauge run specs` then I dont see the validation errors.

**Comment by nehashri** [comment]
@haroon-sheikh was this tried on a new project or an existing project?

**Comment by haroon-sheikh** [comment]
Both new and existing projects.

**Comment by sriv** [comment]
@haroon-sheikh - I am on linux. And here's what I tried:

```
/tmp/foo$ gauge -v
Gauge version: 1.0.2
Commit Hash: b4288bb

Plugins
-------
csharp (0.10.6.nightly-2018-09-05)
dotnet (0.1.1.nightly-2018-09-11)
html-report (4.0.6.nightly-2018-10-10)
java (0.6.8)
js (2.3.1)
python (0.3.4.nightly-2018-09-05)
ruby (0.5.2.nightly-2018-09-11)
screenshot (0.0.1)
spectacle (0.1.4.nightly-2018-07-30)
xml-report (0.2.1.nightly-2018-05-14)

$ gauge init java
Downloading java.zip
.
Copying Gauge template java to current directory ...
Successfully initialized the project. Run specifications with "gauge run specs/".

gauge run specs
# Specification Heading
  ## Vowel counts in single word	 ✔ ✔
  ## Vowel counts in multiple word	 ✔ ✔
  ## As a gauge user, I should be able to add comments in spec files	 ✔ ✔

Successfully generated html-report to => /tmp/foo/reports/html-report/index.html
Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	3 executed	3 passed	0 failed	0 skipped

Total time taken: 53ms

```

o$ cat specs/example.md 
# Specification Heading

This is an executable specification file. This file follows markdown syntax.
Every heading in this file denotes a scenario. Every bulleted point denotes a step.

To execute this specification, run
	gauge run specs


* Vowels in English language are "aeiou".

## Vowel counts in single word

tags: single word

* The word "gauge" has "3" vowels.


## Vowel counts in multiple word

This is the second scenario in this specification

Here's a step that takes a table

* Almost all words have vowels
     |Word  |Vowel Count|
     |------|-----------|
     |Gauge |3          |
     |Mingle|2          |
     |Snap  |1          |
     |GoCD  |1          |
     |Rhythm|0          |


## As a gauge user, I should be able to add comments in spec files

* Given I navigate to a page
// This is just a comment
// This is another comment

```

Could you give this a try with the latest nightly of gauge?

**Comment by shubhamsc** [comment]
@haroon-sheikh  I'm closing this issue. If you are still facing the same issue, please reopen it.
