### ISSUE TITLE
Unable to uninstall js

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1204]
**Expected behavior**
Should be able to uninstall gauge-js

**Actual behavior**
Getting error `Unable to read plugin's metadata, removing ...\AppData\Roaming\gauge\plugins\js\2.3.2.nightly-2018-09-13
Failed to uninstall plugin js . remove ...gauge\plugins\js\2.3.2.nightly-2018-09-13\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node: Access is denied.`

**Steps to replicate**
> Observed on Windows
* gauge uninstall js`

**Version**
```
Gauge version: 1.0.3.nightly-2018-09-25
Commit Hash: b7ea2ee
```

**Comment by sguptatw** [comment]
When I tried to manually delete the folder it said this was being used by some other program. However all other programs were closed.

**Comment by BugDiver** [comment]
@sguptatw I'm not able to replicate this. `gauge uninstall js` working as expected for me.
Can you make sure all the `gauge-js` processes are closed?
The gauge-js is also used by `vscode`. So if you have a `js` project open in `vscode`, `gauge` will not be able to uninstall the plugin.
