### ISSUE TITLE
The silent installation options to be reduced only to install Gauge

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1207]
**Proposed behavior**
The single binary of gauge is to be used on CI. Choco installer also uses the single binary. Hence minimum silent installation options in windows installer is sufficient.

**Current behavior**
Currently there are few redundant silent installation options.

Related to #963

**Comment by BugDiver** [comment]
The silent install is a default behavior for the nsi `exe` files, not sure if we can remove it. We add some custom things to allow the user to install plugins along with gauge (in silent mode). We can remove that.
