### ISSUE TITLE
Support to add custom data into the HTML report at runtime

### ISSUE THREAD

**Issue by prateekbaheti** [getgauge/gauge#121]
Add ability to add custom data at runtime, via an api similar to `System.out.println` (in Java, for ex) that would push text values to the report execution output.

This can then be rendered in HTML report (or any other consumer of test results).

**Comment by prateekbaheti** [comment]
Added field for passing custom messages in the StepExecutionExecution response from the runner. Need to now expose an API on language runners that users can use and write messages into. These messages will be added to the Execution response returned by the runner.
- [ ] Java
- [ ] Ruby
- [ ] Csharp

HTML reporting plugin can then display the custom messages on the generated report
- [ ] HTML report update

**Comment by prateekbaheti** [comment]
Added support for java. Plugins required:
 * java runner - 0.2.0 and above
 * html-report - 1.0.4 and above

**Comment by apoorvam** [comment]
Added support for CSharp in [commit](https://github.com/getgauge/gauge-csharp/commit/6163e4cb11b7db80599fb7f6db09ff4008e4b5aa).

**Comment by sriv** [comment]
Ruby support can be tracked via getgauge/gauge-ruby#19
