### ISSUE TITLE
Feature Request: Add ability to mark scenarios as xfail

### ISSUE THREAD

**Issue by surajbarkale** [getgauge/gauge#1213]
Pytest offers ability to mark a test as [expected to fail](https://pytest.readthedocs.io/en/2.8.7/skipping.html#mark-a-test-function-as-expected-to-fail). The test report highlights these test separately. This is a useful functionality to keep track of brackages in the system.

I was unable to find similar functionality within gauge.

**Comment by nehashri** [comment]
@surajbarkale You can always skip running failing tests using Tags in Gauge. Is there a specific reason you would like to run these tests but ignore their status?

**Comment by surajbarkale** [comment]
A test marked as xfail will error out when it completes successfully. This
provides automated check which you don't get with skipped tests. Very
useful with flakey tests.

It would also be OK if a hook can ignore step/scenario failures.

**Comment by zabil** [comment]
Will this approach be helpful?
https://github.com/getgauge/gauge-java/issues/162

The issue talks about adding a step handler to handle exceptions and control flow.

**Comment by surajbarkale** [comment]
It would be sufficient if it provides ability to:

1. Check the execution context (e.g. tags on the scenario)
2. Stop scenario execution without failing it

I am not clear on what control flow handling is provided in the proposal.

**Comment by zabil** [comment]
> I am not clear on what control flow handling is provided in the proposal.

I meant, the step handler can 
* Throw the exception (if any) to fail the scenario
* Ignore the exception and proceed by executing the remaining steps in the scenario. 
* Stop execution of the current scenario (ignore rest of the steps).

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
