### ISSUE TITLE
A scenario that can be executed with line should be executable with scenario name

### ISSUE THREAD

**Issue by sswaroopgupta** [getgauge/gauge#1217]
**Expected behavior**
A scenario that can be executed with line should be executable with scenario name

**Actual behavior**
The scenario is not found when executed with name

**Steps to replicate**
* Create a `gauge-js` project
* Create a scenario with name ```Show code actions on ~`!@#$%^&()_-+;',./=undefined steps```
* Execute the scenario
```gauge run --scenario="Show code actions on ~`!@#$%^&()_-+;',./=undefined steps"```
> This scenario is not found. However from the VSCode this scenario can be executed

**Version**
```
Gauge version: 1.0.3.nightly-2018-10-05
Commit Hash: ff2114f
```
> Blocks #1012

**Comment by sguptatw** [comment]
Tried executing by escaping `!` - `gauge run --scenario="Show code actions on ~`\!@#$%^&()_-+;',./=undefined steps"`. The scenario is not found.

**Comment by shubhamsc** [comment]
In windows no need to escape `!`. just use single quotes instead of double
` gauge run --scenario='Show code actions on ~!@#$%^&()_-+;'\'',./=undefined steps'`
if you want to use single quotes in scenario name then escape them like -
change `'` to `'\''`

**Comment by shubhamsc** [comment]
Every command line shell uses the different character to escape some special characters.
so you have to change your command according to their escaping rules.
> gauge run --scenario='Show code actions on ~!@#$%^&()_-+;'\'',./=undefined steps'

this command is working fine in Gitbash but not in Powershell. For Powershell, you have to run 
`gauge run --scenario="Show code actions on ~``!@#$%^&()_-+;',./=undefined steps"`
# Powershell -
![scenario](https://user-images.githubusercontent.com/34643008/47081996-dd1da600-d229-11e8-92cb-408af0f132ff.PNG)
# Gitbash -
![scenario_bash](https://user-images.githubusercontent.com/34643008/47081970-d000b700-d229-11e8-954b-aa53b1cd7524.PNG)
