### ISSUE TITLE
Should be able to configure full path of a log directory

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1218]
**Expected behavior**
Should be able to configure full path of a log directory

**Actual behavior**
Getting the error
`The Gauge server crashed 5 times in the last 3 minutes. The server will not be restarted.`

**Steps to replicate**
* Open a gauge project in VSCode
* Change the `logs_directory = c:\logs` in default.properties
* Restart the IDE
> Getting the above error

**Version**
```
Gauge version: 1.0.3.nightly-2018-10-05
Commit Hash: ff2114f
```
Blocks #1198

**Comment by sriv** [comment]
@sguptatw - can you please check with `logs_directory = c:\\logs` i.e use `\\` instead of `\` ?

**Comment by sguptatw** [comment]
@sriv It works with `\\` instead of `\`

**Comment by sguptatw** [comment]
Moving this to backlog since there is a workaround to configure the logs_directory in windows
