### ISSUE TITLE
Feature Request: Grouping by tags so spec groups can be run in parallel

### ISSUE THREAD

**Issue by trung** [getgauge/gauge#1220]
Currently `gauge` offers grouping based on a given number of group and specs in groups are evenly distributed from alphabetically sorted list.

As tags are supported, it would be super useful if Gauge can provide additional grouping strategy based on tags. E.g.:

```bash
gauge run --spec-group tag1,tag2 --spec-group tag3,tag4
```
The above command will make sure:
* There are 2 groups being executed in parallel
* Group 1 contains specs/scenarios which have `tag1` and `tag2`
* Group 2 contains specs/scenarios which have `tag3` and `tag4`

There are some considerations:
* Reuse tag expression similar to `--tags` option
* Specs/scenarios have both `tag1` and `tag3`: -> exclusive, per order in the command line, i.e.: in the above example, spec is added to Group 1 and not Group 2
* Specs/scenarios don't have any tag: -> form a separate group by itself
* Group doesn't have any spec matching with specified tags: -> return error

**Comment by zabil** [comment]
@trung thanks for the suggestion!

However, Gauge wants keep this simple. 
For additional grouping use another Tag that includes scenarios/specs marked as `tag1` and `tag2` For running in parallel, makes scenarios can run independently and not depend on other tests.

**Comment by trung** [comment]
thanks for the response. When running independently, how to combine test reports?

**Comment by NivedhaSenthil** [comment]
@trung can you please explain more on what you mean by running independently ?

**Comment by sriv** [comment]
If I understand @trung correctly, the idea is to have multiple gauge run reports merged together.

This will be tricky with html report. However xml/json report can be collated using external tooling. 

Gauge does not support this currently. I guess that is the tradeoff in parallel run currently.

**Comment by trung** [comment]
@NivedhaSenthil, as @zabil suggested 
> For running in parallel, makes scenarios can run independently and not depend on other tests.

And my understand is to run `gauge` command independently multiple times with `-Dtags`. Hence my question about the test reports merging.

As in parallel execution mode, Gauge is already able to produce a single report. So I am only proposing a different grouping strategy.
