### ISSUE TITLE
Error Message: Step Implementation not found in Persian Language

### ISSUE THREAD

**Issue by asadsafari** [getgauge/gauge#1226]
Hello
I'm trying to use gauge with C#/Visual studio code. 
When I define Step like this, it works:

`
Customer sign-up
================
* Go to the store website
`
`
[Step("Go to the store website")]
        public void LaunchTheApplication()
        {
            Driver.WebDriver.Navigate().GoToUrl("http://developer.dev.sadad.local/site/");
        }
`
But when I try to use Persian language, it doesn't work
`
Customer sign-up
===
* صفحه اول وب سایت را باز کن
`
`
		[Step("صفحه اول وب سایت را باز کن")]
		public void LaunchApplication()
		{
			Driver.WebDriver.Navigate().GoToUrl("http://developer.dev.sadad.local/site/");
		}
`

I got this error message:
Failed Step: صفحه اول وب سایت را باز کن
        Specification: c:\Users\asafari\Desktop\TestDotnet\TestDotnet\specs\App.spec:4
        Error Message: Step Implementation not found
        Stacktrace: 

I think it's about UTF-8 Encoding. Any idea to solve this problem?

**Comment by sguptatw** [comment]
@asadsafari 
Can you please help us with more details

* Which OS are you on? 
* If Windows, please execute `[System.Text.Encoding]::Default` in powershell and paste the results.
* Which version of Gauge and plugins are you using? Please execute `gauge version` and paste the details.
* Can you please share a sample project where you are facing this issue.

Thanks!

**Comment by asadsafari** [comment]
@sguptatw 
Os-> Windows
Default Encoding :
IsSingleByte      : True
BodyName          : iso-8859-1
EncodingName      : Western European (Windows)
HeaderName        : Windows-1252
WebName           : Windows-1252
WindowsCodePage   : 1252
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 1252

Gauge Version: 1.0.3

**Comment by asadsafari** [comment]
[TestDotnet.zip](https://github.com/getgauge/gauge/files/2504924/TestDotnet.zip)
This is source of project

**Comment by sguptatw** [comment]
**Findings**
Not able to find steps always

> Note: With the following step and impl gauge is able to run specs successfully
* Create a dotnet project
**Spec**
```
App
===
* صفحه اول وب سایت را باز کن

App
----------------
tags: create-app

* امیر حسین لاگین کرده
* در صفحه ایجاد اپ هستیم
```
**Code**
```
using System;
using Gauge.CSharp.Lib.Attribute;

namespace TestDotnet
{
	public class StepImplementation
	{
		[Step("امیر حسین لاگین کرده")]
		public void DeveloperLoggedin()
		{
		}
		[Step("در صفحه ایجاد اپ هستیم")]
		public void GoToAppcreationPage()
		{
		}
	}
}
```
**However with the following specs and impl, one step is not found**
```
App
===
* صفحه اول وب سایت را باز کن

App
----------------
tags: create-app

* امیر حسین لاگین کرده
* در صفحه ایجاد اپ هستیم
* و با آدرس برگشت داده
```

**Code**
```
using System;
using Gauge.CSharp.Lib.Attribute;

namespace TestDotnet
{
	public class StepImplementation
	{
		[Step("امیر حسین لاگین کرده")]
		public void DeveloperLoggedin()
		{
		}
		[Step("در صفحه ایجاد اپ هستیم")]
		public void GoToAppcreationPage()
		{
		}
		[Step("و با آدرس برگشت داده")]
		public void CreateApp(arg0)
		{
		}
	}
}
```

**Version**
```
Gauge version: 1.0.3.nightly-2018-10-12
Commit Hash: 63e61ca

Plugins
-------
dotnet (0.1.1.nightly-2018-10-16)
```

**Comment by sriv** [comment]
Hi @asadsafari  - I think I know what's wrong, but would like your help in confirming this.

In your test project, I see that `AppSteps.cs` has this line on line no. 19

```
public void CreateApp(arg0 ,arg1)
```

This is incorrect C# syntax. And while execution, there is error indicating this:

```
AppSteps.cs(19,30): error CS1001: Identifier expected [/tmp/TestDotnet/netcore-template.csproj]
AppSteps.cs(19,35): error CS1001: Identifier expected [/tmp/TestDotnet/netcore-template.csproj]
```

If I change the line to be `public void CreateApp(string arg0, string arg1)` then it works.

I think the issue could be in the Step implementation generation, did you use the "Implement Step" feature ?

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
