### ISSUE TITLE
New feature: Ability to skip specs/scenarios using annotations

### ISSUE THREAD

**Issue by reachcsekar** [getgauge/gauge#1231]
### Expected behavior
Gauge should have a provision to skip specs/scenarios using annotations or any other suitable mechanism.

### Actual behavior
Gauge does not support skipping specs/scenarios currently.

**Comment by sriv** [comment]
Spec/Scenario are not really visible in the code level, so there isn't a place to put the annotation in place.

Currently, one could use tags to filter out a spec/scenario. 

But if it has to be in the code, then the best I can think of is to have a provision in the `BeforeScenario` or `BeforeSpec` hook to ask it to skip current execution.

**Comment by reachcsekar** [comment]
This kind of control should be available at the spec level and not at the code level. It will be easier for non-users to skip scenarios that are affected by a bug. Also, consider the situation where execution is triggered automatically, for example from Jenkins. Only "gauge run specs" will be used and including tags might not be practically feasible.
Lets say i have 1000 test cases and want to skip 100, its easier to skip it using annotations than using tags. If using tags, then every spec should have tag associated with it which might be unnecessary.

**Comment by ajoecker** [comment]
> Lets say i have 1000 test cases and want to skip 100, its easier to skip it using annotations than using tags. If using tags, then every spec should have tag associated with it which might be unnecessary

but then how would this annotation look like ? I thought you are proposing some syntax in the spec file, that will make a spec/scenario skippable.
But this would be the same in your case as using tags.

**Comment by zabil** [comment]
> But this would be the same in your case as using tags.

Closing this in favor of using tags

**Comment by zabil** [comment]
Yes, but unfortunately the spec files can't have special syntax to do this.
If it's in version control, you can always comment or remove it. However it won't appear in reports.
