### ISSUE TITLE
Footer misalignment in test result HTML report

### ISSUE THREAD

**Issue by bharadwajpenydala** [getgauge/gauge#1232]
### Expected behavior
In Reporting Footer looks distorted or enlarged.

### Actual behavior
Footer is occupying half of the page with "Generated by Gauge HTML Report" message.

### Steps to reproduce
1. Execute `gauge run specs`
2. Open index.html from reports folder in Chrome
3. Observe the footer section. 

### Gauge version
Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
html-report (4.0.5)
java (0.6.9)
screenshot (0.0.1)

![image](https://user-images.githubusercontent.com/4959529/47494909-707d5980-d870-11e8-8aef-78a8e2c33258.png)

**Comment by bharadwajpenydala** [comment]
Reproducible while clicking on Failed and Skipped test numerics, the issue isn't reproducible if you click and observe the passed numeric.

**Comment by sguptatw** [comment]
Moving this issue to html-report repository.

**Comment by sguptatw** [comment]
This issue was moved to getgauge/html-report#202
