### ISSUE TITLE
Screenshot will not be taken if plugin not available

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1234]
**Expected behavior**
If network is present and screenshot plugin is not available - It will be installed.
However when network is not available and Gauge is unable to install screenshot, it should not take a screenshot. Instead it should print a message `Screenshot plugin required <gauge install screenshot>`

**Current behavior**
It tries to install screenshot and fails

**Comment by anuj952** [comment]
i want to work on this issue

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
