### ISSUE TITLE
Markdown Best Practice Styling is not Supported

### ISSUE THREAD

**Issue by Vad1mo** [getgauge/gauge#1236]
I wanted to know why does gauge won't work with formatted markdown files that are best practice compliant.

Example: http://www.cirosantilli.com/markdown-style-guide/

This is what gauge perceives as correct.
```md
## Use is Cloud Project Members
* Following users are part of the  Project
  | First Name | Lat Name | ID | Email |
  | ---------- | -------- | -------- | --------------------------- |
  | Mr. | T | ABV | fake@mail.com |
  | Master | of | Desaster | example@example.org |
```

This is what is best practice. 

```md
## Use is Cloud Project Members
- Following users are part of the  Project
  | First Name | Lat Name | ID | Email |
  | ---------- | -------- | -------- | --------------------------- |
  | Mr. | T | ABV | fake@mail.com |
  | Master | of | Desaster | example@example.org |
```

As you see it is considered best practice tu use `-` for lists instead of `*` however gauge can't cope with this setup.

I am using https://prettier.io to check , however any other formatter or linter should produce the same result.

**Comment by zabil** [comment]
Gauge uses Github flavor Markdown, but uses Markdown's syntax to identify scenario's and steps. Right now we use the `*` syntax for lists to identify steps. 

Github flavored markdown also allows `-` and `+` for unordered lists, but for now we want to keep this open for adding some feature in the future.

If you are looking to format Gauge specs we recommend using gauge [format](https://manpage.gauge.org/gauge_format.html)

**Comment by Vad1mo** [comment]
Its pitty that  gauge claims to support Markdown but it actually doesn't. Point is we have quite extensive specification that are also documentation.  For uniformity we try to comply with markdown best practice formatting rules.
