### ISSUE TITLE
Add timeout for steps/scenarios

### ISSUE THREAD

**Issue by jonathangiber** [getgauge/gauge#1237]
It would be great to support timeout per step/scenario to prevent executions getting stuck in case of step failure.

**Comment by sriv** [comment]
gauge-js supports timeouts for steps, since the step definitions can be `async`. But this can be rolled out via gauge.

What would be a good default for execution timeout?

**Comment by jonathangiber** [comment]
I think 5 minutes should be more than enough for a step but I guess there will be many different opinions on this topic.

**Comment by nehashri** [comment]
I think in the interest of backward compatibility, we don't set a timeout at all as default. Instead if it is configured, we can use that timeout in Gauge.

**Comment by haroon-sheikh** [comment]
It would be helpful if we can specify the timeouts:
- for all steps in env files. e.g. `STEP_TIMEOUT=5000` variable
- and should be able to override for a step within the annotations. E.g. @Step(timeout = 5000)

**Comment by h2grover** [comment]
Any plans on launching this feature? Or any update?

**Comment by zabil** [comment]
There are no plans for this as of now. However, PR's are to implement this feature will be accepted.
