### ISSUE TITLE
gauge run --dir does not read env

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#1238]
reported by @Christoffer-Green via [gitter](https://gitter.im/getgauge/chat?at=5be0178240449151f4fe1f26)

### Expected behavior
When running `gauge run` from outside the project directory, using `--dir` flag, it should read the env variables defined.

### Actual behavior
`gauge run` from project root reads the env var ok, but when run from outside using `--dir` it does not pick the properties.

### Steps to reproduce
1. `mkdir /tmp/foo && cd /tmp/foo`
2. `gauge init java`
3. edit `env/default/default.properties`, add `foo=bar`
4. edit `src/test/java/StepImplementation.java`, add `System.out.println(System.getenv("foo"));` in any step.
5. `gauge run specs` with WD: `/tmp/foo`
6. `cd ~ && gauge run --dir=/tmp/foo`
7. Observe that `foo` env is picked up in the first run, not in the second.

### Gauge version
```
Gauge version: 1.0.4
Commit Hash: 942c462

Plugins
-------
csharp (0.10.6.nightly-2018-09-05)
dotnet (0.1.1)
go (0.1.2)
html-report (4.0.7)
java (0.6.9)
js (2.3.1)
python (0.3.4.nightly-2018-09-05)
ruby (0.5.2.nightly-2018-09-11)
screenshot (0.0.1)
spectacle (0.1.4.nightly-2018-07-30)
xml-report (0.2.1.nightly-2018-05-14)

```

**Comment by sguptatw** [comment]
Working as expected in version
```
Gauge version: 1.0.4.nightly-2018-12-25
Commit Hash: fe5e7da
```
