### ISSUE TITLE
Feature request: support code blocks as new type of steps' parameter

### ISSUE THREAD

**Issue by 1u0** [getgauge/gauge#1240]
Currently, Gauge supports passing data to a scenario step as a [table](https://docs.gauge.org/latest/writing-specifications.html#table-parameters).

This is a proposal to add support for a new data type parameter in form of [Markdown's fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks), aka "triple backticks".
An example step can look like:
```markdown
 * Use the following configuration:
    ```yaml
    environment:
      name: local
    feature42:
      enabled: true
    ```
```
**NB:** the code block is indented according to Mardown rules, to be bound with the step.
 
The corresponding Java step implementation can look like:
```java
@Step("Use the following configuration <content>")
public void useConfiguration(Content data) {
  ...
}
```
With `Content` provided by `gauge` and having methods:
```java
public class Content {
    @Nullable
    public String getType(); // Would return "yaml" in the example

    public String getText(); // Would return "environment:\n  name: local\nfeature42:\n  enabled: true\n" in the example
}
```

**Comment by jbadeau** [comment]
also would love this feature

**Comment by 1u0** [comment]
>  ... but then the implementation is simply a string holding everything.

Yes, the proposal is to keep programming language api as simple as possible for such support. And allow the step implementation to interpret the string content.
Other examples of content could be json data, snippets of code, command lines, shell scripts, dockerfile and so on, whatever that doesn't fit into table format but has text representation.

> At least having a map or providing a data class to convert the string into would be better.

For the basic support, passing simple string "as is" would be already nice, imo.

You can extend the support later. For example by allowing application code to register mappers (from string to a typed data) in the Gauge runtime. So the steps can accept objects of user defined type and conversion would happen implicitly (by using the registered mapper) before step invocation.

> Anyhow - personally I do love Gauge because of it*s simplicity in the spec. In my eyes it should it not move the way Gherkin became by removing simplicity over complexity

Personally I find Gherkin more simpler (due to it's restrictiveness). Gauge advertises to use Markdown and I hope that it would have more richer "expressiveness".

**Comment by zabil** [comment]
In the interest of keeping specifications readable and relevant to acceptance testing this feature won't be implemented.
