### ISSUE TITLE
Gauge to support running scenarios with custom datasource

### ISSUE THREAD

**Issue by segeli** [getgauge/gauge#1242]
### Expected behavior
Gauge should have the ability to plug in a custom datasource

### Actual behavior
Gauge can handle with external table (CSV file)

### Gauge version
```
Gauge version: 1.0.3.nightly-2018-10-01
Commit Hash: 15b1e26

Plugins
-------
html-report (4.0.5)
java (0.6.9)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.0)
```

**Comment by ajoecker** [comment]
but is it already possible with file based data sources ?

You can use f.e. YAML files as datasource and simply use it as parameter in a step

`* Read data from "config.yaml"`

and the code then transforms the read string into entities

what kind of datasources you are thinking of ?

Anything besides table based formats would require to provide some kind of dependency to a mapping functionality

**Comment by sriv** [comment]
I believe @segeli 's use case is to have table driven execution using custom datasource.

**Comment by segeli** [comment]
@ajoecker @sriv Actually, I would like to have table driven execution using custom datasource that gets data from database.

**Comment by NicholasEF** [comment]
Are CSVs currently the way to pull in data in a Gauge spec? I threw down a comment over in #94 supporting a way to pull in JSON and YAML within a spec. 

Messing around with
`* Read data from "config.yaml"`
it seems like that would be limited to just one step? It wouldn't be a way to pull in data for a whole test run.
