### ISSUE TITLE
Unable to execute specifications

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1243]
**Expected behavior**
Should be able to execute specifications seamlessly

**Actual behavior**
Getting the error
```
Error ----------------------------------

Connection to runner with Pid 466768 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:65473->127.0.0.1:65474: i/o timeout

Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
        windows, 1.0.4.nightly-2018-11-13, e1ca14f
        dotnet (0.1.1), html-report (4.0.7), java (0.7.0), js (2.3.4), python (0.3.5), ruby (0.5.2), screenshot (0.0.1), spectacle (0.1.4), xml-report (0.2.1)
```
**Steps to replicate**
> Observed on Windows
* Create a new project
`gauge init java`
* Run the specifications
`gauge run`
> The above error is encountered

**Version**
```
Gauge version: 1.0.4.nightly-2018-11-13
Commit Hash: e1ca14f

Plugins
-------
html-report (4.0.7.nightly-2018-11-12)
java (0.7.0.nightly-2018-11-07)
js (2.3.4.nightly-2018-10-24)
```
**Note**
It is working as expected in 
```
Gauge version: 1.0.4.nightly-2018-11-12
Commit Hash: a60ffbf

Plugins
-------
dotnet (0.1.1.nightly-2018-10-16)
html-report (4.0.7.nightly-2018-11-12)
java (0.7.0.nightly-2018-11-07)
```
Blocks #1158

**Comment by iskoc9002** [comment]
Hi,
I've the same problem on IntelliJ 2018.3.  get this error in %80 on Debug mode. %50 run mode also. When I use terminal with mvn command, I didn't get an error.

Listening for transport dt_socket at address: 51989

Error ----------------------------------

Connection to runner with Pid 16248 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:51994->127.0.0.1:51998: use of closed network connection

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
	windows, 1.0.4, 3a9a647
	html-report (4.0.6), java (0.7.2), screenshot (0.0.1)
