### ISSUE TITLE
Gauge.WriteMessage should handle null

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1248]
**Expected behavior**
Gauge.WriteMessage should handle null

**Actual behavior**
An exception occurs after which the runner crashes

**Steps to replicate**
* create a gauge-java project
* Modify step Vowels in English language are <vowelString>. implementation to add Gauge.writeMessage(null)
```
    @Step("Vowels in English language are <vowelString>.")
    public void setLanguageVowels(String vowelString) {
        Gauge.writeMessage(null);
        vowels = new HashSet<>();
        for (char ch : vowelString.toCharArray()) {
            vowels.add(ch);
        }
    }
```
* `gauge run` from the command line
**Version**
```
Gauge version: 1.0.4.nightly-2018-11-19
Commit Hash: 5e997d2

Plugins
-------
java (0.7.0.nightly-2018-11-15)
```
> This happens across language runners

> Related to #1158

**Comment by BugDiver** [comment]
The fix has to be done across runners
- [ ]  Java
- [ ] Csharp
- [ ] Dotnet
- [ ] Pytohn
- [ ] Js
- [ ] Ruby
