### ISSUE TITLE
Support for n number of parameters

### ISSUE THREAD

**Issue by Codename-void** [getgauge/gauge#1254]
Hey there!
I am currently using Gauge to offer a Non Regression Testing solution to a client of mine.
Gauge supports step implementation with a set number of parameters, and while this offers sufficient agility in almost every case, having the ability of having steps with an indefinite amount of parameters would be greatly appreciated.

An example of how this could be put in place here:
```Gauge
# This is a test scenario
* Do something cool for "Thomas"
* Brew coffee for "Matthew", "Jeremy" and "Adrian"
* Celebrate
```

This could, in turn, be implemented in the script with `[]` instead of the usual `<>`, these are unlikely characters to appear in a step anyway. You could use them as a regular array or object afterward.
```JavaScript
step("Do something cool for <name>", async (name) => {
  // Something cool for <name>
});
step("Brew coffee for [names]", async (names) => {
  for each (name in names) {
    // Brews coffee for <name>
    console.log(`Brewed coffee for ${name}!`);
  }
});
```

Thanks for this neat tool, it's quite useful for getting things running with a less tech-savvy client!

**Comment by NivedhaSenthil** [comment]
Multiple parameters can be achieved using table parameters. Refer https://docs.gauge.org/latest/writing-specifications.html#step-with-table

Example: 
Spec
```
* Almost all words have vowels
     |Word  |Vowel Count|
     |------|-----------|
     |Gauge |3          |
     |Mingle|2          |
     |Snap  |1          |
     |GoCD  |1          |
     |Rhythm|0          |
```
Step Implementation
``` 
step("Almost all words have vowels <table>", function(table) {
  table.rows.forEach(function (row) {
    assert.equal(numberOfVowels(row.cells[0]), parseInt(row.cells[1]));
  });
});
```

**Comment by zabil** [comment]
For brewing coffee that's

```
# This is a test scenario
* Do something cool for "Thomas"
* Brew coffee for
     |Peeps   |
     |--------|
     |Mathew  |
     |Jeremy  |
     |Adrian  |
* Celebrate
```
and 

```
step("Do something cool for <name>", async (name) => {
  // Something cool for <name>
});

step("Brew coffee for <table>", async (table) => { // pun intended on table
  table.rows.forEach(function (row) {
    // Brews coffee for <peeps>
    console.log(`Brewed coffee for ${row.cells[0]}!`);
  });
});
```

**Comment by Codename-void** [comment]
This seems to work just fine, should have looked closer at the documentation!
Cheers
