### ISSUE TITLE
Feature request: auto retry failed test

### ISSUE THREAD

**Issue by TzurAnv** [getgauge/gauge#1256]
could be useful to have the ability to execute fail scenario automatically at the end of the regular "gauge run" cycle depended on a configurable retry value.
this will help with handling test flakiness.

**Comment by zabil** [comment]
@TzurAnv there a few discussions about flaky tests like https://github.com/getgauge/gauge/issues/1092

Gauge won't be adding this feature. It's best to fix the flakiness.

However, you can use Gauge's has a [rerun failed tests](https://docs.gauge.org/latest/execution.html#re-run-failed-tests) tests features in bash/powershell script after reading [exit codes](https://bencane.com/2014/09/02/understanding-exit-codes-and-how-to-use-them-in-bash-scripts/) from a Gauge run and re-running failed tests till they pass.
