### ISSUE TITLE
Generic in CustomParameterParser

### ISSUE THREAD

**Issue by AUsachov** [getgauge/gauge#1257]
Would be great to have "CustomParameterParser.canParse(ParameterizedType parameterType, Spec.Parameter parameter)" instead of simple Class<?>. This can simplify mapping from table to List<something>

**Comment by BugDiver** [comment]
@AUsachov The Custom parameter parsing is a runner-specific implementation. In this case, my guess is you are referring to `java`  runner's parameter parsing.

**Comment by BugDiver** [comment]
This issue was moved to getgauge/gauge-java#193
