### ISSUE TITLE
Scenario specific context and teardown steps

### ISSUE THREAD

**Issue by RobertaMary** [getgauge/gauge#1259]
### Expected behaviour
Have scenario specific context and teardown steps

### Actual behaviour
As of now, the context and tear down steps should be the same for all scenarios in a spec.

My current test suite requires different context and tear down steps for each scenario. If this wouldn't be an overhead, this is something that I would love to have in gauge. Also, that would be the best business flow for acceptance tests. It would also improve readability.

Workaround for this is to have the context and tear down steps as normal test steps within the scenario itself as first few steps and last few steps respectively. 

Cons of not having scenario specific context and tear down steps:

1. Some of the tear down steps not getting executed due to failure in any of the previous steps (though I can enforce this by @ContinueOnFailure, I don't feel this would give a good framework touch to it).

Advantages of having scenario specific context and tear down steps:

1. Improved readability
2. Better business flow
3. Robust test cases
4. Repeatable testing

### Gauge version
```
Run gauge -v on your system and paste the results here.
```
Gauge version: 1.0.3

Plugins
-------
html-report (4.0.2)
java (0.6.4)
screenshot (0.0.1)
spectacle (0.1.2)

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
