### ISSUE TITLE
Live execution dashboard plugin

### ISSUE THREAD

**Issue by deepthigc** [getgauge/gauge#126]
A plugin that can read the execution events that gauge exposes and provide a live web based dashboard showing the progress of execution, providing a rich UI to view live execution status.

It can host this on a local web-server that can be viewed on a browser.

**Comment by sriv** [comment]
We have [Flash](https://github.com/getgauge/flash) now.

Also, with #783, one could run gauge, stream stdout to any tool that can take JSON and process it in realtime.
