### ISSUE TITLE
Failed to start gauge API

### ISSUE THREAD

**Issue by texnichnyi** [getgauge/gauge#1260]
Hi guys, 
Sometimes I facing with a problem  "Failed to start gauge API: Timed out connecting to 127.0.0.1:port_number."

Gauge version is 1.0.0
Python plugin is 0.3.3
![gauge error](https://user-images.githubusercontent.com/16348425/49230105-94940380-f3f7-11e8-8ffe-578336afd841.png)

**Comment by texnichnyi** [comment]
@Apoorva-GA  I have the latest 

Gauge 1.0.3
Python 0.3.4

on my local machine. The issue reproducible rarely but sometimes is reproducible too. As I understand the latest version can decrease time of reproducing but can not decrease the reproducible number to 0?

**Comment by Apoorva-GA** [comment]
@texnichnyi I am also trying to reproduce the issue, but i wasn't able to. So Asking you to check with latest nightly as I mentioned in the previous comment. 
Please try and let us know if the issue still persists.

**Comment by texnichnyi** [comment]
@Apoorva-GA Thanks. 
I will provide updates related to this in few days.

**Comment by Apoorva-GA** [comment]
@texnichnyi Thanks you.

**Comment by texnichnyi** [comment]
@Apoorva-GA Looks like everything is fine. Thanks.
