### ISSUE TITLE
Other runner events should not be captured

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1264]
**Expected behavior**
Other runner events should not be captured

**Actual behavior**
Events `manifest` and `execution` are still being captured

**Steps to replicate**
* Enable telemetry
* Run `gauge run --env=js-wd`
> The analytics show events `manifest` and `execution`

> Blocks #1251

**Comment by NivedhaSenthil** [comment]
Those are left being captured because if the user does not use any IDE but still actively uses gauge via command line daemon wont be started and we wanted to know 
>Percentage of active user's language runner (JavaScript vs Java vs Python vs Ruby vs Csharp)

Only during execution we find active usage and runner details in that case.

**Comment by sguptatw** [comment]
**Discussion Update**
The events `execution` and `manifest` should not be captured
