### ISSUE TITLE
Print version of plugin when it is installed

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/gauge#1266]
When installing a plugin, you get output like this:

```
>gauge install html-report
........................
Successfully installed plugin 'html-report'.
```
It would be very helpful, especially when looking at server logs, to have the plugin version be included within the printed output. For instance:

```
Successfully installed plugin 'html-report' version 4.0.6.
```

**Comment by zabil** [comment]
@Thunderforge 
You can get this info by running the following command
```
gauge install html-report --log-level debug
```

Please feel free to open the issue and discuss if you had something else in mind.

**Comment by Thunderforge** [comment]
@zabil The main situation that we wanted to include the version was in the case of running Gauge on a VM with no plugins installed. We run `gauge run specs` plus some tag parameters, and then the first thing that Gauge does is install the required plugins (e.g. Java, HTML).

In this use case, adding `--log-level debug` isn't an acceptable workaround because we'll have megabytes of unnecessary logging for our two hour test suite.

It's true that in my original example, it may be useful for `gauge install html-report`. But for the more general example we need, that's not going to work.

Also, it doesn't look like I have the permissions to re-open this issue on GitHub.

**Comment by sriv** [comment]
Gauge attempts to install the plugins specified in `manifest.json` while executing, if it isn't already installed. In this case `--log-level=debug` will apply to execution logs, which is @Thunderforge 's concern.

Reopening this.

**Comment by Debashis9012** [comment]
While installing from the local disk plugin version is not printing.
 
![PluginVersion](https://user-images.githubusercontent.com/46309201/55327817-91457d00-54a8-11e9-84bb-f48b72605693.JPG)

**Comment by Debashis9012** [comment]
This feature has been verified and found fixed with the below build version.

``` gauge-1.0.5.nightly-2019-04-04-darwin.x86_64 ```
