### ISSUE TITLE
NPM Error Code 6 installing latest JS plugin

### ISSUE THREAD

**Issue by jameshd** [getgauge/gauge#1267]
### Expected behavior
JS Plugin should install

### Actual behavior
Installation bombs out. Only managed to install using `sudo`. Likely issue with NPM dependency. 

### Steps to reproduce
1. Run `gauge install js`
2. 
3.

### Gauge version
```
$ gauge -v
Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
No plugins found
Plugins can be installed with `gauge install {plugin-name}`
$ gauge -l debug install js
Gathering metadata for js
Downloading gauge-js-2.3.2.zip
.........
Running plugin hook command => [npm install --production --silent]
Failed to install plugin 'js'.
Reason: exit status 6
Error ----------------------------------

Failed to add plugin js to project : Plugin js is not installed


Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
	linux, 1.0.3, ff6c0c3
	Could not retrieve plugin information.

```

**Comment by zabil** [comment]
@jameshd 

What your
* Node version
* npm version
* Linux distribution with version

**Comment by jameshd** [comment]
It was on OSX or in a Docker Container

Container versions:
`node:10.9`  
`npm 6.2`


Mac Node version 10.12.0
Mac NPM 6.4.1

**Comment by negiDharmendra** [comment]
@jameshd I have tried with a similar configuration and it works fine as expected.
Is it possible for you to share your docker file?

**Comment by BugDiver** [comment]
Closing it for now. Please feel free to reopen  if the issue still exists
