### ISSUE TITLE
Failed to start gauge API

### ISSUE THREAD

**Issue by Borisakov** [getgauge/gauge#1270]
### Expected behavior
Gauge tests should run

### Actual behavior
Gauge Api does not start

### Steps to reproduce
1. Run test from the IntelliJ 
2. It fails

### Gauge version
```
Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
flash (0.0.1)
html-report (4.0.6)
java (0.6.9)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)

IntelliJ Version:
IntelliJ IDEA 2018.3 (Community Edition)
Build #IC-183.4284.148, built on November 21, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Gauge v0.3.14 plugin

```

Log From IntelliJ :
```
Error: Could not find or load main class com.thoughtworks.gauge.GaugeRuntime


process C:\Program Files\Java\jdk1.8.0_144\jre\bin\java.exe with pid 17504 quit unexpectedly. exit status 1

Error ----------------------------------

Failed to start gauge API: Runner with pid 23940 quit unexpectedly(exit status 1).

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
	windows, 1.0.3, ff6c0c3
	flash (0.0.1), html-report (4.0.6), java (0.6.9), screenshot (0.0.1), spectacle (0.1.3), xml-report (0.2.1)
```

**Comment by NivedhaSenthil** [comment]
Seems to be working fine with given versions and defaults. Is gauge installed in custom location?

**Comment by Borisakov** [comment]
A gauge installed with choco.
Software installed to 'C:\Program Files\gauge\bin'

**Comment by shubhamsc** [comment]
@Borisakov We are not able to replicate the issue. Are you getting this error with IntelliJ or command line also? Can you give a try with reinstalling IntelliJ plugin?

**Comment by BugDiver** [comment]
Closing it for now. In case the issue still exists feel free to reopen the issue with relevant information.

**Comment by gayanjanigamage** [comment]
I am having this same issue

**Comment by gayanjanigamage** [comment]
> Closing it for now. In case the issue still exists feel free to reopen the issue with relevant information.

yes Im getting this same error

**Comment by sriv** [comment]
@gayanjanigamage - please share some information for us to look at it:

- output of `gauge -v`
- are you using any build tool (gradle/maven etc.)
- is it replicable when you do a `gauge init` and create a fresh project?
- is there a project for us to run and check? A sample project would be great.

**Comment by gayanjanigamage** [comment]
> @gayanjanigamage - please share some information for us to look at it:
> 
> * output of `gauge -v`
> * is there any error/warning in the `logs` directory?
> * are you using any build tool (gradle/maven etc.)
> * is it replicable when you do a `gauge init` and create a fresh project?
> * is there a project for us to run and check? A sample project would be great.

Sure thanks
Gauge version: 1.0.8
Commit Hash: 28617ea

Plugins
-------
flash (0.0.2)
html-report (4.0.10)
java (0.7.5)
json-report (0.3.3)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)

[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 25 source files to D:\project\workspace\GGMB_Etext_Title_Ingestion_URL_upload\target\classes
[WARNING] /D:/project/workspace/GGMB_Etext_Title_Ingestion_URL_upload/src/main/java/com/maxsoft/webbot/util/screenshot/CustomScreenshotGrabber.java: Some input files use or override a deprecated API.
[WARNING] /D:/project/workspace/GGMB_Etext_Title_Ingestion_URL_upload/src/main/java/com/maxsoft/webbot/util/screenshot/CustomScreenshotGrabber.java: Recompile with -Xlint:deprecation for details.
[WARNING] /D:/project/workspace/GGMB_Etext_Title_Ingestion_URL_upload/src/main/java/com/maxsoft/webbot/common/wrapper/SeleniumWrapper.java: D:\project\workspace\GGMB_Etext_Title_Ingestion_URL_upload\src\main\java\com\maxsoft\webbot\common\wrapper\SeleniumWrapper.java uses unchecked or unsafe operations.
[WARNING] /D:/project/workspace/GGMB_Etext_Title_Ingestion_URL_upload/src/main/java/com/maxsoft/webbot/common/wrapper/SeleniumWrapper.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ MaxSoft-WebBot-Demo ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\project\workspace\GGMB_Etext_Title_Ingestion_URL_upload\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ MaxSoft-WebBot-Demo ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- gauge-maven-plugin:1.3.0:execute (default-cli) @ MaxSoft-WebBot-Demo ---
specs\STG\etext_title_ingestion_url
usage: GaugeJava --<start|init>

process C:\Program Files\Java\jdk1.8.0_191\jre\bin\java.exe with pid 1736 quit unexpectedly. exit status 1
Error ----------------------------------

[Gauge]
Failed to start gauge API: Runner with pid 5988 quit unexpectedly(exit status 1)

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://spectrum.chat/gauge

Your Environment Information -----------
	windows, 1.0.8, 28617ea
	flash (0.0.1), html-report (4.0.5), java (0.6.9), json-report (0.2.2), screenshot (0.0.1), spectacle (0.1.3), xml-report (0.2.0)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.120 s
[INFO] Finished at: 2020-04-09T09:00:52+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.thoughtworks.gauge.maven:gauge-maven-plugin:1.3.0:execute (default-cli) on project MaxSoft-WebBot-Demo: Gauge Specs execution failed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Build step 'Execute Windows batch command' marked build as failure

Using Maven

No sample project

**Comment by zabil** [comment]
> flash (0.0.1), html-report (4.0.5), java (0.6.9), json-report (0.2.2), screenshot (0.0.1), spectacle (0.1.3), xml-report (0.2.0)

This part of the log says you are using an old version of Java please upgrade that.
Also please follow the instructions at.

https://github.com/getgauge/gauge-java/issues/377

**Comment by gayanjanigamage** [comment]
> > flash (0.0.1), html-report (4.0.5), java (0.6.9), json-report (0.2.2), screenshot (0.0.1), spectacle (0.1.3), xml-report (0.2.0)
> 
> This part of the log says you are using an old version of gauge-java plugin please upgrade that.
> Also please follow the instructions at.
> 
> [getgauge/gauge-java#377](https://github.com/getgauge/gauge-java/issues/377)

I have updated the plugins in server system user and in POM accordingly.But it does not updating in jenkins.How can I get updates in to jenkins
