### ISSUE TITLE
Language runner processes are not killed even after the IDE is closed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1271]
**Expected behavior**
When the IDE is closed the runner process must get killed

**Actual behavior**
Runner processes are not killed even after the IDE is closed

**Steps to replicate**
* Open a `gauge-dotnet` project in the IDE and work on it
* Close it
> Repeat this for a few projects. Open the task manager you will see the relevant language runner process still running
Observed with `gauge-java` and `gauge-dotnet`

**Comment by sguptatw** [comment]
‘ps -ef | grep java’ should give the java process alive

**Comment by Apoorva-GA** [comment]
Could you please update the gauge, gauge-java, gauge-vscode versions on which you are facing this issue?

**Comment by Apoorva-GA** [comment]
The issue with respect to java processes not being killed should be fixed as part of https://github.com/getgauge/gauge-java/issues/196. 

Can we please track `.net` separately?

**Comment by sguptatw** [comment]
Tracking process not getting killed in dotnet issue with https://github.com/getgauge/gauge-dotnet/issues/32

**Comment by Apoorva-GA** [comment]
Should be available in gauge-java nightly >= 10/12/18
