### ISSUE TITLE
How to create a for-loop in a scenario

### ISSUE THREAD

**Issue by delmaamoun** [getgauge/gauge#1274]
I have a case where I am testing a monitoring system which sends the same exact type of data from 17 different devices, and each set of readings is displayed in a separate page. I figure the easiest way to implement this is by using a for-loop or somehow tell a concept that it has to run multiple times through the spec. The only way I have come across to do it with gauge is through a table that looks really silly (see below).
I don't know if there is a more elegant way to do this already but there are a lot of cases where loops don't just belong inside the code.

### Expected behavior
```
* Check readings <17 times>
```

### Actual behavior
```
* Check readings
     |Count|
     |------|
     |1| 
     |2|
     |3|
     |4|
     |5|
     |6|
     |7|
     |8|
     |9|
     ...
```

### Gauge version
```
Gauge version: 1.0.3
```

**Comment by ajoecker** [comment]
wouldnt it make more sense like

```
* Check deviceA for xyz
* Check deviceB for ybc
```
or that as a table ?

**Comment by delmaamoun** [comment]
So if there is a master alarm that gets triggered, all the devices should show that this alarm has been tripped. Each alarm is displayed on its own page, and I need to go over all the pages to make sure they show that alarm has been tripped. So it would be like
```
* Check device 1 alarm is tripped
* Check device 2 alarm is tripped
* Check device 3 alarm is tripped
...
```
or a table with just the device's index.
As to the measurements, for testing, we have to force the values sequentially per device (we don't have the real system to test against), and in this case it makes more sense to use a single dataset to simplify the checks instead of having a huge table for all the devices and different measurements (to make sure that device 1 is not showing the data for device 2 instead) which would make data management a nightmare.
So this loop would:
```
* trip alarm
* force measurements
* check tripped alarm and measurements match
* un-trip alarm and return measurements to normal
* check forced measurements aren't there anymore.
```
That's why it makes more sense to me to loop on the concept level

**Comment by ajoecker** [comment]
not sure that I got your use case completely, so bare with me, but a general fear is to introduce logic into the concept level. Personally I see the specs as a bare text description of steps and I would highly advice to keep it that way. Programming should happens where the actually code is and a pure description of a process should lack that ... imo . it is like opening the gate to hell

**Comment by BugDiver** [comment]
@delmaamoun  You can always implement the loop in the implementation.
In your case -
Instead  of 
```
* Check readings
     |Count|
     |------|
     |1| 
     |2|
     |3|
     |4|
     |5|
     |6|
     |7|
     |8|
     |9|
```
you can hacve a step
`Check readings "17"`

with implementation
```python
@step("Check readings <cound>")
def check_readings(count):
    for device_number in range(count):
        assert.....

```

**Comment by delmaamoun** [comment]
Yeah I started out like that but it would still make more sense to me on the concept level since a concept is a set or reusable steps after all. I should be able to use it consecutively

**Comment by zabil** [comment]
Unfortunately it's quite challenging and tricky to implement logic or loops in specifications. It's better handled vis the step implementations.

Closing this for now. But please feel free to discuss this further.
