### ISSUE TITLE
How to set screenshot_on_failure property at runtime

### ISSUE THREAD

**Issue by vinodbhardwaj1** [getgauge/gauge#1276]
I have common project for web and api. I need screenshot_on_failure=true for web only while running api test; this property should be false under env->default.properties.

How to update that at run time.

### Actual behavior
I'm unable to change property value at run time.

### Steps to reproduce
1. set screenshot_on_failure=true in env->default.properties.
2. run web test and api tests. In both attempts screen shots will be captured.

### Gauge version 1.0.0
```
Run gauge -v on your system and paste the results here.
```

**Comment by sriv** [comment]
Gauge allows you to override project configuration via Environment Variables.

So you could do `screenshot_on_failure=false gauge run specs/api` to prevent screenshots for API tests.

ref https://docs.gauge.org/latest/configuration.html#precedence-of-environments
