### ISSUE TITLE
Gauge+Taiko usage should be captured

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1277]
**Expected behavior**
Gauge+Taiko usage should be captured

**Actual behavior**
Only OS and language runner details are captured

**Steps to replicate**
* Open a `gauge-taiko` project.
> The analytics data is showing the event as `language runner, OS`. It does not capture taiko usage.

**Version**
```
gauge-core - 1.0.4.nightly-2018-12-14
```
> Blocks #1251

**Comment by sriv** [comment]
`use_test_ga` is now being honoured. So you should see some information in the test analytics instance.

**Comment by sguptatw** [comment]
This issue was moved to getgauge/gauge-js#180
