### ISSUE TITLE
Shouldn't get messages unwanted Proto messages while creating report

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1279]
**Expected behavior**
Shouldn't get messages unwanted Proto messages while creating report

**Actual behavior**
<img width="1323" alt="screen shot 2018-12-17 at 9 36 09 am" src="https://user-images.githubusercontent.com/6310197/50066081-c66edd80-01df-11e9-8d25-bb3850641b7f.png">

**Steps to replicate**
* Run gauge-tests on CI 
> Observe https://build.gauge.org/go/tab/build/detail/Java-FT/1513/specs/1/windows towards the end

**Version**
```
Gauge version: 1.0.4
Commit Hash: 90b8b48

Plugins
-------
html-report (4.0.7)
java (0.7.0)
```
> Blocks #1239

**Comment by sriv** [comment]
The `Received SuiteExecutionResultItem for` occurs only when the log level is `debug`. (`GAUGE_LOG_LEVEL=debug`). This is expected. 

The builds set the log level to `debug` in this case.
