### ISSUE TITLE
Configure old templates URL to redirect to https://templates.gauge.org

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1281]
**Proposed behavior**
Configure old templates URL to redirect to https://templates.gauge.org

**Actual behavior**
For the old templates URL we get a `404`

> Currently, the user has to upgrade the gauge configuration manually `gauge_templates_url = https://templates.gauge.org`

**Comment by Debashis9012** [comment]
The above URLs has been verified.
