### ISSUE TITLE
Publish diagnostics should not compute code when Gauge is invoked as an LSP server

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1283]
**Proposed behavior**
When gauge is run as LSP server, diagnostics it can pass parameter like `hide-diagnostics`. In this case it should not compute the code required to generate step.
Furthermore, when the gauge is run as an LSP server codeAction should compute the code.

**Current behavior**
Code is computed when publish diagnostics. When code action is invoked it is copied from the diagnostics.

**Why this optimization?**
Diagnostics are published quite often(file open,close, change,file added or deleted). Many a times we have seen IDE stops working after an edit. This is one of the optimizations we can try.
Furthermore, code action is invoked just before user can implement a step making it an ideal place to compute the code value.

**Why retain an option to give back generated code in diagnostics?**
On the console, we print the default implementation for unimplemented steps unless the user chooses otherwise.

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
