### ISSUE TITLE
The LSP server must respond consistently

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1284]
_From @sguptatw on December 20, 2018 15:2_

**Expected behavior**
The server response should be consistent

**Actual behavior**
The server is sending `"newText":"Object argBefore, String param"` sometimes - 
https://build.gauge.org/go/tab/build/detail/Java-LSP-Tests/55/no-wd-load/1/windows 
and it is sending `"newText":"Object argParam, String param"` - 
https://build.gauge.org/go/tab/build/detail/Java-LSP-Tests/55/no-wd-load/1/darwin. 

This can be observed by comparing the response message printed on the CI console of windows and linux for the scenario `Refactor to add a parameter before existing param` for the same run. 

Also, the result returned by the server for java-wd is `"newText":"Object argBefore, String param"` https://build.gauge.org/go/tab/build/detail/Java-LSP-Tests/55/wd-load/1/linux for the same run.

**Steps to replicate**
* Re-trigger the LSP tests for java

_Copied from original issue: getgauge/taiko#298_

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
