### ISSUE TITLE
Unable to use csv file as parameter in gauge scenario

### ISSUE THREAD

**Issue by SriramIyengar2012** [getgauge/gauge#1290]
We have a requirement where in there is an ask to read different csv files and execute scenarios
each scenario in a spec has different csv file
We currently tried giving a parameter as table: csv file for a scenario but does not work, it only takes a table

Any suggestions here

### Expected behavior
Feel that it would be good to have a spec taking multiple scenario wise csv files

### Actual behavior
Got an error while executing the test case

### Steps to reproduce
1. Create a gauge spec 
2. Create a scenario inside the spec
Test
---------
table: test.csv
* get data <name> (this name is a header for the csv file)

### Gauge version

Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
csharp (0.10.4)
flash (0.0.1)
html-report (4.0.6)
screenshot (0.0.1)

**Comment by SriramIyengar2012** [comment]
Again commenting with steps to reproduce, it not very clear

1. Create a Gauge spec
2. Create two scenarios inside the spec named  Test and Test2

Test Specification
===================

Test
--------------
table: test.csv

* get data<name> (this name is a header in the csv file present for this scenario)

Test 2
---------------------------------------
table: test2.csv

* get address <address> (this addressis a header in the csv file present for this scenario)


We need some help in implementing this approach

**Comment by nehashri** [comment]
@SriramIyengar2012 Table driven scenarios is still an experimental feature. If you still want to use it, you can follow [this](https://github.com/getgauge/gauge/issues/111#issuecomment-431783357) comment to enable the feature.

**Comment by SriramIyengar2012** [comment]
@nehashri thank you for the response i tried this , it is working but would like to know if i can use csv instead of the table for each scenario

**Comment by nehashri** [comment]
@SriramIyengar2012 Yes you should be able to do this.

**Comment by nehashri** [comment]
@SriramIyengar2012 Just found that there is an issue with this after all. It is not working as expected.

**Comment by sriv** [comment]
This feature (table driven execution of scenario) does not (yet) work with external tables.

**Comment by SriramIyengar2012** [comment]
is there any plan to include this functionality

**Comment by zabil** [comment]
> is there any plan to include this functionality

Not at the moment. We'll take a look at this once we decide to finish table driven execution of scenarios.

**Comment by SriramIyengar2012** [comment]
@zabil thank you for the update

**Comment by TheBaekoning** [comment]
Hi. Just was wondering what the current status of having scenario level table driven execution capabilities is at? I'm working for a major airline and we are looking to incorporate Gauge into our test automation and would like to know this. Any help would be appreciated. Thanks.

**Comment by sguptatw** [comment]
@TheBaekoning Scenario level table is toggled off by default. It is an experimental feature. You can use it by setting env `allow_scenario_datatable` more details about it is [here](https://github.com/getgauge/gauge/issues/111)

**Comment by TheBaekoning** [comment]
Sorry I should specify I meant to inquire about CSV driven data tables. The inline works beautifully.

**Comment by nehashri** [comment]
@TheBaekoning This is still an issue and we will look at resolving this soon.

**Comment by delmaamoun** [comment]
I just want to highlight a couple of issues with having a csv file as a table for a scenario to put on your radar:

- I get a ParseError for the scenario that has the data table: `[ParseError] C:\Code\specs\test.spec:9 Scenario should have atleast one step => ''`
- running the single scenario for the csv file works, running the entire spec breaks completely (just the ParseError above)
- running multiple scenarios specifically would run the scenarios but not in the correct order and they all run as one scenario
- in vscode, the debug/run codelens disappears for the entire spec

**Comment by zabil** [comment]
Gauge will not be implementing this feature. A workaround would be generating the csv file outside gauge to the location referred to in the gauge specs before running them.
