### ISSUE TITLE
Fix documentation for scenario versus specification non-markdown syntax

### ISSUE THREAD

**Issue by scraymondjr** [getgauge/gauge#1292]
Documentation at https://docs.gauge.org/latest/writing-specifications.html#specification-heading states 
```
Spec Heading
============
```
and 
```
Scenario heading
================
```
though one of them should use `-----------` (I think).

**Comment by Apoorva-GA** [comment]
@scraymondjr Thanks for pointing this out. 
Fix is available as part of [commit.](https://github.com/getgauge/docs.gauge.org/commit/2d9e021fb305b7324cc9d84f8eb41d3cd9336cb7)
