### ISSUE TITLE
When LSP server is started check if language runner is installed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1294]
**Expected behavior**
When LSP server is started check if language runner is installed

**Actual behavior**
It says `Current runner does not support LSP`

**Steps to replicate**
* Ensure language runner java is not installed
* Open the gauge-tests project
* The logs say the runner does not support LSP
> [Suggestion] When LSP server is started check if language runner is installed else install it like it is done during `gauge run`. Any errors in this should be propagated to the IDE.

**Version**
```
Gauge version: 1.0.4.nightly-2018-12-25
Commit Hash: fe5e7da
```

**Comment by Debashis9012** [comment]
Working as excepted and tested with the below version:
```
Gauge version: 1.0.5.nightly-2019-02-06
Commit Hash: 3bb3fb0

Plugins
-------
dotnet (0.1.1.nightly-2019-01-29)
html-report (4.0.7.nightly-2019-01-11)
java (0.7.1.nightly-2019-02-05)
```
