### ISSUE TITLE
Specs execute even if the before suite hook fails

### ISSUE THREAD

**Issue by apoorvam** [getgauge/gauge#13]

**Comment by h2grover** [comment]
Hi I am facing a similar issue when I execute tests in parallel.

**Comment by sriv** [comment]
hi @h2grover , can you please provide some details? A sample project would be great.

**Comment by asarkisian** [comment]
@sriv I am facing a similar issue. Is it possible I can provide you a sample project to look at? I suspect it is an issue with Gauge itself however I cannot be certain.

**Comment by sriv** [comment]
hi @asarkisian - a sample project would help debug the issue for sure. Would you be able to share something that doesn't have anything confidential?

**Comment by asarkisian** [comment]
Hi @sriv Absolutely. I removed all confidential content and only put in generic sample tests. 

Repo: https://github.com/asarkisian/gauge_test_app

**Here is some info on my system:**

OS: Mac Catalina 10.15.7
Python3 Ver: 3.9.2
Python3 Path: /usr/bin/python3, /usr/local/bin/python3
Gauge version: 1.1.7
Plugins
-------
html-report (4.0.12)
python (0.3.14)
screenshot (0.0.1)

**OUTPUT:**
`➜  test_app git:(master) gauge run specs
Python: 3.9.2
Error occurred while waiting for runner process to finish.
Error : exit status 1

  Error Message: transport is closing
  Stacktrace:


  Error Message: Runner is not Alive
  Stacktrace:

Successfully generated html-report to => /Users/armondsarkisian/Desktop/test_project/test_app/reports/html-report/index.html

Failed to kill Runner: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:51812: connect: connection refused"`

**Log Output:**
<img width="1063" alt="Screen Shot 2021-03-17 at 8 40 14 AM" src="https://user-images.githubusercontent.com/19278388/111496310-71dba500-86fd-11eb-802f-0c0badc41d96.png">
