### ISSUE TITLE
GaugeScreenshots.Capture() is not taking screenshot and not storing in file

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/gauge#1300]
Objective:
Take screenshot using GaugeScreenshots.Capture();

### Expected behavior
Gauge should take screenshot and provide link in HTML report

### Actual behavior
Gauge is not taking any screenshot and not giving any error message as well.

### Steps to reproduce
1. Go to your step and write code GaugeScreenshots.Capture();
2. Step passes successfully but screenshot is not generated in "images" folder in html-reports

### Gauge version
Gauge version: 1.0.2
Commit Hash: b4288bb

Plugins
-------
csharp (0.10.5)
dotnet (0.1.0)
html-report (4.0.6)
screenshot (0.0.1)

**Comment by sriv** [comment]
Screenshot is not saved to disk. It is sent to the html-report plugin as a base64 encoded string, and html-report also renders it as such.

Please see [this StackOverflow answer on the topic](https://stackoverflow.com/a/54059164), I believe you are looking for something similar?
