### ISSUE TITLE
Undefined step definitions in IntelliJ

### ISSUE THREAD

**Issue by sanjindemir** [getgauge/gauge#1305]
There is def an issue with Gauge plug in. I tried several times installing it via IntelliJ and suggested steps:

https://github.com/getgauge/Intellij-Plugin/blob/master/README.md

Build is successful, but sample spec shows each step as Undefined.

**Comment by sriv** [comment]
Hi, did you get the issue resolved? If so, please do share your findings.

**Comment by sriv** [comment]
Gauge-Intellij plugin requires `gauge` to be installed, as it communicates to it. However, it should have reported an error to that effect. Please let us know if that wasn't the case, and we'll investigate it. Thank you.
