### ISSUE TITLE
Rerun for data driven specs should only be executed on data rows which failed

### ISSUE THREAD

**Issue by dnet1** [getgauge/gauge#1307]
### Expected behavior
"gauge run --failed" for data driven specs should only use data table rows on which previous run failed.

### Actual behavior
"gauge run --failed" for data driven specs triggers tests for all the rows in data table (so the tests on data rows which were successful in previous run will be triggered again)

### Steps to reproduce
1. Run spec with data driven execution where some of the tests pass and some fail
2. Rerun "gauge run --failed"
3. All the tests will be executed (including the ones which succeeded in step 1)

### Gauge version
```
Gauge version: 1.0.3

Plugins
-------
html-report (4.0.6)
java (0.6.9)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)
```

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
