### ISSUE TITLE
Add a new step implementation in a new file - the step is shown as unimplemented

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1308]
**Expected behavior**
Add a new step implementation in a new file - the step is shown as implemented

**Actual behavior**
Add a new step implementation in a new file - the step is shown as unimplemented

**Steps to replicate**
* Create a `gauge-java` project
* Add a new step
* Give the implementation in a new file
* Go back to the spec file
* Close the impl file.
* Go back to the spec file
* The step is shown as unimplemented

**Version**
```
Gauge version: 1.0.4.nightly-2018-12-03
Commit Hash: 62a48e5

Plugins
-------
java (0.7.0.nightly-2018-12-04)
```

> Related issue https://github.com/getgauge/gauge-vscode/issues/83

**Comment by sguptatw** [comment]
Moved this issue to https://github.com/getgauge/gauge/issues/1308

**Comment by sguptatw** [comment]
Moved this issue to https://github.com/getgauge/gauge/issues/1308

**Comment by nehashri** [comment]
To fix this, there needs to be a change in the implementation of these requests in the runner. Here is a list of runners which support lsp protocol as of now and the PR's raised against them. This issue needs to be verified against each of these 

| Langauge | Nightly Date | Verified | 
|-----------|--------------|---------|
| Java | >= 17-01-2019 | <ul><li>- [ ] </li></ul> |
| JavaScript |  >= 18-01-2019 | <ul><li>- [ ] </li></ul> |
| Python |   | <ul><li>- [ ] </li></ul> |
| Ruby |  >= 23-01-2019 | <ul><li>- [ ] </li></ul> |
| .Net core | | <ul><li>- [ ] </li></ul> |

**Comment by Debashis9012** [comment]
> Blocks https://github.com/getgauge/gauge-java/issues/243

**Comment by Debashis9012** [comment]
This is reproducible for dotnet language.
```
Gauge version: 1.0.5.nightly-2019-02-15
Commit Hash: 48d032f

Plugins
-------
dotnet (0.1.2.nightly-2019-02-14)
```

**Comment by Debashis9012** [comment]
This has been verified against the below version.
``` 1.0.5.nightly-2019-02-22 ```
