### ISSUE TITLE
Failed to start gauge API : specific to Windows 10

### ISSUE THREAD

**Issue by SureshRajpurohit85** [getgauge/gauge#1312]
Expected results : gauge should execute below command 
'gauge run specs'

Actual results : 
Failed to start gauge API: Runner with pid 24728 quit unexpectedly(exit status 1).
Environment Information -----------
        windows, 1.0.3, ff6c0c3
        html-report (4.0.6), java (0.6.9), screenshot (0.0.1)

**Comment by sriv** [comment]
hi @SureshRajpurohit85 - is there any detail in the logs? please check the `logs` directory.

alternatively, is there a project that I can use to try and replicate the issue?

**Comment by SureshRajpurohit85** [comment]
Hi , i have create a sample project using ,

mvn archetype:generate -B -DarchetypeArtifactId=maven-archetype-archetype -DgroupId=com.sample.maven -DartifactId=UIautomation -Dversion=1.0.0.

**Comment by SureshRajpurohit85** [comment]
[uiautomation.zip](https://github.com/getgauge/gauge/files/2781635/uiautomation.zip)

**Comment by sriv** [comment]
I think there are two issues with the project:

- edit `pom.xml`, set lines `47-48` to 

```
    <source>10</source>
    <target>10</target>
```

- run `mvn test` ( since this is a `mvn` project, you cannot directly run `gauge run specs`)

Post this I see the specs are running, but there is a failure caused by assertion.

**Comment by sriv** [comment]
If you do not have anything sensitive, accessing your project is the quickest way for me to help.

I would recommend posting a simple project where you see this issue. thanks.

**Comment by NivedhaSenthil** [comment]
@SureshRajpurohit85  is there any updates on this ?
