### ISSUE TITLE
Allow multiple repository for plugins

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#1314]
### Expected behavior
Gauge should allow user to configure multiple urls for plugin repository. The plugin should be fetched in priority set by the order in which the repository is listed. ex:

`gauge_repository_url= https://example.com/plugins, https://downloads.gauge.org/plugins` should use `example.com` repository and only fallback to `downloads.gauge.org`.

- Even if a lower priority repository has a higher compatible plugin version, the precedence should be given to the plugins repository.
- Inaccessible/incomplete repository is skipped and the next repository should be checked.
- update checks/update install should also use the same priority

### Actual behavior
there is no way to specify multiple repositories at the moment.

### Gauge version
```
Gauge version: 1.0.4
Commit Hash: e386438

Plugins
-------
csharp (0.10.6.nightly-2018-12-03)
dotnet (0.1.1.nightly-2018-12-11)
flash (0.0.1)
go (0.1.2)
html-report (4.0.7)
java (0.7.0)
js (2.3.4)
python (0.3.4)
reportportal (1.0.0)
ruby (0.5.2.nightly-2018-12-11)
screenshot (0.0.1)
spectacle (0.1.4.nightly-2018-12-04)
xml-report (0.2.2.nightly-2018-12-11)
```

**Comment by zabil** [comment]
Closing this as Gauge will move to a one plugin per repository model that is decentralised and configurable.
