### ISSUE TITLE
[Spike] Gauge + Taiko + BrowserStack integration

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#1316]

**Comment by NivedhaSenthil** [comment]
These [APIs](https://www.browserstack.com/javascript-testing-api) can be useful in creating a plugin that could launch browser and Taiko can connect to it.

**Comment by NivedhaSenthil** [comment]
There seems to be no straight forward way to connect to browser in remote debugging mode, which is what Taiko uses to control browser using CDP. All automation tools supported by browserstack are based on Selenium and they have first class support for webdrivers. Testcafe takes advantage of localised test running in browserstack which requires a proxy server setup. Need to figure out from browserstack team if connecting to browser in debugging mode is possible.

**Comment by NivedhaSenthil** [comment]
Currently not possible to connect to browser on browserstack in debug mode. Hence cant run taiko scripts in there

**Comment by diwannikhil** [comment]
Hi,
How to perform multi-browser and multi-device testing using Taiko?
Any help will be appreciated, thanks!

**Comment by zabil** [comment]
Please read https://github.com/getgauge/taiko/blob/master/docs/FAQ.md for info related to support.
