### ISSUE TITLE
[Spike] Gauge + GraphQL + API testing

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#1317]
Write a sample test suite to test against GraphQL api.

**Comment by nehashri** [comment]
Some Expectations from the spike:
* Does Gauge + GraphQL + API testing work well. Is writing tests easy?
* Can any enhancements be made to Gauge or its plugins to write these tests better?
* Are there any blockers for writing such tests seamlessly?
* A example test suite demonstrating this integration if possible.

Note : implementation of feature or enhancements in Gauge or its plugins is not expected from the spike. Please creating supporting cards for these.

**Comment by negiDharmendra** [comment]
[Here](https://github.com/getgauge-examples/sample-graphql-gauge-specs) is a sample project to demonstrate how to write GraphQL API tests using Gauge and Gauge-JS.
