### ISSUE TITLE
Gauge spec does not accept parameters that start with File

### ISSUE THREAD

**Issue by SriramIyengar2012** [getgauge/gauge#1321]
We have spec files that use csv file at the top as
table:test.csv

We have a below step in many scenarios

![image](https://user-images.githubusercontent.com/46358191/51601869-61ed1f80-1efd-11e9-8e25-c0e010e21f5d.png)

FileLocation and FIlename  data are from the csv file.
These parameters are never recognized, we actually had to change them to a different name
Anything parameter that starts with File does not work

### Expected behavior
Parameter names starting with File needs to be recognized

### Actual behavior
Gauge does not recognize we eventually had to change the name
Presume this is due File being a keyword in gauge

### Steps to reproduce
1.Create a csv file named test.csv with columns FileLocation and FileName
2. create a gauge spec and have this at the top table:test.csv
3. Create a scenario Name Test
4. Create Step - Go to<FileLocation> 
5. Create another Step - Select <FileName>
7. Write an implementation, the parameters are not recognized

Gauge version
Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
csharp (0.10.4)
flash (0.0.1)
html-report (4.0.6)
screenshot (0.0.1)

**Comment by sriv** [comment]
Can you please check what is the output of `gauge validate specs` in this project?
