### ISSUE TITLE
Executing gauge with incorrect parameters should return non-zero exit code

### ISSUE THREAD

**Issue by nvborisenko** [getgauge/gauge#1324]
```
gauge run --blabla
```

gauge doesn't recognize `blabla` parameter, shows help message, but returns 0 as exit code.

**Comment by sriv** [comment]
It should be a Non-zero exit code, IMO.

Some observations:

- `gauge init blah` returns exit-code: 1 (invalid plugin/template)
- `gauge foo` returns exit-code:0, but prints `Error: unknown command "foo" for "gauge"`
- `gauge run --foo` return exit-code:0, but prints help for `gauge run`.

**Comment by Debashis9012** [comment]
This issue has been verified with the below version
``` 1.0.5.nightly-2019-02-22 ```
