### ISSUE TITLE
Getting Timed out connecting issue with gauge on Window Server 2012 std.

### ISSUE THREAD

**Issue by manojTest** [getgauge/gauge#1326]
### Expected behavior
Gauge should not throw any error on Window Server 2012 std.

### Actual behavior
Getting Timed out connecting issue with gauge on Window Server 2012 std.

### Steps to reproduce
we are using  gauge-maven-plugin:1.4.1 plugin to run our tests with 5 chrome browser instances on Windows Server 2012 standard edition.
However the once we start our test it is giving us following error.

0, Failures: 0, Errors: 0, Skipped: 0 [INFO] [INFO] --- gauge-maven-plugin:1.4.1:execute (test-chrome-selfserve) @ mindtickle-test-automation --- Executing in 5 parallel streams. Timed out connecting to [::]:49905 panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x0 addr=0x58 pc=0x7067c9] goroutine 673 [running]: github.com/getgauge/gauge/conn.Write(0x0, 0x0, 0xc042146100, 0x8, 0x10, 0xc0420f6848, 0xc71158) src/github.com/getgauge/gauge/conn/network.go:107 +0x99 github.com/getgauge/gauge/conn.writeDataAndGetResponse(0x0, 0x0, 0xc042146100, 0x8, 0x10, 0x0, 0x0, 0x3f, 0x0, 0x0) src/github.com/getgauge/gauge/conn/network.go:80 +0x5e github.com/getgauge/gauge/conn.getResponseForGaugeMessage(0xc042ccc000, 0x0, 0x0, 0xc0421cc1e0, 0xc0421cc2a0, 0x0, 0x0) src/github.com/getgauge/gauge/conn/network.go:137 +0x1ed created by github.com/getgauge/gauge/conn.GetResponseForMessageWithTimeout src/github.com/getgauge/gauge/conn/network.go:163 +0xe0

### Gauge version
Gauge plugin 0.9.7 (installed on Windows Server 2012 standard)
Gauge maven dependency - 1.4.1
```
Run gauge -v on your system and paste the results here.
```

**Comment by sriv** [comment]
Hi,

- You are using an older version of gauge. The latest released version is `1.0.4`. Can you please try upgrading ?

- Is `gauge-java` plugin installed on the target machine? (Please run `gauge -v` and share the output if possible)

**Comment by manojTest** [comment]
Hi sriv,
We have upgraded the version to 1.0.4 . However the behaviour is inconsistent.
After 2-3 try it is launching 5 chrome instances.
Following is an output of failure try
[INFO]
[INFO] --- gauge-maven-plugin:1.4.1:execute (test-chrome-selfserve) @ mindtickle-test-automation ---
Error ----------------------------------

Connection to runner with Pid 5996 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:52130->127.0.0.1:52131: use of closed network connection

Get Support ----------------------------
    Docs:          https://docs.gauge.org
    Bugs:          https://github.com/getgauge/gauge/issues
    Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
    windows, 1.0.4, 3a9a647
    html-report (4.0.6), java (0.6.9), screenshot (0.0.1)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.496 s
[INFO] Finished at: 2019-01-28T18:55:52+05:30

gauge -v output as below
Microsoft Windows [Version 6.2.9200]
(c) 2012 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>gauge -v
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.6)
java (0.6.9)
screenshot (0.0.1)

**Comment by sriv** [comment]
That is strange. Could you try running the example in the same environment?

`gauge init java_maven_selenium` should give you the example project. I'd like to understand if this is caused by an issue in gauge, project configuration or the environment.

thanks.

**Comment by sriv** [comment]
Thanks for sharing the finding. Let me see if I can get hold of a VM with windows 2012, and I'll take a shot at replicating the issue.

FWIW - we use gauge to test gauge and in our appveyor CI, the VMs are [Windows Server 2012](https://www.appveyor.com/docs/windows-images-software/) machines, and you can see the tests run ok. (https://ci.appveyor.com/project/getgauge/gauge/builds/21936766)

**Comment by Apoorva-GA** [comment]
@manojTest Are you still facing the issue?

I tried replicating the issue using a VM with windows 2012 & windows 10. 
Changed the pom as mentioned above. But was able to successfully execute the spec.
The program got executed in 5 parallel streams.

**Comment by sumitkiit** [comment]
Error ----------------------------------

Connection to runner with Pid 8840 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:55199->127.0.0.1:55209: use of closed network connection

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
	windows, 1.0.5, 562f036
	csharp (0.10.5), html-report (4.0.8), java (0.7.2), json-report (0.3.1), screenshot (0.0.1), xml-report (0.2.1)

Process finished with exit code 1

**Comment by sumitkiit** [comment]
> Error ----------------------------------
> 
> Connection to runner with Pid 8840 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:55199->127.0.0.1:55209: use of closed network connection
> 
> Get Support ----------------------------
> Docs: https://docs.gauge.org
> Bugs: https://github.com/getgauge/gauge/issues
> Chat: https://gitter.im/getgauge/chat
> 
> Your Environment Information -----------
> windows, 1.0.5, [562f036](https://github.com/getgauge/gauge/commit/562f0362432b4ce8ab021b7b1be9de3b634755e4)
> csharp (0.10.5), html-report (4.0.8), java (0.7.2), json-report (0.3.1), screenshot (0.0.1), xml-report (0.2.1)
> 
> Process finished with exit code 1

Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
csharp (0.10.5)
html-report (4.0.8)
java (0.7.2)
json-report (0.3.1)
screenshot (0.0.1)
xml-report (0.2.1)

**Comment by nehashri** [comment]
@sumitkiit Are you facing this issue in Windows Server 2012? 
Also, if possible, can you share a sample project to help replicate this issue.
