### ISSUE TITLE
Suggestion for getgauge.io

### ISSUE THREAD

**Issue by rogeriochaves** [getgauge/gauge#133]
What I most liked about gauge, and what convinced me to try it was seeing the tests being written with markdown, so, just as a suggestion, I think it could be nice to add a screenshot of that to the main page.

![](http://getgauge.io/documentation/user/current/specifications/images/spec.png)

**Comment by prateekbaheti** [comment]
Thanks for the suggestion. We will make that addition.

**Comment by prateekbaheti** [comment]
This issue was moved to getgauge/getgauge.github.io#6
