### ISSUE TITLE
Set an environment variable with gauge's current environment value

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge#1333]
While using Gauge's [environment](https://docs.gauge.org/latest/configuration.html#id1) feature.
There must be a way to access the value of the environment used for execution from the runner.

For e.g

```
$ gauge run specs --env local
``` 

In Javascript
```
console.log(process.env.GAUGE_ENVIRONMENT) // Prints "local"
```

#### WORKAROUND 

Set the environment variable and use it for execution for e.g. in bash

```
$ export GAUGE_ENVIRONMENT=local
$ gauge run specs --env $GAUGE_ENVIRONMENT
```

**Comment by Debashis9012** [comment]
This has been verified and found fixed with the below version:
```Gauge version: 1.0.5.nightly-2019-03-28 ```

**Comment by delmaamoun** [comment]
Hi, I am using this and it's working on windows but not linux:
`env = os.getenv("GAUGE_ENVIRONMENT")` returns a value when running on windows but not on linux.
If it's not set in the env. variable, where else can I know which env I'm running from the code?

Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
flash (0.0.1)
html-report (4.0.8)
python (0.3.5)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.2)

**Comment by zabil** [comment]
Please try using the following and see if it works (notice the lower case)
```
env = os.getenv("gauge_environment")
```

**Comment by zabil** [comment]
Thanks for pointing this out.

Environment variables, by convention should be upper case. Gauge is currently not setting the values as upper case and this must be fixed to follow conventions.

**Comment by zabil** [comment]
> Environment variables, by convention should be upper case. Gauge is currently not setting the values as upper case and this must be fixed to follow conventions.

Won't be doing this as this will break backwards compatibility and not predictable across platforms.

**Comment by x80486** [comment]
I think `GAUGE_ENVIRONMENT` can be added, maintain both for a while, and set a path for `gauge_environment` deprecation.
