### ISSUE TITLE
Make step and concept parameter values available to Gauge API clients

### ISSUE THREAD

**Issue by glalejos** [getgauge/gauge#1335]
Hi,

This issue was originated in the discussion group:
* https://groups.google.com/d/msg/getgauge/BDZ2CqOHDDc/9qkaDRMuFgAJ

### Expected behavior
The value of step and concept parameters should be sent to Gauge API clients upon specs request (`Api.APIMessage.APIMessageType.SpecsRequest`).

### Actual behavior
Only the _name_ of the parameter is sent to the Gauge API client.

### Steps to reproduce
1. Create a scenario with a parameterized step or concept. For example: `* Login as "test_user_0001"`
2. Issue a message of type `Api.APIMessage.APIMessageType.SpecsRequest` from a Gauge API client.
3. The corresponding `Api.APIMessage.APIMessageType.SpecsResponse` doesn't contain the value `test_user_0001`.

### Gauge version
```
Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
html-report (4.0.5)
java (0.6.8)
screenshot (0.0.1)
```

**Comment by glalejos** [comment]
Hi! Is there any update on this issue?
Thanks!

**Comment by zabil** [comment]
We haven't picked this up yet.
If you are comfortable with golang we can help you implement a pull request. Otherwise this will come out most probably in release 1.0.6

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
