### ISSUE TITLE
Specifications with separate underlying implementations for iOS, Android and APIs

### ISSUE THREAD

**Issue by singharsh** [getgauge/gauge#1336]
My problem/use case:
I want to implement user journey specifications for our iOS and Android apps.  Ideally it will be great if there is a way to specify user journey once and have 3 different implementations for iOS, Android and Api layer AND then execute them specifying the implementation.
Is there a way to do that?

**Comment by NivedhaSenthil** [comment]
You can create different environments for different implementations and execute them env. Please refer https://docs.gauge.org/latest/configuration.html#id1

**Comment by singharsh** [comment]
My understanding was that the "Environments" feature is for declaring variables specific to different execution environments like Dev, Integration, QA, Staging etc.

**Comment by singharsh** [comment]
I think this is what i need.
#827

**Comment by nehashri** [comment]
closing this as duplicate. please refer to #827 for updates.
