### ISSUE TITLE
Language support for SWIFT ?

### ISSUE THREAD

**Issue by singhverse** [getgauge/gauge#1339]

**Comment by nehashri** [comment]
@singharsh thanks for bringing this up. We don't have support for SWIFT right now. The Gauge team is busy working on other features right now. But if you would like to build a language runner for SWIFT, you can do this. This [post](https://gauge.org/2017/12/07/authoring-a-language-runner-for-gauge/) maybe helpful for you.

**Comment by zabil** [comment]
Closing this as Gauge will not be adding official support for swift.
