### ISSUE TITLE
Add console message when "gauge update X" is already up to date

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/gauge#1340]
In Gauge 1.0.4, if you have an outdated Gauge plugin, you see something like this:

```
>gauge update java
........................
Successfully updated plugin 'java'.
>
```

But if you are already up to date, no message of any sort appears.

```
>gauge update java

> 
```

It would be much better if there was a simple message like `Plugin 'java' is up to date.` to indicate to the user why nothing is happening. As-is, it can look like the `gauge update` command is not performing correctly.

**Comment by Debashis9012** [comment]
If the plugin is upto date and we are trying to `gauge update java` then we are getting the required excepted message `Plugin 'js' is up to date.`

Tested with below version
``` Gauge version: 1.0.5.nightly-2019-02-22 ```
