### ISSUE TITLE
What is default execution order of scenarios in a single spec file ?

### ISSUE THREAD

**Issue by vinodbhardwaj1** [getgauge/gauge#1342]
Hi team,
As per my current understanding we can't control the execution order of spec. If we can; please let me know.
Second, what is current gauge setting which driver/control the execution order. I mean what is default execution order of multiple scenarios in a single spec file.

If I need to set the scenario execution sequencing which fall under single spec file; how to achieve.

**Comment by Apoorva-GA** [comment]
@vinodbhardwaj1 

- If you are looking for specifications to be executed in alphabetical  order, you can youse `--sort` flag.
- You can also use `--strategy` flag. Check [docs](https://docs.gauge.org/latest/execution.html#run-your-test-suite-with-lazy-assignment-of-tests) for details. 

Scenario execution order can't be controlled right now.
You can use flag `--scenario` to run the scenario by name.
eg : `gauge run <path> --scenario=<scenario1 name> --scenario=<scenario2 name>`

For more info run `gauge run --help` from command line to see different flags that can be used.

**Comment by vinodbhardwaj1** [comment]
Thanks Apoorva, will try these workarounds.

**Comment by sergueis** [comment]
Nobody answered this simple question: what is default execution order of multiple scenarios in a single spec file?

**Comment by sriv** [comment]
That's because gauge does not promise any order in which scnearios will get executed.

**Comment by sergueis** [comment]
> That's because gauge does not promise any order in which scnearios will get executed.

Huh, "The scenarios should execute in the order they are specified when running in serial mode". quote from here:
https://docs.gauge.org/faqs.html?os=windows&language=javascript&ide=vscode#what-is-the-order-of-execution-of-scenarios-in-a-specification

But they are not executed in the order in spec-file. Which is weird and very irritating.

**Comment by vinodkumarfareye** [comment]
In most of the cases (99 %), scenarios are executing in the order of there placement under a spec file and this works to me. If facing issue in any spec file, reset the indexing.

Spec files execution order can be controlled by keeping there name in alphabetic order.

A.name.spec
B.name.spec
C.name.spec

**Comment by sergueis** [comment]
> In most of the cases (99 %), scenarios are executing in the order of there placement under a spec file and this works to me. If facing issue in any spec file, reset the indexing.

What's the indexing and how to reset it? I could find ti in gauge documentation. Also, why 99%? Why not always??
