### ISSUE TITLE
downloads.getgauge.io is throwing ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge#1343]
### Expected behavior
Should be able to download plugins from https://downloads.getgauge.io/plugins/java.json

### Actual behavior
```
ERR_CERT_COMMON_NAME_INVALID
```
https://downloads.getgauge.io/plugins/java.json

![image](https://user-images.githubusercontent.com/13623227/52791275-776aea80-3060-11e9-8abe-c5ae6194b926.png)

https://downloads.gauge.org/plugins/java.json -> `404`

**Comment by Apoorva-GA** [comment]
@haroon-sheikh looks like the url is wrong could try `https://downloads.getgauge.io/plugin/java.json` or `https://downloads.gauge.org/plugin/java.json`

NOTE: its plugin and not plugins

**Comment by Apoorva-GA** [comment]
@haroon-sheikh There was a certificate issue, which we have fixed now please check and let us know.

Now you should be able to hit `https://downloads.getgauge.io/plugin/java.json` or `https://downloads.gauge.org/plugin/java.json`.

**Comment by Debashis9012** [comment]
The below links are working fine.

```
https://downloads.getgauge.io/plugin/java.json 
https://downloads.gauge.org/plugin/java.json
```
