### ISSUE TITLE
Take Screenshots with comments

### ISSUE THREAD

**Issue by alpha1592** [getgauge/gauge#1351]
### Screenshot with comments Feature Request

It would be nice for Web User interface tests to have screenshots with added explanation for the screenshots. In a particular step, sometimes you need to add multiple screenshots with some explanation as to what we are looking at. Due to the nature of the type of testing we do, we need proof of the screens being viewed. Screenshots provide good evidence that the test was actually executed and what was actually "seen".

Currently we have to do the following if we wanted two screenshots with appropriate messages for both...

```
Gauge.captureScreenshot();
Gauge.writeMessage("This Screenshot is show what happens after A");
Gauge.captureScreenshot();
Gauge.writeMessage("This Screenshot is show what happens after B");
```

Looks like attached HTML report
[Current  HTML Report](https://github.com/getgauge/gauge/files/2902545/current.zip)

### Proposed

The proposed solution is to have the comments attached with the screenshot so the report provides clear context as to what the comments mean and what they refer to. 

```
Gauge.captureScreenshot("This Screenshot is show what happens after A");
Gauge.captureScreenshot("This Screenshot is show what happens after B");
```

![Proposed Mock up](https://user-images.githubusercontent.com/2955448/53367895-4ec2da80-3915-11e9-8320-22316397eb4b.png)

**Comment by alpha1592** [comment]
any update?

**Comment by zabil** [comment]
A combination of steps, `writeMessage` is good enough to describe the screenshot. This feature maybe a nice to have but need not be implemented.
