### ISSUE TITLE
Applying hooks to a specific spec file

### ISSUE THREAD

**Issue by varayal** [getgauge/gauge#1353]
I wonder if there is a way to apply a hook to a specific **.spec** file.

I'm applying the following hooks as global to all my specs

```
hooks.js

const { openBrowser, closeBrowser } = require('taiko');

beforeSuite(async () => {
    await openBrowser({ headless: false })
  });
  
afterSuite(async () => {
    await closeBrowser();
});
```

But I would like to use below hook a specific spec file. After reading the documentation I'm not clear about how to get it

```
beforeSpec(async () => {
        await click('Email')
        await write('customer-1@xxx.com', into('aaa'));
        await click('Password')
        await write('aaa', into('Password'));
        await click("INICIAR", {timeout:60000});
})

```

Any thoughts?

**Comment by NivedhaSenthil** [comment]
you can try tagging the spec for which you would like to run the hook and use https://docs.gauge.org/latest/writing-specifications.html#filtering-hooks-with-tags

**Comment by varayal** [comment]
Could you please give me an example tagging the spec using taiko and gauge ?

Regards,

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by NivedhaSenthil** [comment]
Spec

```
# Getting Started with Gauge

Tags: test

## Search Google
```

Step implementation

```
beforeSpec(async(e) => {
    console.log(e);
}, { tags: [ "test"]})
```

This will execute beforeSpec hook only for the spec with tag `test`.

**Comment by varayal** [comment]
thank you very much! That was exactly what I wanted 👍
