### ISSUE TITLE
Dynamic parameter could not be resolved : When using a csv file in step

### ISSUE THREAD

**Issue by singharsh** [getgauge/gauge#1354]
Using a special parameter(csv) to provide data to a step in a specification.

### Expected behavior
No ParseError and should be able to read the data from csv file.

### Actual behavior
Dynamic parameter <table:resources/data.csv> could not be resolved 

### Steps to reproduce
1. Create a spec with at least 1 scenario
2. Create a step in the scenario which takes a csv file as special parameter ( <table:data.csv> )
3. Run "gauge validate specs/" in project directory

### Gauge version
Gauge version: 1.0.4

Plugins
-------
flash (0.0.1)
html-report (4.0.7)
python (0.3.5)
screenshot (0.0.1)
spectacle (0.1.3)

**Comment by singharsh** [comment]
Similar as #414

**Comment by Apoorva-GA** [comment]
@singharsh Relative path to the csv file is with respect to your project root.
So if your `data.csv` is inside the `specs` directory parameter value will be `<table:specs/data.csv>`
Say if your `data.csv` file is inside a folder named `resources` under your project root, parameter will be `<resources/data.csv>`

**Comment by singharsh** [comment]
@Apoorva-GA Tried both of them and still getting ParseError.

**Comment by singharsh** [comment]
Never mind false alert.
Got it working. 
My csv was incorrect.

Thanks for the help.

**Comment by Sathyan87** [comment]
Hi All,

I am new to gauge automation.Using Gauge/js in vs code.

I don't know how to set the path and get the values from xlsx file and write into the text form fields.

Example:In xlsx file given values like

Email |  Password
test@mail.com| tester

kindly help me with Specification and Step Implementation

Thanks

**Comment by zabil** [comment]
@Sathyan87 please read the documentation at https://docs.gauge.org/execution.html?os=macos&language=javascript&ide=vscode#external-csv-for-data-table

Also it's better to ask for help at https://spectrum.chat/gauge?tab=posts
