### ISSUE TITLE
Can't run gauge specs from command line 

### ISSUE THREAD

**Issue by akalaiselvan** [getgauge/gauge#1355]
### Expected behavior
test should get start as per spec
Tell us what should happen

### Actual behavior
It shows some error in cmd like 
17:04:10.592 Plugin java is already installed.
17:04:10.592 Plugin html-report is already installed.
17:04:10.667 Runner connection error: Runner with pid 8788 quit unexpectedly(exit status 1).
17:04:10.667 Error while killing runner: invalid argument
17:04:10.667 Failed to start gauge API: Runner with pid 8788 quit unexpectedly(exit status 1).

### Steps to reproduce
1.write a spec
2.run the spec using gauge run "specs/specname"

### Gauge version
1.0.3
Run gauge -v on your system and paste the results here.
```

**Comment by akalaiselvan** [comment]
In cmd i got a message like 
"Failed to start javac.exe exec: "javac.exe": executable file not found in %PATH%"

Error -----------------------------------------

Failed to start gauge API: Runner with pid 8788 quit unexpectedly(exit status 1).

**Comment by zabil** [comment]
It looks like you only have Java JRE installed. 

Gauge requires Java SDK to compile the source code.
For more information about the difference between the two please read.
https://stackoverflow.com/questions/1906445/what-is-the-difference-between-jdk-and-jre

Please install the latest version of a Java JDK like [OpenJDK](https://openjdk.java.net/install/), make sure it is in your `PATH` before running gauge.
