### ISSUE TITLE
Error while running step via command prompt 

### ISSUE THREAD

**Issue by akalaiselvan** [getgauge/gauge#1359]
### Expected behavior
Test will get start when <gauge run test.spec> command is used

### Actual behavior
It is showing a message like [ error : error reading "jar file path " ; error in opening zip file

Failed to start gauge API: Runner with pid 7216 quit unexpectedly(exit status 1).

### Scenario
1. That is loh4j library file 
2. The same test got started without any issue while running from ide . now trying to run from cmd it show these error .

### Gauge version
Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
html-report (4.0.6)
java (0.7.1)
screenshot (0.0.1)

**Comment by nehashri** [comment]
@akalaiselvan Which IDE are you using? Are you using some dependency management library like Maven or Gradle? What is the command used to run the gauge specs from command line?

**Comment by akalaiselvan** [comment]
Im trying to start spec from cmd... gauge run specfile

**Comment by akalaiselvan** [comment]
16:28:03.692 Plugin java is already installed.
16:28:03.693 Plugin html-report is already installed.
16:28:03.728 Checking updates...
16:28:03.730 Downloading https://downloads.gauge.org/plugin/html-report?l=java&p=html-report,java,json-report,screenshot,xml-report&o=windows&a=386
16:28:04.528 Failed to download html-report-install.json file: Get https://downloads.gauge.org/plugin/html-report?l=java&p=html-report,java,json-report,screenshot,xml-report&o=windows&a=386: read tcp 10.0.3.162:4871->34.216.93.30:443: wsarecv: An existing connection was forcibly closed by the remote host.
16:28:04.530 Downloading https://downloads.gauge.org/plugin/java?l=java&p=html-report,java,json-report,screenshot,xml-report&o=windows&a=386
16:28:04.766 Failed to download java-install.json file: Get https://downloads.gauge.org/plugin/java?l=java&p=html-report,java,json-report,screenshot,xml-report&o=windows&a=386: read tcp 10.0.3.162:4872->34.216.93.30:443: wsarecv: An existing connection was forcibly closed by the remote host.
16:28:04.768 Downloading https://downloads.gauge.org/plugin/json-report?l=java&p=html-report,java,json-report,screenshot,xml-report&o=windows&a=386
16:28:05.004 Failed to download json-report-install.json file: Get https://downloads.gauge.org/plugin/json-report?l=java&p=html-report,java,json-report,screenshot,xml-report&o=windows&a=386: read tcp 10.0.3.162:4874->34.216.93.30:443: wsarecv: An existing connection was forcibly closed by the remote host.
16:28:05.008 Downloading https://downloads.gauge.org/plugin/screenshot?l=java&p=html-report,java,json-report,screenshot,xml-report&o=windows&a=386
16:28:05.244 Failed to download screenshot-install.json file: Get https://downloads.gauge.org/plugin/screenshot?l=java&p=html-report,java,json-report,screenshot,xml-report&o=windows&a=386: read tcp 10.0.3.162:4875->34.216.93.30:443: wsarecv: An existing connection was forcibly closed by the remote host.
16:28:05.246 Downloading https://downloads.gauge.org/plugin/xml-report?l=java&p=html-report,java,json-report,screenshot,xml-report&o=windows&a=386
16:28:05.481 Failed to download xml-report-install.json file: Get https://downloads.gauge.org/plugin/xml-report?l=java&p=html-report,java,json-report,screenshot,xml-report&o=windows&a=386: read tcp 10.0.3.162:4876->34.216.93.30:443: wsarecv: An existing connection was forcibly closed by the remote host.
16:28:05.882 Runner connection error: Runner with pid 5792 quit unexpectedly(exit status 1).
16:28:05.882 Error while killing runner: invalid argument
16:28:05.883 Failed to start gauge API: Runner with pid 5792 quit unexpectedly(exit status 1).




This is  the gauge log.. I think its failed when trying to download from internet ....Is internet mandatory to run gauge test .. or can we configure the same ..?
