### ISSUE TITLE
Failure to install Java plugin - invalid name

### ISSUE THREAD

**Issue by RJBartlett** [getgauge/gauge#136]
I've installed Gague to Windows 7 in c:\Gauge, set the GAUGE_ROOT and added c:\Gauge\bin to the PATH.
From the command line I'm running c:\Gauge>gauge --install java
And get the following error:
13:42:54.923 [WARN] Failed to install plugin java : Could not download java-install.json file. Invalid plugin name

Have also downloaded the plug-in as a ZIP and run it using the --file option and get the following:
13:44:06.593 [INFO] Plugin unzipped to => C:\Users\BARTLE~1\AppData\Local\Temp\1430225045895954500689541019
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x14 pc=0x497fb0]

goroutine 1 [running]:
github.com/getgauge/common.GetFileWithJsonExtensionInDir(0x201487d0, 0x41, 0x0, 0x0, 0x0, 0x0)
        /tmp/src/github.com/getgauge/common/common.go:260 +0x3e0
main.installRunnerFromDir(0x201487d0, 0x41, 0x0, 0x0)
        /tmp/src/github.com/getgauge/gauge/install.go:311 +0x40
main.installPluginFromZip(0x2014a240, 0x32, 0x0, 0x0)
        /tmp/src/github.com/getgauge/gauge/install.go:306 +0x376
main.installPluginZip(0x2014a240, 0x32)
        /tmp/src/github.com/getgauge/gauge/gauge.go:188 +0x30
main.main()
        /tmp/src/github.com/getgauge/gauge/gauge.go:78 +0x197

Do I also need to download the json file? And put it where?

**Comment by prateekbaheti** [comment]
Which version of gauge have you installed ? Does the plugin zip that you have downloaded have a java.json file inside ? It should have been extracted to C:\Users\BARTLE~1\AppData\Local\Temp\1430225045895954500689541019

**Comment by RJBartlett** [comment]
I’ve got version 0.1.2.  Is there a newer one I should be using?

There was a json file in the extract. I have actually now solved this as I found a different link to a 64bit version which is working fine.
The content of the two are quite different, the non-working one contains guage-pronto, skel and src dirs and go files, whilst the one that worked for me has a bin, libs and skil dir but only the json file apart from that.

Thanks for your quick response. 

Regards,	Rebecca

**Comment by prateekbaheti** [comment]
You may have downloaded the source zip the first time instead of the plugin
release. Glad it's resolved now.

On Friday, May 1, 2015, Rebecca <notifications@github.com> wrote:

> I’ve got version 0.1.2. Is there a newer one I should be using?
>
> There was a json file in the extract. I have actually now solved this as I
> found a different link to a 64bit version which is working fine.
> The content of the two are quite different, the non-working one contains
> guage-pronto, skel and src dirs and go files, whilst the one that worked
> for me has a bin, libs and skil dir but only the json file apart from that.
>
> Thanks for your quick response.
>
> Regards, Rebecca
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getgauge/gauge/issues/136#issuecomment-98141253>.
>


-- 
Sent from my iPhone
