### ISSUE TITLE
Stream result notifications to plugins

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/gauge#1372]
Since there are issues happening around sending a huge result to report plugins at the end of execution, will be better to stream results instead of waiting till the end to send them in bulk.

Related: https://github.com/getgauge/html-report/issues/213

**Comment by nehashri** [comment]
Some more context related to this issue. 

This issue should be able address the following issues:
- Sending the execution result at the end of the suite execution is causing problems with huge projects. The size of the message sent at the end can be huge and may exceed the maximum size of message that can be sent via protobuf. (Related issues : https://github.com/getgauge/html-report/issues/213#issuecomment-472048183, https://github.com/getgauge/gauge/issues/1239).
- For a huge project run, if Gauge process has exited before completion, the reporting plugins will not generate the reports. 
- A reporting plugin may need data at different points in time and need not wait for the end of execution. We don't provide enough data to plugins about the execution result before completion of the test suite. (Related issue : https://github.com/getgauge/gauge/issues/1187).

Discussion Update:
We will be sending enough data to reporting plugins at the end of each execution level (step, scenario spec and suite). It is upto the plugin to make use of the data which is needed. For Gauge, we will send as much information as possible at each of these levels along with Suite/Spec/Scenario/Step Execution ending messages.

**Comment by nehashri** [comment]
Needs verification on messages sent. Needs to be verified by developer while developing getgauge/html-report#221
