### ISSUE TITLE
Running specs before parallel execution with multithreading

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#1373]
**Actual Behaviour**
We can run few specs in serial before running specs in parallel after #962. 
With this feature, a new runner process is spawned for the serial runs. After the serial runs are completed new runner process/processes are spawned to run specs in parallel. When multi-threading is enabled, two runner processes are spawned instead of one

**Expected Behaviour**
When `enable_multithreading` is enabled, Gauge spawns off only one runner process. Gauge's behaviour should be same when `--parallel` flag is run with `--only "tags"` and `enable_multithreading` environment variable is used. i.e., only one runner should be spawned and used for parallel and serial execution. 

- This would enable context and data sharing between specs run in serial and parallel. 
- The behaviour of Gauge when run only in parallel vs serial with parallel run will be same.
- It will also optimize performance.

**Comment by iskoc9002** [comment]
Hi,
I've a maven gauge project. My spec include 3 different scripts. First one is, Admin is creating meeting. Second one, Members vote agenda item(s) at the same time. So, I want to run first script. Then second scripts for 10 different users at the same time. Last one, delete createdMeeting after all parallel run completed

So, How can I do it with this solution. I'didn't do it.

**Comment by zabil** [comment]
@iskoc9002 you can run the first script in serial and the second script in [parallel](https://docs.gauge.org/execution.html#run-specs-before-parallel-execution)

However, you cannot run the last one after parallel completion.
