### ISSUE TITLE
Create debian, rpm packages for simpler installation process.

### ISSUE THREAD

**Issue by prateekbaheti** [getgauge/gauge#138]
- [x] Debian

- [x] RPM

- [x] Mac .pkg / dmg

Can use [fpm](https://github.com/jordansissel/fpm) for this.

**Comment by navaneeth** [comment]
From my personal experience, if you want to get into Debian/Ubuntu repo, don't use fpm or tools like that. Go by the hard way of using `dpkg-buildpackage`.

**Comment by kaustavdm** [comment]
We've received requests in the last few days to create Debian and RPM packages. Someone in ThoughtWorks is trying her hands on Debian packaging. I want to take this up next week and write basic Debian and RPM package and integrate it with Gauge's CD pipeline to create packages for each build :-)

From what I hear from @sriv, there were some challenges when packaging was attempted last time. Bring it on!

**Comment by kashishm** [comment]
@kaustavdm has created Debian and RPM packages for Gauge. They will be released along with the next version.

**Comment by kaustavdm** [comment]
Just as a note, we need to sign the `.deb` and `.rpm` packages with our own GPG keys before we publish.

**Comment by mahendrakariya** [comment]
I have updated #190. Let's track all the signing related stuff there.
