### ISSUE TITLE
Multiple instances of Chrome spawned for every run of my spec in headless mode

### ISSUE THREAD

**Issue by dmolin** [getgauge/gauge#1381]
### Note
I'm not sure if the problem is in Gauge or in Taiko (I don't know who's responsible for managing process instances during test execution)

### Expected behavior
Running my spec file with gauge in headless mode should result in one instance of the Chrome process spawned per run. The instance should then be removed from memory after the test finishes its run.

### Actual behavior
Every time I run `HEADLESS=true gauge run spec specs/my-spec.spec.md` 5 separate instances of Chrome are created. They remain in memory after the test ends. So, if I run my spec 3 times I endup having 15 separate instances of Chrome in my machine!

### Steps to reproduce
1. create a spec file with a few steps
2. run `gauge run spec <specfile>`
3. run  `ps` and check how many instances of the Chrome process are visible

### Gauge version
Linux Manjaro (Arch)
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.8)
js (2.3.4)
screenshot (0.0.1)

**Comment by sriv** [comment]
I believe your expectation is valid. Would it be possible to share a sample code for us to replicate the issue? This will help us immensely in arriving at a solution. Thank you.

**Comment by dmolin** [comment]
I apologize, that was an error on my part. I was not correctly shutting down the browser instance in the `afterSuite()` callback, hence the process hanging around. I'm closing this issue since there is no issue at all! Thanks for the quick reply, much appreciated!
