### ISSUE TITLE
unable to run specs with multiple tags

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/gauge#1385]
**Excepted Result:**
It should filters the specs and scenarios to be executed

**Actual Result:**
No specifications found in specs.

**Steps to reproduce:**
1. Create a sample project of java "gauge init java"
2. A spec should include multiple steps with multiple tags
   Ex: tag1, tag2
3. Run the specs with multiple tags
  ```gauge run --tags "tag1, tag2" specs```

gauge version:
```Gauge version: 1.0.5.nightly-2019-04-04```

**Comment by Apoorva-GA** [comment]
I think it works as expected. `gauge run --tags "tag1, tag2" specs` is same as `gauge run --tags "tag1 & tag2" specs`

Mentioned here https://docs.gauge.org/latest/execution.html#specify-tags

**Comment by Apoorva-GA** [comment]
Added docs https://docs.gauge.org/master/execution.html#tag-expressions
