### ISSUE TITLE
Log level is not honored for some gauge commands

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#1387]
**Expected Behaviour**
Log level flag is a global flag and should be honored for all gauge sub commands

**Actual Behaviour**
Log level is not honored for some gauge sub commands like : init, install, list, man, telemetry, uninstall, update, version.

Steps to reproduce:
- Run `gauge init js -l debug` (or any of the subcommands mentioned above with log level debug)
- No debug statements are printed.

**Comment by Debashis9012** [comment]
Debug statements are displaying properly. This has been verified and found fixed with the version ``` 	
gauge-1.0.5.nightly-2019-04-22```
