### ISSUE TITLE
not working for empty dependencies for javascript

### ISSUE THREAD

**Issue by luciferankon** [getgauge/gauge#1392]
### Expected behavior
should run the test even if there is no dependencies

### Actual behavior
Fails with an error message :
TypeError: Cannot read property 'taiko' of undefined
    at getPostData (/Users/ankoncha/.gauge/plugins/js/2.3.4/src/tracker.js:28:32)
    at send (/Users/ankoncha/.gauge/plugins/js/2.3.4/src/tracker.js:68:14)
    at Object.trackConsole (/Users/ankoncha/.gauge/plugins/js/2.3.4/src/tracker.js:81:5)
    at /Users/ankoncha/.gauge/plugins/js/2.3.4/src/gauge.js:41:15

### Steps to reproduce
1. create a simple js project using gauge
2. remove the dependencies section from package.json
3. ```gauge run``` from the project root

### Gauge version
```
```Gauge version: 1.0.4

**Comment by Apoorva-GA** [comment]
Fix Should be available in gauge-js nightly >= 30/4/19

**Comment by Debashis9012** [comment]
After removing dependencies from package.json we are able to do ```gauge run ``` successfully.
Tested with latest nightly js version: ``` 2.3.5.nightly-2019-05-03 ```
