### ISSUE TITLE
Why can't the parameters in the step names map to the parameter names in their implementation

### ISSUE THREAD

**Issue by delmaamoun** [getgauge/gauge#1393]
I have a step that creates a specific data structure with multiple values. Most of these values are default though, and I only need to manipulate a specific value at a time.
e.g.
* create structure with power "100" kW
* create structure with voltage "100" volts

@step(["create structure with power <power> kW",
             "create structure with voltage <voltage> volts"
             "create structure with power <power> kW and voltage <voltage> volts"])
def create_struct(power=0,voltage=0):
    struct.power = power
    struct.voltage = voltage

The parameters instead depend on their location in the step when being passed.

Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.7)
java (0.7.1)
json-report (0.3.0)
python (0.3.6.nightly-2019-03-07)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)

**Comment by sriv** [comment]
Gauge does not support named parameters, mostly because it is not a common feature across all languages that gauge works with. Languages that do not support named parameters require positional arguments to match the signature of the method implementation.

In your particular case, I suggest you try using concepts to abstract out parameters. ex:

Step:

```
@step("create structure with <power> kW and <voltage> volts")
def create_struct(power,voltage):
struct.power = power
struct.voltage = voltage
```

And have concepts like these:

```
# create structure with <power> kW
* create structure with <power> kW and "0" volts

# create structure with <voltage> volts
* create structure with "0" kW and <voltage> volts
```

Does this help?

**Comment by delmaamoun** [comment]
I guess... I've been doing it by checking the step name for keywords which would make the specs less cluttered (but the step implementation more complex).
It's a trade-off. But it would be really cool if there was a way to handle optional parameters.
Thanks for your help.
