### ISSUE TITLE
add ability to detect/diagnose potential setup issues.

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#1400]
### Expected behavior
`gauge` should have the ability to report pre-requisites and perform checks for it's existence. This would allow to check the readiness for a project to be executed.

Proposal: introduce a `diagnose` subcommand that shall look for pre-requisites in the target machine. Examples of checks that could be performed:

- gauge + plugins, list updates
- check if language runtime are installed (ex. JVM, ruby, nodejs etc)
- check permissions (there have been some users who have reported crashes due to permissions)
- ensure package manager is installed (ex. mvn/gradle/npm etc)

The responsibility of diagnosis will be shared with gauge and the runner, since some of the checks would need to be done at the runner level.

### Actual behavior
There is no such feature, and hence users discover issues at runtime.

### Gauge version
```
Run gauge -v on your system and paste the results here.
```

**Comment by zabil** [comment]
Won't be implementing this instead. It's better to log all failure information is a separate log file per run so that it's easy to detect and associate failures.
