### ISSUE TITLE
Gauge Returns Exit Code 0 When It Fails To Run

### ISSUE THREAD

**Issue by bgottfried91** [getgauge/gauge#1405]
### Expected behavior
1. When attempting to run tests ("Gauge run...") in a folder that does not contain a Gauge project file, the Exit Code should be non-zero to denote that the run did not complete successfully.
2. When attempting to run tests in a folder that contains a Gauge project file but you do not point Gauge to a valid spec file or folder containing specs (e.g. "Gauge run adsfasfa" where there's no folder adsfasfa), the Exit Code should be non-zero to denote that the run did not complete successfully.

### Actual behavior
Exit Code 0 is returned.

### Steps to reproduce
1. Open up a command or Powershell window (only tested on Windows) to a directory that does not contain a Gauge project file.
2. Run "Gauge run specs"
3. Check the exit code using either "echo %errorlevel%" (CMD) or "$LASTEXITCODE" (Powershell)
---
1. Open up a command or Powershell window (only tested on Windows) to a directory that does contain a Gauge project file.
2. Run "Gauge run <random name>" where <random name> is a string that does not correspond to a folder in the current directory.
3. Check the exit code using either "echo %errorlevel%" (CMD) or "$LASTEXITCODE" (Powershell)

### Gauge version
Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
csharp (0.10.5)
dotnet (0.1.1)
html-report (4.0.6)
screenshot (0.0.1)

**Comment by luciferankon** [comment]
fix should be available in nightly >= 23/5/2019

**Comment by Debashis9012** [comment]
I am able to replicate the second excepted behaviour. 
Tested version: ```1.0.6.nightly-2019-05-27```

**Comment by svenlange** [comment]
Hi! When will the next Gauge version be released? Is there a schedule?

**Comment by cratace** [comment]
Hello, This issue is making it tough for me to trouble shoot our gauge implementation using powershell/azure devops.  Is this still going to be addressed?

**Comment by sriv** [comment]
Gauge 1.0.7 is out. Can you please check if this is an issue?

I tried on Linux as well as Windows 10. Running `gauge run` in an empty directory or passing a non existent folder (ex. `gauge run nodir`) both return exit code 1 for me on both the operating system.

**Comment by negiDharmendra** [comment]
## Current behavior of `gauge run` command

- When run inside a non Gauge project directory.
   `Exits with exit code 1`

- When run inside a Gauge project directory but the specs directory does not exists.
   `Exits with exit code 0`

- When run inside a Gauge project directory but the specs directory is empty.
   `Exits with exit code 0`

- When run inside a Gauge project directory but no specs are found after applying **tags filter**.
   `Exits with exit code 0`


## Purposed behavior for `gauge run` command

- When run inside a non Gauge project directory.
   `Exits with exit code 1`

- When run inside a Gauge project directory but the specs directory does not exists.
   `Exits with exit code 1`

- When run inside a Gauge project directory but the specs directory is empty.
   `Exits with exit code 1`

- When run inside a Gauge project directory but no specs are found after applying **tags filter**.
   `Exits with exit code 0`
