### ISSUE TITLE
Total specs count shows different values from console and html-report

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/gauge#1406]
### Expected behavior
Total specs count should be identical both in console and html-report.

### Actual behavior
Total specs count is different in console and html-report.

### Project to reproduce
[tmp1.zip](https://github.com/getgauge/gauge/files/3171357/tmp1.zip)
> Run `gauge run specs` and note the stats for total specs executed are different in console and html-report

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
