### ISSUE TITLE
gauge run command gets stuck randomly 

### ISSUE THREAD

**Issue by varayal** [getgauge/gauge#1407]
### Actual behavior
This is a random issue I'm under the VPN to execute my tests but sometimes I get this error

After the 3rd execution, it works. Is there any workaround on this one?

```
gauge run --tags=cod specs/order/MX/cod.spec --verbose                                                     6.46G RAM
(node:10291) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
 Order creation with Cash on Delivery
  Error Message: Error: Navigation took more than 60000ms. Please increase the timeout.
  Stacktrace:
  Error: Navigation took more than 60000ms. Please increase the timeout.

Successfully generated html-report to => /Users/victor.araya/projects/e2e-linio-gauge/reports/html-report/index.html
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	0 executed	0 passed	0 failed	0 skipped

Total time taken: 1m8.182s

````

### Gauge version
```
Gauge version: 1.0.5
```

**Comment by varayal** [comment]
This happens even when the site is available. This is not related to the server

**Comment by NivedhaSenthil** [comment]
does this happen only when executing script using gauge? or also when running taiko script independently ?

**Comment by varayal** [comment]
it's happening only when executing using gauge.

**Comment by NivedhaSenthil** [comment]
Please give more details about your env (gauge-js, taiko, os etc.,) Will try if I can reproduce it

**Comment by varayal** [comment]
after upgrading to `Gauge version: 1.0.6.nightly-2019-05-14` this issue is not happening anymore

**Comment by NivedhaSenthil** [comment]
closing the issue.. feel free to reopen if you face the issue again
