### ISSUE TITLE
First run is slow

### ISSUE THREAD

**Issue by javiviprospe** [getgauge/gauge#1410]
Currently, first run on gauge-java needs more than 5 sec to start launching test. This should not be a problem. But in my case, with more than 400 scenarios with 2 or 3 specs each one of them, It takes around 20 - 30 seconds to start launching tests. Is there a way to tune this ?

### Expected behavior
Tests should start faster

### Actual behavior
20-30 seconds to start launching tests with a high amount of them. 5 seconds to start launching the default "example.spec" gauge java test

### Steps to reproduce
1. Create an empty folder
2. type gauge init java
3. launch first test

### Gauge version
```
Run gauge -v on your system and paste the results here.

Gauge version: 1.0.5
Commit Hash: 7aaf683

Plugins
-------
html-report (4.0.3)
java (0.7.2)
screenshot (0.0.1)

**Comment by shubhamsc** [comment]
@javiviprospe I tried to replicate this issue but found test execution always starts within a second.
I tried with a sample project and a project which has more than 500 specs. In both projects, execution started as soon as a hit for run gauge test.

I checked with MacOS. In which environment you are seeing this issue?

**Comment by javiviprospe** [comment]
I'm using ubuntu linux. And I use java 1.8, do you also use it ?

**Comment by shubhamsc** [comment]
@javiviprospe I checked on Ubuntu with Java 1.8. but found the tests are starting immediately.
 if all dependencies are not installed gauge try to install it first that could take 2-3 sec before running the tests.  If you want to resolve all dependency before running gauge tests, you can use `gauge install`. it will install all gauge related dependency.

**Comment by Debashis9012** [comment]
@javiviprospe Please feel free to reopen this issue if you are still facing this issue. 
Please provide more details as well.
