### ISSUE TITLE
ContinueOnFailure not working

### ISSUE THREAD

**Issue by alpha1592** [getgauge/gauge#1411]
### Expected behavior
When using `@ContinueOnFailure` annotation on a step that is expected to fail, or on occasion does fail but its not a deal breaker for the test, we can add the `@ContinueOnFailure` annotation to continue with test execution. Therefore, Gauge will ignore the failure and continue with the next step rather than skipping all remaining test steps. 

### Actual behavior
In the past, `@ContinueOnFailure` has worked for me as expected (Gauge 1.0.3 i think), but recently i noticed, that the steps are throwing the exception out and breaking the test scenario execution rather than continuing the test scenario. Please Investigate. 

### Steps to reproduce
1. Create a new Gauge Java Maven project `gauge init java_maven`
2. Open the Project in your favorite IDE (IntelliJ)
3. Add an exception to a test step in order to fail it on purpose. 
3.1. `throws new AssertionError("Something went wrong here...");`
4. Add `@ContinueOnFailure(AssertionError.class)` above the `@Step` of that particular step implementation.
5. Run The Test. 
6. Note that the test will result in a failure and reason is an `AssertionError` where the error message reads 'Something went wrong here...'

I have tried many combinations of the annotation, but doesn't seem to work... I have attached a sample project below. 

```java
@ContinueOnFailure
@ContinueOnFailure(AssertionError.class)
@ContinueOnFailure({AssertionError.class})
@ContinueOnFailure(Exception.class)

@Step("Some Step...")
@ContinueOnFailure
public void test()
{
  // do work here
}

@ContinueOnFailure
@Step("Some Step...")
public void test()
{
  // do work here
}
```

```java
@ContinueOnFailure(AssertionError.class)
@Step("Continue with test even if Assertion Error is seen")
public void assertionError()
{
  Gauge.writeMessage("AssertionError will be thrown now...");
  throw new AssertionError("Ok, This is an Assertion Error...");
}
```

### Gauge version
```
Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
flash (0.0.1)
go (0.1.2)
html-report (4.0.8)
java (0.7.2)
json-report (0.3.1)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)
```

### Attachment
[continue_on_failure_poc.zip](https://github.com/getgauge/gauge/files/3189039/continue_on_failure_poc.zip)

**Comment by NivedhaSenthil** [comment]
It seems to execute the consequent steps when there is `@ContinueOnFailure` as expected. Below is the result i get running the attached project. Is there any other error you are seeing on execution ? 

```
➜  continue_on_failure_poc mvn -q clean compile test-compile gauge:execute
# Testing Continue On Failue Anootation
  ## Test Scenario	 ✔ ✘ ✔ ✘ ✔
        Failed Step: Continue with test even if Assertion Error is seen
        Specification: specs/example.spec:6
        Error Message: java.lang.AssertionError: Ok, This is an Assertion Error...
        Stacktrace:
        org.thiss.is.a.test.StepImplementation.assertionError(StepImplementation.java:22)

        Failed Step: Continue with test even if Exception is seen
        Specification: specs/example.spec:8
        Error Message: java.lang.Exception: Ok, This is an exception...
        Stacktrace:
        org.thiss.is.a.test.StepImplementation.exception(StepImplementation.java:30)


Successfully generated html-report to => /.../Downloads/continue_on_failure_poc/reports/html-report/index.html
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	1 executed	0 passed	1 failed	0 skipped

Total time taken: 991ms
```

Version used:

```
Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
csharp (0.10.6.nightly-2019-01-11)
dotnet (0.1.1.nightly-2019-01-29)
flash (0.0.1)
html-report (4.0.6)
java (0.7.2)
js (2.3.5)
json-report (0.2.2)
python (0.3.5)
screenshot (0.0.1)
xml-report (0.2.2.nightly-2018-12-11)
```

**Comment by alpha1592** [comment]
Yes, for some reason running from command line does work. 
From intelliJ, i am getting a different behaviour.
Maybe its IntelliJ / plugin for intelliJ causing some issues...  ill investigate.

**Comment by shubhamsc** [comment]
@alpha1592 I tried with the given project it working fine from the command line and in IntelliJ also. it giving the expected error which @NivedhaSenthil mention above.

Can you provide IntelliJ and gauge-IntelliJ plugin version so we can also investigate?
I'm using MacOS with IntelliJ IDEA 2019.1.2 (Community Edition) and gauge IntelliJ plugin v0.3.15.

**Comment by alpha1592** [comment]
I think this was an issue with my environment. I have reinstalled IntelliJ, and the issue is no longer there. 
I appreciate you looking into this. 
I apologize for wasting your time.
