### ISSUE TITLE
Getting error on Parallel executions - Connection to runner with Pid lost. 

### ISSUE THREAD

**Issue by supraja-kr** [getgauge/gauge#1414]
### Expected behavior
It should complete executing scripts with all the 4 rows of table data.

### Actual behavior
getting error "Connection to runner with Pid 72608 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:60378->127.0.0.1:60381: use of closed network connection

### Steps to reproduce
1. Run the gauge project against a table of data - having 4 lines (rows) of data, in parallel mode
2. command - gauge run -p specs --tags "regression" -n=3
3. Three browser sessions are triggered and scripts start executing.
4. After a few steps, getting error "Connection to runner with Pid 72608 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:60378->127.0.0.1:60381: use of closed network connection.
I am able to simulate this a number of times.
5. I am not able to see this error when I execute with 4 parallel executions

### Gauge version
Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
html-report (4.0.8)
java (0.7.2)
js (2.3.4)
screenshot (0.0.1)

**Comment by shubhamsc** [comment]
@supraja-kr Can you provide more information which will help us to replicate this issue?
* OS information
* Language of implementation
* if possible, share gauge.log file of your project

If you can share a sample project where we can see this error while running with the given command, it will be very helpful.

**Comment by supraja-kr** [comment]
Mac OS- High Sierra - Version 10.13.3, Have used java-script
[gauge.log](https://github.com/getgauge/gauge/files/3201739/gauge.log)

**Command** gauge run -p specs --tags "regression" -n=3

**Comment by shubhamsc** [comment]
@supraja-kr I'm not able to replicate with given information.
Sharing a sample project really help us to track the error.

**Comment by Debashis9012** [comment]
@supraja-kr  Please provide more information for us to solve this issue and please feel free to reopen it.
