### ISSUE TITLE
How to customize gauge reports

### ISSUE THREAD

**Issue by vkumarv** [getgauge/gauge#1415]
@Apoorva-GA , Could you please let us know, how to customize gauge reports, I want generate gauge reports with test case name and time stamp.

**Comment by zabil** [comment]
You can check the HTML report documentation and themes. https://github.com/getgauge/html-report
Closing this as it is not an issue. Can you ask this question on our email groups or gitter chat?

**Comment by vkumarv** [comment]
ok fine thanks for update
