### ISSUE TITLE
Run gauge on Windows from bash MINGW64 results in error

### ISSUE THREAD

**Issue by mattimatt** [getgauge/gauge#1416]
### Expected behavior
When I run gauge on Windows from bash MINGW64 (either through vscode or cmder) I expect it to, well, run.

### Actual behavior
```
$ gauge run specs\example.spec
/c/Users/xxxxxxx/AppData/Roaming/npm/gauge: line 1: /node_modules/@getgauge/cli/bin/gauge: No such file or directory
```

It does work from the command line. Other npm applications like e.g. Mountebank run from both cmd and bash. I would greatly appreciate enabling this for gauge as well. 

### Steps to reproduce
1. install gauge on win10 with MINGW64 and vscode already installed
2. gauge [anything]
3. read error

### Gauge version
```
Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
csharp (0.10.5)
dotnet (0.1.1)
html-report (4.0.8)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)

Perhaps useful
-------
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
```

**Comment by shubhamsc** [comment]
@mattimatt if you want to run gauge on Windows from bash MINGW64. you need to run gauge command  by `gauge.cmd run`.  
Let's know, If you are still facing the same issue with `gauge.cmd`.
