### ISSUE TITLE
Default env is loaded even if it is not specified.

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#1418]
**Expected Behaviour**
Gauge should load environments that is specified using the `--env` flag. If there are no environment specified it should load the `default` environment.

**Actual Behaviour**
Gauge is loading the `default` environment even if some other environment is specified in the `--env` flag.

**Steps to Reproduce**
- Create a simple Gauge project
- Add a new env `foo` with the following additional properties
```
my_foo_variable = bar
```
- Edit the default/default.properties and add the following 
```
my_default_variable = Definetly not Bar!!!
```
- Print the `my_foo_variable` and `my_default_variable` in a step implementation and implement the step(eg in js)
```
step("Print environment variables", function() {
  console.log("The default variable is", process.env.my_default_variable)
  console.log("The foo variable is", process.env.my_foo_variable)
});
```
```
# Specification
## Test env variables
* Print environment variables
```
- Now run `gauge run --env=foo`.
The output contains
```
The default variable is definetly not bar!!!
The foo variable is bar
```
- Observe the line `The default variable is definetly not bar!!!` is printed. This means that the default env was loaded even if it not specified.

The default env should be loaded only if it is explicitly specified in `--env` flag or if `--env` flag is not used in the gauge command.

**Comment by ajoecker** [comment]
we need to be careful here, as this changes the behavior.

Currently, you can define a custom environment and only describe the properties, you like to change. The rest is loaded with the default values from the default env.

If you need to specify the default env, when loading a custom env, you would need to use all properties in your custom env or the properties are actually empty and this will break projects

As far as I see, this is also the case for the test cases in  `env_test.go`, only the properties that change are defined in the custom envs.

**Comment by haroon-sheikh** [comment]
Unless I'm understanding it incorrectly, this isn't really a bug but really useful thing to load variables from default which applies to all environments.

You wouldn't really provide all variables in each env directory, that would be a lot duplication and harder to manage.

As @ajoecker pointed, this would be a breaking change for most projects.
