### ISSUE TITLE
Runner compatibility check should happen when a project is initialized

### ISSUE THREAD

**Issue by navaneeth** [getgauge/gauge#142]
I had gauge-0.0.3 installed using HomeBrew. I have upgraded it with

```
brew upgrade gauge
```
That installed `gauge-0.1.3`. But the plugins are still older versions.

```
/tmp/g1 » gauge --version                                                                                                                     navaneethkn@nkn
Gauge version: 0.1.3

Plugins
-------
java (0.0.3)
ruby (0.0.3)
```
Initialize a new project and run `gauge specs`. It fails with an error, 

`15:40:50.392 [CRIT] Failed to start a runner. Compatible runner version to 0.1.3 not found`

IMO, this should happen during init and no project should be created when there is a plugin incompatibility. Or better, init downloads the compatible version of plugin. 

`gauge --install-all` is also not detecting the incompatibility.

**Comment by sriv** [comment]
I wonder if automatically updating the plugins would break implementations? Perhaps a pre-update validation could let the user decide if it is safe to upgrade?

**Comment by navaneeth** [comment]
That has to be validated by the version number. If the major has changed, chances are that there could be breaking API changes. So a warning/confirmation will be required. Otherwise, it should be fine and nothing should break. 

This assumes that all plugins follow the semantic versioning properly and change the major when backward incompatible changes are introduced. 

Or multiple versions of plugins should work together. Based on what is configured in `manifest.json`,  you load the appropriate version of the plugin. If no version specified, latest will be taken. 

thoughts?

**Comment by ApoorvaM** [comment]
During project initialization, if compatible runner version is not present, it now throws an error message. It also says to update the plugin. 
This check happens before `gauge specs` as well.

Version compatibility check in `--install-all` is done in this [commit](https://github.com/getgauge/gauge/commit/d40435106b773c9c3a97837a94d1a6734a23329d).
