### ISSUE TITLE
How do I disable chromium 'Save Password' functionality while I execute gauge scripts?

### ISSUE THREAD

**Issue by supraja-kr** [getgauge/gauge#1422]
Is there a way to handle this? Or a sample script would help

**Comment by ajoecker** [comment]
that is not an error or issue, so this is the wrong place for that.

ask here https://groups.google.com/forum/#!forum/getgauge 
or here https://gitter.im/getgauge/chat
or at Stackoverflow

**Comment by zabil** [comment]
This has also been fixed via this pull request https://github.com/getgauge/taiko/pull/542
Until the next release you can use
```
openBrowser(args:["--enable-automation"]))
```
