### ISSUE TITLE
Gauge errors out while trying to read proto message 

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#1423]
There are intermittent errors while running Gauge. It errors out trying to read proto messages. Html report also seems to error out. 
Can be seen while running some builds on travis like https://travis-ci.org/getgauge/gauge-python/jobs/537712989

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
