### ISSUE TITLE
Report error in specs with bigger tables

### ISSUE THREAD

**Issue by miroslav750** [getgauge/gauge#1425]
### Expected behavior
After running spec with a table with many lines, I should be able to open report and click on any line in table to see errors/steps

### Actual behavior
After running spec with a table with (in my case) 15 or more lines, I try to open report. It opens but I can not click on any line in table to see error messages or so.

### Steps to reproduce
1. use spec like (data in table is different, this is just for example)
```
# some spec

Tags: tag1, tag2

|      name    |       suffix                    |
|------------------------------------------------|
| name         | /suffix.com                     |
| name         | /suffix.com                     |
| name         | /suffix.com                     |
| name         | /suffix.com                     |
| name         | /suffix.com                     |
| name         | /suffix.com                     |
| name         | /suffix.com                     |
| name         | /suffix.com                     |
| name         | /suffix.com                     |
| name         | /suffix.com                     |
| name         | /suffix.com                     |
| name         | /suffix.com                     |
| name         | /suffix.com                     |
| name         | /suffix.com                     |
| name         | /suffix.com                     |

## check if page is working

* User goes to <suffix>
* Check if element is present
```
2. fails in 2-3 cases for example
3. report is not working, I can see just table and I can not open it

### Gauge version
```
Gauge version: 1.0.5

Plugins
-------
html-report (4.0.8)
java (0.7.2)
screenshot (0.0.1)
spectacle (0.1.3)
```

**Comment by miroslav750** [comment]
Update: Sometimes that happens also when I run all specs (11 specs, 57 scenarios) at once.

**Comment by BugDiver** [comment]
@miroslav750 I tried the steps you mentioned but no luck replicating the issue. Could you provide a sample project where we can replicate this issue.

**Comment by miroslav750** [comment]
Could problem be that I run it in docker ? When I run specs from idea everything is okay.

**Comment by Apoorva-GA** [comment]
@miroslav750 I tried running a gauge project with datatable(with 15 rows) in docker. I was able to executed the specs and open report and click on any row in table to see errors/steps.

It would be helpful, if you can share a sample project where we could replicate the issue.

**Comment by miroslav750** [comment]
Unfortunately I can not provide my project here. I guess it is some problem with mine PC cause when we run it on our company jenkins it works well.

**Comment by nehashri** [comment]
@miroslav750 Unfortunately, it is hard for us to find the source of this problem without a sample project. Feel free to reopen this issue with more details if you are facing this issue elsewhere too.
