### ISSUE TITLE
Feature Request: Info regarding retry and failed tests in context

### ISSUE THREAD

**Issue by jensakejohansson** [getgauge/gauge#1427]
I'm missing information in the context (running gauge python) regarding retries and and number of failed tests.

In "after scenario"-hook I can see if a scenarios is failing, but I cannot see if a retry will be performed (would like "current try" & "max-retries" properties). Basically I'd like to perform an action if it fails and it's the last retry.

In "after suite" I'd like to do some action if "number of failed tests" > 0. 

I can solve/workaround both these problems now, by gathering this information "manually", but it's not very nice. Gauge should have this information I guess, so it's just matter of exposing it?

Best regards,

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
