### ISSUE TITLE
Feature request: Reusability for environment variables

### ISSUE THREAD

**Issue by Christoffer-Green** [getgauge/gauge#1428]
To be able to create a better structure for my defined environments I would like to be able to reuse variables from within the same _.properties_ file.

Example:
```
service_url=http://service.com
api_url=<service_url>/api/endpoint
```

This would enable me to use the inheritance from the **default.properties** file to a much greater extentent. 
It would in some cases also make a large set of env files less fragile e.g you forget to alter a variable and the tests fail because it's trying to access endpoints on a different server.

**Comment by jbadeau** [comment]
Def an interesting feature. :)

**Comment by zabil** [comment]
Gauge uses the standard property files format. Unfortunately the standard property files does not support re-usability. So this can't be implemented in Gauge.
