### ISSUE TITLE
Gauge: command not found on docker image for python on linux 16.04

### ISSUE THREAD

**Issue by Simran-Jit-Singh** [getgauge/gauge#1429]
I am using the gauge docker image in my Dockerfile 
FROM getgauge/gocd-jdk-mvn-python
...

url: https://hub.docker.com/r/getgauge/gocd-jdk-mvn-python

### Actual behavior
When it run this image in interactive mode using command _docker run -it --name <image_name> bash_
and run gauge
then I get the out put _bash: gauge: command not found_

Am I using the correct image for gauge python?
Do I need to install gauge separately despite this image?

**Comment by Apoorva-GA** [comment]
@Simran-Jit-Singh the [image](https://hub.docker.com/r/getgauge/gocd-jdk-mvn-python) is used to run gauge projects in [gocd](https://www.gocd.org/).
This image does not contain gauge or any plugins, these are installed as part of the build.
So if you are using this image you will have to install gauge and required plugins.

**Comment by Simran-Jit-Singh** [comment]
Thanks @Apoorva-GA

**Comment by BugDiver** [comment]
@Simran-Jit-Singh We do not recommend end users to use these images. These are not meant to be used by an end user.
If you are looking for running gauge + python inside a docker image, I guess you should use the official `python` image and then installing `gauge` binary and plugins on top of it.
