### ISSUE TITLE
@AfterSpec creates new object, instead of reusing the object that was used for @Step and @BeforeSpec, losing state

### ISSUE THREAD

**Issue by timhurkmans** [getgauge/gauge#143]
When running @BeforeSpec and @AfterSpec, a new object is constructed for both @BeforeSpec __and__ @AfterSpec methods. This is unexpected as the state is preserved when calling @BeforeSpec and @Step, but a new state is created for the @AfterSpec call.

Fix would be to make sure that during @AfterSpec the original object/state is reused, instead of a new object/state being created.

My use case: @BeforeSpec: create Selenium WebDriver, @AfterSpec: close WebDriver. This way a new browser is created for each spec.

Output:

	[INFO] --- gauge-maven-plugin:1.0.1:execute (default) @ afterSpecTest ---
	MyTestSpec
	==========
	Constructing new TestImplementation object
	Running BeforeSpec
	
	Test Scenario
	-------------
	←[0;34;49m* MyTestStep
	←[0mRunning TestStep
	←[2A←[0;32;49m* MyTestStep
	←[0m←[2BConstructing new TestImplementation object
	Running AfterSpec
	[Html Report Plugin] : Sucessfully generated html reports to => [..some path..]
	11:54:05.025 [INFO] 1 scenarios executed, 0 failed

Spec file:

	MyTestSpec
	=====================
	The implementation class TestImplementation has the @Step MyTestStep, 
	and implementations for @BeforeSpec and @AfterSpec. When @AfterSpec is 
	executed, a new TestImplementation object is created, which is unexpected.
	
	Test Scenario
	--------------
	* MyTestStep

Implementation file

	public class TestImplementation {
		public TestImplementation() {
			System.out.println("Constructing new TestImplementation object");
		}
	
		@BeforeSpec
		public void setUp(SpecificationInfo info) {
			System.out.println("Running BeforeSpec");
		}
	
		@AfterSpec
		public void tearDown(SpecificationInfo info) {
			System.out.println("Running AfterSpec");
		}
	
		@Step("MyTestStep")
		public void testStep() {
			System.out.println("Running TestStep");
		}
	}

**Comment by ApoorvaM** [comment]
Gauge has a configuration to specify the level at which you want to clear the cache and use new objects. By default, this is at scenario level.

If you want it to be at specification level, you can set this property in PROJECT_ROOT/env/default/java.properties :
```
gauge_clear_state_level = spec
```
Refer [documentation](http://getgauge.io/documentation/user/current/test_code/java/configuration.html#gauge_clear_state_level) to see all the possible levels to clear cache.

**Comment by timhurkmans** [comment]
Ok, I understand now. My advice is that you put some warnings about the cache on the hooks page, to avoid confusion.

**Comment by ApoorvaM** [comment]
Thank you for the feedback. We will enhance the documentation.
