### ISSUE TITLE
Plugins are not installed when running the validate command

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge#1430]
### Expected behavior
Currently, when running the `gauge run`, it installs the required plugins if not installed already. The behaviour should be the same when running the `gauge validate` command.

### Actual behavior
Errors on missing plugins.

### Steps to reproduce
1. Uninstall one of the required plugins, e.g. `java`
2. Run `gauge validate specs/`
3. Should install the missing `java`, but errors with `plugin not found`

### Gauge version
```
Gauge version: 1.0.5

Plugins
-------
flash (0.0.1)
html-report (4.0.8)
java (0.7.2)
js (2.3.4)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)
```

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
Tested version: ```Gauge version: 1.0.6.nightly-2019-07-04```
