### ISSUE TITLE
Install failed behind a proxy, unable to get local issuer certificate

### ISSUE THREAD

**Issue by shane51** [getgauge/gauge#1433]
I was trying to install gauge with testcafe, but after npm intall, I found only testcafe was installed ,but gauge was not installed successfully.

### Expected behavior
Install gauge behind a proxy server without `unable to get local issuer certificate` issue

### Actual behavior
Get `unable to get local issuer certificate` error when install by brew or npm

### Steps to reproduce

`npm install -g @getgauge/cli` or
`brew install gauge`

error message:
```
Fetching download url for Gauge version 1.0.5
Downloading https://github.com/getgauge/gauge/releases/download/v1.0.5/gauge-1.0.5-darwin.x86_64.zip to ./bin
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)
    at TLSSocket.emit (events.js:200:13)
    at TLSSocket._finishInit (_tls_wrap.js:792:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}
```

**Comment by nehashri** [comment]
Please check https://github.com/getgauge/gauge-js/issues/205#issuecomment-502553881

**Comment by shubhamsc** [comment]
@shane51 You can try to install gauge with [offline installation](https://docs.gauge.org/latest/installation.html#alternate-installation-methods) and [set proxy](https://docs.gauge.org/latest/configuration.html#http-proxy) to connect the gauge with the internet for download plugins, templates.

**Comment by shane51** [comment]
@shubhamsc @nehashri  it works with offline installation. thanks.
