### ISSUE TITLE
Create a landing page for downloads.gauge.org

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge#1434]
Currently, the landing page of downloads.gauge.org shows the index page listing with no content. 

The url's shared on in the configuration https://downloads.gauge.org/plugins and https://downloads.gauge.org/gauge must also have a landing page or link to documentation so that users know how Gauge uses this url.

**Comment by Apoorva-GA** [comment]
Landing page should be shown when https://downloads.gauge.org is hit.
