### ISSUE TITLE
Retry failed test atleast n number of times before marking it as passed.

### ISSUE THREAD

**Issue by jonathangiber** [getgauge/gauge#1435]
I would like to get more confidence in the retry feature before using it.

If I have a flaky test, I will find the reason for the failure and fix it, but there are some situations where the error can't be expected, for example, a network error. This is when this feature could be handy for me, to minimize the risk of passing a flaky test, I would like to set an amount of retry times if a test fail.

For example, when a test fail, I would like the same test to pass two/three more times . This will give me confidence the test isn't flaky and it was a sporadically error.

This mechanism with https://github.com/getgauge/html-report/issues/230 would give the full solution for it.
Thanks

**Comment by zabil** [comment]
Closing this as Gauge will not be implementing this feature.
