### ISSUE TITLE
Can not install gauge on Ubuntu

### ISSUE THREAD

**Issue by eranga4u** [getgauge/gauge#1437]
### When i trying to install gauge on the Ubuntu getting following error 

 as per the logs i have , i  think its an error on OpenPGP key that i passed as argument 

` sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0D
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.Y6Wr1scJX2 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/openjdk-r-ppa.gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0D
gpg: requesting key 023EDB0D from hkp server pool.sks-keyservers.net
gpgkeys: key 023EDB0D not found on keyserver
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0`

**Comment by nehashri** [comment]
@eranga4u Can you please provide the exact commands you are using to install Gauge?
Also, which version of Ubuntu are you on?

**Comment by eranga4u** [comment]
@nehashri 
Its Ubuntu 16.04
I was able to resolve this issue by changing shell commands
Working shell command as follows 
`        commands:
          - shell: sudo add-apt-repository ppa:webupd8team/y-ppa-manager;
          - shell: echo deb http://dl.bintray.com/gauge/gauge-deb stable main | sudo tee -a /etc/apt/sources.list
          - shell: sudo apt-get update;sudo apt-get install -y y-ppa-manager
          - shell: sudo apt-get install -y --force-yes gauge;gauge --version;mvn test-compile gauge:execute -Dtags=BVT -DspecsDir="specs" -Denv="dev" `

**Comment by nehashri** [comment]
@eranga4u Thanks for letting us know the solution.
