### ISSUE TITLE
Issue with command line execution

### ISSUE THREAD

**Issue by ShankarChoudhury** [getgauge/gauge#1438]
I have the below configuration for my Gauge project
Gauge version - 1.0.5
IntelliJ version - 2019.1.3 CE

Description - 
1. I have 2 spec files under specs folder and corresponding step definitions/implementations under a package in src folder
2. Spec/s are running fine when i execute them by right clicking > Run specifications
3. However,when i cd into the Project root folder and run 'gauge run specs/' command,i am getting error as below.

----------------------------------- Error Log-------------------------------------

C:\Usersxxx\IdeaProjects\BddTest>gauge run specs/
src\test\java\com\getgauge\Googlecheck.java:4: error: package org.openqa.selenium does not exist
import org.openqa.selenium.By;
                          ^
src\test\java\com\getgauge\Googlecheck.java:5: error: package org.openqa.selenium does not exist
import org.openqa.selenium.Keys;
                          ^
src\test\java\com\getgauge\Googlecheck.java:6: error: package org.openqa.selenium does not exist
import org.openqa.selenium.WebDriver;
                          ^
src\test\java\com\getgauge\Googlecheck.java:7: error: package org.openqa.selenium.chrome does not exist
import org.openqa.selenium.chrome.ChromeDriver;
                                 ^
src\test\java\com\getgauge\Googlecheck.java:12: error: cannot find symbol
    WebDriver driver;
    ^
  symbol:   class WebDriver
  location: class Googlecheck
src\test\java\com\getgauge\Googlecheck.java:18: error: cannot find symbol
    driver = new ChromeDriver();
                 ^
  symbol:   class ChromeDriver
  location: class Googlecheck
src\test\java\com\getgauge\Googlecheck.java:24: error: cannot find symbol
        driver.findElement(By.xpath("//input[@name='q']")).sendKeys("Appium");
                           ^
  symbol:   variable By
  location: class Googlecheck
src\test\java\com\getgauge\Googlecheck.java:25: error: cannot find symbol
        driver.findElement(By.xpath("//input[@name='q']")).sendKeys(Keys.ENTER);
                                                                    ^
  symbol:   variable Keys
  location: class Googlecheck
src\test\java\com\getgauge\Googlecheck.java:25: error: cannot find symbol
        driver.findElement(By.xpath("//input[@name='q']")).sendKeys(Keys.ENTER);
                           ^
  symbol:   variable By
  location: class Googlecheck
9 errors
Error ----------------------------------

Failed to start gauge API: Runner with pid 3448 quit unexpectedly(exit status 1).

Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
        windows, 1.0.5, 562f036
        html-report (4.0.8), java (0.7.2), screenshot (0.0.1)
------------------------------ End of Error Log ---------------------------------
Note - The specs run just fine from IntelliJ IDE(Right click on spec folder > Run specifications)

**Comment by nehashri** [comment]
@ShankarChoudhury Are you using any build tool like Maven or Gradle?

**Comment by ShankarChoudhury** [comment]
Yes,we use Maven as the build tool.

**Comment by nehashri** [comment]
@ShankarChoudhury The command you are using to run Gauge with maven is wrong. The correct command to use with maven is `mvn test-compile gauge:execute -Dspecs="specs"`.
Refer https://github.com/getgauge-contrib/gauge-maven-plugin for the correct usage of Gauge with maven.

**Comment by ShankarChoudhury** [comment]
Thanks nehashri. Works fine now!

**Comment by nurayttumer** [comment]
same issue for me . Any solutions ? I'm trying to use gauge with selenium . I 'm new and I don't know  how to do it. I'm open to any kind of documents or tutorials . 
![Screenshot_1](https://user-images.githubusercontent.com/29413193/72897203-78a59c80-3d32-11ea-8573-f9ba0a43b40c.png)

**Comment by zabil** [comment]
This link

https://www.lambdatest.com/blog/how-to-perform-test-automation-with-gauge-selenium-framework/

Has a good summary of using Gauge with selenium. It uses Gauge's selenium template and maven to run the tests.

**Comment by nurayttumer** [comment]
Thanks @zabil  I'm checking it now .
