### ISSUE TITLE
Failed to start gauge API on windows machine 

### ISSUE THREAD

**Issue by adea11** [getgauge/gauge#1439]
### Expected behavior
Tell us what should happen

### Actual behavior
C:\Gauge Test\gauge-testing>npm test
 
> gauge-taiko-template@0.0.1 test C:\Gauge Test\gauge-testing
> gauge run specs/
 
Error ----------------------------------
 
Failed to start gauge API: fork/exec index.bat: invalid argument
 
Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://gitter.im/getgauge/chat
 
Your Environment Information -----------
        windows, 1.0.5, 592hg36
        flash (0.0.1), html-report (4.0.8), js (2.3.5), json-report (0.3.1), screenshot (0.0.1), spectacle (0.1.3), xml-report (0.2.1)
npm ERR! Test failed.  See above for more details.

### Steps to reproduce
1. Install and execute gauge test on windows 8
2.
3.

### Gauge version
Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
flash (0.0.1)
html-report (4.0.8)
js (2.3.5)
json-report (0.3.1)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)

**Comment by osandadeshan** [comment]
@zabil: FYA

**Comment by BugDiver** [comment]
@adea11  I could not get hold of a Windows 8, although I tried replicating your issue with windows 10 and things worked perfectly fine.
Could you please try uninstalling `gauge-js`, reinstall and create/run a sample project?

**Comment by Apoorva-GA** [comment]
Gauge is not supported on windows8. Can you please confirm if you face this issue on windows 10 as well?

**Comment by adea11** [comment]
Sorted
