### ISSUE TITLE
Issue in rerunning failed test cases, with maven plugin

### ISSUE THREAD

**Issue by singla48** [getgauge/gauge#1440]
I am using maven gauge plugin 1.4.1

-Dflags=“—failed”

Using this flag, sometimes it gives the correct result in failure.json but when I increase the script count or there are more failures then all the test scenarios is getting updated in failure.json.

Ideally only failed scenarios should be there in failure.json after one execution, but sometimes it is having passed test cases also.

I am using gauge 0.9.7

Please guide me of this is an open issue in maven gauge plugin ?

**Comment by BugDiver** [comment]
@singla48  I don't think there is an open issue related to yours.
I see that you are using quite an old version of `gauge`. We have done a lot of bug fixes since then. The latest version of `gauge` is `1.0.6`, Would you please upgrade the gauge version and see if the issue still exits.

**Comment by Apoorva-GA** [comment]
Closing this for now. Feel free to reopen if you are still facing this.
