### ISSUE TITLE
Feature Request: Ability to control the order in which spec files are executed

### ISSUE THREAD

**Issue by thaestrup** [getgauge/gauge#1441]
### Feature description
I have some spec files that contain logic for logging into the system before the other specs are run. I would be great if I could somehow determine the order in which the specs are executed such that the specs concerning logging in could be run before the others. At least that would be one way to do it.

### The problem it solves
My issue is that I have a great deal of scenarios for logging into the system with different environments and different user types and different authorization flows. I can control these by tags but I would like not to include all this logic in all of the spec files as that would mean a lot of duplication.

### What I do until this is supported
To circumvent this issue I have for now created a "Log In" step that is to be run as a context step in every spec file. That "Log In" will lookup the needed actions the SuiteStore and perform the login. Then I have a beforeSuite function that reads the tags out of the command line given to gauge when I run it through "npm run". It parses the tags concerning the different parameters mentioned above and then stores them in the SuiteStore. It is not beautiful but it gets the job done.

### Gauge version

```
Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
html-report (4.0.8)
js (2.3.5)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)

Taiko
Version: 0.8.0 (Chromium:76.0.3803.0)

```

**Comment by BugDiver** [comment]
@thaestrup Thanks for raising your request. We will triage the issue, and try to work on it when possible. Keep following the issue for more information/updates.

/cc @getgauge/core

**Comment by zabil** [comment]
Due to the technical complexity of adding this feature Gauge will not be implementing this.
