### ISSUE TITLE
Javascript support in IntelliJ plugin

### ISSUE THREAD

**Issue by philipbeadle** [getgauge/gauge#145]
I really love the idea of using Markdown to write my test steps, however i do mostly Angular development so really need a plugin for IntelliJ :)  Would love to help out on a project for it.

**Comment by sriv** [comment]
Thanks for the feedback. I'll take a crude shot in describing what this would take:

1. Add Javascript support in Gauge (#119 already mentions this). This would mean writing a new plugin that would enable Gauge to run Javascript implementations. [This doc (WIP)](http://getgauge.io/documentation/technical/current/) aims to capture the details.

2. Enhance the Intellij Plugin to support Javascript. This could piggyback on existing Intellij support for Javascript for features such as Auto-complete, Syntax highlighting etc. and can use the exising Gauge-Intellij features for Refactoring, Test execution etc.

I think (2) is simpler, but (1) would be the crucial bit to address. We have had a few people express interests in contributing to a Javascript plugin, but there isn't much progress AFAIK.

**Comment by mahendrakariya** [comment]
Expecting community to contribute.
https://github.com/vishnukarthikl/gauge-js

**Comment by mahendrakariya** [comment]
@renjithgr is working on a javascript plugin for Gauge.
More details at https://github.com/renjithgr/gauge-js

**Comment by mahendrakariya** [comment]
Javascript plugin v1.0.0 has been released.
https://github.com/getgauge-contrib/gauge-js/releases

**Comment by apoorvam** [comment]
This issue was moved to getgauge/Intellij-Plugin#119
