### ISSUE TITLE
Read csv file data always take effect from third row 

### ISSUE THREAD

**Issue by cnhkzyy** [getgauge/gauge#1451]
### Expected behavior
Read cvs file data can take effect from second row when first is head

### Actual behavior
Read csv file data take effect from third row actually

### Steps to reproduce
1. Make dir named resources below root dir
2. Make csv file named users.csv inside resources dir
3. Create a scenario that use an external csv file
4. Run this scenario

### Gauge version
1.0.5

### PC version
windows 7

### Screenshot
![Image 1](https://user-images.githubusercontent.com/29578918/60823996-64a5ad80-a1db-11e9-8b51-b7f143b8c051.png)
![Image 2](https://user-images.githubusercontent.com/29578918/60823995-640d1700-a1db-11e9-84b3-b83441a8eca0.png)
![Image 4](https://user-images.githubusercontent.com/29578918/60824084-9159c500-a1db-11e9-9370-b86721e5ce44.png)

**Comment by shubhamsc** [comment]
@cnhkzyy When you're writing a line with using `#` in your CSV file, Gauge read that line as a comment and ignore that comment line.
The first line of the CSV file(not a comment line), Gauge read as table header and all other as table rows.
So in your case - `# Users` will ignore as a comment. That's why table rows will start from the 3rd line.

**Comment by cnhkzyy** [comment]
> @cnhkzyy When you're writing a line with using `#` in your CSV file, Gauge read that line as a comment and ignore that comment line.
> The first line of the CSV file(not a comment line), Gauge read as table header and all other as table rows.
> So in your case - `# Users` will ignore as a comment. That's why table rows will start from the 3rd line.

Thank you very much. I think that gauge document should provide more detail for how to use, sometimes I met some questions but can't find some useful info in document.  For example, how to get table row value, how to get csv file value etc. 

Actually, I understand some usage until reading offical project,  gauge is a good frame, hope it better !

**Comment by cnhkzyy** [comment]
This is an invalid bug, so close it.

**Comment by Sathyan87** [comment]
Hi All,

I am new to Gauge automation.How to read text from xlsx or csv and fill the Form values (example:Face book login form and Sign up form). kindly help me with Sample Specification and .js file.

Thanks

**Comment by zabil** [comment]
> How to read text from xlsx or csv and fill the Form values (example:Face book login form and Sign up form). kindly help me with Sample Specification and .js file.

Please read https://docs.gauge.org/execution.html#external-csv-for-data-table
