### ISSUE TITLE
Gauge should handle multiple structured log entries properly.

### ISSUE THREAD

**Issue by negiDharmendra** [getgauge/gauge#1452]
### Expected behavior
Gauge's runner or plugin writes two structured log entries and Gauge prints them accordingly.

**Example:**
```
{"logLevel":"debug","message":"log debug message"}
{"logLevel":"info","message":"log info message"}
```
Above log entries should be printed as below.
- When log level is set to debug

        log debug message
        log info message

- When log level is set to info

        log info message
### Actual behavior
Gauge does not process them correctly and prints them as follow regardless of the log level.

**Example:**
```
      {"logLevel":"debug","message":"log debug message"}
      {"logLevel":"info","message":"log info message"}
```
### Gauge version
```
Gauge version: 1.0.6
Commit Hash: df8d663d
```

**Comment by Debashis9012** [comment]
This has been verified with version: `1.0.6.nightly-2019-07-16`
