### ISSUE TITLE
gauge update is not working

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/gauge#1453]
### Expected behaviour
gauge should show the update if the current version is not the latest

### Actual behaviour
gauge does not show the update.

### Steps to reproduce
1. Install an old version of `gauge` 
2. Run `gauge update -c`
3. It does not show the available update.

## Dev Notes

The URL to check `gauge` update `https://downloads.gauge.org/gauge`  is broken. It proxies to a old YML file from `getgauge.github.io` repo.

**Comment by M4rk9696** [comment]
Issue seems to be in version `v1.0.4` and older

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
