### ISSUE TITLE
Unable to run gauge specifications with latest nightly of language runner and released version of gauge

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/gauge#1455]
### Expected behavior
With latest nightly version of language runner and released version of gauge we should be able to run specifications successfully with out any errors. 

### Actual behavior
Getting the below error while we are running specs:
```
Failed to start gauge API: Compatibility error. Incompatible version. Minimum support version 1.0.6 is higher than current version 1.0.5
```

### Steps to reproduce
1. Install gauge release version 
2. Install latest nightly of language runner(csharp,python,js,ruby)
3. `gauge run specs`

### Gauge version
```
Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
csharp (0.10.6.nightly-2019-07-15)
html-report (4.0.8)
js (2.3.6.nightly-2019-07-16)
python (0.3.6.nightly-2019-07-04)
ruby (0.5.3.nightly-2019-07-15)
```

**Comment by BugDiver** [comment]
The error message is right and expected. The latest version of runner won't work with released Gauge. The latest nightlies contain some changes which are only compatible with the latest Gauge, that's the reason we have restricted the version to 1.0.6.
