### ISSUE TITLE
Follow the Freedesktop XDG base directory standard (in Linux)

### ISSUE THREAD

**Issue by x80486** [getgauge/gauge#1458]
On Linux, Gauge currently creates a `${HOME}/.gauge/` subdirectory. Most applications/programs don't create such things anymore in the user's home, but instead follow the `Freedesktop XDG` standard – found here: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html.

Using this standard:
- `${XDG_CACHE_HOME}` says "temporal/non-essential" files go to `${HOME}/.cache/`
- `${XDG_CONFIG_HOME}` says "configuration files" go to `${HOME}/.config/`
- `${XDG_DATA_HOME}` says "data files" go to `${HOME}/.local/share/`

This is just a request to consider using this standard. It makes a lot of sense; it is easy for the user to understand, makes it easier to backup / locate / restore / manage / clear user's data, and creates less clutter in the user's home directory.

Thanks in advance...and thanks so much for everyone's hard work on Gauge – it's amazing, and the `Go` plugin needs more love!

**Comment by zabil** [comment]
> Thanks in advance...and thanks so much for everyone's hard work on Gauge – it's amazing

:-)

> Most applications/programs don't create such things anymore in the user's home, but instead follow the Freedesktop XDG standard

The XDG standard only applies to linux. Mac and Windows use different layouts. `.gauge` folder is a middle ground. However, like you mentioned, guidelines on all these platforms recommend not polluting the user space.

This article has a good write up about directories for the MacOS https://stackoverflow.com/questions/3373948/equivalents-of-xdg-config-home-and-xdg-data-home-on-mac-os-x

We will take a look at this. If implemented, this should preserve backward compatibility.

**Comment by lhanson** [comment]
https://github.com/OpenPeeDeeP/xdg follows the spec on Linux while preserving the usual OS defaults on other platforms, and simplifies cross-platform compatibility to boot. It's also dead simple to default to legacy locations where spec-compliant files aren't found.

**Comment by zabil** [comment]
Implementing this across platforms and preserving backward compatibility is not easy. 
For the sake of simplicity Gauge will stick to `.gauge` folder.

**Comment by lhanson** [comment]
I understand that supporting this functionality is clearly not as easy as continuing to punt to an arbitrary catch-all `$HOME/.gauge` folder, but I dont't imagine that it's that difficult to implement. Was there some discussion or analysis of the effort required that led to the decision to close the issue that we're not seeing? Would you reconsider?

A common refrain I see from projects reticent to adopt this standard is that it requires too much effort for a benefit that maintainers don't really understand. As the maintainer of a single project this is perhaps understandable; many developers don't personally feel the pain of trying to implement workarounds in their own file management/backup automation to account for each and every special snowflake directory dumped into your `$HOME` ignoring your explicit preferences; that's just the way it's "always been done"! However, the effort required to be a good citizen on our users' systems and respect their preferences is so very small for a given project compared to the frustration compounded across each user of each program which doesn't respect them.

If the project team is still unconvinced that this is functionality worth expending effort on, would you at least accept a patch?

**Comment by zabil** [comment]
Thanks for taking time to explain this.

> Was there some discussion or analysis of the effort required that led to the decision to close the issue that we're not seeing? Would you reconsider?

* This format is not standard across across OS's. So adopting this on Windows and MacOS maybe be based on assumptions.
* Complicates support and documentation for new and existing users.
* Breaking changes for existing Gauge users (Backwards compatibility)
* And priority, as there are other issues in the queue.

> If the project team is still unconvinced that this is functionality worth expending effort on, would you at least accept a patch?

Yes, a patch is welcome as long as it is mindful of current users. 

A suggestion is making all these directories configurable (need to figure out how to initialise the config folder first) Or implement this only on Linux.

**Comment by lhanson** [comment]
Thanks! I definitely understand that this isn't high on the priority list. I'll take a shot at writing a patch that takes all of your concerns into account.

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
@lhanson please reach out if you need any help.
