### ISSUE TITLE
Add more Gauge logs

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#1459]
Gauge logs is not quite adequate at present. Gauge should log all activities it does, this helps in debugging any issues that come up and also help in 

Gauge should list all activities performed during runs. 
- [x] Parsing started and ended, all errors should be listed too
- [x] Validation started and ended, all errors should be listed too
- [x] Run started, no of streams, any filters being applied. No of specs/scenarios before and after filter.
- [x] For serial with parallel run, should indicate how many scenarios are run in serial vs parallel.
- [x] Execution for each spec scenario and step. Logs should have verbose logging enabled by default.
- [x] Indicate kill message being sent to plugin.
- [x] Indicate starting plugin.
- [x] Indicate after plugin connected.
- [x] Suite datastore init
- [x] List the command being executed
- [x] Check if any errors occur and log them.

**Comment by nehashri** [comment]
Some more logs to be added,
- [ ] Number of concepts, steps found (after parsing and also after validation stages)
- [ ] Any protobuf message sent to the runner or broadcasted to other plugins.

**Comment by Debashis9012** [comment]
Tested and verified the above list of activities.
Tested version: 
```
Gauge version: 1.0.7
Commit Hash: 104e7eef
```
