### ISSUE TITLE
Unable to Execute a spec on Eclipse Kepler 4.3.2 & Luna

### ISSUE THREAD

**Issue by firozshaik1987** [getgauge/gauge#146]
I have configured an example project into Eclipse (after installing Xtext plugin & Gauge Plugin for java).
While trying to run a sample spec as shown in the attached screenshot('Run as Gauge Specs'), nothing happens. It is not being executed. It does not even giving a console out put or at least an error..Nothing it does or display....No clue at all.. I have been trying it for the past two days. Please help me on how to execute it on Eclipse. As per the documentation it should support Kepler 4.3.2 & Luna.
I am able to run the specs through command line and able to see both XML and HTML reports.
The problem is only with the gauge Eclipse Plugin... Please help me run a spec on Eclipse. It looks like an Issue with the Gauge-Eclipse plugin itself.
![unabletorunaspeconeclipse](https://cloud.githubusercontent.com/assets/12591863/7792859/787144ae-02d5-11e5-872d-0f1b02a16dfb.jpg)
![gaugeandxtextalreadyinstalled](https://cloud.githubusercontent.com/assets/12591863/7792862/876f6076-02d5-11e5-92e0-492e49ca483d.jpg)

**Comment by sriv** [comment]
There is a known issue with the Gauge-Eclipse plugin and Windows : getgauge/gauge-eclipse#7. Although this is fixed, we are yet to release it out, apologies for this. We should get an update out soon.

In the meantime, you could try using our [Intellij plugin](http://getgauge.io/documentation/user/current/ide_support/intellij_idea.html), as at the moment it is far ahead when it comes to feature support.

**Comment by prateekbaheti** [comment]
Fix released in the  [Gauge-Eclipse plugin release 0.0.3](https://github.com/getgauge/Gauge-Eclipse/releases/tag/v0.0.3).
Closing the issue.
