### ISSUE TITLE
specify table rows per specification/scenario in Gauge  execution

### ISSUE THREAD

**Issue by adea11** [getgauge/gauge#1460]
### Expected behavior
Should be able to pass external csv table into scenario

### Actual behavior
can only execute against a role via command e.g <gauge run --table-rows "1" specs/hello.spec>

### Steps to reproduce
run spec file with external csv file (multiple role) using "gauge run specs"

### Gauge version
```
Gauge version: 1.0.5
taiko Version: 0.7.1 (Chromium: 74.0.3723.0) 

Plugins
-------
flash (0.0.1)
html-report (4.0.8)
js (2.3.5)
json-report (0.3.1)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)

**Comment by adea11** [comment]
https://github.com/getgauge/gauge/issues/604

**Comment by negiDharmendra** [comment]
Hi @adea11,

If you are trying to run different scenarios against a different row of the data table.
You should probably look at [Table driven scenario](https://docs.gauge.org/latest/experimental-feature.html#table-driven-scenario). There are few limitations (as explained in the docs) with this feature as it's an experimental feature.

```
Since this is ans experimental feature there are few cases in which it currently does not work:

    IDE plugins does not support this feature.
    CSV files can not be used as table for scenario.
    Reporting plugins does not accommodate this feature.
```

**Comment by adea11** [comment]
@negiDharmendra, I'm trying to execute a scenario against a specific row in my csv table. For example

# My Spec 

   |    user| password|   
   |-------|----------|
   | user A| ****         | 
   | user B| ****         | 
  

scenarios
## Login as user A --[row 1]

## Login as user B -- [row 2] 


**Unrelated question: Is there a way to avoid the data table from appearing in console when test is executed?**

**Comment by negiDharmendra** [comment]
> Unrelated question: Is there a way to avoid the data table from appearing in console when test is executed?

I am afraid, there is no way to hide the data table from the console.


>can only execute against a role via command e.g <gauge run --table-rows "1" specs/hello.spec>

Right now this is the only way to execute a scenario against a specific row.

if you really want to run a scenario against a specific row you can use the [Table driven scenario](https://docs.gauge.org/latest/experimental-feature.html#table-driven-scenario) (as I have already suggested in my [previous](https://github.com/getgauge/gauge/issues/1460#issuecomment-519400053)  comment. 

Just being curious, are these two scenarios doing the same thing?

**Comment by adea11** [comment]
@negiDharmendra, thanks for your reply. The scenarios perform different tasks and each user is configured specifically for each scenario

**Comment by adea11** [comment]
Table driven scenario will not be tidy if I'll be executing up to 20 scenarios and a different user for each one.

**Comment by negiDharmendra** [comment]
@adea11 I am afraid, there is no way to map a Table to a scenario.

**Comment by nehashri** [comment]
@adea11 As @negiDharmendra mentioned, there isn't a way to map a table to to a specific scenario.
You can just as well parameterise the table parameters in your scenario as simple parameters.
Ex: 
```
## Login as user A
* Login with "user A" and password "****"

## Login as user B 
* Login with "user B" and password "****"
```
The purpose of a Table driven scenario is to run the same scenario with multiple parameter values.

PS: I will be closing this issue as this is not a valid use case for using table driven scenarios.
