### ISSUE TITLE
[Enhancement] Publish a .tar.gz for Linux

### ISSUE THREAD

**Issue by x80486** [getgauge/gauge#1464]
For Linux releases, I think it would be great if a `.tar.gz` file is published, instead of the actual `.zip`.

Actually, you can publish both if you want to :wink: ...but `.tar.gz` is more appropriate, in general, for UN*X.

**Comment by zabil** [comment]
It's better to pick one format. The zip format is preferred as it is easy to work with programmatically with various zip libraries.
