### ISSUE TITLE
Installing with npm fails

### ISSUE THREAD

**Issue by luksi1** [getgauge/gauge#1470]
I've followed the instructions verbatim to install gauge from "https://gauge.org/getting-started-guide/quick-install/" and I'm unable to install it.

I'm starting from a fresh GCP Debian instance. After installing the NodeJS PPM and then following the instructions, "gauge" is installing a blank file under /usr/lib/node_modules/@getgauge/cli/bin.  I'm getting the following file permission error. This is all run as root.

Additionally, another person was able to verify the same results, but with Docker. See this thread on the Google forum:

https://groups.google.com/d/topic/getgauge/18wEnSftMtk/discussion

### Terminal output 

```
root@instance-1:~# npm -v
6.9.0
root@instance-1:~# node -v
v10.16.3
root@instance-1:~# npm install -g npm@latest
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.11.2
added 19 packages from 13 contributors, removed 15 packages and updated 53 packages in 6.895s
root@instance-1:~# npm install -g @getgauge/cli
/usr/bin/gauge -> /usr/lib/node_modules/@getgauge/cli/bin/gauge

> @getgauge/cli@1.0.5 install /usr/lib/node_modules/@getgauge/cli
> node ./src/index.js

Fetching download url for Gauge version 1.0.5
Downloading https://github.com/getgauge/gauge/releases/download/v1.0.5/gauge-1.0.5-linux.x86_64.zip to ./bin
{ [Error: EACCES: permission denied, open 'bin/gauge'] errno: -13, code: 'EACCES', syscall: 'open', path: 'bin/gauge' }
+ @getgauge/cli@1.0.5
added 83 packages from 76 contributors in 6.48s
```

### Expected behavior
Gauge should install

### Actual behavior
Gauge doesn't install

### Steps to reproduce
1. npm install -g @getgauge/cli

### Gauge version
```bash
root@gauge:~/gaugetest$ npm -v
6.11.2
root@gauge:~/gaugetest$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch
```

**Comment by Apoorva-GA** [comment]
@luksi1 Could replicate the issue. We will work on fixing this soon.

**Comment by BugDiver** [comment]
@luksi1  I could not get hold of GCP instance, but I could replicate in on `docker`. 

Could you please try installing with ``npm install -g @getgauge/cli --unsafe-perm``?
It worked for me on `docker`.

**Comment by luksi1** [comment]
It worked perfect.

```bash
luke@vscode:~$ sudo npm install -g @getgauge/cli --unsafe-perm
/usr/bin/gauge -> /usr/lib/node_modules/@getgauge/cli/bin/gauge

> @getgauge/cli@1.0.6 install /usr/lib/node_modules/@getgauge/cli
> node ./src/index.js

Fetching download url for Gauge version 1.0.6
Downloading https://github.com/getgauge/gauge/releases/download/v1.0.6/gauge-1.0.6-linux.x86_64.zip to ./bin
+ @getgauge/cli@1.0.6
updated 1 package in 5.034s
luke@vscode:~$ gauge -v
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
No plugins found
Plugins can be installed with `gauge install {plugin-name}`
```

**Comment by BugDiver** [comment]
Great. Closing the issue.
