### ISSUE TITLE
Consistent Cross Platform/Language Support

### ISSUE THREAD

**Issue by tsyed** [getgauge/gauge#148]
Is gauge integration possible for Android and ios platforms - Please guide.

**Comment by tsyed** [comment]
Is gauge integration possible for Android and ios platforms - Please guide.

**Comment by deepthigc** [comment]
You can definitely use Gauge to write tests for Android or iOS apps. Gauge
is driver independent, so this lets you hook up Calabash <http://calaba.sh/>
/Appium <http://appium.io/> or any other similar library and test your
apps. The tests itself can be written in any of the supported languages.
These are C#, Ruby or Java currently.

**Comment by tsyed** [comment]
Thanks Deepthi. I will try these.
