### ISSUE TITLE
proxy error

### ISSUE THREAD

**Issue by spham** [getgauge/gauge#1480]
hi
when i try 
npm install -g @getgauge/cli

and i'm behind proxy's campany.

i have this error

```
Fetching download url for Gauge version 1.0.6
Error: Error: getaddrinfo ENOTFOUND api.github.com api.github.com:443
    at Request.request.get [as _callback] (X:\node-v10.16.3-win-x64\nod
e_modules\@getgauge\cli\src\install.js:46:34)
    at self.callback (X:\node-v10.16.3-win-x64\node_modules\@getgauge\c
li\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (X:\node-v10.16.3-win-x64\node_modules\@g
etgauge\cli\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
+ @getgauge/cli@1.0.6
updated 1 package in 9.739s
```

**Comment by spham** [comment]
proxy is already set and only when call api.github.com:443 , connection is refused

**Comment by zabil** [comment]
Have you tried setting both the `HTTP_PROXY` and the `HTTPS_PROXY` environment variable.
Setting this should solve the issue. 

Please refer this documentation
https://jjasonclark.com/how-to-setup-node-behind-web-proxy/

Closing this as this is not an issue with Gauge but related to having the right settings.

**Comment by spham** [comment]
it s an gauge issue. because when install plugin. gauge get plugin from
other url. and proxy is block.
so it s not a gauge issue, but it can t work in stand alone.
without js plug in.

**Comment by nehashri** [comment]
@spham Have you tried setting the proxy for Gauge? Refer https://docs.gauge.org/configuration.html#http-proxy. to set the proxy.

**Comment by spham** [comment]
yes. but proxy have multi level.
and filter some website.

**Comment by zabil** [comment]
Gauge needs access to GitHub to download and install releases. Please try
* White listing the GitHub urls in your proxy
* Or downloading the zip archive from [releases](https://github.com/getgauge/gauge/releases) and installing it.

**Comment by spham** [comment]
i think is not clear, jauge was download, but only js template can't install

**Comment by zabil** [comment]
This is what happens when you run `npm install -g @getgauge/cli`
* Download a wrapper script
* Download gauge binaries frongithub and install it on the path

After this you can initialise a javascript project using `gauge init js` which
* Downloads the gauge plugin from GitHub
* Runs npm install to install all dependencies

At all of this stages the proxy should not block GitHub or npm urls.

**Comment by spham** [comment]
already done.

gauge init js failed

**Comment by zabil** [comment]
Can you share the complete console output when running `gauge init js` ?

**Comment by spham** [comment]
gauge init js
```
Compatible language plugin js is not installed. Installing plugin...
Failed to install plugin 'js'.
Reason: Invalid plugin. Could not download js-install.json file.
```

**Comment by spham** [comment]
i try offline without success

```
C:\Users\XX\Desktop\gauge>gauge -f gauge-js-2.3.5.zip install
Error ----------------------------------

[Gauge]
File manifest.json doesn't exist.

Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
        windows, 1.0.6, 2bc49db
        Could not retrieve plugin information.
```

**Comment by nehashri** [comment]
@spham We currently can't install gauge-js plugin offline. https://github.com/getgauge/gauge-js/issues/200 should solve this issue, we will be working on this soon.

**Comment by BugDiver** [comment]
@spham We have pushed an offline installer for gauge-js.
Could you please try the following steps

* Download the installer from https://bintray.com/gauge/gauge-js/download_file?file_path=gauge-js-offline-2.3.6.nightly-2019-09-24.zip

* Run `gauge install js -f <PATH_TO_DOWNLOADED_ZIP_FILE>`

**Comment by negiDharmendra** [comment]
@spham Any update on this issue.

**Comment by spham** [comment]
wonderful, it's work perfect, thank you

**Comment by spham** [comment]
Compatible version of plugin html-report not found. Installing plugin html-report...
Failed to install plugin 'html-report'.
Reason: Invalid plugin. Could not download html-report-install.json file.
Installing required plugins.
fatal: not a git repository (or any of the parent directories): .git

**Comment by spham** [comment]
Compatible version of plugin html-report not found. Installing plugin html-report...
Failed to install plugin 'html-report'.
Reason: Invalid plugin. Could not download html-report-install.json file.
Installing required plugins.
fatal: not a git repository (or any of the parent directories): .git

**Comment by spham** [comment]
it have now an issue wirh html report

**Comment by spham** [comment]
ok it's other issue
