### ISSUE TITLE
ReferenceError: click is not defined

### ISSUE THREAD

**Issue by nanu-c** [getgauge/gauge#1484]
# Expected behavior
* install gauge
* create example
* use click()
* it works

### Actual behavior
* install gauge
* create example
* use click() fails with:
```
        Specification: specs/example.spec:11
        Error Message: {}
        Stacktrace: 
        ReferenceError: click is not defined
            at Object.<anonymous> (tests/step_implementation.js:35:2)

```

### Steps to reproduce
1. npm install  @getgauge/cli
2. gauge init js
3.  use
```
    await openBrowser();
    await goto("google.com");
    await write("taiko test automation");
    await click("Google Search");
```
4. `gauge run specs` ->it fails

### Gauge version
```
/bin/gauge -v
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
html-report (4.0.8)
js (2.3.5)
screenshot (0.0.1)

```

**Comment by shubhamsc** [comment]
@nanu-c Please make sure you require API  name from taiko before using it.
Add `click` API in require statement, it should be something like this -
```
const { openBrowser, closeBrowser, goto, click, write, text } = require('taiko');
```

**Comment by nanu-c** [comment]
You are right, stupid mistake :)
