### ISSUE TITLE
Gauge.CSharp.Core nuget package is not compatible with Gauge 1.0.6

### ISSUE THREAD

**Issue by nvborisenko** [getgauge/gauge#1486]
I use this package to communicate with gauge execution core. It works with gauge 1.0.5. After updating gauge to 1.0.6 it stops to work.

Gauge lnaguage: `dotnet`

It seems proto messages should be regenerated. Even standard `json-report` doesn't work.

Error from `json-report`
```
Failed to read proto message: unexpected EOF
```

Steps to reproduce:
- `gauge init dotnet`
- add `json-report` in manifest
- `gauge run`

```
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
csharp (0.10.5)
dotnet (0.1.1)
html-report (4.0.8)
java (0.7.2)
json-report (0.3.1)
reportportal (1.0.1)
screenshot (0.0.1)
xml-report (0.2.1)
```

**Comment by BugDiver** [comment]
Is this issue still valid?

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
