### ISSUE TITLE
[Improvement] Add ability to skip a step

### ISSUE THREAD

**Issue by sarut0bi** [getgauge/gauge#1488]
I am currently developping E2E tests on multi platform project (mobile & web project) using taiko.
I currently put the platform into specstore and make tests at the beginning of all my steps to know which action i have to do according to the platform :(
And calling a step from another step so it would be a very nice improvement if you add ability to skip next step like follows:

## Simple test
* Test1
* Test2
* Test3

step("Test1", async () => {
     gauge.skipNextStep();
});

step("Test2", async () => {
    //do whatever
});

step("Test3", async () => {
    //do whatever
});

=> will run test1, skip test2, then play test3 

It will improve the lisibility of my tests (i hope not only mine) and make them more dynamic without major breaking changes in gauge core (i think...)

**Comment by ajoecker** [comment]
cant this be done with different environments ?

The problem I would have with that is that the spec defintion is different than the implementation. As the spec defines "Simple Test" as a chain of steps, whereas the implementation does whatever it wants. Of course every implementation could do that, but I would vote against support for this from the framework.

**Comment by zabil** [comment]
> The problem I would have with that is that the spec defintion is different than the implementation. 

Agree with this. Implementations must not control the flow of execution. It's better to write the specs in a way they use tags and environments.
