### ISSUE TITLE
Feature: Re-use common step implementations across multiple apps

### ISSUE THREAD

**Issue by pradeep0601** [getgauge/gauge#1489]
### Description

Requesting a feature to group common step implementation and import wherever required.

### For Example

I am using `gauge` with `taiko`  and kept 
- all assertion validation into `assert.js`
- all click activity in `click.js` and similarly have `write.js` for writing, `focus.js` for focus etc.
 
Now i have started automation for some other app using `gauge` again and found that `assertion.js`, `click.js` etc can be re-used here, i should not be copying/writing same step implementation manually.
There should be some way to group all the common step implementation and import it here.

As i am using `gauge` with `taiko`, I was thinking to create an `npm module`  with all reusable steps and import it across multiple apps 

### Gauge version
```
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
html-report (4.0.6)
java (0.7.2)
js (2.3.4)
screenshot (0.0.1)
xml-report (0.2.1)

```

**Comment by sriv** [comment]
Have you looked at using [`Concepts`](https://docs.gauge.org/writing-specifications.html) with gauge?

**Comment by pradeep0601** [comment]
@sriv , I am using `concepts` to group steps within an application, but i want to import re-usable concepts across multiple apps.

**Comment by sriv** [comment]
@pradeep0601 - I see. In that case you can put the common steps in a directory that can be set in [`https://docs.gauge.org/configuration.html?os=windows&language=javascript&ide=vscode#js-properties-8`](https://docs.gauge.org/configuration.html?os=windows&language=javascript&ide=vscode#js-properties-8)

If you put it in a node_module, you'll have to add that path to the above property.
