### ISSUE TITLE
Feature request: Ability to define default tags to run in environment

### ISSUE THREAD

**Issue by lfdebrux** [getgauge/gauge#1491]
### Expected behavior

I would like to be able to have a line in a `.properties` file that specifies a default tag expression for gauge run, so for instance I can tell people to run smoke tests by using `gauge run --env smoke-tests`

```
# smoke-tests/default.properties
tags = !skip & smoke-test
```

**Comment by zabil** [comment]
Closing this as Gauge will not be implementing this feature.
