### ISSUE TITLE
Move away from gauge proxy.

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#1497]

**Comment by zabil** [comment]
This can actually be done using netlify redirects.
https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file

The main website https://downloads.gauge.org can hosted on netlify with a redirects files pointing to other urls. This could be S3 buckets too.

**Comment by zabil** [comment]
Sites now redirect via
https://github.com/getgauge/downloads.gauge.org
https://github.com/getgauge/templates.gauge.org
