### ISSUE TITLE
Gauge -v is not giving expected output

### ISSUE THREAD

**Issue by luciferankon** [getgauge/gauge#1505]
### Expected behavior
gauge -v should give the version details

### Actual behavior
<img width="695" alt="image" src="https://user-images.githubusercontent.com/44019225/66980623-156ef300-f0cf-11e9-8a08-6db64a24869e.png">

### Steps to reproduce
1. install gauge from master
2. run gauge -v

### Gauge version
Gauge version: 1.0.7
Commit Hash: 4e34b1fd

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
Tested version:
```
Gauge version: 1.0.7
Commit Hash: 63760ca7
```
