### ISSUE TITLE
Capture alert screenshot

### ISSUE THREAD

**Issue by suresheck** [getgauge/gauge#1510]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Gauge version
```
Run gauge -v on your system and paste the results here.
```
*Added from topic*
Gauge report not capturing the alert popup image. Can someone please help me to resolve this issue.   In Gauge html-report, while the spec is failing with alert popup,  the screenshot doesn't capturing the alert popup image. Does the gauge having the support to capture the image. Or I need to enable the settings with any code?

**Comment by nehashri** [comment]
@suresheck What frame work are you using with Gauge? Taiko or Selenium or something else? What language are you using?
Have you configured to use Gauge's custom screenshot functionality? If so, please provide a code snippet.

*PS: It would help us if you filled the above template with the correct steps to reproduce the issue, and the Gauge version*

**Comment by nehashri** [comment]
By default Gauge captures the active desktop screenshot and hence it should capture the alert popup if it appears. 

The alert popup should be captured by the screenshot function used by the test automation framework if the custom screenshot is configured. If you don't see it capturing the alert popup please raise an issue in the test automation framework you are using.
