### ISSUE TITLE
Add dynamic additional fields into spenario execution info

### ISSUE THREAD

**Issue by L2jLiga** [getgauge/gauge#1515]
*feature request*: Add additional fields to test execution info

### Motivations:

Additional fields allow to store custom information about test execution within steps.

### Example

We have scenario when we add item into cart, when test fails it would be great to know which item we tried to add (for example store item id)

### Gauge version

`master`

**Comment by zabil** [comment]
Have you tried writing the store item id as a custom message in the report?

**Comment by L2jLiga** [comment]
Make sense, thanks!
