### ISSUE TITLE
Unable to change the CSV file paths on the specs according to the different environments

### ISSUE THREAD

**Issue by osandadeshan** [getgauge/gauge#1518]
### Expected behavior
There should be a way to load the CSVs using a base file location mentioned in the environment property files. 

### Actual behavior
Assume I have 3 environments qa, uat and prod. 
The login user details (email and password) are different from environment to environment. 
Now I need to do a data driven test for the login functionality. 
So I hard coded the CSV file path on the spec file for the qa users. 
But when I need to run the same spec file against the uat or prod environments, Gauge will again pick the qa users detail CSV file since it is hard coded on the spec file.

Example:
```
# Login driven execution

table: /resources/csv/qa_users.csv

## Login scenario
* Login with username <username > and password<password>
```

When I need to run this spec against uat or prod, still gauge picks **qa_users.csv** file because we cannot change the CSV file path based on the execution environment.

### Gauge version
```
Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
flash (0.0.1)
html-report (4.0.8)
java (0.7.2)
js (2.3.5)
json-report (0.3.1)
reportportal (1.0.1)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)
```

**Comment by zabil** [comment]
Also related to https://github.com/getgauge/gauge/issues/1083

**Comment by zabil** [comment]
Instead of dealing with paths where 

* The same structure columns between csv files is not guaranteed
* It's hard to specify multiple environments and parse multiple files
* Technically difficult to handle dynamic parameters

It's better to add a filter feature on one csv file For e.g. `data.csv` with the structure

```
name, email, filter
Jane, jane@doe.com, default
John, John@doe.com, qa
Foo, foo@bar.com, prod
```

```
* Step that takes a table <table:data.csv:filter>
```

Where `filter` can be any column in the csv that specifies the environment string. At runtime only rows matching that filter will be passed to the the step. The user can apply multiple environments while running the spec and the filter will match those environments.

**Comment by onimalarat** [comment]
@zabil 
When using the workaround, will the HTML report for the execution show the failure rows just like usual data driven test (by providing the csv file in the beginning of the spec)?

**Comment by zabil** [comment]
This is a proposal not a workaround. But once implemented it should show the failure rows.

**Comment by zabil** [comment]
You can also use the environment variable `gauge_environment` in your code to filter columns. For example 

```
* Almost all words have vowels
     |Word  |Vowel Count| Environment |
     |------|-----------|-------------|
     |Gauge |3          | prod        |
     |Mingle|2          | test        |
     |Snap  |1          | default     |
```

```
gauge run --env prod
```

```
step("Almost all words have vowels <table>", function(table) {
  table.rows.forEach(function (row) {
    if(row.cells[2] == process.env.gauge_environment) {
      console.log(row.cells[0]);
    }
  });
 });
```

Will only print `Gauge`

You can even mix up and specify multiple environments in a column and use string matching 

```
* Almost all words have vowels
     |Word  |Vowel Count| Environment |
     |------|-----------|--------------|
     |Gauge |3          | prod, default|
     |Mingle|2          | test         |
     |Snap  |1          | default      |
```

```
gauge run specs
```

```
step("Almost all words have vowels <table>", function(table) {
  table.rows.forEach(function (row) {
    if(row.cells[2].contains(process.env.gauge_environment)) {
      console.log(row.cells[0]);
    }
  });
 });
```

Will match `Gauge` and `Snap` as they both contain `default`

Closing this issue as it's better to manage this programmatically using the workarounds mentioned above.

**Comment by nehashri** [comment]
@zabil The workaround mentioned by you will work only for tables within a step. It will not work when a csv datatable is defined in a spec. Eg: (as quoted by @osandadeshan in [first comment](https://github.com/getgauge/gauge/issues/1518#issue-513703584)
```
# Login driven execution

table: /resources/csv/qa_users.csv

## Login scenario
* Login with username <username > and password<password>
```

The table values are passed to the scenario and in turn the steps. 
Gauge will try to spin up as many scenarios as the number of datatable rows.
So the user will not be able to programatically filter based on the datatable rows.

**Comment by pareaadi1987** [comment]
Any update here.
As i am also trying to use JSON for multiple enviorment

**Comment by sriv** [comment]
Not at the moment, this is in the backlog but the team is held up with other things at the moment.

**Comment by zabil** [comment]
Closing this as unfortunately there is no clean and easy way of implementing this feature in Gauge.
