### ISSUE TITLE
Migration from Twist to Gauge leads to @Steps with same name and same number of parameters

### ISSUE THREAD

**Issue by kupna** [getgauge/gauge#152]
When you migrate from Twist to Gauge and you have two methods with same name and same number of parameters this in your scenarios, after migrating to gauge this methods cannot be connected to the correct @Step.

for example:

Twist:
SearchMailMonitoring:
$navigate to mail monitoring all mails
#fill search form "test@test.at"

Gauge:
SearchAddresses.java
@com.thoughtworks.gauge.Step("Fill search form <type>")
	public void fillSearchForm(String type) throws Exception {
SearchAccommodation.java
@com.thoughtworks.gauge.Step("Fill search form <name>")
	public void fillSearchForm(String name)

In Gauge the right method cannot be found because the reference of which file you should call the method is gone. (Before SearchMailMonitoring - After SearchAddresses.java)

**Comment by ApoorvaM** [comment]
Can you please email any of your Twist to Gauge Migration issues to:  twist-migration[at]thoughtworks[dot]com. If you have any issues or have a feature request for Gauge, please raise an issue here at Github.
