### ISSUE TITLE
Logging every successful step?

### ISSUE THREAD

**Issue by emirhangl** [getgauge/gauge#1522]
### Expected behavior
It would be very useful if we could read every step of the scenario as logs after the execution. So that, we could analyze after/before which step scenario got failed without searching through the spec files for the related scenario.

### Actual behavior
After a successful scenario execution, Gauge logs say only success or fail status.

### Gauge version
```
Gauge version: 1.0.4

Plugins
-------
html-report (4.0.8)
java (0.7.2)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)

```

**Comment by nehashri** [comment]
@emirhangl I think you are looking at verbose logging feature of Gauge. 
You can run `gauge run -v` or `gauge run --verbose` to enable verbose logging. You can run `gauge --help` or look at https://manpage.gauge.org/ for a list of flags available.
