### ISSUE TITLE
Find usages of steps would be necessary

### ISSUE THREAD

**Issue by kupna** [getgauge/gauge#153]
It is not possible to find out in which *.spec files or *.cpt files a @Step is used

example:

Which *.spec file or *.cpt file calls

@com.thoughtworks.gauge.Step("Fill search form <name>")
public void fillSearchForm(String name)

**Comment by prateekbaheti** [comment]
This is a duplicate issue of [#5 in the Intellij Gauge plugin](https://github.com/getgauge/Intellij-Plugin/issues/5) repository.

**Comment by prateekbaheti** [comment]
Closing duplicate issue.
 Please track [this original issue](https://github.com/getgauge/Intellij-Plugin/issues/5)
