### ISSUE TITLE
Remote debugging Gauge Java tests

### ISSUE THREAD

**Issue by jphillips-bp3** [getgauge/gauge#1531]
Hi, is there a way if remote debugging Gauge Java tests, i.e. connecting to the Gauge JVM from a remote debugger? Many thanks.

### Gauge version
```
Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
html-report (4.0.8)
java (0.7.2)
js (2.3.5)
screenshot (0.0.1)
```

**Comment by negiDharmendra** [comment]
@jphillips-bp3 [Gauge Vscode](https://github.com/getgauge/gauge-vscode) and [Gauge Intellij](https://github.com/getgauge/Intellij-Plugin) plugins has good support for debugging. If you you are looking for some thing else, please tell us your use case.

**Comment by negiDharmendra** [comment]
@jphillips-bp3 You can set `GAUGE_DEBUG_OPTS` to remotely debug the Gauge JVM

**Example:** `GAUGE_DEBUG_OPTS=<port-number>  gauge run`

**Comment by jphillips-bp3** [comment]
> @jphillips-bp3 You can set `GAUGE_DEBUG_OPTS` to remotely debug the Gauge JVM
> 
> **Example:** `GAUGE_DEBUG_OPTS=<port-number> gauge run`

Thanks @negiDharmendra , I will give it a go in a few days.
