### ISSUE TITLE
How to Skipped some test scenarios when first scenario is failing?

### ISSUE THREAD

**Issue by iskoc9002** [getgauge/gauge#1534]
Hi everyone,
I've a gauge maven project. I've been lot's of test cases and test specs. And I'm using to DataStore at the same spec.

- First case create meeting and storing meetingNumber.
- Second case is make someting using stored meetingNumber.
- Thirth case is deleting meeting using stored meetingNumber.

I want to skip 2nd and 3rd scenarios, when 1st scenario is failed. Also, I want to set scenario status to SKIPPED.

How can I do it. Can anyone help me please?

>gauge -v
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
html-report (4.0.8)
java (0.7.3)
screenshot (0.0.1)

**Comment by zabil** [comment]
This is not possible as scenarios cannot be linked together or run in a specific order.
