### ISSUE TITLE
Failed to start gauge API: fork/exec index.bat: invalid argument

### ISSUE THREAD

**Issue by pavanprakash** [getgauge/gauge#1535]
Hi,

I am trying gauge for the first time, have written spec file & added corresponding step definitions.I am getting an error when i run the specs. Error i get is -  

[Gauge]
Failed to start gauge API: fork/exec index.bat: invalid argument

FYI - using Gauge version: 1.0.6
Your Environment Information -----------
	windows, 1.0.6, 2bc49db
	csharp (0.10.6), html-report (4.0.8), js (2.3.6), screenshot (0.0.1), spectacle (0.1.3)

I am using js template and windows 7 Enterprise. Appreciate if you can throw some light on the issue..

Thanks
Pavan

**Comment by delmaamoun** [comment]
I saw the same issue with windows 7. I think it was mentioned somewhere than windows 8 isn't supported and so I assumed windows 7 isn't supported either (it used to work in the past though, so I don't know)

**Comment by Debashis9012** [comment]
We are closing this issue as we do not support windows 7/8. 
If you are facing the same problem in windows 10 or onwards please feel free to reopen.
