### ISSUE TITLE
All Python examples are broken

### ISSUE THREAD

**Issue by DvagNic** [getgauge/gauge#1537]
### Expected behavior
Visit https://getgauge-examples.github.io, find a working Python example.

### Actual behavior

- https://github.com/getgauge-examples/python-selenium (SUT download link broken)
- https://github.com/gemunulk/gauge-python-selenium-demo (SUT download location domain replaced/expired)
- https://github.com/kashishm/gauge-example-python (SUT download link broken)

**Comment by Apoorva-GA** [comment]
@DvagNic Thanks for bringing this up and sorry for the inconvenience.

We have removed the artifact from bintray. But you can still download the artifact from [github release](https://github.com/getgauge-examples/activeadmin-demo/releases/tag/untagged-f0befd5494efa4baabd2). Hope this helps.

**Comment by zabil** [comment]
Changed the link https://github.com/getgauge-examples/python-selenium 
For the other repositories it's best to raise an issue there and inform the maintainers.
