### ISSUE TITLE
Migration from Twist to Gauge sometimes adds or subtracts whitespace in steps

### ISSUE THREAD

**Issue by Navisayslisten** [getgauge/gauge#154]
After migrating a Twist project to Gauge using the automated plugin, a lot of steps in spec files had an extra space or were missing one.

For example:
Open the context "context1"FAST Method

Where in the original Twist project, the steps are properly spaced out.

**Comment by ApoorvaM** [comment]
Can you please email any of your Twist to Gauge Migration issues to: twist-migration[at]thoughtworks[dot]com. If you have any issues or have a feature request for Gauge, please raise an issue here at Github.
