### ISSUE TITLE
Cannot launches tests from command line Failed to start gauge API: Runner with pid 15884 quit unexpectedly

### ISSUE THREAD

**Issue by brobles82** [getgauge/gauge#1540]
### Expected behavior
On use `gauge run specs` on the command line the test should be launched

### Actual behavior
I can run the tests from IntelliJ but not from command line, I get this error 
`[Gauge]
Failed to start gauge API: Runner with pid 15884 quit unexpectedly(exit status 1).` 

### Steps to reproduce
0. Use java repository
1. Use `gauge run specs`

The interesting part is I can run the tests with IntelliJ but not from command line tool 

```
07-12-2019 01:03:43.343 [Gauge] [DEBUG] Runner connection error: Runner with pid 15884 quit unexpectedly(exit status 1).
07-12-2019 01:03:43.343 [Gauge] [DEBUG] Error while killing runner: os: process already finished
07-12-2019 01:03:43.343 [Gauge] [CRITICAL] Failed to start gauge API: Runner with pid 15884 quit unexpectedly(exit status 1).
```

Looks like the api needs a env variable called GAUGE_API_PORT that I can not find what I have to set

Also in the console there are some import errors that don't know why don't affect IntelliJ, the import is correct done but on command line this appears

```
rc/test/java/utils/driver/Driver.java:7: error: package org.openqa.selenium does not exist
import org.openqa.selenium.WebDriver;
^
src/test/java/utils/driver/Driver.java:12: error: cannot find symbol
public static WebDriver webDriver;
^
symbol:   class WebDriver
location: class Driver
src/test/java/utils/driver/DriverFactory.java:3: error: package io.github.bonigarcia.wdm does not exist
import io.github.bonigarcia.wdm.WebDriverManager;
```

### Gauge version
```
Gauge version: 1.0.6

Plugins
-------
html-report (4.0.8)
java (0.7.3)
screenshot (0.0.1)

```

**Comment by brobles82** [comment]
O just found that in java you have to use the mvn option, if not don't works

**Comment by arunts1982** [comment]
Disconnected from the target VM, address: 'localhost:62861', transport: 'socket' getting error while running template-java-maven-selenium using intellij IDEA

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>AutoMTH</groupId>
    <artifactId>AutoMTH</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <name>AutoMTH</name>
    <url>http://maven.apache.org</url>

    <dependencies>
        <dependency>
                <groupId>org.seleniumhq.selenium</groupId>
                <artifactId>selenium-java</artifactId>
                <version>3.14.0</version>

            </dependency>
        
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-remote-driver</artifactId>
            <version>3.14.0</version>
        </dependency>
        
        

        <dependency>
            <groupId>com.thoughtworks.gauge</groupId>
            <artifactId>gauge-java</artifactId>
            <version>0.7.3</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.thoughtworks.gauge.maven</groupId>
                <artifactId>gauge-maven-plugin</artifactId>
                <version>1.4.0</version>
                <executions>
                    <execution>
                        <id>validate</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>validate</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>execute</id>
                        <phase>test</phase>
                        <goals><goal>execute</goal></goals>
                        <configuration>
                            <specsDir>specs</specsDir>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>

Not able run maven seleium gauge project in intellij IDEA

**Comment by zabil** [comment]
Try changing 
```
    <dependency>
        <groupId>com.thoughtworks.gauge</groupId>
        <artifactId>gauge-java</artifactId>
        <version>0.7.3</version>
        <scope>test</scope>
    </dependency>
```

to 

```
    <dependency>
        <groupId>com.thoughtworks.gauge</groupId>
        <artifactId>gauge-java</artifactId>
        <version>0.7.7</version>
        <scope>test</scope>
    </dependency>
```
