### ISSUE TITLE
Messages to the console should be printed via logger package

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#1542]
Messages to the console should be printed via logger package

The logger package manages the output to be printed correctly. It prints in json format if machine readable flag is provided. It decides when it is safe to print to the console ( if gauge is started with lsp, it will not print). So it is best to let it handle all prints to process standard  output

There are many places where we directly print to the console in Gauge. These should be printed via the logger.

**Comment by s-m-sufyian** [comment]
Any one working on this issue ?

**Comment by zabil** [comment]
Not at the moment.
