### ISSUE TITLE
Update of plugins stopped working

### ISSUE THREAD

**Issue by j-morsum** [getgauge/gauge#1546]
### Expected behavior
The plugins update without any problem.

### Actual behavior
The update of plugins stopped working recently (maybe related with the nightlies removal?). Tried to update on two different machines (Windows and Linux) on two different locations and failed with the information:

```
>gauge update -a
Failed to update plugin 'html-report'.
Reason: Invalid plugin. Could not download html-report-install.json file.
Failed to update plugin 'java'.
Reason: Invalid plugin. Could not download java-install.json file.
Failed to update plugin 'json-report'.
Reason: Invalid plugin. Could not download json-report-install.json file.
Failed to update plugin 'screenshot'.
Reason: Invalid plugin. Could not download screenshot-install.json file.
Failed to update plugin 'spectacle'.
Reason: Invalid plugin. Could not download spectacle-install.json file.
Failed to update plugin 'xml-report'.
Reason: Invalid plugin. Could not download xml-report-install.json file.
Error ----------------------------------

[Gauge]
Failed to update 'html-report, java, json-report, screenshot, spectacle, xml-report' plugins.

Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://gitter.im/getgauge/chat
```

### Steps to reproduce
1. Open a command line/terminal window; 
2. Type the update command `gauge update -a`.

### Gauge version
```
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
html-report (4.0.8)
java (0.7.3)
json-report (0.3.2)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.2)
```

**Comment by sriv** [comment]
What does `gauge config gauge_repository_url` yield? 

Your guess might be right, if your machines are pointing to the nightlies URL then it will not work. We now recommend that you either use the release channel or build from source.

**Comment by j-morsum** [comment]
> What does `gauge config gauge_repository_url` yield?
> 
> Your guess might be right, if your machines are pointing to the nightlies URL then it will not work. We now recommend that you either use the release channel or build from source.

It is pointing to: `https://downloads.getgauge.io/plugin`

**Comment by BugDiver** [comment]
@j-morsum I figured out the issue. Your config is pointing to an old URL. (It's kept for backward compatibility, but I guess the SSL cert for the url is expired.)

Can you please update it `https://downloads.gauge.org/plugin`? To do so run `gauge config gauge_repository_url https://downloads.gauge.org/plugin`

Also you should change all the reference of `getgauge.io` to `gauge.org`.
* To check all the config value run `gauge config --list`

You can also edit all properties directly in the config file. The get the location for the properties file refer https://docs.gauge.org/configuration.html?os=windows&language=java&ide=vscode#global-configuration-of-gauge-gauge-properties

**Comment by j-morsum** [comment]
> @j-morsum I figured out the issue. Your config is pointing to an old URL. (It's kept for backward compatibility, but I guess the SSL cert for the url is expired.)
> 
> Can you please update it `https://downloads.gauge.org/plugin`? To do so run `gauge config gauge_repository_url https://downloads.gauge.org/plugin`
> 
> Also you should change all the reference of `getgauge.io` to `gauge.org`.
> 
> * To check all the config value run `gauge config --list`
> 
> You can also edit all properties directly in the config file. The get the location for the properties file refer https://docs.gauge.org/configuration.html?os=windows&language=java&ide=vscode#global-configuration-of-gauge-gauge-properties

Indeed that was the problem and changing the repository urls solved the issue. Probably is worth the time adding a small note to the documentation about the need to update the urls (`getgauge.io` to `gauge.org`) for older installations.
