### ISSUE TITLE
Json reports are not consistently same

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/gauge#1547]
I opened a ticket for Json plugin and below is the link for the same. Its been 6 days and nobody responded to me so thought of opening a ticket here to see if somebody can take a look at the issue.
https://github.com/getgauge-contrib/json-report/issues/14

Problem Statement --> Json plugin, for the same test, sometimes shows steps details and sometime shows details only at spec level.

I ran my test twice and both the times the report is different. In one report i see that all the step details are present but the second report does not has any step detail. The behavior is inconsistent.

It is happening for both 0.3.0 and 0.3.2

Attached are the files for your reference.
[Json.Results.zip](https://github.com/getgauge/gauge/files/3995771/Json.Results.zip)

### Expected behavior
The Json structure should be same

### Actual behavior
The Json structure is not same

### Gauge version
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
dotnet (0.1.2.nightly-2019-02-14)
html-report (4.0.7)
json-report (0.3.0)
screenshot (0.0.1)
xml-report (0.2.1)

**Comment by negiDharmendra** [comment]
@manavghaigithub I have tried with the versions you have mentioned as well as with the latest Gauge and other plugins installed from the source. Every things is working fine.

Is it possible for you to share a project to relicate this issue and provide a fix.
**Note:** Please upgrade the Gauge and Gauge-dotnet to the latest version.

**Comment by sriv** [comment]
@manavghaigithub - were you able to sort this out?

**Comment by negiDharmendra** [comment]
@manavghaigithub Please feel free to reopen this issue if you are still facing it.

**Comment by manavghaigithub** [comment]
Hi Dharmendra - I am still facing this issue but it is not bothering as such. Last time I was asked to provide the project which I cannot because I work out of customer location.


Thanks,
Manav Ghai

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
