### ISSUE TITLE
Running multi tags with Gradle runner not working

### ISSUE THREAD

**Issue by lirany1** [getgauge/gauge#1549]
### Expected behavior
should ran each spec
### Actual behavior
not running at all

### Steps to reproduce
1.
i have this gauge task on gradle
```
task gaugeTask(type: GaugeTask) {
    doFirst {
        gauge {
            tags = "$gaugeTags"
            specsDir = "specs"
            inParallel = true
            nodes = 4
            env = "$gaugeEnv"
            additionalFlags = "--verbose --max-retries-count=2 --retry-only=should-retry"
        }
    }
}
```
2. than to run this i ran
`gradle --offline -q -PgaugeTags=$gaugeTag -PgaugeEnv=ci gaugeTask
`
through jenkins.

3. gaugeTag="Spec1 spec2 spec3"
where:
spec1 tags = openTable,ui,E2E
spec2 tags = ui,E2E,searcher
spec3 tags = login,ui,E2E

### Gauge version
```
gauge -v
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
html-report (4.0.8)
java (0.7.3)
screenshot (0.0.1)
```

**Comment by sriv** [comment]
in order to specify more than one tags, you need to use a [tag expression](https://docs.gauge.org/execution.html?os=windows&language=javascript&ide=vscode#tag-expressions).

In this case, please try something like `gaugeTag="Spec1 | spec2 | spec3"`

**Comment by lirany1** [comment]
Is the a way to run the tags in order that i want to
where
gaugeTag="Spec1 spec2 spec3"
where:
spec1 tags = login
spec2 tags = openTable
spec3 tags = searcher


so Spec1 will run first then Spec2 run and then Spec3.

**Comment by sriv** [comment]
No, the tags do not have such precedence. Gauge will take all the tags, and the expressions, evaluate it and decide the order.

**Comment by lirany1** [comment]
@sriv thanks,Bt default is it sort by alphabetical order?how it decide the order if not?

**Comment by sriv** [comment]
The tags order do not matter.

The specs order is controlled only if the `--sort` flag is passed or if the input to `gauge run` is an explicit list of specs/folder. ex. if you specified `gauge run specs/example3.spec specs/example1.spec` then gauge should run `example3.spec` before `example1.spec`

By default gauge will take the order that the syscall determines when enumerating the file system, i.e. gauge does not do an explicit sorting.

**Comment by lirany1** [comment]
Cool thanks @sriv
