### ISSUE TITLE
[Feature Request] Ability to run Selenium tests on a Selenium Grid instead of locally

### ISSUE THREAD

**Issue by ghost** [getgauge/gauge#155]
Gauge currently runs tests on my local machine. I'd like to ability to run tests remotely either on a separate Selenium node or hub for several reasons:

 - Keep resources on my machine free so that I may continue testing manually
 - Make more efficient use of parallel test execution
 - Compatibility/Version testing
 - Keep tests in a controlled environment that doesn't have my local test environment changes

**Comment by mahendrakariya** [comment]
It's possible to run Gauge tests on selenium grid. Here's an example project. https://github.com/apoorvam/gaugeGrid
