### ISSUE TITLE
Unable to view api logs in report

### ISSUE THREAD

**Issue by kushalpal17** [getgauge/gauge#1550]
I am doing rest api testing using rest assured with gauge framework. I am not able to see http api request and response in repost.html

**Comment by BugDiver** [comment]
@kushalpal17 I might did not understand your question properly. I'm Assuming you are talking about the report generated via html-report plugin.
The report contains details about the spec/scenario/step etc. If you need any extra information to go in the report you can use gauge's `custom_message` feature. Read more https://docs.gauge.org/writing-specifications.html?os=macos&language=java&ide=intellij#custom-messages-in-reports

We might be able to help you better if you could give us a sample of actual and expected reports.

**Comment by kushalpal17** [comment]
ValidatableResponse vResponse = given().contentType(ContentType.URLENC)
                .formParams(body)
                .config(RestAssured.config().encoderConfig(EncoderConfig.encoderConfig()
                        .appendDefaultContentCharsetToContentTypeIfUndefined(false)))
                .log()
                .all()
                .when()
                .post("myURL")
                .then()
                .log()
                .all();

Here I am using log() but its printed on console not in report.

**Comment by BugDiver** [comment]
@kushalpal17 As I told html-report can not get these logs, since the `log` method prints it to `stdout`. Which is not forwarded to Html-report.

If there is a way you can get the logs in variable then you will be able to send to it to html-report.
Using custom message feature
Ex: 

```java
String log = DO_SOMETHING_TO_GET_THE_LOGS;
Gauge.writeMessage("Log for the respinse %s", log);
```

**Comment by BugDiver** [comment]
On a quick google search I found this SO thread about storing logs to a variable
https://stackoverflow.com/questions/52490508/how-to-save-response-log-in-variable-using-rest-assured

**Comment by kushalpal17** [comment]
Its very straight forword, If my any test is failing in that case I want to log it and want to view it in report. Is this possible in your framework?

**Comment by BugDiver** [comment]
@kushalpal17 There is no direct way to achieve it. But I guess there are workaround which can be used to get what you want.

As I explained you have to extract the log messages from the response and then use the `Gauge.writeMessage` to send any custom/extra data to the html-report plugin.

Since you want to it only on failure you might have to add a check for the failure.

Here is a sample which I'm putting together to make it more clear
```java
Response response = RestAssured.given()
    .headers("data",crypto)
    .when()
    .post("//auth.svc/auth")
    .then()
    .contentType(ContentType.JSON)
    .extract()
    .response();
int statusCode = response.getStatusCode();
// you can add check for other status code as well
if (statusCode < 200 || statusCode >= 300) { 
    Gauge.writeMessage(response.asString())
}
```

**Comment by kushalpal17** [comment]
I think it is basic need and there should be a way in your framework to configure it. We are doing api test and we can't log it in report its very pathetic for me.

**Comment by sriv** [comment]
> I think it is basic need

I disagree. Gauge is a tool designed for Acceptance testing, and concerns itself with User Journeys more than the mechanism used under the hood. API logs are low level details that normally do not concern an end user.

> we can't log it in report its very pathetic for me.

@BugDiver just posted a potential workaround to get report data into the report using `Gauge.writeMessage`. Feel free to discuss it's shortcomings.

I guess you are entitled to your opinion, but calling a tool 'pathetic' isn't particularly helpful.

**Comment by kushalpal17** [comment]
> > I think it is basic need
> 
> I disagree. Gauge is a tool designed for Acceptance testing, and concerns itself with User Journeys more than the mechanism used under the hood. API logs are low level details that normally do not concern an end user.
> 
> > we can't log it in report its very pathetic for me.
> 
> @BugDiver just posted a potential workaround to get custom data into the html-report using `Gauge.writeMessage`. Feel free to discuss it's shortcomings.
> 
> I guess you are entitled to your opinion, but calling a tool 'pathetic' isn't particularly helpful.

I think I have used wrong word but my intension was right.
