### ISSUE TITLE
issue in html report and Gauge.writeMessage() in java language

### ISSUE THREAD

**Issue by kushalpal17** [getgauge/gauge#1551]
### Expected behavior
It should print same string what I am passing in Gauge.writeMessage()

### Actual behavior
I am passing below string in Gauge.writeMessage() but in html report why its showing <br/>
curl 'https://url' \
--header 'Accept: */*' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Host: auth.staging.com' \
--header 'Connection: Keep-Alive' \
--header 'User-Agent: Apache-HttpClient/4.5.3 (Java/13.0.1)' \
--data-binary 'password=password&username=username' \
--compressed \
--insecure \
--verbose

curl ‘https://url' <br/> –header ‘Content-Type: application/x-www-form-urlencoded’ <br/> –header ‘Host: auth.staging..com’ <br/> –header ‘Connection: Keep-Alive’ <br/> –header ‘User-Agent: Apache-HttpClient/4.5.3 (Java/13.0.1)’ <br/> –data-binary ‘password=password&username=username’ <br/> –compressed <br/> –insecure <br/> –verbose

### Gauge version
0.6.9

**Comment by negiDharmendra** [comment]
@kushalpal17 Can you please share the code snippet. 
Also please share the output of `gauge -v` command with us.

**Comment by kushalpal17** [comment]
> gauge -v

Gauge version: 1.0.6

Plugins
-------
html-report (4.0.8)
java (0.7.3)
screenshot (0.0.1)
xml-report (0.2.2)

Gauge.writeMessage(message.toString());

**Comment by negiDharmendra** [comment]
@kushalpal17  This is how I am using `Gauge.writeMessage()`
```
         StringBuilder message = new StringBuilder()
                .append("curl 'https://url'")
                .append("\n--header 'Accept: /'")
                .append("\n--header 'Content-Type: application/x-www-form-urlencoded'")
                .append("\n--header 'Host: auth.staging.com'")
                .append("\n--header 'Connection: Keep-Alive'")
                .append("\n--header 'User-Agent: Apache-HttpClient/4.5.3 (Java/13.0.1)'")
                .append("\n--data-binary 'password=password&username=username'")
                .append("\n--compressed")
                .append("\n--insecure")
                .append("\n--verbose");
        Gauge.writeMessage(message.toString());
```
I could see that the correct message in the html-report.
<img width="1452" alt="Screenshot 2020-01-16 at 1 31 06 PM" src="https://user-images.githubusercontent.com/15261737/72504779-83f55580-3864-11ea-9c2f-2abdb6c53a4f.png">

**Comment by sriv** [comment]
Closing this. Feel free to comment/reopen if issue still persists.
