### ISSUE TITLE
Unable to execute tests on macOS with Jenkins (safaridriver crashes)

### ISSUE THREAD

**Issue by DvagNic** [getgauge/gauge#1553]
### Expected behavior
Safari pops up and executes my tests.

### Actual behavior
If I execute the tests locally, Safari pops up and everything works fine. If I run the tests through Jenkins while having the Mac configured as an agent, they fail with the following error:

```
Python: 3.7.5
  Error Message: Message: Service /usr/bin/safaridriver unexpectedly exited. Status code was: 1
  
  Stacktrace: 
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/getgauge/executor.py", line 31, in execute_method
      step.impl(*params)
    File "/Users/jenkinsslave/jenkins_home/workspace/_collect_feature_gauge-mac-debug/tests/step_impl/utils/driver.py", line 38, in init
      Driver.driver = webdriver.Safari(executable_path=driver_executable_path)
    File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/safari/webdriver.py", line 57, in __init__
      self.service.start()
    File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 98, in start
      self.assert_process_still_running()
    File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
      % (self.path, return_code)
  selenium.common.exceptions.WebDriverException: Message: Service /usr/bin/safaridriver unexpectedly exited. Status code was: 1
```

I read that this issue might be related to the way the agent connects to the master. I tried both via SSH and Java direct connection.
All other "webdrivers" work fine (Chrome and Firefox), only Safari fails.

In the console app I see the same error message:
```
XPC connection to com.apple.WebDriver.HTTPService was interrupted, the server probably exited or crashed.
```

I also tried to start the safaridriver process manually with:
```
# safaridriver -p 0
Attempting to establish XPC connection to com.apple.WebDriver.HTTPService.
Configuring server.
Server started.
```
macOS 10.13.6, Mac Pro

### Steps to reproduce
1. Setup Mac as Jenkins agent (connect agent through Java *not* SSH)
2. Start tests in Jenkins job with `gauge run --env safari specs`

### Gauge version
```
Gauge version: 1.0.6
Commit Hash: 2bc49db
```

**Comment by sriv** [comment]
I suspect this might be specific to webdriver. Gauge does not do anything with regards to webdriver.

**Comment by sriv** [comment]
Closing this as error seems to come from component outside of Gauge.

Please feel free to comment/discuss if Gauge can do something here.
