### ISSUE TITLE
Requirement: Test Report Aggregator

### ISSUE THREAD

**Issue by Vishnu1067** [getgauge/gauge#1554]
**Requirement**
Would like to have Test Report Aggregator (html / xml) to show overall testing statistics.

**Example:** 

https://github.com/jenkinsci/test-results-aggregator-plugin
Above plugin does support only for JUnit and TestNG reports.

**Why this feature?**

We have 50+ test jobs in jenkins and each producing html / xml reports individually. If we have feasible to display overall summary report where we can see  PASS / FAIL / SKIPPED status in each jobs and how much execution time and overall execution time, it is very convenient for us to see all results in one place instead of going to each job to check results.

**Features required**

Need groovy script for pipeline to get overall summary report.

1. Can add groups / teams - where we can get summary for each team results + overall summary for entire application.

2. Job Name, Health checks, Status, Total Tests, PASS, FAIL, SKIPPED, Test Pass Percentage, Duration and Last Run

![Screen Shot 2563-01-07 at 2 57 02 PM](https://user-images.githubusercontent.com/13374564/71878365-0c397380-315e-11ea-9941-db03ff42f123.png)

**Comment by sriv** [comment]
IMO, this probably is something that could be raised with the plugin you referred to. Gauge's reporting concerns with a single run, and any aggregation/trend analysis could be delegated to something higher (ex the CI/CD tool)

**Comment by Vishnu1067** [comment]
@sriv I have just showed the example which supports for TestNG, JUnit. Since gauge is having their reporting tool, can we have a aggregation? It will be very useful to get all reports in one place.

**Comment by sriv** [comment]
@Vishnu1067 In this comparison, Gauge falls into the same bucket as TestNG or JUnit. I meant to state that the plugin that aggregates consumes the test runner's output and builds the metrics.

Of course, you could always use Gauge's xml-report which complies to the JUnit schema, and pass that to the plugin. Or there could be a plugin that writes the data into some store.

> Since gauge is having their reporting tool, can we have a aggregation?

You are correct in stating Gauge has reporting capability, but please note that the reports are for a single run. Gauge does not possess any reporting capability across multiple runs, and that is where I feel would be better off using a tool that does this better.

Would you mind trying out the xml-report plugin? the output xml could be fed into the aggregator plugin and perhaps that could be what you are looking for?

**Comment by Vishnu1067** [comment]
@sriv thanks for prompt response. I have tried with the above plugin and i couldn't get the pass / fail / skipped and total number of testcases. Let me dig into it more. Thanks a lot.

**Comment by zabil** [comment]
Closing this for now as it's best for an external tool to handle aggregation using gauge run output.
