### ISSUE TITLE
JDK 1.7.0_71 Windows 64-bit: Failed to start javac.exe

### ISSUE THREAD

**Issue by ghost** [getgauge/gauge#156]
Gauge 64-bit Windows won't run my tests and gives the error: : Failed to start javac.exe: The filename or extension is too long.

These tests do work on 64-bit Linux.

java version: 1.7.0_71

**Comment by prateekbaheti** [comment]
What is the approx number of java files in the src directory ? 
This seems to be occurring when gauge-java tries run the javac command for compiling. It exceeds the length of command allowed on windows (https://support.microsoft.com/en-us/kb/830473). 
This is because it builds the javac command with names of all java files in the project.

Do the specs run fine on Intellij idea ?

**Comment by prateekbaheti** [comment]
Can you try the same with the [0.1.0 release](https://github.com/getgauge/gauge-java/releases) of the gauge-java plugin. There are improvements in the way the list of files are added to the javac command while building the project.

**Comment by Navisayslisten** [comment]
Oh there are a ton of java files. We converted a rather large project to see if Gauge could handle it better.

IntelliJ idea is where I am running these tests in both Linux and Windows. I have also tried command line execution, which failed with the same error for Windows.

I will attempt the 0.1.0 release of the gauge-java plugin and see if that helps.

**Comment by prateekbaheti** [comment]
@Navisayslisten  Did the gauge-java plugin update resolve the issue ?

**Comment by Navisayslisten** [comment]
Issue is unresolved. Moved on to something different in the meantime. Sorry for not updating the issue. We ended up not using Gauge as a result of this bug.

**Comment by deepthigc** [comment]
@Navisayslisten We're very sorry to hear this. We will be sure to fix this if it still exists. Thank for reporting this and sending us an update. We will send you an update as soon as this is fixed, and hopefully you will be able to use Gauge later.

**Comment by mahendrakariya** [comment]
This issue is not reproducible anymore. Tried with 
```
Gauge version: 0.3.1

Plugins
-------
html-report (2.0.0)
java (0.3.4)
ruby (0.1.0)
xml-report (0.1.1)
```
