### ISSUE TITLE
How to do cross browser testing in gauge ? How to run test case in in different browsers?

### ISSUE THREAD

**Issue by advait012** [getgauge/gauge#1564]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Gauge version
```
Run gauge -v on your system and paste the results here.
```

**Comment by ajoecker** [comment]
better to ask here: https://spectrum.chat/gauge/general?tab=posts
