### ISSUE TITLE
allow_scenario_datatable does not work

### ISSUE THREAD

**Issue by jenniferz79** [getgauge/gauge#1565]
### Expected behavior
Set allow_scenario_datatable should work as described in gauge docs:
https://docs.gauge.org/writing-specifications.html?os=windows&language=csharp&ide=visualstudio

```
Gauge 1.0.3 adds an experimental feature to provide a table at scenario level. Gauge will iterate over the table and run that particular scenario against each row. Set allow_scenario_datatable variable to true in /env/default/default.properties to enable this feature.
```

### Actual behavior
* run command: 'gauge run specs', it throw error as below, and test failed.
```
[ParseError] Example.spec:6 Scenario should have atleast one step => ''
```
* run command specify the spec and line number: 'gauge run specs/Example:6', it still throw error as above, but test executed and passed as expected.

### Steps to reproduce
1. Put data table inside scenario.
2. Run command: gauge run specs
3. Run is failed with below error:
[ParseError] Example.spec:6 Scenario should have atleast one step => ''

### Gauge version
```
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
csharp (0.10.6)
html-report (4.0.8)
reportportal (1.0.1)
screenshot (0.0.1)
xml-report (0.2.2)
```

**Comment by BugDiver** [comment]
@jenniferz79 The error show that there is a parsing error in your specification, could you please provide a sample code snippet of you scenario which is using the table?

**Comment by jenniferz79** [comment]
The spec file is as below, thanks~
```
CheckPaymentStatement
=====================
Created by pengyi.l on 12/19/2019 3:21:11 PM.


Check Payment Statement with Table
----------------
table:TestData/CheckPaymentStatementData.csv
* Get token with endpoint "Identity-ninjago/connect/token"
* Create request with endpoint "DirectEntry/api/v1.0/AccountTemplates"
* Read Default content <file: TestData/DefaultPaymentStructureData.json>
* Update "Term" to <Term>
* Update "TermType" to <TermType>
* Update "isTerm" to <IsTerm>
* Update "TotalAmount" to <TotalAmount>
* Update "OverrideEstFee" to <OverrideEstFee>
* Update "IsCustomFrequency" to <IsCustomFrequency>
* Update "Installment" to <Installment>
* Update "AdditionalOneOffPayment" to <AdditionalOneOffPayment>
* Update "JoiningFeeIsFirstInstalment" to <JoiningFeeIsFirstInstalment>
* Update "IsProrata" to <IsProrata>
* Send request in method "Post"
* Verify the response as following
    |keyName     |expectedResult|
    |------------|--------------|
    |successful  |True          |
    |errorMessage|[]            |
```

**Comment by BugDiver** [comment]
@jenniferz79 Thanks for giving the sample code, I see that you are using an external table (CSV file) at scenario level.
Since the scenario data table is an experimental feature we do not have support for external tables as of now. Only inline tables at scenario level are supported.

**Comment by BugDiver** [comment]
I have raised a feature request for the same.
We will discuss an try to prioritize it. Follow https://github.com/getgauge/gauge/issues/1569 to get updates for it.
