### ISSUE TITLE
Gauge Only Take Desktop Screenshot on Appium 

### ISSUE THREAD

**Issue by silashayri** [getgauge/gauge#1566]
### Description
The Gauge.captureScreenshot(); command just take the current pc desktop screenshot but My project is using for appium android and I want to take the phone screenshot.

### Steps to reproduce
1.Run the project
2.Take Screenshot on phone using Gauge.captureScreenshot();

### Information that will help us debug

Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
flash (0.0.1)
html-report (4.0.8)
java (0.7.3)
json-report (0.3.2)
report-seed (0.0.1)
screenshot (0.0.1)
xml-report (0.2.2)

* Win 10

**Comment by zabil** [comment]
Please use the custom screenshots feature to use appiums api to return custom screenshots.

https://docs.gauge.org/writing-specifications.html#taking-custom-screenshots

**Comment by silashayri** [comment]
Thanks, it works 👍
