### ISSUE TITLE
Exception occurs when static values are passed to a concept called from another concept

### ISSUE THREAD

**Issue by prateekbaheti** [getgauge/gauge#157]
Ex:
For a Concept defined
````
# My concept with <a> and <b>
* A step <a> and <b>
* My nested concept <a> and "foo"
````
Nested Concept Definition
````
# My nested concept <abc> and <def>
* Step inside nested concept <abc> <def>
````
On calling the step - ```* My concept with "foo" and "bar"```

The Exception thrown:
````
panic: Accessing an invalid parameter (12)

goroutine 1 [running]:
main.(*argLookup).getArg(0xc20813aac8, 0xc20802ad88, 0x2, 0x881000)
	/private/tmp/gauge20150525-42544-l3tcxr/gauge-0.1.4/specification.go:830 +0x1b2
main.(*step).getArg(0xc20813aa80, 0xc20802ad88, 0x2, 0xc208010540)
	/private/tmp/gauge20150525-42544-l3tcxr/gauge-0.1.4/specification.go:94 +0x56
main.(*step).getArg(0xc20813ab60, 0xc20802aea0, 0x3, 0x7)
	/private/tmp/gauge20150525-42544-l3tcxr/gauge-0.1.4/specification.go:96 +0xba
main.(*paramResolver).getResolvedParams(0xc208083360, 0xc208054380, 0xc20813ab60, 0xc20812f200, 0x0, 0x0, 0x0)
	/private/tmp/gauge20150525-42544-l3tcxr/gauge-0.1.4/resolver.go:57 +0x478
main.(*specExecutor).resolveToProtoConceptItem(0xc20812cc00, 0x3, 0xc20801f800, 0x11, 0xc20801ea82, 0x13, 0xc20802e1f0, 0x1, 0x1, 0x1, ...)
	/private/tmp/gauge20150525-42544-l3tcxr/gauge-0.1.4/specExecutor.go:271 +0x33c
main.(*specExecutor).resolveToProtoConceptItem(0xc20812cc00, 0x1, 0xc20801f080, 0x19, 0xc20801ea02, 0x1b, 0xc20808cf60, 0x2, 0x2, 0x1, ...)
	/private/tmp/gauge20150525-42544-l3tcxr/gauge-0.1.4/specExecutor.go:269 +0x20e
main.(*specExecutor).resolveToProtoItem(0xc20812cc00, 0x893888, 0xc2080549a0, 0x2)
	/private/tmp/gauge20150525-42544-l3tcxr/gauge-0.1.4/specExecutor.go:238 +0xd6
main.(*specExecutor).resolveItems(0xc20812cc00, 0xc20806e400, 0x6, 0x8, 0x0, 0x0, 0x0)
	/private/tmp/gauge20150525-42544-l3tcxr/gauge-0.1.4/specExecutor.go:217 +0x121
main.(*specExecutor).addAllItemsForScenarioExecution(0xc20812cc00, 0xc20805cc00, 0xc20802e3b8)
	/private/tmp/gauge20150525-42544-l3tcxr/gauge-0.1.4/specExecutor.go:187 +0x209
main.(*specExecutor).executeScenario(0xc20812cc00, 0xc20805cc00, 0x0)
	/private/tmp/gauge20150525-42544-l3tcxr/gauge-0.1.4/specExecutor.go:167 +0x433
main.(*specExecutor).executeScenarios(0xc20812cc00, 0x0, 0x0, 0x0)
	/private/tmp/gauge20150525-42544-l3tcxr/gauge-0.1.4/specExecutor.go:157 +0xf7
main.(*specExecutor).execute(0xc20812cc00, 0xc208084760)
	/private/tmp/gauge20150525-42544-l3tcxr/gauge-0.1.4/specExecutor.go:103 +0x9e1
main.(*simpleExecution).start(0xc2080898b0, 0xc20802e230)
	/private/tmp/gauge20150525-42544-l3tcxr/gauge-0.1.4/execution.go:114 +0x581
main.executeSpecs(0x529800)
	/private/tmp/gauge20150525-42544-l3tcxr/gauge-0.1.4/gauge.go:274 +0x650
main.main()
	/private/tmp/gauge20150525-42544-l3tcxr/gauge-0.1.4/gauge.go:114 +0x3f4
````
Gauge version
````
~ gauge -v
Gauge version: 0.1.4

Plugins
-------
java (0.0.8)
xml-report (0.0.2)
html-report (1.0.3)
````

**Comment by kupna** [comment]
I have now installed gauge 0.1.5 but the error is still here:

{code}
"C:\Program Files\Gauge\bin\gauge.exe" --simple-console "C:/projects/engage/trunk/engage.acceptance.gauge.new1/specs/APP01 Application Permissions.spec"
APP01 Application Permissions
=============================
* Login as superadmin - setup
* Change function "APP_OTHER_WITHOUT_PERMISSION" for authorization group "PEREW" to "aktiviert" - setup
* Renew login as superadmin - setup

APP01 Application Permissions
-----------------------------
panic: Accessing an invalid parameter (Max)

goroutine 1 [running]:
main.(*argLookup).getArg(0x1310bc24, 0x126dfcd0, 0x3, 0x12702720)
	/Applications/Go Agent.app/pipelines/Packaging/specification.go:835 +0x138
main.(*step).getArg(0x1310bc00, 0x126dfcd0, 0x3, 0x12770080)
	/Applications/Go Agent.app/pipelines/Packaging/specification.go:93 +0x46
main.(*step).getArg(0x1310bce0, 0x12702720, 0x9, 0x7)
	/Applications/Go Agent.app/pipelines/Packaging/specification.go:101 +0x12a
main.populateConceptDynamicParams(0x1310bd50, 0x131ab6b0)
	/Applications/Go Agent.app/pipelines/Packaging/specExecutor.go:475 +0x2bd
main.(*specExecutor).resolveToProtoConceptItem(0x13182d80, 0x2, 0x1255e5f0, 0x42, 0x126b8b41, 0x5c, 0x12702d20, 0x4, 0x4, 0x1, ...)
	/Applications/Go Agent.app/pipelines/Packaging/specExecutor.go:262 +0x7c
main.(*specExecutor).resolveToProtoConceptItem(0x13182d80, 0x2, 0x12659590, 0x23, 0x12742701, 0x3c, 0x1279fbb0, 0x3, 0x4, 0x1, ...)
	/Applications/Go Agent.app/pipelines/Packaging/specExecutor.go:269 +0x1b3
main.(*specExecutor).resolveToProtoConceptItem(0x13182d80, 0x1, 0x12658f90, 0x2f, 0x1255f591, 0x48, 0x127c6d20, 0x3, 0x4, 0x1, ...)
	/Applications/Go Agent.app/pipelines/Packaging/specExecutor.go:269 +0x1b3
main.(*specExecutor).resolveToProtoItem(0x13182d80, 0x1d2858, 0x126e1b90, 0x13183a10)
	/Applications/Go Agent.app/pipelines/Packaging/specExecutor.go:238 +0xa6
main.(*specExecutor).resolveItems(0x13182d80, 0x125e4600, 0x36, 0x40, 0x0, 0x0, 0x0)
	/Applications/Go Agent.app/pipelines/Packaging/specExecutor.go:217 +0xe4
main.(*specExecutor).addAllItemsForScenarioExecution(0x13182d80, 0x12819f50, 0x1317e008)
	/Applications/Go Agent.app/pipelines/Packaging/specExecutor.go:187 +0x177
main.(*specExecutor).executeScenario(0x13182d80, 0x12819f50, 0x0)
	/Applications/Go Agent.app/pipelines/Packaging/specExecutor.go:167 +0x348
main.(*specExecutor).executeScenarios(0x13182d80, 0x0, 0x0, 0x0)
	/Applications/Go Agent.app/pipelines/Packaging/specExecutor.go:157 +0xca
main.(*specExecutor).execute(0x13182d80, 0x126de4c0)
	/Applications/Go Agent.app/pipelines/Packaging/specExecutor.go:103 +0x810
main.(*simpleExecution).start(0x13182d50, 0x127dd840)
	/Applications/Go Agent.app/pipelines/Packaging/execution.go:114 +0x4a4
main.executeSpecs(0x7e9600)
	/Applications/Go Agent.app/pipelines/Packaging/gauge.go:261 +0x4ec
main.main()
	/Applications/Go Agent.app/pipelines/Packaging/gauge.go:114 +0x339

goroutine 6 [select]:
github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).acceptConnectionWithoutTimeout(0x12696de0, 0x0, 0x0, 0x0, 0x0)
	/tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:91 +0x2c8
github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).HandleMultipleConnections(0x12696de0)
	/tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:139 +0x28
created by main.startAPIService
	/Applications/Go Agent.app/pipelines/Packaging/api.go:68 +0x337

goroutine 13 [IO wait]:
net.(*pollDesc).Wait(0x12761b10, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x42
net.(*ioSrv).ExecIO(0x127dd940, 0x12761a78, 0x7e8538, 0x7, 0x8c9f84, 0x4e, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_windows.go:188 +0x265
net.(*netFD).Read(0x12761a40, 0x1281c000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_windows.go:470 +0x11a
net.(*conn).Read(0x128141d8, 0x1281c000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/net.go:121 +0xba
github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).handleConnectionMessages(0x12696de0, 0x1d8a80, 0x128141d8)
	/tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:106 +0x9c
created by github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).acceptConnectionWithoutTimeout
	/tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:96 +0x287

goroutine 8 [syscall, locked to thread]:
syscall.ReadFile(0x11c, 0x12782000, 0x8000, 0x8000, 0x12831eb8, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_windows.go:282 +0xa4
syscall.Read(0x11c, 0x12782000, 0x8000, 0x8000, 0x45c515, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/syscall_windows.go:284 +0x68
os.(*File).read(0x127dda98, 0x12782000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/file_windows.go:299 +0x10b
os.(*File).Read(0x127dda98, 0x12782000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/file.go:95 +0x76
io.Copy(0x1d8980, 0x12696e50, 0x1d2668, 0x127dda98, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/io/io.go:362 +0x184
os/exec.func·003(0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:221 +0x6b
os/exec.func·004(0x12697660)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:328 +0x2b
created by os/exec.(*Cmd).Start
	/usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:329 +0x996

goroutine 9 [syscall, locked to thread]:
syscall.WaitForSingleObject(0x180, 0xffffffff, 0x12557da0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_windows.go:689 +0x66
os.(*Process).wait(0x126de2f0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/exec_windows.go:16 +0x7f
os.(*Process).Wait(0x126de2f0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/doc.go:45 +0x38
os/exec.(*Cmd).Wait(0x12566b40, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:364 +0x19f
main.func·007()
	/Applications/Go Agent.app/pipelines/Packaging/runner.go:202 +0x37
created by main.waitAndGetErrorMessage
	/Applications/Go Agent.app/pipelines/Packaging/runner.go:207 +0xe7

goroutine 14 [IO wait]:
net.(*pollDesc).Wait(0x12761870, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x42
net.(*ioSrv).ExecIO(0x127dd940, 0x127617d8, 0x7eece8, 0x8, 0x128141f8, 0x12760620, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_windows.go:188 +0x265
net.(*netFD).acceptOne(0x127617a0, 0x12760540, 0x2, 0x2, 0x127617d8, 0x12808230, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_windows.go:558 +0x3ee
net.(*netFD).accept(0x127617a0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_windows.go:585 +0x119
net.(*TCPListener).AcceptTCP(0x127dd950, 0x1d8ab8, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/tcpsock_posix.go:234 +0x48
net.(*TCPListener).Accept(0x127dd950, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/tcpsock_posix.go:244 +0x48
github.com/getgauge/gauge/conn.func·002()
	/tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:82 +0x39
created by github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).acceptConnectionWithoutTimeout
	/tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:89 +0x17c

goroutine 259 [syscall, locked to thread]:
syscall.WaitForSingleObject(0x530, 0xffffffff, 0x3b, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_windows.go:689 +0x66
os.(*Process).wait(0x131aa190, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/exec_windows.go:16 +0x7f
os.(*Process).Wait(0x131aa190, 0x12df3180, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/doc.go:45 +0x38
os/exec.(*Cmd).Wait(0x12c612c0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:364 +0x19f
main.func·002()
	/Applications/Go Agent.app/pipelines/Packaging/plugin.go:191 +0x29
created by main.startPlugin
	/Applications/Go Agent.app/pipelines/Packaging/plugin.go:192 +0x42c

goroutine 248 [select]:
main.func·008()
	/Applications/Go Agent.app/pipelines/Packaging/specDetails.go:90 +0x1e8
created by main.(*specInfoGatherer).watchForFileChanges
	/Applications/Go Agent.app/pipelines/Packaging/specDetails.go:97 +0x1ca

goroutine 247 [syscall, locked to thread]:
syscall.GetQueuedCompletionStatus(0x5b0, 0x12c9bda0, 0x12c9bda4, 0x12c9bde4, 0xffffffff, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_windows.go:525 +0x7e
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0x12db54a0)
	/tmp/src/gopkg.in/fsnotify.v1/windows.go:381 +0xa3
created by gopkg.in/fsnotify%2ev1.NewWatcher
	/tmp/src/gopkg.in/fsnotify.v1/windows.go:46 +0x2fd

goroutine 258 [syscall, locked to thread]:
syscall.ReadFile(0x120, 0x131ec000, 0x8000, 0x8000, 0x12c9eeb8, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_windows.go:282 +0xa4
syscall.Read(0x120, 0x131ec000, 0x8000, 0x8000, 0x45c515, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/syscall_windows.go:284 +0x68
os.(*File).read(0x12daf7f0, 0x131ec000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/file_windows.go:299 +0x10b
os.(*File).Read(0x12daf7f0, 0x131ec000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/file.go:95 +0x76
io.Copy(0x1ebe70, 0x12daf7a8, 0x1d2668, 0x12daf7f0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/io/io.go:362 +0x184
os/exec.func·003(0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:221 +0x6b
os/exec.func·004(0x131aa0e0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:328 +0x2b
created by os/exec.(*Cmd).Start
	/usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:329 +0x996

goroutine 245 [chan receive]:
main.(*specInfoGatherer).watchForFileChanges(0x127abf80)
	/Applications/Go Agent.app/pipelines/Packaging/specDetails.go:108 +0x4fa
created by main.(*specInfoGatherer).makeListOfAvailableSteps
	/Applications/Go Agent.app/pipelines/Packaging/specDetails.go:51 +0xe7

Process finished with exit code 2

{code}

**Comment by ApoorvaM** [comment]
Fixed in [commit](https://github.com/getgauge/gauge/commit/ba2fc077d75dddba4f52c2f4a2abe70b1976adff).

**Comment by apoorvam** [comment]
@kupna Can you please check if you are still facing this issue with latest release of gauge(0.1.7)?
