### ISSUE TITLE
support emacs

### ISSUE THREAD

**Issue by osman-mohamad** [getgauge/gauge#1570]
### Expected behavior
support emacs

### Actual behavior
there is no support about it

**Comment by sriv** [comment]
gauge supports the language server protocol, so you could wire it up with https://github.com/emacs-lsp/lsp-mode

see [this blog section](https://blog.getgauge.io/gauge-and-the-language-server-protocol-c56fbcfba177#392e) for an illustration of gauge-lsp with neovim.

**Comment by zabil** [comment]
Last time I tried, https://github.com/emacs-lsp/lsp-mode works with a few configuration. Afraid that I do not have anything to share. 

Emacs won't be officially supported by Gauge.
