### ISSUE TITLE
Move template hosting to Github

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge#1575]
### Current behavior

When running the command
```
gauge init -templates
```

Gauge uses the url https://templates.gauge.org to get a list of templates. This file is currently generated and pushed to an amazon s3 bucket.

When running
```
gauge init java
```

Downloads the template files from s3 (Again the zip files are generated from https://github.com/getgauge/gauge-repository) 

### Solution 1

To make this automated and managed via GitHub it's best create and organization called `Gauge-Templates` and split https://github.com/getgauge/gauge-repository based on templates under this organization.

For e.g.

```
https://github.com/getgauge-templates/java
```

The list of templates can be obtained github's API for e.g
```
https://api.github.com/users/getgauge-templates/repos
```

And the latest version can be published as a release and downloaded using

```
https://github.com/getgauge-templates/java/releases/latest/download/java.zip
```

### Solution 2

Similar to Solution 1 but instead of using a separeate organization `getgauge-templates` create template repositories under https://github.com/getgauge for example

```
https://github.com/getgauge/template-java
```

Gauge will use this convention to resolve the template and download the latest version from

```
https://github.com/getgauge/template-java/releases/latest/download/java.zip
```

**Comment by sriv** [comment]
we could also leverage GIthub's template repository - https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

**Comment by zabil** [comment]
To solve this I think it's best to introduce a templates configuration file 
`template.properties`. This will point to github repo locations. Note that they need not be qualified with the full github url's as download of releases is done via github api.

```
java = getgauge/java-template
js = getgauge/js-template
...
```

`template.properties` will be created in the `.gauge` configuration folder.

`gauge init --templates` can read and list from this list.
`gauge config` could add a flag `--template` to work with the values. For examples

```
gauge config --template java getgauge/custom-java-template
```

The template zip files can be published as github releases. Gauge will use github api's to download the lates zip release.

These repositories can also be be marked as github template repositories so that other user can clone and use them.

Users could also publish other templates as github repos for setting up custom templates can be done by adding it to the config and calling the `gauge init` command for example.

```
gauge config --template kotlin user/gauge-kotlin-template
gauge init kotlin
```

**Comment by haroon-sheikh** [comment]
I really like the idea of using github for templates. It allows a lot of users to create custom templates and be installed by just using their github repository address `gauge config --template java getgauge/custom-java-template`.

Think a similar approach could also be taken for plugins, installing using github repo url. Would allow to remove dependecy on the gauge-repository configurations.

E.g. `gauge install plugin-name --path getgauge/gauge-java`

**Comment by zabil** [comment]
An update on how this feature will be implemented.
The templates need not be a GitHub repo but a url to a hosted zip file for e.g.

```
java=https://github.com/getgauge/template-java/releases/latest/download/java.zip
```

Gauge templates will be hosted on GitHub and released to default to the url above.

Support for a direct download gives template authors more flexibility their own hosting setup.

By default this should be a `https` url with a configuration to override to http url with a warning that it about insecure download.

Plugins need some metadata like platform but should work kind of same way.
