### ISSUE TITLE
Unable to install java plugin - Error downloading file: 404

### ISSUE THREAD

**Issue by ed0906** [getgauge/gauge#1577]
Cannot install the java gauge plugin.

### Expected behaviour
The plugin should install correctly

### Actual behaviour
```
gauge install java
Failed to install plugin 'java'.
Reason: Failed to download the plugin. Error downloading file: https://github.com/getgauge/gauge-java/releases/download/v0.7.4/gauge-java-0.7.4-darwin.x86_64.zip.
404 Not Found
```
The plugin artefact does not exist

### Steps to reproduce
1. `npm install -g @getgauge/cli`
2. `gauge install java`

### Gauge version
```
Gauge version: 1.0.7
Commit Hash: ed7b4fd6

Plugins
-------
html-report (4.0.8)
js (2.3.7)
screenshot (0.0.1)
```

**Comment by zabil** [comment]
Thanks for pointing this out.
The download url's are picked up for https://github.com/getgauge/gauge-repository/blob/a27e8b8566232929d267ad3bc589d953d30b012e/java-install.json#L20

However with 1.0.7 the java runner is not platform dependent. so 

```
https://github.com/getgauge/gauge-java/releases/download/v0.7.4/gauge-java-0.7.4-darwin.x86_64.zip
```

Should be

```
https://github.com/getgauge/gauge-java/releases/download/v0.7.4/gauge-java-0.7.4.zip
```

This is fixed, can you check now?

**Comment by ed0906** [comment]
Works fine now thanks for the quick fix!

**Comment by zabil** [comment]
@ed0906 On another note can you tell us how you chanced upon this issue? Where you upgrading to a new version of Gauge or simply trying out the Gauge Java plugin?

**Comment by emlaver** [comment]
@zabil The curl script at `https://downloads.gauge.org/stable` may also need to be updated because it downloads the binary `https://github.com/getgauge/gauge/releases/download/v1.0.7/gauge-1.0.7-linux.x86_64.zip` under Linux.

**Comment by zabil** [comment]
> https://github.com/getgauge/gauge/releases/download/v1.0.7/gauge-1.0.7-linux.x86_64.zip

The Gauge binaries are still platform dependent, so this url is right. It's only the Gauge Java runner that's changed. Are you facing any issue while running the curl script?

**Comment by emlaver** [comment]
Ok thanks for details.  I believe the issue I've found is unrelated.
