### ISSUE TITLE
Allow call of concept foreach inline table row

### ISSUE THREAD

**Issue by michael-zeller** [getgauge/gauge#1578]
### Expected behavior
When i have a concept-file with the params <one> and <two>
When i have a spec-file which uses the concept
And i call the concept-step with an inline table and the columns |one|two|
Then the concept should be called for each row of the inline table with the values from the inline table

### Actual behavior
Found no documentation couldn't get to work :(
Currently i use the `allow_scenario_datatable = true` property and run all the steps multiple times

### Steps to reproduce

1. Files
_specification.spec_
```
# call concept with table
## calling scenario

* echo "normal" "step"
* Use concept with <one> and <two>
   |one|two|
   |hello|world|
   |foo|bar|
```

_concept.cpt_
```
# Use concept with <one> and <two>

* echo "one" <one>
* echo "two" <two>
```
_step_implementation.js
```
step("echo <label> <value>", async function(label, value) {
	console.log(label, value);
});
```

### Gauge version
```
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
html-report (4.0.8)
js (2.3.7)
screenshot (0.0.1)
spectacle (0.1.3)
```

**Comment by sriv** [comment]
This isn't specific to a concept as I see it. 

This invocation:

```
* Use concept with <one> and <two>
   |one|two|
   |hello|world|
   |foo|bar|
```

is the same as you'd invoke a concept or a plain step. And looking at the spec, there is no distinction whether the implementation is a concept or a step. This might pose some confusion while authoring a spec.

Secondly, the above notation already has a semantic meaning: there are three parameters passed: `one` and `two` are explicit, the inline table is passed as a third param. The implementation should match this template - `Use concept with <one> and <two> <table>`. By changing this, it'd break the existing contract.

Some (perhaps related) notes:

- If a step alone needs to iterate over a table, this could be used in the implementation? With concepts, there is nothing relevant in place, except passing the table to it's step. Perhaps something like this could work?

```
# Use concept with <one> and <two> <givenTable>

<table: <givenTable>>

* echo "one" <one>
* echo "two" <two>
```

- If you need to repeat a scenario or spec for specific table rows, you could pass `--table-rows` flag at runtime.

**Comment by michael-zeller** [comment]
Hi @sriv, 
Thanks for the Reply.

You are right, 
* it should not matter, if it is a "normal" step, or a concept.
* with the current possibilities of Gauge specifications i would implement the step as javascript with a table param.




I'm not looking for this specific syntax, but for a way (maybe with some new syntax) to call a step or concept for each row of a table.

**maybe a bit background to my request:**

I use the concepts as a kind of procedure/method to be used by business-experts inside the scenarios. Concepts are way more understandable than the according javascript code and therefore usefull for communicating the requirements between business experts and developers.


Maybe an alternative aproach:
Is there a possibility to call a concept from the javascript implementation? Than i could iterate over each table row and call the concept from inside the step-implementation. This way my business experts could still see and read the concept to understand what is happening and use the tables...

**Comment by zabil** [comment]
> Is there a possibility to call a concept from the javascript implementation? 

Thank you very much for taking time to explaining the use case.

Concept (like the name suggests) is abstract and a collection of steps. It is inaccessible from the step implementations. 

Unfortunately, there are no workarounds at the moment. Nor a simple technical way to implement this feature :(
