### ISSUE TITLE
I can't run Gauge with GoCD

### ISSUE THREAD

**Issue by mohammed-amhend** [getgauge/gauge#158]
I created a task in GoCd to launch the "gauge specs" command, but it didn't work. It told me : "[CRIT] Failed to start a runner". I tried to get into the go agent (it's a docker container ) and issue the "gauge specs" command and it worked perfectly

**Comment by sriv** [comment]
Could you share the environment variables and working directory of your Go task? If you can share the console log (with sensitive information obfuscated, of course), it will help us understand the issue.

**Comment by mohammed-amhend** [comment]
Here's it : 
[root@8cebccff6ce9 logs]# cat api.log
16:33:59.895 [ERRO] Runner connection failed: Plugin 'java' not installed on following locations : [/root/.gauge/plugins]
16:33:59.906 [INFO] Watching directory: /var/lib/go-agent/pipelines/shopping/specs
16:34:38.573 [ERRO] Runner connection failed: Plugin 'java' not installed on following locations : [/root/.gauge/plugins]
16:34:40.763 [ERRO] Runner connection failed: Plugin 'java' not installed on following locations : [/root/.gauge/plugins]
16:34:42.607 [ERRO] Runner connection failed: Plugin 'java' not installed on following locations : [/root/.gauge/plugins]
16:34:43.508 [ERRO] Runner connection failed: Plugin 'java' not installed on following locations : [/root/.gauge/plugins]
16:35:25.180 [ERRO] Runner connection failed: Plugin 'java' not installed on following locations : [/root/.gauge/plugins]
16:35:29.803 [ERRO] Runner connection failed: Plugin 'java' not installed on following locations : [/root/.gauge/plugins]
16:38:42.310 [INFO] Watching directory: /var/lib/go-agent/pipelines/shopping/specs
16:45:03.120 [INFO] Watching directory: /var/lib/go-agent/pipelines/shopping/specs
21:11:21.123 [INFO] Watching directory: /var/lib/go-agent/pipelines/shopping/specs
21:41:19.156 [INFO] Watching directory: /var/lib/go-agent/pipelines/shopping/specs


But After checking I found that the java plugin is installed at /root/.gauge/plugins/java

Here's the env vars : 

16:05:26.140 [go] setting environment variable 'GO_SERVER_URL' to value 'https://goserver:8154/go/'
16:05:26.140 [go] setting environment variable 'GO_TRIGGER_USER' to value 'mohammed'
16:05:26.140 [go] setting environment variable 'GO_PIPELINE_NAME' to value 'shopping'
16:05:26.140 [go] setting environment variable 'GO_PIPELINE_COUNTER' to value '17'
16:05:26.141 [go] setting environment variable 'GO_PIPELINE_LABEL' to value '17'
16:05:26.141 [go] setting environment variable 'GO_STAGE_NAME' to value 'Acceptance'
16:05:26.141 [go] setting environment variable 'GO_STAGE_COUNTER' to value '6'
16:05:26.141 [go] setting environment variable 'GO_JOB_NAME' to value 'install_tools_and_run_tests'
16:05:26.141 [go] setting environment variable 'GO_REVISION' to value '6bf5eb08d30602af9dc9afa56e4292895e1bd280'
16:05:26.141 [go] setting environment variable 'GO_TO_REVISION' to value '6bf5eb08d30602af9dc9afa56e4292895e1bd280'
16:05:26.141 [go] setting environment variable 'GO_FROM_REVISION' to value '6bf5eb08d30602af9dc9afa56e4292895e1bd280'

**Comment by prateekbaheti** [comment]
This could be because most likely because of no read permissions on /root/.gauge/plugins/java directory. The Go agent process that launches gauge may not have permissions to read from /root.

**Comment by prateekbaheti** [comment]
Any updates on this ? Does launching the agent or the gauge process as sudo resolve the issue ?

**Comment by mohammed-amhend** [comment]
the "go" user wasn't a sudoer in my case. After making it a sudoer in the sudoers files, it works perfectly
