### ISSUE TITLE
Failed to start gauge API: Timed out connecting to java in 1.0.7

### ISSUE THREAD

**Issue by damvinod** [getgauge/gauge#1580]
### Expected behavior
Gauge not able to run test cases in kubenetes cluster. Getting below error with gauge `1.0.7` works fine in `1.0.6`

Failed to start gauge API: Timed out connecting to java

Below are the pod resources config

  limits:
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi

### Gauge version
```
Your Environment Information -----------
Gauge version: 1.0.7
linux, 1.0.7, ed7b4fd6
html-report (4.0.9), java (0.7.4), xml-report (0.2.3)
```

**Comment by sriv** [comment]
Please check if your project uses `0.7.4` as gauge-Java version for its dependency (ex. In `pom.xml` or in `build.gradle`).

**Comment by damvinod** [comment]
@sriv Yes its using `0.7.4` as gauge-Java version below is the output of `gauge -v`

Plugins
-------
html-report (4.0.9)
java (0.7.4)
xml-report (0.2.3)

**Comment by damvinod** [comment]
@sriv Looks like this issue is only happening in gauge version `1.0.7` works fine in `1.0.6`

**Comment by negiDharmendra** [comment]
@damvinod Is it possible for you to share a sample project to reporoduce this issue?

**Comment by cyberjaime45** [comment]
I was having the same issue with the time out. It was because I had installed java 0.7.4 but then in the pom file was 0.7.3.

So changed to 0.7.4 then it worked fine

**Comment by cyberjaime45** [comment]
I'm having the same issue. Works fine on my mac, however I get this errors in Ubuntu. Still investigating

**Comment by damvinod** [comment]
It’s working for me after changing the build.gradle to point to gauge-java to ‘0.7.4’

**Comment by negiDharmendra** [comment]
@damvinod @cyberjaime45 Glad to know that the issue has been resolved. Please feel free to reopen this issue or create a new issue if you face this issue again.

**Comment by haimdalet** [comment]
delete node_modules and .gauge folders
change in package.json "@getgauge/cli": "^1.0.6", to 1.0.7
run npm install
and run the tests

works for me :)
