### ISSUE TITLE
Failed to start gauge API: Timed out connecting to java (1.0.7)

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge#1581]
Failed to start gauge API with the latest version of gauge (1.0.7)

### Expected behavior
Should run the gauge-java plugin

### Actual behavior
Following error is thrown: 
```
Failed to start gauge API: Timed out connecting to java
```

### Steps to reproduce
1. Using the https://github.com/getgauge-examples/java-maven-selenium project.
2. `docker run --rm -it -v $(pwd):/usr/src/app sitture/docker-gauge-java:1.0.7 mvn test`

Same thing works on version 1.0.6 and 1.0.5

```
docker run --rm -it -v $(pwd):/usr/src/app sitture/docker-gauge-java:1.0.6 mvn test
docker run --rm -it -v $(pwd):/usr/src/app sitture/docker-gauge-java:1.0.5 mvn test
```

### Gauge version
```
docker run --rm -it -v $(pwd):/usr/src/app sitture/docker-gauge-java:1.0.7 gauge -v

Gauge version: 1.0.7
Commit Hash: ed7b4fd6

Plugins
-------
html-report (4.0.9)
java (0.7.4)
reportserver (0.1.1)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)
```

**Comment by zabil** [comment]
@haroon-sheikh I noticed that the versions in the pom were quite old.
I just pushed a commit to fix that
https://github.com/getgauge-examples/java-maven-selenium/commit/d45c012895acbef43c1d3c18bb277e532ac292c4

Can you check with the updated versions?

**Comment by haroon-sheikh** [comment]
Yep @zabil, the problem with me using older version of gauge-java in pom.xml. Updating to 0.7.4 fixes the problem.

**Comment by negiDharmendra** [comment]
@haroon-sheikh Gauge 1.0.7 is compatible with older version of plugins but new plugins are not compatible with the Gauge version **(< 1.0.7)**.
