### ISSUE TITLE
Report fails to be generated when data driver spec is part of parallel tags filters

### ISSUE THREAD

**Issue by marius-uncrop** [getgauge/gauge#1584]
### Prerequisites:
**$ gauge -v**
Gauge version: 1.0.7
Commit Hash: ed7b4fd6

Plugins
-------
flash (0.0.2)
html-report (4.0.9)
python (0.3.7)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)

**default.properties:**
allow_filtered_parallel_execution = true

### Steps:
1. init a python project
2. Create a data driven spec
3. Add a tag to a scenario from the data driver spec (e.g.: no-parallel)
4. Run the specs in parallel and filter the no-parallel scenarios from parallel execution
**$ gauge run specs/ --parallel --only "\!no-parallel"**

### Expected behavior
Specs run successfully and html report is successfully generated

### Actual behavior
Specs run, but the html-report fails to be generate

`Executing in 0 parallel streams.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x85e70d]
goroutine 12 [running]:
github.com/getgauge/html-report/generator.computeTableDrivenStatuses(0xc0002e6000)
        /Users/runner/runners/2.164.0/work/html-report/html-report/generator/transform.go:421 +0x2d
github.com/getgauge/html-report/generator.toSpec(0xc00021d7c0, 0x0)
        /Users/runner/runners/2.164.0/work/html-report/html-report/generator/transform.go:
373 +0x1309
github.com/getgauge/html-report/generator.ToSuiteResult(0xc00002a004, 0x34, 0xc00007ca80, 0x48)
        /Users/runner/runners/2.164.0/work/html-report/html-report/generator/transform.go:78 +0x86a
main.createReport
(0xc0001f1e30, 0x409e01, 0x930280, 0x955c80, 0xc000221500, 0xa513a0)
        /Users/runner/runners/2.164.0/work/html-report/html-report/htmlReport.go:70 +0xc0
main.(*handler).NotifySuiteResult(0xc00000e308, 0xa4cc60
, 0xc0001f1e00, 0xc0001f1e30, 0xc00000e308, 0xc0001f1e00, 0xc000099a80)
        /Users/runner/runners/2.164.0/work/html-report/html-report/handler.go:58 +0x30
github.com/getgauge/html-report/gauge_messages._Reporter_NotifySuiteResult_Handler(0x955c80, 0xc00000e308, 0xa4cc60, 0xc0001f1e00
, 0xc000221560, 0x0, 0xa4cc60`

** See attached a very simple gauge project
[gauge_test_parallel.zip](https://github.com/getgauge/gauge/files/4235723/gauge_test_parallel.zip)

**Comment by BugDiver** [comment]
@marius-uncrop  I'm able to replicate it. We will try to push a fix soon.
