### ISSUE TITLE
gauge run gets stuck on step applying tags filter for parallel execution

### ISSUE THREAD

**Issue by marius-uncrop** [getgauge/gauge#1585]
Prerequisites:
$ gauge -v
Gauge version: 1.0.7
Commit Hash: ed7b4fd

Plugins
flash (0.0.2)
html-report (4.0.9)
python (0.3.7)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)

default.properties:
allow_filtered_parallel_execution = true

### Notes
Our automation suite contains now 200+ specs, and 800+ scenarios. When trying to use tags filtering for parallel execution, the execution gets stuck at step _"Applying tags filter_
I tried the feature on new, very basic project and it worked fine. So I'm assuming it has to be related to the large number on scenarios. Unfortunately, I can't share our automation tests, but maybe someone can investigate.

This is a log from a run ( I've stopped the execution after about 30 minutes of waiting)

`
gauge run specs/sanity --parallel --only "\!no-parallel" --log-level debug --machine-readable --fail-safe 
{"type":"out","message":"gauge run specs/sanity"}
{"type":"out","message":"fail-safe : [true]"}
{"type":"out","message":"log-level : [debug]"}
{"type":"out","message":"machine-readable : [true]"}
{"type":"out","message":"only : [\\!no-parallel]"}
{"type":"out","message":"parallel : [true]"}
{"type":"out","message":"'gauge_environment' set to 'default'"}
{"type":"out","message":"Created gauge_screenshots_dir at /home/marius/workspace/auto/figtesting/website_sanity_tests/.gauge/screenshots"}
{"type":"out","message":"Plugin python is already installed."}
{"type":"out","message":"Plugin html-report is already installed."}
{"type":"out","message":"Plugin spectacle is already installed."}
{"type":"out","message":"Plugin flash is already installed."}
{"type":"out","message":"Plugin xml-report is already installed."}
{"type":"out","message":"Parsing started."}
{"type":"out","message":"Started concepts parsing."}
{"type":"out","message":"102 concepts parsing completed."}
{"type":"out","message":"Started specifications parsing."}
{"type":"out","message":"206 specifications parsing completed."}
{"type":"out","message":"Parsing completed."}
{"type":"out","message":"Staring python runner"}
{"type":"out","message":"Checking updates..."}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/flash?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Python: 3.5.3"}
{"type":"out","message":"Loading step implemetations from /home/marius/workspace/auto/figtesting/website_sanity_tests/step_impl dirs."}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/html-report?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/python?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/screenshot?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/spectacle?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Downloading https://downloads.getgauge.io/plugin/xml-report?l=python\u0026p=flash,html-report,python,screenshot,spectacle,xml-report\u0026o=linux\u0026a=amd64"}
{"type":"out","message":"Starting TCP server.."}
{"type":"out","message":"Connecting to port 35163"}
{"type":"out","message":"Established connection to runner."}
{"type":"out","message":"Validation started."}
{"type":"out","message":"Validation completed."}
{"type":"out","message":"Sending kill message to runner."}
{"type":"out","message":"Runner with PID:13302 has exited"}
{"type":"out","message":"Run started"}
{"type":"out","message":"Starting Html Report plugin"}
{"type":"suiteStart"}
{"type":"out","message":"Attempting to connect to grpc server at port: 44871"}
{"type":"out","message":"Successfully made the connection with plugin with port: 44871"}
{"type":"out","message":"Starting Flash plugin"}
{"type":"out","message":"[Flash] Starting progress reporting at http://127.0.0.1:5678"}
{"type":"out","message":"Attempting to connect to grpc server at port: 42025"}
{"type":"out","message":"Successfully made the connection with plugin with port: 42025"}
{"type":"out","message":"Starting Xml Report plugin"}
{"type":"out","message":"Attempting to connect to grpc server at port: 37937"}
{"type":"out","message":"Successfully made the connection with plugin with port: 37937"}
{"type":"out","message":"Applying tags filter: \\!no-parallel"}`

**Comment by BugDiver** [comment]
@marius-uncrop Can you please run `pip3 uninstall getgauge -y` and then `pip3 install getgauge` and give the logs/output of that?

**Comment by BugDiver** [comment]
@marius-uncrop I see that you are using gauge v1.0.7 but the python plugin is still a bit older v0.3.7
Could you please update the python plugin and check if that helps?

**Comment by marius-uncrop** [comment]
@BugDiver 
Currently, I cannot run specs with latest version of python plugin. see https://github.com/getgauge/gauge-python/issues/179

**Comment by NivedhaSenthil** [comment]
@marius-uncrop is it working fine now ? could see the issue with latest python plugin is resolved

**Comment by marius-uncrop** [comment]
@NivedhaSenthil , same behaviour using python plugin version 0.3.8
