### ISSUE TITLE
error in 1.0.7 with java 1.8

### ISSUE THREAD

**Issue by Shankar016** [getgauge/gauge#1586]
Error ----------------------------------

[java]
Error in thread 1
Format specifier '%s'
java.util.MissingFormatArgumentException: Format specifier '%s'
[INFO] ------------------------------------------------------------------------
        at java.util.Formatter.format(Unknown Source)
[INFO] BUILD FAILURE
        at java.util.Formatter.format(Unknown Source)
[INFO] ------------------------------------------------------------------------
        at java.lang.String.format(Unknown Source)
        at com.thoughtworks.gauge.connection.GaugeConnector.connect(GaugeConnector.java:45)
[INFO] Total time:  52.397 s
        at com.thoughtworks.gauge.connection.GaugeConnector.makeConnectionsToGaugeCore(GaugeConnector.java:35)
[INFO] Finished at: 2020-02-21T13:05:16Z
        at com.thoughtworks.gauge.GaugeRuntime.makeConnection(GaugeRuntime.java:120)
[INFO] ------------------------------------------------------------------------
        at com.thoughtworks.gauge.GaugeRuntime.connectSynchronously(GaugeRuntime.java:106)
[ERROR] Failed to execute goal com.thoughtworks.gauge.maven:gauge-maven-plugin:1.3.0:execute (default) on project IQBotAutomation: Gauge Specs execution failed -> [Help 1]
        at com.thoughtworks.gauge.GaugeRuntime.startGaugeServer(GaugeRuntime.java:76)
[ERROR]
        at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:53)
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[Gauge]
[ERROR]
Failed to start gauge API: Timed out connecting to java
[ERROR] For more information about the errors and possible solutions, please read the following articles:

[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.c
C:\cognitive\testautomation\ui-automation>gauge -version
Error: unknown shorthand flag: 'e' in -ersion
Usage:
  gauge <command> [flags] [args]

**Comment by Shankar016** [comment]
Anyone has a fix?

**Comment by BugDiver** [comment]
@Shankar016 Please update `gauge-java`  version to `1.0.7` in your `pom.xml` as well.

**Comment by muhammadshakil** [comment]
I am getting same error.

Any update on it?

**Comment by zmaks** [comment]
Try to downgrade gauge java plugin:
`gauge uninstall java --version 0.7.4`
`gauge install java --version 0.7.2`

It's solved the issue for me: macOS 10.15.2, java `openjdk version 1.8.0_232`, gauge 1.0.7

**Comment by zabil** [comment]
Unfortunately, Gauge does not support JDK 1.8 anymore.

**Comment by MonishSriram** [comment]
Facing the same issue with ```openjdk 13.0.2```

Following is the gauge info:
```
Gauge version: 1.0.7
html-report (4.0.8)
java (0.7.3)
screenshot (0.0.1)
```
I am running it on a ubuntu docker instance

**Comment by zabil** [comment]
Please use the latest version of the gauge java plugin i.e 0.7.4

Also follow the instructions mentioned at https://spectrum.chat/gauge/general/issues-after-upgrading-to-the-latest-version-of-gauge-1-0-7-and-java-0-7-4~136093eb-4017-4e4f-9379-a377b4dadb67 to update other dependencies
