### ISSUE TITLE
This version of Gauge Intellij plugin only works with gauge version >= 0.9.0

### ISSUE THREAD

**Issue by kokavolchkov** [getgauge/gauge#1590]
### Expected behavior
Project with Gauge plugin can start on MacOS
### Actual behavior
The "This version of Gauge Intellij plugin only works with gauge version >= 0.9.0" error appears

### Steps to reproduce
1. On the MacOS download the latest Idea version (see the details)
2. Install the Gauge on Mac using the Homebrew 
3. Open the Idea and install the Gauge plugin ver. 0.3.18.
4. In the Idea click the New menu item (to create a new project)
5. Choose the Gauge plugin
6. Click the Next button
7. Set the project name 
8. Click the Finish button
9. Pay attention to the pop-up: "Error adding module to project: This version of Gauge Intellij plugin only works with Gauge version >= 0.9.0"

### Gauge version
 1.0.7

### IntelliJ IDEA 2019.3.3 (Community Edition)
Build #IC-193.6494.35, built on February 11, 2020
Runtime version: 11.0.5+10-b520.38 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: 
Non-Bundled Plugins: com.thoughtworks.gauge

**Comment by kokavolchkov** [comment]
Maybe this will give some additional information: 

I tried launching the project and changed project type to the Maven and added the Gauge archetype (according to this description: https://github.com/getgauge/Intellij-Plugin#installation)

In this case when I try running my project, then I have this error messages:

1. Unable to start Gauge Intellij plugin.: Cannot run program "/Users/username/IdeaProjects/gauge/1.0.7": error=13, Permission denied
2. Unsupported Gauge Version(null): This version of Gauge Intellij plugin only works with Gauge version >= 0.9.0

**Comment by negiDharmendra** [comment]
@kokavolchkov Please run `gauge --version --machine-readable` in your terminal and share the output with us.

**Comment by kokavolchkov** [comment]
{
    "version": "1.0.7",
    "commitHash": "",
    "plugins": [
        {
            "name": "java",
            "version": "0.7.4"
        }
    ]
}

**Comment by kokavolchkov** [comment]
```
{
    "version": "1.0.7",
    "commitHash": "",
    "plugins": [
        {
            "name": "java",
            "version": "0.7.4"
        }
    ]
}
```

**Comment by NivedhaSenthil** [comment]
can you please try the example [project](https://github.com/getgauge-examples/java-maven-selenium) and let us know if you are still facing the issue ?

**Comment by sriv** [comment]
@kokavolchkov - is this still an issue?

**Comment by kokavolchkov** [comment]
@sriv I'll try and tell you

**Comment by sriv** [comment]
investigating one possible cause in getgauge/intellij-plugin#429

Closing this. Feel free to add any detail to the above referenced issue.
