### ISSUE TITLE
Help needed from community.

### ISSUE THREAD

**Issue by negiDharmendra** [getgauge/gauge#1592]
A lot of people in the community are reporting the below issue.

`Connection to runner with Pid 21244 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:62536->127.0.0.1:62538: use of closed network connection`

We have been trying to reproduce this issue on our end but no success until now. So now we are hoping if some from the community facing this issue could share a project to reproduce this issue. It would be nicer if the project also includes a docker file to avoid there are no environment-related issues.

**Comment by nvborisenko** [comment]
Is it one day issue? Or telemetry continues to report this issue?

**Comment by sriv** [comment]
This has been reported multiple times, and the reports do not contain much hint about the possible cause. 

Gauge does not have telemetry anymore, but even when it did, it did not collect information at this level.
