### ISSUE TITLE
Error taking screenshot when running Gauge test through Jenkins 

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/gauge#1594]
Problem Description
I am getting below error message when trying to take screenshot (GaugeScreenshots.Capture();          ) through Jenkins. It works fine when i run the same test on my local.

panic: BitBlt failed
goroutine 1 [running]:
github.com/AllenDang/w32.BitBlt(0x130102ff, 0x0, 0x0, 0x400, 0x300, 0x10101b5, 0x0, 0x0, 0xcc0020)
	/Users/vagrant/go-agent-17.4.0/pipelines/Screenshot/src/github.com/AllenDang/w32/gdi32.go:117 +0x120
github.com/getgauge/gauge_screenshot/capture.CaptureRect(0x0, 0x0, 0x400, 0x300, 0x0, 0x0, 0x0)
	/Users/vagrant/go-agent-17.4.0/pipelines/Screenshot/src/github.com/getgauge/gauge_screenshot/capture/capture_windows.go:110 +0x3a4
github.com/getgauge/gauge_screenshot/capture.CaptureScreen(0xc04203bf50, 0x2d, 0x0, 0x0)
	/Users/vagrant/go-agent-17.4.0/pipelines/Screenshot/src/github.com/getgauge/gauge_screenshot/capture/capture_windows.go:54 +0x105
main.main()
	/Users/vagrant/go-agent-17.4.0/pipelines/Screenshot/src/github.com/getgauge/gauge_screenshot/main.go:42 +0x176
panic: BitBlt failed

goroutine 1 [running]:
github.com/AllenDang/w32.BitBlt(0x140102ff, 0x0, 0x0, 0x400, 0x300, 0x10101b5, 0x0, 0x0, 0xcc0020)
	/Users/vagrant/go-agent-17.4.0/pipelines/Screenshot/src/github.com/AllenDang/w32/gdi32.go:117 +0x120
github.com/getgauge/gauge_screenshot/capture.CaptureRect(0x0, 0x0, 0x400, 0x300, 0x0, 0x0, 0x0)
	/Users/vagrant/go-agent-17.4.0/pipelines/Screenshot/src/github.com/getgauge/gauge_screenshot/capture/capture_windows.go:110 +0x3a4
github.com/getgauge/gauge_screenshot/capture.CaptureScreen(0xc04203bf50, 0x2d, 0x0, 0x0)
	/Users/vagrant/go-agent-17.4.0/pipelines/Screenshot/src/github.com/getgauge/gauge_screenshot/capture/capture_windows.go:54 +0x105
main.main()
	/Users/vagrant/go-agent-17.4.0/pipelines/Screenshot/src/github.com/getgauge/gauge_screenshot/main.go:42 +0x176
panic: BitBlt failed

goroutine 1 [running]:
github.com/AllenDang/w32.BitBlt(0x170102ff, 0x0, 0x0, 0x400, 0x300, 0x10101b5, 0x0, 0x0, 0xcc0020)
	/Users/vagrant/go-agent-17.4.0/pipelines/Screenshot/src/github.com/AllenDang/w32/gdi32.go:117 +0x120
github.com/getgauge/gauge_screenshot/capture.CaptureRect(0x0, 0x0, 0x400, 0x300, 0x0, 0x0, 0x0)
	/Users/vagrant/go-agent-17.4.0/pipelines/Screenshot/src/github.com/getgauge/gauge_screenshot/capture/capture_windows.go:110 +0x3a4
github.com/getgauge/gauge_screenshot/capture.CaptureScreen(0xc04203bf50, 0x2d, 0x0, 0x0)
	/Users/vagrant/go-agent-17.4.0/pipelines/Screenshot/src/github.com/getgauge/gauge_screenshot/capture/capture_windows.go:54 +0x105
main.main()
	/Users/vagrant/go-agent-17.4.0/pipelines/Screenshot/src/github.com/getgauge/gauge_screenshot/main.go:42 +0x176
 F
 
### Gauge version
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
csharp (0.10.5)
dotnet (0.1.2.nightly-2019-02-14)
html-report (4.0.7)
java (0.7.2)
json-report (0.3.0)
screenshot (0.0.1)
xml-report (0.2.1)

**Comment by NivedhaSenthil** [comment]
seems like dependency in gauge-screenshot is erring  and the actual error is shallowed... can you please provide more info regarding your environment ?

**Comment by manavghaigithub** [comment]
Nivedha - What kind of info you are looking for?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by manavghaigithub** [comment]
@NivedhaSenthil Can you please let me know what all details you are looking for?

**Comment by NivedhaSenthil** [comment]
Details regarding the os in which the tests are being run.
Seems like an older version of gauge is used, do try updated to latest and also consider using [custom screenshots writer](https://docs.gauge.org/writing-specifications.html?os=windows&language=java&ide=vscode#taking-custom-screenshots) to take appropriate screenshots

**Comment by sriv** [comment]
@manavghaigithub - did implementing a custom screenshot writer help? You will most likely need it, because there isn't anything useful that the default screenshotwriter can capture in a CI environment, especially if you are running tests headless.

Closing this, feel free to comment if there's anything that can be done at Gauge side.

**Comment by manavghaigithub** [comment]
@sriv Do you have any example of customer screenshot ? So far all the projects have been using Gauge's capture method to take screenshot so it will be little bit painful to change at all the places to run it through. Yeah i can give it a shot if you have any sample code to capture screenshot. Thanks !!!

**Comment by zabil** [comment]
You don't have change the calls to `gauge.screenshot`. You just need to implement a custom screeenshot behavior, this is more like a configuration on how gauge should take screenshot.

Like mentioned in the comments earlier here is a link to the documentation which has code examples.

https://docs.gauge.org/writing-specifications.html?os=macos&language=javascript&ide=vscode#taking-custom-screenshots

The example lists code for Javascript but you can change the language filter in the documentation for code in other languages.
