### ISSUE TITLE
Jira/Xray Plugin announcement

### ISSUE THREAD

**Issue by jbadeau** [getgauge/gauge#1596]
I have created a Jira/Xray report plugin here

https://github.com/jbadeau/xray-report

How do I register it so that Gauge can install via CLI?

Jose

**Comment by jbadeau** [comment]
It basically reports results to X-ray genetic tests. But looking to evolve based on user feedback

**Comment by zabil** [comment]
This is cool!
To register the plugin you can send a pull request like 
https://github.com/getgauge/gauge-repository/pull/35/files

**Comment by jbadeau** [comment]
registered
