### ISSUE TITLE
Need to remove telemetry from doc section

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/gauge#1598]
https://manpage.gauge.org/gauge_telemetry.html

```gauge telemetry
Configure options for sending anonymous usage stats

Synopsis
Configure options for sending anonymous usage stats.

gauge telemetry [command] [flags]
Options
  -h, --help   help for telemetry
Options inherited from parent commands
  -d, --dir string         Set the working directory for the current
                           command, accepts a path relative to current
                           directory (default ".")
  -l, --log-level string   Set level of logging to debug, info, warning, error
                           or critical (default "info")
  -m, --machine-readable   Prints output in JSON format
SEE ALSO
gauge - A light-weight cross-platform test automation tool
gauge telemetry log - Enable/disable telemetry logging
gauge telemetry off - Turn telemetry off
gauge telemetry on - Turn telemetry on
Complete documentati```

**Comment by elbuki** [comment]
Hi, I could work on this issue. Just a question, I was looking for the location where the contents for this manpage is, I tried [searching from the organization level](https://github.com/search?q=org%3Agetgauge+Configure+options+for+sending+anonymous+usage+stats&type=Code) but I was able to just find a setup for Cobra commands that leads to deprecation warnings. Do you know where could I make changes? Thanks!

**Comment by sriv** [comment]
Hi @elbuki - thanks for offering to help! We'd be glad if you help fix this.

You are correct, the only place where this is set is as a cobra command. The manpages are [generated](https://github.com/getgauge/gauge/blob/master/build/man/man.go) from the cobra command.

The cobra command and the generation both need to change. The expectation would be:

- the command `gauge telemetry` continues to exist, but just throws a message - "Gauge does not gather telemetry data. This command exists to notify this deprecation and shall be removed in the future"

- Manpage should stop generating documentation for [`gauge telemetry`](https://manpage.gauge.org/gauge_telemetry.html)

Please feel free to raise a Pull Request once you are happy with your changes.
