### ISSUE TITLE
Run scenarios in parallel

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/gauge#1601]
Expected --> I have multiple specification file and each specification contains multiple scenarios. 

1. Is it possible to run multiple scenarios in parallel across specification file.
2. If Gauge directly does not support than what Gauge's team suggest (like Selenium Grid) in order to achieve this behavior. 
3. Is there any demo/material available to support point 2?
Run gauge -v on your system and paste the results here.

Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
csharp (0.10.5)
dotnet (0.1.2.nightly-2019-02-14)
html-report (4.0.7)
java (0.7.2)
json-report (0.3.0)
screenshot (0.0.1)
xml-report (0.2.1)

**Comment by sriv** [comment]
> Is it possible to run multiple scenarios in parallel across specification file.

No, gauge distributes specifications to be run in parallel.

> If Gauge directly does not support than what Gauge's team suggest (like Selenium Grid) in order to achieve this behavior.

Not sure what is the correlation between the two. Please explain. 

> Is there any demo/material available to support point 2?

There is an example: https://github.com/getgauge-examples/cross-browser that runs against selenium grid. However there are some known issues that you might need to work around.

Folks at Browserstack also have an example - https://github.com/browserstack/gauge-browserstack

**Comment by manavghaigithub** [comment]
@sriv I am using C# dotnet plugin and would like to run scenarios in parallel. Is there any example to achieve it?

**Comment by sriv** [comment]
> I am using C# dotnet plugin and would like to run scenarios in parallel. Is there any example to achieve it?

Unfortunately, no. Because this isn't possible with gauge and the language runner you use has no say in it.
