### ISSUE TITLE
Does Gauge support multi threading for C#?

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/gauge#1603]
I have enable_multithreading = true mentioned in my default.properties file but i am getting message below message

Command --> Gauge run specs -p -n=6

Message --> Executing in 6 parallel streams.
Runner doesn't support mutithreading, using multiprocess parallel execution.

**Comment by sriv** [comment]
if you are using gauge-csharp - then, no. That is deprecated in favour of gauge-dotnet plugin.

We have an open issue for gauge-dotnet -https://github.com/getgauge/gauge-dotnet/issues/40.

We do want to support it, but it may not happen right away. Pull requests are most welcome though.

I'm closing this, feel free to discuss more on https://github.com/getgauge/gauge-dotnet/issues/40

**Comment by manavghaigithub** [comment]
@sriv I have 700 scenarios defined in about 150 spec files. Currently I can only run max of 4 processes in parallel because multi threading is not available?

Is there any other way you can suggest in Gauge when using C# if I want to run more than four specs in parallel?

**Comment by sriv** [comment]
I hear your concern, but the only way out is if the dotnet plugin supported multithreading. We would love to make more runners multithreaded, but the backlog is already huge presently.

It'll be awesome if someone could raise a PR for this.

**Comment by manavghaigithub** [comment]
@sriv how to open the PR for this?

**Comment by zabil** [comment]
instructions for working with pull requests are here

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests
