### ISSUE TITLE
Get Total number of scenarios and specs during run time

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/gauge#1604]
I am using dotnet plugin and c# for my automated tests. Is there any way to get total number of scenarios and spec files during the execution?

I know I can obtain current spec and scenario name but I need total number of spec and scenarios in current execution.

**Comment by sriv** [comment]
This information is not available yet, a good place to add this is under [`ExecutionInfo`](https://github.com/getgauge/gauge-proto/blob/master/messages.proto#L132)

**Comment by zabil** [comment]
Gauge will not extending `ExecutionInfo` to add this info at the moment. 

This means that total number of spec and scenarios can only be obtained after a run. However a PR implementing this feature in a way that does not affect backward compatibility will be merged.
