### ISSUE TITLE
config option to change go test -timeout from default 10 mins

### ISSUE THREAD

**Issue by gaunty** [getgauge/gauge#1613]
HI
We have some specs which take longer than 10 mins,and multiple specs within a folder which combined take longer than 10 minutes.

when a spec takes longer than 10 minutes, this error will occur
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (11m0s).
FAIL    command-line-arguments  660.010s

After drilling down into this, when running go test it will default to 10 mnutes.

We have temporily changed the arguments within gauge/builder.go  

if err := util.RunCommand(os.Stdout, os.Stdout, constants.CommandGo, "test","-timeout","0", "-v", gaugeGoMainFile); err
 != nil {
                return fmt.Errorf("Failed to compile project: %s\nPlease ensure the project is in GOPATH.\n", err.Error())
        }

It would be good if this could be changed via gauge/config/gauge.properties 
Ot if there is another option to prevent the gauge specs failing for long running tests.

Thanks

Steve

**Comment by sriv** [comment]
Can I assume that this is not needed anymore in light of https://github.com/getgauge-contrib/gauge-go/pull/25?

**Comment by gaunty** [comment]
Hi

Yes mate, we using getgauge-contrib version now so that PR can be discarded .

Cheers mate
