### ISSUE TITLE
Not to fail test when tear down steps failed.

### ISSUE THREAD

**Issue by Vishnu1067** [getgauge/gauge#1618]
### Feature Request

Can we have passed test even though there is a failure in tear down?

### Why?

Let's say I have two testcases 
1. Logout.spec
    * Login to app
    * Logout from app - (failure step)
2. CreateQuotation.spec
    * Login to app
    * Create quotation
    _(teardown)
    * Logout from app

When the logout step is failed, it should fail only the Logout.spec but currently it is giving failure of both Logout.spec and CreateQuotation.spec. This lead to wrong successrate in the report.

### SuccessRate

**Current Behavior:**
SuccessRate: 0% 

**Expected Behavior**
SuccessRate: 50%

### Suggested Approach

We shall have the environment variable **TearDownFailure=true / false**

**Comment by zabil** [comment]
Depending on the programming language you are using you can catch and ignore the failure on teardown via exception handling. If you ignore the exception the test will not fail.

You can also use the data store or context to selectively control throwing the exception depending on where the teardown step is executed.

**Comment by Vishnu1067** [comment]
from my above example, i use this step in normal step as well as teardown -`Logout from app`. If i do exceptional handling, it won't capture my main issue right? or i am not understanding the proposed solution?

**Comment by zabil** [comment]
This is the workaround pseudo code.

```
step("Logout from app") {
 if(datastore.get("ignore_logout") != true) {
    throw exception;
 }
}
```

You will have to set this value in the [data store](https://docs.gauge.org/writing-specifications.html?os=linux&language=java&ide=vscode#data-store) in some other step in that specification.

However, please note this is a workaround and not recommended. To find the right error, specifications must fail on teardown too as they can be run independently using a specification name or tags.

**Comment by Vishnu1067** [comment]
This feature is available in robotframework. Teardown failure can make optional. If we bring this feature to gauge, it will give correct success rate in gauge report.

* Logout from app -> this step is failed in my main feature test. If i use this step as a teardown in another feature, still it shows that feature failed hence success rate is 100% instead of 50% 

@sriv  do you think is it valid feature to consider?

**Comment by sriv** [comment]
> @sriv do you think is it valid feature to consider?

No, sorry. Context and teardowns are syntactic sugar added to make the specs capable of avoiding some repetition. They do not (IMO should not) be loaded with interpretation.

The example that you gave is one where it may make sense in your context, to ignore teardown failures. But this is not the only usecase of teardown, hence cannot be generalized. Adding this as an option leads to situations where reading a step would imply something different than what it actually does in gauge's context.

Also, in your example, if logout is already tested, then the teardown can just be workflow steps without any verification. 

Worth noting that gauge is framework agnostic, so it just does not understand the semantics of a user journey, it merely simulates and orchestrates it.
