### ISSUE TITLE
Run scenario is calling '"C:\Python27\python.exe -m pip install getgauge==0.3.7 --user"' and throwing error its not recognized as an internal or external command,

### ISSUE THREAD

**Issue by nischt** [getgauge/gauge#1620]
### Describe the bug

Creatde a project using "Create new Gauge Project" - Ctrl+Shift+P.
It created a default spec example.spec with vowel count. 
when Run scenario was excuted below error 

running tool: gauge run xxx\specs\example.spec:20 --simple-console --hide-suggestion
'"C:\Python27\python.exe -m pip install getgauge==0.3.7 --user"' is not recognized as an internal or external command,

### What command(s) did you run when you found the bug?

**Run scenario** was clicked.
Below error was

ruunning tool: gauge run xxx\specs\example.spec:20 --simple-console --hide-suggestion
'"C:\Python27\python.exe -m pip install getgauge==0.3.7 --user"' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
File "check_and_install_getgauge.py", line 40, in <module>
assert_versions()
File "check_and_install_getgauge.py", line 34, in assert_versions
install_getgauge("getgauge=="+expected_gauge_version)
File "check_and_install_getgauge.py", line 20, in install_getgauge
check_output([" ".join(install_cmd)], shell=True)
File "C:\Python27\lib\subprocess.py", line 223, in check_output
raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '[u'C:\\Python27\\python.exe -m pip install getgauge==0.3.7 --user']' returned non-zero exit status 1
Traceback (most recent call last):

File "start.py", line 9, in <module>
from getgauge import connection, logger, lsp_server, processor
ImportError: cannot import name connection
Error ----------------------------------

[Gauge]
Failed to start gauge API: Runner with pid 18636 quit unexpectedly(exit status 1).

Your Environment Information -----------
	windows, 1.0.6, 2bc49db
	html-report (4.0.8), python (0.3.7), screenshot (0.0.1), spectacle (0.1.3), xml-report (0.2.2)
Error: Tests failed.

### Output, stack trace or logs related to the bug 
On station 

#### Gauge (Output of `gauge -v`)
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
html-report (4.0.8)
python (0.3.7)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.2)

#### Node.js/Java/Python/.Net/Ruby version
python 2.7

#### Operating System information
WIndows 10 1809 (OS build 17763.1098

#### IDE information
VSCode 1.33.0

**Manually command works but not when executed through Run Scenario.**
**C:\Python27\python.exe -m pip install getgauge==0.3.7 --user**
Requirement already satisfied: getgauge==0.3.7 in c:\python27\lib\site-packages (0.3.7)
Requirement already satisfied: redBaron in c:\python27\lib\site-packages (from getgauge==0.3.7) (0.9.2)
Requirement already satisfied: parso in c:\python27\lib\site-packages (from getgauge==0.3.7) (0.7.0)
Requirement already satisfied: ptvsd==4.3.2 in c:\python27\lib\site-packages (from getgauge==0.3.7) (4.3.2)
Requirement already satisfied: grpcio==1.25.0 in c:\python27\lib\site-packages (from getgauge==0.3.7) (1.25.0)
Requirement already satisfied: protobuf>=3.5.2 in c:\python27\lib\site-packages (from getgauge==0.3.7) (3.11.3)
Requirement already satisfied: six in c:\python27\lib\site-packages (from getgauge==0.3.7) (1.14.0)
Requirement already satisfied: futures in c:\python27\lib\site-packages (from getgauge==0.3.7) (3.3.0)
Requirement already satisfied: baron>=0.7 in c:\python27\lib\site-packages (from redBaron->getgauge==0.3.7) (0.9)
Requirement already satisfied: enum34>=1.0.4 in c:\python27\lib\site-packages (from grpcio==1.25.0->getgauge==0.3.7) (1.1.10)
Requirement already satisfied: setuptools in c:\python27\lib\site-packages (from protobuf>=3.5.2->getgauge==0.3.7) (40.6.2)
Requirement already satisfied: rply in c:\python27\lib\site-packages (from baron>=0.7->redBaron->getgauge==0.3.7) (0.7.7)
Requirement already satisfied: appdirs in c:\python27\lib\site-packages (from rply->baron>=0.7->redBaron->getgauge==0.3.7) (1.4.3)
[gauge.txt](https://github.com/getgauge/gauge/files/4487438/gauge.txt)

**gauge.log** content

16-04-2020 14:40:34.285 [Gauge] [DEBUG] Plugin python is already installed.
16-04-2020 14:40:34.286 [Gauge] [DEBUG] Plugin html-report is already installed.
16-04-2020 14:40:34.287 [Gauge] [INFO] Installing required plugins.
16-04-2020 14:40:34.287 [Gauge] [DEBUG] Installing plugin 'screenshot'
16-04-2020 14:40:34.287 [Gauge] [DEBUG] Gathering metadata for screenshot
16-04-2020 14:40:34.291 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/screenshot?l=python&p=html-report,python,spectacle,xml-report&o=windows&a=amd64
16-04-2020 14:40:35.010 [Gauge] [DEBUG] Checking updates...
16-04-2020 14:40:35.014 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/html-report?l=python&p=html-report,python,spectacle,xml-report&o=windows&a=amd64
16-04-2020 14:40:35.753 [Gauge] [DEBUG] Downloading https://github.com/getgauge/gauge_screenshot/releases/download/v0.0.1/screenshot-0.0.1-windows.x86_64.zip
16-04-2020 14:40:36.127 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/python?l=python&p=html-report,python,spectacle,xml-report&o=windows&a=amd64
16-04-2020 14:40:36.536 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/spectacle?l=python&p=html-report,python,spectacle,xml-report&o=windows&a=amd64
16-04-2020 14:40:36.827 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/xml-report?l=python&p=html-report,python,spectacle,xml-report&o=windows&a=amd64
16-04-2020 14:41:11.014 [Gauge] [DEBUG] Installing plugin screenshot 0.0.1
16-04-2020 14:41:11.031 [Gauge] [INFO] Successfully installed plugin 'screenshot' version 0.0.1
16-04-2020 14:41:11.477 [Gauge] [DEBUG] Runner connection error: Runner with pid 11796 quit unexpectedly(exit status 1).
16-04-2020 14:41:11.477 [Gauge] [DEBUG] Error while killing runner: invalid argument
16-04-2020 14:41:11.477 [Gauge] [CRITICAL] Failed to start gauge API: Runner with pid 11796 quit unexpectedly(exit status 1).
16-04-2020 15:04:24.172 [Gauge] [DEBUG] Plugin python is already installed.
16-04-2020 15:04:24.173 [Gauge] [DEBUG] Plugin html-report is already installed.
16-04-2020 15:04:24.436 [Gauge] [DEBUG] Checking updates...
16-04-2020 15:04:24.438 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/html-report?l=python&p=html-report,python,screenshot,spectacle,xml-report&o=windows&a=amd64
16-04-2020 15:04:25.747 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/python?l=python&p=html-report,python,screenshot,spectacle,xml-report&o=windows&a=amd64
16-04-2020 15:04:26.073 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/screenshot?l=python&p=html-report,python,screenshot,spectacle,xml-report&o=windows&a=amd64
16-04-2020 15:04:26.462 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/spectacle?l=python&p=html-report,python,screenshot,spectacle,xml-report&o=windows&a=amd64
16-04-2020 15:04:26.759 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/xml-report?l=python&p=html-report,python,screenshot,spectacle,xml-report&o=windows&a=amd64
16-04-2020 15:04:28.325 [Gauge] [DEBUG] Runner connection error: Runner with pid 472 quit unexpectedly(exit status 1).
16-04-2020 15:04:28.325 [Gauge] [DEBUG] Error while killing runner: invalid argument
16-04-2020 15:04:28.325 [Gauge] [CRITICAL] Failed to start gauge API: Runner with pid 472 quit unexpectedly(exit status 1).
16-04-2020 18:56:39.016 [Gauge] [DEBUG] Plugin python is already installed.
16-04-2020 18:56:39.017 [Gauge] [DEBUG] Plugin html-report is already installed.
16-04-2020 18:56:39.770 [Gauge] [DEBUG] Checking updates...
16-04-2020 18:56:39.772 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/html-report?l=python&p=html-report,python,screenshot,spectacle,xml-report&o=windows&a=amd64
16-04-2020 18:56:40.072 [Gauge] [DEBUG] Runner connection error: Runner with pid 18636 quit unexpectedly(exit status 1).
16-04-2020 18:56:40.072 [Gauge] [DEBUG] Error while killing runner: invalid argument
16-04-2020 18:56:40.072 [Gauge] [CRITICAL] Failed to start gauge API: Runner with pid 18636 quit unexpectedly(exit status 1).

**Comment by nischt** [comment]
Issue is same with latest

**Comment by sriv** [comment]
There have  been new releases for gauge, gauge-vscode and gauge-python. Please try upgrading and let us know if there are still issues.
