### ISSUE TITLE
Unable to connect to plugin Html Report 4.0.10. rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge#1627]
### Describe the bug
When enable_multithreading is set to true, following error is thrown.

### What command(s) did you run when you found the bug?

For e.g. 
```
gauge run specs
```

### Output, stack trace or logs related to the bug 

```sh
Error : exit status 1
unable to kill runner: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:58250: connect: connection refused"
  Failed to initialize suite datastore. Error: rpc error: code = Unavailable desc = transport is closing
  Failed to initialize suite datastore. Error: rpc error: code = Unavailable desc = transport is closing
  Failed to initialize suite datastore. Error: rpc error: code = Unavailable desc = transport is closing
  Failed to initialize suite datastore. Error: rpc error: code = Unavailable desc = transport is closing
  Failed to initialize suite datastore. Error: rpc error: code = Unavailable desc = transport is closing
  Failed to initialize suite datastore. Error: rpc error: code = Unavailable desc = transport is closing
  Failed to initialize suite datastore. Error: rpc error: code = Unavailable desc = transport is closing
  Failed to initialize suite datastore. Error: rpc error: code = Unavailable desc = transport is closing
Error occurred while waiting for plugin process to finish.
Error : exit status 1
Unable to connect to plugin Html Report 4.0.10. rpc error: code = Unavailable desc = transport is closing
```

#### Gauge (Output of `gauge -v`)

```
Gauge version: 1.0.8

Plugins
-------
html-report (4.0.10)
java (0.7.6)
reportserver (0.1.1)
screenshot (0.0.1)
xml-report (0.2.3)
```

#### Operating System information
OSx

**Comment by esvet** [comment]
Hi all. We are facing same issue on differen developer computers again. Gauge runs are working, on all machines, 
BUT the html report isnt' been created and fails and runs end up with:

```
Successfully generated json-report to => /Users/esvet/IdeaProjects/fod-backend-testing/reports/json-report

Error occurred while waiting for plugin process to finish.
Error : exit status 1
Unable to connect to plugin Html Report 4.4.3. rpc error: code = Unavailable desc = error reading from server: EOF

Failed to kill plugin Html Report 4.4.3. os: process already finished
```


Do you have any idea or hint on this? on an apple M3 and MacOS 26.4.1 and gauge setup like this

```
gauge --version
Gauge version: 1.6.30
Plugins
-------
html-report (4.4.3)
java (1.0.1)
json-report (0.5.6)
xml-report (0.5.4)
```


Thanks!

**Comment by chadlwilson** [comment]
This is a generic error - it doesn't tell us anything.

Rather than posting on a 6 years old issue, open a new issue which describes your problem and how to replicate it. If only HTML report is failing, generate a json report and include that. Run with debug logging and look at gauge log.

**Comment by esvet** [comment]
@chadlwilson thank you and sorry for not having created a new issue. Will do as advised next time for sure.

**Comment by chadlwilson** [comment]
It's quite possible there is something the JSON report handles gracefully but the html report does.not. But no-one is ever able to report the issue with enough detail to figure it out, so it never gets resolved :(

**Comment by esvet** [comment]
Gauge.log was the place to check, and just the right hint. With only looking into the run log 99,99% of the time one gets blind sooner or later for other logs^^ A critical was logged there from html plugin. It turned out to be a misconfiguration in the repo, say a copy paste from the old project, and its props, into the new one, and some gauge property which was set but the data it needed, to customize the report,,, not in place. After its cleanup it worked back again properly. cheers, e.
