### ISSUE TITLE
Re-Evaluate Use of Apache Software License

### ISSUE THREAD

**Issue by zgramana** [getgauge/gauge#1628]
We planned to use Gauge to test a project I am working on. The team was very excited, as Gauge is a very good fit for our needs. However, we are now unable to continue on with Gauge due to the perceived risk presented by its use of GPL 3.0.

I am not a lawyer, nor am I suggesting there is or isn't a genuine risk presented by the GPL (or any other copyleft license).

Given that many years have passed since it was [last discussed here](https://github.com/getgauge/gauge/issues/185), I hope there may now be a willingness to re-license under the Apache 2.0 license (or other non-copyleft license such as MIT/X11 or 3-clause BSD).

Gauge is a fantastic project, and aligned with how test automation frameworks ought to be built. The license is the only thing preventing our adoption of it. I would love the ability to introduce it as the standard test automation tool at our corporation.

**Comment by zabil** [comment]
Thanks for bringing this up.
We've started moving Gauge and it's plugins to Apache 2.0 license. For e.g.
https://github.com/getgauge/gauge-java/pull/427
https://github.com/getgauge/gauge-java/pull/427

It will be done by the end of this month,

**Comment by zgramana** [comment]
That’s fantastic news, thanks!
