### ISSUE TITLE
Support for Executing specs through an API message call

### ISSUE THREAD

**Issue by prateekbaheti** [getgauge/gauge#165]
This will provide IDE plugins with a much more structured execution result instead of depending on the console output.

**Comment by sriv** [comment]
#783 should allow IDEs to consume JSON and report. gRPC [does not work](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000487684-Using-grpc-dependencies-in-plugin-gives-errors) well with Intellij, hence ditching it.
