### ISSUE TITLE
ImportError: cannot import name 'connection' from 'getgauge'

### ISSUE THREAD

**Issue by 1160545** [getgauge/gauge#1659]
![Screenshot (659)](https://user-images.githubusercontent.com/38073344/83356527-73152e80-a384-11ea-92cf-3df825923785.png)

### What command(s) did you run when you found the bug?

For e.g. 
```
gauge run specs
```

**Comment by 1160545** [comment]
i am getting this error when i am running run spec command.

**Comment by sriv** [comment]
Please fill in the issue template with information so that we can suggest what you could try.

**Comment by 1160545** [comment]
Versions
Gauge (Output of gauge -v)
gauge version: 1.0.6
python: 0.3.7
html-report: 4.0.8

**Comment by 1160545** [comment]
please help me to find why I am getting connection error and API error.

**Comment by sriv** [comment]
Can you please try upgrading to latest gauge/plugins?

gauge 1.0.8 has been out for sometime - https://github.com/getgauge/gauge/releases/tag/v1.0.8
and gauge-python' latest version is `0.3.9` - https://github.com/getgauge/gauge-python/releases/tag/v0.3.9
html-report - https://github.com/getgauge/html-report/releases/tag/v4.0.11

**Comment by 1160545** [comment]
Error is resolved thank you so much.

**Comment by sriv** [comment]
Glad this is sorted. Closing the issue.
