### ISSUE TITLE
Get rid of orphan gauge processes

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#166]
_From @sriv on October 28, 2014 6:42_

If Visual Studio is killed or crashes, the child `gauge` processes are orphaned. These need to be killed.

_Copied from original issue: getgauge/gauge-visualstudio#1_

**Comment by sriv** [comment]
There is check to gracefully kill child processes from within the runner. Unfortunately, at least in windows there is no easy way [AFAIK] to register a child process to be killed when parent dies, unless there is an explicit "kill process tree" instead of "kill process". 

Suggestions welcome.

**Comment by sriv** [comment]
_From @navaneeth on June 26, 2015 7:12_

You do this the other way. When Gauge starts, it gets the parent's pid. And keep looking whether the pid is available. If not, it can exit itself. This can be controlled via a command line flag so that it is applicable only when required.

**Comment by mahendrakariya** [comment]
We should take a look at this article. It could be relevant here.
https://medium.com/@felixge/killing-a-child-process-and-all-of-its-children-in-go-54079af94773

**Comment by navaneeth** [comment]
@mahendrakariya That article won't help. The approach said in that article works if you have control to trigger the terminate on child process. In this case, gauge parent process itself died making the child go orphan. AFAIK, there is no better way to fix other than the one that was suggested. Rather than relying on PID, which could be reused in some operating systems, you could make a ping API on the gauge core which the runner can keep pinging and if the ping fails, it can exit.

**Comment by mahendrakariya** [comment]
That's a nice idea @navaneeth. I agree with you. We should do that.

**Comment by Thunderforge** [comment]
I should point out that this issue also affects installing a new version of Gauge. During the installation, the user is shown an error message involving "gauge.exe":

![image](https://cloud.githubusercontent.com/assets/6200170/11047493/57581c5a-86f8-11e5-83e8-0ce155d554da.png)

Opening up task manager and killing each process for `gauge.exe`, then clicking "Retry", is a workaround, but it should not be necessary to do this.

**Comment by kashishm** [comment]
It was also happening with Intellij on Linux, Mac and Windows.
After @mahendrakariya's commit, it is fixed on Linux and Mac but not for windows.

**Comment by navaneeth** [comment]
This is not working because the implementation uses `getppid` which is not implemented for Windows.

**Comment by mahendrakariya** [comment]
Looks like it's [implemented (in syscall_windows.go)](https://github.com/golang/go/blob/release-branch.go1.5/src/syscall/syscall_windows.go#L960) in golang 1.5.

We have asked the broader community for some help. Here's the thread. https://groups.google.com/forum/#!topic/golang-nuts/p-H5ODtTXIw

**Comment by mahendrakariya** [comment]
Tested on Windows 8.1 and Windows 7 with both VS and IntelliJ. If the IDE gets killed, gauge daemon is also terminated within 1 second.
