### ISSUE TITLE
Command 'Gauge: create new specification' resulted in an error 

### ISSUE THREAD

**Issue by 1160545** [getgauge/gauge#1663]
I am getting this error when I am trying to create a new specification in vs code. 
Gauge version:1.0.8
Python:(0.3.9)

**Comment by sriv** [comment]
what is the error you are seeing? Please provide details in the issue you raise, it's hard to investigate otherwise.

I am able to open a new gauge-python project, create specs, and add implementation.

**Comment by NivedhaSenthil** [comment]
Feel free to reopen if you can get more details.
