### ISSUE TITLE
gauge.customScreenshotWriter doesn't get screenshot

### ISSUE THREAD

**Issue by wyatt-z** [getgauge/gauge#1664]
### Describe the bug

1. Create a new gauge project in vscode by "Gauge: Create new Gauge Project", then choose js template.
2. Run the example.spec from vs code.
3. Make the test fail.
4. Get the message: "[DEPRECATED] gauge.screenshotFn will be removed soon, use gauge.customScreenshotWriter instead."
5. Replace "gauge.screenshotFn" with "gauge.customScreenshotWriter" in step_implementation.js
6. Run the example again.
7. Get this message: "Failed to read screenhsot open e:\workspace\taiko_example\\.gauge\screenshots/00D7TPB0qUYAAAAAElFTkSuQmCC: The system cannot find the file specified."
8. No screenshot in .gauge\screenshots

### What command(s) did you run when you found the bug?

For e.g. 
```
gauge run specs
```

#### Gauge (Output of `gauge -v`)
Gauge version: 1.1.0
Commit Hash: 19ce9be

Plugins
-------
html-report (4.0.11)
js (2.3.11)
screenshot (0.0.1)  
spectacle (0.1.4)

**Comment by zabil** [comment]
Please share your implementation of `gauge.customScreenshotWriter`

This works for me

```
// Return a screenshot file name
gauge.customScreenshotWriter = async function () {
  const screenshotFilePath = path.join(process.env['gauge_screenshots_dir'],
    `screenshot-${process.hrtime.bigint()}.png`);

    await screenshot({ path: screenshotFilePath });
    return path.basename(screenshotFilePath);
};
```

**Comment by wyatt-z** [comment]
/*
gauge.screenshotFn = async function() {
    return await screenshot({ encoding: 'base64' });
};
*/

gauge.customScreenshotWriter = async function() {
    return await screenshot({ encoding: 'base64' });
};
This is my code, I just change 'screenshotFn' to 'customScreenshotWriter'.

**Comment by zabil** [comment]
There's been a change in how the new screenshots are handled please modify the code accordingly refer https://docs.gauge.org/writing-specifications.html?os=windows&language=javascript&ide=vscode#taking-custom-screenshots

For more info.
