### ISSUE TITLE
Ability of Gauge to be able to call steps from DLL

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/gauge#1671]
Hello - I think i opened a ticket for this long back but i could not find that ticket. Basically we have our own DLL's in which we would like to define some commonly used steps across projects for users to standardize and make more reusability.

Is Gauge now able to call steps present in dll? Please advise.

gauge -v
Gauge version: 1.0.7
Commit Hash: ed7b4fd6

Plugins
-------
dotnet (0.1.3)
html-report (4.0.9)
json-report (0.3.3)
screenshot (0.0.1)

**Comment by sriv** [comment]
hi @manavghaigithub , I believe you are referring to getgauge/gauge-dotnet#63

Loading steps from DLL is now supported via https://github.com/getgauge/gauge-dotnet/pull/64. Please try and pass any feedback.
