### ISSUE TITLE
Gauge not working with Microsoft's System.Data.SqlClient

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/gauge#1673]
I created a brand new dotnet project and included System.Data.SqlClient in it. I am getting error message:

Failed to initialize suite datastore. Error: rpc error: code = Unknown desc = Exception was thrown by handler.
Unable to connect to plugin Html Report 4.0.9. rpc error: code = Unavailable desc = transport is closing

Steps to reproduce:
1. Create a new project using "gauge init dotnet"
2. Include package "<PackageReference Include="System.Data.SqlClient" Version="4.8.1" />" in .csproj file
3. Run dotnet build
4. Open example.spec and click Run Specs.
5. Gauge throws error message as mentioned above

----------------------------------------------------------------
dotnet --version
3.1.102
----------------------------------------------------------------

----------------------------------------------------------------
Gauge -v
Gauge version: 1.0.7
Commit Hash: ed7b4fd6

Plugins
-------
csharp (0.10.5)
dotnet (0.1.3)
html-report (4.0.9)
java (0.7.2)
json-report (0.3.3)
screenshot (0.0.1)
xml-report (0.2.3)
----------------------------------------------------------------

**Comment by sriv** [comment]
Please see https://github.com/getgauge/gauge-dotnet/issues/80#issuecomment-618837470
