### ISSUE TITLE
Unable to debug Gauge tests in IntelliJ IDE

### ISSUE THREAD

**Issue by varsha-varadarajan** [getgauge/gauge#1677]
### Describe the bug
I have been trying to debug Gauge tests through IntellJ. I get the error 
```
Error running '': Unable to open debugger port (localhost:52148): java.net.ConnectException "Connection refused: connect"
```

### Versions
Gauge IntelliJ Plugin version - 0.3.21

#### Gauge (Output of `gauge -v`)
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
html-report (4.0.8)
java (0.7.3)
screenshot (0.0.1)
xml-report (0.2.2)

#### Node.js/Java/Python/.Net/Ruby version
JDK 11

#### Operating System information
Windows 10 Enterprise 1809

#### IDE information
IntelliJ Version - Community Edition 2020.1.2

**Comment by sriv** [comment]
hi - your gauge/plugin versions are quite old. Is there a reason you need to stick to older gauge/gauge-java versions?

**Comment by varsha-varadarajan** [comment]
Hi, I guess, because that was used in my organization, I stuck to that. 
Also I have now move to the newest version. The issue still persists

Here's the version info - 
```
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
html-report (4.0.11)
java (0.7.8)
screenshot (0.0.1)
xml-report (0.2.2)
```

**Comment by sriv** [comment]
Can you try something please:

- set `GAUGE_DEBUG_OPTS=<port>` where `port` is something that is not blocked/reserved on your local. I used `12345`
- run your project from the terminal. it should print out that the gauge-java process is waiting for a debugger to attach at `12345`
- open Intellij, open the project, and choose `Attach to process`
- the project should show up in intelllij's list of processes it can attach.

Another thing to try :

create a new gauge project and check if debugging works (this will help identify if the problem is with the installation/machine or with the project's settings.

**Comment by sriv** [comment]
@varsha-varadarajan - is this still an issue? did the above steps help in any way?

**Comment by varsha-varadarajan** [comment]
It works with a new project, so, I'm guessing the issue is with my project settings. Thanks for the support!

**Comment by RajatNair** [comment]
> Error running '': Unable to open debugger port : java.net.ConnectException "Connection refused: connect"

Facing similar error with IntelliJ Ultimate edition when I try to debug a spec using IntelliJ's Gauge plugin - 
![image](https://user-images.githubusercontent.com/3319907/87780300-0f6b9580-c84c-11ea-83f9-d02e14031984.png)


Tried with Gauge 1.1.1 and 1.0.8 - 

```JSON
{
    "version": "1.0.8",
    "commitHash": "28617ea",
    "plugins": [
        {
            "name": "csharp",
            "version": "0.10.6"
        },
        {
            "name": "html-report",
            "version": "4.0.12"
        },
        {
            "name": "java",
            "version": "0.7.8"
        },
        {
            "name": "js",
            "version": "2.3.12"
        },
        {
            "name": "python",
            "version": "0.3.10"
        },
        {
            "name": "ruby",
            "version": "0.5.3"
        },
        {
            "name": "screenshot",
            "version": "0.0.1"
        },
        {
            "name": "spectacle",
            "version": "0.1.4"
        },
        {
            "name": "xml-report",
            "version": "0.2.3"
        }
    ]
}
```


> Can you try something please:
> 
> * set `GAUGE_DEBUG_OPTS=<port>` where `port` is something that is not blocked/reserved on your local. I used `12345`
> * run your project from the terminal. it should print out that the gauge-java process is waiting for a debugger to attach at `12345`
> * open Intellij, open the project, and choose `Attach to process`
> * the project should show up in intelllij's list of processes it can attach.
> 
> Another thing to try :
> 
> create a new gauge project and check if debugging works (this will help identify if the problem is with the installation/machine or with the project's settings.

The only way I can debug is setting `GAUGE_DEBUG_OPTS=<port>` and then using IntelliJ's remote debugging configuration template. But it's valid only for single spec run. Have to re-do these steps over for next spec run.
