### ISSUE TITLE
How to run gauge specs without project and just binaries

### ISSUE THREAD

**Issue by preetipadalia** [getgauge/gauge#1678]
Hi,

Is there a way to run gauge spec files without dotnet project but with binaries of the project.

**Comment by sriv** [comment]
You can set `GAUGE_CUSTOM_BUILD_PATH` to point to the location of the built binaries. However you will still need the spec files, properties, environment and manifest file.

**Comment by preetipadalia** [comment]
@sriv thank you for your reply. so this property we have to give in default.properties file?

**Comment by sriv** [comment]
Yes, either as a property or an environment variable that is visible to gauge.

**Comment by ayankumaar** [comment]
I have published a gauge project as a single exe. When I am trying to run tests from the published exe it is unzipping everything inside **AppData\Local\Temp\.net\** and running everything from there. Before publishing as a single exe I have inserted the **env folder, specs directory and manifest file** inside the bundle **(i.e. inside the published exe)**.

I have set the **GAUGE_CUSTOM_BUILD_PATH** as an environment variable. The location of  GAUGE_CUSTOM_BUILD_PATH is inside  **AppData\Local\Temp\.net\**  where it is unzipping everything. I have checked that directory; manifest, env and spec files are present there.

But, I haven't copied the **.csproj** file there. As per my understanding if I set the GAUGE_CUSTOM_BUILD_PATH then I don't need to build my project. So, I haven't bundled the **.csproj** file. However, if I try to run the tests from the bundled exe it keeps me giving the following error:
**System.IO.FileNotFoundException: Could not find file C:\Users\XXXX\AppData\Local\Temp\.net\MyProject\abceef.jhi\MyProject.csproj'**

**Should I copy the .csproj file inside the bundle ?**

Even if I copy the .csproj file inside the bundle it keeps giving me the following error
**System.BadImageFormatException: Bad IL format**.

**Any hint why I am getting System.BadImageFormatException ?**

FYI I am using

Gauge version: 1.0.8
Plugins
-------
dotnet (0.1.4)
html-report (4.0.8)
screenshot (0.0.1)

My gauge project is built using .net core 3.1

Any reply on this issue will be highly appreciated.
