### ISSUE TITLE
Environment variable substitution doesn't check properties files

### ISSUE THREAD

**Issue by opursail** [getgauge/gauge#1679]
### Describe the bug
Properties defined in env/default cannot use substitutions from properties defined an environment (e.g.  env/foo) 

For example: We want to define property templates in default and have values substituted for each environment the specs are executed in  

E.g. 
env/default/global.properties
```
TEMPLATE=something.${MYVAR}
```
env/foo/some.properties
```
MYVAR=testing
```

When you run with --env foo you would expect the property TEMPLATE to resolve to "something.testing"

However you get the error below 
```
'MYVAR' env variable was not set
```

The issue is due to the function below never checking against the properties already loaded from properties files (envVars) and only checking the system environment variables 
```
func substituteEnvVars() error {
	for name, value := range envVars {
		contains, matches := containsEnvVar(value)
		// if value contains an env var E.g. ${foo}
		if contains {
			for _, match := range matches {
				// check if match is from properties file
				// if not, get from system env
				envKey, property := match[0], match[1]
				// error if env property is not found
				if !isPropertySet(property) {
					return fmt.Errorf("'%s' env variable was not set", property)
				}
				// get env var from system
				propertyValue := os.Getenv(property)
				// replace env key with property value
				value = strings.Replace(value, envKey, propertyValue, -1)
			}
			// overwrite the envVar value
			envVars[name] = value
		}
	}
	return nil
}
```

I can submit a PR with tests to fix this issue

### What command(s) did you run when you found the bug?

```
gauge run specs --env foo
```

### Output, stack trace or logs related to the bug 
gauge run --env foo specs
Error ----------------------------------

'MYVAR' env variable was not set

Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
        windows, 1.0.6
        go (0.1.2), html-report (4.0.8), java (0.7.2), python (0.3.5), screenshot (0.0.1), spectacle (0.1.3), xml-report (0.2.1)

### Versions 

Issue is present in current code base 

#### Gauge (Output of `gauge -v`)
gauge -v
Gauge version: 1.0.6

Plugins
-------
go (0.1.2)
html-report (4.0.8)
java (0.7.2)
python (0.3.5)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)

#### Node.js/Java/Python/.Net/Ruby version
NA
#### Operating System information
NA
#### IDE information
NA

**Comment by zabil** [comment]
@opursail A PR to fix this will be great.

It might also solve an earlier issue that was reported around something similar https://github.com/getgauge/gauge/issues/1428

**Comment by opursail** [comment]
Yes it would solve the issue for #1428  without changing the existing syntax

Example 
```
service_url=http://service.com
api_url=${service_url}/api/endpoint
```
