### ISSUE TITLE
Unable to run specs in Linux environment, framework dll is unable to load

### ISSUE THREAD

**Issue by gvreddy1265** [getgauge/gauge#1681]
**Background:** Env: Linux
Test project (c#) has a nuget package reference which is a framework project. This would be the entry point of the test.
I have installed dotnet 3.1 sdk, gauge and gauge dotnet plugin.

**$ gauge --version**
Gauge version: 1.0.7
Commit Hash: 6f6a148

Plugins
-------
dotnet (0.1.4)

I am able to get the specs:

**$ gauge list --specs Specs**

Telemetry
---------

This installation of Gauge collects usage data in order to help us improve your experience.
The data is anonymous and doesn't include command-line arguments.
To turn this message off opt in or out by running 'gauge telemetry on' or 'gauge telemetry off'.

Read more about Gauge telemetry at https://gauge.org/telemetry

[Specifications]
New Customer Specification
Sample Specification

**$ gauge run Specs/SampleSpecs.spec**

Telemetry
---------

This installation of Gauge collects usage data in order to help us improve your experience.
The data is anonymous and doesn't include command-line arguments.
To turn this message off opt in or out by running 'gauge telemetry on' or 'gauge telemetry off'.

Read more about Gauge telemetry at https://gauge.org/telemetry

Installing required plugins.
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
**System.IO.FileNotFoundException: Could not load file or assembly 'ABC_CORE, Version=1.0.25.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.**

Please advice what I am missing.

**Comment by sriv** [comment]
hi - there is not enough information for me to comment. Can you please see if you are able to replicate this issue in a sample project?

**Comment by gvreddy1265** [comment]
Hi @sriv I am able to successfully run gauge tests with sample project locally in windows machine. Test project is built using .netcore 3.1.
The problem that I am facing is - unable to run specs in linux os due to above issue.

**Comment by sriv** [comment]
I'm afraid there is not much we can do, without actually seeing the failure ourselves. Without a sample to replicate, we can only speculate. Perhaps your reference project is not built for cross platform execution?

**Comment by sriv** [comment]
closing this, since there isn't enough detail for us to investigate further - feel free to comment with details.
