### ISSUE TITLE
[Urgent]@getgauge/cli v1.1.1 at NPM is not working on Windows

### ISSUE THREAD

**Issue by shane51** [getgauge/gauge#1683]
### Describe the bug
After npm install @getgauge@1.1.1

gauge under \cli\bin\ is 0 byte,  and cannot run on windows 10

same issue with https://github.com/getgauge/gauge/issues/1666

### What command(s) did you run when you found the bug?

For e.g. 
```
gauge run specs
```

#### Gauge (Output of `gauge -v`)
gauge v1.1.1

#### Node.js/Java/Python/.Net/Ruby version
Node V12.18.1
#### Operating System information
Windows 10 1909

**Comment by sriv** [comment]
this is strange. I just created a sample project to install gauge on windows using `npm install @getgauge/cli` and it seems to work.

Please see this run: https://github.com/sriv/gauge-npm-install-demo/runs/826520193?check_suite_focus=true#step:2:27

The code : https://github.com/sriv/gauge-npm-install-demo/blob/master/.github/workflows/gauge.yml#L12-L13

**Comment by shane51** [comment]
I was installing gauge behind proxy (From client's network), not sure if it is caused by network issue.

Finally I installed it from the source.

But I'm thinking that if there is any network issues happens, will gauge@1.1.1 provide correct information?

From the info I got, seems no error messages provided, but installation might be failed.

**Comment by sriv** [comment]
if you are behind a network proxy, you will have to configure `HTTP_PROXY` environment variable to allow gauge and the installers to access the internet.

Please see https://docs.gauge.org/configuration.html#with-authentication for an example.

> But I'm thinking that if there is any network issue happens, will gauge@1.1.1 provide correct information?

In theory, yes (see: https://github.com/getgauge/gauge/blob/master/build/npm/src/index.js#L22). When I turn off my internet, npm installs from my cache, but it throws a warning:

```
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/superagent failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
```

If you see an error, and it's not obvious - please do share the console log.

**Comment by sriv** [comment]
closing this - feel free to comment if issue persists.
