### ISSUE TITLE
table parameter 'table: /data/*.csv' does not work in MAC system

### ISSUE THREAD

**Issue by manasi-rk** [getgauge/gauge#1690]
### Describe the bug
Installed Gauge for js and created a new project. The default templates runs the spec successfully.
Now when I tried pulling a repository from our VCS, that project does not enable gauge. 
Tried running through terminal - gauge run specs - it gives the following error

Also the peeks like 'Run Scenario | Debug Scenario' etc are not visible.

Things tried:
- Added Gauge to the environment variable 'Path'

- Set the .spec and .cpt files to Gauge as described here
https://github.com/getgauge/gauge-vscode/blob/master/README.md#troubleshooting

- Created new repository and deleted old one

- Restarted the system

Also this same project works on my colleagues windows system.
 

### What command(s) did you run when you found the bug?
gauge run specs

## Gauge version
Gauge 1.1.1

### Output, stack trace or logs related to the bug 

Error Message:
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/46588493/87305365-015c0300-c534-11ea-9788-36ad58f18d81.png)

#### Node.js/Java/Python/.Net/Ruby version
Node.js v10.16.3

#### Operating System information
Mac OS Catalina 10.15.5 

#### IDE information
VS Code 1.38.1

**Comment by manasi-rk** [comment]
The issue has been resolved with following changes.
the testcase is using a csv file to send data

table: /data/ABC.csv

this works fine in windows but in MAC systems the data is to be passed as

table: data/ABC.csv

the issue due to '/' has resolved. Tried in windows system without a backslash and it still works. but this is not the same in Mac system. This should be mentioned in the documentation. which has only following info

![image](https://user-images.githubusercontent.com/46588493/87448501-9258da00-c619-11ea-8ad7-1a0962edf3d5.png)

This change should be explicitly written in the documents.

**Comment by sriv** [comment]
Glad you sorted this out.

Note that the filepath `/system/users.csv` is a valid *absolute* file path for macOS/linux. Gauge supports absolute path for csv files. 

> This change should be explicitly written in the documents.
Not sure about this, this issue has nothing to do with gauge, rather it's OS specific path format. Nevertheless, if this is worth being explicit, please feel free to send a pull request against https://github.com/getgauge/docs.gauge.org/blob/master/execution.rst
