### ISSUE TITLE
Gauge 1.1.1 in intelliJ IDE claims it cannot run with java 1.8 or use gauge-java 0.7.4 but picks latest java plugin

### ISSUE THREAD

**Issue by madhavabk** [getgauge/gauge#1691]
### Describe the bug
Installed Gauge 1.1.1 and configured a plug-in in IntelliJ IDE.
The execution fails with error message

D:\software\Gauge1.1.1\bin\gauge.exe run --machine-readable --hide-suggestion --simple-console D:/specs/Dev.spec:125
This version of gauge-java plugin does not support Java versions < 1.9
Please upgrade your Java version or use a version of gauge-java <= v0.7.4
Error occurred while waiting for runner process to finish.
Error : exit status 1

### What command(s) did you run when you found the bug?
```
D:\software\Gauge1.1.1\bin\gauge.exe run --machine-readable --hide-suggestion --simple-console D:/specs/Dev.spec:125
```

### Output, stack trace or logs related to the bug 
D:\software\Gauge1.1.1\bin\gauge.exe run --machine-readable --hide-suggestion --simple-console D:/specs/Dev.spec:125
This version of gauge-java plugin does not support Java versions < 1.9
Please upgrade your Java version or use a version of gauge-java <= v0.7.4
Error occurred while waiting for runner process to finish.
Error : exit status 1

### Versions 
C:\>gauge -v
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
html-report (4.0.12)
java (0.7.4)
json-report (0.3.3)
screenshot (0.0.1)
xml-report (0.2.3)

#### Gauge (Output of `gauge -v`)
C:\>gauge -v
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
html-report (4.0.12)
java (0.7.4)
json-report (0.3.3)
screenshot (0.0.1)
xml-report (0.2.3)

#### Node.js/Java/Python/.Net/Ruby version
Java

#### Operating System information
Windows 10

#### IDE information
IntelliJ Community

**Comment by sriv** [comment]
Are you using a build tool (maven or gradle) - if you do please check what version of `gauge-java` is added as a dependency. It should be `0.7.4`

Java 1.8 has been announced to have "End of Public Updates", and it is recommended that users upgrade to a later version. While you may have your reasons to use an older jdk version, gauge does not support platforms that are not supported by the vendors themselves.

For example, if there's a bug in older versions of gauge, you'll have to update the plugin to receive the fix, and that would automatically make it incompatible with JDK 1.8.

**Comment by madhavabk** [comment]
Using Maven and using 0.7.4 itself.

<dependency>
            <groupId>com.thoughtworks.gauge</groupId>
            <artifactId>gauge-java</artifactId>
            <version>0.7.4</version>
        </dependency>

**Comment by madhavabk** [comment]
till that time where do i get old installer?

**Comment by sriv** [comment]
old installers of gauge and plugins can be found in the releases.

ex: https://github.com/getgauge/gauge/releases lists all releases of gauge. 

Is this what you seek?

**Comment by madhavabk** [comment]
i kind of moved back to older IntelliJ, Gauge 1.0.8 and gauge-java older version with older java 1.8 it works.
but why this new release is not working fine?

**Comment by NivedhaSenthil** [comment]
Can you please be specific on what issue you are facing with the new version ? Like @sriv mentioned gauge-java does not support java1.8 any more.

**Comment by zabil** [comment]
Closing this as Gauge 1.1.1 does not work for Java 1.8 If you are using with the latest version of IntelliJ check JDK settings to pick up the latest version of Java

**Comment by madhavabk** [comment]
i happened to see that Gauge installed some things into C:\Users\xxxxx\AppData\Roaming\gauge\plugins
while from IntelliJ when i had given GAUGE_HOME as my installation path which is D:\Gauge111
That might be the cause for saying that its not finding the plug-in and tried installing each time i run and fails.
