### ISSUE TITLE
SetTimer does work in side step

### ISSUE THREAD

**Issue by bimalviswam** [getgauge/gauge#1692]
### Describe the bug

setInterval() does not seem to be working from steps.

Same code when I tried without gauge works .  I have created a project to demo this. the project actually has to print "hello world"  every 1 sec for a duration of 5 seconds . But it does not wait for setInterval. If we execute the code without 

Here is the project -https://github.com/bimalviswam/gaugeTimer

### What command(s) did you run when you found the bug?

to run with gauge - Run "npm install" and then "gauge run specs"
to run without gauge - cd into the project and then  "node ./tests/withOutGauge.js"

```

### Output:

setInterval function is not respected and gauge completes the execution without any out put


#### Gauge (Output of `gauge -v`)

Gauge version: 1.0.6

Plugins
-------
html-report (4.0.8)
js (2.3.6)
json-report (0.3.2)
screenshot (0.0.1)

#### Node.js/Java/Python/.Net/Ruby version
node - 12.14.4
#### Operating System information
Mac Mojave
Version 10.14.6

#### IDE information
VsCode 1.46.1

**Comment by sriv** [comment]
answered here: https://spectrum.chat/gauge/general/setinterval-from-step-is-not-respected~7ee1391b-9288-41d0-a340-cd2a0792e67e?m=MTU5NDgzNjMzNjcwOA==
