### ISSUE TITLE
Does the spec step of Gauge consider adding conditional judgments? example: If you are not logged in, then the Run login scenario If you are already logged in, skip the login scenario

### ISSUE THREAD

**Issue by jennyjane** [getgauge/gauge#1695]
### Describe the bug
Does the spec step of Gauge consider adding conditional judgments

for example:
If you are not logged in, then the Run login scenario
If you are already logged in, skip the login scenario

**Comment by NivedhaSenthil** [comment]
Don't think there is any specific way in Gauge can do this. But this use case can be easily achieved by handling conditions in step implementations I believe. For this particular case on Login scenario have you tried using [hooks](https://docs.gauge.org/writing-specifications.html#id12) ? Logging in beforeScenario or beforeSpec might solve this case.
