### ISSUE TITLE
Support for parameter transformers

### ISSUE THREAD

**Issue by tlempart** [getgauge/gauge#170]
Look at https://github.com/cucumber/cucumber/wiki/Step-Argument-Transforms .

In my case I need to replace some variables in file parameter (not only), e.g.:

```
{
   "javaHome": "${env.JAVA_HOME}"
}
```

should be replaced to

```
{
   "javaHome": "/usr/share/java ..."
}
```

based on environment variables. The cleanest way would be to use something similar to mentioned transformes.

**Comment by zabil** [comment]
Closing this. Prefer environment variables to be handled in code instead.
