### ISSUE TITLE
Viewing Reports from VS Code: "Gauge" Show last run report" not working

### ISSUE THREAD

**Issue by davebneufeld** [getgauge/gauge#1702]
### Describe the bug

When Following the Tutorial at 
https://docs.gauge.org/getting_started/view-a-report.html?os=windows&language=javascript&ide=vscode

I cannot get a browser to open with the "Show Last Run Report" command.
Nothing happens. No error messages in console or any where else that I can determine.

Steps attempted to resolve the issue with no success.
1. Followed standard install instructions.
2. uninstalled Plugin and reinstalled.
3. Uninstalled VSCode and reinstalled.
4.  Uninstalled VSCode, and removed removed all vscode extensions then reinstalled and then Gauge and Taiko.
5.  Changed Browser default back to Windows Edge from Google Chrome.

Time spent: 1.5 hours.

My assupmption is that I am doing something wrong, but I have no more ideas.
### What command(s) did you run when you found the bug?

In the editor’s command palete type Gauge: Show Last Run Report to view the report in the browser.

### Output, stack trace or logs related to the bug 
No Logs

### Versions 
v.0.0.14

#### Gauge (Output of `gauge -v`)

PS C:\Users\micro\Documents\Gauge\webview\gauge-tests> gauge -v
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
html-report (4.0.12)
js (2.3.12)
screenshot (0.0.1)

#### Operating System information
Windows 10 Latest.
Chrome: latest

#### IDE information
Visual Studio Code: latest;

**Comment by BugDiver** [comment]
@davebneufeld This usually happens when there is no last run available. Please try executing spec and then check the reports.
