### ISSUE TITLE
Add option to fail when specs are skipped due to validation error

### ISSUE THREAD

**Issue by F7502** [getgauge/gauge#1707]
As I understand from reading previous issues and from the documentation the desired behavior of Gauge is to **not** fail the execution in case there are validation errors like a missing step implementation. The affected specs are simply skipped.

This is not always optimal. In a recent project we had some typos in some test steps and then they were skipped when running the tests in our CI pipeline (because there was no test step implementation found). Unfortunately, there were some bugs that we missed due to the silently skipped tests :-(

Would it make sense to add a configuration option to Gauge to change this behavior as needed? Something like `failOnValidationErrors = true`?

**Comment by NivedhaSenthil** [comment]
This seems a valid feature. Thanks for the suggestion... we will look at supporting this

**Comment by F7502** [comment]
Thanks for the fast response and for considering to support this!

**Comment by BugDiver** [comment]
@F7502 Gauge already has a `validate` command which only performs validation and gives non zero exit code in case of failures.
You can add it in your build pipelines before actually executing the specs and detect the validations errors.

Example:
```
gauge validate specs
```
It shows all the validation errors and exit with non zero code.

Does it help in your scenario?

**Comment by F7502** [comment]
> Does it help in your scenario?

Yes, good point, that helps indeed, thanks :-)
