### ISSUE TITLE
able to open edge driver with gauge but Url is not working in edge driver with selenium in gauge 

### ISSUE THREAD

**Issue by 1160545** [getgauge/gauge#1709]
Stacktrace: 
        WebDriverError: Unknown error
            at parseHttpResponse (node_modules\selenium-webdriver\lib\http.js:582:11)
            at Executor.execute (node_modules\selenium-webdriver\lib\http.js:491:26)
            at processTicksAndRejections (internal/process/task_queues.js:93:5)

const common = require('./common');
const { Builder, By, Key, until } = require('selenium-webdriver')
const {sleep } =  require('/common');
const assert = require('assert');
const path = require('path');
const BROWSER = process.env.BROWSER;
step("close browser", async function() {
    await driver.quit();
});
step("Open browser", async function() {
	common.driver = undefined 
 //common.driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
  common.driver = await new Builder().forBrowser('MicrosoftEdge').build()
 
    vars = {}
   
});

step("valid information", async function() {
    driver= common.driver
    await driver.get("https://xs-onboarding.xenon.work/member-registration?token=XSTestV1.saolonhi39@gmail.com")

**Comment by zabil** [comment]
Closing this issue as it is hard to diagnose without all the sections in the issue template especially without important information like versions etc. 

Will re-open and look after all the sections of the issue template are filled up.
