### ISSUE TITLE
"System.Data.SqlClient is not supported on this platform." error appearing with Gauge.

### ISSUE THREAD

**Issue by preetipadalia** [getgauge/gauge#1711]
### Describe the bug
I am trying to connect to sql db using library System.Data.SqlClient but getting following error. 
"System.Data.SqlClient is not supported on this platform."

Can you please help how can i make this work this with Gauge. 
Same Library is working fine with nunit or normal console application in .net core framework.
### What command(s) did you run when you found the bug?

For e.g. 
```
new SqlConnection(connectionstring);
```

### Output, stack trace or logs related to the bug 
"System.Data.SqlClient is not supported on this platform."

#### Gauge (Output of `gauge -v`)
Gauge version: 1.0.8
Commit Hash: 28617ea

Plugins
-------
dotnet (0.1.4)
html-report (4.0.8)
screenshot (0.0.1)

#### Node.js/Java/Python/.Net/Ruby version
.Net

#### Operating System information
Windows 10

#### IDE information
VScode

**Comment by preetipadalia** [comment]
Any update on this issue. Is there any workaround or solution for this?

**Comment by sriv** [comment]
Thanks for reporting, I am investigating this. 

Some findings reported here: https://github.com/getgauge/gauge-dotnet/issues/85#issuecomment-639343328

**Comment by preetipadalia** [comment]
Hi Sriv,

I can see some commits are done for this issue. Can you please tell when can we expect this update?

Thanks
Preeti

**Comment by sriv** [comment]
hi @preetipadalia - yes, this should be fixed now. Can you try installing gauge-dotnet `0.1.6` and see if it helps?

I verified this by using EntityFramework+sqlite (I don't have access to any other RDBMS instance at the moment).

**Comment by preetipadalia** [comment]
I took the updated plugin but it is behaving weirdly. 
Sometimes getting error as file can not access as it is being accessed by some other file. And if i forcefully kill dotnet process again start debugging getting following error:
Exception thrown: 'System.InvalidOperationException' in System.Linq.dll
Exception thrown: 'Grpc.Core.RpcException' in Gauge.Dotnet.dll
Exception thrown: 'System.Reflection.TargetParameterCountException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Linq.dll
Exception thrown: 'Grpc.Core.RpcException' in Gauge.Dotnet.dll

**Comment by sriv** [comment]
Are you able to execute the project? (i.e. without a debugger attached?)

**Comment by preetipadalia** [comment]
Following error appearing while running without debugging:
Error Message: Sequence contains no matching element
  Stacktrace: 
     at System.Linq.ThrowHelper.ThrowNoMatchException()
     at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
     at Gauge.Dotnet.AssemblyLoader.GetLibType(LibType type)
     at Gauge.Dotnet.ExecutionOrchestrator.GetAllPendingScreenshotFiles()
     at Gauge.Dotnet.ExecutionOrchestrator.BuildResult(Stopwatch stopwatch, ExecutionResult executionResult)
     at Gauge.Dotnet.ExecutionOrchestrator.ExecuteHooks(String hookType, HooksStrategy strategy, IList`1 applicableTags, ExecutionContext context)
     at Gauge.Dotnet.Processors.HookExecutionProcessor.ExecuteHooks(ExecutionInfo info)
     at Gauge.Dotnet.Processors.ExecutionEndingProcessor.Process(ExecutionEndingRequest request)
     at Gauge.Dotnet.RunnerServiceHandler.<>c__DisplayClass29_0.<FinishExecution>b__0()
     at Gauge.Dotnet.RunnerServiceHandler.processAndGetTask[TResult](Func`1 fn)

**Comment by sriv** [comment]
Can you please share a sample project where I can replicate these issues?

**Comment by preetipadalia** [comment]
Getting following errors:

Getting following errors:

C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): error MSB3021: Unable to copy file "C:\Users\user\.nuget\packages\fluentassertions\4.19.4\lib\netstandard1.3\FluentAssertions.Core.dll" to "Sample\gauge_bin\FluentAssertions.Core.dll". The process cannot access the file 'Sample\gauge_bin\FluentAssertions.Core.dll' because it is being used by another process. [Sample\netcore-template.csproj]
C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): error MSB3027: Could not copy "obj\Debug\netcoreapp3.1\win-x64\netcore-template.dll" to "Sample\gauge_bin\netcore-template.dll". Exceeded r
etry count of 10. Failed.  [Sample\netcore-template.csproj]
C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): error MSB3021: Unable to copy file "obj\Debug\netcoreapp3.1\win-x64\netcore-template.dll" to "Sample\gauge_bin\netcore-template.dll". The process cannot access the file 'Sample\gauge_bin\netcore-template.dll' because it is being used by another process. [Sample\netcore-template.csproj]
C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): error MSB3027: Could not copy "C:\Users\user\.nuget\packages\gauge.csharp.lib\0.7.6\lib\netstandard2.0\Gauge.CSharp.Lib.dll" to "Sample\gauge_bin\Gauge.CSharp.Lib.dll". Exceeded retry count of 10. Failed.  [Sample\netcore-template.csproj]
C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): error MSB3021: Unable to copy file "C:\Users\user\.nuget\packages\gauge.csharp.lib\0.7.6\lib\netstandard2.0\Gauge.CSharp.Lib.dll" to "Sample\gauge_bin\Gauge.CSharp.Lib.dll". The process cannot access the file 'Sample\gauge_bin\Gauge.CSharp.Lib.dll' because it is being used by another process. [Sample\netcore-template.csproj]
{"logLevel":"fatal","message":"Unable to build Project in Sample\ndotnet Project build failed.\nRan 'dotnet publish --runtime=win-x64 --configuration=Debug --output=\"Sample\\gauge_bin\"  \"netcore-template.csproj\" --verbosit
y=quiet'\n   at Gauge.Dotnet.GaugeProjectBuilder.BuildTargetGaugeProject()\r\n   at Gauge.Dotnet.StartCommand.TryBuild()"}

**Comment by sriv** [comment]
I've put the sample I used to test here: https://github.com/getgauge-examples/gauge-sqlite-ef-demo

Please try and see if this works for you. Please ensure that you are using the latest gauge-dotnet (>= 0.1.6)

**Comment by preetipadalia** [comment]
ok @sriv . I will check this and let u know.

**Comment by preetipadalia** [comment]
Getting 404 for the project link.
Tested it with my project but getting same issue.

**Comment by zabil** [comment]
https://github.com/getgauge-examples/gauge-sqlite-ef-demo should be accessible now.

**Comment by preetipadalia** [comment]
I have tried with the project given. Debugging failed but run I could do with the project.

While debugging, I Am getting an error as the file is being used by some other process.

I tried by enhancing it by adding hooks from my existing projects and getting error as :
AfterSuite Hook and before suite execution is getting failed .

Error Message: Parameter count mismatch.

**Comment by sriv** [comment]
> Error Message: Parameter count mismatch.

Working on this - https://github.com/getgauge/gauge-dotnet/issues/110

Will investigate debugging.

**Comment by sriv** [comment]
@preetipadalia gauge-dotnet 0.1.7 is out, please try.

It contains fix for `Error Message: Parameter count mismatch.`

I am able to debug the project using gauge-vscode as well (see below):
![gauge-dotnet-debug](https://user-images.githubusercontent.com/389148/92601487-819bac00-f2ca-11ea-97a4-bc83152dcba0.gif)

**Comment by preetipadalia** [comment]
Thanks, I'll test it. One thing I noticed when we open the project in vscode, gauge vscode extension instantiate gauge server, and enable code ens in vscode. in that process, it is blocking those dlls. when I Am trying to use Debug scenario I Am getting' file  is being used' error. But when I kill the dotnet process and then again try Debug its attaching the Debugger.

**Comment by sriv** [comment]
So the chain of events is something like this:

Gauge-Vscode --(onActivation)--> Gauge (LangServer mode) ----> gauge-dotnet ----> Load Target Assembly (via Reflection)

So what you describe is correct. However I don't see that issue myself. If you have any way for me to replicate I can look into it deeper.

I'll close this issue now (the original issue around sqlclient should be addressed). Feel free to create a new issue for debugger with details.
