### ISSUE TITLE
Cannot run Gauge after installing from ZIP file in Mac OS Catalina

### ISSUE THREAD

**Issue by chambois** [getgauge/gauge#1713]
### Describe the bug
Cannot run Gauge after installing from ZIP file in Mac OS Catalina.

Appears related to this issue https://github.com/hashicorp/terraform/issues/23033

We are running Gauge on laptops that we don't have `sudo` access to nor the ability to modify the security settings in the system preferences. 

### What command(s) did you run when you found the bug?

```
gauge run <anything>
```

### Output, stack trace or logs related to the bug 
![image](https://user-images.githubusercontent.com/856565/89478713-1e52c180-d7d4-11ea-92bd-21513ef71623.png)

### Versions 
1.0.7-1.1.1

#### Gauge (Output of `gauge -v`)
![image](https://user-images.githubusercontent.com/856565/89478717-2448a280-d7d4-11ea-99ca-0b647b3c0d3f.png)

#### Node.js/Java/Python/.Net/Ruby version
node v10, v12

#### Operating System information
Mac OS Catalina v 10.15.6

#### IDE information
Command line

**Comment by zabil** [comment]
This works for me

```
$ wget https://github.com/getgauge/gauge/releases/download/v1.1.1/gauge-1.1.1-darwin.x86_64.zip
$ unzip gauge-1.1.1-darwin.x86_64.zip
$ ./gauge --version
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
dotnet (0.1.4)
html-report (4.0.12)
java (0.7.4)
js (2.3.12)
python (0.3.10)
ruby (0.5.3)
screenshot (0.0.1)
spectacle (0.1.4)
ts (0.0.5)
xml-report (0.2.3)

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.5 (Catalina)
BuildVersion:	19F101
```

Alternatively please try

```
brew install gauge
```

**Comment by NivedhaSenthil** [comment]
@chambois any updates ? were you able to get it working ?

**Comment by Thesharing** [comment]
I have the same issue on macOS 10.15.6 Catalina. I run the guage in Finder instead of in terminal. The system asks that whether I want to run the software downloaded from the internet. And then I can run the guage in terminal.
