### ISSUE TITLE
Error while using multiple data tables in single spec

### ISSUE THREAD

**Issue by bholya** [getgauge/gauge#1714]
I am reporting this as bug, as suggested by shrikant. See https://groups.google.com/forum/m/#!topic/getgauge/dXYqv6e_ZvA

Hello, 
I am trying to run simple specification Gauge and Taiko, but getting error

organisation.spec:9 Multiple data table present, ignoring table

------------- SPEC File (Organisation.spec)  ----------------
# Organisationsverwaltung 

table: logindata.csv

* Als Benutzer <users> mit Passwort <pwd> anmelden

## Organisation auswählen 

table: orgdata.csv

* Gehe zu Partnerdaten
* Suche Organisation mit Organisationanummer <Organisationanummer>
* Eine Organisation mit Name <Organisationsname> wird angezeigt
----------------------------------------------------------------

Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
html-report (4.0.12)
java (0.7.9)
js (2.3.12)
screenshot (0.0.1)
spectacle (0.1.4)

---------------------------------------------

Can someone help me on this or any workaround ?

Thanks
Sanjay

**Comment by sriv** [comment]
I now recall that csv tables are not yet supported for scenario datatables. Please see the notes under documentation: https://docs.gauge.org/writing-specifications.html?os=macos&language=javascript&ide=vscode#table-driven-scenario

As a workaround you can inline your scenario table.

**Comment by zabil** [comment]
Gauge won't supporting csv for scenario tables anytime soon. 
The error message should point that out clearly.

**Comment by bholya** [comment]
@zabil : 
Thanks for Information.  
May I know, what are the reasons, not to add this feature in future ? 

I think it is important part of test automation to include data from other sources
(like test data management tool)  also.

**Comment by zabil** [comment]
From the initial look at implementing there is no easy way to implement this technically without spending a lot of effort into development and testing.

Any pull request to implement this feature will be however be welcome (i.e csv data table for table driven scenarios)

> I think it is important part of test automation to include data from other sources
(like test data management tool) also.

Gauge will only support external CSV data tables. Test data management tools can export it to csv and run Gauge tests. This is to make tests deterministic and easy to run on every environment without external dependencies.

**Comment by BugDiver** [comment]
@bholya We have reconsidered this enhancement. Gauge will be adding support for the external scenario table in the next release.

**Comment by bansal63** [comment]
Hi @sriv @BugDiver .

It would be great if documentation also gets updated here.
