### ISSUE TITLE
Could not able to install plugin with gauge install xml-report command.

### ISSUE THREAD

**Issue by manojTest** [getgauge/gauge#1718]
### Describe the bug
Could not able to install plugin with gauge install xml-report command.

Getting:
Failed to install plugin 'xml-report'.
Reason: Invalid plugin. Could not download xml-report-install.json file.

### What command(s) did you run when you found the bug?
gauge install xml-report

For e.g. 
```
gauge run specs
```

#### Gauge (Output of `gauge -v`)
Gauge version: 1.0.8

Plugins
-------
html-report (4.0.10)
java (0.7.4)
screenshot (0.0.1)
spectacle (0.1.4)
#### Node.js/Java/Python/.Net/Ruby version
Java
#### Operating System information
Mac
#### IDE information
Intellij

**Comment by zabil** [comment]
This is working for me on version 

```
$ gauge install xml-report
.......................
Successfully installed plugin 'xml-report' version 0.2.3

$ gauge --version
Gauge version: 1.1.1
Commit Hash: 4be1503c
```

My guess is this is a network issue. If you are behind a corporate proxy please check proxy settings https://docs.gauge.org/configuration.html?os=macos&language=java&ide=vscode#http-proxy-setting-while-using-gauge

**Comment by manojTest** [comment]
I am using home network and not behind any proxy

**Comment by manojTest** [comment]
my other members of the team also facing same issue once though we are on different home network

**Comment by manojTest** [comment]
Please let me know how to check this?

**Comment by zabil** [comment]
Try running the following command.

```
gauge install xml-report --log-level=debug
```

To see what url it is trying to download the plugin from. You should see something like

```
$ gauge install xml-report --log-level=debug
Gathering metadata for xml-report
Downloading https://downloads.gauge.org/plugin/xml-report?l=&p=dotnet,html-report,java,js,python,ruby,screenshot,spectacle,ts&o=darwin&a=amd64
Downloading https://github.com/getgauge/xml-report/releases/download/v0.2.3/xml-report-0.2.3-darwin.x86_64.zip
```

Note the urls. If there are different check the config and make sure they looks something like this

```
$ gauge config --list
Key                             Value                              
------------------------------------------------------------------
check_updates                   true                               
gauge_repository_url            https://downloads.gauge.org/plugin 
gauge_templates_url             https://templates.gauge.org        
runner_connection_timeout       30000                              
plugin_connection_timeout       10000                              
plugin_kill_timeout             4000                               
runner_request_timeout          30000                              
ide_request_timeout             30000     
```

If the url's are outdated update to the new ones as follows

```
$ gauge config gauge_repository_url https://downloads.gauge.org/plugin
$ gauge config gauge_templates_url https://templates.gauge.org
```

**Comment by manojTest** [comment]
Thanks looks like the urls are outdated.
https://downloads.getgauge.io/plugin/xml-report?l=&p=html-report,java,screenshot,spectacle&o=darwin&a=amd64

**Comment by manojTest** [comment]
Thanks a lot it work
