### ISSUE TITLE
Alternative way to quote parameters

### ISSUE THREAD

**Issue by tlempart** [getgauge/gauge#172]
Especially in case of _JSON_ values there is a need to use a large number of double-quotes `"`, e.g.: `{ "parameter1": "value1", "parameter2": "value2" }. If I want to use such *JSON* as parameter, than I have to escape every one`"` character. It would very useful to have possibility to use parameter quotes other than double-quotes, e.g. single quotes.

**Comment by deepthigc** [comment]
One way to do this would be to put this JSON segment in a file and use the (file parameter)[http://getgauge.io/documentation/user/current/specifications/parameters.html] that Gauge supports.

Changing the parameters to support single quotes is one way to achieve this, but I feel having JSON embedded within a step takes away the readability aspect that markdown tries to bring in. 

Thoughts?

**Comment by hakito** [comment]
It would be great if a string quoting like in ruby would be possible.

For example:

```
* I am a step that requires json %#{"key": "value"}# data
* I am a step that requires an array %w[with 3 values] as data
```

**Comment by tk8817** [comment]
I feel like this would be easily solved through the use of regex's similar to cucumber. It would allow for the capturing of data in an un-opinionated fashion.

**Comment by zabil** [comment]
Introducing JSON, string syntax, regexes affects the readability of specification. 
Gauge recommends using special parameters or custom parameters https://github.com/getgauge/gauge/issues/7
