### ISSUE TITLE
Install and first example is painful

### ISSUE THREAD

**Issue by fimbault** [getgauge/gauge#1721]
#Describe the bug
Newcomer here.
On linux, the default suggested install doesn't work (keyserver not responding). Used curl to get around.

Then the default example provided in the documentation doesn't work. 
As described: https://docs.gauge.org/getting_started/create-test-project.html?os=linux&language=javascript&ide=vscode
From VSCode: Create Gauge Project > js template. 
Many errors. 
Eventually, VSCode even frizzes when using gauge (didn't search why, but enough to make me stop). 

### What command(s) did you run when you found the bug?
Simply followed the installation process and ran the basic example in js. 
Due to a deprecated API, needed to change screenshotFn by customScreenshotWriter.
Then the example fails:
step("Search for <query>", async (query) => {
    await focus(textBox(toRightOf('Pricing')))
    await write(query);
    await press('Enter');
});
 
This really doesn't make the first experience with gauge very good... (sorry). 

#### Operating System information
Linux

#### IDE information
VSCode

**Comment by BugDiver** [comment]
> Many errors.

@fimbault Could you. please tell us, what errors are you seeing?
