### ISSUE TITLE
Should be able to successfully execute a taiko template project `gauge init js` in docker

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1723]
### Describe the bug
I should be able to successfully execute a taiko project created using `gauge init js` in docker

### What command(s) did you run when you found the bug?
* Create a taiko project
`gauge init js`

* Create a docker file
```
FROM zenika/alpine-chrome:with-node

ENV TAIKO_SKIP_CHROMIUM_DOWNLOAD=true
ENV TAIKO_BROWSER_PATH=$CHROME_PATH
ENV NPM_CONFIG_PREFIX=/home/chrome/.npm-global
ENV PATH="${NPM_CONFIG_PREFIX}/bin:${PATH}"

USER root

RUN apk add --no-cache curl &&\
curl -SsL https://downloads.gauge.org/stable | sh &&\
rm -rf /var/lib/apt/lists/* \
    /var/cache/apk/* \
    /usr/share/man \
    /tmp/*

USER chrome

RUN mkdir -p $NPM_CONFIG_PREFIX &&\
 npm install -g taiko
```
* Build docker image
```
docker build -t gauge-tu1 .
```
* Run the tests in docker
```
docker run -v $(pwd):/gauge -e TAIKO_BROWSER_ARGS=--no-sandbox,--start-maximized -e TAIKO_SKIP_CHROMIUN_DOWNLOAD=true -e TAIKO_BROWSER_PATH=/usr/bin/chromium-browser -e headless_chrome=true -w /gauge -t gauge-tu1 /bin/sh -c "npm install;npm test"
```

### Output, stack trace or logs related to the bug 
```
Failed to capture screenshot on failure.
ReferenceError: path is not defined
 ✘
        Failed Step: Goto getgauge github page
        Specification: specs/example.spec:9
        Error Message: Error: Timed out
        Stacktrace: 
        Error: Timed out
            at Timeout.<anonymous> (/home/chrome/.gauge/plugins/js/2.3.12/src/test.js:43:23)
            at listOnTimeout (internal/timers.js:549:17)
            at processTimers (internal/timers.js:492:7)
```

#### Gauge (Output of `gauge -v`)
docker run -v $(pwd):/gauge -e TAIKO_BROWSER_ARGS=--no-sandbox,--start-maximized -e TAIKO_SKIP_CHROMIUN_DOWNLOAD=true -e TAIKO_BROWSER_PA
TH=/usr/bin/chromium-browser -e headless_chrome=true -w /gauge -t gauge-tu1 /bin/sh -c "gauge -v"
```
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
No plugins found
Plugins can be installed with `gauge install {plugin-name}`
```

#### Node.js/Java/Python/.Net/Ruby version, Operating System information
`zenika/alpine-chrome:with-node` in docker

#### IDE information
NA

**Comment by sguptatw** [comment]
*Couple of observations here*
* The template has a custom screenshot code uses path. This is not included in the js file. After including the `var path = require('path');`. I am not getting the `path` screenshot error. However I am still getting the other error that `Failed to capture screenshot on failure.`
* I have fixed the gauge installation version using the dockerfile. However the plugins are not getting installed with it. Should I explicitly install that in the dockerFile? What is the recommended approach?

**Comment by BugDiver** [comment]
@sguptatw 
Using a chromium image (and hence the bundled chromium in the image) can cause problems when the CDP is mismatched. Best to use bundled chromium with taiko. Using the base node image, installing chromium dependencies and then install/run taiko should work

To run taiko in docker you need to pass `--disable-dev-shm-usage` argument as taiko browser args. That is why you are facing the issue. Since the page, itself was not loaded taiko could not take the screenshot of the page, that's why the error `Failed to capture screenshot on failure.`

> The template has a custom screenshot code uses path. This is not included in the js file.

This has been fixed.

**Comment by NivedhaSenthil** [comment]
Can this be closed if the issue is fixed ?

**Comment by sguptatw** [comment]
Yes this issue has been fixed. The example of this can be found at [gauge-taiko-docker](https://github.com/getgauge-examples/GaugeTaikoDocker)
