### ISSUE TITLE
Even after setting GAUGE_CUSTOM_BUILD_PATH environment variable, gauge says .csproj file is missing.

### ISSUE THREAD

**Issue by ayankumaar** [getgauge/gauge#1739]
I have published a gauge project as a single exe. When I am trying to run tests from the published exe it is unzipping everything inside **AppData\Local\Temp\.net\** and running everything from there. Before publishing as a single exe I have inserted the **env folder, specs directory and manifest file** inside the bundle **(i.e. inside the published exe)**.

I have set the **GAUGE_CUSTOM_BUILD_PATH** as an environment variable. The location of  GAUGE_CUSTOM_BUILD_PATH is inside  **AppData\Local\Temp\.net\**  where it is unzipping everything. I have checked that directory; manifest, env and spec files are present there.

But, I haven't copied the **.csproj** file there. As per my understanding if I set the GAUGE_CUSTOM_BUILD_PATH then I don't need to build my project. So, I haven't bundled the **.csproj** file. However, if I try to run the tests from the bundled exe it keeps me giving the following error:
**System.IO.FileNotFoundException: Could not find file C:\Users\XXXX\AppData\Local\Temp\.net\MyProject\abceef.jhi\MyProject.csproj'**

**Should I copy the .csproj file inside the bundle ?**

Even if I copy the .csproj file inside the bundle it keeps giving me the following error
**System.BadImageFormatException: Bad IL format**.

**Any hint why I am getting System.BadImageFormatException ?**

FYI I am using

Gauge version: 1.0.8
Plugins
-------
dotnet (0.1.4)
html-report (4.0.8)
screenshot (0.0.1)

My gauge project is built using .net core 3.1

Any reply on this issue will be highly appreciated.

**Comment by BugDiver** [comment]
@ayankumaar
> As per my understanding if I set the GAUGE_CUSTOM_BUILD_PATH then I don't need to build my project

That's true. I could replicate this issue.  We will try to fix it ASAP

> Any hint why I am getting System.BadImageFormatException ?

We have never tried packing a gauge Dotnet project as an exe, so can't say what could be the reason.

If you can tell us how are you packaging it (adding specs, envs etc) or provide a sample project explaining all the steps to build/package that project, we will try to check the error and try to fix it.

**Comment by ayankumaar** [comment]
@BugDiver Thanks for your reply. 

So, as per my understanding even if I set the **GAUGE_CUSTOM_BUILD_PATH**, still **I need to copy the .csproj file** inside that location. Am I right ?

Regarding, how I am packaging the application,
Yes, I am packing all the output binaries of the gauge project along with the specs, manifest file, env folder

**Comment by BugDiver** [comment]
> So, as per my understanding even if I set the GAUGE_CUSTOM_BUILD_PATH, still I need to copy the .csproj file inside that location. Am I right?

If you are setting the GAUGE_CUSTOM_BUILD_PATH the build is not required. For now, I can't say if the csproj file is required or not, that's why I said I could replicate the issue (means I see if the files is not there the execution failed), we have to dig into it to check if the file is required or not.

**Comment by sriv** [comment]
This is because gauge-dotnet [locates only `*.dll`](https://github.com/getgauge/gauge-dotnet/blob/master/src/AssemblyLocater.cs#L32)

This could be changed it to look for `exe` as well. But I'd like to know the reason you are packaging it as an `exe` as opposed to a `dll`. `exe` implies the output is a standalone executable. Is that something you need? i.e. run your project as an executable? By design, gauge is the host executable, and it loads your test code as a library (hence `.dll` )

**Comment by sriv** [comment]
If you are not particular about packaging it as an executable, try changing your project's type to be a Class Library, which will compile your project as a DLL. 

Setting GAUGE_CUSTOM_BUILD_PATH bypasses the build from within gauge-dotnet. It should not need copying any source or project file.

**Comment by ayankumaar** [comment]
@sriv 
I am publishing my gauge project as a **"single file"**. For that I need to specify the project output type as exe. Otherwise **"dotnet publish /p:PublishSingleFile=true"** this command is not working. But, the directory at which the exe is getting unzipped, there I can see a dll with the same name as the exe. So, I believe the .dll is present.

Now coming to GAUGE_CUSTOM_BUILD_PATH, I am setting this path where the binaries are present. Let's say my binaries are present inside C:\\MyProject\\. So, my GAUGE_CUSTOM_BUILD_PATH = C:\\MyProject\\. But, every time I try to run the exe it keeps saying me 
System.IO.FileNotFoundException: Could not find file C:\\MyProject\\MyProject.csproj'

**Comment by sriv** [comment]
Thanks - that helps. We'll investigate this and see what's the best way to support `PublishSingleFile`.

The `FileNotFoundException` for csproj is a bug, will push a fix for that.

**Comment by ayankumaar** [comment]
@sriv Thank you for your reply.

**Comment by sriv** [comment]
@ayankumaar - I've raised a PR to fix gauge-dotnet expecting csproj file even when `GAUGE_CUSTOM_BUILD_PATH` is set.

On the other issue, I admit I'm a bit confused. AFAIK, `dotnet publish /p:PublishSingleFile=true` will generate a single executable. How are you using it to run your specs? An example would help verify this.

**Comment by ayankumaar** [comment]
Basically, if I publish my project as an exe. You can imagine it like a zip file. So, while zipping it I add the spec files in the exe.

**In my .csproj file I mention something like this:**
 **<ItemGroup> 
  <Content Include="Specs\**"> 
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory> 
  </Content> 
</ItemGroup>**

This copies the specs to the bin folder. Now, when I use **dotnet publish /p:PublishSingleFile**=true this command. It zips the specs folder inside the published exe and it also zips everything that are present inside the bin folder of the project.

Now when I run the exe, it unzips everything inside **AppData\Local\Temp\**. The location where it unzips everything, there I can see all the project related binaries and the spec folder (Spec folder contains spec files).

I am setting the **GAUGE_CUSTOM_BUILD_PATH as  AppData\Local\Temp\**. The place where all the project binaries are present and spec files are also present there. 

While running any gauge command I provide the specs directory that is inside AppData\Local\Temp\. 
So, I am expecting that should work for gauge.

**Comment by sriv** [comment]
I run linux, and when i run `dotnet publish  /p:PublishSingleFile=true` i get an executable, which i cannot unzip. But if you are able to see your project structure, i suppose you can try post this fix merge.

We'll make a release with the fix for project file.

**Comment by ayankumaar** [comment]
Yes. You can't unzip that. When you try to run it, it unzips everything by itself. In windows the location is inside AppData\Local\Temp\{project_name}\{Somerandomdirectory_String}\

After the fix. I will try what you said.

**Comment by sriv** [comment]
[gauge-dotnet 0.1.7](https://github.com/getgauge/gauge-dotnet/releases/tag/v0.1.7) is out - please try and report back

**Comment by ayankumaar** [comment]
@sriv Thanks for the quick response. I need to little bit of time to test the new release. But, I will surely get back to you on this.

**Comment by ayankumaar** [comment]
I tried with gauge 1.1.4 and dotnet plugin 0.1.9
I have set GAUGE_CUSTOM_BUILD_PATH in the user level environment variable as "X:\XXX_XXXX\MyPorject\WorkSpace\MyPorject\MyProjectDll"

I have copied the Specs, env, manifest file inside X:\XXX_XXXX\MyPorject\WorkSpace\MyPorject\MyProjectDll

**When I try to run gauge run specs at that directory. Here is the error I am getting** It is still looking for the csproj file.

X:\XXX_XXXX\MyPorject\WorkSpace\MyPorject\MyProjectDll>gauge run Specs
X:\XXXX\XXXX\gauge\plugins\dotnet\0.1.9>dotnet bin\Gauge.Dotnet.dll --start
Unhandled exception.
System.IO.FileNotFoundException: Could not find file 'X:\\My_Code\MyPorject\MyPorject\WorkSpace\MyPorject\MyProjectDll\MyPorject.csproj'.
File name: 'X:\\My_Code\MyPorject\MyPorject\WorkSpace\MyPorject\MyProjectDll\MyPorject.csproj'
at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
at System.Xml.XmlTextReaderImpl.FinishInitUriString()
at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
at System.Xml.Linq.XDocument.Load(String uri)
at Gauge.Dotnet.AttributesLoader.GetRemovedAttributes() in \AttributesLoader.cs:line 18
at Gauge.Dotnet.StaticLoader.LoadImplementations() in \StaticLoader.cs:line 73
at Gauge.Dotnet.GaugeCommandFactory.<>c.<GetExecutor>b__0_0() in \GaugeCommandFactory.cs:line 22
at Gauge.Dotnet.StartCommand.Execute() in \StartCommand.cs:line 38
at Gauge.Dotnet.Program.Main(String[] args) in \Program.cs:line 27
Error occurred while waiting for runner process to finish.
Error : exit status 3762504530
Error ----------------------------------

[Gauge]
Failed to start gauge API: Error occurred while waiting for runner process to finish.
Error : exit status 3762504530

Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://spectrum.chat/gauge

Your Environment Information -----------
        windows, 1.1.4, c982558
        dotnet (0.1.9), html-report (4.0.8), screenshot (0.0.1)

**Comment by ayankumaar** [comment]
@sriv Please, let me know once the fix is done

**Comment by ayankumaar** [comment]
@sriv  Where to get the new fixes ? Any link to that will help.

**Comment by sriv** [comment]
https://github.com/getgauge/gauge-dotnet/releases/tag/v0.2.0

gauge-dotnet 0.2.0 is out, you can try with this version.

note that it may take some time for the CDN to refresh and post that `gauge install dotnet` will fetch this versino

**Comment by ayankumaar** [comment]
@sriv It is not asking for the csproj file anymore. However, it is expecting the gauge_bin to be present inside the GAUGE_CUSTOM_BUILD_PATH. Without the gauge_bin it is not running. Is this behavior expected ?

**Comment by sriv** [comment]
> Without the gauge_bin it is not running. Is this behavior expected ?

No.

Here's what I tried (with gauge-dotnet 0.2.0)

```
mkdir /tmp-dotnet-sample && cd /tmp/dotnet-sample
gauge init dotnet
dotnet publish -o /tmp/sample (note- the destination is outside the current working dir)
GAUGE_CUSTOM_BUILD_PATH=/tmp/sample gauge run specs
```

the specs run fine for me. I can even confirm that there is no `gauge_bin` directory present in either the project dir or the published dir.
