### ISSUE TITLE
Inconsistency of raising ExecutionStartingRequest event for grpc plugins if running specs in parallel

### ISSUE THREAD

**Issue by nvborisenko** [getgauge/gauge#1741]
I'm developer of plugin for gauge with grpc support.

When we execute specs using `gauge run` command, plugin gets following execution starting 2 events (json serialized):
```
{"CurrentExecutionInfo":null,"SuiteResult":null,"Stream":0}
{"CurrentExecutionInfo":null,"SuiteResult":{"SpecResults":[],"PreHookFailure":null,"PostHookFailure":null,"Failed":false,"SpecsFailedCount":0,"ExecutionTime":0,"SuccessRate":0,"Environment":"default","Tags":"","ProjectName":"sample-gauge-project-master","Timestamp":"Sep 4, 2020 at 7:48pm","SpecsSkippedCount":0,"PreHookMessages":[],"PostHookMessages":[],"PreHookMessage":[],"PostHookMessage":[],"PreHookScreenshots":[],"PostHookScreenshots":[],"Chunked":false,"ChunkSize":0,"PreHookScreenshotFiles":[],"PostHookScreenshotFiles":[]},"Stream":0}
```

Plugin expects that 2 events are raised. It's true for gauge v1.0.7 and v1.1.1.

But if we run specs in parallel `gauge run -p` then only 1 event is raised in gauge v1.1.1:
```
{"CurrentExecutionInfo":{"CurrentSpec":null,"CurrentScenario":null,"CurrentStep":null,"Stacktrace":"","ProjectName":"","ExecutionArgs":[],"NumberOfExecutionStreams":0,"RunnerId":0},"SuiteResult":null,"Stream":1}
```

Note: With gauge v1.0.7 parallel execution fires 2 events as expected.

**Comment by BugDiver** [comment]
@nvborisenko I'm not able to replicate it. I still see two events being raised.
I tried it with the `html-report` plugin and the `report portal` plugin as well. 
I minimized the report portal (commented lines which send the data) and added a log statement in the `NotifyExecutionStarting` method. Installed it locally, and I could see the two events being raised. Even with the data-driven execution, I see the expected output.

**Comment by nvborisenko** [comment]
@BugDiver should be reproducible with https://github.com/imindersingh/sample-gauge-project. Could you please try it?

**Comment by BugDiver** [comment]
@nvborisenko It would require the report portal credentials to run the project. Is there a way I can bypass that?

**Comment by nvborisenko** [comment]
In `env/default/default.properties`
```
#REPORTPORTAL CONFIG
RP_URI=https://beta.demo.reportportal.io/
RP_PROJECT=default_personal
RP_UUID=9a22543e-fc28-44f1-a171-b87192982078
RP_ENABLED=true
RP_LAUNCH_NAME=test
ReportPortal_TraceLevel=Verbose
```

To see the report on UI just open https://beta.demo.reportportal.io, username `default`, pass `1q2w3e`. UUID might be changed, you can get it on user profile page (right top corner).

**Comment by BugDiver** [comment]
@nvborisenko I was able to see the exception with the specified setup. We will be pushing a fix soon
