### ISSUE TITLE
Gauge templates URL is not reachable

### ISSUE THREAD

**Issue by IRE04** [getgauge/gauge#1742]
### Describe the bug
Gauge templates URL is not reachable when trying to get a list of templates or initialise project templates

### What command(s) did you run when you found the bug?

```
gauge init --templates
```

### Output, stack trace or logs related to the bug 
```
[Gauge]
Gauge templates URL https://downloads.getgauge.io/templates is not reachable: Failed to resolve host
```

#### Gauge (Output of `gauge -v`)
```
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
html-report (4.0.10)
java (0.7.9)
reportportal (1.7.0)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)
```

#### Operating System information
OSX

**Comment by sriv** [comment]
Please note the below:

- With #1575, the need for template repository is removed. Gauge initializes a template using a convention now. Released with gauge  v1.1.3.

- For older releases, the template URL is used, however you are using an older domain (getgauge.io). Please use `https://templates.gauge.org/` (run `gauge config gauge_templates_url https://templates.gauge.org`)
