### ISSUE TITLE
Gauge Java Xml report is not getting generated 

### ISSUE THREAD

**Issue by hcsan** [getgauge/gauge#1748]
Hi Team,

Gauge Java Xml report is not getting generated  , Html report  generates without any issues

Please let me know if we need any configurations updated in default properties

Gauge java version 0.7.9 
gauge --version
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
html-report (4.0.8)
java (0.7.9)
python (0.3.7)
screenshot (0.0.1)
xml-report (0.2.2)

Default env

# The path to the gauge reports directory. Should be either relative to the project directory or an absolute path
gauge_reports_dir = reports

# Set as false if gauge reports should not be overwritten on each execution. A new time-stamped directory will be created on each execution.
overwrite_reports = true

# Set to false to disable screenshots on failure in reports.
screenshot_on_failure = true

# The path to the gauge logs directory. Should be either relative to the project directory or an absolute path
logs_directory = logs

# Set to true to use multithreading for parallel execution
enable_multithreading = false

# Possible values for this property are 'suite', 'spec' or 'scenario'.
# 'scenario' clears the objects after the execution of each scenario, new objects are created for next execution.
gauge_clear_state_level = scenario

# The path the gauge specifications directory. Takes a comma separated list of specification files/directories.
gauge_specs_dir = specs

# The default delimiter used read csv files.
csv_delimiter = ,

# Allows steps to be written in multiline
allow_multiline_step = false

**Comment by sriv** [comment]
What does your `manifest.json` look like? It should have `xml-report` in the `plugins` array. Please check.

**Comment by hcsan** [comment]
Yes it worked, Thank you
