### ISSUE TITLE
Multiline step arguments

### ISSUE THREAD

**Issue by tlempart** [getgauge/gauge#175]
Support multiline step arguments similar to https://cucumber.io/docs/reference#doc-strings. It would be great to allow using different formatting options, e.g.

```
* step 1
'''gauge-parameter <- backtick
multiline step argument as code block
'''
* step 2
```

or:

```
* step 1
multiline step argument as paragraph
* step 2
```

I am not sure about the second example, because sometimes there is a need to document a step in specification, but in that case you can simply ignore such parameter in step implementation.

**Comment by uuunk** [comment]
+1

**Comment by FaustXVI** [comment]
+1. I'll try to make a PR for it.

**Comment by mahendrakariya** [comment]
That'd be really awesome @FaustXVI !!

I'd also suggest you to discuss the changes that you are planning to make, before you actually start implementing it. Because the changes for this feature may not be just limited to Gauge core. It may impact other plugins as well.

**Comment by FaustXVI** [comment]
Looking at the code, I think I'll just change the parser to accept multi-line strings. So :
```
* a step with "a parameter"
```
and
```
* a step with
"""
a parameter
"""
```
would be equivalent.

What do you think ?
What about the triple quotes ?

**Comment by sriv** [comment]
Update, with support for #265 coming up, I believe something like this should be possible:

```
* The word "gauge
in multiple lines" 
has "9" vowels.
```

Will be the same as :

```
* The word "gauge in multiple lines" has "9" vowels.
```

Feedback welcome!

**Comment by haroon-sheikh** [comment]
@FaustXVI @sriv Do we have any updates on this? As part of this we should look at using code blocks to allow passing of `json/xml` strings in the parameters.

E.g.
```json
{"hello":"world"}
```

**Comment by sriv** [comment]
@haroon-sheikh - #265 brings support for mulitline step text (although it is toggled off, by default)

Multiline step arguments needs some work. #1240 also talks about code parameters which I believe is similar to what you seek. Perhaps you could add your thoughts there?

**Comment by zabil** [comment]
To make this usable within markdown syntax it's best to use code blocks as @haroon-sheikh mentions.

For example (provided by @ajoecker)

````
* When sending 
```
{
  human(id: "1000") {
    name
    height
  }
}
```
*  Then the name is "Batman"
````

This means multiline parameters can only be used at the the end of a step in a separate line.
This will also partially meet the requirements of https://github.com/getgauge/gauge/issues/1240

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
