### ISSUE TITLE
when formatting spec files special chars not treated correctly

### ISSUE THREAD

**Issue by fazs** [getgauge/gauge#1755]
### Describe the bug
When using gauge format files contining special characters like german umlauts (ä,ö,ü) and also ß-character are not properly formatted. They get treated as two characters but rendered as one.

### What command(s) did you run when you found the bug?
```
gauge format foo.spec
```

### Output, stack trace or logs related to the bug 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/12977360/93088885-ce043480-f69a-11ea-98e2-8f3e1b61b4ce.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/12977360/93088901-d2305200-f69a-11ea-9797-33b1f8039804.png)
### Versions 
at least until 1.1.4

#### Gauge (Output of `gauge -v`)
Gauge version: 1.1.4
Commit Hash: c982558

Plugins
-------
html-report (4.0.12)
java (0.7.7)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)

#### Operating System information
Win 10 1909

**Comment by sriv** [comment]
Thanks for reporting. Could you please add an example spec that we can try and use to test from our side?

I cannot copy the text from the image that you shared, and I do not have an example with special chars.

**Comment by fazs** [comment]
Here you go 
(Since github doesn't allow 'spec'-files it got zipped)
[testspec.zip](https://github.com/getgauge/gauge/files/5229874/testspec.zip)

**Comment by sriv** [comment]
Thanks again, I could see the issue, and have a fix as well. Will raise a PR.
