### ISSUE TITLE
Allow tables to be inserted for each scenario

### ISSUE THREAD

**Issue by aWdas** [getgauge/gauge#176]
Currently, it is only possible to insert one table for table-driven execution per spec-file:

#Specification
table:data.csv

##Scenario 1
*Step <field>

##Scenario 2
*Step <field>

However, it would be wonderful if you could specify a table for each Scenario as well. It works currently (unofficially), but if two tables have the same column, the earlier loaded table gets skipped. What would be optimal is this:

#Specification
##Scenario 1
table:data1.csv (2 rows)
*Step <field> (gets executed 2x)

##Scenario 2 
table:data2.csv(3 rows)
*Step <field> (gets executed 3x)

**Comment by kashishm** [comment]
We already have this feature in our pipeline, Please track this [issue](https://github.com/getgauge/gauge/issues/111) to get updates.

**Comment by aWdas** [comment]
Whoops, sorry. github search didn't reveal that this issue was already created.

**Comment by prateekbaheti** [comment]
Duplicate to [issue](https://github.com/getgauge/gauge/issues/111).
Closing this.
