### ISSUE TITLE
Gauge java support for Eclipse and IntelliJ

### ISSUE THREAD

**Issue by manavghaigit** [getgauge/gauge#1779]
Does Gauge has plugin for Eclipse or IntelliJ?

**Comment by zabil** [comment]
@manavghaigit Github is for tracking issues and bugs. In the future it's better to ask questions on the forum which is at
https://spectrum.chat/gauge

You can refer https://github.com/getgauge/gauge#talk-to-us for information on where to ask what kind of questions.

That said, there is an IntelliJ plugin here https://plugins.jetbrains.com/plugin/7535-gauge this is maintained by Jetbrains.
Please read https://github.com/getgauge/Intellij-Plugin#notice
