### ISSUE TITLE
Maven error with Gauge

### ISSUE THREAD

**Issue by manavghaigit** [getgauge/gauge#1781]
I have initialized the project using gauge init java_maven_selenium. i am getting below error when trying to run mvn commands, for eg mvn install. I am getting same errors from vscode as well. I checked and i do not have any proxy in my VDI. Please advise.

mvn install
[INFO] Scanning for projects...
[INFO]
[INFO] --------< gauge_java_maven_selenium:gauge_java_maven_selenium >---------
[INFO] Building gauge_java_maven_selenium 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.845 s
[INFO] Finished at: 2020-10-29T18:57:07-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.6: Could not transfer artifact org.apache.maven.plugins:maven-resources-plugin:pom:2.6 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by zabil** [comment]
Please ask this question at https://spectrum.chat/gauge as it is related to maven + java configuration. There are better chances of getting help there.

**Comment by manavghaigit** [comment]
@zabil Very strange, i am getting below message when i clicked on Spectrum link you mentioned in your last message :) :) :)

"It looks like Spectrum is very busy right now, please try again in a minute."
