### ISSUE TITLE
Debug output for URL

### ISSUE THREAD

**Issue by DvagNic** [getgauge/gauge#1782]
### Describe the bug
When starting gauge with the "-l debug" parameter I would like to suggest to output the URL the browser driver was instantiated with.

The reason I am asking for this feature is because I have the weird case where I am connected via VPN to the company network and running my gauge tests. The browser (Chrome) starts up but it does not show an URL - only "Data:,". I'd like to debug this issue.
![Screenshot 2020-11-03 at 11 20 39](https://user-images.githubusercontent.com/50959714/97975557-9c216b80-1dc9-11eb-8c44-2b4af448ec65.png)

### What command(s) did you run when you found the bug?

For e.g. 
```
gauge run -l debug -v specs/...
```

#### Gauge (Output of `gauge -v`)
Gauge version: 1.1.4

#### Node.js/Java/Python/.Net/Ruby version
Python 3.7.4

#### Operating System information
macOS 10.15.7

**Comment by zabil** [comment]
> When starting gauge with the "-l debug" parameter I would like to suggest to output the URL the browser driver was instantiated with.

What library are you using for testing the browser? As Gauge is a runner. It does not have information of the underlying library that it uses for for testing.

**Comment by DvagNic** [comment]
Ok, sorry forgot to mention. I am using Selenium and language is Python.

**Comment by DvagNic** [comment]
One more thing I'd like to mention - this happens only with Chrome. Safari and Firefox (using their respective drivers), work fine.

**Comment by zabil** [comment]
Thanks for the info. I am pretty sure however that Gauge cannot show this information. You might could add extra logging in  your python implementation or set the log levels for selenium 
https://chromedriver.chromium.org/logging
