### ISSUE TITLE
Support to skip the  spec/scenario execution deliberately 

### ISSUE THREAD

**Issue by NSDInesh30** [getgauge/gauge#1784]
I see a similar requirement in [https://github.com/getgauge/gauge/issues/1397]

I created this new ticket since the old ticket is closed .

**Example for the requirement**
Lets say i have used a tag 'Android' in spec level. Now in the BeforeSpec hook, i will get devicetype at run time and skip the spec execution deliberately if device type is iOS.
I need this to be reflected as skipped specs in Gauge html report as well

DO we have any feature to skip the spec execution deliberately(say any static method/ exception to skip)

Any suggestions would be helpful

**Comment by zabil** [comment]
@NSDInesh30 There is no feature to skip execution at runtime. The only workaround would be add conditions to the execute or not. If you can, then it's best to use tags and pre-determine the device type before running the tests.

**Comment by NSDInesh30** [comment]
is it possible to provide this feature in Gauge to skip  the execution by spec level
like Gauge.report(""), is it possible to give Gauge.skipSpec,  Gauge.skipScenario. SO when this is used, all the steps in this spec should be skipped and same be reflected in report.

I could use these methods inside BeforeSpec hooks, to determine whether this spec to run or to skip
