### ISSUE TITLE
Gauge unable to capture screen shots on linux

### ISSUE THREAD

**Issue by harimadusumilli** [getgauge/gauge#1786]
**Issue:**
Gauge unable to capture screen shots on linux. We are running the tests in headless mode. This works fine on windows. On linux we are having an issue.

Gauge screenshots are not captured under the “.gauge” folder  and the html result is generated without screenshots.

**What command(s) did you run when you found the bug?**

gauge run specs

Gauge screenshot method is not working in Linux with full root access for  the user.
/Users/vagrant/go-agent-17.4.0/pipelines/Screenshot/src/github.com/getgauge/gauge_screenshot/main.go:44 +0x19c

** Versions** 
gauge-1.1.1-linux.x86_64

**Gauge (Output of `gauge -v`)**

**Plugins Version :** 
dotnet (0.1.3)
html-report (4.0.9)
json-report (0.3.3)
screenshot (0.0.1)
xml-report (0.2.3)

**.NET VERSION**
.NET CORE 3.1.1

**Operating System information**
Linux

**IDE information**
VS CODE

**Comment by zabil** [comment]
Are you using a custom screenshot handler? If you are please share the code for capturing. 
If you have not implemented a custom screenshot handler please implement one when running tests in headless mode. There is more information here https://docs.gauge.org/writing-specifications.html?os=linux&language=javascript&ide=vscode#taking-custom-screenshots
