### ISSUE TITLE
Env variables in Windows

### ISSUE THREAD

**Issue by apoorvam** [getgauge/gauge#179]
Currently, Environment variables set in property files should be escaped in Windows as : 

`gauge_custom_build_path = C:\\foo\\bar` (escape slashes)
or 
`gauge_custom_build_path = C:/foo/bar`  (unix style)

But this should work fine with : 
`gauge_custom_build_path = C:\foo\bar`
which is the default way of writing file path in windows.

**Comment by sriv** [comment]
`\` is an escape character in the properties file, so it needs to be escaped using `\\`.

Closing. Please comment/reopen if this is still valid.
