### ISSUE TITLE
Maven test failing in debug mode

### ISSUE THREAD

**Issue by manavghaigit** [getgauge/gauge#1791]
Problem Statement - My gauge's maven test when executed in debug mode gets marked failed even though the test is passed. The same test passes when running through "mvn test" or by clicking "Run Scenario/Spec"

Steps to reproduce:
1. Clone maven project from "https://github.com/getgauge/template-java-maven-selenium.git"
2. Open this project in VSCode
3. Run Debug Scenario
4. Test gets passed but is still marked as "Error: Tests failed." as marked in the below output from vscode
5. HTML reporting is showing correctly without any problem

Running tool: mvn.cmd -q clean compile test-compile gauge:execute -Dflags=--hide-suggestion,--simple-console -DspecsDir=specs\example.spec:9

Runner Ready for Debugging
Listening for transport dt_socket at address: 61147
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting ChromeDriver 86.0.4240.22 (398b0743353ff36fb1b82468f63a3a93b4e2e89e-refs/branch-heads/4240@{#378}) on port 34634
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Nov 19, 2020 3:59:55 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
# Getting Started with Gauge
  ## Get Started

Successfully generated html-report to => c:\Users\ghaima2\Desktop\Automation\template-java-maven-selenium\reports\html-report\index.html

**Error: Tests failed.**
Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	1 executed	1 passed	0 failed	0 skipped

Total time taken: 19.43s
Updates are available. Run `gauge update -c` for more info.

**Comment by manavghaigit** [comment]
@zabil Please advise

**Comment by NivedhaSenthil** [comment]
@manavghaigit Thanks for reporting I could see this happening too.. need to analyze the cause

**Comment by chadlwilson** [comment]
Closing this old issue. If it's still relevant, we can re-open and move to the correct project.
