### ISSUE TITLE
Conversion of gherkin to Gauge markdown

### ISSUE THREAD

**Issue by teknologika** [getgauge/gauge#180]
Gauge should leverage the Gerkin3 parser to convert cucumber specs into the Gauge markdown format.

**Comment by alwinmark** [comment]
Why should I use Gauge at all, when I'm able to use Cucumber?

**Comment by teknologika** [comment]
The answer to that question will evolve over time, but at the time of writing if you like the freedom to write your specs in a format that is not restricted to given- then-when, and want to use markdown, then Gauge is a logical choice.

This feature request is about being able to leverage your investment in cucumber tests and convert them to markdown so you can use them with gauge.

Choice is a good thing.

**Comment by zabil** [comment]
This might work https://github.com/raviqqe/gherkin2markdown

However, this feature will not be a part of Gauge core.

**Comment by josersleal** [comment]
why? should you not be instead enforcing a consolidation of requirements understanding? Versus verifying tests?

**Comment by Hrishi2810** [comment]
Is there a way to convert .spec file (gauge) to .feature file (cucumber)?

**Comment by Hrishi2810** [comment]
I am using gauge framework for testing. I wish to store the execution results in Jira/Xray. But Jira/Xray only support cucumber for automated testing. I am thinking of converting the .spec file to .feature file and add it to the Xray test scenario. Then after executing the gauge test I am translating the gauge-json report to a cucumber-json myself. I am looking for a tool or a convinient way to translate the .spec file to .feature file.

**Comment by zabil** [comment]
The best way to do this would be using a custom reporting plugin and the JIRA/XRAY API's. 
There's a sample reporting plugin project you can build on available at https://github.com/getgauge-contrib/report-seed
