### ISSUE TITLE
Invalid test failure when running Debug Spec/Scenario

### ISSUE THREAD

**Issue by alex-gagnon** [getgauge/gauge#1807]
**Describe the bug**
 Running a test with Debug Spec/Scenario in VS Code is resulting in an Error: Test(s) failed. to appear in the gauge execution console. Checking the logs and reports shows that all tests had passed. This is not occurring with Gauge CLI or Run Spec/Scenario.

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Run a test using Debug Spec/Scenario
2. Check gauge execution console output
2. If test passes, run the test again (or any other test)
3. Check gauge execution console output again, there should be an Error: Test(s) failed.
4. Delete the lsp.log, and run test again. First test will pass, following test(s) will fail.

**Logs**

```
N/A
```

**Expected behavior**
Gauge execution output should show valid test pass/failure output.

**Screenshots**
```
N/A
```

**Versions:**

```
gauge -v == 1.1.6
```
 - Windows 10
 - Python
 - VS Code

**Additional context**

**Comment by zabil** [comment]
I think this issue is the same as https://github.com/getgauge/gauge-vscode/issues/518
I am linking it to that and closing this. Please do comment and follow the linked issue for updates.
