### ISSUE TITLE
Cannot run gauge specs on Windows

### ISSUE THREAD

**Issue by apoorvam** [getgauge/gauge#184]
When all the gauge specs are run on command line, it gives :
```
Error when running specifications:
Cannot run program "C:\Program Files\Gauge\bin\gauge.exe" in directory .... Createprocess error=206; the filename or extension is too long
````

**Comment by mahendrakariya** [comment]
As per [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath) the MAX_PATH in Windows is set to 260 chars. To overcome this, we need to prefix the path name with "\\\\?\" on Windows. For example, "\\\\?\D:\very long path".

**Comment by apoorvam** [comment]
Failed to reproduce. We'll re-open this if someone faces this issue.
