### ISSUE TITLE
ASL 2.0

### ISSUE THREAD

**Issue by sirinath** [getgauge/gauge#185]
Is there any chance to move to ASL 2.0 or non *GPL license?

**Comment by sriv** [comment]
Short answer: Not in the near future. Is there a reason why you would want a non-gpl license?

**Comment by sirinath** [comment]
Because GPL complicates usage and makes it only usable in very narrow situations.

When you are running your tests and if Gauge is within the same process boundary then your code needs to be also GPL to be able to test it legally. The implication off this is you either have to own 100% the code without using any other libraries which copyrighted by others or any code you test is convertible to GPL. You cannot test any of your code if you have any 3rd party library which cannot be converted to GPL like EPL, MPL, CDDL, Proprietary License, etc as at the point of testing you have to accept GPL as the license of your code and GPL is not linkable to non GPL code. Even when you are testing code you own with only dependencies being licences which are convertible to GPL then the build process becomes complicated if your license is not GPL. You have to have 2 separate processors to build as well as test as any builds you run to test cannot be distributed other than under GPL (to use Gauge API you have to temporarily accept GPL for the build artifacts and code). The builds for distribution cannot have any testing. Also if the build infrastructure, scripts are not GPLed this creates more complications. Also none of the code between build for testing and build for distribution cannot be shared as build for testing code will be GPLed and the code for building should be independently written without any knowledge of the other as invariantly writing similar constructs for building  you cannot construct if it is copying hence the build for distribution infrastructure will become an adaptation of derived work henced GPLed. Even if you build and testing infrastructure is completely GPLed you still have to run the process twice: one for testing and one for pure building without testing and no usage of Gauge code or GPL code running within the process boundary.

**Comment by sirinath** [comment]
Writing to follow up on this.

**Comment by kaustavdm** [comment]
Thank you bringing up the issue @sirinath. We haven't managed to have a discussion on this yet. We will keep this thread updated.

**Comment by sriv** [comment]
@sirinath - We managed to talk to our lawyer regarding this. He did thank you for bringing up the arguments, and it seems to him that Gauge being GPL need not affect the test code license. 

We would like to stay GPL for now, please feel free to ping any of the Gauge members offline (via gitter/email) if you have further questions.

**Comment by sirinath** [comment]
I would disagree though. Using GPL API and the Gauge and own code executing in one process would be reason enough to trigger GPL.

**Comment by twchad** [comment]
Hi,

Even if that were accurate, the copyright holder, (ThoughtWorks for most of
Gauge thus far) would have to enforce the license. Per Srikanth's earlier
response, ThoughtWorks doesn't think this use case is a violation of the
license terms, so it's a moot point.   Would it help if ThoughtWorks put
out some sort of clarifying statement?

**Comment by sirinath** [comment]
What is another party refuses to user code which they think as tainted by GPL or any now permissive license. The onus would be on us to argue this out with the final decisions not in our hands.

**Comment by sirinath** [comment]
Any chance of revisiting this? Most of your other FOSS software is ASL 2.0. Hence it would be good to switch to a non viral license.

**Comment by sirinath** [comment]
Wondering if you licensing stance is the same? If you are not considering ASL 2.0 is it possible to consider EPL, MPL or CDDL or similar license opposed to GPL. Even maybe LGPL?
