### ISSUE TITLE
How can i sort my spec execute ？

### ISSUE THREAD

**Issue by yicaifeitian** [getgauge/gauge#1854]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sriv** [comment]
Have you tried running `gauge run --sort` ? This would sort the specs alphabetically. 

If this is not what you need, please fill in more details.

**Comment by yicaifeitian** [comment]
I have try， but it doesn't work。still like this


https://ask.csdn.net/questions/6255083













在 2021-01-15 18:42:43，"Srikanth" <notifications@github.com> 写道：

Have you tried running gauge run --sort ? This would sort the specs alphabetically.

If this is not what you need, please fill in more details.

**Comment by sriv** [comment]
The issue you've referred to was a bug in gauge `0.8.4` and had been fixed since. 

Do you have a sample for me to replicate this issue?
