### ISSUE TITLE
AS a QA，Some time we should do app test, then we need mobile screenshots. 

### ISSUE THREAD

**Issue by yicaifeitian** [getgauge/gauge#1855]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

this can develop by plugin?

**Comment by sriv** [comment]
Gauge is framework agnostic, and allows you to hook in your logic to capture screenshots. See https://docs.gauge.org/writing-specifications.html?os=macos&language=javascript&ide=vscode#taking-custom-screenshots for an example.

You can invoke your mobile automation framework to fetch the screenshot.
