### ISSUE TITLE
Gauge could not initialize. Install 'ms-dotnettools.csharp' extension for code insights.

### ISSUE THREAD

**Issue by anantharamakrishnans** [getgauge/gauge#1856]
**Describe the bug**
I am getting the error  -Gauge could not initialize. Install 'ms-dotnettools.csharp' extension for code insights.
Also, I am seeing only Run Scenario and Run Spec option. I dont see Debug Spec and Debug Scenario option.

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Installed Gauge version 0.0.15 and Omnisharp version 1.23.1
2. Open the test project

```

```

**Logs**

```
Paste any log or error messages here
```

**Expected behavior**
I must see the debug spec and debug scenario along with run spec and run scenario.

**Screenshots**

**Versions:**

[```](url
![GaugeError](https://user-images.githubusercontent.com/18507014/104687901-0dfd2600-5726-11eb-96a4-d04ef30b7343.png)
)
gauge -v
```
 - OS [e.g. MacOS 10.15.6 (19G2021) please be specific ]
 - Runner info (Please specify the correct version of Java/Node/Python/Dotnet/Ruby)
 - IDE info (If using VS Code or Intellij IDEA)


**Additional context**
Add any other context about the problem here.

**Comment by sriv** [comment]
Do you have `gauge` installed? Please run `gauge -v` and paste the output.

**Comment by anantharamakrishnans** [comment]
Gauge version : 1.1.4
Vomit Hash: c982558

Plugins
------------
Dotnet (0.1.9)
Html-report (4.0.8)
Screenshot (0.0.1)

**Comment by rogerjak** [comment]
Same issue here in VSCode in Windows (Gauge 1.1.8, gauge-dotnet 0.3.1)
I have that extension (ms-dotnettools.csharp) installed, so don't know what to do.
Besides not seeing the debug actions like @anantharamakrishnans, the non-debug actions sometimes disappears, and I have to restart VSCode.
Also F12 on step in spec fails to jump to code-behind.

**Comment by sriv** [comment]
Do you see any errors/information in the log files when this happens? Please inspect `gauge.log` and `lsp.log`

**Comment by jensakejohansson** [comment]
A comment for this old issue - if someone searches for help: 

When I see this problem it's seems be a timeout that occurs when loading larger projects in VSC. So if anyone has this issue, try to increase the configured Gauge timeouts. Specifically it seems to be the plugin_connection_timeout. Check your timeouts and increase them and see if it makes a difference.

![Image](https://github.com/user-attachments/assets/8bdcf7ac-edba-4178-a79d-bb6ab9c419e4)
