### ISSUE TITLE
Unable to start LSP on MacOS with ts plugin

### ISSUE THREAD

**Issue by hungluong5791** [getgauge/gauge#1857]
### Describe the bug
When activating after initialising a gauge-ts project, the extensions was unable to start after repeatedly crashing.

side note: 
- initialising gauge-java and gauge-js seems to work fine, but referencing gave an error `failed to parse request json: cannot unmarshal array into Go value of type string`

### What command(s) did you run when you found the bug?
Activating the extension, selecting the template for gauge-ts

### Output, stack trace or logs related to the bug

lsp.log

        14-01-2021 18:14:31.669 [Gauge] [DEBUG] Attempting to connect to grpc server at port: 57622
        14-01-2021 18:14:31.672 [Gauge] [DEBUG] Successfully made the connection with runner with port: 57622
        14-01-2021 18:14:31.672 [Gauge] [INFO] LangServer: reading on stdin, writing on stdout
        14-01-2021 18:14:31.884 [Gauge] [DEBUG] Runner with PID:61704 has exited
        14-01-2021 18:14:31.885 [Gauge] [INFO] Connection closed
        14-01-2021 18:14:31.885 [Gauge] [ERROR] Unable to log error 'Connection closed' to LSP: jsonrpc2: connection is closed

### Versions

0.0.19

#### Gauge (Output of `gauge -v`)

        Gauge version: 1.1.7
        Plugins
        -------
        html-report (4.0.12)
        java (0.7.13)
        js (2.3.15)
        screenshot (0.0.1)
        ts (0.1.0)

#### Node.js/Java/Python/.Net/Ruby version

        node --version
        v14.9.0

#### Operating System information

MacOS Big Sur
Version 11.1

#### IDE information

Visual Studio Code Version: 1.52.1

**Comment by realSergiy** [comment]
Experiencing identical issue with identical log messages on Ubuntu.

**Comment by gobbi9** [comment]
I seem to have the same problem with a [fresh example project](https://bugdiver.dev/gauge-ts/#/?id=create-a-project) with Typescript. I can run specs with `gauge run specs`, but not through the VsCode UI. I do not have the problem with a JS project, for example.

```
01-11-2021 12:12:52.659 [Gauge] [INFO] Initializing steps cache with 1 steps
01-11-2021 12:12:52.659 [Gauge] [DEBUG] Watching directory: /Users/xxxx/projects/gauge-ts/specs
01-11-2021 12:12:52.659 [Gauge] [DEBUG] Found 1 files
01-11-2021 12:12:52.659 [Gauge] [INFO] Starting language runner
01-11-2021 12:12:55.647 [Gauge] [DEBUG] Attempting to connect to grpc server at port: 57291
01-11-2021 12:12:55.649 [Gauge] [DEBUG] Successfully made the connection with runner with port: 57291
01-11-2021 12:12:55.649 [Gauge] [INFO] LangServer: reading on stdin, writing on stdout
01-11-2021 12:12:55.864 [Gauge] [DEBUG] Runner with PID:60187 has exited
01-11-2021 12:12:55.864 [Gauge] [INFO] Connection closed
01-11-2021 12:12:55.864 [Gauge] [ERROR] Unable to log error 'Connection closed' to LSP: jsonrpc2: connection is closed
```

```
gauge -v
Gauge version: 1.4.2
Plugins
-------
html-report (4.1.2)
js (2.3.17)
screenshot (0.1.0)
ts (0.1.0)
```

```
node -v
v14.15.3
```

OS: BigSur 11.6
VsCode: 1.61.2

@BugDiver maybe you know more about this?

**Comment by BugDiver** [comment]
@gobbi9 Please refer to https://github.com/getgauge/gauge-vscode/issues/735#issuecomment-950284307
