### ISSUE TITLE
Exception occurred in Gauge plugin

### ISSUE THREAD

**Issue by AhmetRufai** [getgauge/gauge#1863]
**Describe the bug**
While opening IDE, Gradle libraries show exception in Event Logs while they are built.

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Create a gauge project with Gradle
2. Define the following dependencies on Gradle
`dependencies {
    implementation 'com.thoughtworks.gauge.gradle:gauge-gradle-plugin:1.7.3'
    implementation 'com.thoughtworks.gauge:gauge-java:0.7.13'
    testImplementation group: 'org.assertj', name: 'assertj-core', version: '3.12.2'
    implementation 'org.seleniumhq.selenium:selenium-java:3.141.59'
    implementation 'io.github.bonigarcia:webdrivermanager:4.3.1'
    implementation 'org.slf4j:slf4j-log4j12:1.7.30'
}`
3. Reload all Gradle project
4. Invalidate Caches/Restart..
5. See Event Log

**Logs**

```
Exception occurred in Gauge plugin
More details...
Please report an issue in https://youtrack.jetbrains.com/issues/IDEA with following details:
#### Gauge process exited with code ```1```
Gauge daemon initialized and listening on port: 2790
* IDE version: 2020.3.1
* API version: IC-203.6682.168
* Plugin version: 203.5981.155
* Gauge version: 1.1.7
```

**Expected behavior**
There shouldn't have been an exception.

**Versions:**
```
gauge -v: 1.1.7
gradle -v: 6.8
java -version: 15.0.1
```
 - OS Windows 10
 - Runner info: Java jdk 15.0.1
 - IDE info: Intellij IDEA

**Additional context**
I don't know what is causing Exception right now. It is only seen when Ide first opened. Other than that, it is not observed again.

**Comment by zabil** [comment]
Can you please report this to https://youtrack.jetbrains.com/issues/IDEA

**Comment by AhmetRufai** [comment]
Hi,

A similar problem was reported on the page you specified, but they also wrote that this problem should be reported to you.
Report Id: IDEA-259583
Report Url: https://youtrack.jetbrains.com/issue/IDEA-259583

Thanks

**Comment by zabil** [comment]
Can you please refer https://docs.gauge.org/faqs.html#where-does-gauge-non-project-specific-logs-like-plugin-installation-etc to see if there any exceptions in the log files?

**Comment by sriv** [comment]
I know this is late, but is this still an issue? I was able to create a new gradle project (the template is updated to use gradle 6.8.2)  and add the dependencies you mentioned. Could not see any errors.

**Comment by chadlwilson** [comment]
This seems old/stale, so closing. Can re-open if its still an issue.
