### ISSUE TITLE
Unable to install Gauge 0.1.7 on OSX version 10.10.2

### ISSUE THREAD

**Issue by mikedd** [getgauge/gauge#188]
I tried downloading the latest install packages for Gauge 0.1.7 (32 and 64 bit) and the installs failed at the validating packages step.

The link to show the sha1sums didn't work for me, but here are the sums for the files I downloaded. 

1707c7047e5d84ed4b95efc31cd21f70f36fe66e  gauge-0.1.7-darwin.x86.pkg
f1400b62506bb671e8402ca9297ee1c6cc3c8627  gauge-0.1.7-darwin.x86_64.pkg

Brew worked for me, but the prepackaged downloads could put people off.

**Comment by apoorvam** [comment]
Hi @mikedd,
We tried running the installer on various versions of OS X 10.9.x as well as 10.10.x. We weren't able to reproduce the issue. Gauge is getting installed as expected.
 
We do agree that the link for SHA1 sums on the website isn't working. This is a bug which we need to fix.

P.S. The SHA1 sums that you have mentioned are correct.

**Comment by mikedd** [comment]
Odd, I just tried again and I still wasn't able to install. Would it error out if I have a version installed through homebrew? 

One other thing, I was unable to install the java plugin from work (some VPN issue that we haven't diagnosed). From home it worked fine. I'll try the installer from home in case there's something similar going on.

**Comment by mikedd** [comment]
Sigh, sorry for the late reply. 

The installer worked fine for me outside of the VPN. I'm not sure how that would affect it. I have similar problems installing plugins. Wget from the command line works fine, wget from gauge doesn't work. 

If the install process issues a wget or something similar I'd expect it's the same problem, and there's something weird about my environment or the way wget is invoked.

**Comment by sriv** [comment]
One way to troubleshoot this is to uninstall `wget`. Gauge falls back on `curl`, you could see if that works through your VPN.

**Comment by mahendrakariya** [comment]
Hi @mikedd Are you still facing issues installing Gauge on Mac?

**Comment by mikedd** [comment]
I tried again with Gauge 2.1 and it just worked. Either something changed in gauge (unlikely) or something in the network config changed. 

I'm sorry it took so long to try again, but thanks very much for all your help.

**Comment by mahendrakariya** [comment]
Happy to hear that your issue is resolved.
