### ISSUE TITLE
apt-key deprecated

### ISSUE THREAD

**Issue by hrobky** [getgauge/gauge#1887]
`apt-key` is considered deprecated in Ubuntu >=20.10

Please update installation guide here
https://docs.gauge.org/getting_started/installing-gauge.html#step-1-installing-gauge-on-linux

Instead of installing gauge repository key using `apt-key` to `/etc/apt/trusted.gpg`
install it to `/usr/share/keyrings/` as this Debian wiki article suggests. (Either via direct `wget` or `gpg --recv-keys`)

https://wiki.debian.org/DebianRepository/UseThirdParty#OpenPGP_Key_distribution

It's also a great chance to create `/etc/apt/sources.list.d/gauge.list` file instead of appending into `sources.list`

Thank you

**Comment by sriv** [comment]
Good catch, thanks for reporting @hrobky. Since you've done all this study, I wonder if you'd like to open a pull request in the documentation? The source for linux installation is in this file: https://github.com/getgauge/docs.gauge.org/blob/master/partials/linux_installation.rst

thanks!

**Comment by hrobky** [comment]
It would be an honor :) I'm on it...

**Comment by hrobky** [comment]
Pull request #323 is ready.

**Comment by sriv** [comment]
Thanks @hrobky for the contribution! - merged https://github.com/getgauge/docs.gauge.org/pull/323.

I'll mark this one as closed.

**Comment by hrobky** [comment]
Hi, @sriv, thank you for pull, but I found some rendering problems. The resulting website https://docs.gauge.org/getting_started/installing-gauge.html?os=linux&language=python&ide=vscode#step-1-installing-gauge-on-linux does not look good. (And I don't know how to reopen this issue.)

1. There is some custom markdown used which I was unable to guess the syntax for headings. ``#``, ``##``, ... did not work correctly.
I guessed ``~~~``, ``^^^``, ``===`` and they rendered correctly as h2, h3, h4 respectively in the preview.
But on the resulting website they became h3, h4, h1 and the rest of titles stopped working. (Markdown doesn't like the top heading not being the first.)

2. ``.. code-block:: console`` might be changed to ``.. code-block:: sh``. At least in my preview the lines don't get a class "go" and there is some more syntax highlighting regarding ``"`` and ``&&``.

Please, adjust the Markdown, as you might be more familiar with the dialect...

**Comment by sriv** [comment]
My bad - should have pointed that out in the review. The docs use restructuredText (https://docutils.sourceforge.io/rst.html) - I'll make the edits. Thank you for checking in.

**Comment by sriv** [comment]
Hi, I've fixed the syntax - so you should now see the subheading properly.

On the code-block - the reason we keep it to `console` is because it shows the `>` prompt properly, i.e. when you copy the command it copied over without the prompt.

**Comment by hrobky** [comment]
Works.

Just inline code doesn't render with different bgcolor, so it's harder to notice, but this might be the documentation CSS.
