### ISSUE TITLE
Vscode Find step references not working

### ISSUE THREAD

**Issue by brian316** [getgauge/gauge#1889]
**Environment**
- OS Windows 10
- vscode 1.15.1
- gauge 1.1.7
- gauge ext 0.0.19

**Describe the bug**
in vscode command pallete search and click on "Gauge: Find Step References"
It gives the following error in gauge log:
`request #11: gauge/stepReferences: failed to parse request json: cannot unmarshal array into Go value of type string`

**Comment by druzova** [comment]
The same issue for:
OS Windows 10
vscode 1.53.2
gauge 1.0.6
dotnet plugin: 0.1.2

**Bug description:**
Click on reference(s) link over Step definition. And in lsp.log file is presented:
[Gauge] [DEBUG] <-- error #161: gauge/stepReferences: {"code":0,"message":"failed to parse request json: cannot unmarshal array into Go value of type string","data":null}

**Comment by brevnovak** [comment]
same here:
win10,
vscode 1.54.3
Gauge version: 1.1.7
getgauge    0.3.15
Python 3.8.8
python plugin version for getgaugue: python (0.3.15)
getgauge.gauge extenstion for vscode: v0.0.19

lsp.log:
31-03-2021 09:24:44.986 [Gauge] [DEBUG] request #8: gauge/stepReferences: failed to parse request json: cannot unmarshal array into Go value of type string

**Comment by zabil** [comment]
A new release of Gauge (1.1.8) is out. Please try upgrading to this release to see if it solves the problem.

**Comment by druzova** [comment]
It works, thank you !

št 1. 4. 2021 o 11:18 Zabil Cheriya Maliackal ***@***.***>
napísal(a):
