### ISSUE TITLE
Add the ability to uninstall a plugin

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/gauge#189]
The [Gauge documentation on installation](http://getgauge.io/documentation/user/current/plugins/installation.html) says that you can install a plugin (`gauge --install <plugin-id>`) or update a plugin (`gauge --add-plugin <plugin-id>`), but does not list an option to uninstall a plugin. I would expect to be able to do it with the command `gauge --uninstall <plugin-id>`. The only way that I have found so far to uninstall a plugin is to manually go to the install directory and delete the plugin folder.

**Comment by sriv** [comment]
This may need some thought. How should Gauge handle projects that already refer to a plugin? Because, after uninstall, if user runs `gauge specs` against a project whose `manifest` refers to the uninstalled plugin, Gauge will re-install it. 

First thought - just print a warning, get confirmation. I think that would be a compromise on UX (uninstall would be a two step process)...

More thoughts please..

**Comment by Thunderforge** [comment]
Honestly, I had no idea that `gauge specs` would install plugins. I only did it from the command line via `gauge --install java` etc. I figure that an inverse operation, `gauge --uninstall java` would make a lot of sense. What if I installed the wrong plugin, or decided that I didn't need it any more? The only way right now is to manually go to the install directory and delete it.

This is really the use case that I am interested in. I'll leave it to others to decide what happens when `gauge specs` is run, since it's not a use case I'm interested in.

**Comment by sriv** [comment]
Scratch my previous comment, `gauge specs` does not install plugins, it just spits out an error when it does not find this plugin. I mixed things up with `gauge --init`.

Yes, we should add a `--uninstall` flag and wire it up to remove the plugin.

**Comment by navaneeth** [comment]
It will be good if plugins get notified when they are uninstalled. So that they can do necessary cleanup

**Comment by apoorvam** [comment]
@navaneeth 
Can you please elaborate on what cleanup the plugins need to do?

**Comment by navaneeth** [comment]
Cleanup could be anything. If the plugin has kept some data outside the plugin directory. When I started gauge, I was experimenting with an analytical plugin which helps to identify duplicate/similarly worded steps. It was using some natural language toolkit and was generating lot of data which was kept in a Sqlite database somewhere outside the plugin directory. So in a uninstall callback, I can delete these data.

Or make it a convention that plugins should keep data only in their own directory. So when directory is removed as part of uninstall, all data will be deleted. 

Are we providing any variables to get the directory for plugins? Maybe expose a `PLUGIN_DATA_DIR` for each plugin. Any data written outside this directory will not be cleared as part of uninstall.

**Comment by sriv** [comment]
Great tip @navaneeth, I suppose an uninstall hook would be better, IMO the plugin is the best judge on what cleanup it should do. Blind deletion of a data_dir could have consequences.
