### ISSUE TITLE
Unable to download plugins through gauge - wget or browser works fine

### ISSUE THREAD

**Issue by mikedd** [getgauge/gauge#191]
I suspect this has something to do with the networking configuration where I work, however when I run 

$ gauge install java 

I get error output like this: 
>2015/08/19 15:24:14 Downloading using wget => [wget --no-check-certificate http://raw.github.com/getgauge/gauge-repository/master/java-install.json -O /tmp/gauge_temp/java-install.json]
>--2015-08-19 15:24:14--  http://raw.github.com/getgauge/gauge-repository/master/java-install.json
>Resolving raw.github.com (raw.github.com)... 23.235.40.133
>Connecting to raw.github.com (raw.github.com)|23.235.40.133|:80... connected.
>HTTP request sent, awaiting response... 301 Moved Permanently
>Location: https://raw.github.com/getgauge/gauge-repository/master/java-install.json [following]
>--2015-08-19 15:24:14--  https://raw.github.com/getgauge/gauge-repository/master/java-install.json
>Connecting to raw.github.com (raw.github.com)|23.235.40.133|:443... connected.
>HTTP request sent, awaiting response... 301 Moved Permanently
>Location: https://raw.githubusercontent.com/getgauge/gauge-repository/master/java-install.json [following]
>--2015-08-19 15:24:15--  https://raw.githubusercontent.com/getgauge/gauge-repository/master/java-install.json
>Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 23.235.40.133
>Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|23.235.40.133|:443... connected.
>HTTP request sent, awaiting response... 200 OK
>Length: 13399 (13K) [text/plain]
>Saving to: ‘/tmp/gauge_temp/java-install.json’
...
>2015-08-19 15:24:15 (331 MB/s) - ‘/tmp/gauge_temp/java-install.json’ saved [13399/13399]
>
>15:24:15.108 [INFO] Installing Plugin => java 0.2.2
>15:24:15.108 [INFO] Downloading Plugin... => https://github.com/getgauge/gauge-java/releases/download/v0.2.2/gauge-java-0.2.2-linux.x86_64.zip
>15:24:25.713 [ERRO] java : Could not download plugin zip: Could not download File https://github.com/getgauge/gauge-java/releases/download/v0.2.2/gauge-java-0.2.2-linux.x86_64.zip: >Failed to resolve host..

If I then manually run wget : 
 $ wget https://github.com/getgauge/gauge-java/releases/download/v0.2.2/gauge-java-0.2.2-linux.x86_64.zip

The file downloads fine and I can install it manually with
$ gauge --install java -f=gauge-java-0.2.2-linux.x86_64.zip

I've tried this on Linux and I'm able to manually download the gauge-java zip file through Chrome too. 

I'm not blocked, but it does appear that there's something different about the way gauge downloads the plugins (wget?). 

This might be related to #110.

**Comment by mahendrakariya** [comment]
If `wget` command is available, Gauge simply does
```
wget --no-check-certificate <url> -O <targetFile>
```

From the logs, it is clear wget was not able to resolve host. Could you please confirm that there were no network issues on your side?

**Comment by mikedd** [comment]
Thanks for the info. I tried wget --no-check-certificate ... -O somefile and that works for me from the command line. 

Regarding network issues, I thought the same thing. But for me it fails 100% of the time through gauge and succeeds 100% of the time with wget on the command line, or a web browser. 

Is there anything else different about how gauge kicks off wget?

**Comment by mahendrakariya** [comment]
There is nothing different. Gauge simply uses golang's [exec.Cmd](https://golang.org/pkg/os/exec/#Command) to invoke `wget`. It's the same as invoking the command via command line.

**Comment by mikedd** [comment]
Our network guys say the same thing about the network config. It's a very odd side effect. In the mean time we're using wget. Thanks for your help!

**Comment by sriv** [comment]
In case this is still persisting, could you check your firewall settings? To see if `gauge` is allowed to access the network?

**Comment by mikedd** [comment]
Our network admins tell me there are no such firewall settings and I'm not running a software firewall. There is something odd here, I'll reopen the issue if I have more info, but I can't really point you at anything right now.
