### ISSUE TITLE
Blank screenshots in headless mode with custom screenshot handler from docs

### ISSUE THREAD

**Issue by DvagNic** [getgauge/gauge#1959]
**Describe the bug**
When running in headless mode, screenshots which are taken automatically when errors occur, are just white/blank. html-report plugin displays white thumbnails too.

**To Reproduce**
Steps (or project) to reproduce the behavior:

```
$ gauge init python
```
add custom screenshot handler from the docs
https://docs.gauge.org/writing-specifications.html?os=linux&language=python&ide=vscode#taking-custom-screenshots

```
$ gauge run specs
```
check .gauge/screenshots and also reports/html-report/images for blank screenshots.

**Logs**
No error messages

**Expected behavior**
When running without headless mode, screenshots are fine.

**Screenshots**
I have attached a sample blank screenshot.

![screenshotO-239293933872265253411171105262345916706](https://user-images.githubusercontent.com/50959714/114762811-6b733400-9d62-11eb-806b-eb9b21dcce9e.png)

**Versions:**

```
Gauge version: 1.1.8
Plugins
-------
html-report (4.0.12)
python (0.3.15)
screenshot (0.0.1)
```
 - macOS 11.2.3 (20D91)
 - Python 3.7.4 set via pyenv
 - VS Code but not relevant since running tests from command line
 - ChromeDriver 88.0.4324.96 (68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}) installed via homebrew
 - Chrome Version 89.0.4389.114

**Additional context**
This is how I am initializing the webdriver:
```
class Browser(object):
    
    driver = webdriver.Chrome

    @before_suite
    def init(self):
        
        my_chrome_options = webdriver.ChromeOptions()
        my_chrome_options.add_argument('--lang=de-DE')
        my_chrome_options.add_argument('--use-fake-ui-for-media-stream')
        my_chrome_options.add_argument('--use-fake-device-for-media-stream')
        my_chrome_options.add_argument('--headless')
        
        Browser.driver = webdriver.Chrome(options=my_chrome_options, executable_path=self.driver_executable_path)
        
        [...]
        
        Browser.driver.implicitly_wait(5)
        Browser.driver.set_window_size(1920, 1080)
    
    @after_suite
    def close(self):
        Browser.driver.quit()

@custom_screenshot_writer
def take_screenshot():
    image = Browser.driver.get_screenshot_as_png()
    file_name = os.path.join(os.getenv("gauge_screenshots_dir"), "screenshotO-{0}.png".format(uuid1().int))
    file = open(file_name, "wb")
    file.write(image)
    # print(os.path.basename(file_name))
    return os.path.basename(file_name)
```

**Comment by zabil** [comment]
That's strange. Can you check the output of `image = Browser.driver.get_screenshot_as_png()` to verify that screenshot isn't blank. Gauge relies on Webdriver for the actual screenshot and merely points to the screenshot file path.

**Comment by DvagNic** [comment]
I am sorry for the false alarm. I rebooted my mac and now it works... It must have been something about the webdriver as you guessed...
