### ISSUE TITLE
Ability to differentiate null and empty values in CSV table

### ISSUE THREAD

**Issue by apoorvam** [getgauge/gauge#196]
From getgauge [google groups forum](https://groups.google.com/forum/#!topic/getgauge/6TfIqU1_uVo).

**Comment by mahendrakariya** [comment]
As discussed in the [google groups thread](https://groups.google.com/forum/#!topic/getgauge/6TfIqU1_uVo), csv specification doesn't have any concept of `null` value. Hence Gauge returns an empty string.

For more detailed discussion, please refer the thread mentioned above.
