### ISSUE TITLE
Exclusion tags using "!" causing bash error

### ISSUE THREAD

**Issue by jeezyA** [getgauge/gauge#1966]
**Describe the bug**
Using ! for tag exclusion causes error due to "!" bash special character.

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Open a gauge project with tags
2. Run the gauge command with tag exclusion:
    gauge run --tags "!tagname" specs
3. See error

**Logs**
```
$ gauge run -t "!admin" specs
bash: !admin: event not found
```

**Expected behavior**
Gauge should run normally with the tags parameter.

**Versions:**

```
$ gauge -v
Gauge version: 1.1.8
Commit Hash: b1501f4

Plugins
-------
flash (0.0.2)
html-report (4.0.12)
python (0.3.15)
screenshot (0.0.1)
xml-report (0.2.3)
```
 - OS
 $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy

 - Runner info
 $ python3 --version
Python 3.8.6
 - IDE info
VS Code
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-48-generic snap

**Additional context**
Running Ubuntu VM in VirtualBox

**Comment by sriv** [comment]
`!` has a meaning in bash - to expand history. You need to escape it in your bash scripts. Try ` gauge run -t "\!admin" specs`

**Comment by jeezyA** [comment]
I'm not sure it actually worked. I run spec with '\\!admin' and I don't get the error, but the tagged specs run just the same:

![image](https://user-images.githubusercontent.com/13059778/115106350-234a4200-9f19-11eb-986b-426cf7e3fdc4.png)

Side note, the total # scenarios seems off. Is that a known issue? The log showed correct total.

**Comment by jeezyA** [comment]
fixed the issue. Was caused by bash variable expansion.
