### ISSUE TITLE
Default lib support 

### ISSUE THREAD

**Issue by william-best** [getgauge/gauge#1975]
**Is your feature request related to a problem? Please describe.**
Our team (20+ people) use gauge  to test cloud app, we should write lots of common lib. It is a hard work, because  my team members write lots of repetitive code. 

We want to  gauge give some official  lib  as robot framework.

**Describe the solution you'd like**
robot framework  lib : https://robotframework.org/#libraries

**Describe alternatives you've considered**
gauge can import  official or github lib

**Comment by sriv** [comment]
What language do you use to implement the steps/libs?

**Comment by william-best** [comment]
> What language do you use to implement the steps/libs?

Our team use Python. But there is a question - Why I choose gauge as automation framework ?  
There are more than 400+ dev in our BU, some teams use Java, some Golang,  some Python. Gauge support these language.

My suggestion:
Official lib :  all language
github lib: 
         --- Python or java :  inherit all lib from robot framework (it is the most efficient)
         --- golang : rewrite all above

**Comment by sriv** [comment]
Gauge supports multiple languages, but within a project you need to choose one. So, for example, you cannot use a lib written in python in a gauge+java project.

Gauge has support for libs, either using the package manager (ex: if you use the lib as a maven dependency and use maven to run gauge specs, it should pick the libs) or you can use `GAUGE_ADDITIONAL_LIBS` property to point to a location with the libs.

It is also worth noting that gauge is framework agnostic, but it has templates that can help write tests in a particular setup and has mechanisms to include other libraries as per the requirement. Gauge will not include libs that are not essential for it's functioning. (For instance, here Gauge does not have a need for Robot framework's libraries to function, so it won't include those, but as users you may choose to include libraries that are suitable for your test projects).

**Comment by william-best** [comment]
In my opinion:
@step("create a new file") ----- it is the lib ( or  markdown is lib)
def createFile():  ----- it is not
      xxxxxx

Everyone use 'create a new file' to create a file. 
Team members should use the same statement in a very big team. 
Example: 
  1. create a new file   
  2. create file   
  3. create a file
  4. add a file 
Devs may write like above. It is not good in a big project.

Another example: 
We want use gauge as a service. Imagine, people who donot know program (PM or customer), we give them markdown statement, they arrange them and test production.

**Comment by sriv** [comment]
If I understand correctly, you'd like gauge to support libs that package both markdown+implementation?

In that case, unfortunately it isn't possible today (could be a cool thing though!). The best you can do is use [concepts](https://docs.gauge.org/writing-specifications.html?os=linux&language=python&ide=vscode#concepts), but that is within a project and it needs to use the same implementation language.

**Comment by william-best** [comment]
yes. I will close the issue
