### ISSUE TITLE
Spec files not recognised unless plugin is re-installed

### ISSUE THREAD

**Issue by enesuzana** [getgauge/gauge#1976]
**Describe the bug**

All of my steps are marked as red after opening Intellij, with the resolution of 'Could not find step implementation', and a process called "Initializing Gauge connection" is stuck and not ending.

After un-installing the Gauge plugin,  Invalidating caches and deleting .gauge and .java files and restarting and re-installing the plugin, the specs are recognized again. Closing Intellij and opening it the next day, the same issue repeats.

I have heard from multiple people (with different Intellij versions) about this issue and this is the only workaround so far.

I have also tried un-installing other plugins, but nothing so far.

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Initialize a gauge project with maven in Intellij
2. Install Gauge plugin
2. Add some spec files in the spec folder
3. Add valid step implementations
4. Try to see if steps are recognized
5. If yes, wait a day and retry

**Expected behavior**
I expect to have the steps in the spec files recognized.

 - OS [e.g. MacOS 10.15.6 (19G2021) please be specific ]
 - Runner info (Please specify the correct version of Java/Node/Python/Dotnet/Ruby)
 - IDE info (If using VS Code or Intellij IDEA)

**Additional context**
Gauge version: 1.1.8

Plugins
-------
html-report (4.0.12)
java (0.7.13)
screenshot (0.0.1)

In pom.xml:
<gauge-java.version>0.7.13</gauge-java.version>

Intellij: 2021.1

OS: Windows 10 Pro

**Comment by sriv** [comment]
hi, it seems like this could be something to do with the gauge-intellij plugin, which is not maintained by JetBrains.

Can you please report this here: https://youtrack.jetbrains.com/issues/IDEA?

**Comment by enesuzana** [comment]
Hello @sriv,
I opened the issue https://youtrack.jetbrains.com/issue/IDEA-268198. Thank you for the reply!
