### ISSUE TITLE
Multiple step names inside a step annotation not implemented for IntelliJ IDE

### ISSUE THREAD

**Issue by uzmar** [getgauge/gauge#198]
"The same implementation can point to multiple step names. To do this add all the step name template to the @Step annotations."  right now not implemented for IntelliJ IDE

**Comment by Thunderforge** [comment]
If this is an Intellij issue, I think it should be filed in the GitHub project for the [Gauge Intellij-Plugin](https://github.com/getgauge/Intellij-Plugin).

**Comment by mahendrakariya** [comment]
This issue was moved to getgauge/Intellij-Plugin#103
