### ISSUE TITLE
Official Debian repository was sunset

### ISSUE THREAD

**Issue by ebastos** [getgauge/gauge#1986]
**Describe the bug**
The official documentation point that Gauge should be installed from a Debian repository which is not longer available.

**To Reproduce**
```
sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B
echo deb https://dl.bintray.com/gauge/gauge-deb stable main | sudo tee -a /etc/apt/sources.list
sudo apt-get update
Err:9 https://dl.bintray.com/gauge/gauge-deb stable InRelease
403  Forbidden [IP: 52.41.30.229 443]
E: Failed to fetch https://dl.bintray.com/gauge/gauge-deb/dists/stable/InRelease  403  Forbidden [IP: 52.41.30.229 443]
E: The repository 'https://dl.bintray.com/gauge/gauge-deb stable InRelease' is no longer signed.
```

**Screenshots**
The Bintray service is sunset:
![image](https://user-images.githubusercontent.com/1567940/117714913-986e0780-b1a5-11eb-9b47-b5c225f8ee40.png)

**Comment by sriv** [comment]
packagecloud.io is an option, and they have a free tier for OSS projects: https://packagecloud.io/pricing

However, there is no certainty that it will not go the bintray route.

**Comment by zabil** [comment]
Yeah. I also think as gauge has no depedencies maybe using curl is a good alternative. The only change is manual updation whenever there are upgraded, not ideal, but not that tough either.
