### ISSUE TITLE
Got fatal error once  with IntelliJ IDE while doing random testing

### ISSUE THREAD

**Issue by uzmar** [getgauge/gauge#199]
<img width="1084" alt="intellij_fatal_error" src="https://cloud.githubusercontent.com/assets/10433272/9650963/a2fc0712-5227-11e5-9893-8ef9bb9489aa.png">

Note: I have put 2 starts(**) before step name in .spec file then suddenly got this error. but  when tried same again ,it didn't happen.

**Comment by kashishm** [comment]
This issue was moved to getgauge/Intellij-Plugin#106

**Comment by sguptatw** [comment]
The following scenarios have an issue
```
one
===
Scenario Heading
----------------
** def
In between
----------
* abc
```

Unable to refactor * def

```
one
===
Scenario Heading
----------------
* * def
In between
----------
* abc
```
On refactoring `* def` to `* def to something` it adds a new star at the beginning.
```
one
===
Scenario Heading
----------------
* ** def to something
In between
----------
* abc
```

**Comment by sguptatw** [comment]
adding more comments to the other issue
