### ISSUE TITLE
Error installing on Ubuntu

### ISSUE THREAD

**Issue by ecarvalho-olisipo** [getgauge/gauge#1990]
**Describe the bug**
After adding the repository, key, `apt-get update` and install, I got an error. 

**To Reproduce**
Steps (or project) to reproduce the behavior:

```
sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B
echo deb https://dl.bintray.com/gauge/gauge-deb stable main | sudo tee -a /etc/apt/sources.list
sudo apt-get update
sudo apt-get install gauge
```

**Logs**

```
#8 1.384 Err:4 https://dl.bintray.com/gauge/gauge-deb stable InRelease
#8 1.384   403  Forbidden [IP: 18.196.181.147 443]
```

**Comment by zabil** [comment]
Thanks for reporting this.

The debian repo is no longer support as the host bintray dropped support. 
New instructions for installing are available here 
https://docs.gauge.org/getting_started/installing-gauge.html?os=linux&language=javascript&ide=vscode
