### ISSUE TITLE
Gauge retry configuration at run time -  retry only if test failed due to environment issues not the script failed due to application assertions

### ISSUE THREAD

**Issue by hcsan** [getgauge/gauge#1996]
Hi Team

is there any way users can conditionally retry the failed test instead of retry running all scripts . If I know in my test fails because of known issue we are filtering  those by tags .many times scripts fails due to assertions errors I don’t want to rerun those.  Is there any way we can achieve this? Please let me know your thoughts. I mean based the condition can we update the flag without impacting global flag , as I need to keep this retry flag enabled for further execution 

thanks 
Shc

**Comment by sriv** [comment]
hi @hcsan - at present Gauge does not know/analyze the cause of failure, i.e. assertion failure v/s other exceptions are treated as failure. Hence, there is no ability to set retry configuration based on the type of failure. 

wrt the ability to set it at runtime, unfortunately that also isn't possible.

**Comment by hcsan** [comment]
Thanks for the response @sriv is there any way to Merge the gage reports after rerun failed ?

**Comment by sriv** [comment]
There's no support to merge reports in Gauge, unfortunately. But if you are using xml-report/json-report the output can be manipulated to get a consolidated report (i.e. by merging xml/json)
