### ISSUE TITLE
Gauge CLI not working on Apple Silicon (M1)

### ISSUE THREAD

**Issue by Bonitas** [getgauge/gauge#1997]
**Describe the bug**
Running Gauge does not work on the Apple Silicon. Executing any Gauge command does nothing. No message is printed and no action done. 

I tried node v16.1.0 (npm v7.11.2) and node v14.17.0 (npm v6.14.13) 
Installed gauge via npm and homebrew.

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Install gauge cli via homebrew or npm 
2. Run the gauge command
3. See no output at all

**Expected behavior**
I would expect that the gauge cli works as on any other OS.

**Screenshots**
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/1462342/118379411-724bcb80-b5da-11eb-9a01-65f2761a1569.png">

**Additional context**
 - MacOS 11.3.1 Apple M1 Chip
 - Node Runner
 - IDE: VS Code

**Comment by zabil** [comment]
@sriv this will need a release right?

**Comment by sriv** [comment]
@zabil - yes! This will need a release

@Bonitas - I'll need some time to check the PR on my m1 machine (which isn't my primary). Thanks for raising this.

Strangely enough, gauge seems to be working fine on rosetta2 on my machine. But this is something that needs to be done nevertheless.

I expect homebrew to handle this via their bottling, so not much needs to be done at gauge's side. The `go get` install should work without any change. npm, pkg and zip installers need to be addressed here.

**Comment by sriv** [comment]
@zabil - our build failed because the windows cert expired :(  - https://github.com/getgauge/gauge/runs/2644147665?check_suite_focus=true

**Comment by zabil** [comment]
Do we need the certs if we migrate to just a choco package?

**Comment by sriv** [comment]
our choco package is a wrapper over the installer (i.e. it downloads the installer and invokes it in silent mode).

The signing process was done because of two reasons - 1) without signing windows would bring a popup everytime warning the user 2) sometimes antiviruses seem to flag gauge executable, which hasn't happened for a while, possibly because of the signed binaries.

we could simply stop signing and watch for these issues (they were reported years ago, so quite a few things have changed)

**Comment by sriv** [comment]
I looked around and there is no option that I could find that is either free or has some open source sponsorship plan for code signing certificate.

The only way to make the release is to stop signing binaries. Note that we may have to stop signing the jars as well (gauge-java uses it IIRC).

I am going to remove signing from the gauge build. @zabil - is that ok?

**Comment by zabil** [comment]
Yes that's ok. I don't think it's easy to keep maintaining the certs. I hope we can publish checksums of the binary so that users can verify the download. I guess windows must have a way of adding Gauge to some kind of a trusted app list.
