### ISSUE TITLE
error for step implementation is not proper

### ISSUE THREAD

**Issue by uzmar** [getgauge/gauge#200]
when step is not implemented ,console gives error for it but error msg says "[WARN]". that is like confusing user. It should be with proper message.

<img width="567" alt="screen shot 2015-09-03 at 10 43 52 am" src="https://cloud.githubusercontent.com/assets/10433272/9651043/bc670d22-5228-11e5-9fae-5442f4f789bb.png">

**Comment by Thunderforge** [comment]
What are you expecting the message to say? I don't understand what the problem is with the current message.

**Comment by deepthigc** [comment]
@uzmar Are you referring to the fact that it says [WARN] instead of [ERROR]? 

We're not sure if an unimplemented step should be reported as an [ERROR] or a [WARNING]. We're tending towards warning because the test hasn't actually been executed, and therefore it isn't technically an error.

**Comment by Thunderforge** [comment]
@deepthigc I personally would vote for an unimplemented step to be an [ERROR] for an unimplemented step because it prevents a spec from running. [WARN] feels more appropriate for marking potentially problematic behavior, but will still allow for a spec to be executed.

**Comment by kashishm** [comment]
Gauge([0.2.0](https://github.com/getgauge/gauge/releases/tag/v0.2.0) & above) shows unimplemented step as an [ERROR] and skips the scenario/spec containing unimplemented step.
