### ISSUE TITLE
[Multiple step names]No suggestion to implement new step along with existing one on IDE

### ISSUE THREAD

**Issue by uzmar** [getgauge/gauge#201]
there should be some suggestion when trying to implement new step e.g 'add step' at spec level l,so that  user can choose same existing step implementation 

<img width="508" alt="screen shot 2015-09-03 at 4 36 34 pm" src="https://cloud.githubusercontent.com/assets/10433272/9657036/2ad0463e-525b-11e5-9241-b5b27e0152bb.png">

**Comment by sriv** [comment]
This issue was moved to getgauge/gauge-visualstudio#106
