### ISSUE TITLE
want expression support for tags while using along with hooks

### ISSUE THREAD

**Issue by uzmar** [getgauge/gauge#202]
There should be expression support for tags while using along with hooks like
 [BeforeSpec("TagA" & "TagB")]

current behaviour is:  user has to set this value

<img width="416" alt="tagaggregation" src="https://cloud.githubusercontent.com/assets/10433272/9679250/9b254736-530a-11e5-9a9d-e967e464ab14.png">

**Comment by zabil** [comment]
Gauge won't be adding this feature.
