### ISSUE TITLE
Allow customizing the location (and name) of the "env" directory

### ISSUE THREAD

**Issue by joelmukuthu** [getgauge/gauge#2025]
**Is your feature request related to a problem? Please describe.**
In some cases, it's desirable to not have the "env" directory (containing .properties files for various environments) at the project root, particularly in monorepos. "env" is also quite generic and could lead to conflicts/confusion in a team. 

**Describe the solution you'd like**
The location of the "env" directory could be configured as a CLI flag to `gauge run` e.g. `gauge run --env-dir foo/bar/baz --env ci` or as an environment variable e.g. `GAUGE_ENV_DIRECTORY=foo/bar/baz gauge run`. The choice between "dir" vs "directory" is up to your discretion or the current standards. The value itself could follow the same conventions as other path-like settings i.e. either as an absolute path or as a path relative to the project root.

**Describe alternatives you've considered**
- Allow loading default env directory from `.gauge/env` (in the project root).

**Additional context**
The same feature would be nice for `manifest.json` i.e. either allow customizing its location or also support loading it from `.gauge` inside the project.

**Comment by sriv** [comment]
Thank you for the suggestion. 

Of the options you propose, I personally favour the environment variable approach, for two reasons:

- it is consistent with how gauge allows configuration of specs/implementations/logs etc.
- the `--env` flag is already in use and adding another flag to specify the env dir makes it a bit verbose.
