### ISSUE TITLE
Support for CSV file per environment. 

### ISSUE THREAD

**Issue by alpha1592** [getgauge/gauge#2046]
## Problem:
We use CSV files for Test Data extensively in our Gauge Tests. Its a very nice feature, especially when you can loop thru the various rows and run many different situations using only a few test scenarios defined in the spec files. 

The Issue is that CSV files are hard coded in the spec files, and this is a source of a lot of issues. We have many test environments (dev, test, staging, pre-prod, uat). Unfortunately, the data is not the same in each environment. 

One CSV is not suitable for all the environments. This leaves us with having multiple test specs for each environments.
When you have 1000s of tests, multiplied by the number of environments, it causes a lot of unnecessary duplication and maintenance. 

It also defeats the environments feature of Gauge, which I believe is one of the most important feature of the framework. 

This is not a new issue. It has been requested before; and unfortunately ignored. This is a fundamental issue. 
I think this issue needs to be given importance as this issue has come up many times before. We ask our testers to develop tests that are environment agnostic and data driven, but then we cannot support their effort because of this flaw. Test data is a major aspect of the environments feature and it needs to be supported. 

I have also implemented my own JSON data source which can be used in tests. However, I cannot offer the looping functionality (of rows) that I get with the CSV data source. I cannot leverage the tagging functionality either, because the data per environment is different. I cannot say run all tests tagged with `sanity` tag along with specifying the environment `--env staging` and have the test pick up the correct data. CSV file reference is hard coded.

Currently, we are unable to use the environments functionality as we would like and have had to duplicate our tests in order to test on our various environments. I know this feature presents a technical challenge for the team, but it is also a big issue that needs a solution. 

I use Gauge with Java, Maven and Spring. I have not come across any reasonable work around to this issue. 

## The Ask:
Provide an Environments ready Test data source that allows us to loop thru a set of data. 

We define one test scenario, give it a data source of 100 records and press play. You have 100 Tests completed. Add additional data sources to account for environment changes and you are golden. CSV data source matches most of those requirements with the exception of the hard coded path to the csv file. 

## Possible Solution(s):

* Add the ability to add a reference to the environment in the csv file path.
* * `table: /env/${env}/data/mydata.csv`
* Add Filtering functionality on the CSV file so we can determine which rows to use for a scenario.
* * Table-rows functionality that already exists isn't all the useful. It relies on knowing the exact location of your data in every csv file and cannot be used when running multiple scenarios/spec files. 
* * Having a filtering option will check a row against a condition and either include the row or exclude it.
* * `table: /env/default/data/mydata.csv:env==staging`
* * Here the `env` is a column header inside the CSV file and `staging` is the value we are looking for in the column to include the data in the test.
* Add support for Excel file `.xlsx` as a data source. Gauge can use worksheet name to pick up the correct test data per environment.
* * `table: /env/default/mydata.xlsx`
* * create worksheet with name `staging` and add all data related to staging environment in there.
* * loop thru all the data on the `staging` worksheet. 
* Add the ability to loop the scenario on a list or set of data on demand.
* * Allow us to implement some sort of interface that will return a list of records that gauge can then loop thru.
```
interface TestDataSource
{
    List getTestData(ScenarioName)
}
```

Please Find a solution to this issue. We would really appreciate it. 

```
Gauge version: 1.2.1
Commit Hash: fa7918b

Plugins
-------
html-report (4.0.12)
java (0.7.15)
json-report (0.3.5)
screenshot (0.0.1)
```

**Comment by 0vid1u** [comment]
Hi @alpha1592,
we had the same problem and fixed it implementing with spring AOP a joinpoint to all methods witch are annotated with @Step and intercepting the method arguments, we are checking the argument type to be instance of Table, now we can manipulate the table rows as we want and return a new table filtered by environment, as use case example. That's involve to have a column dedicated to env inside csv. 

I hope this approach will help you.

**Comment by alpha1592** [comment]
@0vid1u Thanks for your comment. 
I would really appreciate it if you can provide some code snippets that would allow me to set that up.

also, do you have to pass in the csv file to all your steps?

**Comment by 0vid1u** [comment]
I can provide more details about implementation...

First of all, to be able to use Spring AOP add dependencies:
```
<dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aop</artifactId>
            <version>your-spring-version</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aspects</artifactId>
            <version>your-spring-version</version>
        </dependency>
```
Next step is to implement the aspect class:

```
@Aspect
@Component
public class StepsAspect {

    @Around("@annotation(com.thoughtworks.gauge.Step)")
    public Object interceptStep(ProceedingJoinPoint joinPoint) throws Throwable {

        Object[] args = joinPoint.getArgs();

        args = processArguments(args);

        try {
            return joinPoint.proceed(args);
        } catch (UndeclaredThrowableException e) {
            if (e.getCause() != null) {
                RuntimeException r = new RuntimeException(e.getCause());
                r.setStackTrace(e.getCause().getStackTrace());
                throw r;
            }
            throw e;
        }

    }

    private Object[] processArguments(Object[] args) {
        if (args != null) {
            for (int i = 0; i < args.length; i++) {
                Object a = args[i];
                if (a instanceof Table) {
                    Table initialTable = (Table) a;
                    args[i] = yourTableFilterClass.filterByEnvironment(initialTable);
                }
            }
        }

        return args;
    }
}
```

The final step is to implement the ```filterByEnvironment(Table table)```

**Comment by 0vid1u** [comment]
@alpha1592 and what do you mean by passing the csv file to all steps?
As I know in gauge there's two options for this, to pass a table as a step parameter and in case of data-driven scenarios the table is declared on top. The above code snippet works great for tables passed to steps. I'm pretty sure, the spec table can be intercepted by the same method, just is needed a deep dive in gauge-java implementation to find the join point.

**Comment by sriv** [comment]
Hi @alpha1592 ,

> This is not a new issue. It has been requested before; and unfortunately ignored. This is a fundamental issue.
I think this issue needs to be given importance as this issue has come up many times before.

Agreed. This has been in discussion a few times and I'll admit there is no answer here yet. Apologies for the trouble this has caused!

> We have many test environments (dev, test, staging, pre-prod, uat). Unfortunately, the data is not the same in each environment.

I can understand. I have an idea that is fairly easy to implement (in fact I already have a PR #2047), and could perhaps help. 

Basically, gauge would (potentially!) now have a new property-> `gauge_data_dir` that defaults to `.` (or current directory), which will be resolved to the project root. So if you do not use/set this property, the behaviour should be same as now. 

The idea is that your environment properties would each set this to a unique location where your env specific data files can reside.

See [my comment](https://github.com/getgauge/gauge/pull/2047#issuecomment-880908270) on #2047 for a sample project illustrating this feature and gauge builds that would support this.

Please feel free to post feedback on the PR itself!

**Comment by alpha1592** [comment]
@0vid1u Thats for providing code snipped to help with this. I really appreciate it.

The comment about the table being passed in to each step, I meant the code you provided may not work if you had 
`table: some.csv` 
defined at the top of the Spec. This approach would work if you passed in the csv file as an input to the step like following...

``` * Go to URL <file: some.csv>```

and implementation...

```
@Step("Go to URL <table>")
public void gotoUrl(Table table)
{
    // implement step here
}
```
In the case above, Spring would intercept the \@Step implementation and would allow you to change the table. 
Just wanted to clarification on that.

**Comment by alpha1592** [comment]
@sriv Thats an excellent idea as well. 
Using environment variables, we can override the value and change it at runtime.

```
# Spec file

table: some.csv

```
Default:
```
gauge_data_dir=
```

Override:
```
gauge_data_dir=/env/dev/data
```
so the file would picked up from `/env/dev/data/some.csv`
I would definitely support that.

**Comment by sriv** [comment]
Thanks for the feedback @alpha1592 . The PR I mentioned does exactly that, except for a minor difference - `gauge_data_dir` is set to `.` (i.e. current directory) by default, so that it resolves to the project root when not specified, thus preserving current behaviour.

I would request you to try the build in the PR (links in the PR comment) and let me know how it goes. I am particularly keen to know if this change breaks any other workflow, and also if there are other things we need to add to get this merged.
