### ISSUE TITLE
images/screenshots and static contents in the Gauge HTML Report is broken

### ISSUE THREAD

**Issue by sankarasai18-gauge** [getgauge/gauge#2056]
**Describe the bug**
Hi, I am unable to view the images/screenshots and static contents in the Gauge HTML Report when I access the gauge html report. I am using the below versions of gauge, plugins and taiko. Please help me to fix this issue. TIA!

```
gauge -v
Gauge version: 1.0.7
Commit Hash: ed7b4fd6
Plugins
-------
html-report (4.0.12)
js (2.3.16)
json-report (0.3.5)
reportportal (1.12.0)
screenshot (0.0.1)
xml-report (0.2.3)

taiko -v
Version: 1.0.5 (Chromium: 81.0.3994.0) RELEASE

```

**Comment by zabil** [comment]
Please upgrade to 
the latest version of gauge v1.3.3
Latest version of html report - 4.1.0
Later version of Taiko - 1.2.5

**Comment by sankarasai18-gauge** [comment]
Thank you, We have some challenges in our framework which doesn't support the latest versions. In other machines where we have setup the framework, we are able to view the reports properly with the images/screenshots and it has same above versions.

**Comment by zabil** [comment]
> Hi, I am unable to view the images/screenshots and static contents in the Gauge HTML Report when I access the gauge html report.

Can you provide more details about this problem. Which environment are you seeing this in? Is there some sample or screenshots of the problem or some way to replicate it?

**Comment by sankarasai18-gauge** [comment]
> > Hi, I am unable to view the images/screenshots and static contents in the Gauge HTML Report when I access the gauge html report.
> 
> Can you provide more details about this problem. Which environment are you seeing this in? Is there some sample or screenshots of the problem or some way to replicate it?


Thanks again for looking into this issue.
sure, I am trying to run the scripts on a ubuntu box through the jenkins setup and when I access the reports URL from a different box (within the local network) I am not getting images/screenshots properly and the page gets displayed as below.

**Report from a different machine (within LAN)**
![image](https://user-images.githubusercontent.com/82411044/126871453-4288c018-d90e-4ac1-8ce6-0c2fc75698d9.png)

And when I try to access the reports from the same machine I get few images/static contents on the reportUI except the actual application screenshot. Please refer the below screenshot.

**Report from  the actual Ubuntu box**
![image](https://user-images.githubusercontent.com/82411044/126871593-105e8289-1fbb-44ae-8db3-06cbfe1295a0.png)

**Comment by zabil** [comment]
There's a setting in Jenkins to solve this. For more info please refer
https://github.com/getgauge/html-report/issues/219#issuecomment-478676959

**Comment by sankarasai18-gauge** [comment]
Thanks a ton for the above solution, For some reason the solution is working on incognito mode of google chrome and FF and not on normal google chrome browser session. Also I am still not getting the screenshots images in the reports.

**Comment by zabil** [comment]
The 403 code is definitely a server side error. This is an issue with Jenkins or wherever you are hosting the report. Please check if there any other setting on the Jenkins server that needs to be enabled/disabled to fix this.

**Comment by sankarasai18-gauge** [comment]
Ok, thanks a lot again. Looks like the above command helped me to get the reports without any further issues. 🙇 

I have another issue in this. Somehow the screenshots are not getting generated and displayed in the reports html page and for me I am getting the screenshots under the folder-images with the screenshot address as (**/reports/html-report/images/screenshot-*.png**) and but for my friend he gets the screenshots images displayed on the reports html with address as "**data:image/png;base64,**". and for screenshots we are using the below code and with the below addons.

`gauge.screenshotFn = async function () {
    return await screenshot({ encoding: "base64" });
`

```
gauge -v
Gauge version: 1.2.1
Commit Hash: fa7918b
Plugins
-------
html-report (4.0.12)
js (2.3.16)
json-report (0.3.5)
reportportal (1.12.0)
screenshot (0.0.1)
xml-report (0.2.3)

taiko -v
Version: 1.0.3 (Chromium: 81.0.3994.0) RELEASE
```
