### ISSUE TITLE
Unable to view screenshots in the html reports 

### ISSUE THREAD

**Issue by sankarasai18-gauge** [getgauge/gauge#2058]
The screenshots are not getting displayed in the reports html page and the screenshots are getting generated under the folder-images with the screenshot address as (/reports/html-report/images/screenshot-*.png) and but for my friend he gets the screenshots images displayed on the reports html without any issues and the when we do a right click we get the address as "data:image/png;base64," and for screenshots we are using the below code and with the below addons.

Please help me to fix this issue. TIA!

`gauge.screenshotFn = async function () { return await screenshot({ encoding: "base64" });
`
```
gauge -v
Gauge version: 1.2.1
Commit Hash: fa7918b
Plugins
-------
html-report (4.0.12)
js (2.3.16)
json-report (0.3.5)
reportportal (1.12.0)
screenshot (0.0.1)
xml-report (0.2.3)

taiko -v
Version: 1.0.3 (Chromium: 81.0.3994.0) RELEASE
```

**Comment by sankarasai18-gauge** [comment]
@zabil can I get some help on this please?. TIA!

**Comment by zabil** [comment]
Gauge changed the screenshot implementation post [release 1.0.7](https://github.com/getgauge/gauge/releases/tag/v1.0.7). Unfortunately the old base 64 feature is deprecated and not supported anymore. It will be very hard to debug this without a clear sample project and example. If you can please try upgrading to the latest version. Or make sure the version of software you are using matches in both machines.

**Comment by sankarasai18-gauge** [comment]
Ok, do you mean I have to update to latest gauge version? I already have gauge 1.2.1 version.

**Comment by zabil** [comment]
* Please upgrade gauge and html report plugin to the latest versions
* Refer [taking screenshots](https://docs.taiko.dev/taking_screenshots/#taking-screenshots-with-gauge) to update you code to use the right way of taking screenshots.

**Comment by sankarasai18-gauge** [comment]
Thanks @zabil for your quick response

**Comment by sankarasai18-gauge** [comment]
Thanks, I tried again by upgrading the gauge, taiko and html-report to the latest version as below. I am still not able to view the screenshot images through the jenkins run but can view the screenshots when I run the scripts directly from the ubuntu box terminal . 

I found one observation beween the above 2 rums and some how the screenshots path is different for the jenkins run with 2 folders (specs/proc/) are getting added into the screenshots path as below.

**Screenshots file path through jenkins run** : http://<machinename>/job/<jobname>/ws/reports/html-report/specs/proc/images/screenshot-2465888675949776.png

**Screenshots file path from ubuntu box Terminal run** : file://<FrameworkPath>/reports/html-report/images/screenshot-2465185606851438.png

Could you please take a look into the below and let me know. TIA!

**Comment by sriv** [comment]
What is `gauge_screenshots_dir` in your jenkins job?

Are you able to see the screenshot in Jenkins report using a link without `specs/proc`? ex:  http:///job//ws/reports/html-report/images/screenshot-2465888675949776.png ?

It'd be much easier for us to troubleshoot if you had a sample project to share...

**Comment by sankarasai18-gauge** [comment]
Thanks Sriv, As per the gauge.log, I have the below path for **_gauge_screenshots_dir_** and also I am able to find the actual screenshot file in this folder path (/var/lib/jenkins/workspace/<JobName>/.gauge/screenshots/) 

Yes, by removing the folders **_/specs/proc/_** (http:///job//ws/reports/html-report/images/screenshot-2465888675949776.png)  I am able to access the screenshots files successfully. 
Please find the below details and gauge.log as well.

**gauge_screenshots_dir from gauge.log**
29-07-2021 19:36:32.735 [Gauge] [DEBUG] Created gauge_screenshots_dir at /var/lib/jenkins/workspace/<JobName>/.gauge/screenshots

**gauge.log**
```
29-07-2021 19:36:32.735 [Gauge] [DEBUG] Created gauge_screenshots_dir at /var/lib/jenkins/workspace/<JobName>/.gauge/screenshots
29-07-2021 19:36:32.735 [Gauge] [DEBUG] Plugin js is already installed.
29-07-2021 19:36:32.735 [Gauge] [DEBUG] Plugin html-report is already installed.
29-07-2021 19:36:32.735 [Gauge] [DEBUG] Plugin json-report is already installed.
29-07-2021 19:36:32.735 [Gauge] [DEBUG] Parsing started.
29-07-2021 19:36:32.735 [Gauge] [DEBUG] Started concepts parsing.
29-07-2021 19:36:32.769 [Gauge] [DEBUG] 0 concepts parsing completed.
29-07-2021 19:36:32.769 [Gauge] [DEBUG] Started specifications parsing.
29-07-2021 19:36:32.770 [Gauge] [DEBUG] 1 specifications parsing completed.
29-07-2021 19:36:32.770 [Gauge] [DEBUG] Parsing completed.
29-07-2021 19:36:33.201 [Gauge] [DEBUG] Attempting to connect to grpc server at port: 45487
29-07-2021 19:36:33.202 [Gauge] [DEBUG] Successfully made the connection with runner with port: 45487
29-07-2021 19:36:33.202 [Gauge] [DEBUG] Validation started.
29-07-2021 19:36:33.210 [Gauge] [DEBUG] Validation completed.
29-07-2021 19:36:33.210 [Gauge] [DEBUG] Run started
29-07-2021 19:36:33.210 [Gauge] [DEBUG] Starting Html Report plugin
29-07-2021 19:36:33.213 [Gauge] [DEBUG] Attempting to connect to grpc server at port: 45521
29-07-2021 19:36:33.213 [Gauge] [DEBUG] Successfully made the connection with plugin with port: 45521
29-07-2021 19:36:33.214 [Gauge] [DEBUG] Starting JSON Report plugin
29-07-2021 19:36:33.215 [Gauge] [DEBUG] Established connection to JSON Report plugin
29-07-2021 19:36:33.215 [Gauge] [DEBUG] Initialising suite data store.
29-07-2021 19:36:33.684 [Gauge] [DEBUG] Checking updates...
29-07-2021 19:36:33.684 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/html-report?l=js&p=html-report,js,json-report,reportportal,screenshot,xml-report&o=linux&a=amd64
29-07-2021 19:36:34.250 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/js?l=js&p=html-report,js,json-report,reportportal,screenshot,xml-report&o=linux&a=amd64
29-07-2021 19:36:34.444 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/json-report?l=js&p=html-report,js,json-report,reportportal,screenshot,xml-report&o=linux&a=amd64
29-07-2021 19:36:34.668 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/reportportal?l=js&p=html-report,js,json-report,reportportal,screenshot,xml-report&o=linux&a=amd64
29-07-2021 19:36:34.912 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/screenshot?l=js&p=html-report,js,json-report,reportportal,screenshot,xml-report&o=linux&a=amd64
29-07-2021 19:36:35.137 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/xml-report?l=js&p=html-report,js,json-report,reportportal,screenshot,xml-report&o=linux&a=amd64
29-07-2021 19:41:07.319 [html-report] [DEBUG] Transformed SuiteResult to report structure
29-07-2021 19:41:07.335 [html-report] [INFO] Successfully generated html-report to => /var/lib/jenkins/workspace/<JobName>/reports/html-report/index.html
29-07-2021 19:41:07.335 [html-report] [DEBUG] Done generating HTML report using theme from /var/lib/jenkins/.gauge/plugins/html-report/4.0.9/themes/default
29-07-2021 19:41:07.336 [Gauge] [DEBUG] Sending kill message to JSON Report plugin.
29-07-2021 19:41:07.336 [Gauge] [DEBUG] Sending kill message to Html Report plugin.
29-07-2021 19:41:07.336 [json-report] [INFO] Successfully generated json-report to => /var/lib/jenkins/workspace/<JobName>/reports/json-report
29-07-2021 19:41:07.436 [Gauge] [DEBUG] Plugin [JSON Report] with pid [28661] has exited
29-07-2021 19:41:07.642 [Gauge] [DEBUG] Runner with PID:28631 has exited
29-07-2021 19:41:07.642 [Gauge] [INFO] Specifications:	1 executed	0 passed	1 failed	0 skipped
29-07-2021 19:41:07.642 [Gauge] [INFO] Scenarios:	    1 executed	0 passed	1 failed	0 skipped
29-07-2021 19:41:07.642 [Gauge] [INFO] 
Total time taken: 4m34.108s
29-07-2021 19:41:07.642 [Gauge] [INFO] Updates are available. Run `gauge update -c` for more info.
```

**Comment by sriv** [comment]
Looks like the report html is looking for screenahot images relative to it's path rather than the root folder. Can you try without setting `gauge_screenshots_dir`?  It ahould pick defaults

**Comment by sankarasai18-gauge** [comment]
I am not getting where exactly the setting gauge_screenshots_dir is hard coded in the frame work and I am still trying to find it. We just have only the below code.

```
const path = require('path');
gauge.customScreenshotWriter = async function () {
    let gauge_screenshots_dir;
    gauge_screenshots_dir = '';
    const screenshotFilePath = path.join(process.env['gauge_screenshots_dir'], `screenshot-${process.hrtime.bigint()}.png`);
    await screenshot({ path: screenshotFilePath });
    return path.basename(screenshotFilePath);
};
```

**Comment by sriv** [comment]
It could be set as an environment variable in your jenkins pipeline. Or if you are running using `--env` flag then you may want to check the `env` folder, the properties files may have this set.

**Comment by sankarasai18-gauge** [comment]
Yes, I already checked in the env pipeline/properties file and we don't have this settings (gauge_screenshots_dir) and we just have only the setting (screenshot_on_failure) to enable or disable screenshot as below.

```
# Set to false to disable screenshots on failure in reports.
screenshot_on_failure = true
```

**Comment by sankarasai18-gauge** [comment]
@zabil @sriv could you please help me to resolve this issue?. TIA!

**Comment by sankarasai18-gauge** [comment]
@zabil @sriv could you please help me to resolve this issue?. TIA!

**Comment by sriv** [comment]
Unfortunately, there's nothing much we can do without a way to replicate this. If you have a sample project that can help, I can spend some time to figure out a cause.

**Comment by sankarasai18-gauge** [comment]
ok np, thank you!
