### ISSUE TITLE
Expose the selected gauge environment as an environment variable

### ISSUE THREAD

**Issue by alpha1592** [getgauge/gauge#2067]
**Is your feature request related to a problem? Please describe.**
When you run gauge with a `--env` flag, the selected environment is not accessible to the test.
In our case, we load property files, data files, keystores and other resources based on the environment. 
We store all the files under the env folder. When the user specifies the `--env` flag to gauge, my Java project does not know where to look for the additional files. we therefore have to define another env variable called `app_env` to get the other resources to load correctly. If the `--env` flag value can be published as an environment variable like `gauge_runtime_env`, then we can use that in the Java program automatically without an additional property being added by the user; which is subject to human error. 

env
 - default
 - test
 - uat
 - prod

**Describe the solution you'd like**
Expose an environment variable called `gauge_runtime_env` and provide the selected environment by the user. 

**Describe alternatives you've considered**
we currently use another property called `app_env` which is supposed to be the exact same value as `--env` flag. Sometimes, users enter the value differently and it causes a lot of headache. 
`--env test`
`-Dapp_env=uat`

**Additional context**
I use Gauge with Maven, Java and Spring.

**Comment by sriv** [comment]
This exists today. `gauge_environment` environment variable should expose the `--env` arg passed into `gauge run`.

**Comment by alpha1592** [comment]
That’s wonderful to hear. I am sorry, I must have missed this in the documentation.

I’ll give this a try tomorrow and provide feedback.

thanks

**Comment by sriv** [comment]
Actually, we missed documenting this. Sorry about that. I've added a note here: https://docs.gauge.org/configuration.html?os=macos&language=javascript&ide=vscode#run-a-gauge-specification-with-an-environment

**Comment by alpha1592** [comment]
Thanks for the updated documentation. 

`gauge_environment` works like a charm. 

Perfect. Thanks :)

**Comment by alpha1592** [comment]
Thanks for the updated documentation. 

`gauge_environment` works like a charm. 

Perfect. Thanks :)

**Comment by alpha1592** [comment]
Closing this request.
