### ISSUE TITLE
Step implementation not found  error, even-though steps are defined properly

### ISSUE THREAD

**Issue by PrashinkaS** [getgauge/gauge#2071]
Did setup into a new Mac system and started getting “Step not found” issue for a few steps, the same tests working fine in other system as well as CircleCI tool.

What command(s) did you run when you found the bug?

Run the test using Run scenario or run through command “bundle exec gauge run --env env_property_file_name path_for_spec_file:line number for test to execute.

Also [if](url) we open the class file having step definition method for the highlighted steps, it stops showing the error. However if we try to run the test its not able to find the step definitions and skips the test. 
<img width="1792" alt="Screenshot 2021-08-09 at 10 09 11 PM" src="https://user-images.githubusercontent.com/63770860/128855972-8b7eb515-1554-445d-b620-152911d16465.png">
<img width="1055" alt="Screenshot 2021-08-09 at 10 29 17 PM" src="https://user-images.githubusercontent.com/63770860/128855998-19364bcb-a9e5-41ae-8c06-f4995f9c5b55.png">

Output, stack trace or logs related to the bug
==========
Running tool: gauge run /Users/prashinkasahu/src/system-tests/specs/care_mgmt/payer_population/mark_as_error_form.spec:38 --simple-console --hide-suggestion
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.6-compliant syntax, but you are running 2.6.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
invalid byte sequence in US-ASCII
invalid byte sequence in US-ASCII
[ValidationError] /Users/prashinkasahu/src/system-tests/specs/care_mgmt/payer_population/mark_as_error_form.spec:43 Step implementation not found => 'Click link "Manage Populations" on PCP "Patient Record" tab'
[ValidationError] /Users/prashinkasahu/src/system-tests/specs/care_mgmt/payer_population/mark_as_error_form.spec:45 Step implementation not found => 'Mark all active episodes as error'
[ValidationError] /Users/prashinkasahu/src/system-tests/specs/care_mgmt/payer_population/mark_as_error_form.spec:47 Step implementation not found => 'Move to "Checklist" tab on PCP'
Error in translate; invalid byte sequence in US-ASCII
"Welcome"
/Users/prashinkasahu/src/system-tests/step_implementations/pages/v2_triage.rb:274: warning: circular argument reference - reason
/Users/prashinkasahu/src/system-tests/step_implementations/pages/triage.rb:299: warning: circular argument reference - reason
Error in translate; invalid byte sequence in US-ASCII
[DEPRECATED] Use custom_screenshot_writer instead.
/Users/prashinkasahu/src/system-tests/step_implementations/spec_helper.rb:135: warning: class variable access from toplevel
/Users/prashinkasahu/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/redis-3.0.7/lib/redis/client.rb:386: warning: constant ::Fixnum is deprecated
Successfully generated xml-report to => /Users/prashinkasahu/src/system-tests/reports/xml-report

Successfully generated html-report to => /Users/prashinkasahu/src/system-tests/reports/html-report/index.html
Specifications: 0 executed  0 passed    0 failed    1 skipped
Scenarios:  0 executed  0 passed    0 failed    1 skipped

Log file attached.
[gauge.log.zip](https://github.com/getgauge/gauge/files/6961047/gauge.log.zip)

Step implementation class :
======================
# frozen_string_literal: true
require_relative 'spec_helper.rb'
step 'Move to patient population overview page' do
    @population_overview = GaugeBase::Pages::PatientPopulationsPage.new
    begin
        GaugeBase::Pages::PatientPopulationsPage.visit
    rescue Net::ReadTimeout
      if tries.zero?
        tries = 1
        retry
      else
        raise  Net::ReadTimeout
      end
    end
    20.times{break if @population_overview.loaded?; sleep 0.5}
    @population_overview.assert_true @population_overview.header.text.eql?("Patient Populations"),"Patient Populations Overview page not opened"
end

step 'Verify table on Population <page_name> shows columns <columns>' do |page_name,columns|
    if page_name.downcase.eql?("overview")
        @population_page = GaugeBase::Pages::PatientPopulationsPage.new
    else 
        @population_page = GaugeBase::Pages::PopulationDetailsPage.new
    end
    20.times{break if @population_page.loaded?; sleep 0.5}
    displyed_columns = @population_page.column_names
    columns.split(':').each{|column|
        @population_page.assert_true displyed_columns.include?(column),"#{column} not available, displayed columns are #{displyed_columns}"
    }
end

step 'Populations list displayed on population overview' do
    @population_overview = GaugeBase::Pages::PatientPopulationsPage.new
    20.times{break if @population_overview.loaded?; sleep 0.5}
    displayed_populations=@population_overview.populations.map{|ele| ele.text}
    @population_overview.assert_true displayed_populations.size>0,"No populations available"
end

step 'Verify the round up value of <column_name> against values in table' do |column_name|
    @population_overview = GaugeBase::Pages::PatientPopulationsPage.new
    20.times{break if @population_overview.loaded?; sleep 0.5}
    displyed_columns = @population_overview.column_names
    column_name.split(':').each{|column|
        @population_overview.assert_true displyed_columns.include?(column),"#{column} not available, displayed columns are #{displyed_columns}"
        @population_overview.assert_true @population_overview.get_roundup_of(column).text.to_i==@population_overview.total_of_column(column), "Round up value of #{column} doest match with data in table"
    }
end

step 'Verify View Care Pathway link displayed for each population' do
    @population_overview = GaugeBase::Pages::PatientPopulationsPage.new
    20.times{break if @population_overview.loaded?; sleep 0.5}
    displayed_populations=@population_overview.populations.map{|ele| ele}
    @population_overview.assert_true displayed_populations.size==(@population_overview.view_care_pathway_links.map{|ele| ele}.size),"View Care pathway link not avaiable for all populations"
end

step 'Clicking on View Care Pathway takes user to Population Details Page' do 
    @population_overview = GaugeBase::Pages::PatientPopulationsPage.new
    20.times{break if @population_overview.loaded?; sleep 0.5}
    selected_population=@population_overview.populations.map{|ele| ele.text}[0]
    @population_overview.view_care_pathway_links[0].click
    @population_details=GaugeBase::Pages::PopulationDetailsPage.new
    20.times{break if @population_details.loaded?; sleep 0.5}
    expected_header="#{selected_population} Population"
    @population_details.assert_true @population_details.header.text.eql?(expected_header),"Expectetd Page :[#{expected_header}] , displayed page #{@population_details.header.text}"
end

step 'Store the original order for column <column_list> on population <page_name>' do |column_list,page_name|
    if page_name.downcase.eql?("overview")
        @population_page = GaugeBase::Pages::PatientPopulationsPage.new
    else 
        @population_page = GaugeBase::Pages::PopulationDetailsPage.new
    end
    20.times{break if @population_page.loaded?; sleep 0.5}
    column_list.split(':').each{|column_name|
        current_sort=(@population_page.get_column_by_name(column_name))['aria-sort']
        original_list=@population_page.get_all_values_for_column(column_name)
        name="#{column_name.downcase.gsub(' ',"_")}_list"
        if current_sort.eql?("none")
            GaugeBase::PATIENT_INFO[name]=original_list
        else
            @population_page.assert_true false,"#{column_name} is already sorted in #{current_sort} order"
        end
    }
end

step 'Click on <column_name> column header on populaion <page_name>' do |column_name,page_name|
    if page_name.downcase.eql?("overview")
        @population_page = GaugeBase::Pages::PatientPopulationsPage.new
    else 
        @population_page = GaugeBase::Pages::PopulationDetailsPage.new
    end
    20.times{break if @population_page.loaded?; sleep 0.5}
    @population_page.get_column_by_name(column_name).click
end

step 'Verify <column_name> column sorted in <order> order on population <page_name>' do |column_name, order,page_name|
    if page_name.downcase.eql?("overview")
        @population_page = GaugeBase::Pages::PatientPopulationsPage.new
    else 
        @population_page = GaugeBase::Pages::PopulationDetailsPage.new
    end
    20.times{break if @population_page.loaded?; sleep 0.5}
    name="#{column_name.downcase.gsub(' ',"_")}_list"
    current_list=@population_page.get_all_values_for_column(column_name)
    if order.downcase.eql?("descending")
        list_to_sort=GaugeBase::PATIENT_INFO[name].map { |x| x.eql?("—") ? '0' : x }
        expected_list = list_to_sort.sort.reverse.map { |x| x.eql?("0") ? '—' : x }
    elsif order.downcase.eql?("ascending")
        list_to_sort=GaugeBase::PATIENT_INFO[name].map { |x| x.eql?("—") ? '0' : x }
        expected_list = list_to_sort.sort.map { |x| x.eql?("0") ? '—' : x }
    elsif order.downcase.eql?("original")
        expected_list = GaugeBase::PATIENT_INFO[name]
    else
        @population_page.assert_true false, "Invalid order [#{order}], please pass order as [descending, ascending, original] for column #{column_name}}"
    end
    @population_page.assert_true current_list==expected_list, "#{column_name} not sorted in #{order} order, showing data [#{current_list}], instead of #{expected_list}"
end

step 'Verify buttons <buttons> are <visibility> on Population Details Page' do |buttons, visibility|
    @population_details=GaugeBase::Pages::PopulationDetailsPage.new
    20.times{break if @population_details.loaded?; sleep 0.5}
    (visibility.include?('not')) ? (flag = false) : (flag = true)
    buttons.split(':').each{|button|
        @population_details.assert_true (@population_details.get_button(button).visible? == flag),"Validation failed, expected #{button} to be #{visibility}"
    }
end

step 'Click on View Care Pathway for population <population_name>' do |population_name|
    @population_overview = GaugeBase::Pages::PatientPopulationsPage.new
    20.times{break if @population_overview.loaded?; sleep 0.5}
    displayed_populations=@population_overview.populations.map{|ele| ele.text}
    @population_overview.assert_true displayed_populations.include?(population_name),"Population #{population_name} is not availble, Please check!"
    @population_overview.get_column_for_population(population_name,"View Care Pathway").click
    @population_details=GaugeBase::Pages::PopulationDetailsPage.new
    20.times{break if @population_details.loaded?; sleep 0.5}
    expected_header="#{population_name} Population"
    @population_details.assert_true @population_details.header.text.eql?(expected_header),"Expectetd Page :[#{expected_header}] , displayed page #{@population_details.header.text}"
end

step 'Click on <button_name> button on Population Details Page' do |button_name|
    @population_details= GaugeBase::Pages::PopulationDetailsPage.new
    20.times{break if @population_details.loaded?; sleep 0.5}
    button=@population_details.get_button(button_name)
    @population_details.js_scroll_to(button)
    button.click
end

step 'Enter the task title <title> in newly added blank row' do |title|
    @population_details= GaugeBase::Pages::PopulationDetailsPage.new
    20.times{break if @population_details.loaded?; sleep 0.5}
    title="#{title}_#{Time.now.strftime("%H%M%S")}"
    @population_details.set_task_title(title)
    available_tasks= @population_details.tasks.map{|ele| ele.text}
    @population_details.assert_true available_tasks.include?(title),"Task is not added"
    GaugeBase::PATIENT_INFO["task_title"]=title
end

step 'Check <months> for recently added task' do |months|
    @population_details= GaugeBase::Pages::PopulationDetailsPage.new
    20.times{break if @population_details.loaded?; sleep 0.5}
    title=GaugeBase::PATIENT_INFO["task_title"]
    months.split(':').each{ |month|
        checkbox = @population_details.get_column_for_task(title,month)
        @population_details.js_scroll_to(checkbox)
        checkbox.click
        @population_details.assert_true @population_details.verify_checked(checkbox),"Checkbox #{month} is not selected for task #{
            title}"
    }
end

step 'Publish Care Pathway modal is displayed' do
    @population_details = GaugeBase::Pages::PopulationDetailsPage.new
    20.times{break if @population_details.loaded?; sleep 0.5}
    popup = @population_details.publish_care_pathway
    20.times{break if popup.loaded?; sleep 0.5}
    @population_details.assert_true popup.header.text.eql?("Publish Care Pathway"),"Publish Care Pathway model not displayed"
end

step 'Verify message <message> displayed on Publish Care Pathway model' do |message|
    @population_details = GaugeBase::Pages::PopulationDetailsPage.new
    20.times{break if @population_details.loaded?; sleep 0.5}
    popup = @population_details.publish_care_pathway
    20.times{break if popup.loaded?; sleep 0.5}
    @population_details.assert_true popup.message.text.include?(message),"#{message} not displayed on the popup, actual message displayed as #{popup.message.text}"
end

step 'Publish the changes' do
    @population_details = GaugeBase::Pages::PopulationDetailsPage.new
    20.times{break if @population_details.loaded?; sleep 0.5}
    popup = @population_details.publish_care_pathway
    20.times{break if popup.loaded?; sleep 0.5}
    popup.get_button("Publish").click
    5.times{break if !(popup.loaded?); sleep 0.5}
    @population_details.assert_false popup.loaded?,"Publih Care Pathway popup is not closed"
end

step 'Click link <link_name> on PCP <tab_name> tab' do |link_name, tab_name|
    @pcp_page=GaugeBase::Pages::PatientCareProfilePage.new
    10.times{break if @pcp.patient.visible?; sleep 0.25}
    if !(@pcp_page.get_selected_tab.text.eql?(tab_name))
        @pcp_page.get_tab(tab_name).click
        @pcp_page.assert_true @pcp_page.get_selected_tab.text.eql?(tab_name), "Unabled to open #{tab_name} tab on PCP"
    end
    @pcp_page.getLink(link_name).click
end

step 'Open Manage Populations page by clicking Manage Population button' do
    @pcp_page=GaugeBase::Pages::PatientCareProfilePage.new
    10.times{break if @pcp.patient.visible?; sleep 0.25}
    @pcp_page.getLink("Manage Populations").click
    @manage_population =GaugeBase::Pages::ManagePopulationsPage.new
    20.times{break if @manage_population.loaded?; sleep 0.5}
    @manage_population.assert_true @manage_population.header.text.eql?("Manage Populations"),"Manage populations page not opened"
end

step 'Set <dropdown_to_set> and enter <value_to_enter> on manage population' do |dropdown_to_set, value_to_enter|
    @manage_population =GaugeBase::Pages::ManagePopulationsPage.new
    20.times{break if @manage_population.loaded?; sleep 0.5}
    dropdown_to_set.split(',').each{ |dropdown_option|
     dropdown,option=dropdown_option.split(':')
     @manage_population.get_dropdown(dropdown).click
     @manage_population.assert_true @manage_population.set_dropdown(dropdown,option).eql?(option),"#{dropdown} not set as #{option}"
    }
    if !(value_to_enter.empty?)
        value_to_enter.split(',').each{|label_data|
            label,data=label_data.split(':')
            if label.downcase.include?('date')
                data=Date.today.next_day(Integer((data.downcase.gsub('today',"")).strip)).strftime('%-m/%-d/%Y')
            end
            textbox=@manage_population.get_textbox(label)
            @manage_population.js_scroll_to(textbox)
            textbox.native.send_keys [:control, 'a'], :delete
            textbox.set data  
            @manage_population.assert_true textbox.value.eql?(data),"#{label} not entered as #{data}"
        }
    end
end

step 'Save the episode' do
    @manage_population =GaugeBase::Pages::ManagePopulationsPage.new
    20.times{break if @manage_population.loaded?; sleep 0.5}
    @manage_population.get_button("Save").click
    begin
        20.times{break if !(@manage_population.header.visible?); sleep 0.25}
        @manage_population.assert_false @manage_population.header.visible?, "Episode not created,Please check!"
    rescue Selenium::WebDriver::Error::StaleElementReferenceError
        puts "Handled Stale Element Reference exception."
        @pcp_page=GaugeBase::Pages::PatientCareProfilePage.new
        10.times{break if @pcp.population_header.visible?; sleep 0.25}
        @pcp_page.assert_true @pcp_page.population_header.visible?,"Episode not saved"    
    end
end

step 'Mark all active episodes as error' do
    @pcp_page=GaugeBase::Pages::PatientCareProfilePage.new
    10.times{break if @pcp.population_header.visible?; sleep 0.25}
    @pcp_page.assert_true @pcp_page.population_header.visible?,"Population tab not opened"
    mark_error_links=@pcp_page.mark_error_links
    while(mark_error_links.size>0)
        mark_error_links[0].click
        @mark_error_page=GaugeBase::Pages::MarkAsErrorPage.new
        10.times{break if @mark_error_page.loaded?; sleep 0.5}
        @mark_error_page.assert_true @mark_error_page.header.visible?,"Mark as Error not opened"
        @mark_error_page.reason_dropdown.click
        @mark_error_page.assert_true @mark_error_page.set_reason("Other").eql?("Other"),"Reason not selected correctly"    
        @mark_error_page.mark_error_button.click
        @pcp_page=GaugeBase::Pages::PatientCareProfilePage.new
        10.times{break if @pcp.population_header.visible?; sleep 0.25}
        @pcp_page.assert_true @pcp_page.population_header.visible?,"Population tab not opened"
        mark_error_links=@pcp_page.mark_error_links
    end
    @pcp_page.assert_false @pcp_page.mark_error_links.size>0, "All episodes are not amrked as error"
end

step 'Move to <tab_name> tab on PCP' do |tab_name|
    @pcp_page=GaugeBase::Pages::PatientCareProfilePage.new
    10.times{break if @pcp.patient.visible?; sleep 0.25}
    @pcp_page.get_tab(tab_name).click
    @pcp_page.assert_true @pcp_page.get_selected_tab.text.eql?(tab_name), "Unabled to open #{tab_name} tab on PCP"
    @checklist_page=GaugeBase::Pages::ChecklistPage.new
    20.times{break if @checklist_page.loaded?; sleep 0.5}
end

step 'Verify added task is displayed for months <months>' do |months|
    @checklist_page=GaugeBase::Pages::ChecklistPage.new
    20.times{break if @checklist_page.loaded?; sleep 0.5}
    title=GaugeBase::PATIENT_INFO["task_title"]
    months.split(':').each{|month|
        @checklist_page.assert_true @checklist_page.verify_task_visible(month,title),"Task with title[#{title}] is not displayed for month[#{month}]"
    }
end

step 'Update the task title for first task to <new_task_title> and Month to <months>' do |new_task_title,months|
    @population_details= GaugeBase::Pages::PopulationDetailsPage.new
    20.times{break if @population_details.loaded?; sleep 0.5}
    title="#{new_task_title}_#{Time.now.strftime("%H%M%S")}"
    task_list=@population_details.get_all_values_for_column("Task")
    @population_details.assert_true task_list.size>0,"No task available to updated"
    task_to_update=task_list[0]
    @population_details.assert_true @population_details.edit_task_title(task_to_update,title),"Task title not updated"
    GaugeBase::PATIENT_INFO["task_title"]=title
    GaugeBase::PATIENT_INFO["task_deleted"]=task_to_update
    @population_details.uncheck_all_months(title)
    months.split(':').each{ |month|
        checkbox = @population_details.get_column_for_task(title,month)
        @population_details.js_scroll_to(checkbox)
        checkbox.click
        @population_details.assert_true @population_details.verify_checked(checkbox),"Checkbox #{month} is not selected for task #{
            title}"
    } 
end

step 'Verify no entry available on Checklist tab for edited or deleted task title' do
    @checklist_page=GaugeBase::Pages::ChecklistPage.new
    20.times{break if @checklist_page.loaded?; sleep 0.5}
    old_title=GaugeBase::PATIENT_INFO["task_deleted"]
    available_tasks=@checklist_page.task_title_list.map{|ele| ele.text}
    @checklist_page.assert_false available_tasks.include?(old_title),"Changes not published correctly, task #{old_title} still available in Checklist"
end

step 'Delete first checklist task' do
    @population_details= GaugeBase::Pages::PopulationDetailsPage.new
    20.times{break if @population_details.loaded?; sleep 0.5}
    task_list=@population_details.get_all_values_for_column("Task")
    @population_details.assert_true task_list.size>0,"No task available to delete"
    task_to_delete=task_list[0]
    @population_details.assert_true @population_details.delete_task(task_to_delete),"Task title not deleted"
    GaugeBase::PATIENT_INFO["task_deleted"]=task_to_delete
end

Versions
=========
Gauge version: 1.1.6
Commit Hash: 3af456f
Plugins
-------
html-report (4.0.8)
ruby (0.5.4)
screenshot (0.0.1)
xml-report (0.2.2)
Operating System information
————————————————
Mac BigSur 11.4
IDE information
———————-
VS Code 1.59.0
Ruby Versions
———————
Output for ruby -v
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin20]
Output for “which ruby”
/Users/prashinkasahu/.rbenv/shims/ruby
Output for rbenv
rbenv 1.1.2

**Comment by sriv** [comment]
There seem to be some error loading your `.rb` files. Can you try to fix those and check? The step implementation not found is possibly being thrown because gauge is unable to parse the implementation files due to those errors.
