### ISSUE TITLE
If a spec has an unimplemented step, fail that spec rather than all specs in a run

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/gauge#208]
Currently we run specs using a nightly build framework in groups of about 100. Each spec in the group is tagged with the same spec, like this:

    gauge specs -tags=TT-Group1

However, occasionally a developer will check in a spec with an unimplemented step by accident and we don't immediately catch it. When our nightly run happens, if just 1 of those specs has an unimplemented step, the other 99 good specs will fail to run. This is very frustrating because a nightly run fails to produce any useful results.

What we would like to happen instead is that the spec with the unimplemented step will fail, but other specs will still run. Thus we do not lose the test results of 99 good specs when just one fails.

To be clear, we still want a clear error to occur when this happens so that we can rectify the problem. We just don't want the error in one spec to block execution of all specs in a group.

**Comment by deepthigc** [comment]
@Thunderforge Thanks for pointing this out. We agree it is a valid issue. This happened because we were parsing all tests before execution, and any error in one meant the parse failed and we didn't run any of them. This needs to be fixed. 

We're going to introduce a way to identify which scenarios were 'skipped' because of this reason(in this case step not implemented), and report that in addition to failures and successes.

**Comment by Thunderforge** [comment]
I'm pleased to hear that! We very much look forward to that change.

**Comment by SG57** [comment]
One backwards compatible solution that also adds functionality is to add a new annotation `@WhenStepNotImplemented` .

The idea is, when a step is not implemented all methods annotated with the `WhenStepNotImplemented` annotation get ran instead.  This annotation expects the method signature to accept a variable amount of arguments that gets filled by the step that isn't implemented's arguments.  This annotation should accept tags as well to provide scope if we so choose

**Comment by deepthigc** [comment]
@SG57 we're looking at 2 use cases here

1. There is an unimplemented step in a scenario(maybe I haven't gotten to automating it yet)​
2. There is an unimplemented step in a scenario which I cannot automate and hence was some manual intervention

I think these are separate use cases. 

Now with the @WhenStepNotImplemented, you would execute the scenario, and when you get to the step that is not implemented, then it would invoke the method that has the @WhenStepNotImplemented. This would be scenario 2 as described above.

My earlier response is a solution to scenario 1. We need a way to ignore the scenarios that have unimplemented steps, run all the others, and also find a way to report these scenarios along with those that passed and failed. We're fixing this as part of this issue.

Your use case is something that has been on our radar for a bit. https://github.com/getgauge/gauge/issues/50 is where we have this documented so we can discuss the solution to this there. We refer to it as hybrid execution. Please correct me if I have misunderstood this.

I hope this makes sense.

**Comment by kashishm** [comment]
We have released [gauge 0.2.0](https://github.com/getgauge/gauge/releases/tag/v0.2.0) with the ability to skip scenarios/specifications with unimplemented steps while execution.

* Unimplemented __context step__ will mark the specification as skipped.
* Unimplemented __scenario step__ will mark the scenario as skipped

The skipped scenarios/specifications are shown in console output and reports(HTML/XML)

![screen shot 2015-10-12 at 7 48 08 pm](https://cloud.githubusercontent.com/assets/5915802/10429991/3084a646-711a-11e5-8e70-da0241e800b5.png)
