### ISSUE TITLE
Documentation plugins should have a non-zero exit code when they return an error

### ISSUE THREAD

**Issue by johnboyes** [getgauge/gauge#2080]
**Describe the bug**
At the moment [documentation plugins exit with a zero exit code even if the plugin explicitly returns an error][1]. This means that in a CI/CD pipeline, for instance, we can't check the exit code and instead have to check the console or log output, which is brittle.

[1]: https://github.com/getgauge/gauge/blob/5cc544c7702df7d3604eaefa6c967eb9a54a2462/plugin/plugin.go#L404-L407

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Initialise a gauge project
2. Install any gauge documentation plugin
3. Setup the documentation plugin in an invalid state, e.g. missing a mandatory configuration variable
2. Run the gauge docs command
3. See that gauge exits with a zero exit code (instead of a non-zero code, which it should)

```
$ gauge init java # or js, python etc
$ gauge docs <any-documentation-plugin>
```

**Expected behavior**
Gauge should exit with a non-zero exit code when documentation plugins explicitly return an error.

**Versions:**

```
gauge -v
```
```
Gauge version: 1.4.0
Commit Hash: 5cc544c
```

**Additional context**
Proposed amendment would be to use `logger.Fatalf` instead of `logger.Errorf`:

```go
_, err = p.DocumenterClient.GenerateDocs(context.Background(), getSpecDetails(specDirs))
grpcErr := p.killGrpcProcess()
if grpcErr != nil {
    logger.Errorf(false, "Unable to kill plugin %s : %s", p.descriptor.Name, grpcErr.Error())
}
if err != nil {
    logger.Fatalf(true, "Failed to generate docs. %s", err.Error())
}
```

I'm happy to submit a PR if this issue is accepted.

**Comment by zabil** [comment]
> Gauge should exit with a non-zero exit code when documentation plugins explicitly return an error.

This makes sense. Please feel free to submit a PR

**Comment by johnboyes** [comment]
Thanks @zabil, I've submitted #2081 for this.
