### ISSUE TITLE
Scenarios cannot find step implementations that contain both table and non-table parameters

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/gauge#209]
Consider the following step:

    @Step("Step that takes a table named <tableName> <table>")
    public void stepWithTable(String tableName, Table table) {
        //Things happen
    }

It contains two parameters, the second of which is a table. Gauge does not provide any error that it is invalid, and a programmer would expect it to be work.

In a spec, a developer might write the following lines of code:

    * Step that takes a table named "Foo"
        |Product|       Description           |
        |-------|-----------------------------|
        |Gauge  |Test automation with ease    |
        |Mingle |Agile project management     |

However, Gauge fails with the following error:

    Step implementation not found. Step that takes a table named "Foo"

Since the step in the Java code compiles successfully, there should be no reason why Gauge should report that the step implementation is not found when it contains both table and non-table parameter.

**Comment by apoorvam** [comment]
@Thunderforge Here is a sample [gist](https://gist.github.com/apoorvam/bd5b7cf0d7b35c6169f2) we tried out to reproduce the issue you have described. But this works totally fine. Let us know if this doesn't work at your end.

**Comment by Thunderforge** [comment]
Your code works for me, and now things are working with my old code. I can't explain why it wasn't working at first. I did clean out the `out` directory at some point though. At any rate, this appears to be working now.
