### ISSUE TITLE
unable to create Gauge project through coomand prompt

### ISSUE THREAD

**Issue by somnath4993** [getgauge/gauge#210]
I am not able to create project through command prompt,
![gaugeprojectnotcreatederror](https://cloud.githubusercontent.com/assets/14311712/9903428/0e74b612-5c94-11e5-8a87-e26ceeeaa718.PNG)

**Comment by sriv** [comment]
It looks like you are unable to hit github from the console. Are you behind a proxy? If so, can you try setting `HTTP_PROXY` environment variable as described [here](http://stackoverflow.com/a/28153935/326543) before running the `gauge` command?

**Comment by somnath4993** [comment]
Thanks Sriv, now i able to create project.
