### ISSUE TITLE
Some gauge tests fail, but the report shows "passed"

### ISSUE THREAD

**Issue by EricMullen1989** [getgauge/gauge#2115]
**Describe the bug**
Running a test of a spec file shows "Failed Step: <Title of Step>" followed by the specification and error message and so forth.
However, when checking the report, all tests show as pass.

Looking in the terminal, I get a "build successful" as well as:
`Specifications:	3 executed	3 passed	0 failed	0 skipped`
`Scenarios:	4 executed	4 passed	0 failed	0 skipped`

When in reality it should be:
`Specifications:	3 executed	2 passed	1 failed	0 skipped`
`Scenarios:	4 executed	2 passed	2 failed	0 skipped`

If it helps, in this particular example I'm using a `for loop` to go over a table and check the values and run `assertEquals`

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Initialise a gauge project
2. Run the gauge command
3. Steps that fail should output in terminal
4. See that, even with failures, everything passes

```
$ gauge init java # or js, python etc
Your Environment Information -----------
        linux, 1.4.1, 
        html-report (4.1.2), java (0.7.15), js (2.3.17), python (0.3.17), screenshot (0.1.0)
```

**Logs**

```
Paste any log or error messages here
```

**Expected behavior**
Gauge execution output should show valid test pass/failure output.

**Screenshots**

**Versions:**
Gauge version: 1.4.1
Java 11

```
gauge -v

Gauge version: 1.4.1

Plugins
-------
html-report (4.1.2)
java (0.7.15)
js (2.3.17)
python (0.3.17)
screenshot (0.1.0)
```
 - OS: Linux
 - Runner info: Java 11
 - IDE info: Intellij IDEA

**Additional context**
N/A

**Comment by zabil** [comment]
This can happen if you have add a try catch block in your code instead of throwing an exception. Can you please share the code for your step implementation to replicate this?

**Comment by EricMullen1989** [comment]
So it's a for loop that iterates over a table of data that has the headers: `tagnumber`,  `name`, and `occurrences`. It makes sure that what is found in the html elements (by xpath) matches what is in the table.

The code is as follows (with some removals due to company privacy):
`    @Step("Check Organization tag on view document page <table>")
    public void checkAttributeTag(Table table) throws AWTException, InterruptedException {
        // Wait 10 seconds so page loads properly
        Thread.sleep(10000);

        // Causes a drop-down menu to be expanded.
        WebDriver driver = DriverCache.getDriver();
        String xPath = "elementXpath";
        driver.findElement(By.xpath(xPath)).click();

        for(TableRow row: table.getTableRows()) {
            int tagNumber = Integer.valueOf(row.getCell("TagNumber"));
            String name = row.getCell("Name");
            int occurence = Integer.valueOf(row.getCell("Occurrence"));

            driver = DriverCache.getDriver();
            SeleniumModule.waitForPageLoad(driver);
            WebElement tag = SeleniumModule.waitForVisibility(driver, By.cssSelector("#attribute-tree p-treenode:nth-child(2)" +
                    " p-treenode:nth-child(" + tagNumber+ ") li div"));
            Assertions.assertEquals(name + "\n" + occurence, tag.getText());
        }
    }`

**Comment by sriv** [comment]
> Running a test of a spec file shows "Failed Step: <Title of Step>" followed by the specification and error message and so forth.
However, when checking the report, all tests show as pass.

This is concerning. It should either not report an error or indicate the number of failures in the final summary. I am not sure why this is happening, but this isn't the expected behaviour.

As for the code sample you've pasted, can you try printing the count of rows that you are getting in the method implementation? Reason - the assertion is inside the for loop, so if there were zero rows in the table passed in, the method will not throw an exception, marking the step as passed.

**Comment by EricMullen1989** [comment]
It always has had at least a count of 1, so it always find something. 
Here's a printout of the "failure" message:

` Failed Step: Check Organization tag on view document page`
`        Specification: specs/RunBulkDocuments.spec:14`
`        Error Message: org.opentest4j.AssertionFailedError: expected: <CorTS Trust for J.C.`
`        2> but was: <Act File Number Old Copper Company, Inc.`
 `       1>`

And here's the report output:

`Specifications:	3 executed	3 passed	0 failed	0 skipped`
`Scenarios:	4 executed	4 passed	0 failed	0 skipped`
`Total time taken: 2m35.949s`
`BUILD SUCCESSFUL in 3m 45s`
`3 actionable tasks: 3 executed`

So as you can see, it clearly failed on one row in the for loop, but yet shows passed.

**Comment by PeterKovacs1** [comment]
I have a similar issue. The assertion fails, but Gauge Report shows **...[PASS]**

CODE
`step("'Peter' verify'", async function () {
    try {
    const elementText = await text('Peter', below('Pete')).exists(0,0);
    assert.equal(elementText, 'Pettteer');
        } catch (error) {
          console.error(error);
        } 
});`

CONSOLE.Log
`AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected
+ false
- 'Pettteer'
at Object.<anonymous> (/REMOVED/tests/step_implementaition.js:219:12) {
generatedMessage: true,
code: 'ERR_ASSERTION',
actual: false,
expected: 'Pettteer',
operator: 'strictEqual'
}
      * 'Peter' verify'    ...[PASS]`

Can anyone help me out with the code, so it will fail the step in the gauge report?

**Comment by zabil** [comment]
Please modify your code from

```
step("'Peter' verify'", async function () { 
 try {  
 const elementText = await text('Peter', below('Pete')).exists(0,0); assert.equal(elementText, 'Pettteer'); 
} catch (error) { 
 console.error(error); } 
});
```

to 

```
step("'Peter' verify'", async function () { 
  const elementText = await text('Peter', below('Pete')).exists(0,0); assert.equal(elementText, 'Pettteer'); 
}
```

If you want to report errors.
