### ISSUE TITLE
Gauge does not propagate specDetails to documentation plugins if non-default specs dir is provided

### ISSUE THREAD

**Issue by johnboyes** [getgauge/gauge#2117]
**Describe the bug**
Gauge has a bug where the specDetails are only being passed properly to documentation plugins if the specs directory is the default `specs` directory.  This is a problem for any documentation plugin which relies on the specDetails.  For example my [Confluence plugin][1] relies on the specDetails being passed properly to the plugin, and therefore currently the Confluence plugin is broken if users run e.g. `gauge docs confluence anything-that-is-not-the-default-specs-dir`. 

I have investigated the source of this bug and think I have found it.

The [`GetAvailableSpecDetails` function is currently always given an empty slice][2], when it should instead be passed the [`specDirs` from the outer function parameter][3].  I have tested this locally and verified that making this change fixes the issue.

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Initialise a gauge project
2. Rename the `specs` directory to `something-else`
3. `gauge install confluence`
4. `gauge docs confluence something-else`
5. The confluence plugin panics because `specDetails` is empty.

**Expected behavior**
The specDetails are always propagated to documentation plugins.

**Versions:**

```
gauge -v

Gauge version: 1.4.1
Commit Hash: 064162fd

Plugins
-------
confluence (0.18.1)
```

**Additional context**
I can submit a PR with the above fix for this issue, if you would like me to.

[1]: https://github.com/agilepathway/gauge-confluence
[2]: https://github.com/getgauge/gauge/blob/064162fd9eed48deda8ece5550e2da692156234b/plugin/plugin.go#L558
[3]: https://github.com/getgauge/gauge/blob/064162fd9eed48deda8ece5550e2da692156234b/plugin/plugin.go#L554

**Comment by zabil** [comment]
@johnboyes thanks for taking the time to figure this out. Please feel free to send the change as a PR.

**Comment by johnboyes** [comment]
Excellent, thanks @zabil.  I'm on holiday for a week now, so will submit the PR in 10 days or so when I return.

**Comment by johnboyes** [comment]
Hi @zabil and @sriv, I've now submitted #2133 for this.
