### ISSUE TITLE
Exception occurred in Gauge executable

### ISSUE THREAD

**Issue by George-Sun-2021** [getgauge/gauge#2137]
**Describe the bug**
Exception occurred in Gauge executable

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Initialize a gauge project via IDEA
2. See error after `Gradle sync started`

**Actual behavior**
**Logs**

```
#### Gauge process exited with code ```1```
Gauge daemon initialized and listening on port: 58345
* IDE version: 2021.2.3
* API version: IU-212.5457.46
* Plugin version: 212.4746.52
* Gauge version: 1.4.2
```

**Expected behavior**
No errors while project initialized

**Comment by chadlwilson** [comment]
Closing this as seems old. Please raise or comment if there is still an issue with latest Gauge.
