### ISSUE TITLE
table parameter cannot handle more than 2 columns

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge#214]
When reading from an external csv file and a row has 5 columns 
e.g. a,b,c,d,e

row.get(0) = a
row.get(1) = e - this should be "b"
row.size() = 5

```bash
$ gauge -v 
Gauge version: 0.1.8 

Plugins -------
html-report (1.0.4)
java (0.2.2)
xml-report (0.0.2)
```

**Comment by mahendrakariya** [comment]
We tried reproducing the issue with [this gist](https://gist.github.com/sriv/dd78b9806d42ee73938f). It's working fine as expected on our machine. 

Can you give us more details on how you are passing the csv?

**Comment by haroon-sheikh** [comment]
I cant seem to reproduce the issue myself now. I'll keep an eye on it and see what caused that to happen.

**Comment by mahendrakariya** [comment]
OK. I will close this for now. Feel free to reopen in case if you face it again.
