### ISSUE TITLE
Default log level should be none

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/gauge#215]
A suggestion by @navaneeth 

By default, log level should be None. For user, all those messages are irrelevant. IMO, unless specified, logging should be turned off or probably write to a log file rather than console.

**Comment by kaustavdm** [comment]
As of the current implementation for #212, the default console reporting is concise. Detailed logs are written to file.

**Comment by mahendrakariya** [comment]
This is released in Gauge v0.3.0
