### ISSUE TITLE
Gauge is not taking screen shots when tests are run in Linux - Ubuntu container in a headless mode

### ISSUE THREAD

**Issue by harimadusumilli** [getgauge/gauge#2167]
**Describe the bug**
Issue:
Gauge unable to capture screen shots on linux-Ubuntu. We are running the tests in headless mode. This works fine on windows. On linux we are having an issue.

Gauge screenshots are not captured under the “.gauge” folder and the html result is generated without screenshots.

What command(s) did you run when you found the bug?

gauge run specs

Gauge screenshot method is not working in Linux with full root access for the user.
/Users/vagrant/go-agent-17.4.0/pipelines/Screenshot/src/github.com/getgauge/gauge_screenshot/main.go:44 +0x19c

**Browser :** Chrome and not chromium

gauge -v
Gauge version: 1.1.8
Commit Hash: b1501f4

Plugins
-------
dotnet (0.4.1)
html-report (4.0.12)
js (2.3.15)
json-report (0.3.5)
screenshot (0.0.1)
xml-report (0.2.3)

**.NET VERSION**
.NET CORE 5.0

Operating System information
Linux

IDE information
VS CODE

Below is the code for Screen shot implementation we have written. **The code worked in .Net 3.0 +  .Net 2.x together in a container earlier**

version of Gauge Charip lib available in CSProj : <PackageReference Include="Gauge.CSharp.Lib" Version="0.9.0"/> 
namespace Gauge.CSharp.Lib
{
    class CustomScreenGrabber : ICustomScreenshotWriter
    {
  	public string TakeScreenShot()
        { 
            string screenshotFolder;
            screenshotFolder = (String)Path.Combine(Environment.GetEnvironmentVariable("gauge_screenshots_dir")).Replace("\\","/");
  
            string filename = String.Format("screenshot-{0}.png", Guid.NewGuid().ToString());
            var fullPath = Path.Combine(DriverScript.GetRelativePath() + @"\reports\html-report\images",filename);
            byte [] screenshot=null;
   
            if(DriverScript.driverflg.Equals("Win")){
                screenshot = ((ITakesScreenshot)DriverScript.GetWiniumDriver()).GetScreenshot().AsByteArray;
            }else{
                screenshot = ((ITakesScreenshot)DriverScript.GetSeleniumDriver()).GetScreenshot().AsByteArray;
           }
            DriverScript.screenshotPath=fullPath + " " + screenshot;
            File.WriteAllBytes(fullPath,screenshot);
            Console.WriteLine("Screenshot Captured Successfully");
            return fullPath;
        }
     }
}

**Comment by zabil** [comment]
>         var fullPath = Path.Combine(DriverScript.GetRelativePath() + @"\reports\html-report\images",filename);

This seems to be a problem how you describe a path. For example linux does not understand `\` Please make sure that file paths are [cross platform](https://stackoverflow.com/questions/38168391/cross-platform-file-name-handling-in-net-core).

**Comment by zabil** [comment]
Accidentally closed the issue. But please check the paths and see if it solves the problem.

**Comment by harimadusumilli** [comment]
Thank you for your advise. We did try to change the path using the "\" to "/". Although we have tried this, the issue still exists. 

var fullPath = Path.Combine(DriverScript.GetRelativePath() + @"/reports/html-report/images",filename);

**Comment by sriv** [comment]
Gauge and html-report expect the screenshots to be in location specified in `gauge_screenshots_dir` env var, which is something your code is fetching in

```
screenshotFolder = (String)Path.Combine(Environment.GetEnvironmentVariable("gauge_screenshots_dir")).Replace("\","/");

```

Whereas the subsequent lines write to 

```
        var fullPath = Path.Combine(DriverScript.GetRelativePath() + @"\reports\html-report\images",filename);
```

Can you try writing the images under `screenshotFolder` and return the path set?

**Comment by harimadusumilli** [comment]
Hello Sriv,

We have tried based on the suggestions you have provided above, it appears that the code is not being called. When we execute we get the following error in the console log of Jenkins. The same code works in Dotnet Core  3.x and not in Dotnet 5.x
Not sure if the Gauge.CSharp.Lib has anything to do with it, that is causing this issue.

Error log in job console:
**panic: empty display string**
goroutine 1 [running]:
main.main()
                /Users/vagrant/go-agent-17.4.0/pipelines/Screenshot/src/github.com/getgauge/gauge_screenshot/main.go:44 +0x19c
[0;32m ✔[0mpanic: empty display string
goroutine 1 [running]:
main.main()
                /Users/vagrant/go-agent-17.4.0/pipelines/Screenshot/src/github.com/getgauge/gauge_screenshot/main.go:44 +0x19c
[0;32m ✔[0mpanic: empty display string
goroutine 1 [running]:
main.main()
                /Users/vagrant/go-agent-17.4.0/pipelines/Screenshot/src/github.com/getgauge/gauge_screenshot/main.go:44 +0x19c


Failed to read screenhsot open /home/jenkins/agent/workspace/bn-qa-testing-center/Donet5Container/.gauge/screenshots/screenshot-1cd324a7-8da3-44c1-aadc-ee02d0d86dd1.png: no such file or directory
Failed to read screenhsot open /home/jenkins/agent/workspace/bn-qa-testing-center/Donet5Container/.gauge/screenshots/screenshot-b472850b-b54a-433b-a18a-82da47eb2437.png: no such file or directory
Failed to read screenhsot open /home/jenkins/agent/workspace/bn-qa-testing-center/Donet5Container/.gauge/screenshots/screenshot-99d08c95-d519-4729-8af4-f0bb66533094.png: no such file or directory
Successfully generated html-report to => /home/jenkins/agent/workspace/bn-qa-testing-center/Donet5Container/reports/html-report/index.html


-----------------------------------------------------------------------

Gauge Screenshot code:

using System;
using System.IO;
using OpenQA.Selenium;
using Gauge.CSharp.Lib;
namespace Gauge.CSharp.Lib
{
    class CustomScreenGrabber : ICustomScreenshotWriter
    {
     public string TakeScreenShot()
        { 
            string screenshotFolder;
            Console.WriteLine("Screenshot Captured Starting");
            screenshotFolder = (String)Path.Combine(Environment.GetEnvironmentVariable("gauge_screenshots_dir")).Replace("\\","/");
            string filename = String.Format("screenshot-{0}.png", Guid.NewGuid().ToString());
            var fullPath = Path.Combine(screenshotFolder,filename);
            byte [] screenshot;
            
           if(DriverScript.driverflg.Equals("Win")){
                screenshot = ((ITakesScreenshot)DriverScript.GetWiniumDriver()).GetScreenshot().AsByteArray;
            }else{
                screenshot = ((ITakesScreenshot)DriverScript.GetSeleniumDriver()).GetScreenshot().AsByteArray;
            }
            File.WriteAllBytes(fullPath,screenshot);
            Console.WriteLine("Screenshot Captured Successfully");
            return fullPath;
        }
    }
}

**Note:**  <PackageReference Include="Gauge.CSharp.Lib" Version="0.9.0"/>

**https://github.com/getgauge/gauge_screenshot/blob/master/main.go**
