### ISSUE TITLE
Lazy parallelization strategy for spec execution

### ISSUE THREAD

**Issue by apoorvam** [getgauge/gauge#217]
**Eager:** Currently, parallelization is done by statically distributing specs to each nodes(depending on number of cores of machine, or -n flag). 
**Lazy:** This should be done dynamically so that its optimized. Certain specs might finish faster than others, which leads to situation where one stream finishes faster, but others are still running.

**Comment by Thunderforge** [comment]
This is completed, right?

**Comment by apoorvam** [comment]
Yep, its completed! Thank you for pointing out.
