### ISSUE TITLE
When Test Fails, I get `Error Message: TypeError: no implicit conversion of nil into String`

### ISSUE THREAD

**Issue by adalberto02** [getgauge/gauge#2175]
Gauge version 1.4.0
rspec (3.10.0)
capybara (3.36.0)

Hi, When a test fails, I get **Error Message: TypeError: no implicit conversion of nil into String**, if a test pass it's fine. 
Also, I get  **Error Message: Encoding::UndefinedConversionError: "\x89" from ASCII-8BIT to UTF-8**

Thank you

**Comment by sriv** [comment]
Hi, can you share any project that I can see this issue in? Also, are there any additional details in the logs?

**Comment by adalberto02** [comment]
Ok,  Below is the Step I use.

`
step 'RULES: Verify that <rule> was updated' do | rule | 
  page.driver.browser.navigate.refresh
  rule_name = find(:xpath, '//*[@name="rules_name"]')["value"]
  expect(rule_name).to be(rule)
end`

If The Test Fails, I get **Error Message: TypeError: no implicit conversion of nil into String**, if the Test Passes, it's fine.

<img width="807" alt="Screen Shot 2021-12-06 at 11 19 51 AM" src="https://user-images.githubusercontent.com/3419059/144882830-c903c900-7a05-4b78-88b6-071e58acb173.png">

Or this error below.

**Error Message: Encoding::UndefinedConversionError: "\x89" from ASCII-8BIT to UTF-8**


<img width="829" alt="Screen Shot 2021-12-06 at 11 24 33 AM" src="https://user-images.githubusercontent.com/3419059/144883425-0f2fb8c3-f204-4fc9-a953-96bba9137255.png">

**Comment by sriv** [comment]
The errors do not look like something gauge/gauge-ruby throws. 

> rule_name and rule are both not nil

I would try adding an explicit `expect(rule_name).to be.not_nil` and ``expect(rule).to be.not_nil` just to make sure. This is the only line where there is string comparison involved.

**Comment by adalberto02** [comment]
Adding the not nil is still cause the test to fail, but the object are not nil.

<img width="680" alt="Screen Shot 2021-12-06 at 12 01 30 PM" src="https://user-images.githubusercontent.com/3419059/144889800-abde3b70-15d0-4726-a3bc-9cbfc8f2ea5a.png">

<img width="643" alt="Screen Shot 2021-12-06 at 12 02 02 PM" src="https://user-images.githubusercontent.com/3419059/144889846-b94e055b-aff5-420a-85ba-d38d65933fe5.png">

**Comment by sriv** [comment]
Can you try commenting out the `rule_name = find...` line? and set `rule_name` to a string value? Wonder which line that is causing this error to pop up.

**Comment by adalberto02** [comment]
It Seems to be coming from the expect().to.

<img width="484" alt="Screen Shot 2021-12-06 at 12 27 49 PM" src="https://user-images.githubusercontent.com/3419059/144893230-6143f9c5-f0a4-4a96-aaf2-bed8bb3796db.png">

<img width="662" alt="Screen Shot 2021-12-06 at 12 28 11 PM" src="https://user-images.githubusercontent.com/3419059/144893233-f7339a43-086c-4239-b97d-7c8077a064cf.png">

**Comment by adalberto02** [comment]
Hi, I use byebug, I think that nothing is being passed into the expect(). 
Any Ideas?

<img width="1068" alt="Screen Shot 2021-12-07 at 2 31 01 PM" src="https://user-images.githubusercontent.com/3419059/145094702-236c5221-860e-4775-863a-55e4dd605ee9.png">

**Comment by sriv** [comment]
Sorry, I am not familiar with byebug

**Comment by adalberto02** [comment]
Ok. Thank you, I will keep trying to debug the issue. 
I think it could be some broken gem.

Thanks!
