### ISSUE TITLE
Make screenshot plugin optional

### ISSUE THREAD

**Issue by ppitonak** [getgauge/gauge#2186]
**Is your feature request related to a problem? Please describe.**
My team has a test suite that doesn't contain any web-based scenarios, only API. It doesn't make sense to have plugin `screenshot` installed and enabled.

**Describe the solution you'd like**
Screenshot plugin is not enabled by default or it's possible to disable it per-project.

**Describe alternatives you've considered**
At the moment, we are installing the plugin but ignore it.

**Additional context**
Discussed in https://github.com/getgauge/gauge/discussions/2069

**Comment by sriv** [comment]
This makes sense @ppitonak. In #2069 - I was referring to a config that would turn off reporting altogether. Is that what you seek here? Or is it the ability to turn of screenshot alone?

**Comment by ppitonak** [comment]
Turning off screenshot is enough for my use-case but I agree that disabling reporting makes sense, too.

**Comment by Flintols** [comment]
also would like the option of making the screenshot readable in report (we should be able to adjust size of screenshot in the report)
