### ISSUE TITLE
[Gauge] Failed to start gauge API: Runner with pid 9528 quit unexpectedly(exit status 1)

### ISSUE THREAD

**Issue by tuyluogluramazan** [getgauge/gauge#2202]
**Describe the bug**

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Initialise a gauge project
2. Run the gauge command
3. See error

```
$ gauge init java
$ gauge run specs
```

**Logs**

```
process C:\Program Files\Java\jre1.8.0_202\bin\java.exe with pid 10344 quit unexpectedly. exit status 1
```

**Expected behavior**
A clear and concise description of what you expect to happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/34194868/151770524-1ca24220-7f18-4276-a96e-584bc363a2a1.png)
```
gauge -v
```
Gauge version: 1.0.7
Commit Hash: ed7b4fd6

Plugins
-------
html-report (4.0.9)
java (0.7.3)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.3)

**Comment by zabil** [comment]
This version of Gauge and JDK is not supported anymore. Please upgrade to JDK 13+ and Gauge 1.4.3

**Comment by tuyluogluramazan** [comment]
Thank you for your helping! 👍

**Comment by makifkus95** [comment]
hi. My java version 17.0.2 and gauge version 1.4.3,
doesn't work for me
