### ISSUE TITLE
Post-Test Conditions

### ISSUE THREAD

**Issue by steve-gray** [getgauge/gauge#221]
Hey folks,

I've got a feature-request around post-test conditions. Effectively what I'm after is the ability to define a set of preconditions up-front, and then have them evaluated again at the end of the scenario to ensure the invariants have not been violated. For example:

```
* In less than "10" seconds
* Go to homepage
* Sign in as user
* Search for product
```

Now, in this scenario technically you _can_ work around these by doing:

```
* Go to homepage
* Sign in as user
* Search for product
* Check elapsed time is less than "10" seconds.
```

But this requires you to start a timer in a @BeforeScenario. The use case for me is that I want to cleanly nest concepts - so for example:

  # Within a user session
- Go to homepage
- Sign in as "user" and "password"
- Return to homepage
- (+) Page should not contain 'Guest'

Where + represents a post-condition that should be checked between every step. So when I write a test:
- Within a user session
- Search for product "blah"
- Click buy now

It is implicit that after steps 1, 2, 3 - the condition 'Page should not contain <text>' is evaluated, and I didn't have to apply it every other line, as this would break the containment/separation of concerns from the concept definition. I was also thinking that a similar '-' operator could be used to cancel expectations that we can stop validating.

Is there some way to achieve this behaviour already that I'm unaware of? I've been thinking to put the logic for this into my Java bindings for the test language (so I'm checking invariants myself, and stacking them with regular commands during tests), but it means that _every_ language statement binding has to do this work - so if I miss one, bad times. I've also only got one place to raise the errors - by throwing an exception in the after-scenario handler, but then nothing turns up in the test log or HTML reports - the whole batch just fails.

**Comment by deepthigc** [comment]
@steve-gray This is a very interesting feature request. There is no way in Gauge to do this. Here are my thoughts:

I see 2 patterns here

1. Verify that the step took x amount of time 

This is not functional. And hence I'd be wary of adding this detail on the markdown. The way I see this work is to be able to pass a timer(like you'd pass a logger) into a step and that takes care of starting the timer and everything else. The duration of the timer is potentially a configuration? I guess this is a rather common use case.

2. Ensure "guest" does not appear on the page

This is functional in nature. And I really do like the idea showing this on the business layer. +/- as you suggested would work. I want to see how we can do this without overloading the markdown heavily and making it unreadable. 

Thoughts?
