### ISSUE TITLE
Failed to start gauge API: Error occurred while waiting for runner process to finish. (exit status 127)

### ISSUE THREAD

**Issue by wwindpk** [getgauge/gauge#2212]
**Describe the bug**
Gauge won't work as described [HERE](https://docs.gauge.org/getting_started/create-test-project.html?os=linux&language=python&ide=vscode).

**To Reproduce**

1. Initialise a gauge project
2. Run the gauge command
3. See the error

```
$ gauge init python
$ gauge run specs/example.spec
```

**Logs**

```
02-03-2022 13:39:04.179 [Gauge] [DEBUG] Created gauge_screenshots_dir at /home/wwind/gauge/.gauge/screenshots
02-03-2022 13:39:04.179 [Gauge] [DEBUG] Plugin python is already installed.
02-03-2022 13:39:04.180 [Gauge] [DEBUG] Plugin html-report is already installed.
02-03-2022 13:39:04.180 [Gauge] [DEBUG] Parsing started.
02-03-2022 13:39:04.180 [Gauge] [DEBUG] Started concepts parsing.
02-03-2022 13:39:04.180 [Gauge] [DEBUG] 0 concepts parsing completed.
02-03-2022 13:39:04.181 [Gauge] [DEBUG] Started specifications parsing.
02-03-2022 13:39:04.182 [Gauge] [DEBUG] 1 specifications parsing completed.
02-03-2022 13:39:04.182 [Gauge] [DEBUG] Parsing completed.
02-03-2022 13:39:04.187 [python] [ERROR] ./start.sh: line 7: python: command not found
02-03-2022 13:39:04.187 [Gauge] [ERROR] Error occurred while waiting for runner process to finish.
Error : exit status 127
02-03-2022 13:39:04.187 [Gauge] [CRITICAL] Failed to start gauge API: Error occurred while waiting for runner process to finish.
Error : exit status 127
```

**My setup**
I tested in three systems and the result was the same for all of them.
1. Ubuntu 20.04 (laptop)
2. Ubuntu 20.04 (Clean install VPS)
3. Linux Mint 20.3 x86_64 (laptop)

**Gauge version**
```
$ gauge -v
Gauge version: 1.4.3
Commit Hash: f98dd40

Plugins
-------
html-report (4.1.4)
python (0.3.17)
screenshot (0.1.0)
```

**Comment by sriv** [comment]
`./start.sh: line 7: python: command not found` -> this seems to be the problem.

Are you able to execute `python --version` in that machine/container? If you are using python3 and your executable is `python3` you can tell gauge to use that by setting `GAUGE_PYTHON_COMMAND = python3` in your properties or via environment variable

**Comment by wwindpk** [comment]
> If you are using python3 and your executable is `python3` you can tell gauge to use that by setting `GAUGE_PYTHON_COMMAND = python3` in your properties or via environment variable

Thank you. This solved the issue.
