### ISSUE TITLE
Require feature to skip the scenario or data iteration for condition mismatch during runtime 

### ISSUE THREAD

**Issue by preetipadalia** [getgauge/gauge#2217]
Hi ,
I am trying to skip a scenario of data iteration based on a condition. 
Can we either provide an exception which can be used to handle this or any method which provide this feature.

Thanks

**Comment by sschulz92** [comment]
I am also interested into this feature :)

**Comment by olivebadger14** [comment]
same here, we have a fair few scenarios which rely on certain resources being available.
If these resources are not available these tests should be skipped.
Currently there is no way to do this so the tests just  intermittently fail

**Comment by chadlwilson** [comment]
Implemented in #2502 / `1.6.8` but will need support in various other language plugins other than C#.

**Comment by preetipadalia** [comment]
Hello @chadlwilson,

Thank you for the fix! When can we expect this feature to be available for the Java language plugin? I’d be happy to contribute if any help is needed for the Java implementation.

Thanks

**Comment by chadlwilson** [comment]
No plans - gauge has very limited maintenance. Probably need to follow over at https://github.com/getgauge/gauge-java/issues/691 

The prototypes/API messages have been updated to include the relevant messages, but it needs an implementation and testing from someone.
