### ISSUE TITLE
Can't use gauge plugins in Docker image for linux-arm64 version

### ISSUE THREAD

**Issue by gadgadskiy** [getgauge/gauge#2229]
Hi. I'm working on creating Dockerfile for local running tests in containers on MAC with an m1 processor (arm64).

I've created an image with gauge successfully as described in [discussion](https://github.com/getgauge/gauge/discussions/2227) but got stuck in trying to set up a java plugin for this version.

I've added a code to install the specific version related to arm64-linux gauge:
```
RUN curl -L https://github.com/getgauge/gauge-java/releases/download/v0.8.1/gauge-java-0.0.1-linux.arm64.zip -o gauge-java-0.8.1-linux.arm64.zip
RUN gauge install java --file gauge-java-0.8.1-linux.arm64.zip
RUN gauge version
```
Dockerfile is building successfully and shows that gauge has the java plugin:
```
Gauge version: 1.4.3
Plugins
-------
java (0.8.1)
DONE
```
But when I'm trying to start tests in just built container, it says me that the plugin is absent and can't be installed:
```
[INFO] --- gauge-maven-plugin:1.4.2:execute (default-cli) @ <my-project-name> ---
Compatible version of plugin java not found. Installing plugin java...
........................
Failed to install plugin 'java' version 0.8.1.
Reason: provided plugin is not compatible with OS linux arm64
```
Logically, I'm getting an error on the test start:
```
[Gauge]
Failed to start gauge API: Plugin 'java' not installed on following locations : [/root/.gauge/plugins]
```
And I can't understand where the plugin disappeared from the docker image.

**Comment by sriv** [comment]
Thanks for reporting this @gadgadskiy . There was a problem in the gauge repository metadata and an incorrect platform binary was linked for gauge-java download. I have made some changes, it takes a few hours to propogate. I'll test this again tomorrow and update you.

**Comment by gadgadskiy** [comment]
@sriv, thank you! Will wait for this fix.

**Comment by sriv** [comment]
@gadgadskiy This should be fixed now, could you please try again?

```
FROM arm64v8/golang as build

ARG GAUGE_VERSION=1.4.3
ARG GAUGE_JAVA_VERSION=0.8.1

RUN go install github.com/getgauge/gauge@v$GAUGE_VERSION

FROM arm64v8/maven:3.6-openjdk-11

ENV GAUGE_TELEMETRY_ENABLED false

COPY --from=build /go/bin/gauge /usr/local/bin/

RUN gauge config check_updates false &&\
gauge install java && gauge -v
ENTRYPOINT ["mvn"]
```

This image let me run `gauge init java && gauge run specs` successfully.

**Comment by gadgadskiy** [comment]
@sriv, yes, it's working now! Thank you!
