### ISSUE TITLE
Installing Gauge with non root account

### ISSUE THREAD

**Issue by SeshuHSC** [getgauge/gauge#223]
Hi 

How to install gauge on linux with a non root account ?

When I tried I got this error

[svc-prdsvc@nvprdappjk001uk tmp]$ ./install.sh
creating /usr/local if it doesn't exist
Copying files to /usr/local
[sudo] password for svc-prdsvc:
Sorry, user svc-prdsvc is not allowed to execute '/bin/sh -c cp -rf bin share /usr/local' as root on nvprdappjk001uk.dev.global.tesco.org.
Done installing Gauge to /usr/local
Installing plugin - html-report. This may take a few minutes
./install.sh: line 35: /usr/local/bin/gauge: No such file or directory

**Comment by mahendrakariya** [comment]
It looks like the user svc-prdsvc doesn't have enough permissions to edit the /usr/local folder. Could you please ask with your system admin to grant `write` permission for this folder?

Alternatively, there is also a manual way of installing Gauge at some other location.
  1. Create a folder named `gauge` in any directory where you want to install it.
  2. Copy paste the `bin` and `share` (present in the unzipped version of Gauge installer) folders in the newly created `gauge` folder.
  3. Add `<path_to_gauge_installation_folder>/gauge/bin` to system path.
  4. Verify gauge installation by running `gauge -v`.
  5. Install the html-report plugin using the command `gauge --install html-report`. 
  6. Install a language runner using the command `gauge --install <language_name>`. For example, `gauge --install java`.
     * Supported languages for Gauge, as of now, are `java`, `csharp` and `ruby`.

In the next release, we will also update our installation script to take custom path as a command line argument, so that users don't have to go through these manual steps if they want to install Gauge to a custom location. We have created an [issue](https://github.com/getgauge/gauge/issues/224) for this, where you will be able to track the progress.

**Comment by SeshuHSC** [comment]
it worked upto point 4

Receiving error  for step 4 and 5 .   Does it looking at  internet  repository?
[svc-prdsvc@nvprdappjk001uk tmp]$ /appl/tmp/bin/gauge --install html-report
[ERROR] html-report : Could not construct plugin install json file URL. Could not find gauge repository url from configuration.

[svc-prdsvc@nvprdappjk001uk tmp]$ /appl/tmp/bin/gauge --install java
[ERROR] java : Could not construct plugin install json file URL. Could not find gauge repository url from configuration.

[svc-prdsvc@nvprdappjk001uk tmp]$ ^C

**Comment by mahendrakariya** [comment]
Yes. Gauge requires internet connection to download and install the plugin. 

There is also an offline way to install the plugins. Download the plugin zip file and run the command `gauge -f <path_to_plugin_zip_ file> --install <plugin_name>`. Plugin zip files can be downloaded from the following locations.
  * **Java:** https://github.com/getgauge/gauge-java/releases
  * **C#:** https://github.com/getgauge/gauge-csharp/releases
  * **Ruby:** https://github.com/getgauge/gauge-ruby/releases
  * **HTML Reports:** https://github.com/getgauge/html-report/releases
  * **XML Reports:** https://github.com/getgauge/xml-report/releases

If you still face any issue, please ensure that the `GAUGE_ROOT` environment variable is set to the gauge installation directory.

**Comment by mahendrakariya** [comment]
@SeshuHSC Were you able to successfully install Gauge? 

In case you are still facing any issues with manual installation, please replace the contents of your `install.sh` script with the contents of [this file](https://github.com/getgauge/gauge/blob/master/build%2Finstall%2Finstall.sh) and run 
```
./install.sh <path_to_custom_installation_dir>
``` 
We have updated the installation script to close https://github.com/getgauge/gauge/issues/224. It will be available in the next release.

**Comment by SeshuHSC** [comment]
Will be trying this  today and get back to you

**Comment by stlecho** [comment]
I'm having the same problem on Windows: "[ERROR] java : Could not construct plugin install json file URL. Could not find gauge repository url from configuration."

**Comment by mahendrakariya** [comment]
Sorry to hear about that. Could you please confirm that `gauge.properties` file is present in C:\Program Files\Gauge\share\gauge folder?

**Comment by stlecho** [comment]
I haven't installed gauge in C:\Program Files\, but I confirm that *%INSTALLATION_DIR%\share\gauge\gauge.properties* exists.

**Comment by mahendrakariya** [comment]
Could you please create a new environment variable called `GAUGE_ROOT` and set its value to the Gauge installation dir? That should fix the issue.

**Comment by stlecho** [comment]
Now I'm having the following error: *Failed to initialize. Failed to find the skeleton file: hello_world.spec*. Do I need to download hello_world.spec ?

**Comment by mahendrakariya** [comment]
The skeleton file should be there in *%INSTALLATION_DIR%\share\gauge\skel*. Could you please confirm this?

**Comment by RatanHSC** [comment]
Hi Mahendra,

I am able to install gauge successfully but while I tried to install java plugin as well but couldn't get through it. Please see below steps I tried

[svc-prdsvc@nvprdappjk001uk appl]$ gauge -f /appl/gauge/gauge-java-0.2.2-linux.x86_64.zip --install gauge-java-0.2.2-linux.x86_64.zip
[INFO] Plugin unzipped to => /tmp/1444384606456176444994247717

[WARNING] Failed to install plugin. Invalid zip file : File /tmp/1444384606456176444994247717/gauge-java-0.2.2-linux.x86_64.zip.json doesn't exist.

If I see in this /tmp/1444384606456176444994247717/ directory it is unzipping the zipped file.
But I am able to successfully install html and xml plugins.

**Comment by mahendrakariya** [comment]
Looks like there is an issue with the command you are using to install java language runner. The command should be 
```
gauge -f /appl/gauge/gauge-java-0.2.2-linux.x86_64.zip --install java
```

and not  *gauge -f /appl/gauge/gauge-java-0.2.2-linux.x86_64.zip --install ~~gauge-java-0.2.2-linux.x86_64.zip~~*

**Comment by RatanHSC** [comment]
Yes you are right. It worked. Thanks for the quick response.

**Comment by mahendrakariya** [comment]
@RatanHSC Cool!

@stlecho Are you still facing any issues with the gauge project initialization?

**Comment by stlecho** [comment]
Now it works for me: *Successfully initialized the project. Run specifications with "gauge specs/"*. Tx for your help :)

**Comment by mahendrakariya** [comment]
Cool :)
