### ISSUE TITLE
After install plugin xml-report, I could publish dashboard like below **screenshot. Artifact has include result.xml .Report file has not specs folder becasue of that chart has no all specs or test case. Could I have all specs in the xml chart

### ISSUE THREAD

**Issue by fundabdeniz** [getgauge/gauge#2281]
After install plugin xml-report, I could publish dashboard like below **screenshot. Artifact has include result.xml .Report file has not specs folder becasue of that chart has no all specs or test case.  @zabil   Could I have all specs in the xml chart 

Pipeline tasks:
![Pipeline-tasks](https://user-images.githubusercontent.com/75672044/185901240-39df1a2c-fba3-4a18-a843-0f32271b2927.png)

![Artfiact](https://user-images.githubusercontent.com/75672044/185900361-891c1ee5-add6-48db-8926-08f87acfa17f.png)

![xml-report chart](https://user-images.githubusercontent.com/75672044/185899836-b55ca087-9b84-4184-a108-7a50674c7c47.png)

_Originally posted by @fundabdeniz in https://github.com/getgauge/gauge/discussions/2279#discussioncomment-3445997_

**Comment by haroon-sheikh** [comment]
@fundabdeniz if you publish the report as junit report and point at the xml report directory. It should show all the specs and scenario results.
