### ISSUE TITLE
Intellij create step implementation in ruby project only wants to create java class

### ISSUE THREAD

**Issue by kmugrage** [getgauge/gauge#229]
I have an existing ruby on rails project in Intellij that I'm looking to add Gauge tests to. I did a "gauge --init ruby" in the root directory of the project.

The new files and setting were created as expected, and running 'gauge specs/' works as expected.

I then created a new specification, a scenario and a couple steps. 

When I use the keyboard shortcut to create step implementation I'm only presented with the option of creating a new file. When I choose that option the file types are for a java project. 

![image](https://cloud.githubusercontent.com/assets/3209933/10396588/44f75ac0-6e58-11e5-81dd-4f53001a115b.png)

**Comment by mahendrakariya** [comment]
Sorry Ken. Gauge IntelliJ plugin supports only Java. We do not have support for any IDE for Ruby as of now.

You can find more details about IDE support [over here](http://getgauge.io/documentation/user/current/ide_support/README.html).

**Comment by kmugrage** [comment]
Ah, didn't realize. Thanks
