### ISSUE TITLE
Gauge could not initialize. Install '' extension for code insights.

### ISSUE THREAD

**Issue by NicoGunst** [getgauge/gauge#2306]
When i open my project the message "Gauge could not initialize. Install '' extension for code insights." is displayed.
I use Gauge version: 1.4.3 with Taiko Version: 1.3.4 (Chromium: 103.0.5056.0) RELEASE.

**To Reproduce**
When I run a scenario :
Running tool: gauge run --hide-suggestion --simple-console /Users/NICOLAS/Workspace/Gauge-Tests/specs/sanity-check.spec:7
env: node: No such file or directory
Error occurred while waiting for runner process to finish.
Error : exit status 127
Error ----------------------------------

[Gauge]
Failed to start gauge API: Error occurred while waiting for runner process to finish.
Error : exit status 127

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://github.com/getgauge/gauge/discussions

Your Environment Information -----------
	darwin, 1.4.3, f98dd40
	html-report (4.1.4), js (2.4.0), screenshot (0.1.0)
Error: Tests failed.

```
$ gauge init java # or js, python etc
$ gauge run specs
```

**Expected behavior**
Must be able to run spec.

**Comment by sriv** [comment]
> node: No such file or directory

It looks like nodejs is either not installed or is not visible in `PATH` to vscode. Could you please check?

**Comment by NicoGunst** [comment]
Nodejs is installed because i can run the tests via CLI using "npm test" for example.
I add this lines in the vscode settings :
"terminal.integrated.env.osx": {
        "PATH":"/opt/homebrew/bin:/opt/homebrew/sbin"
    }
I can now run "node" cmd in the vs code terminal but i still have the same errors when running a scenario/spec.
Any idea of where i can change the path used by the gauge command ?

**Comment by NicoGunst** [comment]
Just find a workaround on stackoverflow : 

1. Configure your shell (bash by default) to have the $PATH you want. For example, my ~/.bash_profile has the following line:
 PATH="$PATH:$HOME/bin"
2. In VS Code, press ⇧⌘P and type install 'code' command if you haven't done so before.
 
3. Quit VS Code.
 
4. Launch VS Code not by clicking the icon in the dock or in Launchpad, but by opening Terminal.app and typing code. Your newly set path will be active in VS Code until you quit it.
 
5. If VS Code restarts, for example due to an upgrade, the $PATH will reset to the system default. In that case, quit VS Code and re-launch it by typing code.

**Comment by chadlwilson** [comment]
Looks like this is an environment issue rather than a gauge issue.
