### ISSUE TITLE
"Failed to start runner" error when using parallelization

### ISSUE THREAD

**Issue by apoorvam** [getgauge/gauge#232]
From Will Herrmann in [google group](https://groups.google.com/forum/#!topic/getgauge/bAsY8TqtXMk): 
We have been running into an intermittent failure with Gauge parallelization where we get the following error:

00:05:17.831 [INFO] 99 scenarios executed, 1 failed
00:05:17.831 [INFO] 66 specifications executed, 1 failed
00:05:17.831 [INFO] 685 specifications skipped
00:05:17.831 [INFO] 4h4m6.92s
00:05:17.833 [ERRO] The following specifications could not be executed:
<Many specs are listed>
Reason : Failed to start runner. fork/exec bin/gauge-java.exe: The system cannot find the path specified..
Process exited with code 1

This happens intermittently, about 1 out of 8 times, and only when we use parallelization. Unfortunately, the error message doesn't provide much information about what the problem actually is, so we are unsure of how to debug it.

**Comment by kashishm** [comment]
We have released [Gauge 0.2.1](https://github.com/getgauge/gauge/releases/tag/v0.2.1) with the fix. Feel free to reopen this issue in case if you face it again.
