### ISSUE TITLE
When is the next release of xml-report expected?

### ISSUE THREAD

**Issue by purplepangolin** [getgauge/gauge#2320]
### Discussed in https://github.com/getgauge/gauge/discussions/2319

<div type='discussions-op-text'>

<sup>Originally posted by **purplepangolin** February  7, 2023</sup>
Hello,

I see that arm64 has recently been added to the multi-arch build: https://github.com/getgauge/xml-report/issues/42 but there doesn’t appear to be a release that includes this yet. Do you know when this is likely to be available please?

Regards

Alastair</div>

**Comment by sriv** [comment]
Hello, I saw your other comment and made a release. 0.3.1 of XML report contains binaries for arm64 macOS. 

Looks like the plugin repo hasn't taken this change yet, need to check.

But you can try downloading the artifact from github releases and do `gauge install xml-report -f <path to file>`

**Comment by purplepangolin** [comment]
Thank you, just spotted it and was coming back to update my comment accordingly. Will try your suggestion.

**Comment by purplepangolin** [comment]
Successfully added to my Docker image using:
```
# Install gauge, plugins and other utilities
RUN npm install -g @getgauge/cli && \
    gauge install js --version 2.4.0 && \
    gauge install html-report --version 4.2.0 --log-level=debug && \
    gauge install xml-report --version 0.3.1 && \
    gauge install screenshot --version 0.1.0
```
Woked with both `amd64` and `arm64` build

**Comment by sriv** [comment]
Thanks for checking and confirming. Glad this works for you.
