### ISSUE TITLE
Need ability to control order of scenario execution inside a spec

### ISSUE THREAD

**Issue by deepesh1511** [getgauge/gauge#2321]
### Description - 

We are migrating from Selenium to Gauge framework for UI and API automation in our project and need the ability to control the order of scenario execution inside a spec. 

Is there any functionality similar to TestNG prioritization? Our existing tests heavily depend on the priority annotation and would like to know if anything similar can be implemented in Gauge.

**Comment by zabil** [comment]
Duplicate of https://github.com/getgauge/gauge/discussions/2322
