### ISSUE TITLE
npm package @getgauge/cli broken (empty binary)

### ISSUE THREAD

**Issue by deitmerit** [getgauge/gauge#2327]
It seems that all versions of @getgauge/cli on npmjs.org are broken (tested 1.4.3, 1.4.2, 1.4.1, 1.3.3). The served tar file contains an empty "gauge" binary (0 bytes) in /package/bin.
`npm install -g @getgauge/cli && gauge --version` results in `gauge: Exec format error` 

This worked at least until 2023-03-15 17:00 UTC. It is failing since at least 2023-03-17 14:30 UTC.

**Comment by ArtemShibaev** [comment]
We faced the same issue. Please fix the package

**Comment by zabil** [comment]
This might take a while to fix. As a workaround please try using other[ installation options](https://docs.gauge.org/getting_started/installing-gauge.html?os=macos&language=javascript&ide=vscode)

**Comment by jonathangiber** [comment]
Same here

**Comment by AdrienDura** [comment]
I changed node image used from
`FROM node`
to
`FROM node:lts-alpine`
It worked well for me

**Comment by xemle** [comment]
I've tested `node:18.x-alpine` images and `node:18.16-alpine` fails to install `@getgauge/cli` npm package correctly.

It seems to be an issue of used [unzipper](https://www.npmjs.com/package/unzipper) package. See their issue https://github.com/ZJONSSON/node-unzipper/issues/271.

The file is downloaded correctly, when replacing `unzip.Extract(...)` with `fs.createWriteStream(path, ...)` in `index.js`.

`node:18.15-alpine` docker image and below are working.

**Comment by ckcr4lyf** [comment]
For my tests running in Alpine container I used

```
RUN curl -SsL https://downloads.gauge.org/stable | sh
```

to install. Seems fixed with that.
