### ISSUE TITLE
Setting log level should also honor console

### ISSUE THREAD

**Issue by zahir033** [getgauge/gauge#233]
Currently setting log level is working fine for api.log and gauge.log entries but it should be applied for console also. Scanning result of all classpath resources is making the console dirty.

**Comment by apoorvam** [comment]
Currently, log-levels can be specified for console output too. 
By default, log level is set to INFO and it gives details on currently executing Specification/Scenario. If you need details at step level, you can set flag `--log-level` to `debug`.

Here is a sample output: 

````
$ gauge specs/hello_world_01.spec
[INFO] Executing specification: Specification Heading
[INFO] Executing scenario: First scenario

[Xml Report Plugin] : Sucessfully generated xml-report to => test/reports/xml-report
[Html Report Plugin] : Sucessfully generated Html-report to => test/reports/html-report
[INFO] Specifications: 	1 executed, 1 passed, 0 failed, 0 skipped
[INFO] Scenarios: 	1 executed, 1 passed, 0 failed, 0 skipped
[INFO] Total time taken: 46ms
````

````
$ gauge --log-level=debug specs/hello_world_01.spec
[INFO] Executing specification: Specification Heading
[INFO] Executing scenario: First scenario
[DEBUG] Executing Step: * This is spec num "1" and run this step after "20" ms
[DEBUG] Executing Step: * Say "hello" to "gauge"

[Xml Report Plugin] : Sucessfully generated xml-report to => test/reports/xml-report
[Html Report Plugin] : Sucessfully generated Html-report to => test/reports/html-report
[DEBUG] Plugin [Html Report] with pid [49413] has exited
[DEBUG] Plugin [Xml Report] with pid [49414] has exited
[INFO] Specifications: 	1 executed, 1 passed, 0 failed, 0 skipped
[INFO] Scenarios: 	1 executed, 1 passed, 0 failed, 0 skipped
[INFO] Total time taken: 42ms
````
Let us know if this is what you expected.

**Comment by apoorvam** [comment]
Any warnings thrown by runner(java) is currently shown as INFO. This is already tracked in this [issue](https://github.com/getgauge/gauge/issues/216). The scanning result of Classpath resources might throw some warnings, which is displayed in console as INFO. Fixing this issue should resolve the problem you are facing.

**Comment by apoorvam** [comment]
Please track the issue #216 for a fix to this. Closing this now.
