### ISSUE TITLE
Add a file system reference to the latest version of a plugin

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/gauge#235]
Gauge projects in an IDE, such as Intellij Idea, must point to the files that are part of a plugin. For instance, a project pointing to the `java` plugin must point to:

```
file://$USER_HOME$/AppData/Roaming/gauge/plugins/java/0.3.1/libs
```

This file path contains a version number though, which requires everyone to have the exact same version installed on their machine. So if, for instance, an Intelij Idea `.iml` file of a Gauge project is checked into version control, everyone must have the exact same version of the plugin installed or it cannot run.

However, we have found that plugin versions are often compatible with each other. Therefore, we would like to have the ability to always point to the latest version. For instance, this might be:

```
file://$USER_HOME$/AppData/Roaming/gauge/plugins/java/latest/libs
```

This saves us the trouble of having to check in `.iml` files every time we upgrade plugins (which we do in lock-step with around 50 users). It also means that those testing the viability of a new version can do so without having to change the files in Idea.

**Comment by kashishm** [comment]
>So if, for instance, an Intelij Idea .iml file of a Gauge project is checked into version control, everyone must have the exact same version of the plugin installed or it cannot run

It is not necessary for everyone to have the exact same version. Reopening the Gauge project will update the `libs` reference in `.iml` file to the latest version of java present in the machine.

Let us know, If the plugin doesn't update `libs` reference after reopening.

**Comment by Thunderforge** [comment]
The `libs` reference in `.iml` is updated when you open. The trouble is that this file is checked into version control. We are using Perforce, so that means that everyone using a different version than the one from the checked in `.iml` file has to check out the file when the directory changes. If we had a file system reference to the latest version, they would not have to check out the file when Idea wants to upgrade it.

**Comment by zabil** [comment]
Is this still an issue?
I assume Gauge can be configured with maven of gradle to refer the right libraries. Closing this for now.
