### ISSUE TITLE
Unable to install gauge plugins on windows

### ISSUE THREAD

**Issue by ketan** [getgauge/gauge#236]
Unable to install a gauge plugin on windows, because gauge downloads packages using `wget` and assumes that it accepts the `--no-check-certificate` flag, which the version of wget I have, does not.

Is there a reason to use wget, can't gauge just download using whatever HTTP libraries that golang provides?

<img width="1115" alt="screen shot 2015-10-19 at 4 14 47 pm" src="https://cloud.githubusercontent.com/assets/10598/10575794/91fd9a6a-767c-11e5-8547-9dd6c5116f93.png">

**Comment by apoorvam** [comment]
Gauge looks for `wget`, `curl` in PATH (in the order specified) to download. If either of these is not present, it uses golang's http libraries to download. 

You bring up an interesting point about why we are not using Golang's http libraries as the default. I am not very sure why this is the case; it was a decision made very early on in the product lifecycle. We'll definitely get back to you with more information on this one. 

For now, one option could be to download plugin zip manually from github releases and install the plugin as described [here](http://getgauge.io/documentation/user/current/troubleshooting/installation.html#plugin-installation). 

We would suggest you to update `wget` to latest version and try installing. We agree this is inconvenient, and we will fix this issue soon.

**Comment by ketan** [comment]
It's not really fun to have to do the sort of workarounds that you are suggesting when automating installation on windows.

You clearly have code which checks for wget, curl and falls back to golang's http libraries. Clearly it's easier for me to delete **your** code than to write new code for automating installation on.

I did a quick grep for curl on the gauge codebase but could not find anything interesting. What gives?

**Comment by deepthigc** [comment]
Hi Ketan,

Couldn't agree more. But before we delete code, we just want to make sure
we understand why it was done. Like Apoorva said, no one seems to think
wget by default is the way to go. We're asking for a little time so can be
sure this change breaks nothing.

Is getting the latest of wget an option?

Regarding curl, you won't find it in core. That is present in commons
<https://github.com/getgauge/common/blob/master/common.go#L649>. You will
definitely find it there :)

Sorry about this, we'll get to it soon.

**Comment by vishnukarthikl** [comment]
One of the reasons why we had used wget is to get the progress of download,
since go's http.Get doesn't give any information nor any callbacks to track
the progress. So we chose to use wget or curl before resorting to http.Get.

**Comment by prateekbaheti** [comment]
Like @vishnukarthikl mentioned, it was because we wanted to get download progress on the terminal and wget/curl were easy wins. We considered this a necessary feature to have.
In my opinion, we could look at an alternate to using the --no-check-certificate flag (or any other version specific flags) to handle https requests before we decide to completely moving to go's http library.

**Comment by vishnukarthikl** [comment]
This also means being dependent on changes to wget and curl. If they change
a flag in the future, it will affect us also. If users are ok with not
being showed the download progress, we can just remove wget and curl.

**Comment by prateekbaheti** [comment]
If we need the progress bar and need to use go's Http library, we could do something like [gofret](https://github.com/aligoren/gofret).

**Comment by apoorvam** [comment]
We do agree that download progress should be shown on console. To solve this issue, we will be looking at both these options: 
1. Using `wget` with no version specific flags. 
2. Use external library in go. 

Thank you @vishnukarthikl @prateekbaheti for the response.

**Comment by mahendrakariya** [comment]
@ketan This issue has been resolved in [Gauge v0.3.0](https://groups.google.com/forum/#!topic/getgauge/qEhw1pcDE3Y). Could you please give it a try?

I am closing this issue for now. Feel free to reopen it if you still get this error.
