### ISSUE TITLE
website is broke

### ISSUE THREAD

**Issue by pwmcintyre** [getgauge/gauge#2374]
**Describe the bug**

is it just me or is the Gauge website broken?

The content loads, but once loaded all the content is hidden:
![image](https://github.com/getgauge/gauge/assets/774725/20b1d308-5f12-48e6-8d19-06380daf2950)

You can see the sections are given the `hidden` class:
![image](https://github.com/getgauge/gauge/assets/774725/f5acd575-39cd-4cdd-b0c8-e1ca0eb7cc70)

**To Reproduce**

Go to any of the pages in incognito:
https://docs.gauge.org/getting_started/create-test-project.html

**Comment by zabil** [comment]
Works for me on the latest versions of chrome and safari

<img width="898" alt="Screenshot 2023-07-05 at 09 12 33" src="https://github.com/getgauge/gauge/assets/54427/d7ce3258-e605-47b5-9dc0-eec24f5714d6">
