### ISSUE TITLE
The XML report generated in Gauge 1.5.1 is incorrect. 

### ISSUE THREAD

**Issue by erdemkiiliic** [getgauge/gauge#2378]
**Describe the bug**
The XML report generated in Gauge 1.5.1 is incorrect. Also, the failure message is not caught.

**To Reproduce**
Gauge 1.5.1 version
xml-report (0.3.1)

**Expected behavior**
The report should be created without problems.
<img width="1663" alt="image" src="https://github.com/getgauge/gauge/assets/79028529/8dbbd006-b9f7-4d41-891a-62fc4505f986">
The screenshot was taken with version Gauge 1.4.3 for the same project and scenario.

**Screenshots**
<img width="1630" alt="image" src="https://github.com/getgauge/gauge/assets/79028529/73553346-3d94-4626-b204-94365d55a8e7">
Gauge version: 1.5.1

**Versions:**
```
gauge -v

Gauge version: 1.5.1
Plugins
-------
flash (0.0.2)
html-report (4.2.0)
java (0.9.2)
screenshot (0.1.0)
spectacle (0.1.4)
xml-report (0.3.1)
```
 - MacOS latest
 - Runner Java 1.8.0_372/Maven 3.9.2

**Additional context**
When I rolled back the version to Gauge 1.4.3 and tried, I saw that the report was generated without any problems.

**Comment by haroon-sheikh** [comment]
Im currently looking into it. Will get back to you shortly. It's related to the same issue here https://github.com/getgauge/gauge/issues/2376
