### ISSUE TITLE
Install plugins globally

### ISSUE THREAD

**Issue by ketan** [getgauge/gauge#243]
Is there currently a way to install plugins globally (in addition to installing in `$HOME`). This would be very useful on shared and build machines to be able to provide a global set of plugins that builds can override for specific needs.

**Comment by mahendrakariya** [comment]
I think providing an option to mention custom plugin installation path should resolve this issue.

**Comment by kashishm** [comment]
Fixed via https://github.com/getgauge/common/commit/0a678df2ef614e8b0185100d6f42cc9d53661008
