### ISSUE TITLE
Provide a consistent way to find plugin version

### ISSUE THREAD

**Issue by ketan** [getgauge/gauge#244]
In order to automate plugin installation, I'm currently having to parse the output of `gauge --version` to see what plugins and versions are installed.

This can be error prone if the format of the output changes in anyway and makes me rather queasy. Can there be a better (machine readable `--machine-readable`) alternative?

An alternative could be to declare the output of `gauge --version` as a contract that shall not be broken :)

**Comment by mahendrakariya** [comment]
@ketan How about yaml based below format as the output of `gauge -v`?

```
Gauge: 0.2.1

Plugins:
  html-report: 1.2.0
  java: 0.3.3
  xml-report: 0.1.1
```

**Comment by mahendrakariya** [comment]
Discussed with @ketan and @sriv. Here's the summary.

  * We won't the change the output format for `gauge -v`. It will remain as it is.
  * A new flag `--machine-readable` will be added to `gauge -v` which will return JSON.
  * The new flag will be valid only with `-v` and `--version` flag. If it is passed in combination with any other flag, an error should be thrown.

**Example:**
```
$ gauge -v --machine-readable
```
```json
{
	"version": "0.3.4",
	"plugins": [{
		"name": "html-report",
		"version": "2.0.0"
	}, {
		"name": "java",
		"version": "0.3.3"
	}, {
		"name": "xml-report",
		"version": "0.1.1"
	}]
}
```

**Comment by ketan** [comment]
:+1:

**Comment by kaustavdm** [comment]
Here is how it looks now:

<img width="371" alt="screen shot 2016-02-24 at 5 49 25 pm" src="https://cloud.githubusercontent.com/assets/364832/13285164/361490e8-db1f-11e5-8bbd-5d030d54d3de.png">
