### ISSUE TITLE
Failed to start gauge API with an error notification:There are version incompatibilities between Gauge and it's plugins in this project. Some features will not work as expected.

### ISSUE THREAD

**Issue by RemiHoston** [getgauge/gauge#2454]
**Describe the bug**
I am working on Win 11 and viscode version 1.85.2(user setup). And have installed the latest version of gauge(1.5.6). 
But when I start run the spec, I got the following errors:
[Gauge]
Failed to start gauge API: Timed out connecting to 127.0.0.1:53329

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://github.com/getgauge/gauge/discussions

Your Environment Information -----------
	windows, 1.5.6, 9b96118
	csharp (0.10.6), dotnet (0.5.2), html-report (4.2.0), screenshot (0.1.0), xml-report (0.4.0)
Error: Tests failed.

And an error notification on the vs code right bottom:
There are version incompatibilities between Gauge and it's plugins in this project. Some features will not work as expected.

I have restarted the laptop and reinstalled the vs code. But shese did not work.

**Comment by RemiHoston** [comment]
The result runs in cmd:
>gauge update --check
No Updates available.

>gauge version
Gauge version: 1.5.6
Commit Hash: 9b96118

Plugins
-------
csharp (0.10.6)
dotnet (0.5.2)
html-report (4.2.0)
screenshot (0.1.0)
xml-report (0.4.0)

**Comment by chadlwilson** [comment]
Not sure of the detail of your specific project, but make sure you update the version of the Nuget dependency for the gauge-dotnet or gauge-csharp plugin that is defined within your project so it matches the plugin version installed with gauge. Can re-open if still having problems.
