### ISSUE TITLE
"Unexpected end of file" for specs that end with a table

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/gauge#247]
Say that I have a spec with the follwoing scenario:

    Second, scenario for the specification
    -------------------------------------
    * Step that takes a table
        |Product|       Description           |
        |-------|-----------------------------|
        |Gauge  |Test automation with ease    |
        |Mingle |Agile project management     |
        |Snap   |Hosted continuous integration|
        |Gocd   |Continuous delivery platform |

However, there is no whitespace in the file following the table. The final line is the final row of the table.

In this case, Gauge gives the following error:

> &lt;table row value&gt;, Specification.NEW_LINE, Specification.TABLE_ORDER or Specification.WHITESPACE expected, unexpected end of file

This seems unnecessarily pedantic to me that there must be a blank line after a table, especially since it's not required for normal steps. I would rather that Gauge allow for the final row of a table to be the last line of a file, and not throw an "unexpected end of file" error.

**Comment by kashishm** [comment]
This issue was moved to getgauge/Intellij-Plugin#115
