### ISSUE TITLE
Gauge-maven-plugin 1.6.1 version has vulnerabilities from its dependencies

### ISSUE THREAD

**Issue by deepesh1511** [getgauge/gauge#2487]
**Describe the bug**
Gauge-maven-plugin `1.6.1` version has vulnerabilities from its dependencies
Maven version - `3.8.1` has direct and dependency vulnerabilities.
Need to upgrade the gauge-maven-plugin to have maven version of `4.0.0-alpha-12`

The org that I work in is blocking gauge-maven-plugin because of this issue. A PR is already created to make the necessary change.

https://github.com/getgauge-contrib/gauge-maven-plugin/pull/85

**Comment by chadlwilson** [comment]
This should probably be resolved by https://github.com/getgauge-contrib/gauge-maven-plugin/pull/87 in the cleanest way
