### ISSUE TITLE
Unable to run tests on Gauge after version update

### ISSUE THREAD

**Issue by deepesh1511** [getgauge/gauge#2488]
**Describe the bug**

Unable to run tests on Gauge after version update. I have a gauge-java-maven project that works on old version of gauge-java library but doesn't work on the latest version.

Old gauge-java dependency version - 0.7.13
New gauge-java dependency version - 0.10.3

![image](https://github.com/getgauge/gauge/assets/64553558/5964f21c-ed47-4237-b865-69b856e2b133)

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Initialise a gauge project
2. Run the `mvn test` command
3. No error displayed, tests are not initiated

**Expected behavior**
Test execution should start.

**logs**

**Comment by chadlwilson** [comment]
There's not enough information here to know what your problem is. What error do you get? What do the gauge logs say? what have you tried to fix the problem? Have you looked through the plugin release notes at https://github.com/getgauge/gauge-java/releases to see any possible reason for your issue?

**Comment by deepesh1511** [comment]
The tests are working with version 0.7.13 but when the version is updated to 0.10.3, the tests are not executed. There is not error or warning on the console neither on the logs. I have to manually terminate the run. There is literally no progress.

**Comment by chadlwilson** [comment]
What does gauge.log say?

Are you using Java 11+?

And how are you running gauge itself? Via the gauge-maven-plugin?

**Comment by deepesh1511** [comment]
I am using Java 11. I tried to run the tests via both maven command and directly from spec file as well. In either case the response was same, the test execution didn’t start. 

gauge maven plugin version is 1.6.1

I can get you the gauge.log tomorrow. From what I see there was no error as such.

**Comment by chadlwilson** [comment]
Unfortunately as I hope you understand - without more information about what works/doesn't work or clear reproduction steps that you have validated without your own custom code, it's a bit harder to help.

You could try incrementally increasing different gauge-java plugin versions from `0.7.13` through to `0.10.3` via the versions at https://github.com/getgauge/gauge-java/releases to find the first version that "broke" things to narrow it down?
