### ISSUE TITLE
Support for golang

### ISSUE THREAD

**Issue by dhanunjay** [getgauge/gauge#249]
Is there any plan to support golang in the near future?

**Comment by sriv** [comment]
We wish to, but we are a small team with our hands full of current stuff. We welcome any help/contribution on this. 

Incidently, someone else had asked for this [on twitter](https://twitter.com/mjmac/status/664836303674978304).

**Comment by joeblew99** [comment]
+1

**Comment by mahendrakariya** [comment]
@manuviswam is working on the golang runner for Gauge.
More details at https://github.com/manuviswam/gauge-go

**Comment by kaustavdm** [comment]
Closing this. Head over to **https://github.com/manuviswam/gauge-go**!
