### ISSUE TITLE
[ERROR] Failed to execute goal com.thoughtworks.gauge.maven:gauge-maven-plugin:1.6.2:execute (default-cli) on project

### ISSUE THREAD

**Issue by svshravankumarAutomationFramework** [getgauge/gauge#2507]
### Discussed in https://github.com/getgauge/gauge/discussions/2501

<div type='discussions-op-text'>

<sup>Originally posted by **svshravankumarAutomationFramework** March 11, 2024</sup>
[ERROR] Failed to execute goal com.thoughtworks.gauge.maven:gauge-maven-plugin:1.6.2:execute (default-cli) on project AutomationFramework: Gauge Specs execution failed. null: GaugeExecutionFailedException -> [Help 1]
I'm getting above error when i run  my code througm command prompt. My test cases are getting executed but at the end I'm seeing this error.

  ## user testing Customer Login        browser name=chrome;
Mar 11, 2024 10:58:21 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 122, returning the closest version; found: 120; Please update to a Selenium version that supports CDP version 122
 P P P P P P P P P P P P P P
  ## user testing Customer Login Excess Withdraw        browser name=chrome;
Mar 11, 2024 10:58:40 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 122, returning the closest version; found: 120; Please update to a Selenium version that supports CDP version 122
 P P P P P P P P P P P P P P
  ## user testing Manager Login browser name=chrome;
Mar 11, 2024 10:58:57 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 122, returning the closest version; found: 120; Please update to a Selenium version that supports CDP version 122
 P P P P P P P P P P P P

Successfully generated html-report to => D:\Gauge E2E Framework\AutomationFramework\reports\html-report\index.html

Specifications: 1 executed      1 passed        0 failed        0 skipped
Scenarios:      3 executed      3 passed        0 failed        0 skipped

Total time taken: 49.681s
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:07 min
[INFO] Finished at: 2024-03-11T10:59:09+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.thoughtworks.gauge.maven:gauge-maven-plugin:1.6.2:execute (default-cli) on project AutomationFramework: Gauge Specs execution failed. null: GaugeExecutionFailedException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

pom file:

 <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.thoughtworks.gauge.maven</groupId>
                <artifactId>gauge-maven-plugin</artifactId>
                <version>1.6.2</version>
                <executions>
                    <execution>
                        <phase>test</phase>
                        <configuration>
                            <specsDir>specs</specsDir>                          
                        </configuration>
                        <goals>
                            <goal>execute</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

command which I'm using: mvn clean test-compile gauge:execute -Dtags="abc"</div>

**Comment by chadlwilson** [comment]
Please don't open a duplicate issue when you already created a discussion.
