### ISSUE TITLE
No support for Visual Studio 2015

### ISSUE THREAD

**Issue by MattFenner** [getgauge/gauge#252]
Just downloaded gauge for the first time and found that it has no support for Visual Studio 2015 which is quite annoying.

Is there plans to port the VS 2013 extension to VS 2015?

Who maintains that extension? Is this the right place to raise this issue? Is the extension open source so that i could have a go at upgrading it myself?

**Comment by MattFenner** [comment]
i just realised that this probably belongs in this area: https://github.com/getgauge/gauge-visualstudio

**Comment by sriv** [comment]
Yes, Gauge-VisualStudio is the right place to raise this. Closing this one.
