### ISSUE TITLE
Explore a way to allow custom order of execution of Scenarios

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#253]
From @krwhitney via gitter:

> If test 'Y' requires that test 'X' run sometime before 'Y', can I create that test and dependency chain? ('X' may have preconditions as well.) Note that ideally test 'X' runs exactly once, no matter how many times test 'Y' runs, but they are structurally independent tests.

> Dependencies are useful in long running test sets, each of which may contain one or more common test activities. If that common test activity takes hours to execute, you naturally want to execute it only once. When one invokes a collection of test sets, each of which may be run independently and thus contain all common and necessary components, it is easy to get overlap in the test activities because they contain common test activities. To avoid that overlap, one can establish dependencies that require something to be run, but also do not run that activity if it has already run.

**Comment by Thunderforge** [comment]
Is this a behavior that we want to encourage? One thing that I like about Gauge is that specs can be run in any order, which makes it optimal for parallelization (this is why JUnit does not allow for dependencies either). I also think it's bad practice for specs to not be self-contained.

For many "I need to have this happen first" behaviors, you can have things execute by simply using `@BeforeSpec` or its siblings. Is there some use case in which this would not be sufficient?

**Comment by sriv** [comment]
@Thunderforge - I don't think this should be the default way, and it certainly would hit our parallelization strategy. (I mentioned this earlier on GItter chat as well)

@krwhitney - Do you think you can use the [Execution hooks](http://getgauge.io/documentation/user/current/execution/execution_hooks.html) at the required level to handle big setup/teardown? This is the recommended Gauge way today.

**Comment by sriv** [comment]
Closing this. Gauge shall continue to encourage independent specs/scenarios. If there is a use-case that requires specific run order, please comment with examples.
