### ISSUE TITLE
Filter by tag in reporting

### ISSUE THREAD

**Issue by harinee** [getgauge/gauge#254]
There is currently no way to list the scenarios based on tags from my tests, in my report.
I would like to see how my tests are split based on the different tags that exist, across spec files.

Things that can help in reporting:
1. Count of scenarios across tags
2. Scenario heading under each tag
3. Ability to drill into the scenario to see the steps

**Comment by kaustavdm** [comment]
Thanks for bringing this up @harinee. Looks like this depends on or is related to #113 and #97. We'll look into this, but seems like it is something we'll want to take up after a while.

**Comment by Thunderforge** [comment]
If this is just about reporting, perhaps it would be better to move this issue to the [html-report](https://github.com/getgauge/html-report) or [xml-report](https://github.com/getgauge/xml-report) projects?

**Comment by mahendrakariya** [comment]
This issue was moved to getgauge/html-report#22

**Comment by manuviswam** [comment]
@Thunderforge @mahendrakariya I think the changes won't be just on the reporting side. AFAIK gauge core is not sending any information about the filtered steps. I may be wrong.

**Comment by deepthigc** [comment]
Update: We will treat this issue as a request to provide the ability to filter and drill down by a given tag on the HTML-report plugin UI. There is another issue(#113) which talks about the need for an api that will fetch all scenarios/specs given a tag expression.
