### ISSUE TITLE
miss makezero in slice init

### ISSUE THREAD

**Issue by alingse** [getgauge/gauge#2545]
**Describe the bug**

I was running github actions to run linter [makezero](https://github.com/ashanbrown/makezero) for top github golang repos.

see issues https://github.com/alingse/go-linter-runner/issues/1

and the github actions output https://github.com/alingse/go-linter-runner/actions/runs/9242995169/job/25426544240 

```
====================================================================================================
append to slice `us` with non-zero initialized length at https://github.com/getgauge/gauge/blob/master/cmd/list.go#L131:[9](https://github.com/alingse/go-linter-runner/actions/runs/9242995169/job/25426544240#step:4:10)
====================================================================================================
```

```
func uniqueNonEmptyElementsOf(input []string) []string {
	unique := make(map[string]bool, len(input))
	us := make([]string, len(unique))
	for _, elem := range input {
		if len(elem) != 0 && !unique[elem] {
			us = append(us, elem)
			unique[elem] = true
		}
	}

	return us
}
```
the us is neither empty and neither unique

`us := make([]string, len(unique))` should be `us := make([]string, 0, len(unique))`

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Initialise a gauge project
2. Run the gauge command
3. See error

```
$ gauge init java # or js, python etc
$ gauge run specs
```

**Logs**

```
Paste any log or error messages here
```

**Expected behavior**
A clear and concise description of what you expect to happen.

**Screenshots**

**Versions:**

```
gauge -v
```
 - OS [e.g. MacOS 10.15.6 (19G2021) please be specific ]
 - Runner info (Please specify the correct version of Java/Node/Python/Dotnet/Ruby)
 - IDE info (If using VS Code or Intellij IDEA)

**Additional context**

**Comment by chadlwilson** [comment]
`len(unique)` is always 0 since this is a map allocated (not a slice), so this seems a false positive. Confusing code though.

**Comment by alingse** [comment]
Yes you are right. LoL, this case is correct in a magic way.
