### ISSUE TITLE
Make the csv table file respect whitespace if columns are quoted

### ISSUE THREAD

**Issue by opursail** [getgauge/gauge#256]
We have fixed format data where whitespace is required. Currently using a csv file for a table means that the whitespace is trimmed. Is there a setting to not trim whitespace, or alternatively can a change be made to preserve whitespace if the data in the csv is quoted  

Example csv:

```
request,response
"DUMMY REQUEST","EXPECTED RESPONSE           " 
```

When you use the response in the code for a step then the whitespace is trimmed from the string

Expected: 

```
response = "EXPECTED RESPONSE           " 
```

Actual: 

```
response = "EXPECTED RESPONSE"
```

A work around would be to load the csv into a data store, but it would be nice to be able to use the inbuilt table csv feature

**Comment by apoorvam** [comment]
With [this](https://github.com/getgauge/gauge/commit/4bf65f372552eead7037170f6a7b319dfd301e05) commit, the whitespaces in CSV input is not ignored as per [CSV standard](https://tools.ietf.org/html/rfc4180#page-2).

However in case of inline table the leading and trailing white spaces are trimmed.
