### ISSUE TITLE
Exception occurred in Gauge executable

### ISSUE THREAD

**Issue by mervehakyemez** [getgauge/gauge#2583]
Hello,
Exception occurred in Gauge executable

When i try to open my automation project on intellij, it's starting to initialize.
However i had an error message
"Exception occurred in Gauge executable"

Steps (or project) to reproduce the behavior:
1.  Open project on intellJ
2. Wait to initialize gauge connection for the project
3. See error

**Error details:**
Exception occurred in Gauge executable
			More details...
			Please report an issue to https://github.com/getgauge/gauge/issues with following details:
			#### Gauge process exited with code ```1```
			Error ----------------------------------

			My Environment Information -----------
			darwin, 1.6.7
			html-report (4.1.4), java (0.9.2), screenshot (0.1.0), xml-report (0.2.3)
			* IDE version: 2021.3.3
			* API version: IU-213.7172.25
			* Plugin version: 213.5744.125
			* Gauge version: 1.6.7
			
Could you please help me?
Thank you.

**Comment by chadlwilson** [comment]
Does it work fine when launched from the command line? if so, you may need to raise with the IntelliJ plugin, that's not maintained here.

Did you look at the gauge logs or logs from IntelliJ to find anything useful? There's not enough information here to debug anything.

**Comment by chadlwilson** [comment]
Will re-open if you can supply more detail. If you installed gauge via npm, try updating to the latest (1.6.8).
