### ISSUE TITLE
plugin gauge java not recognized after installation

### ISSUE THREAD

**Issue by israel-santiago-praxis** [getgauge/gauge#261]
After performing the installation of java plugin, the gauge is not recognizing it , following images :

![install](https://cloud.githubusercontent.com/assets/13141011/11427562/e704f954-944a-11e5-95a6-4e4ac30658e6.png)

![notinstall](https://cloud.githubusercontent.com/assets/13141011/11427585/13c7e0aa-944b-11e5-920d-0b3c2baf3e92.png)

Configuration:
  Ubuntu 14.04.3 LTS
  Java version "1.8.0_66"
  Gauge version: 0.2.1

Please , any suggestions?
Thank you !

**Comment by mahendrakariya** [comment]
Welcome to Gauge!

Sorry to hear about the issue. Could you please confirm if `java` folder is present in the `~/.gauge/plugins/` directory?

**Comment by israel-santiago-praxis** [comment]
Thank you and congratulations on the excellent work in the gauge !
So, yes the older is present.

![tela2](https://cloud.githubusercontent.com/assets/13141011/11428815/fb6a0a2c-9456-11e5-9b54-afa5e864228d.png)

**Comment by mahendrakariya** [comment]
The presence of this folder indicates Gauge java plugin is installed. Could you please try running the command `gauge -v` once more and check?

**Comment by israel-santiago-praxis** [comment]
Strange ... now the plugin was displayed !!! 

![tela3](https://cloud.githubusercontent.com/assets/13141011/11429033/360244c2-9459-11e5-9b31-f69f0d580ac5.png)

When I open a new section of the terminal, the gauge continues to inform that the plugin was not installed :-(

![tela4](https://cloud.githubusercontent.com/assets/13141011/11429072/ccbe577a-9459-11e5-8d07-bab085d052bb.png)

Any possible suggestion for the random behavior ?!!?!

**Comment by mahendrakariya** [comment]
That's strange. 

Could you please logout and login once? This will ensure that Gauge related environment variables are set across all shells.

**Comment by israel-santiago-praxis** [comment]
did not work :-(

![tela7](https://cloud.githubusercontent.com/assets/13141011/11440827/f7aff806-94ec-11e5-9dac-2fc1da629110.png)

**Comment by mahendrakariya** [comment]
Hi @israel-santiago-praxis,

Gauge can be installed globally across the system by doing `sudo ./install.sh`. But Gauge plugins are installed in user's home directory.

If you have installed plugins via some other user or by using `sudo`, you won't be able to access them by doing `gauge -v`. Could you please ensure that you are installing plugins and running Gauge from the same user (without `sudo`)?

P.S. You don't need to use `sudo` for installing plugins.

**Comment by xmeltrut** [comment]
I had the same issue. Removing the directory, re-installing without sudo, and then restarting my terminal session resolved it.

**Comment by kaustavdm** [comment]
As @xmeltrut mentioned, you can hit this issue if you use different users to install the plugins and run gauge. Using `sudo` uses the `root` user's settings, so it will try to look for `.gauge/` dir in the home directory of `root`.

I'm closing this for now. Please reopen if you have further concerns.

**Comment by israelsantiago** [comment]
Problem resolved ! Thanks a lot !
