### ISSUE TITLE
Windows Visual Studio HTML Report Only Outputs One Spec

### ISSUE THREAD

**Issue by jason-roberts** [getgauge/gauge#262]
When using VS runner and there is more than 1 specs file, when all tests are run at once (and hence multiple spec files) in VS Test Explorer, only one spec is ever output to HTML report (looks like the last test/spec that gets executed gets output).

Running multiple specs from command line at the same time works as expected with all specs output correctly in HTML report.

**Comment by jason-roberts** [comment]
Looks like this is a duplicate of https://github.com/getgauge/gauge-visualstudio/issues/72

**Comment by sriv** [comment]
@jason-roberts - please see [my comment](https://github.com/getgauge/gauge-visualstudio/issues/72#issuecomment-160560186) on the issue for further analysis.
