### ISSUE TITLE
Vscode ide support

### ISSUE THREAD

**Issue by joeblew99** [getgauge/gauge#264]
Anyone know ?
I am finding vscode excellent

**Comment by sriv** [comment]
We have a Visual Studio 2013 plugin, but nothing on VSCode AFAIK.

**Comment by joeblew99** [comment]
+1 :)

**Comment by bloodsplatter** [comment]
+1 here as well. Either that or a plugin for VS2017

**Comment by gbaligh** [comment]
+1

**Comment by sriv** [comment]
FYI, we have started work on vscode plugin. You may see the progress and give feedback [here](https://github.com/getgauge/gauge-vscode).

I'll mark this issue as closed, vscode specific issues can be logged [here](https://github.com/getgauge/gauge-vscode/issues).
