### ISSUE TITLE
Windows: gauge.properties is scanned at incorrect location

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#269]
Refer to https://github.com/getgauge/gauge-csharp/issues/45

The `gauge.properties` file is located at `C:\Program Files\Gauge\share\gauge`, but in this case, Gauge seems to try to read it from `C:\Program Files\Gauge\bin\share\gauge`, which is not right.

**Comment by apoorvam** [comment]
By default, Gauge sets the `GAUGE_ROOT` to install location, i.e `C:\Program Files\Gauge` in windows. If its custom location, `GAUGE_ROOT` is set to this path. 

This issue happens only when user have manually set the env variable `GAUGE_ROOT` to an incorrect value.

**Comment by sriv** [comment]
Not reproducible anymore.
