### ISSUE TITLE
How to execute gauge with exclude tag

### ISSUE THREAD

**Issue by itsmemittal** [getgauge/gauge#271]
I have read the gauge documentation and found that we can do execution using tag filtration but is there any way of inverse of this. 

i want to exclude test from execution based on tag name

**Comment by mahendrakariya** [comment]
Yes. You can. [This page](http://getgauge.io/documentation/user/current/execution/tagged_execution.html) has some examples.

**Comment by kashishm** [comment]
@itsmemittal were you able to pass tag expression while execuing Gauge?
