### ISSUE TITLE
Multiple Tags with BeforeScanario hook is not working

### ISSUE THREAD

**Issue by itsmemittal** [getgauge/gauge#272]
I am using BeforeScanario Hook and when i am passing multiple tags comma separated then it is not working

For example  

[BeforeScanario["tag1","tag2"]
public void Setup(){
}

**Comment by prateekbaheti** [comment]
I think your usage is incorrect. See the usage for multiple tags in
execution hooks java here
<http://getgauge.io/documentation/user/current/test_code/java/execution_hooks.html#filtering-hooks-execution-based-on-tags>
.

// A before spec hook that runs when tag1 and tag2 is present in the
current scenario and spec.
    @BeforeSpec(tags = {"tag1, tag2"})
    public void setup() {
       // Code for before scenario
    }

This execution hook will run only when both tags are present in this case.

**Comment by itsmemittal** [comment]
Can we support that any tag from the given tag list i n before hook match
to scanario tag then before hook method should execute.

**Comment by prateekbaheti** [comment]
Yes you can do that using OR aggregation

````java
    @BeforeScenario(tags = {"tag1", "tag2"}, tagAggregation = Operator.OR)
    public void performBeforeScenario() {
       // Code for Before Scenario
    }
````

**Comment by itsmemittal** [comment]
Is this support to csharp because before hook have only one para meter
support

Yes you can do that using OR aggregation

    @BeforeScenario(tags = {"tag1", "tag2"}, tagAggregation = Operator.OR)
    public void performBeforeScenario() {
       // Code for Before Scenario
    }

—
Reply to this email directly or view it on GitHub
<https://github.com/getgauge/gauge/issues/272#issuecomment-164096392>.

**Comment by sriv** [comment]
Yes, this is supported in `gauge-csharp` as well. A slightly different syntax though. You can use the `TagAggregationBehaviour` attribute to specify that you want an `OR` aggregation. The default is `AND`.

Have a look at the example from the [unit tests](https://github.com/getgauge/gauge-csharp/blob/master/Runner.UnitTests/Processors/HookExecutionProcessorTests.cs):

- [Definition](https://github.com/getgauge/gauge-csharp/blob/master/Runner.UnitTests/Processors/HookExecutionProcessorTests.cs#L41)
- [Behaviour](https://github.com/getgauge/gauge-csharp/blob/master/Runner.UnitTests/Processors/HookExecutionProcessorTests.cs#L108)
