### ISSUE TITLE
Failed to start gauge API: Runner exited with error

### ISSUE THREAD

**Issue by anushkaa** [getgauge/gauge#273]
Trying to run Gauge projects in command line in MacOS (Tried with IntelliJ too with latest gauge plugin )
Almost same error in the screenshot

All gauge projects give the same error as in the screenshot, updated the gauge java plugin to latest version, uninstalled and installed the jave plugin.

Is there any way to uninstall Gauge completely and try again?

Kindly help!

<img width="765" alt="screen shot 2015-12-15 at 12 59 51 pm" src="https://cloud.githubusercontent.com/assets/1584369/11806930/46b645f6-a33c-11e5-8bbc-129085233747.png">

**Comment by mahendrakariya** [comment]
If you have installed Gauge using `brew`, you can use it to uninstall it. 

But before uninstalling and reinstalling, could you try invoking Gauge from 1 directory above (from `~/Gauge/gauge-demo-project`) with the command `gauge specs/ShoppingCart.spec` and see if you are still getting the same error?

**Comment by apoorvam** [comment]
@anushkaa 
Refer this [doc](http://getgauge.io/documentation/user/current/troubleshooting/installation.html) to find the installation location for Gauge and its plugins.

You can uninstall plugin using `uninstall` flag.

**Comment by anushkaa** [comment]
Thanks Apporva, issue resolved by uninstalling gauge from bin folder.
Thanks for the help!
