### ISSUE TITLE
Stdin input is printed as log

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#274]
ref : https://github.com/getgauge/gauge-ruby/issues/17

Although this came up when @cococoder found an issue with pry + gauge-ruby, this is because of the way Gauge treats the Stdout stream from the runners.

Gauge-core redirects stdout, stderr from the runner. Pry brings up a REPL for users to use, and this causes stdin characters to be reflected in stdout immediately. Gauge intercepts this stdout writes and logs them in a new line.

**Comment by kashishm** [comment]
Fixed via 08ee26c3e6354be9974571f42a618a22a3f4e559
