### ISSUE TITLE
Support for non-asterisk lists

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/gauge#279]
_From @tlempart on July 8, 2015 7:51_

Asterisk lists are used to define scenario steps, but sometimes there is a need to use lists for documentation purpose within scenario/specification. It would be great, if you can render non-asterisk lists (http://daringfireball.net/projects/markdown/syntax#list) properly.

_Copied from original issue: getgauge/html-report#11_

**Comment by mahendrakariya** [comment]
_From @Thunderforge on September 22, 2015 19:38_

I think that this should be moved to the general [gauge project](https://github.com/getgauge/gauge/issues), since HTML is just reporting

**Comment by zabil** [comment]
Gauge will stick to asterisk for list for now and it wants to keep other symbols available for other implemetations for example https://github.com/getgauge/gauge/issues/805
