### ISSUE TITLE
Export execution report to Excel or CSV

### ISSUE THREAD

**Issue by kaustavdm** [getgauge/gauge#280]
This was originally requested in getgauge/html-report#16 by @uzmar. This should ideally be a separate plugin and not part of html-report.

**Comment by jackperalta** [comment]
do you have any idea on how csv/excel shall be structured ? What information should go into the reports?

**Comment by sriv** [comment]
@jackperalta not really, I guess this should be driven by user needs?

**Comment by jackperalta** [comment]
I agree completely. I was just wondering, whether such needs are already known.


Gesendet von Yahoo Mail für iPhone


Am Freitag, Februar 23, 2018, 5:17 AM schrieb Srikanth <notifications@github.com>:


@jackperalta not really, I guess this should be driven by user needs?

**Comment by sriv** [comment]
No, unfortunately this was brought up in one of the team discussions, and has been logged to gauge (pun unintended!) the interest in such a format.

Thoughts/ideas are welcome.

**Comment by sriv** [comment]
There is now a [report-seed](https://github.com/getgauge-contrib/report-seed) plugin template, with examples for csv (and other formats). Building a plugin using it is possible, but not something the gauge team will undertake right away.

Closing as stale. Please comment/reopen if this is still valid.
