### ISSUE TITLE
pass environment variables and command line arguments to runner

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#282]
When launching Gauge, if user sets environment variables via command line or command line arguments, Gauge should pass it all to the language runners. 

I.e. any command line argument that gauge does not understand should be passed on to the runner.

**Comment by haroon-sheikh** [comment]
@sriv @mahendrakariya Can we please prioritise this? I've come across another scenario where this would really useful.

For example, the reports directory... when running on CI, I need to be able to dynamically set the reports directory depending on what's being run.

**Comment by mahendrakariya** [comment]
@haroon-sheikh Can you please install yesterday's [Gauge nightly build](https://bintray.com/gauge/Gauge/Nightly/view) and try out your use case?

**Usage:**
```
gauge_reports_dir=newReportsDir mvn gauge:execute
```

**Comment by kaustavdm** [comment]
Tested. This works for me. 

<img alt="Gauge environment variable in commandline" src="https://cloud.githubusercontent.com/assets/364832/12638350/695e47ea-c5c2-11e5-8b22-8fab3aa5985b.png">

**Comment by mahendrakariya** [comment]
For more details, please refer the _Precedence of Environments_ section in the [environment documentation](http://getgauge.io/documentation/user/current/managing_environments/index.html).
