### ISSUE TITLE
install.sh has old version hardcoded

### ISSUE THREAD

**Issue by jean** [getgauge/gauge#287]
https://github.com/getgauge/gauge/blob/master/install.sh has `latest_release='0.1.6'` while https://github.com/getgauge/gauge/blob/master/version/version.go has 0.3.1
This will always cause bitrot.

The version number should be stored once and retrieved in a canonical way. Here's guidelines for Python: [Single-sourcing the Project Version](http://python-packaging-user-guide.readthedocs.org/en/latest/single_source_version/) 

What is the proper way in go?

**Comment by mahendrakariya** [comment]
This is definitely an issue. But honestly, I am not sure if this file is in use anymore. We will have to check. If it's not in use, we should delete this file.
