### ISSUE TITLE
Event log errors in IntelliJ Idea after updating gauge and plugin

### ISSUE THREAD

**Issue by smathistad** [getgauge/gauge#289]
I currently use IntelliJ IDEA (v14.1.6).  After upgraded to gauge v0.3.0, I restarted IDEA and saw a popup to upgrade the gauge plugin for IDEA.  After I upgraded the gauge plugin to v0.1.0, I began getting a very large number of errors in the event log (see below). And I haven't even run any gauge specs yet.  Also after running a few specs, IDEA will freeze and have other strange behavior.  If I uninstall the plugin v0.1.0 and reinstall v0.0.15, the issues go away.

The following error occurs about 100 times before IDEA says there are too many fatal errors and stops monitoring.

10:00:32 AM	Throwable
			Access is allowed from event dispatch thread only.
			Details: EventQueue.isDispatchThread()=false
			isDispatchThread()=false
			Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@aa02cb
			Current thread: Thread[JobScheduler FJ pool 0/8,6,main] 4399826
			SystemEventQueueThread: Thread[AWT-EventQueue-0 14.1.6#IU-141.3056.4, eap:false,6,main] 20885278
			"AWT-EventQueue-0 14.1.6#IU-141.3056.4, eap:false" prio=0 tid=0x0 nid=0x0 waiting on condition
			java.lang.Thread.State: WAITING
			on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@e762f7
			at sun.misc.Unsafe.park(Native Method)
			at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
			at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
			at java.awt.EventQueue.getNextEvent(EventQueue.java:554)
			at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:170)
			at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThrea... (show balloon)

**Comment by mahendrakariya** [comment]
@smathistad Could you please let us know what Gauge version you are using along with Gauge plugin versions? You should be able to get these details by running `gauge -v`.

**Comment by smathistad** [comment]
I have Gauge version v0.3.0 and Gauge plugin version v0.1.0

**Comment by kashishm** [comment]
Thanks for reporting the issue. We could not reproduce the issue on intelliJ 14 and intelliJ 15. 
Are you seeing the same behaviour on a new Gauge project?

**Comment by kashishm** [comment]
This issue was moved to getgauge/Intellij-Plugin#117
