### ISSUE TITLE
Gauge uninstall / update issue - Windows 7

### ISSUE THREAD

**Issue by pataky** [getgauge/gauge#291]
**Platform:** Windows 7, 64 bit, Version 6.1.7601
**Expected:** When the someone executes the gauge uninstaller it should remove the gauge completley.
**Actual:** First I downloaded a new version of gauge (gauge-0.3.1-windows.x86_64) and ran the installer. The installation was successful but according to the command line I still had the old version (0.1.7).
After that I executed the gauge uninstaller and it finished without any issues. I checked the gauge version again on command line it said I still had the uninstalled version of gauge. I checked the path environmnet variable and gauge wasn't removed form there. After I removed it and restarted the OS and checked gauge again it was still installed according to the system. 
![gauge_1](https://cloud.githubusercontent.com/assets/8683488/12712365/239511a4-c8c8-11e5-9f01-a897107e92ac.PNG)

**Comment by mahendrakariya** [comment]
@pataky Can you please try running `where.exe gauge` on command prompt to check the path of Gauge executable? Is it pointing to the directory where you installed Gauge v0.3.1?

**Comment by sriv** [comment]
@pataky - is this still an issue? I am closing this assuming it isn't. Please reach out if this is still not working, and we will troubleshoot further.

**Comment by pataky** [comment]
@sriv Sorry for I didn't response. I've got a new workstation and I had not been able to reproduce the issue there.
