### ISSUE TITLE
please, support typescript with decorator

### ISSUE THREAD

**Issue by alexsad** [getgauge/gauge#293]
Great project ,
Please, with the advent of angular 2 help us with support to typescript.

**Comment by kaustavdm** [comment]
Do you mean that you want to write your tests in TypeScript? The closest we have as of now is a [JavaScript test runner for gauge](https://github.com/getgauge-contrib/gauge-js).

**Comment by rightisleft** [comment]
Typescript support would be amazing

**Comment by sriv** [comment]
There have been some discussions here (some relevant, but not specific to typescript)

- https://github.com/getgauge/gauge-js/issues/187
- https://github.com/getgauge/gauge-js/issues/168

**Comment by BugDiver** [comment]
@rightisleft @alexsad I have created gauge typescript plugin (with decorators support).
Please try it out and give some feedback so that we can improve the plugin.
To get started refer the https://bugdiver.github.io/gauge-ts/#/
