### ISSUE TITLE
Visual Studio Issue 

### ISSUE THREAD

**Issue by marek2209** [getgauge/gauge#297]
Hi,

I have problems with Visual Studio 2013 and 2015 integration...
I`ve opened  https://github.com/getgauge/gauge-example-csharp  project  but i can`t see any tests in Test Explorer Window... How i can start this demo project ?

**Comment by sriv** [comment]
Is this happening consistently? Or are you seeing this behaviour intermittently?

It would help if you could look at the Output Pane -> "Gauge" output and paste that log for debugging.

**Comment by sriv** [comment]
Also, if you could run `gauge -v` in your command prompt and paste the output, it will help troubleshoot. thanks.

**Comment by marek2209** [comment]
C:\Users\msiebert>gauge -v
Gauge version: 0.3.2

Plugins
-------
csharp (0.7.1)
html-report (2.0.0)
ruby (0.1.0)

**Comment by marek2209** [comment]
Problem solved. I`ve reinstall VS plugin as a Admin.

**Comment by kaustavdm** [comment]
@marek2209 Closing this as you reported the problem has been solved. Feel free to reopen this if it recurs.
