### ISSUE TITLE
Add spec file name and step line number in case of failure

### ISSUE THREAD

**Issue by apoorvam** [getgauge/gauge#298]

**Comment by BugDiver** [comment]
Fix should be available in nightly > 26-05-2016

**Comment by sguptatw** [comment]
The line number should be clickable.
This should be available in other reporting formats like html and xml.

**Comment by mahendrakariya** [comment]
Making line number clickable is not feasible on console output. However, this can be done in reports and probably on IDEs. So I think this should be a separate issue on the respective repos.

**Comment by sguptatw** [comment]
If the failure is inside a concept, the information getting displayed is incorrect.
