### ISSUE TITLE
Cant start tests from visual studio

### ISSUE THREAD

**Issue by marek2209** [getgauge/gauge#300]
I cant debug and start tests. I have succesfully rebuild. But after start or debug i receive this exception
![image](https://cloud.githubusercontent.com/assets/9087374/13173292/0df45f6a-d6fd-11e5-8bec-4c3bb7272b16.png)

**Comment by sriv** [comment]
Just to confirm, this is still on VS2015?

**Comment by marek2209** [comment]
Yes

**Comment by sriv** [comment]
Could you please try Gauge-VisualStudio [v0.2.1](https://visualstudiogallery.msdn.microsoft.com/dd8ea767-aa75-4771-98f4-6c8a9055ca92)? This should be fixed. I am closing this issue, please feel free to reopen if you still face problems.
