### ISSUE TITLE
Provide a hook to show custom execution information in reports(at spec level)

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge#301]
Provide a hook to add information like browser and os used from the implementation to the reports.
For more details refer [this post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/getgauge/9UugT-WeudA/lql4uejeAAAJ).

**Comment by kbangur** [comment]
Can someone please share if we are expected to see any movement with this request in near term..

**Comment by JanVandekerckhove** [comment]
Any plans for implementation of this one in a next release ?
We are using a randomize browser for the test execution of each spec -> we want to track on what specific browser a test ran through the report.

Thank you !

**Comment by sriv** [comment]
There are a couple of options that I can think of:

1. Expose methods similar to [Gauge WriteMessage](https://docs.getgauge.io/language.html#custom-messages-in-reports) that will let users write metadata from their test suites.

This will require changes to proto contract, gauge core, all language runners and html-report.

2. The meta information shall be stored in properties and env vars, user's test code will have to read and use this data from respective env vars. Html report can have a property that will contain a white list of the properties to publish, and read these property values and publish them in reports.

Personally I feel option 2 is less disruptive and also easier to implement. But as users what do you prefer @kbangur, @JanVandekerckhove ?

**Comment by JanVandekerckhove** [comment]
Hi sriv, 

Thank you to think about this.
I'm still a beginner with Gauge I have to admit.  I hope my reply makes sense :-)

For me it is enough when I could write a message to the html report from a BeforeSuite hook (as I'm initializing my Selenium webDriver instance of a particular browser over there).
My requirement / usage could be too narrow and if you want to make things usable to a larger extent that is also OK with me :-).

Thank you !

Jan

**Comment by sriv** [comment]
Hi Jan,

As an implementor, it is easier for me to just allow ENV vars/properties to be selectively included, when generating the report. 
 Building an API that you could call in the `BeforeSuite` is option 1, and requires much more thought, development and testing of course!

I have been thinking a bit more, and it seems to me that using ENV to configure has other benefits (i.e. you can control the behaviour much better in a CI setup).

So I am inclined with option 2 (and you can definitely use the BeforeSuite hook to read ENV and setup accordingly), unless someone has a major point against it.

**Comment by JanVandekerckhove** [comment]
Hi sriv,

Thank you.
I think it would suite in case the browser to be used ( I refer to my use case) is fixed for all scenario's to be executed (and set like that using ENV), but not when the ENV is marked with "random" meaning for every scenario execution a random browser is being chosen out of a list of eg. 4 browsers foreseen.  
Perhaps I don't get it fully and it is possible after all with your solution ?  A more detailed example would help in that case.

Thanks again !

Jan

**Comment by sriv** [comment]
Hi Jan,

Interesting use case. No, my proposal will not work for what you are describing.

To be honest, almost every user I have seen pre-determines the browser before the run.

As I mentioned earlier, adding this will require changes to multiple components, hence may not be as trivial. At the moment, we have some help for redesigning the html-report (please see getgauge/html-report#99). I'm afraid this one will have to wait at least till then.
