### ISSUE TITLE
Support concept in specification file

### ISSUE THREAD

**Issue by hakito** [getgauge/gauge#305]
We would like to have a collection of specification specific concepts within a .spec file.
For example

```
Specification Heading
=====================

My Scenario
-----------
* Run step from concept

# Run step from concept
* Hello world
```

Otherwise specification specific concepts would be available for all other spec files. Currently the above syntax is not allowed because the concept line is interpreted also as a specification heading.

**Comment by zabil** [comment]
It would be tough to parse concepts inside a specification file as we use the same syntax for scenario headers.
