### ISSUE TITLE
Configurable parallel execution of rows [table driven execution]

### ISSUE THREAD

**Issue by bmiael** [getgauge/gauge#306]
My team is using table driven execution for nearly all of it's tests, but some of our tables have over 1000 rows, each taking up to 3 seconds to run. If it were possible to execute them in parallel (In cases where parallelization would matter) that would vastly speed up our specs.

**Comment by pradnyasamant** [comment]
When would we expect this feature?

**Comment by saritapol13** [comment]
This feature was available in Twist. We are moving from Twist to Gauge. We have around 100+ scenarios with 500+ data table rows which is impacting us badly in execution time as the specs are running in serial with 500+ rows.

It would be really helpful if this feature is avilable soon.
