### ISSUE TITLE
No way to define separate table-driven execution values

### ISSUE THREAD

**Issue by harinee** [getgauge/gauge#312]
### Expected behavior
There should be way to define data in table-driven execution at scenario level.
I may not necessarily use the same data all through the specification.

### Actual behavior
The only way to define data for table-driven execution is from the spec level. So I have to define a spec for every scenario I want to test with different combinations of data.

### Steps to reproduce
http://getgauge.io/documentation/user/current/execution/table_driven_execution.html

### Gauge version
Gauge version: 0.3.0

**Comment by mahendrakariya** [comment]
This seems to be a duplicate of #111.

**Comment by kashishm** [comment]
We will track this at #111.
