### ISSUE TITLE
Multiple step definitions accepted, causing issues while reporting

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#313]
Given the following spec

Users should be able to start the game
======================================

* User "user"should be able to join the game
User should be able to access the site
---------------------
tags: join

User should be able to join an existing game
---------------------
tags: search

If there is a failure in the step, the error is getting reported twice(as many number of step definitions)
[index.html 2.zip](https://github.com/getgauge/gauge/files/198089/index.html.2.zip)

**Comment by mahendrakariya** [comment]
The language runners will have to take care of this. There is an issue in each of the repos.

  - https://github.com/getgauge/gauge-java/issues/43
  - https://github.com/getgauge/gauge-csharp/issues/55
  - https://github.com/getgauge/gauge-ruby/issues/20
