### ISSUE TITLE
CANT RUN TEST WITH RUBY

### ISSUE THREAD

**Issue by marek2209** [getgauge/gauge#317]
![image](https://cloud.githubusercontent.com/assets/9087374/14205832/a1bf2cd4-f80e-11e5-9347-ba373356e370.png)

windows 10 
latest version of gauge 
C# and ruby language runner instaled
latest ruby

Why i cant start tests. ?..

**Comment by kashishm** [comment]
I think it is missing the gauge-ruby gem. Can you try running bundle install
in the project directory, this should install latest gauge-ruby gem.

On Fri, Apr 1, 2016 at 5:06 PM, marek2209 <notifications@github.com> wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/9087374/14205832/a1bf2cd4-f80e-11e5-9347-ba373356e370.png>
>
> windows 10
> latest version of gauge
> C# and ruby languaga runner instaled
> latest ruby
> \
>
> Why i cant start tests. ?..
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/getgauge/gauge/issues/317>
>



-- 
Thanks,
Kashish Munjal

**Comment by marek2209** [comment]
![image](https://cloud.githubusercontent.com/assets/9087374/14206224/034e8cf8-f812-11e5-9cab-032dafb42200.png)
 

still the same issue

**Comment by kashishm** [comment]
You need to run gem install gauge-ruby instead of gem install gauge.

On Fri, Apr 1, 2016 at 5:30 PM, marek2209 <notifications@github.com> wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/9087374/14206224/034e8cf8-f812-11e5-9cab-032dafb42200.png>
>
> still the same issue
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/getgauge/gauge/issues/317#issuecomment-204368389>
>



-- 
Thanks,
Kashish Munjal

**Comment by marek2209** [comment]
ok works good
