### ISSUE TITLE
Could not install csharp plugin from Latest Gauge installer 0.4.0

### ISSUE THREAD

**Issue by itsmemittal** [getgauge/gauge#321]
Hi,

I have recently installed latest gauge installer 0.4.0 but when its trying to install gauge plugin then its giving error.

OS - Windows 7 64bit
Gauge Installer - Gauge 0.4.0 64 Bit

![gaugeerror](https://cloud.githubusercontent.com/assets/3033471/14342953/5bd6a934-fcbb-11e5-9874-897eeebf11d4.png)

**Comment by mahendrakariya** [comment]
@itsmemittal It looks like Gauge is not installed at the default location (`C:\Program Files\Gauge`).

If my assumption is correct, could you please ensure that there is an environment variable `GAUGE_ROOT` pointing to the folder where Gauge is installed?

**Comment by itsmemittal** [comment]
Gauge is installed at C:\Program Files\Gauge

and Enviornment variable Gauge_ROOT = C:\Program Files\Gauge

And trying to install csharp plugin

[image: Inline image 1]





On Thu, Apr 7, 2016 at 12:26 PM, Mahendra Kariya <notifications@github.com>
wrote:

> @itsmemittal <https://github.com/itsmemittal> It looks like Gauge is not
> installed at the default location (C:\Program Files\Gauge).
>
> If my assumption is correct, could you please ensure that there is an
> environment variable GAUGE_ROOT pointing to the folder where Gauge is
> installed?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/getgauge/gauge/issues/321#issuecomment-206723081>
>



-- 
*With Regards,*
*Ashu Kumar*

**Comment by itsmemittal** [comment]
Please find error attached

On Thu, Apr 7, 2016 at 12:40 PM, Ashu Mittal <itsme.mittal@gmail.com> wrote:

> Gauge is installed at C:\Program Files\Gauge
>
> and Enviornment variable Gauge_ROOT = C:\Program Files\Gauge
>
> And trying to install csharp plugin
>
> [image: Inline image 1]
>
>
>
>
>
> On Thu, Apr 7, 2016 at 12:26 PM, Mahendra Kariya <notifications@github.com
> > wrote:
>
>> @itsmemittal <https://github.com/itsmemittal> It looks like Gauge is not
>> installed at the default location (C:\Program Files\Gauge).
>>
>> If my assumption is correct, could you please ensure that there is an
>> environment variable GAUGE_ROOT pointing to the folder where Gauge is
>> installed?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/getgauge/gauge/issues/321#issuecomment-206723081>
>>
>
>
>
> --
> *With Regards,*
> *Ashu Kumar*
>
>
>


-- 
*With Regards,*
*Ashu Kumar*

**Comment by itsmemittal** [comment]
![gauge csharp](https://cloud.githubusercontent.com/assets/3033471/14344989/3fd6d850-fcc8-11e5-8c00-f105f6b64d27.png)

**Comment by mahendrakariya** [comment]
@itsmemittal Thanks for bringing this to our notice. There was an issue with the Gauge repository. We just fixed it.

Could you please try again?

**Comment by itsmemittal** [comment]
Oh

That's great ! Its working now .

Thanks

On Thu, Apr 7, 2016 at 2:45 PM, Mahendra Kariya <notifications@github.com>
wrote:

> @itsmemittal <https://github.com/itsmemittal> Thanks for bringing this to
> our notice. There was an issue with the Gauge repository. We just fixed it.
>
> Could you please try again?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/getgauge/gauge/issues/321#issuecomment-206777431>
>



-- 
*With Regards,*
*Ashu Kumar*

**Comment by mahendrakariya** [comment]
Glad to know your problem is resolved!
