### ISSUE TITLE
Problem when running Gauge by custom command task with GO

### ISSUE THREAD

**Issue by kupna** [getgauge/gauge#325]
We have migrated our Twist Tests to Gauge Tests and are now trying to run these tests with GO.

We are starting them with GO but after running the first tests with GO the java.exe process opened by gauge won't be killed and so the directory cannot be cleaned up and no new gauge test can be started.

### Expected behavior
Gauge Tests should be allowed to by started on same GO Server one after another. Processes should be killed after Custom Commands are executed.

### Actual behavior
A java.exe process started by the gauge tests keeps alive and is not killed and then the next gauge process could not be started.

### Steps to reproduce
1.
Custom Command 
/c
gauge
--tags="install|restrictedmode"
./specs

![image](https://cloud.githubusercontent.com/assets/12813719/14485652/9bfa9d26-0158-11e6-93f4-4b0c0bce8f6d.png)

2.
Custom Command 
/c
gauge
--tags="!install&!update&!inprogress&!setup&!teardown&!ei&basic"
./specs

Result:
09:02:23.647 [go] Job Started: 2016-04-13 09:02:23 MESZ

09:02:23.647 [go] Start to prepare engage-acceptance-tests-gauge/2016.1.EAP.9574/acceptance/1/acceptanceTests-basic on catwehrwaat01 [C:\GoAgent1]
09:02:47.968 Clean working directory is set to true. Unable to clean working directory for agent: C:\GoAgent1\pipelines\engage-acceptance-tests-gauge, with error: Unable to delete file: pipelines\engage-acceptance-tests-gauge\engage.acceptance.gauge\logs\twist.log
09:02:47.999 [go] Job completed engage-acceptance-tests-gauge/2016.1.EAP.9574/acceptance/1/acceptanceTests-basic on catwehrwaat01 [C:\GoAgent1]

### Gauge version

Gauge version: 0.3.2

Plugins
-------
html-report (2.0.0)
java (0.3.4)

**Comment by kupna** [comment]
Do you know when this problem can be fixed - we are really waiting for a solution here. Is there any possibility to get the java.exe process killed when the gauge tests are finished?

**Comment by apoorvam** [comment]
@kupna, Sorry about this issue. But we are already looking into this and you can expect it to be fixed in our next release. 

We'll update you on this issue once we have fixed it.

**Comment by kupna** [comment]
So you can reproduce it? 

If there is anything that I can do to help you fix it - please contact me

**Comment by apoorvam** [comment]
Thanks for it. We are trying to reproduce this at our end. 

Are you able to reproduce this issue in your local box and with a simple gauge project?

**Comment by kupna** [comment]
@apoorvam I think we found a hint, that there is a problem with the log file written by log4j. Maybe that's the reason why the java.exe process won't be killed. You don't have to look into this issue for now. I'll come back to you with further information.

**Comment by apoorvam** [comment]
@kupna We have added a fix to this in the latest gauge-java plugin. This will go as part of our next gauge-java release which should be by next week. 

If you like to try out our nightly build, you can download it from [here](https://bintray.com/gauge/gauge-java/Nightly/view) and install it as 
```
gauge --install java -f <path_to_downloaded_zipfile>
```

**Comment by kupna** [comment]
@apoorvam I tried to install the nightly build, but it won't work because version 0.3.4 is already installed.

C:\Users\kupna.INFONIQA>gauge --install java -f "C:\Users\kupna.INFONIQA\Downloads\gauge-java-0.3.4.nightly-2016-04-25-windows.x86_64.zip"
Plugin unzipped to => C:\Users\KUPNA~1.INF\AppData\Local\Temp\gauge_temp1461741703988431500

Installing Plugin java 0.3.4
Failed to install plugin. Plugin java 0.3.4 already installed at C:\Users\kupna.INFONIQA\AppData\Roaming\gauge\plugins/java/0.3.4


C:\Users\kupna.INFONIQA>gauge -v
Gauge version: 0.3.2

Plugins
-------
html-report (2.0.0)
java (0.3.4)

**Comment by kupna** [comment]
@apoorvam I just replaced the files in the directory C:\Users\kupna.INFONIQA\AppData\Roaming\gauge\plugins\java\0.3.4 
manually with the files of the nightly build

But the problem is the same. When starting the gauge tests by command line a gauge.exe, a gauge-java.exe and a java.exe process are opened. After execution of the tests the gauge.exe and the gauge-java.exe process are killed but the java.exe process keeps alive. When I want to start the next tests on this machine I can't because the java.exe process is still locking the files in the directory I want to copy my files to.

**Comment by kupna** [comment]
@apoorvam 

I tried to find out more about the java.exe process that won't be killed by gauge 

here are the infos from the task manager

C:\dev\Java\jdk1.8.0_71\jre\bin\java.exe 
-classpath C:\Users\goagent\AppData\Roaming\gauge\plugins\java\0.3.4/*;C:\Users\goagent\AppData\Roaming\gauge\plugins\java\0.3.4/libs/*;
D:\GoAgent\pipelines\engage-acceptance-tests-gauge-login\engage.acceptance.gauge\libs\*;
D:\GoAgent\pipelines\engage-acceptance-tests-gauge-login\engage.acceptance.gauge\libs\com.thoughtworks.twist.driver.sahi_5.0.0.13854-86b20931c7a610;
gauge_bin 
-Dfile.encoding=UTF-8 com.thoughtworks.gauge.GaugeRuntime

There is not problem with log4j logging. Can you help me any further with this?

**Comment by apoorvam** [comment]
@kupna We have released Gauge-Java 0.4.0! Can you try execute specs after installing Gauge-Java v0.4.0 and Gauge v0.4.0 ?

**Comment by kupna** [comment]
@apoorvam I tried today with the new gauge-java and gauge Version.

Unfortunately nothing changed - when starting gauge a gauge.exe a gauge-java.exe and a java.exe process are opened and after finishing the tests all processes except the java.exe process are killed. Every time I start new tests a new java.exe process is opened.

![image](https://cloud.githubusercontent.com/assets/12813719/15011780/f5a4e970-11f3-11e6-855a-df3c6e7b5360.png)

**Comment by kupna** [comment]
![image](https://cloud.githubusercontent.com/assets/12813719/15011820/32e75476-11f4-11e6-84a4-7e235cc73880.png)

**Comment by kupna** [comment]
Gauge version: 0.4.0

Plugins
-------
html-report (2.1.0)
java (0.4.0)

**Comment by kupna** [comment]
How can I get rid of the java.exe process when I start the Tests with GO? When I start the Tests with Intellij the Java.exe process does NOT stay alive - there it is killed.

**Comment by apoorvam** [comment]
@kupna Were you able to reproduce this issue on a simple gauge project? Also, please let us know if this is happening only on your CI or even in your local box?

Let us know if you see any error messages on console after execution/ any log messages saying `Failed to kill process`.

**Comment by kupna** [comment]
@apoorvam 
I have tried to start the tests of you example sahi project and as described here https://github.com/getgauge/gauge-example-sahi 

The java.exe process keeps alive after finishing the tests. I have tried this on my local box and on the servers.
![image](https://cloud.githubusercontent.com/assets/12813719/15139527/dd749678-1696-11e6-8f06-271bd46aafd0.png)

**Comment by kupna** [comment]
starting your example project
![image](https://cloud.githubusercontent.com/assets/12813719/15139546/f89d0994-1696-11e6-9b8f-03c2b4f3e386.png)

there are no log Messages saying failed to kill process.

**Comment by kashishm** [comment]
@kupna Thanks for the information, I could reproduce the issue with gauge example sahi project and have added a fix for this.

Can you try the [latest nightly](https://bintray.com/gauge/gauge-java/Nightly/view) and verify if the fix works for you?

**Comment by kupna** [comment]
thanks a lot - now it works :)

**Comment by apoorvam** [comment]
This fix will be available as part of next Gauge-Java release. Closing this now.
