### ISSUE TITLE
Gauge logs shouldn't be written to wd

### ISSUE THREAD

**Issue by apoorvam** [getgauge/gauge#326]
### Expected behavior
When i run, `gauge --update java` in a non-gauge project directory, it adds logs to my working directory. This pollutes my dir. 

### Actual behavior
Logs should be written to a specific location, say `~/.gauge/logs`.

### Steps to reproduce
1. `mkdir foo && cd foo`
2. `gauge --update java`
3. `ls` shows gauge logs. 

### Gauge version
```
Gauge version: 0.4.1
```

**Comment by sguptatw** [comment]
Closed
