### ISSUE TITLE
Should not allow implementation of an empty step

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#330]
### Expected behavior
Should give parse error when empty step is created and implemented.
OR
Should not implement a step with no description

### Actual behavior
Allows the creation and implementation of empty step.

### Steps to reproduce
1. Create a scenario with "" step
2. Implement the step
3. Refactoring (shift F6) this gives an error.

### Gauge version
```
Run gauge -v on your system and paste the results here.
```

**Comment by kashishm** [comment]
This issue was moved to getgauge/Intellij-Plugin#134
