### ISSUE TITLE
Getting IllegalArgumentException with valid parameters

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#332]
### Expected behavior
Should execute without error when parameters are valid

### Actual behavior
Failed Step: Refactor "met" the parameter name, bug number #44
        Error Message: java.lang.IllegalArgumentException: argument type mismatch
        Stacktrace: 
        sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        java.lang.reflect.Method.invoke(Method.java:498)
        com.thoughtworks.gauge.execution.MethodExecutor.execute(MethodExecutor.java:31)
        com.thoughtworks.gauge.execution.StepExecutionStage.executeStepMethod(StepExecutionStage.java:94)
        com.thoughtworks.gauge.execution.StepExecutionStage.executeStep(StepExecutionStage.java:77)
        com.thoughtworks.gauge.execution.StepExecutionStage.execute(StepExecutionStage.java:58)
        com.thoughtworks.gauge.execution.AbstractExecutionStage.executeNext(AbstractExecutionStage.java:24)
        com.thoughtworks.gauge.execution.HookExecutionStage.execute(HookExecutionStage.java:42)
        com.thoughtworks.gauge.execution.ExecutionPipeline.start(ExecutionPipeline.java:31)
        com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:34)
        com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:72)
        com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:37)

### Steps to reproduce
1. Create a spec
```
Users should be able to start the game1
=======================================

* Refactor "met" the parameter name, bug number #44

User should be able to access the site
--------------------------------------
tags: join
```
2. with the implementation
```

    @Step("Refactor <met> the parameter name, bug number #44")
    public void RefactorTheParameterName(String met) {
        assertEquals(met, "sfd");
    }
```
3. On execution getting the exception

### Gauge version
```
0.4.0
```

**Comment by kashishm** [comment]
I think the problem is with the `String` import. Could you please make sure that the imports are right?

**Comment by sguptatw** [comment]
Fixes the problem
