### ISSUE TITLE
Not able to run the spec even after correcting the concept name

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#334]
### Expected behavior
After changing concepts same names to different names, I should be able run the spec without any parse error.

### Actual behavior
Even after correction, getting the parse error "Duplicate concept definition found"

### Steps to reproduce
1. Create a concept SampleConcept.cpt

```
Delete project old
==============
These are context steps

* Ensure "example" project has been deleted
```

2. Create a spec
```
Should not get exception
======================================

Should not get exception
--------------------------------------
tags: something

* Delete project old
```

3. Copy paste the SampleConcept.cpt in the same folder with file name SampleConceptNew.cpt
4. Run the spec
5. Get the parse error
6. Now in SampleConceptNew.cpt change the name of the concept to "Delete project" as shown below
```
Delete project
==============
These are context steps

* Ensure "example" project has been deleted
```

7. Now run the test, still get the same parse error

### Gauge version
```
0.4.0
```

**Comment by BugDiver** [comment]
Unable to reproduce on gauge nightly 2016-05-31.
