### ISSUE TITLE
In autocomplete shows as a concept, but navigates to a step

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#336]
### Expected behavior

In autocomplete if the sentence is shown as a concept then it should navigate to the concept
### Actual behavior

In autocomplete if the sentence is shown as a concept then it should navigates to the step
### Steps to reproduce
1. Create a concept

```
Remove project
==============
* Ensure "example" project has been deleted
```
1. In a existing java implementation class add

```
    @Step("Remove project")
    public void implementation9() {

    }
```

Create a spec

```
Should get latest concept names
======================================

Should get latest concept names
--------------------------------------
tags: something

* Remove project
* 
```
1. Auto complete and select the concept
2. Now navigate by (cmd B)

It goes to the step instead of the concept
### Gauge version

```
0.4.0
```

**Comment by kashishm** [comment]
And while execution Gauge executes the `Remove project` concept.

**Comment by sriv** [comment]
Is this an IntelliJ issue? @sguptatw @kashishm
