### ISSUE TITLE
Parse error should be thrown in case of scenario heading in concept

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge#337]
### Expected behavior
If a scenario heading (markdown equivalent: H2) is present in a concept file, a parse error should be thrown.

### Actual behavior
1. While execution, Gauge is treating the text starting with scenario heading as comments.
2. While refactoring, Gauge changes the scenario heading to concept heading and hence a new concept is created.

### Steps to reproduce
* Create a new concept file. Add a new scenario to it. Here's a sample concept file.
```
# Test Concept
* Step1
* Step2

Scenario Heading
----------------
* Scenario step 1
* Scenario step 2
```
* Use this concept in some spec.
* Execute `gauge specs`. It should throw parse error.

**Comment by sguptatw** [comment]
Please check concept_should_not_contain_scenario_heading.spec and close

**Comment by BugDiver** [comment]
Fixed the FT(concept_should_not_contain_scenario_heading.spec), the fix should be available in the nightly > 20/04/2016
