### ISSUE TITLE
Table parameter one or more hyphen get removed when spec formatted

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#339]
### Expected behavior

spec format should not remove parameter value from table when spec is formatted
### Actual behavior

Table parameter one or more hyphen get removed when spec formatted
### Steps to reproduce
1. Create a spec

```
Should not remove hyphen form table
===================================

     |something|
     |---------|
     |a        |
     |b        |
     |-        |

Should not remove - from table param value
-------------------------------
tags: something


```
1. Do a spec format
2. Now you will see that the table parameter value no longer contains the hyphen.
### Gauge version

```
0.4.0
```

**Comment by sriv** [comment]
Does not exist in 0.6.3. Closing.
