### ISSUE TITLE
Table parameter value < should be allowed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#340]
### Expected behavior
Table parameter value < should be allowed

### Actual behavior
Gives a parse error

### Steps to reproduce
1. Create a spec
```
Should not remove hyphen form table
===================================

     |something|
     |---------|
     |a        |
     |b        |
     |<        |
     |/**/|
     |```|
     |>|
     |!|
     |@|
```
2. This shows a parse error

### Gauge version
```
0.4.0
```

**Comment by kashishm** [comment]
This issue was moved to getgauge/Intellij-Plugin#138
