### ISSUE TITLE
Does not format the spec as expected

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#342]
### Expected behavior

Format of the spec should format the table and its contents
### Actual behavior

Does not format the spec as expected
### Steps to reproduce

1.

```
|spec|
|-----|
    |-|
    |||

```
1. The format still remains the same
### Gauge version

```
0.4.0
```

**Comment by sguptatw** [comment]
Any format errors is not shown in the IDE and format does not work

**Comment by sriv** [comment]
Works on gauge 0.6.3. Closing.
