### ISSUE TITLE
Does not allow \ as a table parameter value

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#343]
### Expected behavior
Should allow \ as a parameter value. Atleast it should be allowed with an escape character.

### Actual behavior
Getting parse error

### Steps to reproduce
1. Create a spec with the following table
```
    |HEADER|
    |\|
    |value|
```
2. You will see the parse error

### Gauge version
```
0.4.0
```

**Comment by kashishm** [comment]
This issue was moved to getgauge/Intellij-Plugin#136
