### ISSUE TITLE
Getting a parse error for a valid spec

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#346]
### Expected behavior
Should not get a parse error in IntelliJ for a valid spec

### Actual behavior
Gives a parser error in IntelliJ for a valid spec

### Steps to reproduce
1. Create a spec with the following table
```
|example|
|--------|
|+|
|||
|\\|
```
2. Gives a parse error but execution works fine.

### Gauge version
```
0.4.0
```

**Comment by kashishm** [comment]
This issue was moved to getgauge/Intellij-Plugin#135
