### ISSUE TITLE
Inner concepts are listed as step

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#348]
### Expected behavior

In auto-complete a concept should be listed as a concept
### Actual behavior

In auto-complete an inner concept is being listed as a step
### Steps to reproduce
1. Create inner concept

```
#innerCpt
* something
```

with implementation

```
    @Step("something")
    public void implementation1() {
    }
```
1. Create outer concept

```
#outerCpt
* innerCpt
```
1. In any other spec 

```
Specification Heading
=====================
Vowel counts in single word
---------------------------
* 
```

In auto-complete inner concept is being listed as a step
### Gauge version

```
0.4.1.nightly-2016-04-19
```

**Comment by sriv** [comment]
Should be an intellij-issue. @sguptatw please confirm that you see this behaviour in Intellij.

**Comment by sguptatw** [comment]
I was told this is a Gauge issue, 'cause the list of steps comes from Gauge.

**Comment by sriv** [comment]
ok - I am going to attempt a test harness to verify the APIs, to make sure this is the case. Quite likely that this is.

**Comment by sriv** [comment]
@sguptatw - could you test this with [spider](https://github.com/kashishm/spider) in place and see what is the request/response?

**Comment by sguptatw** [comment]
This is working as expected in
```
Gauge version: 0.9.2.nightly-2017-08-15

Plugins
-------
csharp (0.10.1)
html-report (4.0.2.nightly-2017-08-07)
java (0.6.5.nightly-2017-08-14)
ruby (0.4.1)
spectacle (0.1.2)
xml-report (0.2.0)
```
