### ISSUE TITLE
Should show all parse errors together instead of one by one

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#349]
### Expected behavior
If there are multiple errors during execution, then it should all be displayed 

### Actual behavior
Only one error gets displayed at a time during execution, as and when I correct it, the next error shows up. This will be an issue especially during migrations.

### Steps to reproduce
1. Create a sub folder under specs with 2 concepts
2. Copy paste the sub folder under specs.
3. Create a dummy valid spec 
4. Execute the specs
5. One gets the errors one at a time

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-04-19

Plugins
-------
html-report (2.1.0)
java (0.3.4.nightly-2016-04-19)
```

**Comment by sguptatw** [comment]
The following scenario failed
* Execute a single file. The parse errors are not consolidated.

Steps to reproduce
1. Create a spec file
```
One
=====================

Two
=====================
Created by sswaroop on 5/3/16

This is an executable specification file which follows markdown syntax.
Every heading in this file denotes a scenario. Every bulleted point denotes a step.

Scenario Heading
----------------

* dynamic <param>
* dynamic <param>

File missing
----------------

* dynamic <file:param>
```

2. Create implementation
```
    @Step("dynamic <param>")
    public void implementation2(Object arg0) {

    }
```

**Comment by sguptatw** [comment]
Scenario 2 which is currently failing

* An unresolved file dynamic parameter is not getting listed until executed

**Steps to reproduce**
1. Create a spec file
```
One
=====================

Two
=====================
Scenario Heading
----------------
File missing
----------------
* dynamic <file:param>
```
2. Give the implementation
```
    @Step("dynamic <param>")
    public void implementation2(Object arg0) {
    }
```
3. Execute the spec
4. It displays error
```
/usr/local/bin/gauge --simple-console /Users/sswaroop/work/issue_samples/java/specs/multipleSpecHeading.spec
[ParseError] /Users/sswaroop/work/issue_samples/java/specs/multipleSpecHeading.spec : line no: 4, Parse error: Multiple spec headings found in same file

Process finished with exit code 1
```
5. It does not display the file special parameter

**Comment by sguptatw** [comment]
[multipleParseErrors.zip](https://github.com/getgauge/gauge/files/246665/multipleParseErrors.zip)

**Comment by kashishm** [comment]
The above-mentioned scenarios are working now(showing multiple parse errors as expected).
The fix will be available in nightly >= 26-05-2016

**Comment by sguptatw** [comment]
Failing for other parse error

[] #428

**Comment by BugDiver** [comment]
Fix should be available in nightly >= 06-06-2016

**Comment by sguptatw** [comment]
It is failing for concept with static param

```
# Concept with "static" param
* pass <static> param
* dynamic <param>
```

**Comment by sguptatw** [comment]
Having multiple unresolved dynamic issues does not list all.

```
# Concept with param
* pass <static> param
* dynamic <param>
```

**Comment by mahendrakariya** [comment]
> It is failing for concept with static param

It's supposed to fail. Static params are not allowed in concept headings.

**Comment by mahendrakariya** [comment]
> Having multiple unresolved dynamic issues does not list all.

This issue has been fixed. Should be available in nightly >= 2016-06-08.

**Comment by sguptatw** [comment]
@mahendrakariya : With `It is failing for concept with static param` what I meant was this test case is failing. It was throwing an error, now which is fixed.
