### ISSUE TITLE
Statistics of passed, failed and skipped do not add up to the total

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#350]
### Expected behavior
Statistics of passed, failed and skipped should add up to the total

### Actual behavior
Statistics of passed, failed and skipped do not add up to the total

### Steps to reproduce
1. Create a spec file
```
Specification Heading
=====================

Vowel counts in multiple word
-----------------------------

This is the second scenario in this specification

Here's a step that takes a table

* somethingelse

```
2. Do not implement any steps

3. Execute the spec and see the result
Though there are no scenarios executed it says 1 spec passed
```
Successfully generated html-report to => /Users/sswaroop/work/issue_samples/java/reports/html-report
Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	0 executed	0 passed	0 failed	1 skipped
```

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-04-19

Plugins
-------
html-report (2.1.0)
java (0.3.4.nightly-2016-04-19)
```

**Comment by mahendrakariya** [comment]
Could you also share how the statistics look like currently?

**Comment by sguptatw** [comment]
updated the issue with the statistics.

**Comment by BugDiver** [comment]
Added test( Skip spec if all scenarios are skipped) in spec_execution_with_validation_error.
It's passing.
