### ISSUE TITLE
Should be able to rename the dynamic parameter from the table

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#351]
### Expected behavior

Should be able to rename the dynamic parameter from the table
### Actual behavior

Does not allow the dynamic parameter rename
### Steps to reproduce

1.

```
Should not remove hyphen form table
===================================

     |something         |
     |------------------|
     |a     c           |
     |b                 |
     |------------------|

Should not remove - from table param value
------------------------------------------
tags: something

* use the parameter <something>
```
1. Try renaming the table dynamic parameter something
### Gauge version

```
Gauge version: 0.4.1.nightly-2016-04-19

Plugins
-------
html-report (2.1.0)
java (0.3.4.nightly-2016-04-19)
```

**Comment by kashishm** [comment]
[FT](https://github.com/getgauge/gauge-tests/blob/cb0f318e5994cf175fe0474b944e7ab7485095e2/specs/refactoring/should_allow_to_refactor_parameter_in_tear_down.spec) is passing.

**Comment by sriv** [comment]
Closing as stale. Please comment/reopen if this is still valid.
