### ISSUE TITLE
Unimplemented steps are shown as implemented

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#352]
### Expected behavior
Unimplemented steps should show as unimplemented

### Actual behavior
Spec with only context steps show the steps as implemented

### Steps to reproduce
1.
```
Something
=========

* something else
* This is showing as implemented

```
2. The steps are shown as unimplemented

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-04-19

Plugins
-------
html-report (2.1.0)
java (0.3.4.nightly-2016-04-19)
```

**Comment by apoorvam** [comment]
This issue was moved to getgauge/Intellij-Plugin#155
