### ISSUE TITLE
Refactoring of Tear down steps - unable to add a parameter

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#353]
### Expected behavior
Should be able to pass parameter to a tear down step

### Actual behavior
Unable to refactor and add a parameter to a tear down step

### Steps to reproduce
1. Create a spec
```
Something
=========

sfsdfsdf
--------

* This is showing as implemented
___
* Tear down step 1
```
2. Implementation
```
    @Step("This is showing as implemented")
    public void implementation1() {
    }

    @Step("Tear down step 1")
    public void implementation5() {
    }

```
3. Now Refactor the "Tear down step 1" to "Tear down \<b\> step 1"
4. The spec shows some errors
5. Refer should_allow_to_refactor_parameter_in_tear_down.spec for more details

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-04-19

Plugins
-------
html-report (2.1.0)
java (0.3.4.nightly-2016-04-19)
```

**Comment by kashishm** [comment]
Fixed via https://github.com/getgauge/gauge/commit/c91634aa0fa51fdc0a592ada6a128bc96b475fec. [FT](https://github.com/getgauge/gauge-tests/blob/cb0f318e5994cf175fe0474b944e7ab7485095e2/specs/refactoring/should_allow_to_refactor_parameter_in_tear_down.spec) is passing.
