### ISSUE TITLE
Lack of consistency in parameter generation

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#354]
### Expected behavior

The type of parameter generated should be consistent
### Actual behavior

The type of parameter generated should be consistent
### Steps to reproduce
1. Create a spec file 

```
Something
=========

sfsdfsdf
--------

* This is showing as implemente"b"d

```
1. use create a step implementation.
2. The generated parameter type is Object
3. Now use shift f6 and refactor the step to This is "showing" as implemente"b"d
4. The newly generated parameter is of type String
### Gauge version

```
Gauge version: 0.4.1.nightly-2016-04-19

Plugins
-------
html-report (2.1.0)
java (0.3.4.nightly-2016-04-19)
```

**Comment by sriv** [comment]
Not a Gauge issue. Which IDE is this happening?

**Comment by sguptatw** [comment]
This happens on IntelliJ

**Comment by sguptatw** [comment]
This issue was moved to getgauge/Intellij-Plugin#227
