### ISSUE TITLE
Refactoring fails with special parameter

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#355]
### Expected behavior

Refactoring should not give an error when parse is successful and no compilation errors
### Actual behavior

Refactoring gives an error
### Steps to reproduce
1. Create a spec

```
Something
=========
wwwwwwww
--------
* Verify email text is <table:/email.csv>

```
1. With default implementation
2. Now refactor 'Verify email text is table:/email.csv' to 'Verify "email" text is table:/email.csv'
3. See the error
### Gauge version

```
Gauge version: 0.4.1.nightly-2016-04-19

Plugins
-------
html-report (2.1.0)
java (0.3.4.nightly-2016-04-19)
```

**Comment by sriv** [comment]
Gauge Version - 0.6.3

I get an error with the above example because `/email.csv` does not exist. Instead if I use `specs/email.csv`.

And I run the below command:

```
gauge --refactor "Verify email text is <table:specs/email.csv>" 'Verify "email" text is <table:specs/email.csv>'
```

 I can see that the step text is changed to 

```
* Verify "email" text is ""
```

and the implementation is:

```
    @Step("Verify <email> text is")
    public void implementation1(String argEmail, Object arg0) {
    }
```

**Comment by sriv** [comment]
Issue replicable. The new step text has `table` which is not generated in the implementation.

### Gauge Version

```
Gauge version: 0.9.1

Plugins
-------
csharp (0.10.1)
html-report (4.0.1)
java (0.6.5)
js (2.0.0)
ruby (0.4.1)
xml-report (0.2.0)
```

**Comment by zabil** [comment]
Command line refactoring will be deprecated in favour of IDE refactoring.
