### ISSUE TITLE
Refactor execution to broadcast various states in the execution lifecycle

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#356]
An increasing number of features require to tap into the execution lifecycle, ex #105.

The execution should broadcast the states in the execution lifecycle, so that observers can be attached to probe.

**Comment by sguptatw** [comment]
On executing the tests in parallel `https://github.com/getgauge/gauge-test-apps`. The gauge did not exit to give the result.

**Comment by BugDiver** [comment]
@sguptatw Gauge tests in `https://github.com/getgauge/gauge-test-apps` works fine in parallel with gauge version >= 07-06-2016 and gauge-java nightly >= 30-05-2016
