### ISSUE TITLE
Refactor - Adding a special parameter in tear down step is replacing with the content of the file

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#358]
### Expected behavior

Adding a special parameter in tear down step should replace with special parameter
### Actual behavior

Adding a special parameter in tear down step is replacing with the content of the file
### Steps to reproduce

*

```
Something
=========

wwwwwwww
--------
* Verify "email" "blah"

___ somewhere
* Tear down step
step 1
```
- With the implementation

```
    @Step("Verify <email> <blah>")
    public void implementation7(String argEmail, String argBlah) {
    }

    @Step("Tear down step")
    public void implementation5() {
    }
```
- Add a text file email.txt

```
Id,Name
1,The Way to Go On
2,Ivo Jay Balbaert
```
- Refactor the step 'Tear down step' to 'Tear down step file:specs/email.txt'
### Gauge version

```
Gauge version: 0.4.1.nightly-2016-04-19

Plugins
-------
html-report (2.1.0)
java (0.3.4.nightly-2016-04-19)
```

**Comment by sriv** [comment]
> Refactor the step 'Tear down step' to 'Tear down step file:specs/email.txt'

This works on Gauge 0.6.3, since it does not introduce a new parameter. However this

```
gauge --refactor "Tear down step" "Tear down step <file:specs/email.csv>"
```

has this output:

```
Note: src/test/java/StepImplementation.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Cannot perform refactoring: Refactoring failed: null

0 specifications changed.

0 concepts changed.

0 files in code changed.
```

**Comment by zabil** [comment]
Command line refactoring will be deprecated in favour of IDE refactoring.
