### ISSUE TITLE
Refactoring fails for step containing \t \n

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge#359]
### Steps to reproduce
1. Create a step `step with \t\n here`
2. Create implementation for `step with \t\n here`
3. Refactor the `step with \t\n here` to `step \t\n here`
4. It doesn't refactor the step.
### Gauge version

```
0.4.1
```

**Comment by sriv** [comment]
Fails in Gauge 0.6.3

```
gauge --refactor "step with \t\n here" "step \t\n here"
```

yields

```
Cannot perform refactoring: Refactoring failed: null

0 specifications changed.

0 concepts changed.

0 files in code changed.
```

**Comment by sguptatw** [comment]
Working as expected
```
Gauge version: 1.0.1.nightly-2018-07-31
Commit Hash: 4ae7c9a
```
