### ISSUE TITLE
A parse error in a different file does not allow any refactoring in the current file

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#361]
### Expected behavior

If the current file has no parse errors it should allow refactoring
### Actual behavior

A parse error in a different file does not allow any refactoring in the current file
### Steps to reproduce
1. Create a spec file

```
Something
=========

wwwwwwww
--------
* Say hi to <table:specs/test/email.txt>

```
1. Create another spec file 

```
Something
=========

* All here

wwwwwwww
--------
* All here
```
1. Give implementation

```
    @Step("Say hi to <table:specs/test/aNewSpec.spec>")
    public void implementation4(Object arg0) {
        System.out.println(arg0);
    }

    @Step("All here")
    public void implementation5() {
    }
```
1. Now refactor "All here" to "all here"
   it does not allow it.
### Gauge version

```
Gauge version: 0.4.1.nightly-2016-04-19

Plugins
-------
html-report (2.1.0)
java (0.3.4.nightly-2016-04-19)
```

**Comment by apoorvam** [comment]
Refactoring will make changes to spec files. If there is a parse error and we change the spec file during refactoring, it can result in unexpected changes. This is expected behavior as of now. We can consider this if there are valid use-cases. Closing this for now.
