### ISSUE TITLE
Pass on executed table row info to reports

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/gauge#363]
Reports do not have the information on which table rows are executed, in case `--table-rows` flag is used by the user. It only has information about the rows that have failed.

As a result, there are a couple of bugs on html-report.
   - [x] https://github.com/getgauge/html-report/issues/50
   - [x] https://github.com/getgauge/html-report/issues/64 

This will require a change in the [spec.proto](https://github.com/getgauge/gauge-proto/blob/master/spec.proto) file. The [ProtoSpecResult](https://github.com/getgauge/gauge-proto/blob/master/spec.proto#L269) has information only about the failed data table rows and not the ones which have been skipped.

**Comment by apoorvam** [comment]
The message `ProtoTableDrivenScenario` in `spec.proto` now has a field `tableRowIndex` which indicates the table row number against which the scenario in the message is executed. This is implemented [here](https://github.com/getgauge/gauge-proto/blob/master/spec.proto#L121).
