### ISSUE TITLE
Concept should allow data table

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#365]
### Expected behavior

Concept should allow data table. It currently allows table as a special parameter 
### Actual behavior

Data Table is not allowed 
### Steps to reproduce
1. Create a concept

```
# Generate user report

|user status|
----
|active|
|inactive|
|disabled|

* Print the active period
```
1. This is not allowed
### Gauge version

```
Gauge version: 0.4.1.nightly-2016-04-19

Plugins
-------
html-report (2.1.1.nightly-2016-04-27)
java (0.3.4.nightly-2016-04-19)
xml-report (0.1.2)
```

**Comment by apoorvam** [comment]
Conceptually, a `concept` is just a collection of steps. The idea of data table comes only against a spec/scenario which are actual test cases. Whereas, a concept is used just like a step in scenario. Do you still think this enhancement is useful?

**Comment by bddTeam** [comment]
I was faced with this problem too
