### ISSUE TITLE
Custom messages are not passed to reports in nightly

### ISSUE THREAD

**Issue by kaustavdm** [getgauge/gauge#367]
### Expected behavior
When test implementations send custom messages, Gauge is supposed to send them to reports. For example, the following snippets should print custom messages in reports:

in Java:

```java
import com.thoughtworks.gauge.Gauge;

@Step("My step")
public void mystepimpl() {
    Gauge.writeMessage("I am a message");
}
```

in JavaScript:

```js
gauge.step("My step", function () {
    gauge.message("I am a message");
});
```

and, they show up as:

<img width="474" alt="Gauge custom message" src="https://cloud.githubusercontent.com/assets/364832/14909525/3f1ee9e8-0e02-11e6-8e07-0dc51b52abd6.png">

### Actual behavior
The expected behaviour breaks in current nightly. I could not get custom messages working for either Java or JavaScript using the snippets above.

Downgrading to gauge v0.4.0 resumes expected behaviour.

### Steps to reproduce
1. Use the snippets mentioned above
2. Use Gauge nightly or compile from source.
3. Watch the non-existence of custom messages.

**Comment by apoorvam** [comment]
Compiled Gauge from source and I could see Gauge custom messages on html-report. 

Gauge version: 0.4.1

Plugins
-------
html-report (2.1.1)
java (0.4.0)
