### ISSUE TITLE
Wrong nightly version displayed on gauge -v

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#368]
When multiple nightly versions of a plugin are installed, Gauge shows an older version.

**Steps to Reproduce:**
1. Install html-report v `2.1.1.nightly-2016-05-02`
2. Install html-report v `2.1.1.nightly-2016-04-27`
3. Run `gauge -v`

**Expected Behavior:**

The `2.1.1.nightly-2016-05-02` version of html-report should be shown.

**Actual Behavior:**

The `2.1.1.nightly-2016-04-27` version of html-report should be shown.

**Gauge Version:**
```
Gauge version: 0.4.1.nightly-2016-04-24

Plugins
-------
html-report (2.1.1.nightly-2016-04-27)
java (0.3.4.nightly-2016-04-19)
xml-report (0.1.2)
```

**Comment by mahendrakariya** [comment]
The changes should be available in nightly > 2016-05-12
