### ISSUE TITLE
Should be able to format concept

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#369]
### Expected behavior

Should be able to format a concept
### Actual behavior

It allows only a spec format
### Gauge version

```
Gauge version: 0.4.1

Plugins
-------
html-report (2.1.1.nightly-2016-05-02)
java (0.3.4.nightly-2016-04-19)
xml-report (0.1.2)
```

**Comment by nehashri** [comment]
Duplicate of https://github.com/getgauge/gauge/issues/369
