### ISSUE TITLE
Remove old versions from bintray

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#373]
Bintray has limits on OSS artifacts, and gauge nightly is exhausting it. 

Delete nightly versions older than 7 days from current date.

**Comment by sguptatw** [comment]
The other nightlies are also eating up a lot of space.
The following still have many nightly artifacts which are older than 7 days from current date and can be deleted.

https://bintray.com/gauge/gauge-csharp/Nightly/view
https://bintray.com/gauge/gauge-deb/gauge/view
https://bintray.com/gauge/gauge-java/Nightly/view
https://bintray.com/gauge/Gauge-Java-Intellij/Nightly/view
https://bintray.com/gauge/gauge-rpm/gauge-nightly/view
https://bintray.com/gauge/gauge-ruby/Nightly/view
https://bintray.com/gauge/Gauge.VisualStudio/Nightly/view
https://bintray.com/gauge/html-report/Nightly/view
https://bintray.com/gauge/xml-report/Nightly/view
