### ISSUE TITLE
Gauge eclipse nightly is available along side core

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#374]
This is the placeholder for the Gauge nightly
https://bintray.com/gauge/Gauge

Gauge eclipse nightly should be moved or deleted from here.

**Comment by apoorvam** [comment]
Gauge eclipse nightly/release is now moved to [https://bintray.com/gauge/Gauge-Eclipse](https://bintray.com/gauge/Gauge-Eclipse).
