### ISSUE TITLE
The bintray space of gauge-maven-plugin is unused

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#375]
This is a space allocated for gauge-maven-plugin but has nothing under it.
https://bintray.com/gauge/gauge-maven-plugin

**Comment by kaustavdm** [comment]
@sguptatw I am not sure what is the action item on this.

**Comment by sguptatw** [comment]
@kaustavdm :either this should have the corresponding artifacts, or the space should be removed from bintray

**Comment by kaustavdm** [comment]
If we are not using it, it can be killed, I suppose. LMK if I should do it.

**Comment by kaustavdm** [comment]
Deleted the bintray repository. We were not using it. If needed in future, it can be created again.
