### ISSUE TITLE
Scenario should not be allowed in teardown

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#376]
**Expected Behavior**
Teardown is a collection of steps and should not allow a scenario

**Actual Behavior**
Allows definition of a scenario in tear down and considers it as a scenario and not the tear down steps

**Steps to reproduce**
1. Create a spec

```
one
===
Scenario Heading
----------------
* def
In between
----------
* abc
_____

Scenario Heading1
-----------------
* def
```
1. Create implementation

```
@Step("abc")
    public void abc() {
     }

@Step("def")
    public void def() {
    }
```
1. Run the specs
2. See the report there are no teardown steps but only scenarios.

**Version**

```
Gauge version: 0.4.1

Plugins
-------
html-report (2.1.1)
java (0.4.0)
python (0.1.2)
ruby (0.1.2)
```

**Comment by apoorvam** [comment]
If 3 or more underscores are present in between scenarios, its treated as comment. Restricting scenario to be not defined after a `____` will make horizontal lines (equivalent to 3 or more underscores) to be not used in markdown file.

**Comment by sguptatw** [comment]
In that case the horizontal lines should be visible in the report.
