### ISSUE TITLE
Confusion between step and scenario

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#379]
**Expected Behavior**
There should be a clear distinction between a scenario name and a step.

**Actual Behavior**
Something that looks like a scenario gets executed as a step

**Steps to reproduce**
1. Create a spec
```
sf
==
Scenario Heading
----------------
* abc

--------
* def
```
2. Give implementation
```
    @Step("abc")
    public void implementation4() {
    }

    @Step("def")
    public void implementation4() {
    }
```

3. Goto console and give
```
gauge --format specs
```

3. This removes the newlines and now the spec looks like 
```
sf
==
Scenario Heading
----------------
* abc
-------
* def
```

4. On execution `abc` is getting executed as a step.
However when one tries to goto the definition of it. It says 'Cannot find declaration to goto'

**Version**
```
Gauge version: 0.4.1.nightly-2016-05-06

Plugins
-------
html-report (2.1.1.nightly-2016-05-02)
java (0.4.0)
xml-report (0.1.2)
```

**Comment by kashishm** [comment]
Now, the formatting is working as expected and it does not remove those new lines. Fix is available in nightly >= 26/5/2016
But the go to def issue still exists in IntelliJ plugin https://github.com/getgauge/Intellij-Plugin/issues/153
