### ISSUE TITLE
Cyclic dependancy of concepts throws an exception

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#380]
**Expected Behavior**
Should get a parse error without an exception

**Actual Behavior**
Get an exception along with a parse error

**Steps to reproduce**
1. Create a concept
```
# Concept Heading
* step1
* step2
```

2. With implementation
```
    @Step("step1")
    public void implementation7() {
    }
```

3. Create a concept
```
# step2
* step1
* step2
```

4. Create a spec
```
one
===

In between
----------
* Concept Heading

```
5. Run the spec
and one would get the following exception.

[ParseError] /Users/sswaroop/work/issue_samples/java/specs/concepts/two.cpt:6: Cyclic dependancy found. Step is calling concept again. => 'step2'
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x267ec8]

goroutine 25 [running]:
panic(0x64e4a0, 0x820b8e090)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/getgauge/gauge/gauge.(*Specification).processConceptStep(0x820cd2600, 0x820cde7e0, 0x0)
	/tmp/src/github.com/getgauge/gauge/gauge/specification.go:81 +0x48
github.com/getgauge/gauge/gauge.(*Specification).ProcessConceptStepsFrom(0x820cd2600, 0x0)
	/tmp/src/github.com/getgauge/gauge/gauge/specification.go:72 +0x154
github.com/getgauge/gauge/parser.(*SpecParser).CreateSpecification(0x820dc3200, 0x820dc3240, 0x8, 0x8, 0x0, 0x8, 0x0)
	/tmp/src/github.com/getgauge/gauge/parser/specparser.go:248 +0x717
github.com/getgauge/gauge/parser.(*SpecParser).Parse(0x820dc3200, 0x820cca980, 0x71, 0x0, 0x0, 0x0)
	/tmp/src/github.com/getgauge/gauge/parser/specparser.go:72 +0xb6
github.com/getgauge/gauge/parser.parseSpec(0x7fff5fbff036, 0x46, 0x0, 0x820cd6f00, 0x820cd6ea0)
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:54 +0x2ea
created by github.com/getgauge/gauge/parser.ParseSpecFiles
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:35 +0x19b

Process finished with exit code 2

**Comment by kashishm** [comment]
Available in nightly > 26/05/2016
