### ISSUE TITLE
Concepts not resolved when a spec is executed

### ISSUE THREAD

**Issue by apoorvam** [getgauge/gauge#382]
### Expected behavior
If a spec and concept are in `specs` dir, executing specification from specs dir should resolve concept.

### Actual behavior
Concept is not resolved

### Steps to reproduce
1. Create a spec hello.spec and a concept in specs dir. This concept should be used in spec.
2. `cd specs`
3. `gauge hello.spec`

### Gauge version
```
Gauge version: 0.4.1

Plugins
-------
html-report (2.1.0)
java (0.4.0)
```

**Comment by kashishm** [comment]
In this fix, Gauge always looks for concepts in the whole project, folders starting with dot(`.`) are excluded and a user can add folders to the excluded folders list by adding a new property i.e `gauge_exclude_dirs` and pass paths to folders separated by comma(`,`).

For Example: `gauge_exclude_dirs = src/test, bin`

**Comment by kashishm** [comment]
The fix will be available in nightly > 13-05-2016
