### ISSUE TITLE
Should have a clean way to uninstall gauge

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#383]
**Expected Behavior**
In mac, I should be able to uninstall gauge which takes care of uninstall the core and the plugins installed on the machine. 

**Actual Behavior**
Since there is no standard approach to uninstall something, there are files left behind.

Currently, to uninstall Gauge completely, we have to run

```
rm -rf /usr/local/share/gauge
rm -rf /usr/local/bin/gauge*
rm -rf ~/.gauge
```

**Version**

```
Gauge version: 0.4.1.nightly-2016-05-09

Plugins
-------
html-report (2.1.0)
java (0.4.0.nightly-2016-05-09)
xml-report (0.1.2.nightly-2016-05-09)
```

**Comment by sriv** [comment]
Need to do this for all installation channels:

- Homebrew
- pkg installer
- download & run `./install.sh`

**Comment by mahendrakariya** [comment]
Homebrew is the cleanest of all as of now.

`brew install gauge` installs binaries in `/usr/local/bin` and the shared files in `/usr/local/share/gauge`.

`brew uninstall gauge` will remove both these things.

Since plugins are not installed via brew, uninstalling them via brew is also not feasible.

**Comment by kaustavdm** [comment]
Deb and RPM packages will also handle the same way as brew, but they do not remove the plugins directory.

Does `brew uninstall` remove the plugins installation directory? I guess we leave it untouched.

**Comment by apoorvam** [comment]
Here is [Gauge Uninstallation docs](http://getgauge.io/documentation/user/current/installations/uninstallation.html).

**Comment by sguptatw** [comment]
The Program Files -> Gauge created by 32 bit windows installer does not uninstaller as mentioned in docs
