### ISSUE TITLE
Able to install xml-report using gauge --install java

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#384]
**Expected Behavior**
gauge --install java should install java plugin only

**Actual Behavior**
installs other plugins as well

**Steps to reproduce**
```
gauge --install java -f /somepath/xml-report-0.1.2.nightly-2016-05-09-darwin.x86_64.zip
```
successfully installs xml-report

```
gauge --install java -f /Users/sswaroop/Downloads/html-report-2.1.1.nightly-2016-05-09-darwin.x86_64.zip
```
successfully installs html-report

**Comment by BugDiver** [comment]
Fixed should be available in nightly > 27-5-2016

**Comment by sguptatw** [comment]
The reason of failure is not clear

Reason: File /var/folders/_r/rxkwk7zn1dnfky2b22yx4yfr0000gn/T/gauge_temp1464667204163944408/plugin.json doesn't exist.

The reason may be
Incompatible plugin and installer...

**Comment by BugDiver** [comment]
Available in nightly >= 03/06/2016
