### ISSUE TITLE
Getting invalid validation errors when executing --validate command from a sub-folder

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#386]
### Expected behavior
Should get relevant validation error irrespective of the current directory the user is in.

### Actual behavior
Getting invalid validation errors when executing command from a sub-folder

### Steps to reproduce
1. Create a concept file
```
# 1<werwer>
* 2 "1-2" two
* 3 "1-3"
* 4"1-4"
* self <werwer>

# 2 <werwer> two
* self <werwer>
* 3 "werwer"

# 3 <werwer>
* self <werwer>
* 4<werwer>

# 4<werwer>
* self <werwer>
* self "4"
```
2. Create a spec file
```
one
===

     |something|
     |---------|
     |2        |
In between
----------
* 1<table:specs/one.csv>
In between1
-----------
* 2 <something> two
In between2
-----------
* 3 "3"
In between3
-----------
* self "3"
* 4"4"

* self "e"
```
3. Create an implementation
```
    private int test = -1;

    @Step("self <abcdef>")
    public void implementation6(String abcdef) {
        System.out.println(abcdef + "inside self");
        test++;

        System.out.println("variable:" + test);

        Assert.assertEquals(true, false);
    }

```
4. cd specs
5. gauge --validate .
This gives invalid validation errors.
```
[ValidationError] /Users/sswaroop/work/issue_samples/java/specs/mergeScenarioFormat.spec:9: Step implementation not found => '1<table:specs/one.csv>'
[ValidationError] /Users/sswaroop/work/issue_samples/java/specs/mergeScenarioFormat.spec:12: Step implementation not found => '2 <something> two'
[ValidationError] /Users/sswaroop/work/issue_samples/java/specs/mergeScenarioFormat.spec:15: Step implementation not found => '3 "3"'
[ValidationError] /Users/sswaroop/work/issue_samples/java/specs/mergeScenarioFormat.spec:19: Step implementation not found => '4"4"'
[ValidationError] /Users/sswaroop/work/issue_samples/java/specs/mergeScenarioFormatc.spec:9: Step implementation not found => '1<table:specs/one.csv>'
[ValidationError] /Users/sswaroop/work/issue_samples/java/specs/mergeScenarioFormatc.spec:12: Step implementation not found => '2 <something> two'
[ValidationError] /Users/sswaroop/work/issue_samples/java/specs/mergeScenarioFormatc.spec:15: Step implementation not found => '3 <file:specs/three.txt>'
[ValidationError] /Users/sswaroop/work/issue_samples/java/specs/mergeScenarioFormatc.spec:18: Step implementation not found => '4<file:specs/four.txt>'
```

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-05-09

Plugins
-------
java (0.4.0.nightly-2016-05-06)
ruby (0.2.0.nightly-2016-05-09)
xml-report (0.1.2.nightly-2016-05-09)
```

**Comment by BugDiver** [comment]
@sguptatw It'd be great if you could add how you'd want the validation messages to look like.

**Comment by mahendrakariya** [comment]
Had a quick chat with @sguptatw. Here's some more details.
  * All the steps are actually implemented.
  * When running `--validate` from project root, everything is working fine.
  * But when `--validate` is run from some subfolder, say `specs`, validation errors are thrown.

**Comment by mahendrakariya** [comment]
@sguptatw Can you please confirm this issue once again? I am unable to reproduce it.

A few things to keep in mind.
  * When running `gauge --validate`, Gauge defaults the directory name to `specs`. And the assumption is that the specs directory will be present in the folder from where this command is invoked.
  * So, if you are running from inside a subfolder, say `subfolder`, please make sure to give the relative path to specs directory. So the command that you should run from within level one subfolder should be `gauge --validate ../specs`.

**Comment by sguptatw** [comment]
@mahendrakariya : This issue might have been fixed with the other issue of subfolder spec execution, closing it.
