### ISSUE TITLE
wrong table rows getting executed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#387]
### Expected behavior

When table rows parameter is passed as a parameter the mentioned rows should be executed
### Actual behavior

The first row is getting executed
### Steps to reproduce
1. Create a spec

```
one
===

     |something|
     |---------|
     |0        |
     |1        |
     |2        |

In between1
-----------
* 2 <something> two
```
1. Create a concept

```
#2 <werwer> two
* self <werwer>
```
1. Give implementation

```
    @Step("self <abcdef>")
    public void implementation6(String abcdef) {
        System.out.println(abcdef + "inside self");
        Assert.assertEquals(true, false);
    }

```
1. Goto the command line and execute

```
gauge --table-rows=2-100 specs
```

One will see that only the first row is executed. This also occurs when the tabl-rows is invalid.
### Gauge version

```
Gauge version: 0.4.1.nightly-2016-05-09

Plugins
-------
html-report (2.1.0)
java (0.4.0.nightly-2016-05-06)
ruby (0.2.0.nightly-2016-05-09)
xml-report (0.1.2.nightly-2016-05-09)
```

**Comment by sriv** [comment]
In Gauge 0.6.3, `gauge --table-rows=2-100 specs` isn't a valid command anymore in this case, and Gauge reports an error:

```
Table rows validation failed. Table rows range validation failed.
```

However, running ``gauge --table-rows=2-3 specs` runs the spec for two table rows.

Closing this.
