### ISSUE TITLE
Confusion implementing steps

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#388]
Create a concept
```
# concept 1 <arg>
* steppass <arg>
```
This concept can now be used in a spec in different ways as below.
```
Spec
====
Scen1
-----
* concept 1 "1"
* concept 1 <table:foobar.csv>
```

How should the step implementation look like?
* If the method is implemented with String as param data type, there will be issues with type casting String to Table type as they are `Inconvertable types`.
* If the method is implemented with Table as param data type, passing any other data type will throw IllegalArgumentException.
* If the method is implemented with Object as param data type, type casting from Object to Table is throwing an error since the language runner is implicitly passing a String.
```
    @Step("steppass <arg0>")
    public void implementation2(Object arg0) {
        System.out.println("table content : " +((Table)arg0).getColumnNames());
    }
```
```
Error Message: java.lang.IllegalArgumentException: argument type mismatch
            Stacktrace: 
```

**Comment by mahendrakariya** [comment]
This issue was moved to getgauge/gauge-java#54
