### ISSUE TITLE
gauge init failed but creates the folder structure

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#390]
### Expected behavior
If gauge init fails then it should not create any folders.

### Actual behavior
gauge init failed but creates the folder structure

### Steps to reproduce
1. Create a selenium project using template
```
mkdir functionalTest
cd functionalTest
gauge --init java-maven-selenium
```
It fails Failed to initialize project. Plugin 'java-maven-selenium' not installed on following locations
2. However do ls and you will see the folders
```
1. env
2. specs
3. manifest.json
```

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-05-09

Plugins
-------
html-report (2.1.1.nightly-2016-05-10)
java (0.4.0.nightly-2016-05-09)
ruby (0.2.0.nightly-2016-05-09)
xml-report (0.1.2.nightly-2016-05-09)
```

**Comment by BugDiver** [comment]
looks same as #396.
Fix should be available in nightly > 2016-05-15
