### ISSUE TITLE
[Table driven Exec] Scenario exe halts if datastore init fails

### ISSUE THREAD

**Issue by apoorvam** [getgauge/gauge#392]
### Actual behavior

In a spec with datatable if  scenario datastore init fails for 1st row, further rows are not executed. Scenario Executor marks this scenario as skipped/adds it to ScenarioErrMap, which makes further execution of spec as skipped. 
### Expected behavior

If scenario init fails against first row, it should continue with 2nd row execution.

This [TODO](https://github.com/getgauge/gauge/blob/master/execution%2FspecExecutor.go#L265) could potentially fix this issue.

**Comment by zabil** [comment]
Closing this as an old issue. Will open it and look into it if this is still a problem in the newer releases.
