### ISSUE TITLE
The logic to sort plugin nightly versions should be in `version` package

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/gauge#395]
Currently the `plugin/plugin.go` has a struct to sort plugins `byPath`. Since paths are nothing but version number, it is essentially sorting the plugins by version.  There is also sort `byDecreasingVersion` in `version/version.go`.

There is also a func `GetLatestVersion()` in `version/version.go` and another func `getLatestInstalledPlugin()` which is internally calling `getLatestOf()` in `plugin/plugin.go`.

From business point of view, these should have same behavior. But that is not the case. These funcs are producing different outputs, has different logic and is spread across two packages.

**Comment by zabil** [comment]
We don't maitain nightly versions anymore.
