### ISSUE TITLE
Tries to create a project in a language even when the plugin is not available

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#396]
**Expected Behavior**
Should not create a folder structure if the language runner is not available

**Actual Behavior**
Creates the folder structure with basic spec files even if the language runner plugin is not available

**Steps to reproduce**
1. Install gauge, html-report, java.
2. Ensure c-sharp is not installed.
3. on command line run
```
gauge --init csharp
```
4. Since csharp plugin is it fails
```
Failed to initialize project. Plugin 'csharp' not installed on following locations : [/Users/sswaroop/.gauge/plugins]
```
However the folder structure with example.spec is created. 

This is true for the other language runners as well.

**Version**
```
Gauge version: 0.4.1.nightly-2016-05-13

Plugins
-------
html-report (2.1.1.nightly-2016-05-13)
java (0.4.1.nightly-2016-05-13)
xml-report (0.1.2.nightly-2016-05-13)
```

**Comment by sguptatw** [comment]
@BugDiver : Please add the nightly against which this would be available

**Comment by BugDiver** [comment]
@sguptatw This should be available in nightly build > 2016-04-29
