### ISSUE TITLE
Tries to create project for an invalid language runner

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#397]
**Expected Behavior**
If the language runner is not valid the project should not be created.

**Actual Behavior**
It creates the basic gauge structure for an invalid language runner

**Steps to reproduce**
1. mkdir testing
2. cd testing
3. create a project using invalid language runner name.
```
gauge --init sdf
```
4. Creates the basic gauge structure

**Version**
```
Gauge version: 0.4.1.nightly-2016-05-13

Plugins
-------
csharp (0.7.3.nightly-2016-05-13)
html-report (2.1.1.nightly-2016-05-13)
java (0.4.1.nightly-2016-05-13)
xml-report (0.1.2.nightly-2016-05-13)
```

**Comment by BugDiver** [comment]
this issue looks same as #396.
Fix should be available in nightly > 2016-05-15

**Comment by sguptatw** [comment]
@BugDiver 
This is not because this leads to the issue
https://github.com/getgauge/gauge/issues/401
