### ISSUE TITLE
csharp project initiation fails on mac

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#398]
**Expected behavior**
I should be able to create and run c# tests on mac.

**Actual behavior**
It allows to install csharp on mac but fails to create the project on mac.

**Steps to reproduce**
1. install gauge, html-report,csharp on mac
2. init the gauge project
```
mkdir testing
cd testing
gauge --init chsharp
```
3. This fails to create the project, but creates the basic structure.

**Version**
```
Gauge version: 0.4.1.nightly-2016-05-13

Plugins
-------
csharp (0.7.3.nightly-2016-05-13)
html-report (2.1.1.nightly-2016-05-13)
java (0.4.1.nightly-2016-05-13)
xml-report (0.1.2.nightly-2016-05-13)
```

**Comment by sriv** [comment]
C# is not supported on Mac. Need to check if issue exists post fix of #396

**Comment by BugDiver** [comment]
Fixed as #396

**Comment by sriv** [comment]
Note: The fix just address the failure more gracefully. Actual C# on Linux and Mac using Mono is [WIP](https://github.com/getgauge/gauge-csharp/issues/74#issuecomment-222537272), thanks to @tomzo.

**Comment by sriv** [comment]
Closing this, as this is being tracked via getgauge/gauge-csharp#74
