### ISSUE TITLE
Unable to run gauge test in teamcity

### ISSUE THREAD

**Issue by itsmemittal** [getgauge/gauge#399]
Hello, 

I am trying to run gauge+selenium  tests in teamcity and i am getting message **use of closed network connection**

Following details from gauge.log
user and item bank then login as user.
15:51:40.281 * Login as admin user "sbadmin" and password "xxx"
15:53:46.717 Error Message: write tcp 127.0.0.1:14499->127.0.0.1:14504: use of closed network connection
15:53:46.717 Stacktrace: 
15:53:46.718

**Comment by sriv** [comment]
@itsmemittal - Another user had commented on one of your earlier issues (#45), with similar error. [My comment](https://github.com/getgauge/gauge-csharp/issues/45#issuecomment-216445431) suggests a workaround, that worked in the scenario mentioned. Can you please try it out and see if it helps?

**Comment by itsmemittal** [comment]
Failed to start gauge API : Timeout Api connection

**Comment by itsmemittal** [comment]
Yeah, I got it this problem related to selenium server not to gauge i resolved that issue. but when i am running my gauge test on virtual machine i am getting * API Timeout * exception.

Following on my virtual machine.
- Installed gauge
- Installed csharp and html-report plugins
- GAUGE_HOME is in environment variable.

When i try to run gauge --init chsarp command then giving me failed to initialize exception

**Comment by sriv** [comment]
Ok nice, thanks for the update. So can I close this issue ?

**Comment by itsmemittal** [comment]
i need to run my gauge test on virtual machine but i am getting * API Timeout * exception. Even Though i am trying to create new gauge project using gauge --init chsarp but its giving Failed to initialize exception

Following on my virtual machine.

Installed gauge
Installed csharp and html-report plugins
GAUGE_HOME is in environment variable.

**Comment by sriv** [comment]
Can you please copy and paste the output of `gauge -v` from the virtual machine?

**Comment by itsmemittal** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3033471/15318216/bc391860-1c42-11e6-8a55-56edebbcf202.png)

**Comment by sriv** [comment]
You mentioned that you have installed `html-report` plugin also, but it is not showing in this output.

Can you please verify that the output of `where.exe gauge` is the same as the value that you set in your `GAUGE_HOME` env variable?

**Comment by itsmemittal** [comment]
![2](https://cloud.githubusercontent.com/assets/3033471/15319028/72f2fa96-1c46-11e6-85ac-db8816c67b1d.png)

**Comment by itsmemittal** [comment]
![3](https://cloud.githubusercontent.com/assets/3033471/15319100/d504705c-1c46-11e6-828d-5b3c7aae2f54.png)

**Comment by itsmemittal** [comment]
![3](https://cloud.githubusercontent.com/assets/3033471/15319116/e2533cfc-1c46-11e6-9b66-fdbcedb9fdf2.png)

**Comment by sriv** [comment]
Actually, I was wrong, sorry.

`GAUGE_ROOT` is the env variable that should point to the location of the gauge core install.

`GAUGE_HOME` is the location where you would like your plugins to be installed. By default it is `%APPDATA%\gauge`

**Comment by itsmemittal** [comment]
So should i rename it ?

**Comment by sriv** [comment]
Teamcity runs under local account AFAIK, and this causes the `%APPDATA%` location to be at a location different from `C:\Users\...` and we've noticed that this can cause permission issues while launching `Gauge.CSharp.Runner.exe`.

Have you tried the workaround suggested in [my comment ](https://github.com/getgauge/gauge-csharp/issues/45#issuecomment-216445431) I refered to earlier? If so, could you please share the details on what you did, and what was the output? thanks.

**Comment by itsmemittal** [comment]
@sriv Here i am not running gauge test in teamcity. On my vm machine straightforward running gauge commands in command window and getting exception.

**Comment by sriv** [comment]
This issue refers to failure on teamcity, I was assuming your VM was a teamcity agent.

On a simple VM, you do not need to change the environment variables, just a plain install of Gauge, followed by :

- `gauge --install csharp` 
- `gauge --init csharp`
- `gauge specs`

should work. Please indicate the step in which you encounter the error, with error details in a new issue. It will help future users. 

I will close this issue, since this isn't related to Teamcity anymore. Thanks for understanding.

**Comment by itsmemittal** [comment]
As you said i follow same step but getting same issue * Failed to initialize project. exit with status 3221225595*
