### ISSUE TITLE
Should throw parse error in case of empty scenario headings

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#403]
**Expected behavior**
It is skipping the spec

**Actual behavior**
It should execute the spec

**Steps to reproduce**
```
Specification Heading
=====================

* step2
----
* step2
___
* step2
```
2. Give the implementation
```
    @Step("step2")
    public void implementation2() {
    }
```

**Version**
```
Gauge version: 0.4.1.nightly-2016-05-13

Plugins
-------
csharp (0.7.3.nightly-2016-05-13)
html-report (2.1.1.nightly-2016-05-13)
java (0.4.1.nightly-2016-05-13)
xml-report (0.1.2.nightly-2016-05-13)
```

**Comment by sriv** [comment]
I don't see any scenarios in the example given. Are you trying to execute a spec with no scenario and just teardown steps?

**Comment by sguptatw** [comment]
In the above example

* step2
----
* step2 - This is a step of a scenario
___
* step2 - This is the teardown step

**Comment by sriv** [comment]
The definition is ambiguous, `* step2` is a valid step syntax, and since it is single underlined another interpretation is that it could be a scenario.

However, Gauge parses top-down, so 

```
* step2
--------
```

would mean that `step2` is a step and not a scenario. This is by design.

**Comment by sguptatw** [comment]
```
* step2

----
* step2

___
* step2
```
If this is a step and not a scenario, 

then it should give me a parse error that 
`Scenario heading should have at least one character`. But it executes and says 
```
No scenarios found in spec: /Users/sswaroop/work/gauge-test-apps/basic-java/specs/subfolder/one.spec

Successfully generated html-report to => /Users/sswaroop/work/gauge-test-apps/basic-java/reports/html-report
Specifications:	0 executed	0 passed	0 failed	1 skipped
Scenarios:	0 executed	0 passed	0 failed	0 skipped
```

**Comment by apoorvam** [comment]
```
# spec
* step2

----
* step2
___
* step2
```
This is considered as a spec with no scenarios. Even the markdown considers 
```
<empty line>
---
```
 as `br` tag and not as h2. So message `No scenarios found` should be fine.
