### ISSUE TITLE
The project is incompatible with current version of Visual studio

### ISSUE THREAD

**Issue by itsmemittal** [getgauge/gauge#406]
Hi, 

I fork visual studio repository but when i am trying to load this project on VS 2013 or VS 2015 then giving me error "The project is incompatible with current version of Visual studio" for following project
I forked this repository because i want to contribute in it.

- Gauge.ItemTemplate.Concept

**Comment by sriv** [comment]
Hi, you need to install the [Visual Studio SDK](https://msdn.microsoft.com/en-us/library/bb166441.aspx) to open the project. Please make sure that you have the VSSDK for the visual studio version that you plan to use. Currently the Gauge-VisualStudio project are developed on VS2013, so please could you stick to VS2013, we will upgrade the project at a later point.

thanks

**Comment by BugDiver** [comment]
This issue was moved to getgauge/gauge-visualstudio#132
