### ISSUE TITLE
should be able to use the file separator specific to the OS to run command line

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#407]
### Expected behavior
If I am on windows I should be able to run the commands on cmd line using the windows specific file separator

### Actual behavior
Currently the supported file separator is `/`

### Steps to reproduce
1. Create a project with in its own directory 
2. cd into the solution directory
3. run the gauge command
```
gauge projectName\specs
```
This is not working, however the following works
```
gauge projectName/specs
```
It should support file separator specific to the OS.

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-05-16

Plugins
-------
csharp (0.7.3.nightly-2016-05-16)
html-report (2.1.0)
```

**Comment by apoorvam** [comment]
Fix should be available in gauge nightly > 26-5-2016
