### ISSUE TITLE
Concepts defined outside specs folder

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#409]
**Expected Behavior**
If the gauge specs executes the concept, then one should be able to navigate to it and highlighted should be relevant. 

**Notes**
Seems to be the gauge-api issue.

**Actual behavior**
The concept usage is marked as unimplemented, with no goto definition

**Steps to reproduce**
1. Add a concepts folder at the same level of the specs folder
```
<projectname>\specs
<projectname>\concepts
```
2. Create spec in the spec folder
3. Create a concept in the concept folder.
4. execute runs successfully.
5. the usage is highlighted as unimplemented and unable to navigate.

**Version**
VS - 0.2.2

**Comment by apoorvam** [comment]
This issue was moved to getgauge/gauge-visualstudio#146
