### ISSUE TITLE
Overwriting manifest.json, default.properties while creating the gauge --init

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#412]
### Expected behavior
It should skip overwriting any files if they already exist

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1. Create an existing ruby project 
```
mkdir testing
cd testing
gauge --init ruby
```
2. Overwrite some values in manifest.json and default.properties
3. run `gauge --init ruby` again
4. The old changes are lost. However the messages say that manifest.json and default.properties are skipped.

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-05-18

Plugins
-------
html-report (2.1.1.nightly-2016-05-19)
ruby (0.2.0.nightly-2016-05-17)
```

**Comment by kaustavdm** [comment]
To add to this, Gauge prints that it `skip`ped the existing file, but it actually overwrites.

e.g., In this output fragment from `$ gauge --init ruby`, all the files marked as `skip` are currently getting overwritten:

```
 create  manifest.json
 skip  manifest.json
 create  specs
 skip  specs
 create  specs/example.spec
 skip  specs/example.spec
```

**Comment by kaustavdm** [comment]
Had a quick discussion with @kashishm on whether `gauge` should at all allow to run `--init` in a existing Gauge project. This is more of a design decision.

For example, say you have created a gauge-java project by doing `gauge --init java` in a directory and have written some specs and tests. At that point you run `gauge --init ruby` in the same directory.

Now:

 - Should `gauge` throw an error saying something like `This is already a gauge project.`?
 - Or, should `gauge` carry on with its initialization function and avoid overwriting default files that already exist?

In the first case, `gauge` does a preemptive check to determine if the current directory is already a "gauge project". This can be done as of now by checking if a `manifest.json` exists in the current dir and if it has the `Language` key set. If that exists, `gauge` errors out with a message saying this is already a gauge project even before it begins attempting to copy files and invoking runner.

In the second case, `gauge` has no control over what language runners do as part of the `init` process. `gauge` can skip existing files, but runners or templates may overwrite their default implementation files. Gauge can mandate runners from overwriting existing files, but it cannot secure that.

So, this question requires further inputs. cc/ @getgauge/core

**Comment by apoorvam** [comment]
I think we should give an error saying `This is already a Gauge project` and stop initialization. If user still wants to create a new Gauge project in same directory, they will have to remove `manifest.json` file and do `gauge --init`. 
Opinions?

**Comment by sguptatw** [comment]
@apoorvam : +1

**Comment by mahendrakariya** [comment]
With https://github.com/getgauge/gauge/commit/8b55f826fb560a66e0baf165d99929c859f061cc, if `gauge --init` is run in a directory with an existing Gauge project, the message `This is already a Gauge Project. Please try to initialize a Gauge project in a different location.` is shown.
