### ISSUE TITLE
Warn if reporting-plugin is mentioned in manifest but not installed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#413]
**Expected Behavior**
If the reporting plugin is mentioned in the manifest and not installed, I should get a warning.

**Actual Behavior**
It does neither

**Steps to replicate**
1. do not install any reporting plugins.
2. Create a gauge project.
3. The manifest file should contain a reporting plugin.
4. run the spec 
5. It does not warn about the plugin not present.

**Version**
```
Gauge version: 0.4.1.nightly-2016-05-18

Plugins
-------
html-report (2.1.1.nightly-2016-05-19)
ruby (0.2.0.nightly-2016-05-17)
```

**Comment by apoorvam** [comment]
Fix should be available in nightly >= 01.06.2016.
