### ISSUE TITLE
Provide a mechanism to specify table rows per specification/scenario in execution

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge#415]
### Actual behavior

Currently `--table-rows` flag lets you specify the table rows against which all the specified specifications/scenarios are executed. But every specification can have different data table and number of rows in that data table.

So provide a way to specify table rows per specification/scenario.
For Example: 

```
gauge specs/example.spec[1,4] specs/hello.spec[4,10] 
```

Executing the above command will execute scenarios in `example.spec` against `1-4` rows from data table and scenarios in `hello.spec` against `4-10` rows

```
gauge specs/example.spec:3[1,4]
```

Executing the above command will execute 3rd scenario in `example.spec` against `1-4` rows from data table
### Gauge version

```
0.4.1
```

**Comment by zabil** [comment]
This can be done in combination with the `gauge run --scenario` flag which allows running scenarios by name
