### ISSUE TITLE
Able to install windows plugin artifacts on mac

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#421]
**Expected behavior**
If I get a successful installation message. I should be able to perform gauge operations post that.

**Actual behavior**
Windows installer is getting installed on mac, however further operations fail to initiate gauge.

**Steps to replicate**
1. On mac download any plugin of other OS.
2. Install it using gauge --install <plugin> -f
3. It says successful
4. Cannot perform operations of gauge

**Version**

**Comment by sriv** [comment]
Should be addressed via #567
