### ISSUE TITLE
parser.ParseError should have file name

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/gauge#425]
In specParser.go, there is [`ParseError`](https://github.com/getgauge/gauge/blob/f8212264992c44e05b49ccda06f5dfdd63bf576d/parser/specparser.go#L739) object which has message, line text, and line number. But it doesn't have file name.

```
type ParseError struct {
    LineNo   int
    Message  string
    LineText string
}
```

The file name information is instead present in [`ParseResult`](https://github.com/getgauge/gauge/blob/f8212264992c44e05b49ccda06f5dfdd63bf576d/parser/specparser.go#L758) object, which has arrays of parse errors and warnings.

```
type ParseResult struct {
    ParseErrors []*ParseError
    Warnings    []*Warning
    Ok          bool
    FileName    string
}
```

This leads to more issues since a new instance of `ParseResult` is not always returned for every parsed file. An example of this is [parser.CreateConceptsDictionary()](https://github.com/getgauge/gauge/blob/master/parser/conceptParser.go#L205).

So, the file name details should be moved from `ParseResult` to `ParseError`.

**Comment by apoorvam** [comment]
The same should apply to [`parser.Warning`](https://github.com/getgauge/gauge/blob/f8212264992c44e05b49ccda06f5dfdd63bf576d/parser/specparser.go#L773) as well. Even this object doesn't have file name.

**Comment by mahendrakariya** [comment]
We may not be able to get rid of `FileName` from `parser.ParseResult` altogether, for the time being. While parsing spec files, a separate object of ParseResult is returned for every file. And this information is used by [`formatter.FormatSpecFiles()`](https://github.com/getgauge/gauge/blob/07e1c26ab461a61a3111e5106d68a1d64efa4179/formatter/formatter.go#L39).

The real issue here is that the purpose/usage of `parser.ParseResult` is not well defined. In case of parsing concepts, a errors/warnings are merged across multiple files into a single `ParseResult` object. But while parsing specs, a separate `ParseResult` object is created for each file.

**Comment by zabil** [comment]
Closing this as an old issue and may have be fixed. 
Will open it and look into it if this is still a problem in the newer releases.
