### ISSUE TITLE
Concept with static parameter is not giving a parse error

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#427]
**Expected Behavior**
* Concept with static parameter should give a parse error.

**Actual Behavior**
* Concept with static parameter is not giving a parse error. Gives validation error while executing.

**Steps to replicate**
1. Create a file with multiple concepts
```
# testinghjk "sdf"

* step1
* step1

# Concept Heading37a
* step1
* step2
___
* step2
```
2. Create a spec
```
One
=====================

A concept file
------------
* testinghjk "sf"
```
3. This is not giving a parse error.

**Version**
```
Gauge version: 0.4.1.nightly-2016-05-30

Plugins
-------
html-report (2.1.1.nightly-2016-05-30)
java (0.4.1.nightly-2016-05-30)
```

**Comment by apoorvam** [comment]
With [this](https://github.com/getgauge/gauge/commit/ad4537da7c7995824d68251142db92a010eb44a1) commit, the parse error is shown if static params are present in concept heading. 
```
[ParseError] specs/one.cpt:1 Concept heading can have only Dynamic Parameters => 'Concept "foobar"'
```

This will appear when you run `gauge --validate specs`. Showing this parse error in IDE should be separate issues in respective IDE's.

Fix should be available in nightly >= 2016-06-16

**Comment by sguptatw** [comment]
Unable to verify 'cause of #460

**Comment by apoorvam** [comment]
This is ready for QA as the dependent issue #460 is now fixed.
