### ISSUE TITLE
One should be able to refactor from the command line from specs outside the spec folder

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#430]
### Expected behavior
One should be able to refactor from the command line from specs outside the spec folder

### Actual behavior
The command line refactor does not take the specs folder as an argument. So no way to change it

### Steps to reproduce
1. Create a spec folder spec1 
2. Create a spec inside spec1
```
spec else
=====================

not
---------------------------
* something
```
2. Give default implementation
3. Goto the command line. Execute the cmd
`gauge --refactor "something" "something else"`
4. The step implementation changes but not the spec file.

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-05-30

Plugins
-------
html-report (2.1.1.nightly-2016-05-30)
java (0.4.1.nightly-2016-05-30)
```

**Comment by BugDiver** [comment]
The usage is wrong. In case specs files are not present in the default folder, the actual folder name(s) should be passed to `--refactor`. Something like this.

`gauge --refactor "something" "something else" spec1`
