### ISSUE TITLE
Add support to execute scenario by line number

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge#440]
### Expected behavior
Execute a scenario by providing line number with the spec name.

Example: `gauge specs/example.spec:10`

### Gauge version
```
0.4.0
```

**Comment by kashishm** [comment]
latest nightly of Gauge, Gauge-Visualstudio and gauge-IntelliJ will support this.

**Comment by sguptatw** [comment]
Gauge-Visualstudio nightly is not available

**Comment by kashishm** [comment]
@sguptatw you can use the Gauge Visual Studio nightly 2016-06-08, Gauge IntelliJ plugin nightly 2016-06-15 and Gauge nightly 2016-06-14  to test this.
