### ISSUE TITLE
After the first spec an after suite failure is not executing subsequent specs

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#443]
### Expected behavior
A suite is a collection of specs, an after suite hook should execute after the collection of specs are executed.

### Actual behavior
A failure in after suite is not executing subsequent specs.

### Steps to reproduce
1. Create 3 specs, with implementations
2. throw exception in after suite
```
    @AfterSuite
    public void A2(ExecutionContext context) throws Exception {
        throw new Exception(getName(context));
    }
```
3. Only the first spec is executed. Subsequent specs are skipped.
4. After suite should have been executed after all the specs are executed.

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-06-06

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-05-30)
```

**Comment by apoorvam** [comment]
This is not reproducible with mentioned gauge version. It works as expected.

**Comment by sguptatw** [comment]
Yes it works in the current gauge nightly. So closing the issue.
