### ISSUE TITLE
Scenario with no steps is getting executed and shown as passed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#444]
### Expected behavior
Scenarios with no steps should give a parse error

### Actual behavior
It is getting executed

### Steps to reproduce
1. Create a spec
```
spec else
=========
tags: top head

here
----

tags: scenario3 ppp a b c d e f g h i j k l m n o p q r s t u v w x y z

This is the second scenario in this specification

Here's a step that takes a table
```
2. Execute the scenario.
3. The result is
```
Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	1 executed	1 passed	0 failed	0 skipped
```
whereas this has no steps

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-06-06

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-05-30)
```

**Comment by apoorvam** [comment]
If scenario has no steps, a validation error should be thrown instead of parse error. The scenario should also be skipped.

This has been implemented and should be available in nightly >= 2016-06-10.

**Comment by sguptatw** [comment]
The statistics displayed is wrong.

```
Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	0 executed	0 passed	0 failed	1 skipped
```
The spec should also be skipped.

**Comment by BugDiver** [comment]
Fix should be available in nightly >= 16-06-2016.

**Comment by abenabderrahmane** [comment]
hello
