### ISSUE TITLE
BeforeClassSteps and AfterClassSteps executes for every scenario but does not have execution context details

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#446]
### Expected behavior
Should the BeforeClassSteps and AfterClassSteps be executed after every scenario. If yes then the execution details should have the details, else the hooks should not get executed multiple times.

### Actual behavior
Before and after class steps are getting executed for every scenario, however the execution context does not have the details.

### Steps to reproduce
1. Create spec with multiple scenarios.
2. Add the implementation
```
    public String getName(ExecutionContext context) {
        String tags = context.getAllTags().toString();
        String scenarioName = context.getCurrentScenario().getName().toString();
        String specName = context.getCurrentSpecification().getName().toString();
        String step = context.getCurrentStep().getText().toString();

        return "spec name \n" + specName + "tags \n" + tags + "scenario \n" + scenarioName + " step \n" + step;
    }

    @BeforeClassSteps
    public void BeforeClassSteps(ExecutionContext context) throws Exception {
        throw new Exception("before class steps " + getName(context));
    }

    @AfterClassSteps
    public void AfterClassSteps(ExecutionContext context) throws Exception {
        throw new Exception("after class steps " + getName(context));
    }
```
3. Execute the specs and see the report. It does not display the execution context details and is executed multiple times.

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-06-06

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-05-30)
```

**Comment by apoorvam** [comment]
This is by design. Moreover, `BeforeClassSteps` and `AfterClassSteps` have been deprecated and we don't expect the users to use these annotations any more.
