### ISSUE TITLE
Could not resolve table from table giving wrong line number

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#448]
**Expected Behavior**
Should point to the line where the table is defined.

**Actual Behavior**
Is pointing to the eof line number

**Steps to replicate**
1. Create a spec
```
Specification Heading
=====================
tags:top
table:c
* to pass

c
-----------------------------

* pass

c1
-----------------------------
tags:scenario3 ppp a b c d e f g h i j k l m n o p q r s t u v w x y z

* pass

* pass
```
2. Create implementation
```
    @Step("pass")
    public void implementation5() {
    }
```
3. run the specs.
See the line number indicated in the error is of the eof and not the line with the table definition.

**Version**
```
Gauge version: 0.4.1.nightly-2016-06-06

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-05-30)
```

**Comment by apoorvam** [comment]
Fix should be available in nightly >= 2016-06-16
