### ISSUE TITLE
Proposal: The statistics should reflect data driven execution as well.

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#453]
Currently the statistics in any reporting format has at max the details of the specification/scenarios executed, passed, failed, or skipped.
However, a spec having n scenarios with data table driven execution is reported as n scenarios only. 
For each row in a data driven execution, the scenarios are executed n*row number of times. 
Assuming there are x failures and y passes. The statistics still show only

```
Specifications: 1 executed  0 passed    1 failed    0 skipped
Scenarios:  n executed  0 passed    n failed    0 skipped
```

Option 1:-
If one were to consider each row as a different scenario driven by data, it would mean the following representation.
The statistics could be represented as

```
Specifications: 1 executed  0 passed    1 failed    0 skipped
Scenarios:  n*rows executed y passed    x failed    0 skipped
```

`where x+y = n*rows`

Option 2 :-
If one were to consider this as one scenario with various data parameters The statistics representation would look like.

```
Specifications: 1 executed  0 passed    1 failed    0 skipped
Scenarios:  n executed  0 passed    n failed    0 skipped
Data driven:     n*rows executed x passed y failed 0 skipped
```

Which option works for you or do you have any other suggestions. Please comment.

**Comment by srpelissier** [comment]
I would not consider each row as an individual scenario. And I am not sure what your proposal is improving. None of the two options seems better to me than the current state.

This being said, I wonder what it is you are improving: debugging errors in test, designing data driven tests? In my opinion, if one needs to pass data to a scenario and they are multiple rows, it's because the rows play a different role for the scenario (otherwise it is just repeating the same test). And if the data is so different between rows that it needs its test results to be written down separately as pass or fail, does it not mean that these are potentially different scenarii?

The current implementation seems to encourage designing test cases that are very focused on one thing, while making the statistics more flexible will encourage writing spaghetti code.

**Comment by sguptatw** [comment]
@srpelissier : Thanks for your response.

As you mentioned, the data given to a scenario using a table would have different role for the scenario otherwise one would be repeating the test.
Using `data driven feature` gives the ability to see how the application is behaving in this scenario and changing data context. Hence the question - does the user perceive changing data context as different scenarios, if yes then how should it reflect in the statistics of the report.

**Comment by srpelissier** [comment]
Hello Soumya. The Data Driven line seems to report the results for one scenario only. Does this not imply there has to be one such line for every scenario that is data driven? I had a try at running gauge with -p yesterday. How readable will the statistics become combining data-driven results and parallelism?

**Comment by sguptatw** [comment]
@srpelissier : Gauge's current behavior is - when the data driven table is added to a scenario it gives the results for all the rows. 
The attached results are of the spec with data table(details mentioned to replicate are given below). [html-report.zip](https://github.com/getgauge/gauge/files/315758/html-report.zip) [xml-report.zip](https://github.com/getgauge/gauge/files/315775/xml-report.zip). This is independent of sequential and parallel runs.

Also please help us with ur view about - 
`does the user perceive changing data context as different scenarios, if yes then how should it reflect in the statistics of the report.`
__________
Example below help to re-create the scenario we are discussing.

1.  Create a project. By default html-report is added to the project.  
```
gauge --init java
```

2. Create a spec
```
Specification Heading
=====================

     |data table|
     |----------|
     |a         |
     |b         |
     |c         |

This is a scenario
------------------

* This is a step with param from <data table>
```
3. With implementation
```
    @Step("This is a step with param from <data table>")
    public void implementation1(String argDataTable) {
        assertEquals(argDataTable,"a");
    }
```
4. run the specs
```
gauge specs
```
The html-report looks like this [html-report.zip](https://github.com/getgauge/gauge/files/315758/html-report.zip)
- click on the specific spec with the data table. On the RHS one will see the data table printed. Clicking on the individual rows give the corresponding run details.

5. If you add xml-report to the project, do
```
gauge --add-plugin xml-report
gauge specs
```
The xml report has test cases which look like the following, where the scenario name is repeated with the data row index.
```
		<testcase classname="Specification Heading" name="This is a scenario 0" time="0.001"></testcase>
		<testcase classname="Specification Heading" name="This is a scenario 1" time="0.000">
			<failure message="This is a step with param from &lt;data table&gt;&#xA;Step Execution Failure: &#39;org.junit.ComparisonFailure: expected:&lt;[b]&gt; but was:&lt;[a]&gt;&#39;" type="This is a step with param from &lt;data table&gt;&#xA;Step Execution Failure: &#39;org.junit.ComparisonFailure: expected:&lt;[b]&gt; but was:&lt;[a]&gt;&#39;">org.junit.Assert.assertEquals(Assert.java:115)&#xA;org.junit.Assert.assertEquals(Assert.java:144)&#xA;StepImplementation........................&#xA;</failure>
		</testcase>
		<testcase classname="Specification Heading" name="This is a scenario 2" time="0.000">
			<failure message="This is a step with param from &lt;data table&gt;&#xA;Step Execution Failure: &#39;org.junit.ComparisonFailure: expected:&lt;[c]&gt; but was:&lt;[a]&gt;&#39;" type="This is a step with param from &lt;data table&gt;&#xA;Step Execution Failure: &#39;org.junit.ComparisonFailure: expected:&lt;[c]&gt; but was:&lt;[a]&gt;&#39;">org.junit.Assert.assertEquals(Assert.java:115)&#xA;org.junit.Assert.assertEquals(Assert.java:144)&#xA;StepImplementation...........................&#xA;</failure>
		</testcase>

```

**Comment by srpelissier** [comment]
In my opinion, there is just one scenario which gets input from a table and consists of as many steps as the number of rows in the table. Are you asking if multiple steps defined under a single scenario should be treated as multiple scenarii?

**Comment by sguptatw** [comment]
@srpelissier : Thanks for the input. 
We are referring to the scenario getting input from the table which you said you would perceive as a single scenario. Thanks again.

**Comment by kbangur** [comment]
@sguptatw : I would surely consider each row as a different scenario driven by data. I was just wondering how would we show stats with Option 1 or Option 2 when there are more than 1 Specification executed with few of them having data driven scenarios! Though on a later stage of this discussion - but I would also be interested to understand if we are considering the HTML reports OR results.js JSON data file to change based on conclusions from #453

**Comment by sguptatw** [comment]
@kbangur: Thanks for your response.
________________
Please find the details of Option1 and Option2 for the following scenario
`x Specs` with `y scenarios`. 
Assume there are 2 specs with `2 scenarios are data driven` each i.e total of 4 scenario in these 2 specs. 
Let spec 1 have  table data of `b rows` and spec 2 have `c rows`.
Let there be a `1 scenario which fails for 1 data row in 1st spec` driven by data table.
Let there be a `2 scenarios which fails for 2 data row in 2nd spec` driven by data table.
The statistics would like the following

Option 1
The total number of specs in the project would y - number of scenarios with data table driven rows + (scenarios*rows of every spec which is data driven). Thereby
 
`z = ((y-4)+(b*2)+(c*2))` executed
counting every failure there would be `5 failures`
counting the number passed `((y-4)+((b*2)-1))+((c*2)-4)))`


```
Specifications: x executed  x-2 passed   2 failed    0 skipped
Scenarios:  ((y-4)+(b*2)+(c*2)) executed  ((y-4)+((b*2)-1))+((c*2)-4))) passed   5 failed    0 skipped

```
Option 2
```
Specifications: x executed  x-2 passed    2 failed    0 skipped
Scenarios:  y executed  y-3 passed    3 failed    0 skipped
Data driven:     (b+c) executed (b+c-5) passed 5 failed 0 skipped
```

**Comment by srpelissier** [comment]
> Let spec 1 have table data of b rows and spec 2 have c rows.
Isn't it possible that the data table is declared at scenario level?

**Comment by mahendrakariya** [comment]
> Isn't it possible that the data table is declared at scenario level?

Not as of now. But we have an open issue for that. https://github.com/getgauge/gauge/issues/111

**Comment by srpelissier** [comment]
Maybe I did not put it correctly. In theory I think the table can be at spec-, scenario- and step-level. Does that not affect the calculation of the results? Were the above examples from Soumya not considering only spec-level data tables?

**Comment by mahendrakariya** [comment]
> I think the table can be at spec-, scenario- and step-level.

Currently, Gauge treats tables at various levels quite differently. 

  * **Spec level:** Table can be declared at spec level. In this case, Gauge executes all the scenarios for every row of the table. In Gauge terminology, this is [data driven execution](http://getgauge.io/documentation/user/current/gauge_terminologies/parameters/table_parameters.html#data-driven-execution).
     * As a side note, I would like to add that there is an open issue to change this behavior. https://github.com/getgauge/gauge/issues/219
  * **Scenario level:** Gauge doesn't support tables at scenario level as of now. Once #111 is implemented, a scenario with data table will be executed for every row of the table.
  * **Step level:** At a step level, Gauge only supports table as a parameter. The entire table associated with step is passed on to step implementation. So a step with table is executed only once, irrespective of the number of rows in the table. You can refer [documentation](http://getgauge.io/documentation/user/current/language_features/step_implementations.html#step-with-table) for more details. 


> Were the above examples from Soumya not considering only spec-level data tables?

Yes! The examples given by @sguptatw are only considering spec level data tables.
I think we should even discuss how the stats will look like once #111 is implemented.

**Comment by srpelissier** [comment]
OK, I was off topic then, considering only spec-level. I was even ignorant of gauge's understanding of the data driven execution concept. This makes much more sense now.
So back to @sguptatw's original question: I am not in favor of treating rows as separate scenarii. The reason why is that the rows of a table have the same structure (group of fields), so the same logic should be applied. The logic is captured in the scenarios/steps. If you enforce treating different rows of the same table as potentially different scenarii, then the logic is attached to both the scenario and the data, without adding anything specific. Isn't that giving too much responsibility to the data, thus mixing logic and content together (which is something I try to avoid).
This is very personal opinion, but I must say that I have not come up with a situation where I would benefit from a different logging option where data driven execution need a separate report, nor do I see direct gain when the results is on two lines but it includes finer grained counts.

**Comment by sguptatw** [comment]
@srpelissier : Thanks for the input.

**Comment by kasto** [comment]
I am using data driven tables at Spec level. This enhancement is one of the key asks - Without this, execution report doesn't carry much meaning in case of data driven test execution. We may have different datasets for each role type and may want to see how many different role data passed and how many failed. Don't see a target milestone for this enhancement - Is it planned anytime soon?

**Comment by srpelissier** [comment]
@kasto Are you describing a data table containing user login credentials? If so I understand your needs. However, I am curious what the quantity of failures/successes tells you about the actual quality of the functionality being tested. Maybe did I misunderstood you though: what do you mean by dataset (is that different from the table itself, or a row in that table)? Thanks.

**Comment by kasto** [comment]
@srpelissier I am talking about scenarios involving role based testing. Test dataset could be more than just user credentials, additional attributes describing user characteristics. Even expected assertions for each usertype will be passed in this data row. So, essentially we are talking about each data row being a test-case in this specific type of testing (as actual assertions, passed from data row, could be different; though assertion step could be abstracted to be generic to handle all data rows)

**Comment by mahendrakariya** [comment]
@kasto That's an interesting use case your are mentioning. Would it be possible for you to share a sample project (using gist or github) that describes the use case you are mentioning?

We would like to understand how Gauge is being used by different users.

**Comment by kasto** [comment]
@mahendrakariya Thought this is a very common use case across various types of test cases that we execute in most projects. Unfortunately, don't have shareable code for sample

**Comment by thjenny** [comment]
for our needs, Option 1 would be the solution.

We use data driven tests for testing a decision workflow.
Each test data row contains the input data for the decision, and the expected output/result.
The gauge specification then contains one scenario, essentially with the 3 steps:

- prepare the data
- call the decision
- compare expected and effective results

This has proven to be a very efficient way to test, because our business people will just edit an Excel file to prepare additional test cases, or to edit existing ones.
We have multiple data driven scenarios with e.g. 50 rows or more.

The current statistics are only marginally useful in this case, because it does not distinguish if e.g. 1 of the 50 rows failed, or if all of them failed, in both cases, 1 scenario fails according to the stats.

**Comment by Apoorva-GA** [comment]
Should be fixed as part of https://github.com/getgauge/gauge/issues/1261.

**Comment by sguptatw** [comment]
[Discussion Update]
**Expected behavior**
The statistics should be consistent in console and HTML report. There will be a toggle feature at the project level to indicate if the data rows are considered for stats or not.

**Comment by sguptatw** [comment]
**Expected behavior**
The statistics should be consistent in console and HTML report. There will be no toggle feature.
The statistics will now consider rows for calculating report statistics. i.e `Option 1` of the original proposal.

**Known Issue**
Statistics calculation when `table-driven-scenario` feature is enabled needs to be handled - https://github.com/getgauge/gauge/issues/1299

**Comment by Debashis9012** [comment]
Tested the above scenario. Now the statistics are displaying consistent result in output console, html report and in last execution report.

Tested with the below versions
```
auge version: 1.0.4.nightly-2019-01-22
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.7.nightly-2019-01-11)
java (0.7.0.nightly-2019-01-18)
gauge-0.0.8.nightly-2019-01-24.vsix
```
![Screen Shot 2019-01-24 at 4.32.38 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c2c44a4dc094700118e111a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77226456f76b7191a37cf111294f5c575ecc3c4a4356bcbbd671f3e57862804e0eebd4395775906847afebd74bbf05bc208b4bd4b5ef8f4ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df243e24f5da5133e63e4772431.png)
![Screen Shot 2019-01-24 at 4.33.51 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c2c44a4dc094700118e111a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77226456f76b7191a37cf111284f5a5e5ecc3c4a4356bcbbd671f3e57862804e0eebd4395775906847afebd74bbf05bc208b4bd4b5ef8f4ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df243e24f5da5133e63e4732431.png)
![Screen Shot 2019-01-24 at 4.38.38 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c2c44a4dc094700118e111a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77226456f76b7191a37cf111234f5c575ecc3c4a4356bcbbd671f3e57862804e0eebd4395775906847afebd74bbf05bc208b4bd4b5ef8f4ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df243e24f5da5103164e1762431.png)
