### ISSUE TITLE
Trying to install active demo example app but fails

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#456]
### Expected behavior
Following the instructions mentioned in the demo app, I should be able to set up the demo app.

### Actual behavior
```
bundle exec rake db:drop db:create db:migrate db:seed
Could not find activemodel-3.0.10 in any of the sources
Run `bundle install` to install missing gems
```

### Steps to reproduce
1. checkout in a new folder https://github.com/getgauge/activeadmin-demo
2. Follow the instructions.
3. On `bundle exec rake db:drop db:create db:migrate db:seed` getting the above error.

### Gauge version
```
Gauge version: 0.5.1.nightly-2016-06-14

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-06-14)
xml-report (0.1.2.nightly-2016-05-27)
```

**Comment by mahendrakariya** [comment]
Could you try running `bundle install` before `bundle exec`?

By the way, you don't need to build this app locally. This app has been packaged into [activeadmin-demo.war](https://bintray.com/artifact/download/gauge/activeadmin-demo/activeadmin-demo.war). You can use that. See [this](https://github.com/getgauge/gauge-example-java#setting-up-the-system-under-test-sut) for more details.

**Comment by sguptatw** [comment]
@mahendrakariya : I followed all the steps

```
bundle install 
Fetching dependency metadata from http://rubygems.org/
Using rake 0.9.2
Using abstract 1.0.0
Using activesupport 3.0.10
Using builder 2.1.2
Using i18n 0.5.0
Using rack 1.2.3
Using tzinfo 0.3.29
Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES
section: 'mini_portile'
```
This is a new folder and a fresh checkout. I just wanted to test it by building it locally following all the instructions given.

**Comment by mahendrakariya** [comment]
The recommendation is to use the war which is already built.
