### ISSUE TITLE
With table column name missing, the spec file does not give the goto step definition

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#458]
**Expected behavior**
Features like goto definition or create step implementations are working when there are other parse errors. It should work when a table does not have a header.

**Actual behavior**
Does not give me options to create/navigate a step

**Steps to replicate 
1. Create a spec
```
Something
=========
||
|---|
||
Scenario Heading
----------------
* Step that takes a table1 <dynamic>
* s"a˘bc"
* s"def"
```
2. Unable to perform the above mentioned operations

**Version**
```
Gauge version: 0.5.1.nightly-2016-06-16

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-06-16)
xml-report (0.1.2.nightly-2016-05-27)
```

**Comment by mahendrakariya** [comment]
This issue was moved to getgauge/Intellij-Plugin#201
