### ISSUE TITLE
WriteMessage to write on console as well

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#461]
Currently the write message output is given in the reports only. It would be helpful if this would reflect on the console as well.

### Gauge version
```
Gauge version: 0.5.1.nightly-2016-06-16

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-06-16)
xml-report (0.1.2.nightly-2016-05-27)
```

**Comment by apoorvam** [comment]
Duplicate of #503. Closing this.
