### ISSUE TITLE
Linux: installing gauge require switching to root account

### ISSUE THREAD

**Issue by srpelissier** [getgauge/gauge#465]
### Expected behavior

`sudo go run build/make.go --install` should install **gauge**
### Actual behavior

I need to log in as root
### Steps to reproduce
1. Follow the steps to install **go**, get the gauge source code and build it using `go run build/make.go`
2. To install **gauge** it you need to add `--install` to the previous command.

Usually installing software in `/usr/local/bin` require super user privileges, eg. with `sudo`, but not here (which is the problem I'm reporting).
Workaround: `sudo su -` to log in as root, define $GOPATH, and run `--install` as root, when I believe elevated privileges should suffice.

See also [June 21, 2016 11:41 AM](https://gitter.im/getgauge/chat?at=57690bc02a4cd63745eb82b2)

```
Gauge version: 0.5.1

Plugins
-------
ruby (0.2.1)
```

**Comment by mahendrakariya** [comment]
You can use the `gaugeInstallPrefix` flag to specify where you want to install Gauge. Something like this.

```
go run build/make.go --install --gaugeInstallPrefix=/home/username/Documents/gauge
```

**Comment by sguptatw** [comment]
@srpelissier : Please let us know if this solved the issue.

**Comment by sriv** [comment]
Still an issue. In linux `gauge` is installed at `/usr/bin` which requires `sudo` access.

**Comment by kashishm** [comment]
Gauge can be installed on custom location with the following command
```
go run build/make.go --install --prefix <path>
```
It requires the `GAUGE_ROOT` to be set to `<custom_path>` and`<custom_path>/bin` should be in `PATH` env var.
