### ISSUE TITLE
Messaging of duplicate code implementation

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#469]
On identifying duplicate step implementation, the gauge process gives a validation error. It will be more useful if the error message had the details of the code files where these duplicate step implementations can be found apart from the spec file where the step is being used.

**Comment by kaustavdm** [comment]
This information can be passed along in the `errorMessage` field, without needing to change the proto. But, gauge currently does not display the content of `errorMessage` as far as I can see.

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
