### ISSUE TITLE
Gauge autocomplete fails if parse/compile fails

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#47]
Even if there is a problem in building the language implementation, Gauge should ideally return steps to autocomplete.

Gauge should attempt a best-effort approach in responding to API messages, rather than breaking all features.

**Comment by prateekbaheti** [comment]
Gauge reverts back with steps from spec files if runner fails due to any error. On parse errors in spec files, steps are returned from the succesfully parsed spec files.
