### ISSUE TITLE
Refactoring with a new step parameter name changes data values and parameter names

### ISSUE THREAD

**Issue by alpermermer** [getgauge/gauge#472]
### Expected behavior

It should change the naming and definition but shouldn't touch the data
### Steps to reproduce

Using Ruby project strucuture;
Setup: 
- I have 2 spec files and a step definition file
- In the specs there are 2 identical steps as: Go to website "www.google.com"
- In the step definition the step is defined as step 'Go to website <site>' do |site|

1- Then i execute this command: gauge --refactor "Go to website <site>" "Go to website <website>"
### Results of these steps
- In the specs file, the steps are changed into this: Go to website "website" (notice the loss of data)
- In the step definition, the new definition is changed into this: step 'Go to website <website>' do |arg_website| (notice the argument name change)
### Gauge version

```
Gauge version: 0.5.0

Plugins
-------
html-report (2.1.0)
java (0.4.1)
ruby (0.2.1)
xml-report (0.1.2)
```

**Comment by zabil** [comment]
Gauge will be deprecating the `--refactor` from command line.
