### ISSUE TITLE
Feature Request: Video Recording for Gauge

### ISSUE THREAD

**Issue by alpermermer** [getgauge/gauge#473]
### Video Recording for Gauge

Some specification suggestions:
- Videos could be recorded per suit, per feature or per scenario: (per feature would be default)
- Video fps and quality could be lower than standart (should be trialed and should be configurable)
- Videos should be recorded if there is a failure (default behaviour, should be configurable)
- Failure moment should be indicated in the video, including a log dump in the same folder.

**Comment by tk8817** [comment]
Hi @longlost this is really not something that guage should be concerned with in its core. It could be a plugin but even that is really stretching things as it would have to be fairly opinionated. There are some great libraries out there which will do this for you, a good example would be the Headless gem for Ruby which you can insert right into your start / pass / fail blocks.

**Comment by longlost** [comment]
Hi @tk8817 Justin, thank you for the comment. I don't think this video recording feature is very different than screenshot taking on failure. It could definitely get de-prioritized though.

**Comment by zabil** [comment]
Gauge is going to delegate the responsibility to the driver used for testing for example https://github.com/getgauge-contrib/taiko-screencast
