### ISSUE TITLE
Content comes from skel folder even if a template exists

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#475]
### Expected behavior
If a language plugin template exists, then the content generated during init should come from there else from the plugin skel.

### Actual behavior
Though ruby template is available, the content generated is from https://github.com/getgauge/gauge-ruby/blob/master/skel/step_implementation.rb

### Steps to reproduce
1. Create a project using
`gauge --init ruby`
2. The content generated is from
https://github.com/getgauge/gauge-ruby/blob/master/skel/step_implementation.rb

### Gauge version
```
Gauge version: 0.5.1.nightly-2016-07-10

Plugins
-------
html-report (2.1.1.nightly-2016-07-08)
java (0.4.2.nightly-2016-07-07)
ruby (0.2.1)
```

**Comment by apoorvam** [comment]
The reason Ruby template is generated using plugin skel is that, ruby template is not added in repository of templates [here](https://bintray.com/gauge/Templates/gauge-templates#files). So we need to add templates for Ruby and C# over here.

**Comment by sguptatw** [comment]
The ruby template is added at https://github.com/getgauge/gauge-repository/tree/master/templates/ruby in the morning. However this is not appearing in the list you have mentioned. Assuming everything gets published by 6 pm, this is still not available.

**Comment by mahendrakariya** [comment]
Templates don't change often. So there is no nightly job for them. You will have to publish them by manually triggering the job on the build pipeline.

**Comment by sguptatw** [comment]
The [publishing](https://build.getgauge.io/go/tab/pipeline/history/Templates) of the job seems to be failing on the pipeline.

**Comment by kashishm** [comment]
Ruby template is published now. Currently, `gauge --list-templates` shows ruby twice because ruby and csharp are hardcoded in Gauge. This would be fixed in nightly >= 2016/07/12
