### ISSUE TITLE
Clojure language runner

### ISSUE THREAD

**Issue by jerger** [getgauge/gauge#479]
As I'm using clojure for large and more and more projects, it would be fine, to have a clojure language runner also. 

Is someone else interested in? 

Some chance to implement such a runner in a team?

**Comment by mahendrakariya** [comment]
@craftybones You were talking about writing a Clojure runner for Gauge. You may want to get in touch with @jerger.

**Comment by craftybones** [comment]
@jerger I'm certainly interested.

**Comment by jerger** [comment]
:-) To get in touch u can use my email - it's visible in my github profile ...

**Comment by nehashri** [comment]
closing as stale, reopen the issue if needed

**Comment by lyderichti59** [comment]
I'd be very happy to use Gauge with Clojure too !
