### ISSUE TITLE
ContinueOnFailure should not be allowed on hooks

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#483]
**Expected behavior**
I should get a validation error or message that ContinueOnFailure cannot be applied on the hooks

**Actual behavior**
It ignores the tag if present on any hook

**Comment by kaustavdm** [comment]
Shouldn't it be a warning rather than an error? Having ContinueOnFailure does not affect the behaviour of a hook. It is dead code, AFAIK.

**Comment by sguptatw** [comment]
@kaustavdm : The expected behavior states an error or a message (I meant warning)

**Comment by raviu** [comment]
Is there a design reason why we can't use ContinueOnFailure with hooks?

**Comment by Apoorva-GA** [comment]
@raviu hooks are generally not functional. So if you want ContinueOnFailure with hooks we would encourage to handle exceptions (use a try catch block).
