### ISSUE TITLE
Link is broken for installing guage "http://getgauge.io/documentation/user/current/installations/"

### ISSUE THREAD

**Issue by shashisd** [getgauge/gauge#486]
Not able to access the link
http://getgauge.io/documentation/user/current/installations/ 
![guage](https://cloud.githubusercontent.com/assets/1111921/17061538/a5e02840-504c-11e6-8dd6-e460d5b4281f.JPG)

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Gauge version
```
Run gauge -v on your system and paste the results here.
```

**Comment by mahendrakariya** [comment]
@shashisd Thanks a lot for reporting this issue. We have fixed it. You should now be able to access the link.
