### ISSUE TITLE
gauge_clear_state_level = scenario should be a property in default.properties

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#487]
This is a gauge core level property. On generation of project, this should get added to the default.properties file and not language specific property file. 

Please verify the code generated using the fall back mechanism - with no internet as well.

**Version**

```
Gauge version: 0.6.1.nightly-2016-07-25

Plugins
-------
csharp (0.8.1.nightly-2016-07-18)
html-report (2.1.1.nightly-2016-07-20)
java (0.4.2.nightly-2016-07-15)
ruby (0.2.2.nightly-2016-07-13)
```

**Comment by sriv** [comment]
fix available in nightly >= 10/03/2017

**Comment by sguptatw** [comment]
Test cases
- [ ] should work when project is create offline (there is no internet connection)
- [ ] should work in Mac Gauge Java project
- [ ] should work in Mac Gauge C# project
- [ ] should work in Mac Gauge Ruby project
- [ ] should work on Windows Gauge Java project
- [ ] should work on Windows Gauge C# project
- [ ] should work on Windows Gauge ruby project
- [ ] should work in Ubuntu Gauge Java project
- [ ] should work in Ubuntu Gauge ruby project

**Comment by sguptatw** [comment]
Unable to create a ruby project

**Comment by sriv** [comment]
Is there a correlation? This change doesn't look like anything to do with ruby

**Comment by sguptatw** [comment]
I have to check the property file created when the ruby project is initialized. I can't check this until I create a ruby project.
