### ISSUE TITLE
Quotes in the step code implementation is treating the parameter as dynamic

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#489]
**Expected behavior**
The <> should be used for dynamic parameters.

**Actual behavior**
In code if the annotation text `@Step("Add \"product\" to basket")` is being allowed and considered as dynamic parameter. However subsequent operations like refactoring are not working.

**Steps to replicate
1. Create a spec

```
Test all verifications
======================
* Add "product1" to basket

Test break on failure
---------------------
* Add "product1" to basket
```
1. Create an implementation

```
    @Step("Add \"product\" to basket")
    public void implementation13(Object arg0) {
        System.out.println(arg0);
    }
```
1. Refactoring does not complete successfully

**Version**

```
Gauge version: 0.6.1.nightly-2016-07-25

Plugins
-------
csharp (0.9.1.nightly-2016-07-25)
html-report (2.1.1.nightly-2016-07-20)
java (0.5.1.nightly-2016-07-25)
ruby (0.3.1.nightly-2016-07-25)
```

**Comment by zabil** [comment]
>     @Step("Add \"product\" to basket")

Not adding refactoring support for this format
