### ISSUE TITLE
Screenshot is not taken for RemoteWebDriver instance while tests running on linux headless machine

### ISSUE THREAD

**Issue by saritapol13** [getgauge/gauge#490]
### Expected behavior
Screenshot should be taken and no error should come

### Actual behavior
Failed to take regular screenshot: headless environment[runner: 1] 

### Steps to reproduce
We are using Selenium server standalong 2.53.0 jar
We are using selenium grid in which all runners are linux machines with GUI configured and code where the tests runs is non gui linux machine(headless)

EventFiringWebDriver browser = (EventFiringWebDriver) MultiBrowser.getActiveBrowser();
WebDriver augmentedDriver = new Augmenter().augment(browser.getWrappedDriver());
return ((TakesScreenshot) augmentedDriver).getScreenshotAs(OutputType.FILE);

This setup works well when we just run using standalone code of selenium webdriver.
When we run gauge specs using the same its gives exception and doesnt take the screenshot

default.properties have below values:
# default.properties
gauge_reports_dir = reports
overwrite_reports = false
screenshot_on_failure = true
logs_directory = logs
plugin_connection_timeout = 30000

### Gauge version
Gauge version: 0.3.2

Plugins
-------
html-report (2.0.0)
java (0.3.4)

**Comment by apoorvam** [comment]
Hi @saritapol13,

Can you try the following?

* Have gauge installed in the remote machine and try running tests?
* If you don't want to install Gauge in it, you can use custom screenshot,
as described here
<http://getgauge.io/documentation/user/current/language_features/custom_screenshots.html>
and
then run specs.

For reference, you can check out the sample Gauge project here
<https://github.com/apoorvam/gaugeGrid> which runs gauge specs using
Selenium Grid.

Let us know how it works.

Cheers,
Apoorva

**Comment by apoorvam** [comment]
Hi @saritapol13,

Can you try the following?
* Install Gauge in the remote machine and try running tests?
* If you don't want to install Gauge in it, you can use custom screenshot, as described [here](http://getgauge.io/documentation/user/current/language_features/custom_screenshots.html) and then run specs.

For reference, you can check out the sample Gauge project [here]
(https://github.com/apoorvam/gaugeGrid) which runs gauge specs using Selenium Grid.

Let us know how it works.

**Comment by saritapol13** [comment]
Hi,

We dont want to install Gauge on the runners.

I tried with cutom screenshot and its working well.

Thanks,
Sarita

**Comment by apoorvam** [comment]
Good to know its working. Closing this for now :)
