### ISSUE TITLE
Portable Gauge installer for Windows

### ISSUE THREAD

**Issue by Buthrakaur** [getgauge/gauge#491]
Current Gauge version is released just as a standard executable installer, which makes it hard to use Gauge in some CI environments, where different Gauge versions are necessary between independent test/dev projects. It would be nice to release also standalone portable package (ZIP file) and everyone could choose installer or portable package depending on his needs.

**Comment by mahendrakariya** [comment]
As of Gauge 0.6.2, zip files are available on Github on the [releases](https://github.com/getgauge/gauge/releases) page.
