### ISSUE TITLE
[Feedback needed] Gauge

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#493]
Please give us your inputs and help us understand your use-cases better.

**Features in Gauge that you like**
- Please tell us why you like it

**Features in Gauge that you would want to be improved**
- Please tell us more about your experience and what needs to be improved

**Features you think Gauge can do without**
- Please let us know if you have come across a feature that did not seem useful to you.

**Comment by gemunulk** [comment]
**Features in Gauge that I like:**
- Table Driven execution, Tagged execution, Parallel execution and Report Generation are really nice, useful and like them very much.

**Features in Gauge that you would want to be improved:**
- [ ] It would be great to have the feature run tests specifying multiple row numbers which are not adjacent. E.g. gauge --table-rows "4, 6" test_user.spec. (Just like in tagged execution gauge --tags "tag1, tag2" specs)

- [ ] I would love to run steps in a single spec, parallelly; providing a table at the setup. In that way I could save execution time for different inputs red from the csv table.

- [ ] Currently I could only specify a single .csv as table parameter. Would be great to have multiple csv in one spec.

> Wonderful project. Cheers!!

**Comment by sguptatw** [comment]
@gemunulk : Thank you for your feedback. 

I have created separate cards for each of the improvements suggested so that we can discuss and track them separately.
1. [To run specific table rows](getgauge/gauge/issues/495)
2. [To parallelize data table execution](getgauge/gauge/issues/496)
3. [Multiple csv parameters](getgauge/gauge/issues/497)

Thanks again.

**Comment by gemunulk** [comment]
@sguptatw Thank you very much.

**Comment by haroon-sheikh** [comment]
@sguptatw Firstly, Thank you all for great work that's going to make gauge better. I'm promoting gauge not on within my department but throughout Sky departments.

In terms of features I would like to see in the roadmap:

- regex mapping of steps (similar to cucumber) to remove duplication of steps as well as reduce number of aliases.
- Customisation of html reports

In terms of releases, It would really good if any breaking changes are released then these are communicated to a user list. i.e. when 0.8 was released a lot of people had issues as it wasn't backward compatible.

Also it would really be helpful if there was a roadmap for everyone to see. Something like this https://trello.com/b/9tcaMB4w/monzo-transparent-product-roadmap. Maybe we could make more use of the project board on github https://github.com/getgauge/gauge/projects/1. It would encourage a lot of people to contribute as it's visually easier to identify things that are to do and in progress.

**Comment by sguptatw** [comment]
@haroon-sheikh Thanks for your feedback. 

I have created separate 2 cards for the features suggested so that we can discuss and track them separately.
* [Customization](https://github.com/getgauge/html-report/issues/131) of html reports
* [Regex mapping](https://github.com/getgauge/gauge/issues/580) of steps. 

Thanks again
