### ISSUE TITLE
To run specific table rows during Data driven execution

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#495]
Created from the feedback received on getgauge/gauge/issues/493
It would be great to have the feature run tests specifying multiple row numbers which are not adjacent. E.g. gauge --table-rows "4, 6" test_user.spec. (Just like in tagged execution gauge --tags "tag1, tag2" specs)

**Comment by apoorvam** [comment]
This enhancement should be available with nightly >= 29.11.2016

Better log messages? Please suggest.
