### ISSUE TITLE
Getting 404 page on this link 

### ISSUE THREAD

**Issue by shashisd** [getgauge/gauge#498]
http://getgauge.io/documentation/user/current/getting_started/project_structure/configuration.md 

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Gauge version
```
Run gauge -v on your system and paste the results here.
```

**Comment by sguptatw** [comment]
@shashisd : Thank you for reporting the issue.
This page is currently available at /documentation/user/current/getting_started/project_structure/

We are looking into the issue of redirecting the user to the new page automatically.

**Comment by sguptatw** [comment]
This issue was moved to getgauge/documentation#65
