### ISSUE TITLE
Allow users to configure types for ContinueOnFailure

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#499]
Currently (thanks to #255 ), users can configure `Steps` such that they do not break on failure. This is done via an Annotation/Attribute in Java/C# or as a configuration in Ruby/Javscript.

Allow users to specify what type of errors should be honoured in such cases.

To be considered:
- Java assertion frameworks throw errors derived from `java.lang.assertionerror`, allowing Gauge to differentiate assertion errors. There isn't a similar language provided assertion exception in C#.
- Consider allowing a whitelisting mechanishm as @thunderforge [suggests](https://github.com/getgauge/gauge/issues/255#issuecomment-232194318).
- [x] Java getgauge/gauge-java#66
- [x] Ruby
- [x] CSharp

**Comment by sguptatw** [comment]
Continue on failure is implemented. The details of the feature is available at https://docs.gauge.org/latest/writing-specifications.html#continue-on-failure
