### ISSUE TITLE
Plain binary download

### ISSUE THREAD

**Issue by tobyclemson** [getgauge/gauge#501]
Is there any plan in the future or reason why it would not be possible to provide a plain binary download for gauge?

I like my codebase to take care of as many of its dependencies as possible so that I can ensure consistent versions across workstations and CI. Being able to download binaries for my platform rather than relying on platform specific installs allows me to do this very easily and vendor those binaries within each project.

This is the approach most of the hashicorp tools take (e.g., terraform, packer).

Is there any way to do this today with Gauge? Is there anything I can help with to make it possible?

**Comment by sriv** [comment]
Currently, only linux downloads are available independent of installer/package manager, but it should be fairly straightforward to make them available for other platforms.We generate the files in the build process and then package them into `pkg` or `exe` installers. This could be another alternative that we could generate and publish.

@Buthrakaur has raised [an issue](https://github.com/getgauge/gauge/issues/491) specifically for windows installers.

Note that in the current form, Gauge requires certain files to be present along with the install (ex `skel` folder for creating project skeleton). So a single binary download would require some additional work.

@tobyclemson - would you be interested in sending a PR?

**Comment by tobyclemson** [comment]
I think it is ok if what gets downloaded is a zip containing binaries and other requirements, so long as I can vendor the entire contents of that zip file and then manage my PATH for the contained binary.

@sriv I'm happy to work on a PR but would be great if you could point me in the right direction.

**Comment by mahendrakariya** [comment]
As of Gauge 0.6.2, binaries are available on Github on the [releases](https://github.com/getgauge/gauge/releases) page.
