### ISSUE TITLE
Methods implementing an interface marked as a step gives duplicate step definition error

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#502]
Currently there is a technical limitation. Methods of an interface implementations marked as steps gives duplicate step error. Do you think  we should address this?

**Comment by sriv** [comment]
Which language runner did you check this with? Ideally the annotations should be on the implementation, and not the interface.

**Comment by sguptatw** [comment]
In Java, Yes the annotation is on the Methods of interface implementations. Since there are more than one, getting the duplicate step error.

**Comment by apoorvam** [comment]
I think the `@Step` annotation should be present on method implementation only, not on interface methods. Closing this for now. Please re-open if we need to consider this.
