### ISSUE TITLE
Unable to run tests from CLI when Step implementations are defined in external JARs

### ISSUE THREAD

**Issue by richfay** [getgauge/gauge#504]
Some background: Our test project is built containing only specs + concepts, with the step implementations being imported as JARs built in a different project. We are able to run these with no issues from the Gauge IntelliJ plugin.

### Steps to reproduce
- Attempt to run tests on CLI via "gauge specs/" (or any runner permutation)

### Expected behavior
- Properly written tests should not be skipped

### Actual behavior
- All step implementations are unable to be found

### Gauge version
```
Gauge version: 0.6.1

Plugins
-------
html-report (2.1.1)
java (0.5.0)

```

**Comment by sriv** [comment]
When running via the CLI, you need to set [`GAUGE_ADDITIONAL_LIBS`](http://getgauge.io/documentation/user/current/language_features/configuration.html#gaugeadditionallibs) env var to the location of the jar. If the location is pre-determined and consistent across machines/environments, you could include this setting in your project's `env/<env>/<any>.properties`

The Intellij plugin does this automatically. Hence you might see this working via Intellij+Gauge.

**Comment by richfay** [comment]
Yup that fixed it, thanks for pointing that out!
