### ISSUE TITLE
Extract to concept: Extracting with a new file without extension not completing the action

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#506]
### Expected behavior
Should be able to extract to a new file by specifying the name without extension

### Actual behavior
The user has specified name without extension. The steps are replaced by the concept name, the new concept file is being created. However it is not recognized as a concept and that is still marked as unimplemented.

### Steps to reproduce
1. Create a spec
```
A basic spec has only scenarios
===============================

tags: spec

* In an empty directory initialize a project named "spec_with_passing_scenarios" without example spec

basic spec with one scenario, passing
-------------------------------------

* Create "Sample scenario" in "Basic spec execution" with the following steps 

     |step text               |implementation                                          |
     |------------------------|--------------------------------------------------------|
     |First step              |"inside first step"                                     |
     |Second step             |"inside second step"                                    |
     |Third step              |"inside third step"                                     |
     |Step with "two" "params"|"inside step with parameters : " + param0 + " " + param1|

* Execute the current project and ensure success
* sdf
```
2. Give the implementations to all steps except `sdf`
3. Select `Execute the current project and ensure success` and `sdf`. Extract to concept.
4. Choose new file `without extension`.
The user has specified name without extension. The steps are replaced by the concept name, the new concept file is being created. However it is not recognized as a concept and that is still marked as unimplemented.

### Gauge version
```
Gauge version: 0.6.2.nightly-2016-09-02

Plugins
-------
csharp (0.9.1.nightly-2016-08-12)
html-report (2.2.0.nightly-2016-08-28)
java (0.5.1.nightly-2016-08-18)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```
IntelliJ
```
gauge-java-intellij-0.2.4.nightly-2016-09-05
```

**Comment by kashishm** [comment]
This issue was moved to getgauge/Intellij-Plugin#191
