### ISSUE TITLE
Extract to concept: Incomplete extraction if path does not exist

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#507]
### Expected behavior
If the path does not exist, I should either get an error or it should create the required folder structure.

### Actual behavior
The extraction is incomplete. The concept name is replaced but the concept is not created

### Steps to reproduce
1. Create a spec
2. Select steps for extraction
3. In the dialog box specify a new path example /specs/<new folder>/abc.cpt
4. The path does not exist, the extraction is incomplete.

### Gauge version
```
Gauge version: 0.6.2.nightly-2016-09-02

Plugins
-------
csharp (0.9.1.nightly-2016-08-12)
html-report (2.2.0.nightly-2016-08-28)
java (0.5.1.nightly-2016-08-18)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```
IntelliJ
`gauge-java-intellij-0.2.4.nightly-2016-09-05`

**Comment by kashishm** [comment]
This issue was moved to getgauge/Intellij-Plugin#195
