### ISSUE TITLE
[Test Case] Expand/Collapse of scenarios and concepts

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#511]
**Test Cases for expand/collapse for scenarios**
- [ ] Should expand/collapse one scenario in specification 
- [ ] Should expand/collapse with inline data table in the last step
- [ ] Should expand/collapse with tags
- [ ] Should expand/collapse with comments
- [ ] Should expand multiple scenarios in a specification 
- [ ] Should not expand/collapse context steps in a scenario
- [ ] Should not expand/collapse last scenario with tear down steps
- [ ] Should expand/collapse with inline data table as the parameter to the last step in the file
- [ ] Formatting works even after the scenarios are collapsed

**Test cases for expand/collapse for concepts**
- [ ] Should expand/collapse one concept in a concept file
- [ ] Should expand/collapse multiple concepts in a concept file with new line spaces between concepts
- [ ] Should expand/collapse multiple concepts in a concept file without new line spaces between concepts
- [ ] Should expand/collapse with inline data table as the parameter to the last step in the file
- [ ] Formatting should work even after the concepts are collapsed. Formatting is not yet implemented for concepts.

**Comment by sriv** [comment]
Is this a meta issue? If so, I'd recommend logging issues in respective IDEs for every item and linking them.

**Comment by sguptatw** [comment]
Just thought it will be useful to have one meta issue. So that if and when it is picked in other IDEs we know what to expect. Shall I create another issue in individual IDE plugin?

**Comment by sriv** [comment]
Yes please, that would help us track implementation in the IDEs

**Comment by sguptatw** [comment]
Tracking this separately https://github.com/getgauge/Intellij-Plugin/issues/198
