### ISSUE TITLE
Refactoring removes nested tables

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/gauge#512]
### Expected behavior

If there are nested tables, refactoring should retain it.
### Actual behavior

Refactoring removes nested tables.
### Steps to reproduce
- Create a spec which has a step with a nested inline table. Something like this.

```
* Console should contain following lines in order 

     |console output                        |
     |--------------------------------------|
     |inside step with parameters : |header||
     ||one   |                              |
     ||two   |                              |
```
- Refactor this spec file
### Gauge version

```
Gauge version: 0.6.2

Plugins
-------
html-report (2.1.1)
java (0.5.1)
ruby (0.3.1.nightly-2016-07-25)
xml-report (0.1.3)
```

**Comment by sguptatw** [comment]
As per this syntax, won't this be considered as 3 separate rows? Is there a way to represent multiline values as a single value?

**Comment by sriv** [comment]
@sguptatw - is this relevant? Not sure if there was a decision on what is the expected outcome.

**Comment by sguptatw** [comment]
Currently nested tables are not supported. Hence this issue is not relevant.
