### ISSUE TITLE
Table parameter data types

### ISSUE THREAD

**Issue by mayask** [getgauge/gauge#513]
### Expected behavior

I want table to not only support string data, but also `int` and `bool`. I don't know how you achieve this in the current version, but I find it quite frustrating that you can't represent data in different types.

As a workaround I introduce an extra `type` column describing data types.

```
    | field              | value                | type           |
    |--------------------|----------------------|----------------|
    | pid                | PID-123              |                |
    | profile_level      | newbie               |                |
    | name               | James Bond           |                |
    | allow_bonus        | true                 | boolean        |
    | front_end_id       | 1234567              |                |
    | score_adjustment   | 1                    | integer        |
```

and convert types by hand.

My proposal should be to use quotes for strings. This would help recognize truthy values like `true` or `false` and use numbers.

```
    | field              | value                |
    |--------------------|----------------------|
    | pid                | "PID-123"            |
    | profile_level      | "newbie"             |
    | name               | "James Bond"         |
    | allow_bonus        | true                 |
    | front_end_id       | "1234567"            |
    | score_adjustment   | 1                    |
```
### Actual behavior

All data in table parameters are returned as `string` type.
### Steps to reproduce
1. Define step table parameter with values in different types.
2. Try read table data.
3. All data is represented in strings. 
### Gauge version

```
Gauge version: 0.5.0

Plugins
-------
html-report (2.1.1)
js (1.2.1)
```

**Comment by zabil** [comment]
This would be hard to implement in a way that's backward compatible and same across languages that's supported by Gauge.
