### ISSUE TITLE
Need to be able to use steps that take a data table as a parameter in concepts.

### ISSUE THREAD

**Issue by dylanmcguire** [getgauge/gauge#514]
We have many steps that take a data table as a parameter. We would like to be able to include these steps in concepts.

### Gauge version
0.6.1

**Comment by dylanmcguire** [comment]
I see this has already been raised in issue 365.

**Comment by mahendrakariya** [comment]
@dylanmcguire Like you mentioned, this is a duplicate issue. So I am closing it. The progress can be tracked at #365.

**Comment by dylanmcguire** [comment]
I haven't seen any movement on this issue in issue #365 and after closer inspection I think we may actually be making different requests. It appears that issue #365 is about allowing the input of a concept to be driven by contents of a data table. That is not what we are asking for. What we need is for a concept to be able use a step that takes a data table as a parameter. We have many steps that use this parameter type and we need to be able to include those steps in our concepts.

**Comment by mahendrakariya** [comment]
@dylanmcguire Gauge already supports this. You can have steps with table params in a concept. Except that there is a bug (#524) due to which table header underlines are being parsed as table rows. We will be fixing it soon.
