### ISSUE TITLE
OSX Sierra / Golang runtime Issues

### ISSUE THREAD

**Issue by steve-gray** [getgauge/gauge#518]
On my OSX Sierra machines gauge fails pretty horribly most of the time. The suite runs fine on non-OSX machines, and Googling the errors appears to indicate it's a known Golang issue and one they've patched around.

References:
- https://github.com/golang/go/issues/17570
- https://github.com/BramGruneir/go/commit/37c90ab73eb20126a4a9698191afccf3881d32d5

What version of the runtime does Gauge use?
### Expected behavior

gauge should run reliably on OSX Sierra.
### Actual behavior

Intermittent random crashes due to Golang runtime issues on Sierra. For example:
- Failure to start (often requires several runs)
- Random crashes during plugin execution
- Errors such as:

`failed MSpanList_Insert 0x615000 0x7d13a971b398 0x0 0x0
        fatal error: MSpanList_Insert
        mach error semaphore_signal: 15
        fatal error: mach error`
### Steps to reproduce
1. Install OSX Sierra
2. gauge init java
3. gauge specs
### Gauge version

0.62

**Comment by apoorvam** [comment]
@steve-gray Yes, it's a known Golang issue and they have patched it. Our nightly releases are compiled using the latest version of Go(1.7.3). You can download appropriate Gauge installer from [here](https://bintray.com/gauge/Gauge/Nightly) and install. This is working fine for us.

You might also have to install the nightly releases of other plugins that you would be using like Gauge-Java, Html-report etc. You can find them [here](https://bintray.com/gauge).
Let us know how it goes.

**Comment by apoorvam** [comment]
@steve-gray Any updates on this?

**Comment by steve-gray** [comment]
It runs fine: I'd held off waiting for an official fix before yelling out to use the dailies for people as that's utterly terrible practice.

Is there some technical reason someone can't update the build script and trigger the CI/CD processes and get this in people's hands?

**Comment by apoorvam** [comment]
Right, we'll be releasing it soon. 

But at the moment, we have some work in progress related to Gauge API. With just Gauge-core released, the plugins will not be compatible with Gauge. We'll have to make changes to plugins as well reflecting the API changes.

**Comment by apoorvam** [comment]
Hey @steve-gray We have released a new version of Gauge. i.e. v0.7.0
Download latest version of Gauge from [website](http://getgauge.io/get-started/index.html) or install from brew/choco as: 
```
choco upgrade gauge
brew upgrade gauge
```

With this, this issue can be closed.
