### ISSUE TITLE
Not closing all browser instances even after completing the run

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#522]
Should close all browsers after running

The link to the project is https://github.com/getgauge/gauge-test-apps/tree/master/projects
run from web-apps-e2e.

![not_closing_all_server_instances](https://cloud.githubusercontent.com/assets/6310197/20047942/e6ddb8d0-a4de-11e6-923a-c95a1593b717.png)

**Comment by sriv** [comment]
Is this a Gauge issue? Works for me on macOS.

Gauge Version:

```
Gauge version: 0.6.3

Plugins
-------
csharp (0.9.2)
docker-ruby (0.0.1)
go (0.0.1)
html-report (2.1.1)
java (0.5.0)
js (1.2.1)
m2h (0.0.1)
ruby (0.3.1)
xml-report (0.1.2)
```
