### ISSUE TITLE
Gauge exit status should be zero in case of skipped scenarios

### ISSUE THREAD

**Issue by apoorvam** [getgauge/gauge#523]
If there are 3 scenarios and one of it has an unimplemented step, one scenario gets skipped with validation error and the rest get executed. However, the exit code of `gauge` is non-zero. 

Say I have a few scenarios with no steps in it and I execute all specs on CI, the build fails since there is a scenario skipped. This should be giving zero exit code.

**Comment by sguptatw** [comment]
How should the specs with parse errors get treated?
**Observation**
[ParseError] <path>:<linenumber> Spec does not have any elements => ''
gives exit code 1

No steps found in scenario is not getting marked as a parse error and is giving exit code 0.
There should be consistency in the exit codes.

**Comment by sriv** [comment]
This issue handles that the exit code is zero if there are skipped specs. What should be a parse error is addressed as part of #532. More scenarios can be added to it, if required.

**Comment by sguptatw** [comment]
Yes, this is about the exit code.
When there this specific a parse error, we are getting an exit code of 1 instead of 0.

**Comment by apoorvam** [comment]
Fixed as part of issue #532 

Fix should be available in nightly >= 24.1.2017

**Comment by sguptatw** [comment]
This is no longer valid, as the parse errors will now have a non-zero exit code.
