### ISSUE TITLE
Underlines in table header in concepts is being considered as a table row

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/gauge#524]
### Actual behavior
When some step in a concept uses a table param, the underlines in table header is being considered as a table row.

### Expected behavior
Table headers in concepts should be parsed properly.

### Steps to reproduce
  * Create a concept as below.
```
# Concept with step using tables and use it in some spec.

* Almost all words have vowels
     |Word  |Vowel Count|
     |------|-----------|
     |Gauge |3          |
     |Mingle|2          |
     |Snap  |1          |
     |GoCD  |1          |
     |Rhythm|0          |
```
  * Run `gauge specs`
  * The header underlines (`|------|-----------|`) are getting parsed as table rows.

### Gauge version
```
Gauge version: 0.6.3

Plugins
-------
go (0.0.1)
html-report (2.2.0)
java (0.5.1)
xml-report (0.1.3)
```

**Comment by mahendrakariya** [comment]
Fix available in nightly >= 2016-11-16

**Comment by sguptatw** [comment]
@mahendrakariya - The corresponding Nightly is not yet available.

**Comment by mahendrakariya** [comment]
@sguptatw It's available now!
