### ISSUE TITLE
Allow dynamic parameters inside of data table in concepts

### ISSUE THREAD

**Issue by dylanmcguire** [getgauge/gauge#525]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
Need to be able to create a concept of the form.

> #Choose the \<proejctName\> project on the \<itemBankName\> item bank.
> * Click "Home" link
> * Click \<itemBankName\> link
> * Select "Manage Item Bank" tab
> * Click button with tooltip "edit" for row
>       |Name                |
>       |------------------|
>       |\<projectName\>|

### Gauge version
```
0.6.1
```

**Comment by jtlee** [comment]
I expected this feature to already be part of concepts. It would be so much more useful if I could create a concept like this:
# send <size> <price> …
* send …
|FIELD|VALUE|
…
|size|<size>|
|price|<price>|

**Comment by televox** [comment]
This issue is a feature I need.
Please raise your priority and apply.
^.^

**Comment by kashishm** [comment]
Fix will be available in nightly >= 25-07-2017.

**Comment by sguptatw** [comment]
Known issue - getgauge/gauge#743
