### ISSUE TITLE
Unable to create new project using init - "Failed to find project directory issue"

### ISSUE THREAD

**Issue by NaveenJonty** [getgauge/gauge#526]
Post setting up gauge and language runners (java), tried running the guage init --java
Ideally new project should be initialized, instead face 
"Failed to find project directory" issue.

Tried searching the documentation and issues, but didnt find a working solution. 

**Existing version of gauge and plug-ins**
```
gauge -v 
Gauge version: 0.6.2

Plugins
-------
java (0.5.0)
```

**Comment by mahendrakariya** [comment]
@NaveenJonty I tried running `gauge --init java` and things are fine on my end. Could you please give us detailed steps to reproduce the issue? It would be great if you could also mention the OS on which you are facing this issue.

**Comment by NaveenJonty** [comment]
@mahendrakariya - Thanks for the response.

The command works for few others in my team, but doesn't my system (Mac)
Are there any environment variables that need to be set ?

Steps for reproducing is just running gauge init --java

I am keen to understand if anyone faced this issue the first time. It may not be a common issue ...maybe related to some specific setup/configuration.

**Comment by mahendrakariya** [comment]
@NaveenJonty That's strange. Could you please run `gauge --log-level=DEBUG --init java` and post the output that you see on your terminal?

**Comment by zabil** [comment]
@NaveenJonty did you mean
```
$ guage init --java
```
or
```
$ guage --init java
```

**Comment by NaveenJonty** [comment]
Got it Zabil ....trying to recall, on how did I try --java....:(
