### ISSUE TITLE
[Feature/Improvement] Internationalization of the eco-system

### ISSUE THREAD

**Issue by boazberman** [getgauge/gauge#527]
Hey, I'm a big fan of gauge, and as such I would like to use it for my project.
But, as a native Hebrew speeker, my company would not have all of the benefits of using gauge, since it supports English only (As though one can write tests in different language to some degree).
Is there plans to support different languages?
Also, given that Hebrew is written right to left, some more work is needed in the lets say html plugin.
I would be thrilled to help with the coding, but I would appreciate some direction and help.
Thanks!

**Comment by sriv** [comment]
Hey there @boazberman - thanks for raising this.

So, Gauge supports UTF-8 for authoring specs, and this enables users to write specs on non-latin characters as well. Here is an [example gist](https://gist.github.com/sriv/622909dbacd32f79d2d22f1981b2c641) to illustrate specs written in Hindi.

But RTL language support will require some changes, HTML report needs to change for sure. But I suspect that we might have to change Gauge Core + Language runners to accommodate parameters written from RTL, since Gauge depends on parameter positions. 

IDE plugins need to be aware of RTL languages as well, since features like AutoComplete etc, will have to address this.

I think this requires some analysis and we will do some study and post sub-issues, treating this as a master issue. What do you say?

We will surely need and appreciate all the help we can get, since none of us are conversant in any Right-Left languages :(

**Comment by boazberman** [comment]
First of all, Thanks for the quick response!

> accommodate parameters written from RTL
I don't think that is required since parameters are to be always written in English.

More to think of:

- Saved Words like "tags" that is marking tags and need to be translated

Also I've tried using gauge with Hebrew on my computer (With the latest build of the Java runner & html-report) and It seems that the runner is fully supporting this, and mostly the html-report is requiring some implementation.
Main chanllenge: How to allow language configuration throught the gauge eco-system?

**Comment by sriv** [comment]
@boazberman - So, the way Gauge interprets parameters is via positions. i.e.

Say we have this step:

    * Say "hello" to "gauge"

And its implementation as :

```

@Step("Say <what> to <whom>")
public void sayHello(String a, String b)
{
    System.out.println(a + ", " + b);
}
```

the mapping of parameters works like this: `a` holds the first value (i.e. "hello") and `b` holds "gauge".

Now, in Hebrew this would look something like:

<pre dir='rtl'>
* להגיד "שלום" כדי "מד" 
</pre>

[**Disclaimer**: I used [google translate](https://translate.google.com/#auto/iw/Say%20%22hello%22%20to%20%22gauge%22), so I wash my hands off any mistakes!]

I am not sure if this is how you would use it in your specs, but essentially, the order of parameters in the step annotation and the java method need to be same. Please correct me if this assumption is mistaken.

> Main chanllenge: How to allow language configuration throught the gauge eco-system?

I would imagine something like a property `gauge_locale=he-IL` could be of help. Gauge (and plugins such as html-report) would then need to respect this locale. What do you say?

Defninitely agree that the html-report needs quite a bit of tweaking to enable this.

**Comment by boazberman** [comment]
@sriv Thanks for the quick response! The translation is good enough, but I can't seem to understand where is the problem with the parameters mapping. Even though it's rtl, parameters still have order. I mean what comes first still comes first... 
As in your example the first parameter would be "שלום" as for it is the first parameter in the sentence.

**Comment by sriv** [comment]
@boazberman - I guess my confusion is this - would you expect someone authoring specs in Hebrew to 

- write java code (which is English) keeping in mind the order?
- reuse step implementations between english and hebrew, and which would hence cause some confusion?

All this is due to my ignorance of usage of RTL languages, so pardon me if I am missing something obvious.

**Comment by boazberman** [comment]
Well when writing the Java code there is a need to keep in mind the order of the parameters and since parameters names are written in English some IDEs would cause some bad time. But in eclipse for example I've tried writing a step with Hebrew and it worked. Hence I'm saying this is not a problem. 
For example:

@Step("להגיד <what> כדי <whom>")
public void sayHello(String a, String b)
{
    System.out.println(a + ", " + b);
}

Is working when the step used as
* להגיד "שלום" כדי "מד"

**Comment by sriv** [comment]
@boazberman - excellent, thanks for the explanation. In this case I will create an issue in getgauge/html-report to add this support, since I guess that is the only thing limiting your use of Gauge.

If you think there is any change/enhancement required in Gauge/Language runner, please do let us know. Thanks.

**Comment by boazberman** [comment]
@sriv As I mentioned, the use of tags is with an English word, which is the only place where I would have to use English in the specs, therefor a translation would be great!

**Comment by boazberman** [comment]
I've spent the last hour trying to compile the latest version of html-report on my computer and it keeps on failing... So I'm having an hard time running the hebrew specs I wrote.

This is what I'm getting:

> D:\Projects\github.com\getgauge\html-report>go run build/make.go
2016/12/09 18:35:33 Execute [go build -o bin\windows_amd64\html-report.exe]
htmlReport.go:27:2: cannot find package "github.com/getgauge/common" in any of:
        D:\Installs\Go\src\github.com\getgauge\common (from $GOROOT)
        D:\Projects\github.com\getgauge\html-report\src\github.com\getgauge\common (from $GOPATH)
htmlReport.go:28:2: cannot find package "github.com/getgauge/html-report/gauge_messages" in any of:
        D:\Installs\Go\src\github.com\getgauge\html-report\gauge_messages (from $GOROOT)
        D:\Projects\github.com\getgauge\html-report\src\github.com\getgauge\html-report\gauge_messages (from $GOPATH)
htmlReport.go:29:2: cannot find package "github.com/getgauge/html-report/generator" in any of:
        D:\Installs\Go\src\github.com\getgauge\html-report\generator (from $GOROOT)
        D:\Projects\github.com\getgauge\html-report\src\github.com\getgauge\html-report\generator (from $GOPATH)
htmlReport.go:30:2: cannot find package "github.com/getgauge/html-report/listener" in any of:
        D:\Installs\Go\src\github.com\getgauge\html-report\listener (from $GOROOT)
        D:\Projects\github.com\getgauge\html-report\src\github.com\getgauge\html-report\listener (from $GOPATH)
panic: exit status 1
> 
> goroutine 1 [running]:
panic(0x50d900, 0xc042004300)
        D:/Installs/Go/src/runtime/panic.go:500 +0x1af
main.runProcess(0x517b81, 0x2, 0xc04202deb8, 0x3, 0x3)
        D:/Projects/github.com/getgauge/html-report/build/make.go:204 +0x173
main.compileGoPackage(0x518fa2, 0xb)
        D:/Projects/github.com/getgauge/html-report/build/make.go:215 +0xa9
main.compile()
        D:/Projects/github.com/getgauge/html-report/build/make.go:77 +0x5a
main.main()
        D:/Projects/github.com/getgauge/html-report/build/make.go:69 +0x66
exit status 2

**Comment by sriv** [comment]
Sorry to hear that you are facing hurdles installing from source. 

Can you try something else please?

- Download HTML report nightly build from [here](https://bintray.com/gauge/html-report/Nightly/2.2.0.nightly-2016-12-06)

- run `gauge --install html-report -f <path_to_zip>`

- run gauge specs

**Comment by mahendrakariya** [comment]
@boazberman Did you run `go get --all` or `go get ./...` from the html report project root before building? If not, could you please try it and build again?

**Comment by boazberman** [comment]
@mahendrakariya it did not work as well, I will just use the nightly zip.
Sorry guys but I'm having a busy month. I'll get back on it ASAP. Thanks again for you willingness to support hebrew!

**Comment by apoorvam** [comment]
@boazberman In case you want to build from source:

From the logs it look like you have set GO_ROOT = `D:\Installs\Go` which is Golang install location. The Golang workspace should have structure as:
```
$GO_PATH(In your case, this is `D:\Projects`)
     - src 
         - github.com
               - getgauge
                     - html-report (This is your clone of html-report)
     - bin
     - pkg

```

You can do a `go get ./...` in directory `html-report` to get all dependencies. 

Build:
```
go run build/make.go
```

**Comment by boazberman** [comment]
Hey, @mahendrakariya & @sriv  & @apoorvam , I've just created a repository and translated the default init project of gauge to Hebrew (which is an rtl) language.
You can find it here: [https://github.com/boazberman/gauge-rtl]
Take into account that currently the tests are not passing due to the fact that it reads the parameters in the wrong order.
For the first step:
* המילה "גואג" מכילה "2" אמות קריאה.
if read in rtl the first parameter is "גואג" and the second is "2" but it is interpreted the other way around. Same happens in the table.
Currently this is a major problem, and a blocker for rtl.
Also, you can notice that the safe word "tags" is the only thing that must be kept in English, hurting the fluent of the specification.
Thanks!

**Comment by boazberman** [comment]
ping @sriv @mahendrakariya @apoorvam ?

**Comment by apoorvam** [comment]
@boazberman Sorry for the late response, was held up with something.

I forked your translated gauge-template in RTL langauge. Specs passed after changing the accessor fields in table. Ref: [Pull Request](https://github.com/boazberman/gauge-rtl/pull/1/commits/c58da3a52c618caabe7c777e32eed71a3255851e)

I'm little confused of how the spec is written in RTL. Is this the actual way that you have written spec? (Screenshot attached)

![screen shot 2017-01-11 at 11 27 06 am](https://cloud.githubusercontent.com/assets/8859725/21837339/6a402880-d7f1-11e6-998f-df4060fd4434.png)

When I open it in say, VS Code it shows me in left to right. However the specs are passing. But Textedit is showing me as the screenshot above. Not sure of who is handling RTL correctly.

Can you please give more details on if the way that spec is currently written and implemented is the expected way you write in Hebrew/any RTL language? 
What you think is still missing to add this support? Rendering in reports?

**Comment by boazberman** [comment]
Well the screen shot is presenting the Hebrew properly. In my machine I have an exception concerning the step
> המילה "גואג" מכילה "2" אמות קריאה. 

Where to in my memory it parsed the parameters in the wrong order and tried casting גואג to introduce instead of parsing 2. I've ran it with the latest version of gauge and gauge-java

**Comment by boazberman** [comment]
I'll check it again tomorrow, can't today.

**Comment by boazberman** [comment]
Thanks @apoorvam it totaly worked! I've taken the time to translate the html-report generated to hebrew (and make it rtl friendly). I would be gratefull if you could take a look and allow further integration of this changes into html-report.
The tricky thing would be translating saved words such as "Tags" which is also in the spec files.

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
