### ISSUE TITLE
Steps with enum parameter marked as continueOnFailure is not working as expected

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#528]
**Expected Behavior**
If a step is marked as continueOnFailure(COF) the next step should get executed even if there is a failure in the current step.

**Actual Behavior**
Even if marked as COF on failure, the next steps are not getting executed.

**Steps to replicate**
1. Run the specs in the project.
[enumWithCOF.zip](https://github.com/getgauge/gauge/files/608023/enumWithCOF.zip)

2. Check the html report.
The next steps are not executed.

**Version**
```
Gauge version: 0.6.3.nightly-2016-11-06

Plugins
-------
csharp (0.9.2.nightly-2016-09-14)
html-report (2.2.0.nightly-2016-11-09)
java (0.5.1.nightly-2016-11-21)
js (1.3.0)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by mahendrakariya** [comment]
@sguptatw Gauge should allow `ContinueOnFailure` if the failure is on the functional side of things. In this case, Gauge is not even able to execute the functionality. It's a parameter conversion failure. In other words, the failure is on the language / implementation side. So even if the step is marked as `ContinueOnFailure`, the execution should ideally step here and the next steps should not get executed.

**Comment by sguptatw** [comment]
@apoorvam : I think this has to be documented along with COF.

**Comment by sriv** [comment]
Documented via https://github.com/getgauge/documentation/commit/16864a5f015f9ba1ff56be5ae277122190b7b5bc
