### ISSUE TITLE
Enum parameter populated from the table is not working as expected

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#529]
**Expected behavior**
Validations should continue to work with table(without the separator) parameters as input

**Actual behavior**
An empty value in such case is skipping the row instead of giving any validation error.

**Steps to replicate**
1. Run the specs in the project and check the html report. It is running only 2 rows.
[enumWithTable.zip](https://github.com/getgauge/gauge/files/608048/enumWithTable.zip)

Note: This behavior is the same when the csv file is used for datatable.

**Version**
```
Gauge version: 0.6.3.nightly-2016-11-06

Plugins
-------
csharp (0.9.2.nightly-2016-09-14)
html-report (2.2.0.nightly-2016-11-09)
java (0.5.1.nightly-2016-11-21)
js (1.3.0)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by mahendrakariya** [comment]
@sguptatw It would be great if you could add a sample spec so that we can easily reproduce this issue.

**Comment by mahendrakariya** [comment]
This is a weird issue. It's not just for enums, but for any blank rows, if table header underline is not present. I have created a new issue for this. Ref #530.
