### ISSUE TITLE
Support for return values from Step implementations

### ISSUE THREAD

**Issue by ColOfTheDead** [getgauge/gauge#531]
**Expected Behavior**

Gauge supports variables in steps in order to:

- Facilitate easier re-use of steps
- Reduce the tight coupling of specs to code
- Reduce the up-front design requirements on a test framework

**Actual Behavior**

```
* Create a new product "Virtual Machine" to the current order and store the product ID in <out:productID>
* Add the value-add product "Backup" to the product <productID>
```

You can of course do the above with data stores, but in a more complex test scenario with multiple products and having the test case link products on the order etc. such as in our complex Telco order management platform, it starts to require a lot of design in the test framework to get it right.

**Comment by boazberman** [comment]
+1 Since it will also make it easier to transform junit tests to gauge tests

**Comment by zabil** [comment]
Closing this for now in favor of the workaround using data stores so that the steps remain re-usable across scenarios.
