### ISSUE TITLE
No steps found in scenario should be marked as a parse error

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#532]
_From @sguptatw on November 30, 2016 10:10_

**Expected behavior**
The parse errors should be marked as [ParseError] in the result.

**Actual behavior**
`No steps found in scenario` is not marked as parse error

**Steps to replicate**
Create a spec
```
Specification Heading
=====================

|abc|
|def|

Scenario Heading
----------------
```
2. Run the specs and see the error

**Version**
```
Gauge version: 0.6.3.nightly-2016-11-29

Plugins
-------
csharp (0.9.2.nightly-2016-09-14)
html-report (2.2.0.nightly-2016-11-29)
java (0.5.1.nightly-2016-11-21)
js (1.3.0)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-10-27)
```

_Copied from original issue: getgauge/html-report#114_

**Comment by apoorvam** [comment]
Currently, if there is a parse error in any spec, the execution halts. 

Case 1: No scenarios in a spec
Case 2: No steps in scenario

In the above two cases, the spec/scenario is skipped. If these are made Parse errors, it will not be able to continue with execution. 

1. If there is a parse error in a spec, should we continue with execution of other specs?
2. Should Case 1 and 2 be considered Parse errors?

**Comment by sguptatw** [comment]
1. Ideally if there is a parse error in a spec, execution of other specs should not be affected.
Do you see a reason why it should not be so, apart from technical limitation if any?
2. A parse error is when the specification is not in the expected format. Going by that these are parse errors.

**Comment by Apoorva-GA** [comment]
If there are parse errors, now the execution continues with rest of the specs. The exit code in case of spec with no scenarios and scenario with no steps is handled. 

Fix should be available in nightly >= 24.1.2017

**Comment by sguptatw** [comment]
Getting a panic runtime error

```
[ParseError] /Users/sswaroop/work/gauge_git/test/specs/one.spec:7 Scenario should have atleast one step => ''
# Specification Heading1
  ## Scenario Heading	 ✔ ✔

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa338c]

goroutine 25 [running]:
panic(0x3173e0, 0x4205b20a0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
github.com/getgauge/html-report/generator.computeTableDrivenStatuses(0x4206b48a0)
	/tmp/src/github.com/getgauge/html-report/generator/transform.go:198 +0x1c
github.com/getgauge/html-report/generator.toSpec(0x4206b4840, 0x4206a9b30)
	/tmp/src/github.com/getgauge/html-report/generator/transform.go:191 +0x941
github.com/getgauge/html-report/generator.generateSpecDiv(0x4ea5a0, 0x4206a62e8, 0x4206b4840)
	/tmp/src/github.com/getgauge/html-report/generator/generate.go:378 +0x47
github.com/getgauge/html-report/generator.generateSpecPage(0x4206d6090, 0x4206b4840, 0x4ea5a0, 0x4206a62e8, 0x42071cd90)
	/tmp/src/github.com/getgauge/html-report/generator/generate.go:356 +0x29a
created by github.com/getgauge/html-report/generator.GenerateReports
	/tmp/src/github.com/getgauge/html-report/generator/generate.go:243 +0x3eb
```

**Comment by kashishm** [comment]
@sguptatw Cannot reproduce on latest nightly of Gauge and HTML-report.
