### ISSUE TITLE
Have a structured format for the errors

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#533]
An error, be it validation error or parse error, has to have a format with
- tag to indicate the kind of error. 
- specification/concept name along with the line number name where the error occurs.
- error message.

Ideally, the errors belonging to a given spec should be listed together.

**Comment by apoorvam** [comment]
With [this](https://github.com/getgauge/gauge/commit/00e6007f52bf17206c205e1ed986990ab33b57b0) commit, the parse errors, step validation errors, spec validation errors are all shown in same format. In case of failure of data table row validation, it raises a validation error(which was not happening earlier).

Format of errors:

[Type of error] filename:line_number Error message => Error specific detail

Example:
```
[ParseError] foo/specs/spec1.spec:37 Dynamic parameter <item> could not be resolved => 'buy <item>'
[ValidationError] foo/specs/spec2.spec: Table rows range validation failed => Table row number '1' is out of range
[ValidationError] foo/specs/spec3.spec: Table rows range validation failed => Table row number '1' is out of range
[ValidationError] foo/specs/spec3.spec:36: Step implementation not found => 'my step'
```

**Comment by sguptatw** [comment]
Tested for parse errors

* Step is not defined inside a concept heading
* Table doesn’t belong to any step
* Scenario heading is not allowed in concept file
* Concept should have at least one step
* Concept heading can only have dynamic parameters
* Duplicate concept definition found
* Teardown should have at least three underscore characters
* Table location not specified
* Scenario heading should have at least one character
* Table header should be not blank
* Table header cannot have repeated column values
* Multiple spec headings found in the same file
* Scenario should be defined after the spec heading
* Could not resolve table from file
* Spec does not have any element
* Spec heading not found
* Spec heading should have at least one character
* Data table should at least have 1 data row
* Dynamic param could not be resolved
* Step should not be blank
* Circular reference found in concept
* Duplicate scenario definition found in the same specification

Tested for validation errors

* Table rows range validation failed
* Step implementation not found
