### ISSUE TITLE
should be able to get output for an individual scenario, when run from VS

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#536]
### Expected behavior
Before using the execution API, I was able to see the output for both passed and failed tests for a selected scenario.

### Actual behavior
With the execution API, I am not able to see the output for a given scenario.

### Steps to reproduce
1. Create a new project
2. Use execution API
3. Run the tests. Click on a scenario. The test output below does not have the output link

### Gauge version
```
Gauge version: 0.6.3.nightly-2016-12-07

Plugins
-------
csharp (0.9.3.nightly-2016-11-04)
html-report (2.2.0.nightly-2016-12-06)
java (0.5.1.nightly-2016-08-18)
ruby (0.3.2.nightly-2016-08-22)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by sriv** [comment]
Execution API should send back output from STDOUT/STDERR from the specs run. This could then be displayed in IDEs.

**Comment by zabil** [comment]
Execution API will be deprecated soon.
