### ISSUE TITLE
Gauge tests with chromedriver crash on startup on snap-ci - Could not get authority info

### ISSUE THREAD

**Issue by yolinas** [getgauge/gauge#541]
### Expected behavior
Browser test suite should run successfully in snap-ci

### Actual behavior
When the tests start and the first test step that requires a browser executes, it blows up with the following error: 
```
XGB: conn.go:47: Could not get authority info: open /var/go/.Xauthority: no such file or directory
```
Please see full stack trace below:

```
Starting rake.
bundle exec rake --verbose test:end_to_end
# Administration
  ## Complete Orders	
      * An order is submitted
XGB: conn.go:47: Could not get authority info: open /var/go/.Xauthority: no such file or directory
XGB: conn.go:48: Trying connection without authority info...
XGB: conn.go:47: Could not get authority info: open /var/go/.Xauthority: no such file or directory
XGB: conn.go:48: Trying connection without authority info...
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x556a40, 0xc420012160)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
image.(*RGBA).Opaque(0xc4200fc040, 0x62e340)
	/usr/local/Cellar/go/1.7.3/libexec/src/image/image.go:141 +0xc3
image/png.opaque(0x62e340, 0xc4200fc040, 0x62c240)
	/usr/local/Cellar/go/1.7.3/libexec/src/image/png/writer.go:60 +0x162
image/png.(*Encoder).Encode(0xc420668000, 0x62c5c0, 0xc4200b2090, 0x62e340, 0xc4200fc040, 0xc4203a4000, 0xc4200ce2c0)
	/usr/local/Cellar/go/1.7.3/libexec/src/image/png/writer.go:508 +0x505
image/png.Encode(0x62c5c0, 0xc4200b2090, 0x62e340, 0xc4200fc040, 0xc4200fc040, 0x0)
	/usr/local/Cellar/go/1.7.3/libexec/src/image/png/writer.go:476 +0x6a
github.com/getgauge/screenshot/capture.CaptureScreen(0x7ffc03bacb0f, 0x13, 0x0, 0x0)
	/tmp/src/github.com/getgauge/screenshot/capture/capture_linux.go:60 +0x195
main.main()
	/tmp/src/github.com/getgauge/gauge_screenshot/main.go:32 +0x101
      * An order is submitted	 ...[FAIL]
```

### Steps to reproduce
1. Install gauge and gauge-ruby on a linux distribution of snap-ci
2. Run gauge tests with bundler and snap-ci provided chromedriver
3. Tests fail with the above error

Also worth mentioning that these tests are successfully running on our local machines which include both mac os and linux machines.

### Gauge version
0.6.2 and 0.7.0

**Comment by kashishm** [comment]
@yolinas Sorry for the delayed response. I could replicate the issue on snap-ci with stack `Cybele(Ubuntu)`. The exception occurs when there is a failure and Gauge tries to take a screenshot.

Workaround:
Add the following line to the `default.properties` file in default env or [add a new env](http://getgauge.io/documentation/user/current/advanced_readings/managing_environments.html#creating-new-environment) 'ci' with the following property and specify this env during execution i.e.
`bundle exec gauge --env ci specs`
```
screenshot_enabled = false
```

**Comment by yolinas** [comment]
Thanks, this work around worked for us but we would like to eventually have the ability to get screenshots when running our tests in ci. Any idea when this will be fixed? Thanks!

**Comment by sriv** [comment]
@yolinas - we should be addressing this in a release post the upcoming one. On a side-note, since snap-ci has announced that they will be shutting down, I hope you have a migration plan. If you do, could you please check if the workaround is valid in the new CI? 
We will address this in the meantime. Thanks.

**Comment by yolinas** [comment]
Hello, wondering if you have any updates on this?

We have just moved to circle-ci and this fix no longer works there.

Here is my setup with circle-ci:
circle-ci 2.0 - using workflows and docker containers
docker container for running the gauge tests: circleci/python:2.7.13-browsers
default.properties file:
```
gauge_reports_dir=../../build/end-to-end
overwrite_reports=true
screenshot_enabled = false
```
Here is the stacktrace:
```
bundle exec rake --verbose test:end_to_end

# Customer Support Agent
  ## Acting on customer behalf	
      * Customer has signed up for a weekly subscription
XGB: conn.go:47: Could not get authority info: open /home/circleci/.Xauthority: no such file or directory
XGB: conn.go:48: Trying connection without authority info...
```

Any ideas?

Thanks!

**Comment by zabil** [comment]
@yolinas 
Have you tried overriding the default screen-shot feature with a custom one?
Here's how to do that.

https://docs.getgauge.io/language.html#taking-custom-screenshots

**Comment by sriv** [comment]
@yolinas - I noticed from another issue that you have moved to circle-ci and are still facing issues. Please let us know if the issue persists even after doing one of the below:

- upgrade to latest gauge (we have changed the way gauge_screenshot works, but that might be irrelevant if you are running gauge in a headless OS)
- use custom screen shots
- disabling screenshots.
