### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#542]
_From @sguptatw on December 13, 2016 6:47_

- [ ] As a user evaluating the tool, I should be able to try Gauge simple examples in the browser without installing Gauge on my local box.
- [ ] As a Gauge user, I should be able to decide whether Gauge is the tool to use by visiting the website.
- [ ] [Add more Gauge API](https://github.com/getgauge/gauge/issues/539)
- [ ] As a Gauge user, I should be able to [find content](https://github.com/getgauge/documentation/issues/74) - video, text based on search input.
_Copied from original issue: getgauge/documentation#73_

**Comment by zabil** [comment]
Spiked web assembly to run Gauge in the browser. There will be significant changes to get this up and running. Won't be implementing this.
