### ISSUE TITLE
Use `GAUGE_ROOT` to customize the location of gauge configs and plugins

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge#544]
### Expected behavior
Gauge configurations should be at user level rather than at system.
The location would be same as gauge plugins i.e `~/.gauge/` in mac/linux and `%APPDATA%\gauge` in windows.`GAUGE_ROOT` env var will be optional and to change the location of the configs/plugins, override `GAUGE_ROOT`.

### Actual behavior
Currently, the configs and plugins are stored in different locations

|Platform|executable|plugin|current config|new config|
|--------|-------|------|-----|-----|
|Mac|`/usr/local/bin`|`~/.gauge` |`/usr/local/share`|`~/.gauge/`|
|Linux|`/usr/local/bin`|`~/.gauge` |`/usr/local/share`|`~/.gauge`|
|Windows|`%ProgramFiles%\gauge\bin`|`%APPDATA%\gauge` |`%ProgramFiles%\gauge\share`|`%APPDATA%\gauge`|

To change the install location for gauge and configs, we need to set `GAUGE_ROOT` env var and to change the plugin install location, `GAUGE_HOME` needs to be set.

We can have consistent behaviour if we store the configs and plugins at the same location and use one env var i.e. `GAUGE_ROOT` to customize it.

Test cases
- [ ] should work on Mac
- [x] should work on Linux with ./install.sh interactive
- [x] should work on Linux with ./install.sh by giving the parameters GAUGE_PREFIX and GAUGE_PLUGINS
- [x] should work on Windows

**Comment by sguptatw** [comment]
The installer is not giving me an option to enter the password of admin
```
Installing gauge at /usr/local/bin
Enter custom install location :-

Creating /home/sswaroop/.gauge/config ...
mkdir: cannot create directory ‘/home/sswaroop/.gauge’: Permission denied
```

**Comment by sguptatw** [comment]
Gauge installation on linux using GAUGE_PREFIX requires the user to exec command source ~/.profile. The message in the installation looses focus when there are other plugins also getting installed. User gets an impression as though Gauge is not working as expected

**Comment by sguptatw** [comment]
Install gauge using the GAUGE_PREFIX. 
use command source ~/.profile. 
Now close the terminal
Re-open the terminal
gauge is not found.

**Comment by sriv** [comment]
when installing `gauge` to custom location i.e. using `GAUGE_PREFIX` option, it is the user's responsibility to source the respective settings in their shell. i.e. in bash, one can add `source ~/.profile` to their `.bashrc`. Gauge cannot automate this, since user may be using any shell of their preference.

**Comment by sguptatw** [comment]
usage `GAUGE_PREFIX=/tmp GAUGE_PLUGINS=java,ruby,spectacle ./install.sh` for Mac and Linux.

On windows the exe provides the option to install at a custom location and select the plugins.
