### ISSUE TITLE
Output rich content via method like Gauge.writeHtml

### ISSUE THREAD

**Issue by nguyennv84** [getgauge/gauge#545]
Use Cases:
- Ability to display screenshot capture in results even if result passes. Provides proof of passed UI steps for clients. 
- Ability to display formatted XML in results which is not possible using existing writeMessage method.

**Comment by mgraffx** [comment]
As a user, I would like the ability to enter message containing html tags with attributes and have then appear in the report source as entered.  
Responsibility is on the user to correctly enter their markup in messages.

**Comment by zabil** [comment]
This is only applicable for HTML reports. However Gauge can generate reports in other formats. To maintain compatibility, this won't be implemented.
