### ISSUE TITLE
Inconsistent error message when table location not specified

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#553]
**Expected behavior**
The message should be consistent.

**Actual behavior**
Getting `table location not specified` in one scenario and `Dynamic param could not be resolved` in another.

**Steps to replicate**
1. Create a spec
```
Specification Heading1
==================
table:
Scenario Heading
---------------
* some1 "abc"
* Conce1pt with step using tables and use it in some spec "RED"

* step2 <table:>
```
2. Run the spec. Look at the message inconsistency

**Version**
```
Gauge version: 0.7.1.nightly-2017-01-06

Plugins
-------
html-report (3.0.1.nightly-2017-01-11)
java (0.5.2.nightly-2016-12-20)
ruby (0.3.2.nightly-2016-12-16)
xml-report (0.1.4.nightly-2017-01-13)
```

**Comment by sguptatw** [comment]
The same is true for the following as well

```
Specification Heading1
==================
table:sdf.csv

---------------
* some1 "abc"
* Conce1pt with step using tables and use it in some spec "RED"

* step2 <table:sdf.csv>
```

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
