### ISSUE TITLE
Support for Node JS or say webdriverio tests

### ISSUE THREAD

**Issue by rahulmr** [getgauge/gauge#554]
Does this support node js or webdriverio specs. JavaScript has been evolving nowadays so want to know how to work on it with gauge.

I have android appium tests using webdriverio and want to know how to use gauge to work with them

**Comment by sriv** [comment]
You can use the [gauge-js](https://github.com/getgauge-contrib/gauge-js) community plugin to write JavaScript implementations.

Examples are listed [here](https://github.com/getgauge-contrib/gauge-js/blob/master/README.md#demos-and-examples)
