### ISSUE TITLE
Incorrect error with missing manifest.json

### ISSUE THREAD

**Issue by jgwilson42** [getgauge/gauge#555]
### Expected behavior

If gauge cannot find the manifest.json file then the error should point to this file as being missing.

### Actual behavior

The current error is:
```
Failed to find project directory
```

### Steps to reproduce
1. Install gauge
2. gauge --init java
3. mv manifest.json manifest.json_old
4. gauge specs/

### Gauge version
```
Gauge version: 0.7.0

Plugins
-------
html-report (3.0.1)
java (0.5.1)
```

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.

**Comment by jgwilson42** [comment]
@zabil, please could you reopen this ticket? I am still seeing the issue with the latest version of gauge:

```
Gauge version: 1.0.7
Commit Hash: ed7b4fd6

Plugins
-------
html-report (4.0.9)
java (0.7.4)
screenshot (0.0.1)
```

Steps to reproduce
```
gauge init java
mv manifest.json manifest.json.old
gauge run specs/
```

Output
```
Failed to find project directory
Usage:
  gauge run [flags] [args]

Examples:
  gauge run specs/
  gauge run --tags "login" -s -p specs/

Flags:
  -e, --env string              Specifies the environment to use (default "default")
      --fail-safe               Force return 0 exit code, even in case of failures.
  -f, --failed                  Run only the scenarios failed in previous run. This cannot be used in conjunction with any other argument
<snip>
```

It would be much better if the error specifically mentioned `manifest.json`
