### ISSUE TITLE
Consistent behavior in showing parse errors on console/reports

### ISSUE THREAD

**Issue by apoorvam** [getgauge/gauge#557]
From issue #532,  if we have parse errors in few specs, we should continue with execution of rest of the specs.

### Current behavior

If there are parse errors, its currently shown only in console as below and is not reflected in reports(html/xml reports).
```
[ParseError] /Users/myproject/specs/example1.spec:28 Dynamic parameter <table:input.csv> could not be resolved => 'Almost all words have vowels <table:input.csv>'
```

### Approach

* The spec with parse error should be marked as failed. 
* The statistics should reflect this spec with parse error
* The reports should include this spec as failed and state the parse error
* In case where there is only one spec and it has parse error, reports will still be generated showing this parse error.
* The exit code will be non-zero in case of parse errors, irrespective of execution result of remaining specs.
* If there is a parse error in concept, the execution will not proceed. This is because these concepts can be used in any specs. It can be an enhancement to execute the specs which do not use these concepts.

### Notes

* The parsing, validation, execution is all a part of actual execution i.e `gauge specs` command invocation. Even if parsing fails, reports are generated for the execution attempt made.

#### If there is a parse error, why it should not be marked as skipped? (and is marked as failed)

In case where spec is marked as skipped, the exit code of process will be zero. This doesn't bring up the failure in execution. The specs which do not have implementation will be marked as skipped. In this case its valid to have exit code as 0 because there will be specs written ahead of implementation or they could be manual specs.

**Comment by kashishm** [comment]
Fix will be available in following nightly versions:
**Gauge** >= 0.7.1.nightly-2017-01-31
**HTML Report** >= 3.0.1.nightly-2017-01-31
**XML Report** >= 0.1.4.nightly-2017-02-03

**Comment by sguptatw** [comment]
Please add the documentation of how to interpret the statistics when there is a parse error.

**Comment by sguptatw** [comment]
There are certain ParseErrors in which case we do not execute the specs at all. Can we differentiate such ParseErrors as something else a ParseException may be?

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
