### ISSUE TITLE
install behind a proxy failed,could not download plugin.

### ISSUE THREAD

**Issue by tigerlei010** [getgauge/gauge#559]
### Expected behavior
when install gauge in ubuntu 14.04 which behind a proxy, it could not install html-report automatically. I have set the http_proxy env var.  I can use wget to download html-report/ruby plugin file from github.

### Steps to reproduce
1. a ubuntu 14.04 behind a proxy. http_proxy env variable has been setted.
2. download gauge-0.7.0-xxx-zip ,and unzip it
3. run sudo -E ./install.sh
4. the installer puts "Failed to install plugin html-report .Reason: Invalid plugin. could not download html-report-install.json file"

### Gauge version
```
Gauge 0.7.0
```

**Comment by sguptatw** [comment]
@ tigerlei010: There were several fixes w.r.t installations in the latest release. Kindly let us know if you still face the issue.

**Comment by sguptatw** [comment]
Closing this issue as of now. If you face this again, please feel free to re-open it.

**Comment by mathinithu** [comment]
Hi.. I am also facing this now can you give solution for this..          
I  installed the gauge..but while running with this command . I using to install the from "weget" it downloaded 
Step 2: run the npx gauge --version
Gauge version: 1.0.4
Commit hash:3a9a647

Plugins
Is(2.3.2)
Step:3 run npx gauge run
These error came
Compatible version of plugin html-report not found. Installing plugin html-report...
Failed to install plugin 'html-report'.
Reason: Invalid plugin. Could not download html-report-install.json file.
Installing required plugins.
(node:6841) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
Unable to start plugin html-report. Plugin html-report is not installed. To install, run gauge install html-report.
{ Error: getaddrinfo EAI_AGAIN www.google-analytics.com:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'www.google-analytics.com',
  host: 'www.google-analytics.com',
  port: 80 }
Error ----------------------------------
Connection to runner with Pid 6835 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:46693->127.0.0.1:43200: use of closed network connection

Get Support ----------------------------
    Docs:          https://docs.gauge.org
    Bugs:          https://github.com/getgauge/gauge/issues
    Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
    linux, 1.0.4, 3a9a647
    js (2.3.2)

Can you help to solve this....
