### ISSUE TITLE
go run build/make.go --install is not installing by default into /usr/local

### ISSUE THREAD

**Issue by navaneeth** [getgauge/gauge#56]
It installs into `deploy` directory now.

**Comment by navaneeth** [comment]
```
go run build/make.go --install --prefix /usr/local
```
Even specifying a prefix installs to the deploy directory

**Comment by prateekbaheti** [comment]
Hey can you check this again? It creates the directory structure into deploy then copies all files into /usr/local/ .

![screen shot 2015-01-12 at 5 02 17 pm](https://cloud.githubusercontent.com/assets/1955832/5702213/cf3f5fe4-9a7c-11e4-80d0-996eea10c1d6.png)

**Comment by navaneeth** [comment]
Yeah. `mirrordir` might be returning error in `installGauge()` function. On my box, /`usr/loca/` needs a sudo to write. You need to add error check when calling `mirrordir`. In buid/make.go:274

To reproduce, try into install to a location where you don't have write access. It will fail silently.
