### ISSUE TITLE
Difference in behavior when plugin is not installed

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge#564]
_From @sguptatw on February 9, 2017 13:22_

In java if the plugin is not installed and I initialize the project, it initializes the project. Tells me that the compatible plugin is not installed. Downloads and installs it.

However c# and ruby do not share the same behavior

**Version**
```
Gauge version: 0.8.0.nightly-2017-02-06

Plugins
-------
```

_Copied from original issue: getgauge/gauge-csharp#103_

**Comment by BugDiver** [comment]
_From @sriv on February 9, 2017 13:24_

## Dev Notes

Plugin installation is done by `gauge`, could be a potential gauge core issue. Needs verification.

**Comment by BugDiver** [comment]
With [this](https://github.com/getgauge/gauge/commit/813a1619ff697daaec8c7b7cecb91620c4697552) commit gauge installs compatible runner before initializing the project.
Fix should be availabe in nightly >= 14-02-2017.

**Comment by sguptatw** [comment]
Working fine on Windows and Mac.
Todo test on Linux
