### ISSUE TITLE
Error starting the html-report

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#566]
On executing the project getting the error
```
Error starting plugin Html Report 3.1.0. exec: "C:\\Users\\sswaroop.CORPORATE\\AppData\\Roaming\\gauge\\plugins\\html-report\\3.1.0.nightly-2017-02-08\\bin\\html-report": file does not exist
# kusfdsf sdfsdfsdf
  ## sdfsdf
```
**Version**
```
Gauge version: 0.8.0.nightly-2017-02-14

Plugins
-------
csharp (0.9.3.nightly-2017-02-13)
html-report (3.1.0.nightly-2017-02-08)
```

**Comment by sguptatw** [comment]
unable to reproduce this again

**Comment by sguptatw** [comment]
Please use the dataStoreIssue project. Unable to upload the project now. Will upload asap.

**Steps to replicate**
* Run from the Visual Studio
* Click on the individual output 
* Observe the error in the report.

**Comment by BugDiver** [comment]
@sguptatw I’m not able to reproduce it with latest plugins.
the issue is reproducible with wrong plugin installed i.e. darwin plugin instlled on windows . Please make sure you have installed the correct plugin.

**Comment by sguptatw** [comment]
@BugDiver This error is intermittent. Unable to replicate it consistently.
