### ISSUE TITLE
Version check and platform check

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#567]
### Context

Installing a plugin via file can be done using `gauge --install ruby -f /path/to/ruby/plugin.zip`.

However this workflow bypasses the version compatibility check available during online install. 
Also, the online installation mechanism ensures that the right artifact is downloaded for the respective platform.

### Expected

When doing an offline installation (ex `gauge --install ruby -f /path/to/ruby/plugin.zip`)

- Ensure that the `/path/to/ruby/plugin.zip` corresponds to the right platform (OS+Arch)
- Ensure that the installed `gauge` verion is in range of compatible versions of `/path/to/ruby/plugin.zip`'s metadata.

**Comment by BugDiver** [comment]
Fix should be available in nightly >= 21-02-2017.

**Comment by sguptatw** [comment]
32 bit Gauge is getting installed on 64 bit machine.
Furthermore any plugins installed using this Gauge is installing plugins of 32 bit.

**Comment by sguptatw** [comment]
This card is limited to plugin installation from file. The other test cases will be taken up separately.
