### ISSUE TITLE
Uninstall is not deleting the Gauge folder

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#568]
Uninstall is not deleting the Gauge folder from Program files. Two files are left behind
- backup_properties_file
- set_timestamp

**Version**
```
gauge-0.8.0.nightly-2017-02-14-windows.x86_64
```

**Comment by sriv** [comment]
this is expected, given we backup the `gauge.properties` when doing a re-install. This should not be the case when uninstalling and installing everytime.
