### ISSUE TITLE
I have linted ruby template

### ISSUE THREAD

**Issue by gastzars** [getgauge/gauge#569]
I have fork your ruby template and linted it using Rubocop.
This can help when people initial a new project, they would get **100% linter pass**, and more friendly code.

What I have changed are
1. Fix some **indent** in _step_implementation.rb_
2. Remove **semicolon** in _step_implementation.rb_ ( ruby doesn't need it )
3. Change the **variable's name** from **CamelCase** to **snake_case** ( ruby comunity standard )
4. Some **too long** code in _create_gemfile.rb_ 

Check it out here: https://github.com/gastzars/gauge_ruby_template
And the **commit's change** here: https://github.com/gastzars/gauge_ruby_template/commit/0bec12d61b09f19d9d39ff2b37c745f9ac6d7ad5

ps. I didn't see any of template available in your repository, so I download it and commit for you to easily see it, what have I done.

**Comment by sriv** [comment]
@gastzars - thanks for this, it is always good to have proper conventions followed.

The template code resides here: https://github.com/getgauge/gauge-repository/tree/master/templates

You will see two templates for ruby: `ruby` and `ruby_selenium`. 

It would be great if you could open an PR against this repository.

**Comment by gastzars** [comment]
@sriv I have create a PR here https://github.com/getgauge/gauge-repository/pull/6

:smile:

**Comment by sriv** [comment]
Thanks for contributing! I've merged the PR. Am closing this issue.
