### ISSUE TITLE
After update to gauge 0.8.0 gauge job in GO is failed even though all tests are passed

### ISSUE THREAD

**Issue by kupna** [getgauge/gauge#573]
### Expected behavior
When running a gauge job with GO the job should be passed when all tests are passed

### Actual behavior
When running a gauge job with GO the job is failed even though all tests are passed
11:30:37.830 Feb 21, 2017 11:30:37 AM net.sf.sahi.test.ProcessHelper kill
11:30:37.830 INFORMATION: Kill: [732, 1780, 6912, 7420, 6096, 6568, 5092, 5588, 5252]
11:30:38.948 Feb 21, 2017 11:30:38 AM net.sf.sahi.Proxy c
11:30:38.948 INFORMATION: socket closed
11:30:40.617 Successfully generated html-report to => C:\GoAgent\pipelines\engage-gauge-courseguide\courseguide\reports\html-report
11:30:41.255 Specifications:	2 executed	2 passed	0 failed	0 skipped
11:30:41.255 Scenarios:	6 executed	6 passed	0 failed	0 skipped
11:30:41.262 
11:30:41.262 Total time taken: 13m42.898s
11:30:41.343 [go] Current job status: failed.

### Gauge version
Gauge version: 0.8.0

Plugins
-------
html-report (3.1.0)
java (0.6.0)

**Comment by kashishm** [comment]
@kupna This might happen when there is an `AfterSuite` failure. Do you see any exception in console/HTML reports?

**Comment by kupna** [comment]
No there is no exception in console and no exception in html report...

**Comment by kupna** [comment]
Is it because of the  [ParseError]?

**Comment by kashishm** [comment]
If there is a `[ParseError]`, Gauge would consider the specification failed and execution summary/statistics would reflect that. #557 issue has more details on this.

Do you see any `[ParseError]` in the console/HTML reports?

**Comment by kupna** [comment]
Yeah there was this:
11:16:44.359 [ParseError] C:\GoAgent\pipelines\engage-gauge-courseguide\courseguide\specs\inprogress\COU Verify show registration information.spec:6 Scenario should have atleast one step => ''
11:16:44.359 [ParseError] C:\GoAgent\pipelines\engage-gauge-courseguide\courseguide\specs\inprogress\COU BulkRegistration.spec:4 Scenario should have atleast one step => ''

I removed the [ParseError] but I don't think the run should fail if there is a [ParseError]

**Comment by kashishm** [comment]
Ideally, it should have reflected the spec count in execution summary. I am not sure why that is not happening.
Please update the issue with reasons why the run should not fail if there are parse errors.

**Comment by kupna** [comment]
In my case I call the gauge tests by tag - and the tests that are assigned to that tag do not cause a ParseError - other tests in the spec folder cause the ParseError, but they are inProgress and do not have to be ready or successfully parsed. 

So I suggest, if I execute tests that do not have a ParseError, even if they are called by tag, the test run should not fail.

**Comment by sguptatw** [comment]
@kupna, yes the way Gauge treats ParseError has changed.

If you have a spec that is work in progress, then we suggest having a specification with scenarios with unimplemented steps. These scenarios will be skipped and reported with details when executed. Later, when anyone wants to automate the scenario can get more context.

Please let us know if this addresses your issue.

**Comment by sriv** [comment]
@kupna - is there something that we should be tracking as part of this issue?

**Comment by sguptatw** [comment]
@kupna - If there is anything more you want to track as a part of this issue please feel free to re-open.
