### ISSUE TITLE
Include options to install plugins via installer - Windows

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#574]
Currently, only core language runners are listed for users to choose while installing Gauge.

Have an option to include

- html-report (mandatory)
- xml-report
- spectacle

**Comment by sriv** [comment]
Fix available in nightly >= 23/02/2017

**Comment by sguptatw** [comment]
Not getting these options in the installer gauge-0.8.2.nightly-2017-03-01-windows.x86_64

**Comment by sriv** [comment]
Issue with the installer in our build server. Has been resolved, fix should be available in nightly >= 07/02/2017
