### ISSUE TITLE
Include options to install plugins via installer - osx pkg

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#575]
ref to #574.

Similar to windows installer, consider including plugins installation options in the pkg installer for mac.

Possible options:

Language runners:

- java
- csharp
- ruby

Reporting plugins:

- html-report (mandatory)
- xml-report
- spectacle

**Comment by sriv** [comment]
fix should be availabe in nightly >=09/03/2017

**Comment by sguptatw** [comment]
On unchecking the reporting plugins option, the html-report is also getting unchecked.

**Comment by BugDiver** [comment]
Fix should be avalable in nightly >= 14-03-2017
