### ISSUE TITLE
Takes too long to start execution

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#581]
[art.zip](https://github.com/getgauge/gauge/files/806121/art.zip)

The command used is `mvn test -DinParallel=true -Dnodes=100`
It takes unusually long(about half a minute) to start the execution, even when optimization is switched off.

**Version**
```
Gauge version: 0.8.1.nightly-2017-02-23

Plugins
-------
html-report (3.1.0)
java (0.6.1.nightly-2017-02-23)
```

**Comment by sriv** [comment]
when you are not setting `enable_multithreading=true`, you are telling gauge to run in parallel and use 100 processes, which essentially means 100 JVM! It is expected that this will take some time to start up, and depending on your machine's configuration it might even have some impact on other applications.

When I run the above command using `enable_multithreading=true` I see the tests starting quite fast. The whole test execution is completed in less than 30 seconds: 

```
Specifications:	81 executed	81 passed	0 failed	2 skipped
Scenarios:	2025 executed	2025 passed	0 failed	2 skipped

Total time taken: 26.563s
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.813 s
[INFO] Finished at: 2017-03-01T07:31:52+05:30
[INFO] Final Memory: 9M/240M
[INFO] ------------------------------------------------------------------------
```
