### ISSUE TITLE
Add commit sha in gauge version info when installing from source

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge#584]
Currently, there is no way to know if the user has installed gauge from source or installers.

```
Gauge version: 0.8.2

Plugins
-------
html-report (3.0.1)
java (0.6.1)
```
Include commit sha in version info if gauge or the plugins are installed from source. Example:
```
Gauge version: 0.8.2@<commit_sha>

Plugins
-------

html-report (3.0.1@<commit_sha>)
java (0.6.1)
```

**Comment by sriv** [comment]
available in nightly >= 10/03/2-17.

Sample format is `Gauge version: 0.8.2.cd96637-master`

**Comment by sriv** [comment]
Will have to wait for Go 1.9. See: https://github.com/golang/go/issues/14853

**Comment by Apoorva-GA** [comment]
Currently gauge version doesn't have any commit hash information.
```
Gauge version: 0.9.2

Plugins
-------
html-report (4.0.2)
java (0.6.5)
spectacle (0.1.2)
```

Expected 
```
Gauge version: 0.9.2
Commit Hash: 4f1be71

Plugins
-------
html-report (4.0.2)
java (0.6.5)
spectacle (0.1.2)
```
Available in nightly >=23/08/17

**Comment by sguptatw** [comment]
The commit hash message is available only for Gauge.
Having this for other plugins is not in scope.
