### ISSUE TITLE
Unable to run Gauge specs on ubuntu

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#585]
sudo gauge --init ruby
Initializes the project successfully.

However running the Gauge specs is giving the following error
$ sudo bundle exec gauge specs
/usr/lib/ruby/2.3.0/rubygems/requirement.rb:101:in `parse':  (Bundler::Dsl::DSLError)
[!] There was an error parsing `Gemfile`: Illformed requirement ["~>"]. Bundler cannot continue.

 #  from /home/username/rubytest/Gemfile:4
 #  -------------------------------------------
 #  gem 'test-unit', :group => [:development, :test]
 >  gem 'gauge-ruby', '~>', :group => [:development, :test]
 #  -------------------------------------------
	from /usr/lib/ruby/2.3.0/rubygems/requirement.rb:131:in `block in initialize'
	from /usr/lib/ruby/2.3.0/rubygems/requirement.rb:131:in `map!'
	from /usr/lib/ruby/2.3.0/rubygems/requirement.rb:131:in `initialize'
	from /usr/lib/ruby/2.3.0/rubygems/requirement.rb:59:in `new'
	from /usr/lib/ruby/2.3.0/rubygems/requirement.rb:59:in `create'
	from /usr/lib/ruby/2.3.0/rubygems/dependency.rb:59:in `initialize'
	from /usr/lib/ruby/vendor_ruby/bundler/dependency.rb:59:in `initialize'
	from /usr/lib/ruby/vendor_ruby/bundler/dsl.rb:86:in `new'
	from /usr/lib/ruby/vendor_ruby/bundler/dsl.rb:86:in `gem'
	from /home/sswaroop/rubytest/Gemfile:4:in `eval_gemfile'
	from /usr/lib/ruby/vendor_ruby/bundler/dsl.rb:36:in `instance_eval'
	from /usr/lib/ruby/vendor_ruby/bundler/dsl.rb:36:in `eval_gemfile'
	from /usr/lib/ruby/vendor_ruby/bundler/dsl.rb:10:in `evaluate'
	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:24:in `build'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:120:in `definition'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:88:in `setup'
	from /usr/lib/ruby/vendor_ruby/bundler/setup.rb:18:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Ruby runner Failed. Reason: exit status 1
Failed to start gauge API: Runner with pid 8631 quit unexpectedly(exit status 1).

> This issue occurs even after `sudo gem install gauge-ruby`

**Comment by sriv** [comment]
On Arch Linux:

With installer v0.8.2.nightly-2017-03-09, I am able to do the below:

- `./install.sh`
- `gauge --init ruby` Note, this is without `sudo`
- `bundle exec gauge specs`

Specs run fine.

**Comment by sguptatw** [comment]
@BugDiver  is able to replicate this issue is on Mac as well.

**Comment by BugDiver** [comment]
It happens if you doesn't have any other gauge_ruby gem installed.
