### ISSUE TITLE
is it possible to have data per environment? how can this be done?

### ISSUE THREAD

**Issue by aredz** [getgauge/gauge#586]
### Expected behavior
lets say we have 3 env.
dev, uat, prod.

These environments are configured in *.properties with a custom variable

**The path to the gauge test data directory (for each environment this is configured differently so we can have configurable data)**
data_dir= test_data\\uat

we should have a configurable data.
It could be table or anything else which we can configure per environment.

### Actual behavior
If env = dev
user = "admin1"

if env = uat
user = "admin2"

if env = prod
user = "admin3"

### Steps to reproduce
1. gauge --env uat specs/
2. data used by all specs should be as per environment,
 2.1 user tables, product tables, etc...
 2.2 sample spec:
  2.2.1 Login as user _<table:<data_dir>\\login.csv>_
  2.2.2 also if possible, we can access a column inside the csv _<table:<data_dir>\\login.csv"userId">_
3. execute specs implementation

Additional Note:
I'm running 0.8.0 with xml-report 0.2.0 I believe on a different machine.

### Gauge version
```0.8.0
Run gauge -v on your system and paste the results here.
```Gauge version: 0.6.2

Plugins
-------
csharp (0.9.2)
html-report (2.1.1)
python (0.1.6)
spectacle (0.0.1)
xml-report (0.1.3)

**Comment by sriv** [comment]
Gauge currently does not look at `env` when looking for the data sources. But this is a good suggestion, thanks for bringing it up.

There is a related request for variable support : #178. I think one option to address this issue, would be to allow variables so that the datasource name can be externalized thus allowing different datasource for environments..

**Comment by aredz** [comment]
thanks @sriv . Yep I've also seen that post, however not sure how it can be configured per environment. I am thinking based from tags, but yeah I'll let you know when I can think of a workaround. I'm currently starting up the test automation for my employer so I'd like the framework to be configurable for maintainability. 

also, when would this be possible as a new feature? is there a timeframe usually when suggestions are bring up? sorry, not to be rude. I just created an account today.

**Comment by sriv** [comment]
@aredz - It isn't unfair to expect a timeframe, so no need to apologize. However, we do not plan with timeframes, rather we try to release as often as it makes logical sense. You can take a peek at our backlog and wip [here](https://waffle.io/getgauge/gauge) (Disclaimer: please expect the wall to change :)).

I would be really interested in a workaround if you can think of it. I feel one workaround could be: 

- refer to a data file using : `<table:does_not_exist.csv>` where `does_not_exist.csv` is not yet present.
- in `BeforeSuite` hook, copy your environment specific data as `does_not_exist.csv`. Thus making the right dataset available according to the environment. Does this make sense?

**Comment by sriv** [comment]
@aredz - just wanted to refer you to [a similar question](https://groups.google.com/forum/#!searchin/getgauge/env%7Csort:relevance/getgauge/DrEuYIODEp8/K-E1aWrEAQAJ) on our google groups forum.

**Comment by aredz** [comment]
@sriv - Many Thanks! I will have a look at your suggestion.
The WIP for gauge looks cool as well. I will visit it once in a while :)

**Comment by aredz** [comment]
@sriv - the one in google groups does not seem to work.

csv_path = *.csv in *.properties to setup local variable
<table:csv_path> in *.spec returns error

Dynamic parameter <table:csv_path> could not be resolved

as for the `BeforeSuite` hook, how do I check the gauge environment? how would I access the gauge parameter value --env?

**Comment by sriv** [comment]
@aredz - you need to have a dummy `csv_path` file present, else gauge is unable to parse the spec file. 

Just to summarize:

- keep a `.csv` file in the location you desire, (this need not have the actual data you need)
- In `BeforeSutie` hook move the csv from the location you desire to this path.
- Specs can continue to refer to `<table:csv_path>`

This should work, please post back if you have issues.

**Comment by aredz** [comment]
hey @sriv . sorry I didn't indicate the actual data in the environment file. The file is in the actual location

this is the `uat.properties` file

# The path to the gauge test data directory
csv_path = resources/uat/login.csv

this is the `test.spec` file

Gauge Environment Testing
=========================

This is a test

Test 1
------

* Log into REST API as user <table:csv_path>

the code above is not working. however if I use below spec, it is working

* Log into REST API as user <table:resources/uat/login.csv>

for the `BeforeSuite`, not sure how I can do that. I just learned python. can you please provide me a sample? even on a different programming language would be fine

this is all I know for the python execution but I don't know what to write on the actual one:
@before_step
def before_step_hook(context):
#code here to check environment variable

sorry for bugging you out on this issue I'm having

**Comment by sriv** [comment]
@aredz - I believe I misunderstood your use-case.

Please see this gist: https://gist.github.com/sriv/3964962b6595140f79de074b6132a2e1and this should give you some hints. Note: this is in ruby, so python should be similar.

**Comment by aredz** [comment]
thanks @sriv . I got the same approach you mentioned. I just need to get the csv reader as well in python.
Many thanks for your valuable time.

thanks @sriv . I got the same approach you mentioned. I just need to get the csv reader as well in python.
Many thanks for your valuable time.

```
@step("REST API LogOn")
def ret_api_login_table():
    users = (os.getenv('csv_path')) --> need to fix this part
    x = LoginHelper()
    for row in users:
        x.api_failed_login(row[0], row[1])
        pprint(row[0])
        pprint(row[1])
```

**Comment by aredz** [comment]
@sriv  thanks again for this. I was able to make it work yesterday

**Comment by sriv** [comment]
Excellent and you're welcome! If you have the time to write a quick summary of what you did, it will help the community immensely! 

Closing this issue.
