### ISSUE TITLE
windows installer: allow silent install to take plugins as arguments

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#587]
`gauge-0.8.1-windows.x86_64.exe` can be invoked with a `/S` option to perform silent install. The installer could take plugins that also need to be installed so that silent installers can also install plugins.

ex. `gauge-0.8.1-windows.x86_64.exe /S /PLUGINS ruby,csharp` should install `gauge`, `gauge-ruby` and `gauge-csharp`.

**Comment by sguptatw** [comment]
Unable to test due to #589

**Comment by sguptatw** [comment]
using `gauge-0.8.1-windows.x86_64.exe /S /PLUGINS ruby,csharp` 
This installs gauge, however it is not installing the plugins, not even install the html-report.

**Comment by sriv** [comment]
Should be tested against nightly. The feature isnt available in 0.8.1

**Comment by sguptatw** [comment]
This is tested with nightly. The plugins argument is case sensitive.
furthermore if I use PLUGINS, it is not installing any of the plugins. Not even the html-report

**Comment by sriv** [comment]
Works as expected. Steps:

- Download latest nightly (tested with https://bintray.com/gauge/Gauge/Nightly/0.8.2.nightly-2017-03-13)
- Run `gauge-0.8.2.nightly-2017-03-13-windows.x86_64.exe /S /PLUGINS ruby,csharp`
- **Wait for installer process to complete** (This is important as the above command invokes the installer in background). If you notice the task manager, it will tell you when the process has exited.
- `gauge -v` yields:

``` 
Gauge version: 0.8.2.nightly-2017-03-13

Plugins
-------
csharp (0.10.0)
html-report (3.1.0)
ruby (0.4.0)
```
