### ISSUE TITLE
Getting an error while installing Gauge on Windows

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#589]
Even with the basic Gauge installation, I am getting the error 

Error opening file for writing
`skel\example.spec`
If I ignore this file I get the same error with
skel\env\default.properries

**Steps to replicate**
1.  use `gauge-0.8.2.nightly-2017-03-10-windows.x86_64` to install
2. Start installation
3. Select the default options and continue, you will get this issue.

> On ignoring the 2 files the installation goes through successfully.

**Comment by sguptatw** [comment]
Unable to continue with tasks like installing other plugins after this installation.

**Comment by kashishm** [comment]
Fixed via 1a5dcfceb7f663343bdec5b24b52eca5bd279789.

@sguptatw Please try with the latest nightly >= 0.8.2.nightly-2017-03-13
