### ISSUE TITLE
Validation errors are not informative

### ISSUE THREAD

**Issue by navaneeth** [getgauge/gauge#59]
```
# Test

* The following users exist
   |name | email      |
   | test   | t@t.com |
```
```
step "The following users exist" do |table|
end
```

This throws a validation error because step implementation don't say the parameter placeholder. But the message is not very informative. This is what I got:

```
Validation failed. The following steps have errors
login_logout.spec:4: . The following users exist
```

It should say it is expecting a parameter which is not found.

**Comment by sriv** [comment]
gauge-ruby has a fix via https://github.com/getgauge/gauge-ruby/commit/230f9dff9a9f56f6eeacb1b7cd8b3ce17998c26b
