### ISSUE TITLE
Initialize project offline does not create java.properties file

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#592]
**Expected behavior**
The properties file created during offline project initialization is similar to the project created with user being online.

**Actual behavior**
The project created with user being offline does not have the java.properties file.

**Steps to replicate**
1. Ensure the user is offline
2. Create gauge java project
`gauge --init java`
3. open the env default folder. It has only the default.properties file

**Version**
OS - Ubuntu
```
Gauge version: 0.8.2.nightly-2017-03-13

Plugins
-------
html-report (3.1.0)
java (0.6.1)
ruby (0.4.0)
```

**Comment by sriv** [comment]
I get this, with network disconnected:

```
gauge init java
 create  src/test/java
 create  libs
 create  src/test/java/StepImplementation.java
 create  /tmp/bar/env/default
 create  env/default/java.properties
 create  /tmp/bar/.gitignore
 create  manifest.json
 create  specs
 create  specs/example.spec
 create  .gitignore
 create  env
 create  env/default
 create  env/default/default.properties
Successfully initialized the project. Run specifications with "gauge run specs/".
```

### Gauge version

```
Gauge version: 0.9.1

Plugins
-------
csharp (0.10.1)
html-report (4.0.1)
java (0.6.5)
js (2.0.0)
ruby (0.4.1)
xml-report (0.2.0)
```
