### ISSUE TITLE
Show error when spec file contains no scenarios

### ISSUE THREAD

**Issue by navaneeth** [getgauge/gauge#60]
Currently it says it executed, but it is not actually executed. 

```
# Test

* The following users exist
   |name | email      |
   | test   | t@t.com |
```

I'd expect gauge to call implementation of the above context step, but since there are no scenarios in the above spec file, it said it executed 0 scenarios, and 1 spec. But it never called the above implementation. This will cause confusion to the users.

**Comment by sriv** [comment]
I don't think executing context steps in isolation is a good idea. However, I think the messaging should be fixed. Given `Scenarios` are our test cases (drawing a rough parallel to unit test frameworks), I am inclined to think something like `Executed 0 scenarios in 1 specification` should be a better message.

Thoughts @prateekbaheti @deepthigc @navaneeth ?

**Comment by navaneeth** [comment]
I was not saying it should execute context. Sorry for the wrong messaging. I was saying it should fail saying there is nothing to execute.

**Comment by deepthigc** [comment]
Would it be better to explicitly message that "No scenarios to execute in the specification" rather than 0 scenarios? Does it have to follow the "Executed x scenarios in 1 specification" because it hasn't actually executed  a scenario?

**Comment by sriv** [comment]
I would like to think of a case when such files co-exist with valid spec files having complete scenarios. I feel skipping these files silently would be better then.
