### ISSUE TITLE
How to enable / disable the row in data table and scenario wise data pick

### ISSUE THREAD

**Issue by Vishnu1067** [getgauge/gauge#604]
### Expected behavior
1. I have to enable or disable the row in data table for execution.
 For ex: i have 4 rows in data table and 4th row need to disable for a while in execution. How to disable them.

2. I have 3 scenarios in a spec and i want to use some rows should specific to scenarios. How to map rows to scenarios?

### Gauge version
```
Gauge version: 0.8.1

Plugins
-------
html-report (3.1.0)
java (0.6.1)
spectacle (0.1.0)
xml-report (0.2.0)
```

**Comment by Apoorva-GA** [comment]
Hi,

**1. You can execute your scenarios against selected data table rows.**

For example :
gauge --table-rows "1" specs/hello.spec
gauge --table-rows "1,4,7" specs/hello.spec

You can also specify the range of rows against which you want to execute your scenarios.

Ex :
gauge --table-rows "1-3" specs/hello.spec

Please refer Docs for more details : https://docs.getgauge.io/using.html?highlight=data%20table#data-driven-execution


**2. To run a scenario against a data table row** 
Note : We have a issue in progress for mapping scenarios and data table rows:https://github.com/getgauge/gauge/issues/306

The work around that you can try is:
 ```
Specification Heading
=====================
     |id|name     |
     |--|---------|
     |1 |vishnu   |
     |2 |prateek  |
     |3 |prateek  |



first Scenario
--------------
* Say "foo" to "nar"

Second Scenario
---------------
* Say foo "namaste" to <name>
```
Example :  gauge --table-rows "3" specs/example.spec:11 

The above command runs first scenario(at line number 11) against data table row 3.

**Comment by Apoorva-GA** [comment]
Hi,

If you have any questions there is no need to create an issue, you can ask the same in our forum. 

https://gitter.im/getgauge/chat
https://groups.google.com/forum/#!forum/getgauge

**Comment by Vishnu1067** [comment]
@Apoorva-GA , I am running test scenarios in jenkins using the tags. In this case, i cannot specify which row should run for only specific scenario. If we have a feature to disable / enable the rows, it will be helpful.

**Comment by Vishnu1067** [comment]
@sriv As mentioned the chat, the below points are my thoughts for data driven. Please correct me if i am wrong.

1. We shall have a data table with aligned rows and columns. For now, if one row have long string, have to adjust the columns.

2. Shall have a default first column (when create the table) for enable / disable checkbox. Based on these check test scenario would run.

3. Shall have another default column (when specify more than one scenario in spec ) to map the scenarios to the particular row. This feature can allow more than one scenario mapping. If not mapped, the row will apply for all the scenarios in the spec.

(Mostly test scenarios will run on jenkins based on the tags (@smoke, @regression) and test will trigger wherever the tag matched. In this situation, when we mentioned job with --table--row syntax, it will specific to the spec which means one spec = one job on jenkins.)

**Comment by ab-yz** [comment]
I would suggest to indeed do this with tags.
Tags are already used in gauge for filtering and execution, so expand the usabiltiy of tags by giving the possibility for a specific columnheader, say "tags:", just like you can use the keyword "tags:" right under a specification for comma separated tags.
If the first columnheader found is "tags:", the rows of this datatable will be executed based on the tag(s) present on each particular row. The matching may be done the same way as is now the case for specifications/scenarios with & and |. This would give way for the usecase of "toggling execution on/off", but even allow for much more.

In the above example the rows to be executed on jenkins would get the tags @smoke and @regression, the rows not to be executed on jenkins would not get the tags.
Probably you would give jenkins its own tag to manage jenkins runs, smoke and regression may apply no matter in which env specs are to be executed, to only switch scenarios on/off for jenkins.

This could be done for data tables specification wide and for step datatables.

Building further on this, you could apply similar mechanism for envs, which also already is a given feature of gauge, by giving the possibility for another keyword column header say "env:". If this header is present, entries in that column must be names of envs like with --env on commandline and rows will be executed corresponding with env.

Not knowing if this is technically feasable, but from my personal user perspective this would be a dream of testing flexibility come true.

The link above to an issue "for mapping scenarios and data table rows:#306" led to an issue over parallelized execution of rows, as far as I understand not for mapping. If this exists elsewhere I haven't seen it.

This may be relevant for issue #415 "Provide a mechanism to specify table rows per specification/scenario in execution" from @kashishm , too. That feature probably also already may be realized with above idea. From example given there, "gauge specs/example.spec:3[1,4]" to execute "3rd scenario in example.spec against 1-4 rows from data table" would translate to a specific tag which is present on the 3rd scenario and on rows 1,2,3,4 of data table, but not on a probable row 5-8. Tags would be easier to maintain in case a scenario would get added and the desired scenario would become the 4th, same goes for rows.

Also there was a question on gitter which may be addressed with this https://gitter.im/getgauge/chat?at=58875c8b074f7be7630f74b5 by use of tags on a datatable or even prevented with a column env.

This got a bit much, I guess I could use something like this a lot ;-)

**Comment by sriv** [comment]
@ab-yz @Vishnu1067 - thanks for the feedback and thoughts. All very well thought of, I really appreciate such insights.

Just wanted to say, I need to get my head around this a little bit more, and will put a proposal to address this. Perhaps we can then iterate on a acceptable solution.

I am a little worried about the use of tags here, as I feel this is not a tagging/classification problem, so this could lead to a potential tag explosion!

Clearly, this needs to be such that the filters are applicable at a micro as well as a macro level, allowing user to use this at a specific spec/scenario level and also at the suite level. Perhaps it should even allow the user to define this at the time of authoring, rather than at the time of execution?

**Comment by sriv** [comment]
I have a proposal - allow table driven execution for scenarios. Please see #111. This will allow users to specify data against which a scenario will get executed.

So rather than having a common datatable at Spec level and trying to slice/dice it per scenario, user would get the option of specifying exactly which data to use for every table.

Here are my thoughts on benefits of doing this:

- Scenario and its data are together, thus making it not only easy to read, but also easy to debug
- No unnecessary filter/conditions to decide which dataset to run scenario against.
- Given that table can be externalized (i.e. via a csv), it makes it easier to not have rules in the data (i.e. tags etc)
- Helps keep the dataset clean and not scatter it with meta information. This makes regeneration of data much simpler (ex. query a DB and write out a csv).

Thoughts? 

/cc @Vishnu1067 @ab-yz

**Comment by Vishnu1067** [comment]
@sriv , I agreed with your thought to keep table driven for scenarios. If this feature release as soon, it would be great for me. Could you tell me estimation time for this feature?

**Comment by ab-yz** [comment]
@sriv Just to fully get this: how would this go together with the current implementation of tables for steps?
Right now, if I write a table under a step the values are passed as special table parameter.
Would those special table parameters be kept and the feature of table driven execution for scenarios would be added on top? Or would the new feature of  table driven execution for scenarios replace the current step tables? Or that you should use only one or the other in a given scenario?

**Comment by ab-yz** [comment]
@sriv Then it's clear, thank you. Sorry being late.

I think your proposal is certainly something worth to have and complements perfectly gauges existing features.

On the other hand, I saw the jenkins example above more like an environment issue: run it in one environment, don't run that data in the other env (or with different data).

Personally I'm looking  for possibilities regarding different data for different envs, so when I read "scenario wise data pick" I was assuming different sets of data for scenarios without necessarily running one scenario multiple times with different sets (table driven = rows) of data.

Regarding #604 - if running one scenario several times with data from a row from an new scenario specific table solves the original request, I guess probably I'm on the wrong ticket here and my thoughts are a different ticket.

**Comment by sriv** [comment]
@ab-yz - Ah, now I see the overlap. You are probably thinking about #586, where @aredz wanted to have a dataset per environment. Please see if there are ideas that you can borrow.

I believe this issue should focus on enabling a scenario to run multiple times, once per row of table it is associated with, and not related to environments.

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
