### ISSUE TITLE
dotnet core support.

### ISSUE THREAD

**Issue by gbaligh** [getgauge/gauge#607]
Hi,

Want to know if there is a Gauge runner that support dotnet core ?
I tested it using mono and it is really great, but I think that using dotnet core make it more portable.

Thanks.

**Comment by sriv** [comment]
There isn't a runner that supports .net core at the moment.

Looks like .net core has support for [System.Reflection](https://docs.microsoft.com/en-us/dotnet/core/api/system.reflection) API, which was not complete last I checked.

@gbaligh - would you be interested in giving this a shot? The Gauge team would be happy to help in any way we can. At the moment, we are focused on Gauge Core features.

**Comment by gbaligh** [comment]
Thank you for your answer.
I will try to look at that.

**Comment by sriv** [comment]
gauge dotnet core support is available via github.com/getgauge/dotnet

- Nightly build is available here: https://bintray.com/gauge/gauge-dotnet/Nightly

**Comment by sguptatw** [comment]
On Windows
**Test Cases**
- [x] Should be able to create gauge-dotnet project
Use `gauge install dotnet`
- [x] Should be able to run specs
Use `gauge run specs`.
- [x] Should be able to run specs in parallel
Use `gauge run specs -p`.
- [x] HTML Report should be generated
- [x] XML Report should be generated

> Note: Currently FTs of gauge-dotnet run only for Windows.
> Note: Format, Run specs can be used for VSCode as well

**Suggestion**
- Pre-requisite `dotnet core sdk` can be updated in the readme of https://github.com/getgauge/gauge-dotnet

**Issue**
- [ ] When a specification is executed, console messages should be minimum - https://github.com/getgauge/gauge-dotnet/issues/1

**Comment by sguptatw** [comment]
On Mac OS
**Test Cases**
- [ ] Should be able to create gauge-dotnet project
- [ ] Should be able to run specs
- [ ] Should be able to run specs in parallel
- [ ] HTML Report should be generated
- [ ] XML Report should be generated
- [ ] format
- [ ] Refactor
- [ ] Parse errors
- [ ] Continue on Failure

**Issues**
- [ ] Should be able to create a project - https://github.com/getgauge/gauge-dotnet/issues/2

**Comment by gbaligh** [comment]
Great 😄
