### ISSUE TITLE
Intellij plugin fails to initialize existing gauge project

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge#611]
### Expected behavior
It should not fail to initialize while creating a new project in a directory with gauge specs 

### Actual behavior
Error while initializing
![errorscreen](https://cloud.githubusercontent.com/assets/54427/24288494/a0812b84-10a3-11e7-9375-dbded47ad880.png)

### Steps to reproduce
1. ` gauge --init java_maven_selenium `
2. Create a new gauge project and specify the folder where you created the gauge project using template

### Gauge version
```
Gauge version: 0.8.2

Plugins
-------
html-report (3.1.0)
java (0.6.1)
python (0.2.0)
ruby (0.4.0)
spectacle (0.1.0)

```

**Comment by kashishm** [comment]
This issue was moved to getgauge/Intellij-Plugin#240
