### ISSUE TITLE
0.8.2 Installation issue on Linux

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge#612]
### Expected behavior
With gauge 0.8.2 `gauge --install java` should install the latest version of gauge-java.

### Actual behavior
```bash
Failed to get configuration from Gauge properties file. Error: open /root/.gauge/config/gauge.properties: no such file or directory
```

### Steps to reproduce
1. apt-get install -y gauge
2. gauge --install java

### Gauge version
0.8.2

Looks like side affect of https://github.com/getgauge/gauge/issues/544

**Comment by BugDiver** [comment]
@haroon-sheikh Can you please check your `GAUGE_ROOT` environment variable? Make sure it's empty or points to the location where the `gauge` configurations are. By default, the configuration should be at `$HOME/.gauge/config`.

**Comment by haroon-sheikh** [comment]
@BugDiver `GAUGE_ROOT` env variable is empty.

**Comment by BugDiver** [comment]
@haroon-sheikh The new installers copies `gauge` configuration files to `$USER` level.
Some steps which might resolve your issue:- 
* Run `gauge_setup` after installation.
* check permissions for your `.gauge` dir. If  It or It,s children directories doesn't have user permissions, Please remove your `.gauge` repo and do the installation again.

**Comment by haroon-sheikh** [comment]
v0.8.3 fixes this issue.
