### ISSUE TITLE
gauge_setup failed on Ubuntu 16.04 (v0.8.2)

### ISSUE THREAD

**Issue by samuel-phan** [getgauge/gauge#615]
### Expected behavior
After installing Gauge for Ubuntu, we should be able to run `gauge_setup` without any error.

### Actual behavior

When I run `gauge_setup` I got this output & error:

```
$ gauge_setup 
Creating /home/sphan/.gauge/config
Copying gauge configuration files to /home/sphan/.gauge/config
Gathering metadata for html-report
2017/03/27 12:03:05 Failed to get configuration from Gauge properties file. Error: open /usr/local/gauge.properties: no such file or directory
Failed to install plugin 'html-report'.
Reason: Could not construct plugin install json file URL. Could not find gauge repository url from configuration.
```

### Steps to reproduce

Install Gauge following the guide here: https://docs.getgauge.io/installing.html#on-debian-ubuntu, i.e.:

1. Add the Gauge deb repo:
```
sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B
echo deb https://dl.bintray.com/gauge/gauge-deb stable main | sudo tee /etc/apt/sources.list.d/getgauge.list  # I prefer to have a separated file for the Gauge repo
```
2. Install Gauge:
```
sudo apt-get update
sudo apt-get install gauge
```
3. Run:
```
gauge_setup
```

### Gauge version

```
$ gauge -v
Gauge version: 0.8.2

Plugins
-------
No plugins found
Plugins can be installed with `gauge --install {plugin-name}`
```

### OS version

```
$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="18.1 (Serena)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.1"
VERSION_ID="18.1"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=serena
UBUNTU_CODENAME=xenial
```

**Comment by samuel-phan** [comment]
Sorry, I found the culprit. I installed Gauge throught the zip first, since it was the first way given by the documentation. This installation using the script `install.sh` is messy, as it has no way to uninstall Gauge properly, and I didn't see that it appended this line in my `~/.profile`.

```
export GAUGE_ROOT=/usr/local
```

The documentation of the Getting Started should give first the way to install through RPM/deb instead of 
the zip way.

**Comment by BugDiver** [comment]
@samuel-phan Thanks for sharing the information to troubleshoot this issue. It will help others.
We will consider your suggestion for documentation. For any further documentation related issue, please raise an issue [here](https://github.com/getgauge/docs.getgauge.io).
