### ISSUE TITLE
Installation : Mac OSX - Latest gauge installation is missing gauge.properties

### ISSUE THREAD

**Issue by akanksha4lal** [getgauge/gauge#616]
I recently did a fresh install on new mac os machine. I tried both brew and local install. Both of them are missing gauge.properties

### Expected behavior
No error should be thrown

### Actual behavior
Getting error
```
2017/03/27 10:20:57 Failed to get configuration from Gauge properties file. Error: open /usr/local/Cellar/gauge/0.8.2/gauge.properties: no such file or directory
```

### Steps to reproduce
1. Run gauge specs

### Gauge version
```
Gauge version: 0.8.1

Plugins
-------
html-report (3.1.0)
java (0.6.1)
python (0.2.0)
xml-report (0.2.0)
```

**Comment by BugDiver** [comment]
@akanksha4lal We did some changes in our installers, which affected to the `brew` installation. We'll try to fix it as soon as possible. You can install `gauge` using  [pkg installer](https://getgauge.io/get-started.html) for mac.

**Comment by kashishm** [comment]
@akanksha4lal We have fixed Gauge brew formula. Please update gauge to 0.8.3 `brew upgrade gauge`.
