### ISSUE TITLE
Inconsistent console reporting with UTF-8 chars 

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#621]
**Expected Behavior**
With UTF-8 chars in the spec. The console reports should be consistent.

**Actual behavior**
* In powershell - When the step is unimplemented the UTF-8 chars are getting printed. However if the step is implemented then there are `????`
![screen shot 2017-04-03 at 2 51 03 pm](https://cloud.githubusercontent.com/assets/6310197/24603934/70483e5a-1880-11e7-8614-8b5d2b1f475a.png)

* Furthermore for the same project on simple command line. The validation error does not get printed when UTF-8 char is used.
<img width="716" alt="screen shot 2017-04-03 at 3 10 57 pm" src="https://cloud.githubusercontent.com/assets/6310197/24603954/86502afa-1880-11e7-886a-3f5f845912cc.png">

**Steps to replicate**
[GaugeProject2.zip](https://github.com/getgauge/gauge/files/889630/GaugeProject2.zip)
* Run without implementation of `* search user "администрптор"`
* run this project from powershell command line
* run this project from simple command line.
* Run with implementation of `* search user "администрптор"`
* run this project from powershell command line
* run this project from simple command line.

**Version**
```
Gauge version: 0.8.3.nightly-2017-03-31

Plugins
-------
csharp (0.10.1.nightly-2017-02-17)
html-report (3.1.0)
java (0.6.2.nightly-2017-03-16)
```

**Comment by sguptatw** [comment]
Issue replicable in

Update the gauge csharp lib to the latest before executing
```
Gauge version: 1.0.1.nightly-2018-07-31
Commit Hash: 4ae7c9a

Plugins
-------
csharp (0.10.5.nightly-2018-07-24)
```

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
