### ISSUE TITLE
Unable to uninstall using choco

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#622]
**Expected behavior**
If I have installed Gauge using `choco`, I should be able to uninstall it using choco.

**Actual behavior**
Though choco says Skipping auto uninstaller. However it also says successfully uninstalled. But, Gauge is still present.

![screen shot 2017-04-03 at 4 11 01 pm](https://cloud.githubusercontent.com/assets/6310197/24605977/b986a23e-1888-11e7-85a7-a3f110a109c5.png)

**Steps to replicate**
* Install Gauge using choco.
* check installation using `gauge -v`
* Now uninstall gauge using `choco uninstall gauge`
* now check `gauge -v`

**Version**
```
Gauge version: 0.8.3

Plugins
-------
html-report (3.1.0)
```

**Comment by sguptatw** [comment]
Yes, there is only one installation of Gauge. This was done using chocolatey.

```
>where gauge
C:\Program Files\Gauge\bin\gauge.exe
```

**Comment by sriv** [comment]
@sguptatw - is this still valid?

**Comment by sguptatw** [comment]
Working as expected with `Gauge version: 0.9.2.nightly-2017-08-11`
