### ISSUE TITLE
Add a step failure hook

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge#623]
### Feature
Add a new hook ```OnStepFailure``` that can be used to perform specific tasks in case of step failure.

This works similar to the other [hooks](https://docs.getgauge.io/language.html?highlight=hook#id10) 
For e.g.

```
@OnStepFailure
  public void onStepFailure() {
     // Code for some task when any step fails.
 }

```

**Comment by SreejithShenoi** [comment]
Is is possible to get the failure reason, along with the stack trace of the failure as well in this.

We are trying to use gauge as our  execution engine and will be triggered from an application. So in the application log we would need the exception message along with the stack trace to log the test failure reasons for logging purposes. It would be very convenient if this information is passed into this method.
Or if there is any other method for getting the failure reason and stack trace for a failed gauge test during run time, please let me know.

**Comment by nehashri** [comment]
@SreejithShenoi The errors are reported in the console, as well as in gauge.log file. Is this information not enough?

**Comment by SreejithShenoi** [comment]
@nehashri 
No we are looking a way to get this information for gauge execution engine during run time. Is there a way we can hook on to logs from gauge, is there any event to which we can register? We need to get this information on to the report generated by the application which triggers gauge execution. 
Can we have an event raised by gauge in case of failures, with the information requested above being passed as event arguments?

**Comment by nehashri** [comment]
@SreejithShenoi from the use case you have described, you may not need a step failure hook. You could use AfterStep hook, use ExecutionInfo and get the required details. ExecutionInfo should have all relevant details of Step and failures if any.
ExecutionInfo is not yet available in C#, there is an issue for this [here](https://github.com/getgauge/gauge-csharp/issues/53)

**Comment by SreejithShenoi** [comment]
@nehashri 
Thanks for the information. Is there any plan when ExecutionInfo will be available for C# as well?
Also will ExecutionInfo  be available for Execution hooks like AfterScenario(),AfterSpec etc as well?
Can you please point to a sample code where in ExecutionInfo has been used in the implementation? Jav a implementation also should be fine.

**Comment by nehashri** [comment]
@SreejithShenoi Yes it will be available for AfterScenario and AfterSpec hooks too. We do not have an example project using these methods. Here is a java code snippet using this though. 
```java
    @AfterStep
    public void afterStep(ExecutionContext context) {
        if (context.getCurrentStep().getIsFailing()) {
            System.out.println(context.getCurrentStep().getStackTrace());
        }
    }
```

**Comment by SreejithShenoi** [comment]
@nehashri 
Thanks a lot for the snippet. Now it gives better clarity. When this would be available for C#?

**Comment by nehashri** [comment]
What we are discussing is a separate issue tracked here - https://github.com/getgauge/gauge-csharp/issues/53. Any comments/suggestions regarding the current issue `Add a step failure hook` is welcome here.

**Comment by sguptatw** [comment]
Closing this issue. Alternate approach suggested is to use the AfterStep hook and getIsFailing method.
