### ISSUE TITLE
DataTable row validation to consider scenarios not using table values.

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#624]
## Expected behavior
When executing specs with `--table-rows` parameter, the spec having data tables but with scenarios not using the values should behave similar to the spec having no data tables.

Ideally, the `--table-rows` should have no effect on specs/scenarios that do not use table rows.

## Actual behavior
The spec with data table does not get executed. The spec having data tables but with scenarios not using the values are getting executed.

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
