### ISSUE TITLE
BadImageFormatException thrown for dependency dll which is managed c++

### ISSUE THREAD

**Issue by nfiroz** [getgauge/gauge#626]
### Expected behavior
No exception thrown, or continue with ignoring the exception.

### Actual behavior
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly or one of its dependencies. An attempt was made to load a program with an incorrect format.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, 
[CallStack.txt](https://github.com/getgauge/gauge/files/918187/CallStack.txt)

### Gauge version
```
Gauge version: 0.8.1

Plugins
-------
csharp (0.10.0)
html-report (3.1.0)
spectacle (0.1.1)
xml-report (0.2.0)
```

**Comment by sriv** [comment]
Could you please share some more details to help debug this?

`BadImageFormatException` occurs when the architecture against which an assembly to be loaded was compiled is different from the host architecture. Classic example : load an x86_64 assembly in x86 machine.

Your description does not have enough information for any of us to narrow down the cause. Perhaps if you can share a sample project which has this issue?

**Comment by nfiroz** [comment]
Sorry, I forgot to mention that. All assemblies are compiled for x64. and machine is also 64 bit.
I tried with both 32 bit and 64 bit versions of Gauge too.
I will try to create a sample project.

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
