### ISSUE TITLE
Invoking command line with multiple tags not finding specs

### ISSUE THREAD

**Issue by anupmanekar** [getgauge/gauge#627]
Referring: https://docs.getgauge.io/using.html#tagged-execution

### Expected behavior
Invoking below command line 
`gauge --tags rest,ui specs `
This should ideally execute specs tagged with either of "rest" or "ui". 
### Actual behavior
Invoking below command line 
`gauge --tags rest,ui specs `
This is currently not finding any specs. 
Independently able to execute both tagged specs
`gauge --tags rest specs `
`gauge --tags ui specs`

### Gauge version
0.8.3
64-bit Windows 7

**Comment by kashishm** [comment]
@anupmanekar It is working as expected for me on mac. I am not sure why it is not working for you. You could try putting the tag expression in quotes and then try running the command `gauge --tags "rest,ui" specs`.

**Comment by anupmanekar** [comment]
@kashishm I have tried all possible combinations. In single quotes, double quotes, with comma, without comma.. but to no avail :(

**Comment by afeique** [comment]
@anupmanekar 

Referring [Gauge docs](https://docs.getgauge.io/using.html#tagged-execution):

> `gauge --tags "tag1, tag2" specs`
> This executes only the scenarios and specifications which are tagged with tag1 **and** tag2.

What you said:

> Invoking below command line
> `gauge --tags "rest,ui" specs`
> This should ideally execute specs tagged with **either** of "rest" **or** "ui"**.

Correct me if I'm wrong, but it appears you misunderstood the Gauge documentation -- the comma separation combines the tags using logical AND and is equivalent to:

`gauge --tags "rest&ui" specs`

To filter a set of tags using logical OR, use:

`gauge --tags "rest|ui" specs`

Verified working on Windows 7 x64, Gauge 0.8.5.

HTH

**Comment by sguptatw** [comment]
Closing this issue. Please feel free to reach us on https://gitter.im/getgauge/chat if you have more questions.
