### ISSUE TITLE
Reporting improvement on table failure

### ISSUE THREAD

**Issue by Vishnu1067** [getgauge/gauge#629]
### Expected behavior
When test is failed, row should mark red for failed test.

### Actual behavior
Step marked as failure instead of specific row.

### Steps to reproduce

Example Scenario:

* Login to application
* Search shop
   |search type| search name|
   |location      | New York      |
   |ShopName | XYZ               |
   |Item Name | Mobile           |
* Logout from application

Assume that Shop name test iteration is failed and it has to mark as Red color in report. But step has been marked as red. 

### Gauge version
```
Gauge version: 0.8.3

Plugins
-------
csharp (0.10.0)
html-report (3.1.0)
java (0.6.2)
ruby (0.4.0)
spectacle (0.1.0)
xml-report (0.2.0)

```

**Comment by sriv** [comment]
The scenario you describe is not table driven execution. Rather you seem to have a step that takes in a table parameter.

Table driven execution illustration: https://docs.getgauge.io/using.html#data-driven-execution

In your scenario, gauge executes a step, which happens to take a table as a parameter. It is up to the implementation to decide what to do with it. Gauge has no context or control on the implementation, rather it only tracks the step's execution.

**Comment by Vishnu1067** [comment]
I am using table as a parameter. When i have 10 rows in a table, i dont know which row is failed while looking into the reports.

**Comment by sriv** [comment]
I'm afraid what you are asking is not possible. Here's why:

The `table` parameter serves a different need than "table driven execution". Typically it is used to send complex data to step, i.e something that cannot be represented using primitives such as `string` or `int`. 

Hence Gauge does not treat the `table` parameter any different, and does not report at `table row` level.

#### Alternatives

- Use Custom Message to write extra information (like what @aredz suggests in the [gitter chat](https://gitter.im/getgauge/chat?at=58f7113ff22385553d556505).)

- Convert this scenario into Table driven. An example would be:

```
# Multi Search 

|search type| search name|
|location | New York |
|ShopName | XYZ |
|Item Name | Mobile |

## Search after login

- Login to application
- Search shop <search type> <search name>
- Logout from application

```

**Comment by Vishnu1067** [comment]
Yes, I would like to do table driven. since there is an enhancement pending for scenario table driven, I am waiting for release. I will wait for that and will modify my scenario later.

**Comment by Vishnu1067** [comment]
And also, we cannot write custom failure message to gauge right? Gauge.WriteMessage(boolean, message)

**Comment by sriv** [comment]
`Gauge.WriteMessage` does not carry any state, just content. So you cannot mark it as `pass` or `fail`.

**Comment by Vishnu1067** [comment]
Ok, Please close this issue (invalid).
1. Please update me when this feature [604](https://github.com/getgauge/gauge/issues/604) will be released. 
2. Is there any custom gauge message to make test fail?

**Comment by sriv** [comment]
> Please update me when this feature 604 will be released.

Sure.

> Is there any custom gauge message to make test fail?

No, but if your implementation throws an exception, Gauge will mark the step as failed. 

Closing this issue. Thanks.
