### ISSUE TITLE
Command to take screenshot during test execution

### ISSUE THREAD

**Issue by jgwilson42** [getgauge/gauge#632]
This is a feature request.

### Expected behavior

I would like to be able to take a screenshot at a specific point in the test execution. In the same way that I can use `Gauge.writemessage()` I would like a command like `Gauge.screenshot()` .

Currently I am using the following to write the screenshot to the disk, it would be much better to include the screenshot in the gauge report.

### Gauge version
```
Gauge version: 0.8.3

Plugins
-------
html-report (3.1.0)
java (0.6.2)
```

**Comment by sguptatw** [comment]
@jgwilson42 The following is a workaround. Let me know what you think.
How about using Gauge.writemessage to print the path of the screenshot captured. So while browsing the report, the screenshot can be opened manually using the path specified.

**Comment by jgwilson42** [comment]
Interesting approach. Assuming this works with relative paths this would be fine. The reason for needing relative paths is that the tests are run from travis and then the report is zip'd up and moved to google storage.

**Comment by nomade** [comment]
So, I was needing take screenshot for each step, then, I use Selenium to take picture and use Gauge.writeMessage to add image in report. It's working for me.

```
@AfterStep
public void screenshot() {
	try {
		Thread.sleep(10);
		takesScreenshot(String.valueOf(System.currentTimeMillis()));
	}catch (Exception e) {
		e.printStackTrace();
	}
}
```

```
public void takesScreenshot(String pictureName) {
    	try {
    		String fileName = "images/"+MessageMd5.md5(pictureName)+".png";
    		File file = new File("reports/html-report/"+fileName);
    		if(file.exists()) {
    			file.delete();
    		}
    		File scrFile = ((TakesScreenshot)browser).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile, file);
		Gauge.writeMessage("<img src='../"+fileName+"' width='800' height='480'");
		} catch (IOException e) {
			e.printStackTrace();
		}
}
```

Another approach, I created a step to take screenshot between scenarios.

```
@Step("Take a screenshot with the name <pictureName>.")
public void takesScreenshot(String pictureName) {
    	try {
    		String fileName = "images/"+MessageMd5.md5(pictureName)+".png";
    		File file = new File("reports/html-report/"+fileName);
    		if(file.exists()) {
    			file.delete();
    		}
    		File scrFile = ((TakesScreenshot)browser).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scrFile, file);
		Gauge.writeMessage("<img src='../"+fileName+"' width='800' height='480'");
		} catch (IOException e) {
			e.printStackTrace();
		}
}
```

Congratulations Gauge team, it's a fantastic application, I imagine incredible possibility of using this tool like: Automation Test, Performance Test, Load Test, Functional Specification...

**Comment by sriv** [comment]
I am going to start work on this.

Notes:

- Gauge shall expose a `screenshot` api via language runners. For ex. gauge-ruby shall have `Gauge.capture_screenshot` .
- Mechanism to capture the screenshot: The behaviour would be the same as capturing the screenshot for failures:
  - By default gauge will capture the active desktop (using the screenshot plugin)
  - CustomScreenshotGrabber will be used when configured.
  - `screenshot_enabled` property will be honoured. Disabling screenshots will result in no screenshots (failure or otherwise)
- Reports: The screenshot will be shown similar to the failure screenshots. These shall be inlined as a `base64` image, and hence will not be available as a separate file.

Thoughts/Feedback welcome.

**Comment by ajoecker** [comment]
reason for not have them as separate files ?

**Comment by sriv** [comment]
Mostly historic. It used to be a single page application, but had performance issues when loading huge suite results. We did not externalize the screenshots when we used the Golang templating.

So, given the current implementation, it is simpler to include the screenshots as inline base64 images. I would like to know if the preference is to have files.

**Comment by ajoecker** [comment]
personally yes. when filing e.g. a bug ticket i do not need to somehow link the whole report with all its files, but can simply add this one screenshot that shows the failure to the ticket

**Comment by sriv** [comment]
Language runner support:

- [ ] [gauge-csharp](https://github.com/getgauge/gauge-csharp/issues/137)

**Comment by sriv** [comment]
Should be available in nightly >= 18/07/2018
