### ISSUE TITLE
Getting an Failed to initialize scenario datastore

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#633]
**Steps to replicate**
* Run the command from the command line
[art 2.zip](https://github.com/getgauge/gauge/files/957307/art.2.zip)

```
mvn gauge:execute -DspecsDir=specs/one -DinParallel=true
```
Getting the following error
Failed to initialize scenario datastore. Error: write tcp 127.0.0.1:49693->127.0.0.1:49704: use of closed network connection

**Comment by kashishm** [comment]
This is happening because the tests are running in parallel using threads and The `Gauge.writeMessage` code is not thread safe.

**Comment by kashishm** [comment]
This issue was moved to getgauge/gauge-java#88
