### ISSUE TITLE
Not executing the context step

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#637]
Execute from command line or IDE, the context step Open the Gauge homepage <param> is not getting executed. 

[art 2.zip](https://github.com/getgauge/gauge/files/957760/art.2.zip)

**Version**
```
Gauge version: 0.8.4.nightly-2017-04-20

Plugins
-------
html-report (4.0.0.nightly-2017-04-20)
java (0.6.3.nightly-2017-04-21)
xml-report (0.2.0)
```

**Comment by Apoorva-GA** [comment]
Hi,
Fix is available in nightly version : `0.8.4.nightly-2017-04-26`.
