### ISSUE TITLE
The information about feature toggle settings should be available to the user

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#646]
**Expected Behavior**
Need one place to know the features settings that can be toggled in Gauge.

**Actual behavior**
Currently we have to refer to release notes or documentation.

**Suggested approach**
Gauge About can have the list of the feature toggles available in Gauge.

**Comment by sriv** [comment]
`gauge config --list` now shows the list of global configuration, project level configuration should be available in `env` properties.

Is there anything else to be done?
