### ISSUE TITLE
The examples of Gauge should run on CI

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#647]
Currently any issues on the example project are discovered late. We have to set up a pipeline to run the Gauge examples and get faster feedback.

**Comment by sguptatw** [comment]
**Expected behavior**
We should have at-least one green build for all the active examples.

**Actual behavior**
https://travis-ci.org/getgauge-examples/ruby-selenium is failing for chrome permission issue.

**Comment by sriv** [comment]
@sguptatw - does this still need attention?
