### ISSUE TITLE
Steps are showing in red colour in the specification file 

### ISSUE THREAD

**Issue by osandadeshan** [getgauge/gauge#650]
I have created a gauge project. The steps are showing in red color in the specification file. But those steps have step implementations. If I run the specification file although it is in red, it works fine. I just wanted to remove the red underlines of the test steps in specification file.

### Expected behavior
Test steps should not have underlined in red

### Actual behavior
Test steps are underlined in red

### Gauge version
Gauge version: 0.8.0

### Plugins
-------
csharp (0.10.0)
html-report (3.1.0)
java (0.5.0)
ruby (0.4.0)
xml-report (0.1.3)

**Comment by sguptatw** [comment]
@osandadeshan : Which IDE are you using?

**Comment by osandadeshan** [comment]
Hi Soumya,
I was using IntelliJ IDEA Community Edition. I solved this issue by uninstalling the current version and reinstalling the latest version.

**Comment by sguptatw** [comment]
Thanks for letting us know that it is working for you now. Closing this issue.
