### ISSUE TITLE
Problem with execution of specs in alphabetical order since update to gauge 0.8.4

### ISSUE THREAD

**Issue by kupna** [getgauge/gauge#652]
Before we updated to gauge Version 0.8.4 we never set any flag for the execution order. But since update the execution order of the specifications seems to be random.

Now I set the flag like that:
gauge "--tags=\"install|restrictedmode\"" ./specs --verbose --order=sort

And hoped that now the execution would be alphabetical again. But unfortunately it is a random order and every run is different, no mattter if the order flag is set or not.

We intentionally added numbers at the beginning of the specification name, but this does not seem to work anyway. How can I get a non random execution order again?

### Expected behavior
alphabetical execution of specifications

### Actual behavior
random execution of specifications

### Steps to reproduce
1. run gauge with gauge "--tags=\"install|restrictedmode\"" ./specs --verbose --order=sort
2. for this tag there are three specifications found: 001 Engage installation, 005 Restricted mode, 007 Reschedule Jobs
3. This specifications should be executed in the following order
001 Engage installation
005 Restricted mode
007 Reschedule Jobs
4. But they are executed like this:

### Gauge version
Gauge version: 0.8.4

Plugins
-------
html-report (4.0.0)
java (0.6.3)

`
[go] Task: gauge "--tags=\"install|restrictedmode\"" ./specs --verbose --order=sort
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2017-05-22 15:38:55,932 0    [Thread-1] INFO  com.infoniqa.engage.utils.BrowserFactory  - looking for sahi user data under path: C:\GoAgent\pipelines\engage-gauge-demo\engage.gauge\sahi\userdata
Mai 22, 2017 3:38:55 PM net.sf.sahi.config.Configuration reinitialize
INFORMATION: Sahi properties file = C:\dev\sahi_pro\config\sahi.properties
Mai 22, 2017 3:38:55 PM net.sf.sahi.config.Configuration reinitialize
INFORMATION: Sahi user properties file = C:\GoAgent\pipelines\engage-gauge-demo\engage.gauge\sahi\userdata\config\userdata.properties
2017-05-22 15:38:56,603 671  [Thread-1] DEBUG com.infoniqa.engage.utils.BrowserFactory  - start wait for proxy
2017-05-22 15:38:56,603 671  [Thread-1] INFO  com.infoniqa.engage.utils.BrowserFactory  - try waiting for sahi proxy
Mai 22, 2017 3:38:56 PM java.util.prefs.WindowsPreferences <init>
WARNUNG: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Mai 22, 2017 3:38:57 PM java.util.logging.LogManager$RootLogger log
INFORMATION: VALID LICENSE
---------------
Sahi Pro 1-User License
Licensed to: Infoniqa HR Solutions GmbH
Issued date: 21 Sep 2016
Expiry date: 21 Sep 2017
---------------

2017-05-22 15:38:57,774 1842 [Thread-1] INFO  com.infoniqa.engage.utils.BrowserFactory  - sahi proxy is not yet started
2017-05-22 15:38:57,785 1853 [Thread-1] INFO  com.infoniqa.engage.utils.BrowserFactory  - try waiting for sahi proxy
>>>> Sahi Pro v6.3.2 started. Listening on port: 9999
>>>> Configure your browser to use this server and port as its proxy
>>>> Browse any page and CTRL-ALT-DblClick on the page to bring up the Sahi Controller
Mai 22, 2017 3:38:58 PM net.sf.sahi.util.BrowserTypesLoader loadAvailableBrowserTypes
INFORMATION: 
-----
Reading browser types from: C:\GoAgent\pipelines\engage-gauge-demo\engage.gauge\sahi\userdata\config\browser_types.xml
-----

Mai 22, 2017 3:38:58 PM net.sf.sahi.util.Utils setUrlConnectionFollowRedirectsInternal
INFORMATION: urlConnectionFollowRedirectsInternal = false
Mai 22, 2017 3:38:58 PM in.co.sahi.datastore.SahiDB <clinit>
INFORMATION: Using Database:
driverName=org.h2.Driver
jdbcurl=jdbc:h2:C:/GoAgent/pipelines/engage-gauge-demo/engage.gauge/sahi/userdata/database/db0;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE
userName=sa
Using Connection Pool
2017-05-22 15:38:58,674 2742 [Thread-1] DEBUG com.infoniqa.engage.utils.BrowserFactory  - finished wait for proxy in 2070 ms
2017-05-22 15:38:58,814 2882 [Thread-1] INFO  com.infoniqa.engage.utils.BrowserFactory  - Launch browser chrome
Mai 22, 2017 3:38:58 PM in.co.sahi.distributed.BrowserType launchInstanceCommon
INFORMATION: Acquired available browser instance after retries:0  threadNo:0
sessionId:sahi_4e0e6f1c011ae04db50840e01e45a0c8b9f9
Mai 22, 2017 3:38:58 PM in.co.sahi.datastore.SahiDB createTables
INFORMATION: Check tables version
Mai 22, 2017 3:38:59 PM net.sf.sahi.test.ProcessHelper execute
INFORMATION: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --user-data-dir=C:/GoAgent/pipelines/engage-gauge-demo/engage.gauge/sahi/userdata\browser\chrome\profiles\sahi0 --proxy-server=localhost:9999 			--disable-popup-blocking --always-authorize-plugins --allow-outdated-plugins --enable-npapi --incognito "http://sahi.example.com/_s_/dyn/Driver_start?sahisid=sahi_4e0e6f1c011ae04db50840e01e45a0c8b9f9__SahiAmpersandSahi__startUrl=http%3A%2F%2Fsahi.example.com%2F_s_%2Fdyn%2FDriver_initialized%3FstartUrl%3D"
Mai 22, 2017 3:38:59 PM in.co.sahi.datastore.SahiDB createTables
INFORMATION: versionFromDB=2016-10-13 14:21:30
Mai 22, 2017 3:38:59 PM in.co.sahi.datastore.SahiDB createTables
INFORMATION: version=2016-10-13 14:21:30
Mai 22, 2017 3:38:59 PM in.co.sahi.datastore.SahiDB createTables
INFORMATION: At current version. No changes were done.
Mai 22, 2017 3:38:59 PM in.co.sahi.datastore.SahiDB createTables
INFORMATION: {result: [["SAHIKEY","SAHIVALUE"],["dbVersion","83"],["versionNo","2016-10-13 14:21:30"]]}
Mai 22, 2017 3:38:59 PM in.co.sahi.datastore.SahiDB createTables
INFORMATION: Finished preparing report tables: 513ms
# 001 Engage installation
  ## 001 Engage installation	Mai 22, 2017 3:39:00 PM net.sf.sahi.test.ProcessHelper$PIDGatherer run
INFORMATION: PIDs: [1272, 4796, 3396, 2076]; 1998 ms
 P2017-05-22 15:39:09,967 14035 [Thread-1] INFO  com.infoniqa.common.acceptance.EngageInstallation  - getUpdateLink
2017-05-22 15:39:09,968 14036 [Thread-1] INFO  com.infoniqa.common.acceptance.EngageInstallation  - link: updatePending.goToAdminLink.message
2017-05-22 15:39:10,484 14552 [Thread-1] INFO  com.infoniqa.common.acceptance.EngageInstallation  - link: zur engage Update Administrationsseite.
2017-05-22 15:39:11,100 15168 [Thread-1] INFO  com.infoniqa.common.acceptance.EngageInstallation  - link: the engage Update Administration site.
2017-05-22 15:39:11,619 15687 [Thread-1] INFO  com.infoniqa.common.acceptance.EngageInstallation  - update link exists: false
2017-05-22 15:39:12,244 16312 [Thread-1] INFO  com.infoniqa.common.acceptance.EngageInstallation  - no engage! update necessary
 P2017-05-22 15:39:12,248 16316 [Thread-1] INFO  com.infoniqa.common.acceptance.EngageInstallation  - wait for installation to be ready
2017-05-22 15:39:12,248 16316 [Thread-1] INFO  com.infoniqa.common.acceptance.EngageInstallation  - installation done!
 P P P2017-05-22 15:39:33,736 37804 [Thread-1] INFO  com.infoniqa.engage.login.LoginScreen  - User INFONIQA SUPERADMIN is logged IN.
 P

# 007 Reschedule Jobs
  ## 007 Reschedule Jobs	 P P P P P P

# 005 Restricted mode
  ## 005 Change System Settings	 P P P

Mai 22, 2017 3:40:07 PM net.sf.sahi.test.ProcessHelper kill
INFORMATION: Kill: [1272, 4796, 3396, 2076]
Successfully generated html-report to => C:\GoAgent\pipelines\engage-gauge-demo\engage.gauge\reports\html-report
Specifications:	3 executed	3 passed	0 failed	0 skipped
Scenarios:	3 executed	3 passed	0 failed	0 skipped

Total time taken: 1m12.601s
`

So what should I do to get the execution order alphabetically again?

thanks in advance.

Regards, 
Natalie

**Comment by kupna** [comment]
I am using multithreading - if that could have any inpact on my problem.

default.properties 
enable_multithreading=true

**Comment by sriv** [comment]
Hi @kupna , 

I noticed a couple of things:

- The flags should preceed the `./specs` in the command.
- The `--order=sort` should actually be `--sort`.

Could you please try this command:

```
gauge "--tags="install|restrictedmode"" --verbose --sort ./specs
```

**Comment by kupna** [comment]
@sriv 
I did not know, that the --order flag is not yet released, because you can find it in the options list, when you write gauge in the console:
`--order, -o=""                   Set the specs execution order. Possible options are: `random`, `sort`. Ex: gauge --order="random"`

when I use the --sort flag the console claims that it will be deprecated soon:

`This flag will be deprecated soon. Please use --order=sort instead.`

Before I updated to gauge 0.8.4 I did not need the --sort or --order flag the execute the specs alphabetically - what has happend?`

I have tried now with this command
`C:\dev\Gauge\bin\gauge.exe --simple-console --tags "install|restrictedmode" --sort C:\projects\engage.gauge\specs`

And it is still not executed alphabetically:

C:\dev\Gauge\bin\gauge.exe --simple-console --tags "install|restrictedmode" --sort C:\projects\engage.gauge\specs
This flag will be deprecated soon. Please use --order=sort instead.
2017-05-23 09:57:46,439 0    [Thread-1] INFO  com.infoniqa.engage.utils.BrowserFactory  - looking for sahi user data under path: C:\projects\engage.gauge\sahi\userdata
Mai 23, 2017 9:57:46 AM net.sf.sahi.config.Configuration reinitialize
INFORMATION: Sahi properties file = C:\dev\sahi_pro\config\sahi.properties
Mai 23, 2017 9:57:46 AM net.sf.sahi.config.Configuration reinitialize
INFORMATION: Sahi user properties file = C:\projects\engage.gauge\sahi\userdata\config\userdata.properties
2017-05-23 09:57:46,555 116  [Thread-1] DEBUG com.infoniqa.engage.utils.BrowserFactory  - start wait for proxy
2017-05-23 09:57:46,555 116  [Thread-1] INFO  com.infoniqa.engage.utils.BrowserFactory  - try waiting for sahi proxy
Mai 23, 2017 9:57:46 AM java.util.logging.LogManager$RootLogger log
INFORMATION: VALID LICENSE
---------------
Sahi Pro 1-User License
Licensed to: Infoniqa HR Solutions GmbH
Issued date: 21 Sep 2016
Expiry date: 21 Sep 2017
---------------

2017-05-23 09:57:47,572 1133 [Thread-1] INFO  com.infoniqa.engage.utils.BrowserFactory  - sahi proxy is not yet started
2017-05-23 09:57:47,582 1143 [Thread-1] INFO  com.infoniqa.engage.utils.BrowserFactory  - try waiting for sahi proxy
>>>> Sahi Pro v6.3.2 started. Listening on port: 9999
>>>> Configure your browser to use this server and port as its proxy
>>>> Browse any page and CTRL-ALT-DblClick on the page to bring up the Sahi Controller
Mai 23, 2017 9:57:47 AM net.sf.sahi.util.BrowserTypesLoader loadAvailableBrowserTypes
INFORMATION: 
-----
Reading browser types from: C:\projects\engage.gauge\sahi\userdata\config\browser_types.xml
-----

Mai 23, 2017 9:57:47 AM net.sf.sahi.util.Utils setUrlConnectionFollowRedirectsInternal
INFORMATION: urlConnectionFollowRedirectsInternal = false
Mai 23, 2017 9:57:47 AM in.co.sahi.datastore.SahiDB <clinit>
INFORMATION: Using Database:
driverName=org.h2.Driver
jdbcurl=jdbc:h2:C:/projects/engage.gauge/sahi/userdata/database/db0;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE
userName=sa
Using Connection Pool
Mai 23, 2017 9:57:47 AM in.co.sahi.datastore.SahiDB createTables
INFORMATION: Check tables version
2017-05-23 09:57:48,098 1659 [Thread-1] DEBUG com.infoniqa.engage.utils.BrowserFactory  - finished wait for proxy in 1543 ms
2017-05-23 09:57:48,099 1660 [Thread-1] INFO  com.infoniqa.engage.utils.BrowserFactory  - Launch browser chrome
Mai 23, 2017 9:57:48 AM in.co.sahi.distributed.BrowserType launchInstanceCommon
INFORMATION: Acquired available browser instance after retries:0  threadNo:0
sessionId:sahi_52c37c490fe58042cd09dc90ad60a5b18318
Mai 23, 2017 9:57:48 AM in.co.sahi.datastore.SahiDB createTables
INFORMATION: versionFromDB=2016-10-13 14:21:30
Mai 23, 2017 9:57:48 AM in.co.sahi.datastore.SahiDB createTables
INFORMATION: version=2016-10-13 14:21:30
Mai 23, 2017 9:57:48 AM in.co.sahi.datastore.SahiDB createTables
INFORMATION: At current version. No changes were done.
Mai 23, 2017 9:57:48 AM in.co.sahi.datastore.SahiDB createTables
INFORMATION: {result: [["SAHIKEY","SAHIVALUE"],["dbVersion","83"],["versionNo","2016-10-13 14:21:30"]]}
Mai 23, 2017 9:57:48 AM in.co.sahi.datastore.SahiDB createTables
INFORMATION: Finished preparing report tables: 393ms
Mai 23, 2017 9:57:48 AM net.sf.sahi.test.ProcessHelper execute
INFORMATION: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --user-data-dir=C:/projects/engage.gauge/sahi/userdata\browser\chrome\profiles\sahi0 --proxy-server=localhost:9999 			--disable-popup-blocking --always-authorize-plugins --allow-outdated-plugins --enable-npapi --incognito "http://sahi.example.com/_s_/dyn/Driver_start?sahisid=sahi_52c37c490fe58042cd09dc90ad60a5b18318__SahiAmpersandSahi__startUrl=http%3A%2F%2Fsahi.example.com%2F_s_%2Fdyn%2FDriver_initialized%3FstartUrl%3D"
# 001 Engage installation
  ## 001 Engage installation
Mai 23, 2017 9:57:48 AM net.sf.sahi.test.ProcessHelper$PIDGatherer run
INFORMATION: PIDs: [22312, 20756, 22920, 13316, 21280, 22912]; 864 ms
2017-05-23 09:57:52,358 5919 [Thread-1] INFO  com.infoniqa.common.acceptance.EngageInstallation  - getUpdateLink
2017-05-23 09:57:52,359 5920 [Thread-1] INFO  com.infoniqa.common.acceptance.EngageInstallation  - link: updatePending.goToAdminLink.message
2017-05-23 09:57:52,874 6435 [Thread-1] INFO  com.infoniqa.common.acceptance.EngageInstallation  - link: zur engage Update Administrationsseite.
2017-05-23 09:57:53,490 7051 [Thread-1] INFO  com.infoniqa.common.acceptance.EngageInstallation  - link: the engage Update Administration site.
2017-05-23 09:57:54,107 7668 [Thread-1] INFO  com.infoniqa.common.acceptance.EngageInstallation  - update link exists: false
2017-05-23 09:57:54,725 8286 [Thread-1] INFO  com.infoniqa.common.acceptance.EngageInstallation  - no engage! update necessary
2017-05-23 09:57:54,726 8287 [Thread-1] INFO  com.infoniqa.common.acceptance.EngageInstallation  - wait for installation to be ready
2017-05-23 09:57:54,727 8288 [Thread-1] INFO  com.infoniqa.common.acceptance.EngageInstallation  - installation done!
2017-05-23 09:58:16,226 29787 [Thread-1] INFO  com.infoniqa.engage.login.LoginScreen  - User INFONIQA SUPERADMIN is logged IN.

# 007 Reschedule Jobs
  ## 007 Reschedule Jobs

# 005 Restricted mode
  ## 005 Change System Settings

Mai 23, 2017 9:58:43 AM net.sf.sahi.test.ProcessHelper kill
INFORMATION: Kill: [22312, 20756, 22920, 13316, 21280, 22912]
Successfully generated html-report to => C:\projects\engage.gauge\reports\html-report
Specifications:	3 executed	3 passed	0 failed	0 skipped
Scenarios:	3 executed	3 passed	0 failed	0 skipped

Total time taken: 57.584s

Process finished with exit code 0

As you can see it is again the wrong order:

# 001 Engage installation
# 007 Reschedule Jobs
# 005 Restricted mode

The order seems to be random now.

What should I do to get the execution to alphabetical again? With this actual state of gauge all of our test runs fail - thats very disappointing for us. I am thinking of going back to gauge 0.8.3...

We really need the execution alphabetically to rely on because we are also setting up our test data with the gauge tests and therefore we need a specific order.

Please help.

**Comment by sriv** [comment]
@kupna - the `--sort` implementation had an issue. It prevented gauge from randomizing the order of execution, but did not enforce a sorted list. So there were rare occasions where `--sort` will not sort. Hence this issue.

I suspect it worked most of the case, but once a while it doesn't and that leads to a very tricky situation to debug. 

From your logs, I notice that you are running on windows. if so, may I suggest that you use `powershell`, and the below command to run it in order?

```
gauge --verbose $(gci -r specs | sort-object Name | resolve-path -relative)
```

**Comment by kupna** [comment]
@sriv 
I have tried to start it with powershell, but how exactly do I transform this command 
`C:\dev\Gauge\bin\gauge.exe --simple-console --tags "install|restrictedmode" --sort C:\projects\engage.gauge\specs`

to the powershell command with the alphabetical order?

**Comment by sriv** [comment]
Ideally you should be running `gauge` command with `C:\projects\engage.gauge` as the "Working Directory". In which case your powershell command would look something like this:

```
C:\dev\Gauge\bin\gauge.exe --simple-console --tags "install|restrictedmode" $(gci -r specs | sort-object Name | resolve-path -relative)

```

If you have to run it from location other than project root as working directory, you may try this:

```
 powershell.exe {set-location  C:\projects\engage.gauge\; & 'C:\dev\Gauge\bin\gauge.exe' --simple-console --tags "install|restrictedmode" $(gci -r specs | sort-object Name | resolve-path -relative) }
```

**Comment by kupna** [comment]
@sriv 

I run the gauge tests with GO. I read [here ](https://support.thoughtworks.com/hc/en-us/articles/213253646-Go-s-custom-command) that it is possible to give a powershell argument to the go task. I would like to try that, because I like to define the gauge test execution directly in the task and prefer not not call a batch file instead.

Is it possible, that I use the powershell call as an argument, so that I can make a custum command for gauge and not for powershell

yaml file before:

- setup-acceptance:
          clean_workspace: true
          jobs:
            setup: # name of the job
              tasks: # ordered list of tasks to execute
                - exec:
                    command: gauge
                    working_directory: "engage.gauge"
                    arguments:
                          - "--tags=\"install|restrictedmode\""
                          - "./specs"
                    run_if: passed            



Now it looks like that in my yaml file:

- setup-acceptance:
          clean_workspace: true
          jobs:
            setup: # name of the job
              tasks: # ordered list of tasks to execute
                - exec:
                    command: gauge
                    working_directory: "engage.gauge"
                    arguments:
                          - "--tags=\"install|restrictedmode\""
                          - "powershell $(gci -r specs | sort-object Name | resolve-path -relative)"
                    run_if: passed            

Unfortunately that does not work - how can I give use the powershell call as an argument?

Thanks in advance.

**Comment by kupna** [comment]
Another question for me is why the gauge --sort option is not working and I am forced to sort the specs by myself?

I could not get it working with calling an powershell script either... 

- exec:
                    command: powershell
                    working_directory: "engage.gauge"
                    arguments:
                          - call_gauge.ps1
                          - "--tags=\"install|restrictedmode\""
                    run_if: passed

call_gauge.ps1
`gauge "$args[0]" $(gci -r specs | sort-object Name | resolve-path -relative)`

[go] Task: powershell call_gauge.ps1 "--tags=\"install|restrictedmode\""
call_gauge.ps1 : Die Benennung "call_gauge.ps1" wurde nicht als Name eines 
Cmdlet, einer Funktion, einer Skriptdatei oder eines ausf?hrbaren Programms 
erkannt. �berpr?fen Sie die Schreibweise des Namens, oder ob der Pfad korrekt 
ist (sofern enthalten), und wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ call_gauge.ps1 --tags=install|restrictedmode
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (call_gauge.ps1:String) [], Comm 
   andNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

[go] Task status: failed
[go] Current job status: failed

**Comment by kupna** [comment]
@sriv 
I am really disappointed - that I could not get any of your solutions to work

1. --sort does not work every time it is called 
2. call gauge by go task of powerscript file does not work 
3. call gauge by go task of gauge does not work

now our tests are not running again for another week... before the update they where running every day since the migration of twist.

I would really appreciate a quick solution.

Please help - thanks

**Comment by sriv** [comment]
I understand that this is important. I am investigating further. In the meantime, since you say this was working prior to the upgrade, please see if you can switch to 0.8.3. 

Will update this issue with findings. Thanks.

**Comment by kupna** [comment]
@sriv Thank you very much. 

What Intellij Plugin Version and Java Plugin Version do I need for 0.8.3?

**Comment by sriv** [comment]
Not at my computer at the moment, but off the top of my head I think the the latest gauge-java and intellij should work.

**Comment by sriv** [comment]
@kupna - is it possible for you to share a sample project where the sorting doesn't work with gauge `0.8.4`? I can't seem to replicate this at my end. I am on windows 10.

**Comment by kupna** [comment]
@sriv Did you try it with a project that has specs with this names?

![image](https://cloud.githubusercontent.com/assets/12813719/26538863/89c6c9b0-4449-11e7-89ef-ce01ce989406.png)

I think the problem might be, that I choose the specs to execute by tags:

- "--tags="install|restrictedmode""

The following specs are selected by this tags
![image](https://cloud.githubusercontent.com/assets/12813719/26538884/a6bb9c3a-4449-11e7-8e2b-21b3b1dd1bd5.png)

![image](https://cloud.githubusercontent.com/assets/12813719/26538890/b1e2e5be-4449-11e7-9626-35ea66428b0f.png)

![image](https://cloud.githubusercontent.com/assets/12813719/26538903/c156c074-4449-11e7-81d9-9a0e3d08b7f1.png)

And this specs should be executed in alphabetical order like this as it was before:

001 Engage installation
005 Restricted mode
007 Reschedule Jobs

Can you reproduce it now?

**Comment by kashishm** [comment]
@kupna Thanks for the info. We could replicate this and it is a bug in the `--sort` flag implementation.

**Dev Notes**
In `gauge.go`, while initializing package flags, [line 237](https://github.com/getgauge/gauge/blob/master/gauge.go#L237) overrides the value set by [line 235](https://github.com/getgauge/gauge/blob/master/gauge.go#L235) if `--sort` flag is used.

**Comment by kupna** [comment]
@kashishm 
Great that you found the bug. So should I step back to gauge 0.8.3 or can I have a fix soon?

Thanks.

**Comment by kashishm** [comment]
@kupna I think you could use `0.8.3` for now and the fix will be available in the next release.

**Comment by kupna** [comment]
@kashishm Now that 0.8.5 is released - is this bug fixed?

**Comment by kashishm** [comment]
@kupna Yes, the bug is fixed. You can update Gauge to the latest version and verify.

**Comment by kupna** [comment]
@kashishm I updated to 0.8.5. yesterday and I am facing the problem again :(

Gauge version: 0.8.5

Plugins
-------
html-report (4.0.0)
java (0.6.3)

Command:
gauge "--tags=\"install|restrictedmode\"" ./specs

executes this specs - found by the tags (as in the screenshots above)

# 001 Engage installation
# 005 Restricted mode
# 007 Reschedule Jobs

in the following order
![image](https://user-images.githubusercontent.com/12813719/27624748-563339e8-5be2-11e7-84f3-9fdaeb44fcd3.png)

Which is again not alphabetical... what should I do?

I would really appreciate if I could use any release above 0.8.3. again.

Regards
Natalie

**Comment by kashishm** [comment]
@kupna The command is missing `--sort` flag. Can you try running `gauge "--tags="install|restrictedmode"" --sort ./specs`? The HTML Report doesn't guarantee any order. Please check console for the order of execution.

**Comment by kupna** [comment]
@kashishm  I'll try and write you my results

**Comment by sriv** [comment]
@kupna - any updates on this?

**Comment by kupna** [comment]
I did not have any problems with the order since. Thanks.

**Comment by sriv** [comment]
Thanks for confirming, I'll mark this issue as closed. Feel free to comment if there are further inputs.
