### ISSUE TITLE
Assign a unique identifier when installing or using Gauge

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge#653]
Generate a unique identifier for gauge installation to enable analytics on Gauge.
In the future, if a user **opts-in** to participate, the team can use this for identifying feature usage, support, and adoption. 

Display the identifier when along with the version. 

```
$ gauge -v 
Gauge version: 0.8.4 (xxx-xxxx-xxxxx-xxxx)

Plugins
-------
html-report (4.0.0)
java (0.6.1)
python (0.2.0)
ruby (0.4.0)
spectacle (0.1.2)
```

Where `xxx-xxxx-xxxxx-xxxx` is the identifier

Generate the identifier, if not available, while running Gauge commands.

**Comment by sguptatw** [comment]
- [ ] The ID is generated the first time Gauge is installed/updated
- [ ] Does not change when Gauge is updated later manually
- [ ] Does not change when Gauge is updated later using a package manager
- [ ] Works as expected on all supported OS
