### ISSUE TITLE
Collect statistics for gauge commands

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge#658]
**If a user opts-in to send usage information.**

Collect statistics of gauge commands execution to improve or deprecate command line options.
The statistics will be collected via google analytics using [measurement protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1/reference)

This **must** exclude user identifiable information like ip and user specific parameters like spec folders
```
$ gauge myspecfolder
```
Must not record ``myspecfolder``.

or 

```
gauge --dir="../"
```
Must exclude directory information.

**Comment by sriv** [comment]
The default behaviour shall be "opted in", with options for the users to disable these pings. This is so that unattended execution of gauge is not left out.

**Comment by sriv** [comment]
Information captured:

- IP address is **anonymized**
- No Personally Identifyable Information is collected.

- A Client ID (unique UUID)
- Parameters Tracked:
  - Manifest (Language + Plugins)
  - Execution (tagged, parallel, sort, simple-console, verbose flags). No project specific values are captured.
  - Refactor (Rename) (only usage, no parameters)
  - Refactor (Extract To Concept) (only usage, no parameters)
  - Format (only usage, no parameters)
  - List Templates
  - Plugin Install
  - Plugin Update
  - Plugin Install-All
  - Plugin Update-All
  - Plugin Install from Zip
  - Project Init
  - Daemon execution
  - Docs generation (ex spectacle)

---

The raw requests that is sent can be traced by setting `gauge_analytics_log_enabled=true` in `gauge.properties`.

**Comment by sriv** [comment]
should be available in nightly >= 03-jul-2017

**Comment by sguptatw** [comment]
`gauge install` event on a project is not getting logged.

**Comment by sriv** [comment]
> gauge install event without any parameters on a project is not getting logged.

Happened because of fast events, fixed.
> Capture the language, template being used while init

Fixed.
> gauge uninstall <plugin> is not getting logged.

Happened because of fast events, fixed.
> Should a failed request get logged - example failed refactoring, init, add etc?

Telemetry now captures arguments to `init` and `add` subcommands. What is expected to be captured from failed refactoring? Telemetry does not track refactoring text.
> Events which are fast are not getting logged - example format, docs spectacle with one file.

Fixed
> gauge check-updates is not getting logged.

Incorrect command. Try `gauge updates -c` (or `gauge --check-updates` for legacy syntax).

**Comment by sguptatw** [comment]
Please find the test results inline in my above comment.

**Comment by sriv** [comment]
> The event label of install-all should contain the list of all plugins installed.

Requires track to happen post the event. deferred.
>The event label of update-c should contain the list of all plugins being checked for update.

Requires track to happen post the event. deferred.
>If the event label for an event cannot be logged because we do not capture project specific information the let the event name be the label. This being empty is an issue when custom reports are created.
e.g: gauge daemon
gauge format
gauge refactor
template list
gauge validate

Does not make sense to do this, except when there is a default implicit behaviour. changed for `gauge install` 

>The analytics of gauge refactor is getting logged. However the action is getting hung.

Cannot replicate.

>event category should be based on the new subcommands
e.g: gauge init --templates is getting listed as event category templates event label list. However, this should be listed as event category init and event label templates. Please refer gauge help --legacy and update all such usages.

changed `gauge init --templates` -> event category="init", event action = "templates"

> When gauge run is used the event category is execution. On drilling down one level the label and category is serial. In this case doesn't it make sense to capture it as serial-?

removed logging of "serial" in both action and label. 

> simple console is captured only for a parallel run. This should get captured for a serial run as well

label now captures simple v/s rich console.
