### ISSUE TITLE
Execution Context getCurrentStep giving the wrong value

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#659]
**Expected behavior**
In the BeforeScenario hook, the getCurrentStep().getText() of the execution context should give an empty value.

**Actual behavior**
The first scenario hook works as expected. In the subsequent scenarios, the value getting printed is taking the last step of the previous scenario.

**Steps to replicate**
* run the specs of the project [test1.zip](https://github.com/getgauge/gauge/files/1037352/test1.zip)
* In the result you will see that executionContext.getCurrentStep().getText() + " is the current step is printing `step1` for the second scenario.

**Version**
```
Gauge version: 0.8.4.nightly-2017-05-18

Plugins
-------
html-report (4.0.0.nightly-2017-05-04)
java (0.6.3.nightly-2017-05-26)
ruby (0.4.1.nightly-2017-05-08)
xml-report (0.2.0)
```

**Comment by sriv** [comment]
`BeforeScenario` should not have a `CurrentStep`. Issue here is that ExecutionContext is not getting reset in appropriate intervals, hence `BeforeScenario` of `Scenario2` is getting the `CurrentStep` from the step it executed prior to the hook execution.

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge nightly >= 15/09/17
