### ISSUE TITLE
To agree upon the --sort behavior

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#666]
Here is the notes from an earlier discussion.

Notes: Expected behavior
The specs will be executed in the order provided by the user.

If the user has specified a spec multiple times, the spec will get executed multiple times in the given order.
If sort and user input is given, then sort will take priority.
If the user chooses to use --sort the following behavior will be applied
Specs will be sorted based on depth first.
Specs will be sorted based on the file names(full path) and not the specification name.

What should be the expected behavior when parallel execution is used.

**Comment by RabihHallage** [comment]
Hello @sguptatw,
what do you mean with depth in "Specs will be sorted based on depth first."

**Comment by sguptatw** [comment]
@RabihHallage : Yes, the folder hierarchy.

**Details**:
Considering folders and subfolders is a kind of grouping of specs. We think sort should consider that.
E.g: Consider specs folder having the following structure.
001.spec
C\B\001.spec
C\A\001.spec
B\001.spec
D\001.spec

The order of execution we are considering (depth first) would result in
001.spec
B\001.spec
C\A\001.spec
C\B\001.spec
D\001.spec

Kindly let us know if you have any concerns/suggestions. Thank you.

**Comment by RabihHallage** [comment]
@sguptatw,
Thanks for the information, seems good to me ... !

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
