### ISSUE TITLE
Create a .gitignore file while creating gauge projects from templates.

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#668]
The .gitignore file should be created when `gauge --init` is executed. It should contain relevant folders to be ignored. 
Gauge directories like .gauge, logs and reports should be ignored
For java template, gauge_bin directory should be ignored.
For ruby template, vendor directory should be ignored
For maven projects, target directory should be ignored

**Comment by nehashri** [comment]
Online templates should work.
Offline templates should be available with gauge, gauge-java and gauge-ruby nightly > 12-06-2017.

**Comment by sguptatw** [comment]
* Does not add .gitignore when `gauge --init csharp` is used
* When a project is created from the IDE, .idea, out and the .iml should be added to the gitignore.

**Comment by nehashri** [comment]
@sguptatw We decided not to add any logic in the IDEs, reason being that the IDEs provide their own plugins which can add relevant files to .gitignore.
`gauge --init csharp`  may need fixing though.

**Comment by nehashri** [comment]
@sguptatw The .gitignore file got created for csharp project too, please check your gauge version.

**Comment by sguptatw** [comment]
@nehashri : .gitignore is added even in the project created in the IntelliJ.
However the file content is 
```
.gauge
logs
gauge_bin
reports
```

**Comment by nehashri** [comment]
IDEs will not handle creation of .gitignore files. 
Creating a project via Visual Studio will not have the .gitignore file present. 
Intellij on the other hand, will have the .gitignore file. This is mainly because Intellij internally uses gauge to initialize the project. Therefore the file will contain all gauge directories to be ignored.

**Comment by sguptatw** [comment]
Initializing the project with the command
```
gauge --init java_maven
```
does not have the gitignore file. This is true for the java_maven_selenium also.

**Comment by sguptatw** [comment]
list of project templates
- [ ] java_maven_selenium still does not have .gitignore
- [x] java_maven - works as expected
- [x] java -works as expected
- [x] csharp - works as expected
- [x] ruby - works as expected
- [x] ruby_selenium - works as expected
- [x] python - works as expected
- [x] js - works as expected

**Comment by nehashri** [comment]
should be available with java_maven_selenium now

**Comment by sguptatw** [comment]
working as expected
