### ISSUE TITLE
Autocomplete should show concepts defined in the parent module

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#674]
**Expected behavior**
Autocomplete should show concepts defined in the parent module

**Actual behavior**
Autocomplete is not showing concepts defined in the parent module

**Steps to replicate**
* In the child module of the project `gauge1`. Open a spec and try `Concept Heading`
[artifact.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46e9868e2a8482aa9babf301b44fff9e2c4533317346f67d2581bb79b9477d520c0a1aac455e5f44f8a88a78a3b42e6c981e5ab38532022d8c6853beb2901db90bbb24824881b4bb8344c4ef3426f5c6.zip)

**Comment by sriv** [comment]
Maven projects are not recognized by gauge. so you cannot share concepts/specs as maven modules.
