### ISSUE TITLE
Refactoring a step in the child project is failing

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#675]
**Expected behavior**
Refactor a step in the child project 

**Actual behavior**
Refactoring is a step in the child project is failing

**Steps to replicate**
* In gauge1 module, try refactoring `Vowels in English language are "aeiou"1` to something else in the project.
[artifact.zip](https://github.com/getgauge/gauge/files/1073941/artifact.zip)

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
