### ISSUE TITLE
Refactoring action triggered for a step with alias syntax

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#677]
**Expected behavior**
If there is only one step with alias syntax. It should be treated as a step without alias and refactor. 
Or
If refactoring is not possible then it should not start the process

**Actual behavior**
The refactoring process gets started and I get an error
```
Error: Gauge refactoring failed: Cannot perform refactoring: Refactoring failed: null
```
I can't make any sense of the reason null

**Steps to replicate**
* Create a step with implementation
```
    @Step({"Sign up as <customer> with email <customer@example.com> and <password>."})
    public void registerCustomerWith(String customer, String email, String password) {
    }
```
* Use this in a spec and try refactoring it.

**Version**
```
Gauge version: 0.8.5.nightly-2017-06-13

Plugins
-------
csharp (0.10.1.nightly-2017-05-05)
html-report (4.0.0.nightly-2017-05-04)
java (0.6.3.nightly-2017-06-12)
ruby (0.4.1.nightly-2017-05-08)
xml-report (0.2.0)
```

**Comment by nehashri** [comment]
should be available in gauge-java nightly > 27-06-2017

**Comment by sguptatw** [comment]
It is changing the step in the specification and the code is not changed.

Please let me know What among the 2 suggestions was considered for implementation.

**Comment by nehashri** [comment]
The expected behaviour is that refactoring takes place. It should be treated as a step without alias and refactor.
And please check the version of gauge-java and Intellij Plugin you are using.

**Comment by sguptatw** [comment]
```
Gauge version: 0.9.0.nightly-2017-06-28

Plugins
-------
html-report (4.0.1.nightly-2017-06-27)
java (0.6.5.nightly-2017-06-27)
js (2.0.0)
python (0.2.0)
ruby (0.4.1.nightly-2017-05-08)
xml-report (0.2.0)
```
IntelliJ version - 0.3.5.nightly-2017-06-28

**Comment by sguptatw** [comment]
It works with java (0.6.5.nightly-2017-06-28)
