### ISSUE TITLE
One step calling another

### ISSUE THREAD

**Issue by navaneeth** [getgauge/gauge#68]
There should be a way to call one step from another.  It is sort of like concepts, but much better because you can call it conditionally. 

This could be done something like:

```
step "a step <name>" do |name|
end

step "another step" do
   execute_step 'a step "value"'
end

step "third step" do
   if some_condition
      execute_step 'a step "value"'
   else
      execute_step 'another step"'
   end
end
```

I think this feature is very important for any test suites,

**Comment by prateekbaheti** [comment]
Isn't that equivalent to just calling the right method in code ?
And more importantly should refactoring perform changes in these calls ?

**Comment by navaneeth** [comment]
It is. But usually people are too lazy to extract the step implementations into proper methods so that it can be reused. That's where this makes more sense.

Refactoring should change it if possible or leave a warning about this,

**Comment by teknologika** [comment]
If you think of steps from a business context, you should be able to compose them into larger actions.

I think that the way to think about this feature is "how can I minimise duplication" and this should be at the code, test step and in the markdown as well.

**Comment by haydonduan** [comment]
researched the source code, this way can do this
when you write the step in markdown file like this:
```
  * click the submit button
```
and you must write this step in ruby file, like this:
```
step "click the <button_name> button" do |button_name|
end
```
If you want to execute the step in ruby file, you can:
```
Gauge::Executor.execute_step('click the {} button', ['submit'])
```

**Comment by haydonduan** [comment]
@sriv this feature is implemented?

**Comment by sriv** [comment]
@haydonduan - I won't say we implemented this feature, but clearly you have figured out a way :) 

I think with ruby, you can getaway with this monkey-patched solution, but beware, Gauge::Executor.execute_step is not a public API, and is subject to change without notice. 

However, the issue spans beyond gauge-ruby, and there isn't a way to do this in say, gauge-java and gauge-csharp (at least no API). Hence I wouldn't classify this as an implemented feature yet.
