### ISSUE TITLE
Spec format to add newlines before and after tags

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#684]
Spec format should add newline before and after a tag
Eg :
For the following spec scenario with tags
```
Vowel counts in single word
---------------------------
tags: single word
Some comment
* The word "gauge" has "3" vowels.
```
After formatting, the spec should have
```
Vowel counts in single word
---------------------------

tags: single word

Some comment
* The word "gauge" has "3" vowels.
```

**Comment by Apoorva-GA** [comment]
Available in nightly > 07/07/17

**Comment by sguptatw** [comment]
- [x] should be able to format a spec from the IDE - IntelliJ, VS
- [x] should be able to format from the command line
- [ ] should indicate the error if formatting fails.
Trying to format the following spec, we get Error: Spec Formatting: . However the reason is not specified.
```
Specification Heading
=====================

Vowel counts in single word
---------------------------
Some comment
* The word "gauge" has "3" vowels.
tags: single word
```

**Comment by Apoorva-GA** [comment]
When tags are present at the last line in the spec file : 
Expected : should add new line before tag and should not get the error - `Error: Spec Formatting`.

Fix should be available in nightly > 10/07/17
