### ISSUE TITLE
Statistics inconsistent when specs are repeated

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#685]
_From @sguptatw on June 29, 2017 7:47_

**Expected behavior**
The specifications executed count should be the number of specifications executed. i.e If any specs are repeated, then it should be listed as many times.

**Actual behavior**
The scenario count reflects the repeated execution, the specifications dont.

**Steps to replicate**
* Run specs from the command line 
```
gauge run specs -d="ttt"
# Specification Heading
  ## Vowel counts in single word	 ✔ ✔
  ## Vowel counts in multiple word	 ✔ ✔

Successfully generated html-report to => /Users/sswaroop/work/test/ttt/reports/html-report
Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	2 executed	2 passed	0 failed	0 skipped
```
* Now run the following command
```
gauge run specs/example.spec specs -d="ttt"
# Specification Heading
  ## Vowel counts in single word	 ✔ ✔
  ## Vowel counts in multiple word	 ✔ ✔
  ## Vowel counts in single word	 ✔ ✔
  ## Vowel counts in multiple word	 ✔ ✔

Successfully generated html-report to => /Users/sswaroop/work/test/ttt/reports/html-report
Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	4 executed	4 passed	0 failed	0 skipped
```
The specification count is 1 and the scenario count is 4.

**Version**
```
Gauge version: 0.9.0.nightly-2017-06-28

Plugins
-------
csharp (0.10.1)
html-report (4.0.1)
java (0.6.4)
ruby (0.4.1)
spectacle (0.1.2)
```

_Copied from original issue: getgauge/html-report#151_

**Comment by nehashri** [comment]
The approach to this has changed. If we specify duplicate specifications, the specification will be run only once(only the first specified specification is run). The same applies for scenarios also.

**Comment by Apoorva-GA** [comment]
Available in nightly > 07/07/17
