### ISSUE TITLE
Statistics of scenarios should not consider number of test cases in it

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#686]
**Expected behavior**
The number of scenarios in the statistics should be independent of the number of test cases in the specifications.

**Actual behavior**
The number of scenarios in the statistics is currently the number of test cases in the specifications when the context step has an usage.

**Steps to replicate**
* gauge run specs
[t.zip](https://github.com/getgauge/gauge/files/1111471/t.zip)
The statistics are 
```
Successfully generated html-report to => /Users/sswaroop/work/test/t/reports/html-report
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	4 executed	2 passed	2 failed	0 skipped
```
However there are only 2 scenarios in the spec
**Version**
```
Gauge version: 0.9.0.nightly-2017-06-28

Plugins
-------
csharp (0.10.1)
html-report (4.0.1)
java (0.6.4)
ruby (0.4.1)
spectacle (0.1.2)
```

**Comment by Apoorva-GA** [comment]
Fix should be available in nightly > 7/07/17
