### ISSUE TITLE
gauge update -a should print messages should be reduced

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#696]
**Expected behavior**
gauge update -a should print messages should be reduced

**Actual behavior**
gauge update -a prints a lot of messages even when all the plugins are the latest

**Proposed behavior**
gauge update -a should print messages only when update is available.

**Comment by sriv** [comment]
`gauge update -a` will only print the result. Use `gauge update -a -l debug` to see detailed log

**Comment by sriv** [comment]
Fixed via #724, should be available in nightly >= 18/7/2017
