### ISSUE TITLE
Support for RubyMine

### ISSUE THREAD

**Issue by shane51** [getgauge/gauge#705]
### Expected behavior
User can install gauge plugin for RubyMine, and can run Gauge test through RubyMine

### Actual behavior
I cannot see gauge plugin for RubyMine, and no IDEs support for Ruby

**Comment by sriv** [comment]
There is a Gauge Intellij plugin, which we tried extending to Rubymine a while ago. It didn't go too well, and we figured that the way the Intellij plugin is designed, it can't work with Rubymine without some effort.

We do have some plans to bring Gauge support to text editors, for instance, we are looking at building [language server](http://langserver.org/) support with Gauge, which will open up integration with text editors such as vscode/vim/emacs etc.

Hopefully that should help the gauge ruby users a bit more.

In the meantime, if there is enough interest, please open an issue in [gauge-ruby](https://github.com/getgauge/gauge-ruby/issues/new) and we can discuss what's the best way forward.

**Comment by zabil** [comment]
Closing this as Gauge will not be implementing this feature.
