### ISSUE TITLE
Display the commit hash when showing gauge version

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge#706]
To identify the commit that built the release without having to check ci builds display the commit sha in the gauge version command 

### Expected behavior
```
$ gauge version
~> gauge version
Gauge version: 0.9.0.nightly-2017-07-05 be81241

Plugins
-------
html-report (4.0.1)
java (0.6.4)

```
### Actual behavior
The commit hash is not displayed.

**Comment by sriv** [comment]
related #584, which is waiting for golang 1.9 (see comments).

All the more important when we support #698 

Also, should we include which branch it was built?

**Comment by zabil** [comment]
Oh  didn't see that.
I can close this in favor of  #584 only that we always show a commit from wherever it is built.

Can't the sha be used to identify the branch?
