### ISSUE TITLE
Simplify commands to add and remove plugins.

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge#709]
There are two ways to add a plugin
* Using the `install` command
* Using the `add` command

The `gauge add` command adds the plugin to the project and installs it globally. 
However, some plugins like `spectacle` are global they cannot be added to a project.  

Instead of knowing when to use `add` or when to use the `install` make this one command

### Expected behavior
```
$ gauge install plugin
```
Will download and install the plugin and add it to the manifest json of the project if it is an execution plugin.
If the plugin was already downloaded it will just add an entry in the `manifest.json`.

```
$ gauge install
```
Will install all the plugins in the manifest json.

The 'uninstall' functionality remains the same.

### Actual behavior
```
$ gauge add plugin
```

Installs and adds the plugin to the manifest.

### Gauge version
```
Gauge version: 0.9.0.nightly-2017-07-07

```

**Comment by nehashri** [comment]
should be available in nightly >= 11-07-2017

**Comment by sguptatw** [comment]
`gauge install java` on an existing gauge java project, am getting the following error
```
Failed to add plugin java to project : File /Users/sswaroop/.gauge/plugins/java/0.6.4/plugin.json doesn't exist.
```

**Comment by kashishm** [comment]
should be available in nightly >= 12-07-2017
