### ISSUE TITLE
analytics - track usage statistics

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#71]
would be worth seeing who uses what plugins etc, and help in understanding user needs.

A simple way would be to have a 1px ping url that can be hit by gauge at appropriate contexts, and attach something like piwik/GA to collect this information.

Need to work out a good privacy model, and publish information that is collected.

**Comment by Thunderforge** [comment]
A good start to this would just be to determine how many times each plugin was downloaded. This would not capture installs using the `-f` parameter, and would double-count reinstalls, but it would give a good estimate for usage.

**Comment by sriv** [comment]
After consideration, we feel this will be intrusive, and if we do it effectively, we should ask users to opt in.  Since the metrics would only make sense if Gauge is able to capture per user (i.e. have unique installation ids) and split by platforms (i.e. capture OS info etc), this would lead to Gauge capturing these parameters.

Closing this for now as `wontfix`, can be revisited later.
