### ISSUE TITLE
Deprecate strategy flags and GAUGE_ROOT

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/gauge#716]
Should give a warning message when users are using strategy flags.
Deprecating `GAUGE_ROOT`.

**Comment by Apoorva-GA** [comment]
Available in nightly >= 14/07/17 .

**Comment by sguptatw** [comment]
Unable to access link https://docs.getgauge.io/master/faqs.html#what-is-gauge-home

**Comment by sguptatw** [comment]
When Gauge home is set, there should be different folder for config. Like plugins and logs. Currently the GAUGE_HOME folder structure looks like
```
gauge.properties	logs			plugins
id			notice.md		skel
```
It should be
```
config          logs			plugins
```

**Comment by sguptatw** [comment]
Still Unable to access link https://docs.getgauge.io/master/faqs.html#what-is-gauge-home
