### ISSUE TITLE
Support Code completion via LSP

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#718]
Gauge should support Autocomplete/Code completion via LSP (Refer #717 for more LSP features). 

Gauge should provide a list of completion items to LSP clients. The code completion character which should invoke autocomplete in LSP client is `*`. The list of items should contain a list of concepts and steps. It should also add placeholders for params.

**Comment by nehashri** [comment]
Gauge handles the following behaviour.
- completion shows only if the cursor is in between a step
- completion doesn't show up if cursor is in between parameters
- duplicate steps are filtered
- completion replaces the text (after *) entered by the user.

The changes should be available with gauge nigtly >= 26-07-17

**Comment by sguptatw** [comment]
Test cases VS Code
Autocomplete
- [x] Should list all steps and concepts only once
- [ ] By default, the step text parameter shown should have the step annotation details, not the parameter value.
- [ ] Autocomplete should trigger only when ctrl+space is invoked. This should wait again for the event to occur once the autocomplete task is done/cancelled.
- [ ] Unimplemented steps should also show up in autocomplete.

**Comment by nehashri** [comment]
> Autocomplete should trigger only when ctrl+space is invoked. This should wait again for the event to occur once the autocomplete task is done/cancelled.

Gauge only acts as an LSP server. It can only respond to any request the IDE asks gauge. The auto complete event is invoked differently by different IDEs. Gauge-LSP does not have any control on what/how the IDE behaves. LSP server only has the ability to ask the IDE to invoke autocomplete when '*' is typed, but it has no way to make the IDE behave in a certain way. 

> By default, the step text parameter shown should have the step annotation details, not the parameter value.
Unimplemented steps should also show up in autocomplete.

This involves language runners giving the steps present to gauge. Moving this to https://github.com/getgauge/gauge/issues/753 as this involves language runner changes and need to be present if first cut of this feature.
