### ISSUE TITLE
Ability to write tags in multiple lines

### ISSUE THREAD

**Issue by MaxBt** [getgauge/gauge#720]
as Gauge user I want to be ale to write tags in multiple lines

### Expected behavior
After switching to new line while writing tags, tags are still treat as tags
```
tags:   some_long_tag, another_very_long_tag,
 one_more_very_very_very_long_tag //these tags are treated as tags by gauge
```
### Actual behavior
After switching to new line while writing tags, tags are treated as comments

```
tags:   some_long_tag, another_very_long_tag,
 one_more_very_very_very_long_tag //these tags are not treated as tags by gauge
```

### Steps to reproduce
1. Create sample specification through Intellij plugin
2. write under scenario "tags:" and add some tags
3. press enter (will lead to new line apperared)
4. continue write tags

### Gauge version
```
Gauge version: 0.8.5

Plugins
-------
html-report (4.0.1)
java (0.6.4)
spectacle (0.1.2)
```

### Changes have to be done in
- [ ] gauge core
- [ ] intellij plugin

**Comment by MaxBt** [comment]
Propose this solution:

If line started with "tags" keyword ends by comma then the next line is supposed to contain tags.
Some cases:
```
tags: tag1,
tag2, tag3 //treated as tags
```

```
tags: tag1
tag2, tag3 //**not** treated as tags
```

```
tags: tag1,
tag2, tag3 //**not** treated as tags
```
Also, we don't want want to have two lines limit:

```
tags: tag1,
tag2, tag3, //treated as tags
tag4, tag5  //treated as tags
```

Same logic represented by pseudo code :
if line starts with "tags":
    for each 'word' in ( line split by comma)
        remove spaces at the end and beginning of 'word'
        add 'word' to tags list
    while line ends with ",":
        line = get next line
        for each 'word' in ( line split by comma)
            remove spaces at the end and beginning of 'word'
            add 'word' to tags list

**Comment by ab-yz** [comment]
I would also like to have this feature!

**Comment by Apoorva-GA** [comment]
Gauge now supports tags in multiple lines. 
The changes required from IDE plugins are being tracked separately.
Please fallow issues https://github.com/getgauge/Intellij-Plugin/issues/285 and https://github.com/getgauge/gauge-visualstudio/issues/194 for updates.

Fix available in nightly >= 1/8/17
