### ISSUE TITLE
Opening the spec in the browser is broken

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#721]
**Expected behavior**
When the specification is opened in the browser, table alignment should be retained.

**Actual behavior**
The table alignment is not as expected.

**Steps to replicate**
* Spec
```
Specification Heading
=====================

tags: websearch

|Vowels|d|
|------|-|
|aeiou |a|
|AEIOU |e|

* something else "here"

Vowel counts in single word
---------------------------

tags: single word

* The word "gauge" has "3" vowels.

Vowel counts in multiple word
-----------------------------

This is the second scenario in this specification

Here's a step that takes a table

* Almost all words have vowels 

|Word  |Vowel Count|
|------|-----------|
|Gauge |3          |
|Mingle|2          |
|Snap  |1          |
|GoCD  |1          |
|Rhythm|0          |
```
* format the spec
* Open it in the browser. The alignment is not as expected.

**Version**
```
Gauge version: 0.9.0.nightly-2017-07-14

Plugins
-------
html-report (4.0.1)
java (0.6.5.nightly-2017-07-03)
```

**Comment by Apoorva-GA** [comment]
Should be available in nightly >=24/7/17

**Comment by sguptatw** [comment]
**Expected behavior**
Should be able to view the spec in the browser

**Actual behavior**
Getting `missing plugin spectacle` even after installing it.

* On viewing the spec in the browser, I am getting missing plugin spectacle. 
* It gives me a link to install. On clicking it says successfully installed spectacle.
* However, now opening the spec in browser gives the error `missing plugin spectacle` again

**Comment by BugDiver** [comment]
This issue was moved to getgauge/Intellij-Plugin#283
