### ISSUE TITLE
CI installation should be in the non-interactive mode

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#722]
**Expected behavior**
On CI installation should be non-interactive mode

**Actual behavior**
The installation on CI is interactive. I have to explicitly use the GAUGE_PREFIX and GAUGE_PLUGINS variables to continue.

**Steps to replicate**
* .travis.yml of https://github.com/getgauge-examples/gauge-active-admin-example-ruby

**Comment by BugDiver** [comment]
should be available in nightly >= 17/07/2017
