### ISSUE TITLE
Redundant message should be removed from the installer.

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#726]
**Expected behavior**
Redundant message should be removed from the installer.

**Actual behavior**
Even though the properties are merged, we are getting the following message in the installer
```
If you have Gauge installed already and there are any manual changes in gauge.properties file, a backup of it has been taken at GAUGE_INSTALL_LOCATION\share\gauge\gauge.properties.bak. You can restore these configurations later.
```
**Suggestion**
Remove the message

**Comment by BugDiver** [comment]
Fix should be available in nightly >= 20-7-2017
