### ISSUE TITLE
Proposal: Conditional Steps

### ISSUE THREAD

**Issue by steve-gray** [getgauge/gauge#728]
At present, Gauge cannot be used for tests that require conditonality, unless this conditional behavior is entirely consumed and hidden from the runtime as a single step implementation. This means applications with any degree of dynamism cannot be reliably tested without suddenly shifting the majority of implementation into code, and out of the specs.

This change is two fold:

- Introduce the concept of conditional steps.
- Sub-Lists

Proposed Syntax:
````
Example Test
--------------
* Do a common step
* If the user was allocated to "test group A"
    - Click button
    - Do thing
     - Frobber should frob
* If the user was allocated to "test group B"
````

From a runtime perspective, this then is executed thus:
1. If there is no sub-step, execute the step as normal.
2. If the step implementation is a conditional step, the boolean response of evaluating it is used to determine whether the next-level sub-list is applicable for the test scenario.
3. If the boolean response is false, continue executing at the next step for the current level.
4. If the step is a non-conditional step, but there is a sub-list, execute children sequentially, in depth first order.

In C#/Java this can be presented as a variant of the attribute/annotation that is applied to elements, allowing simple delcarations, such as:

````
[Conditional("If user was allocated to <testGroup>"]
public static bool WasAllocatedTo(string groupId) {
   // Return bool.
}
````

I think from a semantic perspective, this ticks a few boxes:

- Existing tests are unaffected 
- Users can opt in to new behviour progressively but also use the new syntax to group & organised steps, without excessive numbers of concepts being required (Sometimes steps are correlated, but not repeated, and flat list tests of insane length are hard to mentally parse).

Future expansion:

- Is it possible to generalise how the runtime works with these conditions, so that we can do other behaviour besides simple IF(x), but instead do concepts like fan out/in.

**Comment by sriv** [comment]
@steve-gray - thanks for thinking this through. Definitely looks tempting and I am trying to digest your thoughts. 

/cc @zabil @sguptatw

**Comment by zabil** [comment]
@steve-gray this is tempting, but we must to avoid conditionals in a test case.
IOHO, tests must be deterministic. The example you've listed 

```
Example Test
--------------
* Do a common step
* If the user was allocated to "test group A"
    - Click button
    - Do thing
     - Frobber should frob
* If the user was allocated to "test group B"
```

does not guarantee a run of both branches i.e. 

```
* If the user was allocated to "test group A"
```
and 
```
* If the user was allocated to "test group B"
```

Instead, if the data setup is right, this can be split into two tested scenarios with re-used steps.

```
Frob
----
* Create user group 'test group A'
* Click button
* Do thing
* Frobber should frob

Don't Frob
----------
* Create user group 'test group B'
* Click button
* Do another thing
* Frobber should not frob
```

Is there a real life example where you'll find this useful?

**Comment by steve-gray** [comment]
Specific examples include:

- Ability to conditionally perform tasks to stack the deck/perform test setup - i.e. Create test user, allocate to group, if they don't already exist. Without this any steps that might fail like this need to be completely duplicated code-wise, two methods, with two annotations - one version of the method swallows errors, the other raises them as normal, so you can actually check that 'registering a user twice fails', but still use the same steps to conditionally register the test user in the first place.

- MV Testing scenarios, where the user-experience may vary slightly from user to user, and the steps required to reach the target functional area that is the subject of the test might vary.

More generally, pluggable execution semantics would allow for:

- Retry semantics - You may want to have a retry operation over a list of steps up to N times, to account for unreliable systems (this is more an example of, if we're adding pluggable execution control, how we can apply it to benefit).

- Ability for languages to use tables to drive execution (step takes table as input now, but really for this to be useful, you need to be able to pass columns of rows to sub-steps and loop over the steps once per row, etc).

Semantic purism only works if you've got the ability to reach behind the curtain and manipulate the system under test, but if you're trying to write non-flakey tests that treat the system under test as a black box, you end up writing hideous sequences of  Java/C# steps that hide the conditional behavior.

**Comment by zabil** [comment]
> Ability to conditionally perform tasks to stack the deck/perform test setup - i.e. Create test user, allocate to group, if they don't already exist. Without this any steps that might fail like this need to be completely duplicated code-wise, two methods, with two annotations - one version of the method swallows errors, the other raises them as normal, so you can actually check that 'registering a user twice fails', but still use the same steps to conditionally register the test user in the first place.

Gauge will have data set up logic, and it's not easy to cater to all data setup requirements. This can result in a fragmented data setup. It's better to have it centralized using Turing complete language.

This also affects scenario readability where setting up data is not part of the requirements.

> MV Testing scenarios, where the user-experience may vary slightly from user to user, and the steps required to reach the target functional area that is the subject of the test might vary.

Yes, it makes sense here. However this can be done different scenarios.

> Retry semantics - You may want to have a retry operation over a list of steps up to N times, to account for unreliable systems (this is more an example of, if we're adding pluggable execution control, how we can apply it to benefit).

Writing scenarios this way makes flakiness a part of the requirements! We'd want testers to get rid of flakiness. Like they say, there's no such thing as flaky tests.

> Semantic purism only works if you've got the ability to reach behind the curtain and manipulate the system under test, but if you're trying to write non-flakey tests that treat the system under test as a black box, you end up writing hideous sequences of Java/C# steps that hide the conditional behavior.

True, but it will push teams to take a look at the systems being tested a maybe make changes.
Gauge favors testability over test cases. 

That said, we agree semantic purism is harsh and the solution you've provided is neat. 
We'll think over this and see what's best.

**Comment by neo-de** [comment]
Are there any news about this?

**Comment by zabil** [comment]
> That said, we agree semantic purism is harsh and the solution you've provided is neat.
We'll think over this and see what's best.

Gauge won't be implementing this feature.

**Comment by neo-de** [comment]
Very sad!
