### ISSUE TITLE
Allow telemetry to be turned on/off via env var

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#736]
## Actual Behaviour

Telemetry in gauge can be turned on or off using 

`gauge telemetry on` or `gauge telemetry off`

The status of telemetry can be queried via 

    gauge telemetry.

## Expected Behaviour

Introduce an environment variable `GAUGE_TELEMETRY_ENABLED` (true|false) which will get priority over the value of `gauge_telemetry_enabled` property in `gauge.properties`.

When GAUGE_TELEMETRY_ENABLED env var is set:

- `gauge telemetry on` and `gauge telemetry off` will continue to modify the value in `gauge.properties`
it will print a warning stating "Telemetry status is controlled via GAUGE_TELEMETRY_ENABLED environment variable"

- `gauge telemetry` will print the effective value. it will print an info stating "Telemetry status is controlled via GAUGE_TELEMETRY_ENABLED environment variable"
-

**Comment by sguptatw** [comment]
When GAUGE_TELEMETRY_ENABLED is off, the `gauge telemetry on` should indicate that the env value has to be on for telemetry to be on.
