### ISSUE TITLE
Unable to start plugin html-report

### ISSUE THREAD

**Issue by shreyapandey** [getgauge/gauge#738]
Hi,
I am trying to run and debug our java project using gauge 0.9.0 with 
                -html-report[4.0.1],
		-java [0.6.4],
		-xml-report[0.2.0],
eclipse 2017.1.5 ,
java 8_131 .
I am facing a strange issue "Unable to start plugin html-report. Plugin html-report is not installed. To install, run `gauge install html-report`." 
while running the spec files. Also, its skipping the spec file and exiting. I have uninstalled and reinstalled gauge. Its showing all the versions in command prompt successfully but not in intellijIdea. Kindly Help.

**Comment by sguptatw** [comment]
@shreyapandey : What version of Gauge-IntelliJ plugin are you using?

**Comment by shreyapandey** [comment]
I am using gauge 0.9.0 with
-html-report[4.0.1],
-java [0.6.4],
-xml-report[0.2.0], , Operating system is windows 7 64 bit.

**Comment by sguptatw** [comment]
Are you able to execute the tests from the command line?

Gauge-IntelliJ version is available in IntelliJ
<img width="1024" alt="screen shot 2017-07-27 at 12 08 59 pm" src="https://user-images.githubusercontent.com/6310197/28657406-aaf88098-72c4-11e7-9e6d-5ab72e6cc284.png">
Please update the version in the issue

**Comment by shreyapandey** [comment]
Yes I have updated the Gauge from intellij. Could you please tell me how to execute gauge from command line? 
Thanks!

**Comment by shreyapandey** [comment]
Hi,
I ran by command promtpt.Getting this error "Failed to start gauge API: Timed out connecting to [::]:57356"

Please help!

**Comment by sguptatw** [comment]
To help us understand the issue better. Please do the following steps

* Create a new gauge java project
gauge init java
* run the specs
gauge run specs

and share the console logs and the generated logs folder with us.

**Comment by shreyapandey** [comment]
Hi,
Did 1.gauge --init java
2.went to the specs folder
3.gauge specs/

![gauge cmd run result](https://user-images.githubusercontent.com/4942951/28666861-b48c0f04-72e6-11e7-9bf7-d42b5dc82d20.PNG)


I am sorry I can't share log files due to my organisation's policy. Please help us!
Also, we are getting a strange error while debugging since a month.[Error running : Unable to open debugger port (localhost:60556): java.net.ConnectException "Connection refused: connect"] We have tried a 100 ways.Can you shed some light on it as well?

**Comment by shreyapandey** [comment]
Hi,
Latest status is html-report error is gone but now its skipping the .spec files.
here is the message:
Successfully generated html-report to => reports\html-report
Specifications:	0 executed	0 passed	0 failed	1 skipped
Scenarios:	0 executed	0 passed	0 failed	1 skipped

Total time taken: 2.205s

Please help us so that 
1.its able to find the spec files and run them
2."Unable to open debugger port (localhost:60556): java.net.ConnectException "Connection refused: connect"  and on this issue

**Comment by sguptatw** [comment]
`gauge spec/abe.spec` the folder name given is wrong
it should be specs
`gauge specs/abe.spec`

The newly created project is executing successfully on the command-line. Can you please check if you can run this from the IDE.

**Comment by shreyapandey** [comment]
from IDE I am getting this

here is the message:
Successfully generated html-report to => reports\html-report
Specifications:	0 executed	0 passed	0 failed	1 skipped
Scenarios:	0 executed	0 passed	0 failed	1 skipped

**Comment by sguptatw** [comment]
A scenario/specification gets skipped if there are no implementations for any step in the scenario. You can use the `alt-enter` option on a step and create a default empty implementation for a step.

As you are not facing the issue `unable to start html-report`, I will close this issue. If you face any other issues please feel free to raise another issue or reach us at https://gitter.im/getgauge/chat

**Comment by shreyapandey** [comment]
Thanks! Yes I will raise another issue!! 
Thanks for your help :)

**Comment by rav2607** [comment]
Hi @shreyapandey   @sguptatw  i am facing the same error ,is there any solution found for this,i hope i am not alone facing this.
