### ISSUE TITLE
Table is not visible as a table in the generated Gauge docs

### ISSUE THREAD

**Issue by osandadeshan** [getgauge/gauge#739]
### Expected behavior
Table should be visible as a table in the generated Gauge docs

### Actual behavior
Table is not visible as a table in the generated Gauge docs

### Steps to reproduce
1. Create a demo gauge project for Java (Make sure you are having a table in a step of one of your spec file)
2. Shift key + Right click on the root directory of the project
3. Open a command prompt
4. Execute this command
    gauge --docs spectacle specs
5. Go to the docs folder on the project directory
6. Go to the html folder on the project directory
7. Open index.html

### Gauge version
Gauge version: 0.8.4

Plugins
-------
html-report (4.0.0)
java (0.6.3)
spectacle (0.1.2)

![gauge defect](https://user-images.githubusercontent.com/9147189/28655663-0396cca0-72bb-11e7-8321-471c72712bd1.png)

**Comment by kashishm** [comment]
@osandadeshan Can you format the specs first `gauge --format <specs>` and then try running `gauge --docs spectacle <specs>`
