### ISSUE TITLE
No specifications found in spec file

### ISSUE THREAD

**Issue by shreyapandey** [getgauge/gauge#742]
from CMD:
 I tried running the spec file by gauge spec/abe.spec
Its giving message as "No specifications found in specs/ABE.spec."

from IDE I am getting this:-
here is the message:
Successfully generated html-report to => reports\html-report
Specifications:	0 executed	0 passed	0 failed	1 skipped
Scenarios:	0 executed	0 passed	0 failed	1 skipped

I am using gauge 0.9.0 with
-html-report[4.0.1],
-java [0.6.4],
-xml-report[0.2.0], , Operating system is windows 7 64 bit.
PLEASE HELP!

**Comment by sguptatw** [comment]
gauge spec/abe.spec the folder name given is wrong
it should be specs
gauge specs/abe.spec

**Comment by sguptatw** [comment]
A scenario/specification gets skipped if there are no implementations for any step in the scenario. 
In the IDE such steps are marked in red.
You can use the alt-enter option on a step and create a default empty implementation for a step.

**Comment by shreyapandey** [comment]
@sguptatw  thanks!
It was a typo.I am typing gauge specs/ABE.spec and then its not able to locate the file.
Could you please guide me on how to create a default empty implementation for a step in intellij Idea? I am using alt-enter in a spec file but its of no use. :(

**Comment by sguptatw** [comment]
@shreyapandey Please refer https://docs.getgauge.io/using.html#implement-step
