### ISSUE TITLE
Failed row of the table is not colored as red

### ISSUE THREAD

**Issue by osandadeshan** [getgauge/gauge#747]
![attachment2](https://user-images.githubusercontent.com/9147189/28715504-ed3e8924-73b5-11e7-9bdf-68c293620923.PNG)

### Expected behavior
Failed row of the table should be colored as red

### Actual behavior
Failed row of the table is not colored as red

### Steps to reproduce
1. Create a sample project
2. Add a step in the spec file for data driven testing using a table
3. In that table, add a row to fail that step

### Gauge version
Gauge version: 0.8.4

Plugins
-------
html-report (4.0.0)
java (0.6.3)
spectacle (0.1.2)

**Comment by kashishm** [comment]
@osandadeshan Please try this with the latest version i.e 0.9.0

**Comment by osandadeshan** [comment]
I am sorry. Still no difference

**Comment by kashishm** [comment]
@osandadeshan You are using the table as a param in the step. The behavior you have mentioned only works with [`Data Driven Execution`](https://docs.getgauge.io/using.html?highlight=data#data-driven-execution).

**Comment by osandadeshan** [comment]
@kashishm Yes. But It will be much effective for the testers if you can add that as an enhancement. It will increase the readability of the executable html report.

**Comment by MrCoder** [comment]
Is this being considered?

**Comment by zabil** [comment]
Unfortunately this cannot be implemented for table parameters as looping through the rows are handled inside the step implementation. There is no way to send this information while creating html reports.
