### ISSUE TITLE
Tags behavior should be consistent in commandline and IDE

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#750]
**Expected behavior**
Tags behavior should be consistent in command-line and IDE.

**Actual behavior**
On the command line the tag is recognized, however on the IDE it is shown as a parse error.

**Steps to replicate**
* Tag a spec with 
```
tags: tag1,
tags: tag2
```
From the command-line this is a valid syntax. However using the IDE, this is highlighted as an error.

The behavior should be consistent in the IDE and commandline

**Version**
```
Gauge version: 0.9.0.nightly-2017-08-01

Plugins
-------
html-report (4.0.1.nightly-2017-06-27)
java (0.6.5.nightly-2017-07-26)
spectacle (0.1.2)
```

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
