### ISSUE TITLE
Gauge LSP to show unused/unimplemented steps for code completion request

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#753]
Gauge should show unused/unimplemented steps for code completion. 

## Tech notes
Gauge should ask the language runners for this information. The language runners should be able to handle this request. 

## Out of scope
- Unused steps defined in a different library/module

## Acceptance criteria
- The step text parameter shown should have the step annotation details. 
In case of implemented steps, instead of the parameter values used show the parameter name from the annotation details.
- The step code completion should show implemented, unimplemented steps.
- The step code completion should show implemented but unused steps.
- Unimplemented step with parameters is used in multiple places, the first step should be displayed

## Notes
This story is part of [LSP support](https://github.com/getgauge/gauge/issues/717) for gauge.

## Test cases
- [ ] Steps with implementation, but unused, should come in the code completion list
- [x] Used but unimplemented steps should also be available in the list

**Comment by sguptatw** [comment]
Test cases
- [ ] Steps with implementation, but unused, should come in the code completion list
- [ ] Unused Steps defined in a different library/module should be available
- [ ] Steps used in specification but unimplemented should also be available in the list

**Comment by sguptatw** [comment]
## Open question
- If an unimplemented step with parameters is used in multiple places, how should this be handled?
- Should unused steps defined in a different library/module be available?

**Comment by sguptatw** [comment]
**Test Case**
Steps with implementation, but unused, should come in the code completion list

**Question**
How should `gauge_exclude_dirs` work?
`Concepts` in `gauge_exclude_dirs` do not appear in the autocomplete list. Should the steps implemented in `gauge_exclude_dirs` appear in the list. 

Goto definition for concepts defined in `gauge_exclude_dirs` are not recognized, should steps implemented in it be honored?

**Comment by zabil** [comment]
Honor the `gauge_exclude_dirs` and do not list concepts in auto completion.
