### ISSUE TITLE
Cannot print a table as a custom message in the HTML report

### ISSUE THREAD

**Issue by osandadeshan** [getgauge/gauge#755]
### Expected behavior
A table can be able to print as a custom message in the HTML report

### Actual behavior
A table is not printed as a custom message in the HTML report

### Steps to reproduce
1. Use a method to print the table in console
2. Pass that string into Gauge.writeMessage(tableString);
3. View the generated HTML-report after the execution

### Gauge version
Gauge version: 0.9.0

Plugins
-------
html-report (4.0.1)
java (0.6.4)
spectacle (0.1.2)
xml-report (0.2.0)

This is the table I am printing on the console by using System.out.println(tableString);
![console output](https://user-images.githubusercontent.com/9147189/28907309-25133b54-783b-11e7-876b-8a7246be4bfc.PNG)

This is what I got in the HTML report when I use Gauge.writeMessage(tableString);
![html report](https://user-images.githubusercontent.com/9147189/28907310-2517a16c-783b-11e7-8eee-75a0e42bdd1b.PNG)

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
