### ISSUE TITLE
Formatting tags defined in multiple lines.

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/gauge#756]
Tags defined in multiple lines should be formatted.
Given tags : 
```
tags: def, 
abc, asd, 
xyz
```

### Expected behavior
```
tags: def, 
      abc, asd, 
      xyz
```
### Actual behavior
```
tags: def, abc, asd, xyz
```

**Comment by Apoorva-GA** [comment]
Should be available in nightly >= 9/8/17

**Comment by sguptatw** [comment]
The preview in the browser still shows all the tags in a single line.

**Comment by Vishnu1067** [comment]
@Apoorva-GA I tried to use tags in multiple lines and second line considered as description

```Tags: smoke-newdash-sg, smoke-newdash-my, smoke-newdash-id, smoke-newdash-dd, smoke-newdash-dde, smoke-newdash-mobile-sg,
      smoke-newdash-mobile-my, smoke-newdash-mobile-id, smoke-newdash-mobile-dd, smoke-newdash-mobile-dde```

**Comment by sguptatw** [comment]
Gauge does supports tags in multiple lines. Executing gauge run specs --tags="smoke-newdash-mobile-my" from the command line executes the corresponding specs.

However, there are changes required on IDE plugins to highlight the tags in multiple lines. These  are being tracked separately.
Please follow issues getgauge/Intellij-Plugin#285 and getgauge/gauge-visualstudio#194 for updates.
