### ISSUE TITLE
Gauge installation is failing on Ubuntu

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#758]
**Expected behavior**
I should be able to install Gauge on Ubuntu

**Actual behavior**
Gauge installation is failing on Ubuntu gauge_setup: command not found

**Steps to replicate**
* Here is a [Circle CI setup](https://circleci.com/gh/getgauge-examples/ci_setup/13) to replicate the issue.

**Version**
```
gauge amd64 0.9.0 
```

**Comment by BugDiver** [comment]
@sguptatw The `gauge_setup` step has been removed. I have updated the docs.
