### ISSUE TITLE
Goto definition for LSP - Concepts

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#760]
Gauge LSP server should support goto definition for concepts. 
When a LSP client asks gauge for definition of a concept, gauge should give the correct concept filename, and line number of the concept definition.
This story is part of [LSP support](https://github.com/getgauge/gauge/issues/717) for gauge. 

## Acceptance criteria

- [ ] The location of the concept definition should be given
- [ ] The exact location of a concept inside a file with multiple concepts defined should be given
- [ ] provide a peek of the concept of the selected concept.
- [ ] No action for any symbols apart from concept and step.

## Test cases for Goto definition
- [x] Concept file with one concept
- [x] Concept file with multiple concepts
- [x] Concept file with parse error
- [x] Navigate from spec/concepts
- [x] Duplicate concept definitions
- [x] deleted concepts - should say `No definition found`
- [ ] Refactored concept - old names should say `No definition found`

**Comment by sguptatw** [comment]
Test cases
- [ ] The location of the concept definition should be given
- [ ] The exact location of a concept inside a file with multiple concepts defined should be given
- [ ] provide a peek of the concept of the selected concept.
- [ ] No action for any symbols apart from concept and step.

**Comment by nehashri** [comment]
Should be available in gauge nightly >= 06-10-2017

**Comment by sguptatw** [comment]
Issue list
- [ ] textDocument/definition should return a not null value - https://github.com/getgauge/gauge/issues/836

**Comment by nehashri** [comment]
closing this as #838 is closed now.
