### ISSUE TITLE
LSP Code completion - Parameters

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#762]
LSP code completion should work for parameters. If a user invokes autocomplete within the context of a parameter, Gauge should give the LSP client a list of all the parameters used in the file. 
In case of dynamic parameters, the autocomplete should list all dynamic parameters used within the file and spec table headers.
In case of static parameters, the autocomplete should list all static parameters used within the file.
This story is part of [LSP support](https://github.com/getgauge/gauge/issues/717) for gauge.

**Comment by nehashri** [comment]
should be available in nightly >= 30-08-2017

**Comment by sguptatw** [comment]
[Unable to install VSCode](https://github.com/getgauge/gauge-vscode/issues/4)

**Comment by sguptatw** [comment]
Parameters from the csv should also be listed for parameters

**Comment by nehashri** [comment]
@sguptatw Parameters from csv are listed as dynamic parameters.
