### ISSUE TITLE
Latest version of gauge on brew is 0.8.5. Latest version here is 0.9.1

### ISSUE THREAD

**Issue by mglazer** [getgauge/gauge#763]
### Expected behavior

`brew info gauge` reports the latest version as 0.9.1

### Actual behavior

`brew info gauge` reports the latest version as 0.8.5. And that is the version here: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gauge.rb

### Gauge version
```
0.8.5
```

**Comment by sriv** [comment]
The homebrew formula for gauge went through some changes, which did not pass homebrew's review.

Latest PR is here: https://github.com/Homebrew/homebrew-core/pull/16534

Once merged, gauge 0.9.1 should be available on brew. In the meantime, please use the `pkg` installer. Thanks.

**Comment by sriv** [comment]
Homebrew has been [updated](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gauge.rb#L6). Please try installing gauge with brew.

Am closing this issue. Please comment if this requires attention.
