### ISSUE TITLE
Example project executing successfully in IDE fails on command line

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#764]
**Expected behavior**
Specs executing successfully in IDE should execute successfully from command line.

**Actual behavior**
https://github.com/getgauge-examples/gauge-guice is an example project that executes successfully in IntelliJ but fails on command line.

**Steps to replicate**
* clone https://github.com/getgauge-examples/gauge-guice
* execute from IntelliJ - it passes.
* execute from command line - it fails.

**Version**
```
Gauge version: 0.9.1

Plugins
-------
html-report (4.0.2)
java (0.6.4)
```

**Comment by sriv** [comment]
This works:

```
git checkout d9551da2ded7f646b2b7ecfd77ab3975b39686d1
gauge specs
```

So I guess this commit: https://github.com/getgauge-examples/gauge-guice/commit/d9551da2ded7f646b2b7ecfd77ab3975b39686d1 has introduced breaking changes.

FWIW - `HEAD` doesn't work for me in Intellij.

**Comment by BugDiver** [comment]
@sguptatw It works perfectly fine for me from both IDE and console with 

```
Gauge version: 0.9.3
Commit Hash: 2cfd7a8

Gauge-Java version: 0.6.6
Commit Hash: e68bb70

IntelliJ-Plugin version 0.3.7.nightly-2017-09-06
```

can you please verify it and close the issue?
