### ISSUE TITLE
Unable to install gauge using brew after uninstallation

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#765]
**Expected behavior**
I should be able to install gauge after uninstalling it.

**Actual behavior**
I get a message that gauge is already installed.

**Steps to replicate**
* Uninstall gauge - 
```
rm -rf /usr/local/bin/gauge /usr/local/bin/gauge_screenshot ~/.gauge
```
* install gauge using brew
$ brew install gauge
Updating Homebrew...
Warning: gauge 0.9.1 is already installed

* check if gauge is present
$ which gauge
*check for gauge version
$ gauge version
-bash: /usr/local/bin/gauge: No such file or directory

But still I get a warning that gauge is already installed and does not proceed in installation
$ brew install gauge
Warning: gauge 0.9.1 is already installed

**Comment by sguptatw** [comment]
We have to update the documentation to uninstall gauge
```
brew uninstall gauge
```

**Comment by sriv** [comment]
Command for uninstalling gauge via brew:

```
brew uninstall gauge
```

It is a bad idea to manually change files installed via a package manager. If you install it with a package manager, always use the package manager to uninstall/upgrade.

**Comment by BugDiver** [comment]
@sguptatw The docs for gauge uninstallation with package managers are updated and available in [master](https://docs.getgauge.io/master/installing.html#id7).
Could you verify it and close the issue?
