### ISSUE TITLE
Gauge Install ID should not be created for docker instances

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#767]
When gauge is installed in docker instance, the `Gauge Install ID` should not be created. This is to ensure, sharing docker images do not have the same Gauge Install ID. 
The Gauge Install ID will be generated when gauge commands other than `gauge install`, `gauge update`, `gauge man`, `gauge version`, `gauge help` is run for the first time in the instance. These commands should not generate the Gauge Install ID as these commands can be executed while creating the docker images.

**Comment by zabil** [comment]
Gauge does not use install id's anymore.
