### ISSUE TITLE
gauge install --all is not recognized

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#768]
**Expected behavior**
Commands in the `gauge help --legacy` should work.

**Actual behavior**
`gauge install --all` is not recognized.

**Steps to replicate**
* command line
`gauge install --all`

**Version**
```
Gauge version: 0.9.1.nightly-2017-08-09

Plugins
-------
html-report (4.0.2.nightly-2017-08-07)
java (0.6.5.nightly-2017-07-26)
```

**Comment by BugDiver** [comment]
@sguptatw you just need to run `gauge install`. We need to update the legacy message.

**Comment by BugDiver** [comment]
Fix should be available in nightly >= 10-08-2017

**Comment by sguptatw** [comment]
The gauge help --legacy wordings is not clear - It just says `Gauge 0.8.5 and below`. This message has to be more clearer. Something like Use new commands instead of the commands used earlier Gauge 0.8.5 and below.
```
gauge help --legacy
Gauge 0.8.5 and below

Options:
<all options are listed here>
```

**Comment by sriv** [comment]
The invocation here explicitly has `--legacy`. So it implies the user is looking for legacy help. I guess having `Gauge 0.8.5 and below` is enough to indicate the version below which the legacy commands should be used.
