### ISSUE TITLE
Configuration options and scopping test execution in Ruby

### ISSUE THREAD

**Issue by navaneeth** [getgauge/gauge#77]
Today, if I have to use `capybara` or `rspec-matchers` with gauge ruby, I have two options:

* Include it in each of the step implementation files
* Include it in the global space at the suite level hook

Both of these issues are problematic. 

First one makes changing the libraries difficult. If I have to use a different matcher /assertion library, I will have to make the changes in all the step implementation file. 

In the second one, global namespace gets polluted and all the objects lives in the global namespace making garbage collection improper for long running tests suits. 

To solve this, we need to scope the execution of steps into an object. This object will be instantiated and destroyed after executing a scenario or a specification. All the instance level objects which are used inside step implementation will be scopped to this object. A config option will be provided which can be used to scope includes and requires. Something like:

```
Gauge.config do |config|
   config.include [Rspec::Matchers, FactoryGirl::SyntaxHelpers]
end
```

We need to do more research on implementation possibilities of this. Cucumber has a similar one which they call `world`. If you define a world in cucumber, they scope execution to the world instance. 

Without this, I don't think having a big, long running test suite with Gauge is possible today. 

thoughts?

**Comment by sriv** [comment]
How does scoped inclusion of matchers help in this case? I mean, how would it be any different if you include the matchers at suite vs specification level?

PS - I like the DSL approach of inclusion, +1 on having a `config` block.

**Comment by navaneeth** [comment]
I didn't get your point well. But are you saying what difference it makes on whether we include it at each step implementation file separately than doing it at the hooks using the config option provided above?

**Comment by sriv** [comment]
Nope, :-1: for having to include at each step implementation file.

I am trying to understand - what is the benefit of having a scoped include, v/s global include, particularly for matchers. The includes themselves are stateless (I hope), so would it not be enough to include once per run?

In essence, gauge could could include the helpers once before the run. I am trying to understand the need for scoping the include at a granular level.

**Comment by navaneeth** [comment]
Scoping is good to manage names. Since ruby is very loose, multiple libraries using the same name can overwrite code and cause confusion. So it is better to avoid doing anything at global scope. Before test runs, instantiate the object, do all the includes, execute the test, throw the object away.

It is also not safe to assume `include` is stateless. Ruby fires a `included` block for modules which can do any nasty stuffs.

**Comment by sriv** [comment]
I see what you mean, I was drawing parallel to what RSpec [does](https://relishapp.com/rspec/rspec-core/docs/helper-methods/define-helper-methods-in-a-module) in such `config` blocks. Although it supports scoping, it isn't mandatory. I suppose it doesn't harm us to scope includes.

I am guessing there needs to be a way to specify which include is valid for which scope? I.e. name the scopes in some format?

**Comment by navaneeth** [comment]
Not really. You specify all the includes and they all will be included in all the step implementation classes. Filtering includes for each step implementation will be too much, I guess.

**Comment by sriv** [comment]
Partial fix via https://github.com/getgauge/gauge-ruby/commit/1649dbc41bf97c42c106a08eeb566900ecdca674

getgauge/gauge-ruby#7 should address the scoping of includes.

**Comment by navaneeth** [comment]
Nice. How is the API looking like?

**Comment by sriv** [comment]
It looks like this at the moment:

```
Gauge.configure do |c|
    c.include Foo, Bar
end
```

This should include `Foo` and `Bar` modules.

Note to us: We need to improve the docs, possibly use rdoc like something for API docs.
