### ISSUE TITLE
Run `@BeforeSuite` and `@AfterSuite` once for parallel execution

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#770]
`@BeforeSuite` and `@AfterSuite`hooks should be run once per gauge run for parallel execution. As of now it is run once for every parallel stream created for gauge. 
We should also make Datastores part of gauge, so that they are not duplicated during parallel execution.

**Comment by nickmorell** [comment]
I second this, this would be a huge help! Right now I'm trying to send out an email when the entire suite finishes but instead I get one email for every node.

**Comment by gieghia** [comment]
me too. Currently each parallel task execute @BeforeSuite.
need some @BeforeAll annotation.

**Comment by gieghia** [comment]
finally i found work round.
because gauge parallel task run on separate jvm, so every jvm task run @BeforeSuite.

1.we can run multithread task on one jvm with this option.
enable_multithreading = true

2.singleton @BeforeSuite inside task.
for example
@BeforeSuite
fun setup() {
    SingletonTask.initData() //internally execute just once
}

SingletonTask have some state to record ensure initData logic call just once.

**Comment by h2grover** [comment]
`beforeSuite` is running for each spec file in case of parallel execution, is there work around or solution in javascript?

code:
```
beforeSuite(async () => {
  console.log("Before suite -------------------------------");
  // rest of the code
});
```
output:
```
[runner: 3] Before suite -------------------------------
[runner: 1] Before suite -------------------------------
[runner: 2] Before suite -------------------------------
```

**Comment by zabil** [comment]
Related to https://github.com/getgauge/gauge-js/issues/191

**Comment by nehashri** [comment]
getgauge/gauge-js#191 enables parallelization in JS runner. i.e., only one js process will be spawned for execution. 
Please note, that Gauge will still try to run the hooks for every parallel stream. However, you will now be able to control the number of times the beforeSuite and afterSuite hook to be run through your code.
Hope this helps. If you have more queries, please reopen this issue.
