### ISSUE TITLE
Multiple errors with same cause do not have suggestions

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#772]
### Expected behavior
When more than one specs have validation errors, all of them should be listed when running `gauge validate specs` or `gauge run specs`. If suggestions are available, they should be printed for all errors that can have suggestions.

### Actual behavior
If more than one specs have validation errors, all of them are listed when running `gauge validate specs` or `gauge run specs`. However, not all errors contain suggestions.

### Steps to reproduce
1. Download the project [multi_errors_no_suggestion.zip](https://github.com/getgauge/gauge/files/1227283/multi_errors_no_suggestion.zip)

2. Run `gauge run specs`
3. Observe the output:

```
[ValidationError] /tmp/foo/specs/example.spec:18 Step implementation not found => 'The word "gauge" has "3" vowels.'

Quick Fix :
@Step("The word <gauge> has <3> vowels.")
public void implementation(Object arg0, Object arg1){
}

[ValidationError] /tmp/foo/specs/example1.spec:18 Step implementation not found => 'The word "gauge" has "3" vowels.'
[ValidationError] /tmp/foo/specs/example2.spec:18 Step implementation not found => 'The word "gauge" has "3" vowels.'
[ValidationError] /tmp/foo/specs/example3.spec:18 Step implementation not found => 'The word "gauge" has "3" vowels.'
# Specification Heading
  ## Vowel counts in multiple word	 ✔ ✔

# Specification Heading
  ## Vowel counts in multiple word	 ✔ ✔

# Specification Heading
  ## Vowel counts in multiple word	 ✔ ✔

# Specification Heading
  ## Vowel counts in multiple word	 ✔ ✔

Successfully generated html-report to => /tmp/foo/reports/html-report
Specifications:	4 executed	4 passed	0 failed	0 skipped
Scenarios:	4 executed	4 passed	0 failed	4 skipped

Total time taken: 48ms
```

### Gauge version
```
Gauge version: 0.9.2 [built from source]

Plugins
-------
csharp (0.10.1)
html-report (4.0.1)
java (0.6.5)
js (2.0.0)
ruby (0.4.1)
xml-report (0.2.0)
```

**Comment by Apoorva-GA** [comment]
If there is a unimplemented step in multiple files. How should the suggestion be shown? Should it be shown for each unimplemented step or consolidate all validation error for that particular step and show suggestion at the end?

Something like this : 
CASE : 1
```
[ValidationError] /Users/apoorvag/Desktop/foo/specs/example2.spec:18 Step implementation not found => 'The word "gauge" has "3" vowels.'

Suggestion :
@Step("The word <gauge> has <3> vowels.")
public void implementation(Object arg0, Object arg1){
	// your code here...
}

[ValidationError] /Users/apoorvag/Desktop/foo/specs/example3.spec:18 Step implementation not found => 'The word "gauge" has "3" vowels.'

Suggestion :
@Step("The word <gauge> has <3> vowels.")
public void implementation(Object arg0, Object arg1){
	// your code here...
}

[ValidationError] /Users/apoorvag/Desktop/foo/specs/example.spec:18 Step implementation not found => 'The word "gauge" has "3" vowels.'

Suggestion :
@Step("The word <gauge> has <3> vowels.")
public void implementation(Object arg0, Object arg1){
	// your code here...
}

[ValidationError] /Users/apoorvag/Desktop/foo/specs/example1.spec:18 Step implementation not found => 'The word "gauge" has "3" vowels.'

Suggestion :
@Step("The word <gauge> has <3> vowels.")
public void implementation(Object arg0, Object arg1){
	// your code here...
}
```

OR
CASE : 2
```
[ValidationError] /Users/apoorvag/Desktop/foo/specs/example2.spec:18 Step implementation not found => 'The word "gauge" has "3" vowels.'
[ValidationError] /Users/apoorvag/Desktop/foo/specs/example3.spec:18 Step implementation not found => 'The word "gauge" has "3" vowels.'
[ValidationError] /Users/apoorvag/Desktop/foo/specs/example.spec:18 Step implementation not found => 'The word "gauge" has "3" vowels.'
[ValidationError] /Users/apoorvag/Desktop/foo/specs/example1.spec:18 Step implementation not found => 'The word "gauge" has "3" vowels.'

Suggestion :
@Step("The word <gauge> has <3> vowels.")
public void implementation(Object arg0, Object arg1){
	// your code here...
}
```

**Comment by zabil** [comment]
CASE 2 works when all similar validation errors are grouped together.
Is that the case? or it depends on the spec execution order?

If not (grouped) how will this look?

**Comment by sriv** [comment]
How about a modification of `CASE 2`:

```
[ValidationError] /Users/apoorvag/Desktop/foo/specs/example2.spec:18 Step implementation not found => 'The word "gauge" has "3" vowels.'
[ValidationError] /Users/apoorvag/Desktop/foo/specs/example3.spec:18 Step implementation not found => 'The word "gauge" has "3" vowels.'
[ValidationError] /Users/apoorvag/Desktop/foo/specs/example.spec:24 Step implementation not found => 'Say "hello" to "gauge".'
[ValidationError] /Users/apoorvag/Desktop/foo/specs/example1.spec:24 Step implementation not found => 'Say "hello" to "gauge".'

One or more errors were due to : Step implementation not found => 'The word "gauge" has "3" vowels.', Suggestion:

@Step("The word <gauge> has <3> vowels.")
public void implementation(Object arg0, Object arg1){
	// your code here...
}

One or more errors were due to : Step implementation not found => 'Say "hello" to "gauge"., Suggestion:

@Step("The word <gauge> has <3> vowels.")
public void implementation(Object arg0, Object arg1){
	// your code here...
}

```

**Comment by Apoorva-GA** [comment]
@sriv Still it depends on the order of execution of specs right?

**Comment by sriv** [comment]
@Apoorva-GA - Not really. Validation does not depend on the order of execution.

But I guess the answer to @zabil's [question](https://github.com/getgauge/gauge/issues/772#issuecomment-322973097) is that the errors are grouped per spec file, and not by errors.

**Comment by Apoorva-GA** [comment]
So we can't do grouping, which means CASE 2 is not possible. Correct me if I am missing something. 

If grouping is not possible, whats the best way to show the suggestion?

**Comment by sriv** [comment]
My proposal was to decouple the error listing and suggestion listing. For ex. in this case we show the errors against the spec files (since we need to show line nos. etc). 

Then, show a consolidated list of suggestions (against errors).

IMO CASE 1 is a little too verbose, and can clutter the output.

**Comment by zabil** [comment]
That sounds good enough.
To make the copy+paste easier tab the suggestion block as they will be indented by a tab in the class.

```
One or more errors were due to : Step implementation not found => 'The word "gauge" has "3" vowels.', Suggestion:

    @Step("The word <gauge> has <3> vowels.")
    public void implementation(Object arg0, Object arg1){
    	// your code here...
    }

One or more errors were due to : Step implementation not found => 'Say "hello" to "gauge"., Suggestion:

    @Step("The word <gauge> has <3> vowels.")
    public void implementation(Object arg0, Object arg1){
    	// your code here...
    }
```

**Comment by kashishm** [comment]
@zabil Indenting the suggestions by tab will not work for languages having indentation-based blocks like `python`.

**Comment by zabil** [comment]
As the stubs are generated from language runners, is it ok that the formats be specific to the language then?

**Comment by kashishm** [comment]
@zabil @sriv @Apoorva-GA With the format mentioned [above](https://github.com/getgauge/gauge/issues/772#issuecomment-322983596), it's gonna be difficult for a user to copy multiple/all the implementation suggestions to a file because of the text `One or more errors were due to...` present in between the suggestions.

**Comment by zabil** [comment]
@kashishm yes that's right.

Maybe have that text as a comment? So that they can copy it and have context and delete later?

**Comment by kashishm** [comment]
The comment syntax is again language-specific. For Example: `#` in Python and '//' in Java.

**Comment by zabil** [comment]
Right, but can we use the right convention based on language?
If not any other suggestions?

**Comment by Apoorva-GA** [comment]
Currently displaying of msg `One or more errors were due to...`  is being done in gauge. If we want it as comment then language runner should send the entire msg to gauge.

**Comment by kashishm** [comment]
Can we print the message first and then all the suggestions together?
```
Add the following missing implementations to fix above `step implementation not found` errors.

    @Step("The word <gauge> has <3> vowels.")
    public void implementation(Object arg0, Object arg1){
	    // your code here...
    }

    @Step("The word <gauge> has <3> vowels.")
    public void implementation(Object arg0, Object arg1){
	    // your code here...
    }
    
    @Step("The word <gauge> has <3> vowels.")
    public void implementation(Object arg0, Object arg1){
	    // your code here...
    }
```
