### ISSUE TITLE
Duplicate Step Implementation

### ISSUE THREAD

**Issue by chriskellydev** [getgauge/gauge#773]
### Expected behavior
Step implementations with similar syntax but different underlying signatures should call the appropriately matching method signature.

### Actual behavior
Duplicate step implementations are thrown if you have steps with similar text attached to different implementations.

### Steps to reproduce

*GaugeStepImpl.java*
```
import com.thoughtworks.gauge.Step;
import com.thoughtworks.gauge.Table;
import com.thoughtworks.gauge.TableRow;

public class GaugeStepImpl
{
    /**
     * Do Step "String"
     *
     * @param string
     */
    @Step("Do Step <string>")
    public static void doStep(String string)
    {
        System.out.println(string);
    }

    /**
     * Do Step
     * |COL|
     * |---|
     * |A  |
     * |B  |
     *
     * @param table
     */
    @Step("Do Step <table>")
    public static void doStep(Table table)
    {
        for (TableRow tr : table.getTableRows())
        {
            System.out.println(tr.getCellValues().get(0));
        }
    }
}
```

*example.spec*
```
# Example

## Duplicate Step Implementations That Are Not Really Duplicates

* Do Step "A String"

* Do Step
    |TABLE|
    |-----|
    |A    |
    |TABLE|
```
*Console Output*
```
/usr/local/bin/gauge --simple-console /home/me/git/gaugebugs/specs/example.spec:3
[DEPRECATED] This usage will be removed soon. Run `gauge help --legacy` for more info.
[ValidationError] /home/me/git/gaugebugs/specs/example.spec:5 Duplicate step implementation => 'Do Step "A String"'
[ValidationError] /home/me/git/gaugebugs/specs/example.spec:7 Duplicate step implementation => 'Do Step <table>'
Successfully generated html-report to => /home/me/git/gaugebugs/reports/html-report
Specifications:	0 executed	0 passed	0 failed	1 skipped
Scenarios:	0 executed	0 passed	0 failed	1 skipped

Total time taken: 16ms
```

### Gauge version
```
Gauge version: 0.9.0

Plugins
-------
html-report (4.0.1)
java (0.6.4)
spectacle (0.1.2)
```

**Comment by sriv** [comment]
Gauge looks at a templated step text (aka `StepValue`) to compare step texts. In this case both `Do Step <string>` and `Do Step <table>` translate to `Do Step {}`. Hence the collision.

Now, the reason this is done is because Gauge looks at it from the spec point of view, not the implementation. In this case it is evident that the `string` and `table` arguments have different meaning. How would you expect Gauge to behave when the step implementation have same `Step` text, but different primitive parameter types? For ex:

`Do Step <int>` v/s `Do Step <string>`

It gets a little more tricky when you consider the `Object` type in java. If you have two implementations such as:

```
@Step("Do Step <string>")
public void doStep(Object string){
   // some code
}
```

versus 

```
@Step("Do Step <table>")
public void doStep(Table table){
   // some code
}
```

They differ in signature, but `Table` can be assigned to `Object`!

**Comment by chriskellydev** [comment]
Gauge only scanning template text and not even checking/matching for method signature when providing arguments to methods just seems lazy.

Also, your example about the `Object` is hardly an example since if you called your methods in Java, Java would always direct explicit Tables to the one and everything else to the other. Gauge should at least attempt to abide by basic language signature definitions.

This isn't ideal, but since you're so against abiding by the definition of a signature why not allow us to specify the type in the template text thereby giving us different template text. Similar to:

```
@Step("Do Step <table:arg>")
public void doStep(Table arg) {}

@Step("Do Step <string:arg>")
public void doStep(String arg) {}
```

I'm mostly saying that claiming that there is a "duplicate implementation" is hardly true since the implementations are different but use similar template text.

**Comment by sriv** [comment]
@chriskellydev - thanks for the comments.

I like what you proposed, but I am just trying to be sure that it does not go against something already in place. One of the things we try to do is to maintain backward compatibility, so I guess my inertia comes from that. 

I apologize if my comments seem dismissive, definitely not the intention.

Some further thoughts:

- `@Step("Do Step <table:arg>")` does not seem like a good thing, I would like to avoid it as much as I can. 

- `* Do Step <foo>` is a valid step invocation. Here `<foo>` is a dynamic parameter, and is resolved at runtime. This means that Gauge cannot just assume that every step invocation will have the parameter value to determine the type from.

This change will need to be done at the language runner ([gauge-java](https://github.com/getgauge/gauge-java/) in this case). Specifically, there are [parameter converters](https://github.com/getgauge/gauge-java/tree/master/src/main/java/com/thoughtworks/gauge/execution/parameters/parsers/converters) in place, which can be enhanced to determine the best type a string blob matches to.

**Comment by chriskellydev** [comment]
Correct me if I'm wrong, but enhancing the string blob matching is only a portion of the solution. There are multiple items that need addressing:

* Template text shouldn't be the be-all-end-all definition of uniqueness. This is something that is occurring in the pre-run validation of the specification.
* The converters need to be invoked in such a way that they convert the string blobs into whatever the best underlying method is.
    * The only real assumption that could be safely made is that any step with a Table in it will have the Table correctly matched to its appropriate method.

Now for the record, I was not intending `<type:arg>` to be a permanent change but simply an option for those of us who code methods with similar nomenclature but different signatures. It seemed to be the easiest way to solve the points above as the template text would no longer be similar while allowing method-to-template matching at runtime.

**Comment by sriv** [comment]
> enhancing the string blob matching is only a portion of the solution

Correct. However, in this case it is a prelude to validation and execution. So, I guess this (in tandem with a pattern matched lookup of implementation signature) should handle the use case.

> Template text shouldn't be the be-all-end-all definition of uniqueness. This is something that is occurring in the pre-run validation of the specification.

Correct again. My proposal was to enhance the parameter converters so that they assist in matching beyond just text template comparison. The language runners already use reflection to get method signature, parameter types etc, this happens late in the cycle (i.e execution). These could be made part of validation as well, so that steps with same template text, but different method signatures can be allowed.

> The converters need to be invoked in such a way that they convert the string blobs into whatever the best underlying method is.

Correct. (details above).

**Comment by zabil** [comment]
Closing this as Gauge will not be implementing this feature.
