### ISSUE TITLE
HTML report doesn't include the total number of scenarios passed and failed.

### ISSUE THREAD

**Issue by osandadeshan** [getgauge/gauge#777]
### Expected behavior
HTML report should include the total number of scenarios passed and failed. Also when a user clicks on a specification name, it should show the number of  scenarios passed and failed for that specification.

### Actual behavior
HTML report doesn't include the total number of scenarios passed and failed. Also when a user clicks on a specification name, it doesn't show the number of  scenarios passed and failed for that specification.

### Steps to reproduce
1. Create two or more specifications
2. Run all those specifications
3. Open the html-report
4. There will only show the number of failed, pass, skipped in specifications wise

### Gauge version
Gauge version: 0.9.1

Plugins
-------
html-report (4.0.2)
java (0.6.4)
spectacle (0.1.2)
xml-report (0.2.0)

![capture](https://user-images.githubusercontent.com/9147189/29456643-42e945ba-8434-11e7-8edb-fd57f904d29e.PNG)

**Comment by sguptatw** [comment]
This issue was moved to getgauge/html-report#159

**Comment by osandadeshan** [comment]
Hi Soumya,

Is this issue is fixed?




Thanks & Best Regards!




Osanda Deshan  |  Software Automation Engineer

Pearson Lanka (PVT) LTD.
Colombo 09.

Mobile:  +94 71 552 2087
Email  : osanda.deshan@gmail.com
<https://www.facebook.com/profile.php?id=%22osanda.nimalarathna%22>
<https://twitter.com/osandadeshan>
<https://www.linkedin.com/in/osandadeshan>
