### ISSUE TITLE
Gauge-go project running error

### ISSUE THREAD

**Issue by starztp** [getgauge/gauge#778]
### Expected behavior
The gauge specs should run

### Actual behavior
the output message is 
Failed to start gauge API: Timed out connecting to [::]:61472
![image](https://user-images.githubusercontent.com/25835562/29510026-f118e7c6-868c-11e7-8010-001dbddfc1bc.png)

### Steps to reproduce
I tried to run gauge specs in windows ubuntu,but it gave me wong messages:
1.cd /usr/local/goflow/src/EzbuyTest
2.gauge run specs

### Gauge version
```
Run gauge -v on your system and paste the results here.
```
![image](https://user-images.githubusercontent.com/25835562/29510136-4f22d32c-868d-11e7-9833-29d40389295f.png)

**Comment by sriv** [comment]
@starztp - can you please check the below:

- what version of GO do you have installed? `go version` should give you the info.
- Ensure that your `GOPATH` is set to`/usr/local/goflow`
- Are you able to run the same project on other platforms? ex windows /osx or linux natively?

As Linux subsystem for Window is still in beta, we have not tested Gauge (or plugins) in the ecosystem.

**Comment by starztp** [comment]
go version:
![image](https://user-images.githubusercontent.com/25835562/29513178-168f82bc-8697-11e7-83e0-78d2122cca0d.png)

go path:
![image](https://user-images.githubusercontent.com/25835562/29513223-370840b0-8697-11e7-9c1d-71e36258da4e.png)

I haven't run on other platforms before

**Comment by sriv** [comment]
@starztp - Thanks for the info. Is there a project that you can share which has this error? A sample project will help troubleshoot further.

Also, were you able to run this successfully in the past?

**Comment by starztp** [comment]
@sriv 
I haven't ran sucess before,but i want to know in which stuation  gauge will throw this exception?

**Comment by sriv** [comment]
One scenario when Gauge throws the `Failed to start Gauge API` is if it isn't able to run the language runner, or the language runner crashed on start.

Please see under the `logs` directory under the project if there is any additional information logged.

**Comment by starztp** [comment]
okay,i still can not run my project sucessfully and i didn't found the log directory under my project.I suggest  you can provide logs under the project when we run "gauge init go" or init other languages,thanks anyway

**Comment by sriv** [comment]
`logs` folder is created by `gauge` if it does not exist. 

I tried to run `gauge` with `ruby` on ubuntu (linux subsystem on windows) and it works.

I suspect that this could be an issue in `gauge-go`. Can you please raise this [here](https://github.com/getgauge-contrib/gauge-go/issues)

**Comment by sriv** [comment]
I have logged https://github.com/getgauge-contrib/gauge-go/issues/11

**Comment by sguptatw** [comment]
Closing this issue as this is being tracked @  getgauge-contrib/gauge-go#11
