### ISSUE TITLE
Failed to download plugin

### ISSUE THREAD

**Issue by sridhareaswaran** [getgauge/gauge#781]
Plugin download failing both via command prompt and Setup.

![image](https://user-images.githubusercontent.com/9800626/29617267-004212bc-8832-11e7-887b-1a8ea50fe44f.png)

![image](https://user-images.githubusercontent.com/9800626/29617251-ebef1f8a-8831-11e7-8f2a-43372e79e832.png)

**Comment by sriv** [comment]
Gauge Status does not indicate any downtime: https://status.getgauge.io/778781500

Are you behind an internet proxy? Gauge requires internet connection to install plugins.

If you are behind an internet proxy, you can do one of the below:

- set `HTTP_PROXY` via environment variables. See https://docs.getgauge.io/configuration.html#http-proxy

- Download and [install plugin offline](https://docs.getgauge.io/plugins.html#offline-installation).

**Comment by zabil** [comment]
Guess this is working now.
