### ISSUE TITLE
Make gauge download gauge screen-shot tool on first run

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge#782]
To make gauge easier to set up as a single binary. 
Download ```gauge_screenshot``` on first run.

Gauge screenshot binary rarely changes and need not be bundled with every gauge install
Once this is done the zip installer can simplified to curl download for e.g.

```
curl http://getgauge.io/latest -o /usr/local/bin/gauge
``` 
(something similar)

Note that we must have a mechanism to download the ```gauge_screenshot``` tool **if** there are updates.

**Comment by zabil** [comment]
This also makes IDE's downloading and setting up gauge, if not installed, easier.

**Comment by sguptatw** [comment]
gauge_screenshot is used only for the execution cycle of gauge.
Hence check for whether this plugin is installed should be done along with the check for plugins required for the project(manifest.json)

**Comment by kashishm** [comment]
`gauge_screenshot` is installed at first run. So what checks are required?

**Comment by sguptatw** [comment]
@kashishm : updated the previous comment. Kindly let me know if u need more information.

**Comment by kashishm** [comment]
The following command downloads the `gauge` binary to `/usr/local/bin`.
```sh
curl -SsL https://downloads.getgauge.io/stable | sh
```

**Custom Location:**
```sh
curl -SsL https://downloads.getgauge.io/stable | sh -s -- --location=<path>
```

**Comment by kashishm** [comment]
Will be available in Gauge nightly >= 2017-09-21

**Comment by zabil** [comment]
Tested curl command and screenshot tool download as a plugin works fine.

```
$ gauge version
Gauge version: 0.9.3

Plugins
-------
html-report (4.0.2)
java (0.6.5.nightly-2017-09-05)
screenshot (0.0.1)
$ gauge uninstall html-report
Successfully uninstalled plugin html-report 4.0.2.
$ gauge uninstall screenshot
Successfully uninstalled plugin screenshot 0.0.1.
$ gauge version
Gauge version: 0.9.3

Plugins
-------
java (0.6.5.nightly-2017-09-05)
$ gauge validate
No error found.
$ # Does not download plugins
$ gauge telemetry
off
ENV[GAUGE_TELEMETRY_ENABLED]=false. Overrides telemetry configuration.
$ # Does not download plugins
$ gauge run
Installing required plugins.
.......................
........................
# Specification Heading
  ## Vowel counts in single word         ✔ ✔
  ## Vowel counts in multiple word       ✔ ✔

Successfully generated html-report to => /home/zabilcm/Projects/vowels/reports/html-report
Specifications: 1 executed      1 passed        0 failed        0 skipped
Scenarios:      2 executed      2 passed        0 failed        0 skipped

Total time taken: 63ms
$ gauge version
Gauge version: 0.9.3

Plugins
-------
html-report (4.0.2)
java (0.6.5.nightly-2017-09-05)
screenshot (0.0.1)
```

**Comment by haroon-sheikh** [comment]
the curl command is really useful 👍
