### ISSUE TITLE
Gauge init clobbers existing .gitignore

### ISSUE THREAD

**Issue by sghill** [getgauge/gauge#785]
Context: I've been trying out gauge for adding acceptance tests to an existing project.

### Expected behavior
`gauge init` should add to an existing .gitignore if present

### Actual behavior
`gauge init` clobbers existing .gitignore

### Steps to reproduce
1. Create a repository with a .gitignore that has some content and commit
2. Run `gauge init java`
3. See the .gitignore's previous content has been clobbered:
```
--- a/.gitignore
+++ b/.gitignore
@@ -1,2 +1,4 @@
-/build/
-
+.gauge
+logs
+gauge_bin
+reports
```

### Gauge version
```
Gauge version: 0.9.1

Plugins
-------
java (0.6.4)
```

**Comment by sriv** [comment]
Thanks for reporting this. I can replicate this.

But I noticed something:

- If the target directory is not empty, but is a `gauge` project, `gauge` detects that and errors out with the message that `This is already a Gauge Project...`
- However `gauge` does not check if the target directory is actually empty. Whereas `gauge` tempates assume so, since they `write` to files but not append or skip if they exist.

So question is - what should be the behaviour?

/cc @getgauge/core

**Comment by BugDiver** [comment]
Fixed through PR #788. Should be available in nightly >= 30 Aug 2017.

**Comment by nehashri** [comment]
New line should be added after gauge directories in .gitignore, so it is easier to differentiate between user's ignored files and ones added by gauge.
Current file has 
```
# gauge reports generated by reporting plugins
reports
myIgnoredDir
```
Should be 
```
# gauge reports generated by reporting plugins
reports

myIgnoredDir
```

Also, .gauge has more than just failures, can change `# failures metadata dir` to just `# failures metadata dir`

**Comment by BugDiver** [comment]
@nehashri The required changes have been done in language templates.

**Comment by nehashri** [comment]
Comments are not shown for gauge initialization without internet, gauge initialization of csharp template.
initializing maven template is not appending to existing .gitignore, gauge contents are not added.

**Comment by BugDiver** [comment]
Initialization of Maven templates is done by `mvn`, it fetches the project files from archetype an put in the target dir hence it overwrites the existing files.
Required changes for offline installation are done in language runners.

Fix should be available in nightly >= Gauge.05-09-2017, gauge-java.05-09-2017 and gauge-ruby.05-09-2017
