### ISSUE TITLE
Lists specs with no scenarios executed in console

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#787]
**Expected behavior**
If no scenarios of the spec are getting executed, the spec name should not be listed in the console.

**Actual behavior**
The spec name is getting listed

**Steps to replicate**
* This happens when there is a datatable
* run the specs in the project and see `Specification Heading2` getting listed even when no scenarios are executed
[specList.zip](https://github.com/getgauge/gauge/files/1255259/specList.zip)

**Version**
```
Gauge version: 0.9.2.nightly-2017-08-22

Plugins
-------
csharp (0.10.1)
html-report (4.0.2.nightly-2017-08-07)
java (0.6.5.nightly-2017-08-14)
ruby (0.4.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
