### ISSUE TITLE
Undeprecate `-v` and `--version`

### ISSUE THREAD

**Issue by sghill** [getgauge/gauge#790]
Opening as discussed in #786. It's common for tools that feature subcommands to also support flags like `-v` or `--version`. This also means the Github issue templates could continue asking for `gauge -v` without printing deprecation warnings.

### Expected behavior
User is asked to run `gauge -v` to get the version

### Actual behavior
`gauge -v` shows the version beneath a deprecation warning: ```[DEPRECATED] This usage will be removed soon. Run `gauge help --legacy` for more info.```

### Steps to reproduce
1. Install gauge > 0.9.0
2. `gauge -v`

### Gauge version
```
Gauge version: 0.9.1
```

**Comment by kashishm** [comment]
This will be available in nightly >= 2017-09-27
