### ISSUE TITLE
Project logs are getting written to $GAUGE_HOME/logs` dir

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge#791]
### Expected behavior
Logs should be present in `<project_dir>/logs` directory

### Actual behavior
logs are getting written to `$GAUGE_HOME/logs` or `$HOME/.gauge/logs` dir

### Gauge version
```
Gauge version: 0.9.1
```

**Comment by BugDiver** [comment]
It is fixed as part of #782

**Comment by sguptatw** [comment]
Test cases
- [ ] If the user is in a gauge project directory, then the logs are written to the project folder
- [ ] If the user is not in a gauge project directory, then the logs are written to the Gauge HOME\logs folder

> Note: gauge init command in a directory without the gauge project, the logs are written to the Gauge HOME folder.
