### ISSUE TITLE
Failure in tests marked COF is not failing the test case

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#794]
**Expected behavior**
A test should fail, if there is a failure.

**Actual behavior**
If it is marked as COF, throwing an exception in step also does not fail the test case.

**Steps to replicate**
* create a basic project
* Give step implementation of `Vowels in English language are <vowelString>.` as 
```
    @ContinueOnFailure
    @Step("Vowels in English language are <vowelString>.")
    public void setLanguageVowels(String vowelString) throws Exception {
        vowels = new HashSet<>();
        for (char ch : vowelString.toCharArray()) {
            vowels.add(ch);
        }
        new Exception("sfd");
    }
```
* Running the spec is not failing the suite.

**Version**
```
Gauge version: 0.9.2.nightly-2017-08-30
Commit Hash: b0fda9f

Plugins
-------
csharp (0.10.1)
java (0.6.5.nightly-2017-08-14)
ruby (0.4.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

**Comment by sriv** [comment]
Expected behavour with gauge-java. See [here](https://github.com/getgauge/gauge-java/issues/66#issuecomment-246576819)
