### ISSUE TITLE
Merge Common with gauge

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#80]
getgauge/common is a dependency for Gauge, but Gauge is the only project using it. Merge `common` to this repository.

**Comment by prateekbaheti** [comment]
html-report plugin has a [dependency to getgauge/common](https://github.com/getgauge/html-report/blob/master/htmlReportPlugin.go#L8)

**Comment by sriv** [comment]
Ah well, missed that one. Lets leave it as it is.
