### ISSUE TITLE
Vendor gauge dependencies

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#800]
Gauge uses godep to manage dependencies, this locks down a particular version of the dependency needed by gauge. 
This forces `godep restore`  to be executed for gauge to be built.
This command does not work well with if gauge has to be installed with `go get`. 
To remove this dependency on gauge, use go vendor support instead.

**Comment by sriv** [comment]
dependencies are now vendored via 0c5bdec9041ce36cb960410f98cb2c36d2181504
