### ISSUE TITLE
Gauge Visual studio plugin executing scenario in alphabetically instead of scenario sequence.

### ISSUE THREAD

**Issue by itsmemittal** [getgauge/gauge#802]
Gauge VisualStudio Plugin running spec scenario alphabetically.

### Expected behavior
When running specific spec from plugin then it should run spec in scenario order

### Actual behavior
running scenario alphabetically.

### Gauge version
```
Gauve - 0.9.1
Visual Studio Plugin version : 0.3 (Latest)
```

**Comment by sguptatw** [comment]
This issue was moved to getgauge/gauge-visualstudio#202
