### ISSUE TITLE
Error when loading .Spec files (only part of the file markup rules are working)

### ISSUE THREAD

**Issue by tzuravner** [getgauge/gauge#804]
### Expected behavior
when opening an existing gauge c# solution and opening a .spec file the file should open correctly

### Actual behavior
when opening an existing gauge c# solution and opening a .spec file im receiving an error
the spec file open with only part of the highlights and markup features

### Steps to reproduce
1.open an already existing solution
2. open a spec file

### Gauge version
```
0.8.5
```

##VS version
Community 2015

i can also add the spec file

[ActivityLog.TXT](https://github.com/getgauge/gauge/files/1291927/ActivityLog.TXT)

**Comment by sriv** [comment]
This issue was moved to getgauge/gauge-visualstudio#201

**Comment by sriv** [comment]
@tzuravner - thanks for sending across the logs, this seems to be an issue with gauge-visualstudio plugin, hence moved the issue there.
