### ISSUE TITLE
[Enhancement] setup(context) & tear-down steps for the entire spec

### ISSUE THREAD

**Issue by dudicp** [getgauge/gauge#805]
It will be useful to have a Setup steps (context) and TearDown steps which will run before and after spec (instead of before and after each scenario) - similar to suite setup & teardown in Java.

In contrary to @BeforeSpec & @AfterSpec, I want to use the spec files to hold the spec setup & teardown steps instead of having to invoke those steps from the code.

I prefer to use the spec files due to the following reasons: 
(1) the ability to reuse existing steps/concepts
(2) readability of the specs (instead of looking in the code)
(3) have the ability for non-developer to add scenarios.

**Comment by fruityoat** [comment]
It would indeed be very useful. Our tests run on remote machines and connecting and disconnecting every scenario is problematic.

It would also be useful for adding messages to reports, such as the version of the spec file (especially since this can't be done from the execution hooks).

**Comment by fadc80** [comment]
I think steps to be executed before and after the whole spec could be defined using markdown code blocks. For example:

Delete project
===========

```
* Log in as "admin"
* Sign up for user "mike"
* Log off user "admin"
```

* Log in as "mike"

Delete single project
---------------------------------
* Delete the "example" project
* Ensure "example" project has been deleted

Delete multiple projects
--------------------------------------
* Delete all the projects in the list
* Ensure project list is empty
___
* Logout user "mike"

```
* Log in as "admin"
* Delete user "mike"
* Log off user "admin"
```

**Comment by lchrennew** [comment]
it will be useful if there are spec level context steps, for example:
`
# the publicly visible posts must be audited posts

// call serivce APIs to login user1 and user2, get their tokens
* Given there are two users "user1" and "user2"
// call service APIs (publish post A)
* Given "user1" submited a unaudited post "A"
// call service APIs (publish post B)
* And he submited a audited post "B"

## unaudited posts are privately visible
// call services APIs (get post lists, and then asserts)
* "user1" could see post "A"

## unaudited posts are not publicly visible
* "user2" couldn't see post "A"

## audited posts are publicly visible
* "user1" and "user2" could see both "A" and "B"
`
In the present way, it will login users, publish posts for several times, and they are unnecessary except the first time login and publish.

**Comment by jonathangiber** [comment]
This could be definitely useful and save lot of execution time

**Comment by zabil** [comment]
`+` and `-` is valid Markdown syntax for lists. They render as lists on Markdown editors. 

Using them instead of backticks in the example mentioned above, the specification will look as follows.

```
I think steps to be executed before and after the whole spec could be defined using markdown code blocks. For example:

Delete project
===========

+ Log in as "admin"
+ Sign up for user "mike"
+ Log off user "admin"

* Log in as "mike"

Delete single project
---------------------------------
* Delete the "example" project
* Ensure "example" project has been deleted

Delete multiple projects
--------------------------------------
* Delete all the projects in the list
* Ensure project list is empty

___
* Logout user "mike"

- Log in as "admin"
- Delete user "mike"
- Log off user "admin"

```

### Pros
* Easy to parse and distinguish it from steps
* Good readability in the specifications to identify the setup and teardown steps

### Cons
* Note readable in the rendered markdown as they look similar to steps

**Comment by andrumacgiollari** [comment]
I would also find this feature very useful. 
For example, my tests require some considerable setup and configuration of the SUT, copying files, setting parameters etc. 
I only need to do this once per suite of tests.
Of course, the corresponding cleanup to return the SUT to pre-test state is also required.

**Comment by sriv** [comment]
@andrumacgiollari - if I understand you correctly, you might benefit from defining `BeforeSuite` and `AfterSuite` hooks? ref: https://docs.gauge.org/writing-specifications.html?os=linux&language=javascript&ide=vscode#execution-hooks

**Comment by andrumacgiollari** [comment]
@sriv Thanks for the quick answer. 
I have about 20 steps I currently call in the setup. 
If I understand correctly, I should annotate each of these steps with @BeforeSuite to ensure they only run once per specification....
I believe there is no guaranteed order-of-execution issue here?
I also would not be able to re-use these annotated steps in further scenarios?
Is my understanding correct?
Thanks,
Andrú

**Comment by sriv** [comment]
hi @andrumacgiollari, some more comments below:

> If I understand correctly, I should annotate each of these steps with @BeforeSuite to ensure they only run once per specification....

No, `BeforeSuite` runs once per Suite execution. If you want them to run before every spec, you could use `BeforeSpec`.

> I believe there is no guaranteed order-of-execution issue here?

Correct. 

> I also would not be able to re-use these annotated steps in further scenarios?

A method can have multiple annotations, so you can annotate the same method with appropriate attribute and try. Ex: if you had a method with `Step` and `BeforeScenario`  like

```
    @Step("Say Hi")
    @BeforeScenario
    public void sayHi() {
        System.out.println("Hi!!");
    }
```

and a Scenario:

```
## Test

* Say Hi
```

it'll print `Hi!!` two times.

**Comment by andrumacgiollari** [comment]
Hi @sriv 
Thanks again for the quick answers!
One of the use cases in my setup is to login as the default admin, create a user, logout as the default admin and then login as the created user to proceed with the tests.
This created user can then be used for each following step.
I believe that each of these steps are independent and should be re-usable to any scenario...
To use these once and once only in a specification and to ensure the order is preserved (I cant create a user if I'm not logged in as the default admin), I would need to put all these 'actions' into one step and annotate it with @BeforeSuite?
To then re-use these 'actions' in a further scenario, I would need to wrap each 'action' implementation in it's own step, thus duplicating the functionality...
If the above suggestion is implemented, this can be avoided... 
I can write a step for each 'action', not annotate it with anything and re-use it as often as I like...
That's my reasoning...
Thanks,
Andrú

**Comment by sriv** [comment]
hi @andrumacgiollari - thanks for the input. I now have a better idea of your usecase. 

This issue is in the backlog, we definitely feel this would add value. I was trying to explore if there was something else you could do in the interim to get your tests working.

**Comment by andrumacgiollari** [comment]
Hi @sriv 
Thanks for trying!
I can see real value in this feature.
One last question, any rough idea when this might be delivered?
Thanks,
Andrú

**Comment by zabil** [comment]
It's marked to the next major release which is Gauge 2.0. We've just started planning for that and don't have a time frame yet. You can follow this issue or keep track of it on https://github.com/orgs/getgauge/projects/9

**Comment by jonathangiber** [comment]
Hi guys,
Do you have some news or time frame regarding this one?

**Comment by zabil** [comment]
Work on this won't happen anytime soon. 
However, a PR will be accepted if anyone were to implement this change.

**Comment by goblinfactory** [comment]
Does the fact that not having a **before-all** (setup and teardown) is a deal breaker for adoption (i.e. no way to migrate specs where test setup data is included in other popular spec tooling) and 
- given that this is closed
- given that it was promised more than 2 years ago
- not a single announcement on the official blog for gauge since September 2020

**That ... Gauge project is dead?**

... or as close to being dead as a open source project can be, i.e. only only work or code changes appear to be life support patches? 

I'm really hoping my comment hits a nerve and that someone SHOUTS AT ME (please do!) Since I would LOVE Guage to still be alive. 

I'm calling time of Death : September 2020, ...someone please hear this plea and shout at me!

**Comment by goblinfactory** [comment]
Oh, and lastly ...  regarding
```
It's marked to the next major release which is Gauge 2.0. We've just started planning for that and don't have a time frame yet. You can follow this issue or keep track of it on https://github.com/orgs/getgauge/projects/9
```

That link goes to a 404 page! That's kinda the nail in the coffin.

**Comment by goblinfactory** [comment]
@zabil  can you please provide an updated link for Gauge 2.0 planning and status?

**Comment by chadlwilson** [comment]
@goblinfactory you might want to look at https://github.com/getgauge/gauge#important-note

With Gauge's development sponsorship ending, I imagine any earlier planning was invalidated.
