### ISSUE TITLE
Failed to find project directory [Gauge requires .csproj file to compile and execute everytime]

### ISSUE THREAD

**Issue by mura28info** [getgauge/gauge#809]
### Expected behavior
Gauge should not look for .csproj file on every time it gets executed, gauge-bin should have the reference of back end implementation and should be able to package it to execute on Non- installed visual studio machines as well. Expecting typical VS .dll or .exe file.

### Actual behavior
Gauge is getting compiled every time and expects .csproj file for the execution.

### Steps to reproduce
1.Develop a simple gauge application using Visual Studio.
2.Build the project.
3.Copy the gauge-bin/Debug/Release folder and try to execute different machine where Visual Studio is not installed but Gauge, CSharp plugin and .NetFramework 4.5+ is installed.

### Gauge version
Gauge version: 0.9.2
Commit Hash: e2c0d17

Plugins
-------
csharp (0.10.1)
html-report (4.0.2)
ruby (0.4.2)

Run gauge -v on your system and paste the results here.
Gauge version: 0.9.2
Commit Hash: e2c0d17

Plugins
-------
csharp (0.10.1)
html-report (4.0.2)
ruby (0.4.2)

**Comment by sriv** [comment]
You can set `GAUGE_CUSTOM_BUILD_PATH` env variable (or property) to the location where the compiled artifacts are located. Gauge should pick and run specs from there.

**Comment by mura28info** [comment]
@sriv Thanks for the reply, it works fine after setting GAUGE_CUSTOM_BUILD_PATH.

**Comment by apulko** [comment]
If **manifest.json** file is missing, you will get the same error.

_sample Manifest.json_
{
  "Language": "dotnet",
  "Plugins": [
    "html-report",
    "spectacle"
  ]
}
