### ISSUE TITLE
Stopping test execution In between

### ISSUE THREAD

**Issue by SreejithShenoi** [getgauge/gauge#810]
Steps:

1. Setup a guage C# project
2. Add some spec files and add corresponding step implementation code.
3. Now from command line run "gauge run specs"

Is there a way to stop the gauge execution in between? If yes, will it create reports for the specs executed?
I am not sure such a feature exists in gauge and could not find any information from gauge command line documentation as well.

gauge -v results
Gauge version: 0.9.2
Commit Hash: e2c0d17

Plugins
-------
csharp (0.10.1)
html-report (4.0.2)

**Comment by nehashri** [comment]
There is no way to stop gauge execution in between. Can you please give us more information on your specific usecase to stop gauge execution.

**Comment by SreejithShenoi** [comment]
One use case could be
1. Start running spec using "gauge run specs" or by mentioning specs which needs to be executed.
2. Then we detect a problem in the test setup.
3. So the user might want to stop the execution in between to correct the setup. Also it is necessary that it would create the report for all the tests that were run till that point.

**Comment by NicholasEF** [comment]
From Terminal, you should be able to hit Ctrl-C to stop, but #917 seems to indicate a problem with that.
I added a comment over there about how if you're running through VSCode, test runs can be stopped by clicking on 'Running', in the small bottom status bar.
