### ISSUE TITLE
gauge handling predefined global table in a wrong order (compared to alocal spec table)

### ISSUE THREAD

**Issue by tzuravner** [getgauge/gauge#811]
in the spec table:
|word|
|----------|
|a |
|b |
|c |

Test1
-------
* do something with <word>

Test2
-----
* do something without any table

### Expected behavior

The result if running the spec file using the cmd "gauge specfile":
executing of test1
and then execution of test2 

### Actual behavior
the result if running the spec file using the cmd "gauge specfile":
executing of test2
and then execution of test1

###notes:
1. running this with the VS Test explorer result with executing in the expected order
2. running the table in the specefic test also working correctly, for example:

test1
----
do somthing with table
|word|
|----------|
|a |
|b |
|c |

### Gauge version
```
Gauge version: 0.9.2
Commit Hash: e2c0d17

Plugins
-------
csharp (0.10.1)
flash (0.0.1)
html-report (4.0.2)
spectacle (0.1.2)
```

**Comment by nehashri** [comment]
Visual Studio registers the scenarios present in the file and sends them to gauge to be executed explicitly. 
Whereas from command line, gauge takes the spec file parses the spec file and sends them for execution. In this case, all non table driven scenarios are executed first. Gauge does not guarantee any specific order execution of scenarios, as interdependent test cases are not advised.
If you want them to be executed in a specific order, you will have to specify this explicitly in command line. You can specify [scenarios for execution in command line](https://docs.getgauge.io/using.html#executing-tests).

**Comment by tzuravner** [comment]
This might be a real hard limitation to the product to my opinion as the order of the test scenario might be a very important (business and functional wise.)
the cmd is not really  usable for a large amount of scenarios

**Comment by zabil** [comment]
@tzuravner 
To run tests in parallel scenarios must not be dependent on a order or hold state.
This guides users to properly design their tests.

Closing this issue as we will not support ordering of scenarions and they have to be authored in a way where they are not dependent on each other.

**Comment by tzuravner** [comment]
understood, make sense.
thanks
