### ISSUE TITLE
Formatting for LSP : Specification

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge#813]
Gauge LSP server should support formatting specs.
When an LSP client asks gauge to format a spec file, gauge should format the spec.
This story is part of [LSP support](https://github.com/getgauge/gauge/issues/717) for gauge.

## Assumptions
-  Gauge format feature is working as expected

## Test cases
- [x] Should invoke gauge format if there are no parse errors

**If formatting fails, the reason must be indicated**
- [x]  Table doesn’t belong to any step
- [x] Table location not specified
- [x] Scenario should be defined after the spec heading - This should consider 3 `-` and more as a step. This parse error appears even if there is 1 hyphen
- [x] Could not resolve table from file - give a wrong path in the table parameter <table:something> or <table:>
- [x] Update the vs-code readme with every new feature

**Comment by sguptatw** [comment]
Assumptions
-  Gauge format feature is working as expected

Test cases
- [x] Should invoke gauge format if there are no parse errors
- [x] If formatting fails, the reason must be indicated

> Update the vs-code readme with every new feature
