### ISSUE TITLE
[LSP code completion]Tag list should be displayed when autocomplete is invoked

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#824]
**Proposed behavior**
LSP code completion should work for tags. 

**Steps**
* User invokes autocomplete within the context of a tag 

This story is part of LSP support for gauge.

## Acceptance Criteria
- [ ] Gauge should give the LSP client a list of all the tags used in the project.

## Test cases
- [x] Unique list of all tags should be displayed.
- [ ] Should display only tags and not other content.
- [ ] Tags with white space should be considered as one tag
- [x] Tags defined in new line should also be considered

**Comment by sguptatw** [comment]
Test cases
- [ ] Gauge should give the LSP client a list of all the tags used in the project.

**Comment by Apoorva-GA** [comment]
Should be available in gauge nightly >= 25/10/17

**Comment by sguptatw** [comment]
**Expected behavior**
Only tags should get listed in tags autocomplete

**Actual behavior**
Content other than tags are getting listed in tags autocomplete

**Steps to replicate**
* In a gauge project, at a scenario or specification level use tag autocomplete
<img width="386" alt="otherinfo" src="https://user-images.githubusercontent.com/6310197/32533352-3c2e9798-c476-11e7-89b3-8b535265c481.png">

**Version**
```
Gauge version: 0.9.4

Plugins
-------
csharp (0.10.2.nightly-2017-10-26)
html-report (4.0.2)
java (0.6.6.nightly-2017-09-14)
js (2.0.3.nightly-2017-11-07)
```

**Comment by sguptatw** [comment]
**Expected behavior**
One tag with white space should get listed as one tag

**Actual behavior**
Tag with white space is getting listed as different tags

**Steps to replicate**
* add a tag 
```
tags: one, two with space, three
```
* autocomplete tags lists `two` `with` and `space` are getting listed as different tags.

**Version**
```
Gauge version: 0.9.4

Plugins
-------
csharp (0.10.2.nightly-2017-10-26)
html-report (4.0.2)
java (0.6.6.nightly-2017-09-14)
js (2.0.3.nightly-2017-11-07)
ruby (0.4.3.nightly-2017-10-17)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge nightly >= 9/11/17
