### ISSUE TITLE
Gauge LSP: Highlight the dynamic parameter usages

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#825]
**Proposed behavior**
Highlight the dynamic parameter usages

**Steps**
* User clicks on a dynamic parameter
Gauge should give the LSP client a list of all the Symbol Information used in the current file.
This story is part of LSP support for gauge.

## Test Cases
- [ ] Inline/external Table parameter usages should get highlighted in a spec
- [ ] Concept dynamic parameters should get hightlighted

**Comment by sguptatw** [comment]
Test Cases
- [ ] Inline/external Table parameter usages should get highlighted in a spec
- [ ] Concept dynamic parameters should get hightlighted

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
