### ISSUE TITLE
Random issues with Visual Studio 2015 Plugin

### ISSUE THREAD

**Issue by itsmemittal** [getgauge/gauge#829]
Hi, 
I am facing random issues with visual studio plugin these following are coming randomly.

1. While Building project Test adapter saying "Object Reference Exception"
2. When Building project test adapter saying "The given key is not present in dictionary"
3. When i am changing anything in step implementation i am not able to debug i have to uninstall and re install plugin again.
4. Gauge Demon error.

Please guide me.

Thanks

**Comment by sriv** [comment]
This issue was moved to getgauge/gauge-visualstudio#204

**Comment by sriv** [comment]
@itsmemittal - thanks for reporting this. Please can you provide the gauge relevant section from `activitylog.xml` in the form of a code-block? screenshot isn't very readable. thanks.
