### ISSUE TITLE
Gauge LSP: Execute a specification

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#830]
**Proposed behavior**
Execute all the scenarios in the specification

**Out of scope**
- Debugging
- Parallel

**Steps**
* Provide a Code lens link to execute all scenarios in the specification. 

## Acceptance criteria
- [x] Execute all the scenarios in the specification, show the results in the output window.

## Test cases
- [x] Should be able to execute all scenarios in the specification
- [x] Should be able to execute all the test cases in a specification

**Comment by BugDiver** [comment]
Should be available in gauge nightly >= 05-10-2017 and gauge-vscode nightly >= 6-10-2017
