### ISSUE TITLE
Gauge LSP: Execute a scenario

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#831]
**Proposed behavior**
Execute a scenario in the specification

**Out of scope**
- Debugging
- Parallel

**Steps**
* Provide a Code lens link to a specific scenario in the specification. 

## Acceptance criteria
- [ ] Execute the selected scenario in the specification, show the results in the output window.

## Test cases
- [x] Code lens link to execute should appear only in .spec and .md files
- [x] Link to execute should not appear in .cpt files
- [x] Should be able to execute a scenario
- [x] When there are parse errors in the file, the links are not shown.

**Comment by BugDiver** [comment]
Should be available in gauge nightly >= 05-10-2017 and gauge-vscode nightly >= 6-10-2017
