### ISSUE TITLE
textDocument/definition should return a non null value if definition is present

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#836]
**Expected behavior**
The call should return all the values required to navigate to the code.

**Actual behavior**
Getting response as null

**Steps to replicate**
* In the project https://github.com/getgauge/lsp-tests.git
* Create a concept abc.cpt in specs\concepts
```
# One
* start gauge daemon for project "testdata\\parse-errors"
```
* goto definition on the step. This gives the result
```
--> request #2: textDocument/definition: {"textDocument":{"uri":"file:///c%3A/work/getgauge/lsp-tests/specs/concepts/abc.cpt"},"position":{"line":1,"character":16}}
<-- result #2: textDocument/definition: null
```
**Version**
```
Gauge version: 0.9.4.nightly-2017-10-09
Commit Hash: 8ef345c

Plugins
-------
csharp (0.10.1)
html-report (4.0.2)
java (0.6.6.nightly-2017-09-14)
js (2.0.1)
ruby (0.4.2)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```
VS code plugin - gauge-0.0.1.nightly-2017-10-06

**Comment by nehashri** [comment]
@sguptatw It looks like you are trying to goto definition of a Step implementation. As per #760, Goto definition will work only for steps in concept or spec files whose implementation is a concept.

**Comment by sguptatw** [comment]
@nehashri Thanks for the clarification.
