### ISSUE TITLE
No commit sha when go get gauge is used to install gauge

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#837]
**Expected behavior**
Commit sha message should be displayed irrespective of how gauge was installed.

**Actual behavior**
The message does not appear if go get is used

**Steps to replicate**
* Uninstall gauge
* go get gitHub.com\getgauge\gauge
* gauge version
> This does not display the commit sha

**Version**
```
Gauge version: 0.9.4

Plugins
-------
csharp (0.10.1)
html-report (4.0.2)
java (0.6.6.nightly-2017-09-14)
js (2.0.1)
ruby (0.4.2)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

**Comment by sriv** [comment]
commit hash is available only when building via `go run build/make.go`. `go get` builds will not get commit hash.
