### ISSUE TITLE
gauge_exclude_dirs configuration not considered

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#840]
**Expected behavior**
Any concept defined inside the directories listed in gauge_exclude_dirs should not be considered by gauge.

**Actual behavior**
The concepts are still getting considered

**Steps to replicate**
* In the `default.properties` add gauge_exclude_dirs="<folder_path>"
* Define concept inside the path
* Use this concept in a step.
* Execute the scenario. Concept definition is still considered.

**Version**
```
Gauge version: 0.9.4

Plugins
-------
csharp (0.10.2.nightly-2017-10-09)
html-report (4.0.2)
java (0.6.6.nightly-2017-09-14)
```

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge nightly >= 16/10/17

**Comment by Apoorva-GA** [comment]
The list of folder paths to be excluded, should be given without quotes and separated by comma(if more than one) in `default.properties` file.
eg : ` gauge_exclude_dirs=<folder_path1>,<folder_path2>`
