### ISSUE TITLE
Cannot find gauge.properties on a fresh install (Linux)

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge#842]
### Expected behavior
Install should be succesful with no errors/warnings.

### Actual behavior
Step 10/18 : RUN gauge telemetry off && gauge install java

```bash
2017/10/16 16:30:18 Failed to get configuration from Gauge properties file. Error: open /root/.gauge/config/gauge.properties
```
### Steps to reproduce
1. apt-get install -y gauge
2. gauge telemetry off && gauge install java
3.

### Gauge version
```
0.9.3
```

**Comment by sriv** [comment]
fix should be in nightly >= 04/12/2017
