### ISSUE TITLE
Allow tables to be specified as columns rather than rows

### ISSUE THREAD

**Issue by ssg47** [getgauge/gauge#845]
Often, I use the table format even when I'm only testing a single set of values because it's more readable than long sentences with lots of quoted parameter values.

For some scenarios I have lots of input parameters to supply and output values to check.  It would be more readable if the table could be specified with the parameters names in the first column and the values in the second column (and third, fourth, etc. when there's more than one set of parameters).

In the documentation, you have:

    * Step that takes a table
       | id  | name    |
       |-----|---------|
       | 123 | John    |
       | 456 | Mcclain |

In column-format, it would become:

    * Step that takes a column-format table
       | id   | 123     | 456     |
       | name | John    | Mcclain |

This makes more sense where there are lots of parameters:

    * GetUser returns valid values
       | Title       | Mr     |
       | FirstName   | Bob    |
       | Initials    | A      |
       | LastName    | Smith  |
       | EmployeeId  | 123456 |
       | DisplayName | Bob A Smith (123456) |
       | Department  | A1     |
       | Division    | Manuf  |
       | Location    | MA     |
       | Floor       | 1      |
       | Role        | Mgr    |
       | Group       | 42     |
       | CanDelegate | Y      |

It would be good if this format was reflected in the output - currently, wide tables result in wide report and screenshots are right-aligned rendering them invisible without a lot of scrolling back and forth.

**Comment by zabil** [comment]
@ssg47  This breaks markdown's table syntax :-( 
We don't want that. Gauge specs must be editable with standard markdown tools (for parsing etc) or any editor with markdown support.

Closing this issue, but feel free to open it if you have suggestions on to do this without deviating from markdown.
