### ISSUE TITLE
`Installing required plugins.` before each run on Linux?

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge#852]
### Gauge version
```
Run gauge -v on your system and paste the results here.
0.9.4
```

**Comment by zabil** [comment]
This doesn't happen on Ubuntu 16.04

Can you please give us more info?

**Comment by haroon-sheikh** [comment]
@zabil I've been looking at my logs and I see the following:

```bash
Step 10/18 : RUN gauge telemetry off &&   gauge install java &&   gauge install html-report &&   gauge install xml-report &&   gauge update -c &&   gauge update -a
 ---> Running in 16ab1d38623f
2017/11/08 22:46:12 Failed to get configuration from Gauge properties file. Error: open /root/.gauge/config/gauge.properties: no such file or directory
2017/11/08 22:46:12 Incorrect value for gauge_telemetry_enabled in property file. Cannot convert  to boolean.
2017/11/08 22:46:12 Failed to get configuration from Gauge properties file. Error: open /root/.gauge/config/gauge.properties: no such file or directory
2017/11/08 22:46:12 Incorrect value for gauge_telemetry_log_enabled in property file. Cannot convert  to boolean.
2017/11/08 22:46:12 Unable to read /root/.gauge/config/id
```

Could that be the reason, its not finding the plugins?

**Comment by zabil** [comment]
Probably not.

Does your build run with a fresh installation gauge every time? or on an image/container that has it already installed with all the plugins?

**Comment by haroon-sheikh** [comment]
It's an image container that has it installed. This started to happen with the latest version 0.9.4 but was fine with 0.9.3

**Comment by haroon-sheikh** [comment]
Here's my docker file:

```bash
FROM maven:3-jdk-8
MAINTAINER Haroon Sheikh <haroon.sheikh@sky.uk>

# install the required dependencies

RUN apt-get update && \
  apt-get install -y build-essential g++ flex bison gperf ruby perl \
  libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev \
  libpng-dev libjpeg-dev python libx11-dev libxext-dev

# install gauge
RUN apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B
RUN echo deb http://dl.bintray.com/gauge/gauge-deb stable main | tee -a /etc/apt/sources.list
RUN apt-get update && \
  apt-get install -y gauge

# install gauge plugins
RUN gauge telemetry off && \
  gauge install java && \
  gauge install html-report && \
  gauge install xml-report && \
  gauge update -c && \
  gauge update -a

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ONBUILD ADD . /usr/src/app

ENTRYPOINT ["/usr/local/bin/mvn-entrypoint.sh"]
CMD ["bash"]
```

**Comment by zabil** [comment]
Can you try adding

```
# install gauge plugins
RUN gauge telemetry off && \
  gauge install java && \
  gauge install html-report && \
-> gauge install screenshot && \
  gauge install xml-report && \
  gauge update -c && \
  gauge update -a
```

**Comment by haroon-sheikh** [comment]
Yes adding the screenshot plugin removes the message.

Is screenshot a required plugin now, if yes, should it not install when installing gauge?

**Comment by zabil** [comment]
Yes,  gauge screenshot is a plugin now.

> should it not install when installing gauge?

No, more details here https://github.com/getgauge/gauge/issues/782

**Comment by haroon-sheikh** [comment]
Can we get this documented somewhere please? Also how are these changes communicated out to users?

**Comment by haroon-sheikh** [comment]
And changes like these should really be treated as a minor update to version not just a patch.
I'm guessing we're following http://semver.org/

**Comment by haroon-sheikh** [comment]
We should treat patch versions for bug fixes only.

**Comment by zabil** [comment]
> Can we get this documented somewhere please?

Yes, I guess it can be done here https://docs.getgauge.io/howto/docker.html and it'd be great if you can make modifications (like the many you've contributed already!) since you are using Docker and know what works and what does not.

Here's a discussion why don't use semantic versioning.
https://github.com/gocd/gocd/issues/2509

**Comment by haroon-sheikh** [comment]
https://github.com/getgauge/docs.getgauge.io/pull/48 😉
