### ISSUE TITLE
Error - An existing connection was forcibly closed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#856]
**Expected behavior**
Goto definition should continue to work when the project is open

**Actual behavior**
Goto definition commands do not work after getting the error - An existing connection was forcibly closed by the remote host.

**Steps to replicate** 
* Open the [lsp-tests](https://github.com/getgauge/gauge-lsp-tests) project in vs-code
* type a new step sdfsdf - let it remain unimplemented
* try to goto the step definition of this unimplemented step
* In the IDE, the user does not see any error. However goto the logs of Gauge to see the error
--> request #71: textDocument/definition: {"textDocument":{"uri":"file:///c%3A/work/getgauge/lsp-tests/specs/autocomplete.spec"},"position":{"line":3,"character":4}}
<-- error #71: textDocument/definition: {"code":0,"message":"write tcp 127.0.0.1:49769-\u003e127.0.0.1:49774: wsasend: An existing connection was forcibly closed by the remote host.","data":null}
[Error - 10:38:23 AM] Request textDocument/definition failed.
  Message: write tcp 127.0.0.1:49769->127.0.0.1:49774: wsasend: An existing connection was forcibly closed by the remote host.
  Code: 0 
--> request #72: textDocument/definition: {"textDocument":{"uri":"file:///c%3A/work/getgauge/lsp-tests/specs/autocomplete.spec"},"position":{"line":2,"character":13}}
<-- error #72: textDocument/definition: {"code":0,"message":"write tcp 127.0.0.1:49769-\u003e127.0.0.1:49774: wsasend: An existing connection was forcibly closed by the remote host.","data":null}
[Error - 10:39:31 AM] Request textDocument/definition failed.
  Message: write tcp 127.0.0.1:49769->127.0.0.1:49774: wsasend: An existing connection was forcibly closed by the remote host.
  Code: 0 

**Version**
```
Gauge version: 0.9.5.nightly-2017-11-07
Commit Hash: 7ea750c

Plugins
-------
js (2.0.3.nightly-2017-11-10)
```
IDE - gauge-0.0.3.nightly-2017-11-13

**Comment by sguptatw** [comment]
Getting this on document closed also
```
--> notif: textDocument/didClose: {"textDocument":{"uri":"file:///c%3A/work/getgauge/lsp-tests/tests/autocomplete.js"}}
2017/11/14 12:28:07 jsonrpc2 handler: notification "textDocument/didClose" handling error: write tcp 127.0.0.1:51308->127.0.0.1:51310: wsasend: An existing connection was forcibly closed by the remote host.
--> notif: textDocument/didClose: {"textDocument":{"uri":"file:///c%3A/work/getgauge/lsp-tests/tests/gauge_daemon.js"}}
2017/11/14 12:28:07 jsonrpc2 handler: notification "textDocument/didClose" handling error: write tcp 127.0.0.1:51308->127.0.0.1:51310: wsasend: An existing connection was forcibly closed by the remote host.

```

**Comment by nehashri** [comment]
fix should be available with gauge-js nightly >= 15-11-2017

**Comment by sguptatw** [comment]
This is still replicable in nightly 15-11-2017

**Steps to replicate**
* Goto definition for a step.
* Close the js file
* Open the spec file
