### ISSUE TITLE
Scenario in Execution context should contain all steps info from scenario

### ISSUE THREAD

**Issue by olejkavn** [getgauge/gauge#857]
Scenario in ExecutionContext should contain array of StepDetails instead of "currentScenario", also StepsDetails should contain field isExecuted

Issue opened according to discussion:
https://gitter.im/getgauge/chat?at=5a09cfa8f257ad91098ce6b5

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
