### ISSUE TITLE
Exclude Directories from Gauge's working

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#869]
**Expected behavior**
Gauge should exclude the directories mentioned in the list from its working

**Acceptance criteria**
- [ ] Concepts in these folders should not be considered for validation, execution, autocomplete.
- [ ] Specifications in these folders should not be considered (.md is a common extension for non-Gauge files as well)
- [ ] Files and folders in the list should not have Gauge features working ex:- syntax highlight...
Currently the Readme file also shows Gauge syntax highlights.

**Comment by sguptatw** [comment]
Getting a duplicate concept defined even if one of the folders is configured in gauge_exclude_dirs.

**Comment by sguptatw** [comment]
Parse errors should be consistent in validate and gauge run specs - https://github.com/getgauge/gauge/issues/848

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
