### ISSUE TITLE
Deleting a file which is not open should refresh the diagnostics

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/gauge#873]
### Expected behavior
Deleting a file which is not open should refresh the diagnostics.
### Actual behavior
Deleting a file which is not open. Diagnostics will be shown even after the file is deleted.
### Steps to reproduce
1. Create a file `concept.cpt` with contents 
```
# concept
* step1
```
where `step1` is unimplemented.
2. use the concept in spec file.
3.Now delete the `concept.cpt` file without opening it.

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
