### ISSUE TITLE
Validation must honour gauge_exclude_dirs

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#874]
**Expected behavior**
When `gauge_exclude_dirs` is used, validation must not consider such files/folders for validation.

**Actual behavior**
When `gauge_exclude_dirs` is used validation does not consider it.

> Though `gauge_exclude_dirs` is not used often. The point is validation should be a reused before execution. There seems to be a tech debt for code clean up

**Steps to replicate**
* In a project use `gauge_exclude_dirs`.
* Create a concept inside the gauge_exclude_dirs.
* use the concept in the spec files in the gauge project
* The IDE does not show errors
* execute gauge and this gives the validation error that `Concept` is a `step that is unimplemented`
* This is the same behavior in the console as well

**Version**
```
Gauge version: 0.9.5.nightly-2017-11-23
Commit Hash: 51cfe8d

Plugins
-------
js (2.0.3.nightly-2017-11-23)
```

**Comment by Apoorva-GA** [comment]
@sguptatw need a confirmation.

`gauge validate specs` and `gauge run specs` are giving different output when `gauge_exclude_dirs ` property is set.

Is this the isuue is all about?

**Comment by sguptatw** [comment]
@Apoorva-GA - Yes

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge nightly >= 4/12/17
