### ISSUE TITLE
Failed to initialize scenario datastore. 

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#876]
**Expected behaviors**
When there are errors executing the project, we should get the errors.

**Actual behavior**
Getting `Failed to initialize scenario datastore. Error: write tcp 127.0.0.1:58864->127.0.0.1:58866: use of closed network connection`

**Steps to replicate**
* `gauge run specs` on the `js` project
[craft2.zip](https://github.com/getgauge-contrib/gauge-js/files/1501310/craft2.zip)
> Do this without node install. It fails for several reasons and starts giving the above error

**Version**
```
Gauge version: 0.9.5.nightly-2017-11-23
Commit Hash: 51cfe8d

Plugins
-------
js (2.0.3.nightly-2017-11-23)
screenshot (0.0.1)
```

**Comment by sguptatw** [comment]
Furthermore, HTML report is not getting generated
```
Plugin [Html Report] with pid [8704] did not exit after 4.00 seconds. Forcefully killing it.
Specifications: 1 executed      0 passed        1 failed        89 skipped
Scenarios:      1 executed      0 passed        1 failed        8099 skipped
```

**Comment by sguptatw** [comment]
The same issue also occurs only taiko is not installed.

**Comment by sguptatw** [comment]
The issue is replicable when node is installed
**Steps to replicate**
* Project - https://github.com/getgauge/gauge-lsp-tests
* In autocomplete.spec, Change the 1st step to  
```
* start gauge daemon for project "testdata/autocomp"
``` 
* run the specs from command line
```
gauge run specs
```
>Observe the `Failed to initialize scenario datastore`. and `Error: write tcp 127.0.0.1:50272->127.0.0.1:50273: use of closed network connection`

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
