### ISSUE TITLE
Remove use of panic.

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#877]
We use panic in our code in some places. Panics are not recommended by Go. Panic is to be used only if the error is not recoverable. Go's idiomatic way of handling exceptions is by returning a error back to the callee.

**Comment by sguptatw** [comment]
Opening a non-gauge project also gives a crash message in the IDE. Will that also be addressed with this change?

**Steps to replicate**
* Open the following [attachment.zip](https://github.com/getgauge/gauge/files/1508111/attachment.zip) in IDE

**Comment by sriv** [comment]
@sguptatw - which IDE/OS are you facing this issue?

**Comment by sguptatw** [comment]
Windows OS. VSCode IDE

**Comment by sriv** [comment]
fix should be available in nightly >= 1/12/2017
