### ISSUE TITLE
[Usability issue] Error message not clearly visible on powershell prompt

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#878]
**Expected behavior**
On the command prompt, the colors used should be readable.

**Actual behavior**
The error messages are not clearly visible on the powershell prompt of Windows

<img width="615" alt="errornotclear" src="https://user-images.githubusercontent.com/6310197/33302396-b947507a-d421-11e7-9ad6-8c6bf927df6a.png">

**Steps to replicate**
* run a failing test on Windows powershell prompt

**Version**
```
Gauge version: 0.9.6.nightly-2017-11-27
Commit Hash: ab40a8e

Plugins
-------
js (2.0.3.nightly-2017-11-27)
```

**Comment by sriv** [comment]
Gauge does not have information about the user's terminal settings/properties. So it cannot use matching colours.

Suggestion: change powershell's background colour to a more convenient one.

**Comment by zabil** [comment]
I agree.
Error on PowerShell by other command line tools also look the same. The theme has to be adjusted. I am closing this.
