### ISSUE TITLE
can gauge support Junit runner?

### ISSUE THREAD

**Issue by felix1982** [getgauge/gauge#882]
**can gauge support Junit runner?**

in cucumber-jvm, can run scenarios like this:

import cucumber.api.junit.Cucumber;
import org.junit.runner.RunWith;

@RunWith(Cucumber.class)
public class RunCukesTest {
}

**Comment by zabil** [comment]
Unlike cucumber that uses JUnit runner, Gauge **is** the runner. 
So there's no support for the JUnit runner.
