### ISSUE TITLE
log all LSP request response to file

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge#884]
Record all LSP request and response to a file. It will help to figure out the steps to replicate an issue.

**Comment by zabil** [comment]
Is this configurable and switched off by default?

**Comment by BugDiver** [comment]
by default, it is turned off and can be enabled by using `gauge.enableDebugLog` in `vs code`.

**Comment by BugDiver** [comment]
SHould be available in gauge nightly >= 29-11-2017

**Comment by sguptatw** [comment]
VSCode is only a client to LSP.  This setting is currently within VSCode. But this usecase seems to be for non-VSCode clients as well.
Let's say there is a problem in LSP-tests(that don't use VSCode) I need the logs to figure out the problem.

**Comment by sriv** [comment]
@sguptatw  try `gauge daemon --lsp -l debug`
