### ISSUE TITLE
Gauge langauge server must work without specifying a root directory

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge#885]
### Actual behavior

While launching a language server `gauge` expects a root directory.
Language server plugins for [neovim](https://github.com/autozimu/LanguageClient-neovim#quick-start) are started for files or extensions.

The current configuration for vim gauge language is
```
let g:LanguageClient_serverCommands = {
    \ 'spec': ['gauge', 'daemon', '--lsp', '--dir=/pathto/gauge/project'],
    \ }
```

As the `gauge` language server process is only launched once, per file passing path cannot be dynamic, making editing files in `vi` difficult. 

### Expected behavior
Launch the language server from any path
```
$ gauge daemon --lsp
```

Once launched, Gauge will resolve the gauge root project and work for all the features.
Gauge must handle multiple project root paths.

**Comment by Apoorva-GA** [comment]
Gauge LSP should work without specifying root dir.

Configuration of vim:

```
au BufRead,BufNewFile *.cpt set filetype=spec

let g:LanguageClient_serverCommands = {
    \ 'spec': ['gauge', 'daemon', '--lsp'],
    \ }
```

Fix should be available in gauge nightly >= 2/1/18

**Comment by sguptatw** [comment]
Need confirmation if the following issues are related
- Unable to require module - https://github.com/getgauge-contrib/gauge-js/issues/94
- format test case failing with `Fix all the problems first` even if project does not have problems.

**Comment by Apoorva-GA** [comment]
Looks like the issues are not related and both the issues are fixed. So you can go ahead and test this.
