### ISSUE TITLE
Code Lens call from LSP returns null

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#887]
**Expected behavior**
Find usages should be available always.

**Actual behavior**
It stops working after opening 4 consecutive js files.

**Steps to replicate**
* Project - [LSP Tests](https://github.com/getgauge/gauge-lsp-tests)
* Open the following files one after the other 
```
diagnostics.js
execution.js
fileAction.js
gaugeDaemon.js
```
> Observe that usages for `start gauge daemon for project <relativePath>` is not shown

**Version**
```
Gauge version: 0.9.6.nightly-2017-11-30
Commit Hash: 9dad03e

Plugins
-------
js (2.0.3.nightly-2017-11-30)
```

**Comment by sguptatw** [comment]
OS - Windows 10
Logs -
[lsp.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46e4878a61cec1b99de6b546a749b2ce6b1371262d5cf22d7583b02bba462b55595f4ea8105b0c41feeb9539e4e76224d50152a7842f4d7ed43c16a6b9871ebd02bc25884b87b3b98e5e8d.zip)
> Observe 
```
10:51:01.101 --> request #4: textDocument/codeLens: {"textDocument":{"uri":"file:///c%3A/work/getgauge/gauge-lsp-tests/tests/autocomplete.js"}}
10:51:01.128 <-- result #4: textDocument/codeLens: null
```
The codeLens call for the file returns null.

**Comment by sguptatw** [comment]
Getting the following error from LSP
```
16:15:55.426 --> request #202: textDocument/codeLens: {"textDocument":{"uri":"file:///c%3A/work/getgauge/gauge-lsp-tests/testdata/performance/specs/example.spec"}}
16:15:55.426 <-- error #202: textDocument/codeLens: {"code":0,"message":"failed to parse specification c:\\work\\getgauge\\gauge-lsp-tests\\testdata\\performance\\specs\\example.spec","data":null}
```
> Observation - able to validate and run the spec from the command line.

After this error, gauge crashes. Run spec... does not appear on the spec file.

**Steps to replicate**
* Project - [performance.zip](https://github.com/getgauge/gauge/files/1526752/performance.zip)
* After creating the concepts in folder 10.
* Implemented `step 1` and `step 2`
* removed the exception
* opened example spec
> Then the code Lens call started returning null

**Version**
```
Gauge version: 0.9.6.nightly-2017-12-01
Commit Hash: fdcd4e2

Plugins
-------
js (2.0.3.nightly-2017-11-30)
```
IDE - gauge-0.0.3.nightly-2017-12-01.vsix

**Comment by Apoorva-GA** [comment]
Not replicable. 
Please check if this is still relevant.
