### ISSUE TITLE
Unable to install gauge plugins on CI

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#888]
**Expected behavior**
Should be able to install js

**Actual behavior**
Getting the error 
`Command executed with exception: 2017/12/02 09:07:15 Unable to read C:\Users\appveyor\AppData\Roaming\gauge\config\id`

**Steps to replicate**
* Appveyor CI -  https://ci.appveyor.com/project/getgauge/gauge-lsp-tests/build/1.0.1

**Version**
```
Gauge - gauge-0.9.5
js - 2.0.3.nightly-2017-11-30.zip
```

**Comment by sguptatw** [comment]
> Info

This happens on a new gauge install, gauge subcommands seem to run before gauge has a chance to write the config. the subcommands attempt to use the config
it happens only on first run, next run onwards works fine.

> Issue

We shouldn't be getting these messages.

**Comment by sriv** [comment]
fix should be in nightly >= 4/12/2017
