### ISSUE TITLE
Add support for project templates

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#89]
Right now, there is a default template that gets copied over while doing `gauge --init <lang>`. While this `hello world` template is useful for demos, there isn't any practical use for it.

Have a repository/gallery of templates that can initialize various project types. Something that would contain templates for:

- [x] Java
  - [x] Webdriver 
  - [ ] Calabash-ios
  - [ ] Calabash-android
  - [x] Vanilla (no frameworks)

- [x] Ruby
  - [ ] Rails
  - [ ] Sinatra
  - [x] Vanilla (no frameworks)

- [x] CSharp
  - [ ] ASP.NET MVC
  - [ ] ASP.NET Web API
  - [x] Vanilla (no frameworks)

**Comment by navaneeth** [comment]
+1

**Comment by kmugrage** [comment]
+1

**Comment by apoorvam** [comment]
Update : 
To make getting started experience easier, we have added support for templates in Gauge v0.3.0. You can initialize a project with a particular template and Gauge will create the entire folder structure along with basic build files (if applicable) and the required dependencies.

To begin with, we have added the following templates.

* **java** (Vanilla, without any frameworks, build tools, etc)
* **java_maven** (template for creating a Gauge Java project with Maven)
* **java_maven_selenium** (template for creating a Gauge Java project with Maven and selenium, includes WebDriverFactory setup)
* **csharp** (Vanilla, without any frameworks, build tools, etc)
* **ruby** (Vanilla, without any frameworks, build tools, etc)
At any point of time, you can get the list of available templates by running the command `gauge --list-templates`.

Any feedback is much appreciated.

**Comment by sriv** [comment]
C# templates are available via Visual Studio plugin. Users can still create a vanilla C# project by running `gauge --init csharp`. 

Closing this issue for now, contributions to templates are welcome.
