### ISSUE TITLE
in java environment,when you run multi-thread in gauge,the thread won't run,especially for the time-consuming task；And won't run in threadpool，such as fixedthreadpool。 

### ISSUE THREAD

**Issue by hecyxy** [getgauge/gauge#893]
such as:
ExecutorService service  = Executors.newFixedThreadPool(3);
        for(int i = 1;i<=24;i++){
            final int index = i;
            service.execute(new Runnable() {
                @Override
                public void run() {
                    System.out.println("current number"+index);
                    if(index % 3 == 0)
                        execute(conn1);
                    else if(index % 3 == 1)
                        execute(conn2);
                    else
                        execute(conn3);
                }
            });
        }

Gauge version: 0.8.4

Plugins
-------
html-report (4.0.2)
java (0.6.2)

**Comment by sriv** [comment]
Hi,

Apologies for the very late response, but in case you still need an answer, I tried the below, and it does seem to run as expected.

```
    @Step("Run tasks")
    public void setLanguageVowels() throws InterruptedException {
        ExecutorService service = Executors.newFixedThreadPool(3);
        for(int i = 1;i<=24;i++){
            final int index = i;
            service.execute(new Runnable() {
                @Override
                public void run() {
                    System.out.println("current number"+index);
                    if(index % 3 == 0)
                        execute(1000);
                    else if(index % 3 == 1)
                        execute(3000);
                    else
                        execute(5000);
                }
            });
        }
        service.awaitTermination(5, TimeUnit.MINUTES);
    }

    private void execute(int time) {
        try {
            Thread.sleep(time);
        } catch (InterruptedException e) {
            System.out.println(e);
        }
    }
```

Sample output:

```
# Specification Heading
  ## Run tasks	current number1
current number3
current number2
current number4
current number5
current number6
current number7
current number8
current number9
current number10
current number11
current number12
current number13
current number14
current number15
current number16
current number17
current number18
current number19
current number20
current number21
current number22
current number23
current number24
```

**Comment by sriv** [comment]
I am closing this issue, but please feel free to comment if I misunderstood your case. thanks.
