### ISSUE TITLE
LSP should handle case insensitive paths based on OS

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#898]
**Expected behavior**
If OS allows case-insensitive paths, gauge should handle it

**Actual behavior**
Windows allows case-insensitive paths. However gauge LSP file name requires it to be case sensitive.

**Steps to replicate**
* LSP tests - https://ci.appveyor.com/project/getgauge/gauge-lsp-tests - Parameter code completion

**Version**
```
Gauge version: 0.9.6

Plugins
-------
js (2.0.3.nightly-2017-11-30)
```

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
