### ISSUE TITLE
Provide a hook for screenshots

### ISSUE THREAD

**Issue by prateekbaheti** [getgauge/gauge#9]
Currently only the language runner can take screenshots on failure. Need to add  a hook to allow taking custom screenshots.

**Comment by sriv** [comment]
The language runners should continue taking screenshots IMO, we just need them to be more intelligent, and allow users to configure screenshot mechanisms.

For instance, the default screenshot mechanism in ruby could be to invoke `gauge_screenshot`, but that would just capture the active screen. Instead, there could be an option to use driver's built-in screenshot mechanisms, particularly useful when using headless drivers.

**Comment by prateekbaheti** [comment]
Implementations for a Custom Screenshot hook need to be added for each language implementation
- [ ] [Java](https://github.com/getgauge/gauge-java/issues/18)  
- [ ] [Csharp](https://github.com/getgauge/gauge-csharp/issues/22)  
- [ ] [Ruby] (https://github.com/getgauge/gauge-ruby/issues/13)

**Comment by sriv** [comment]
Ruby support is being tracjed via getgauge/gauge-ruby#18
