### ISSUE TITLE
Check enum parameters before runtime

### ISSUE THREAD

**Issue by andrew041** [getgauge/gauge#901]
### Expected behavior
When using an enum as a parameter in a step, the values of the enum should be displayed as options and if a value is entered that is not in the enum, the step should show an error.

### Actual behavior
When using an enum as a parameter in a step, the value entered into the step is not checked until runtime.

### Steps to reproduce
1. Create an enum with some values.
2. Create a step that uses the enum.
3. Create a spec that uses the step that has been created.
4. Observe how there are no available options displayed for the enum parameter.
5. Observe how any value can be entered in the enum parameter without any error.

### Gauge version
Gauge version: 0.9.5

Plugins
-------
html-report (4.0.2)
java (0.6.5)
screenshot (0.0.1)
spectacle (0.1.2)
```

**Comment by nehashri** [comment]
@andrew041 It looks like a good feature to have.
Gauge core does not hold any implementation details. Gauge does not invoke the language runner until runtime. Hence, you see these errors coming up only during runtime. Also, not all language runners support Enum parameters. Hence, this feature may not be valid for all runners.

May I know which editor you are talking about? We could probably track this there.

**Comment by andrew041** [comment]
@nehashri I am using gauge with java in the Intellij IDE.

**Comment by sguptatw** [comment]
This issue was moved to getgauge/Intellij-Plugin#345
