### ISSUE TITLE
Peek definition of a step does not highlight the step definition

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/gauge#902]
_From @zabil on December 13, 2017 11:12_

```
VS-Code version: 1.18.1
Gauge Extension Version: 0.0.3

Gauge version: 0.9.6
Commit Hash: 0b85c7e

Plugins
-------
csharp (0.10.1)
go (0.1.1)
html-report (4.0.2)
java (0.6.5.nightly-2017-09-05)
js (2.0.3)
python (0.2.2)
ruby (0.4.2)
screenshot (0.0.1)

```

### Steps to replicate
```
$ gauge init js
$ code .
```

* Open `example.spec` in VS code
* Use peek definition (ctrl+shift+f10) on any step
* Step implementation is not highlighted

![peekdefintion](https://user-images.githubusercontent.com/54427/33936054-24268b64-e024-11e7-934b-582f1fad757f.png)

### Expected behavior
Highlight the function or function name for e.g.

![highlightedreference](https://user-images.githubusercontent.com/54427/33936143-81c84a64-e024-11e7-8f84-0656df3bc020.png)

_Copied from original issue: getgauge/gauge-vscode#72_

**Comment by Apoorva-GA** [comment]
On peek definition the entire step definition gets highlighted.

Should be available in gauge and gauge-js nightly >= 21/12/17

**Comment by sguptatw** [comment]
Getting `Duplicate step implementation` on every step after clicking on `Peek Definition`.

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge-js nightly >= 8/1/18
