### ISSUE TITLE
Request timedout for Message IDs in v0.9.6

### ISSUE THREAD

**Issue by juame** [getgauge/gauge#906]
Following behaviour with 0.9.6:

### Expected behavior

The example specs/steps should work as in v0.9.5:

```bash
$ gauge run specs/
# Specification Heading
  ## Vowel counts in single word	 ✔ ✔
  ## Vowel counts in multiple word	 ✔ ✔

Successfully generated html-report to => /Users/julian/go/src/github.com/juame/myproject/reports/html-report
ok  	command-line-arguments	0.160s
Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	2 executed	2 passed	0 failed	0 skipped

Total time taken: 17ms
```

### Actual behavior

The example specs/steps with example implementation (go plugin) times out:
```bash
$ gauge run specs/


  Error Message: Request timedout for Message ID => 7
  Stacktrace: 
  

  Error Message: Request timedout for Message ID => 9
  Stacktrace: 
  
Successfully generated html-report to => /Users/julian/go/src/github.com/juame/myproject/reports/html-report
ok  	command-line-arguments	60.301s
Specifications:	0 executed	0 passed	0 failed	0 skipped
Scenarios:	0 executed	0 passed	0 failed	0 skipped

Total time taken: 1m0.053s
```

### Steps to reproduce
1. cd $GOPATH/src/github.com/myname/myproject
2. gauge init go
3. gauge run specs/

### Gauge version
```
Gauge version: 0.9.6

Plugins
-------
go (0.1.1)
html-report (4.0.2)
screenshot (0.0.1)
```

Can someone confirm this? Do I need to change something in the go project structure for the new release? Thank you!

**Comment by BugDiver** [comment]
@juame  I could replicate this issue with the sample project. After further analysis found out that the actual issue is in `go` runner.

**Comment by BugDiver** [comment]
This issue was moved to getgauge-contrib/gauge-go#15
