### ISSUE TITLE
Add ability to override flags by default via config file

### ISSUE THREAD

**Issue by sergDao** [getgauge/gauge#907]
Hello.I want to have ability to run specs with enabled verbose flag  by default without passing flag during every specs run. do we have this possibility? For example I want to set in config file verbose=true and dont care about passing this flag. Is't possible?

**Comment by odudar1** [comment]
I need this feature also!!! I think it will be very useful.

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
