### ISSUE TITLE
format fails with error even with a valid project

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#911]
**Expected behavior**
Format should not fail when project is valid

**Actual behavior**
LSP Test for format is failing - https://build.getgauge.io/go/tab/build/detail/JS-LSP-Tests/208/tests/1/linux

**Version**
```
Gauge version: 0.9.7.nightly-2018-01-08
Commit Hash: bc9784c

Plugins
-------
js (2.1.0.nightly-2018-01-08)
```

**Comment by riju91** [comment]
fixed as result of https://github.com/getgauge/gauge/commit/1c656c456f98bd61e64dce3976a5a1a6a12e4d61
should be available from nightly >= 2018-01-11
