### ISSUE TITLE
Code Lens not appearing with a valid project

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#914]
**Expected behavior**
Should get `Run in parallel` when project is valid

**Actual behavior**
Getting Error: failed to parse specification, even though project is valid

**Step to replicate**
LSP Test - https://build.getgauge.io/go/tab/build/detail/JS-LSP-Tests/219/tests/1/linux

**Version**
```
Go cd build version - https://build.getgauge.io/go/tab/build/detail/JS-LSP-Tests/219/tests/1/linux
Gauge version: 0.9.8
Commit Hash: 1c656c4

Plugins
-------
html-report (4.0.4)
js (2.1.0)
```

**Comment by sguptatw** [comment]
**Note:** Use command
`gauge run specs --env=no-wd-js`
- https://build.getgauge.io/go/tab/build/detail/JS-LSP-Tests/227/tests/1/linux-js-no-wd

**Comment by Apoorva-GA** [comment]
This is not failing after the shut down method fix. Please check if this is still relevant.
