### ISSUE TITLE
autocomplete should not change the existing parameter

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#916]
**Expected behavior**
Autocomplete of a step should not change the parameters used in the current step

**Actual behavior**
* autocomplete of a step is changing the parameters

**Steps to replicate**
In LSP tests
* For step `start gauge daemon for project "data/runFromSpecfication"`
try autcompleting to `* start gauge daemon for project <parameter> with no runner`

This is changing the parameter data to `data/codecomplete`

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
