### ISSUE TITLE
Cannot continue after stopping gauge command in the command line

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#917]
**Expected behavior**
Should be able to continue with other operations

**Actual behavior**
have to restart the prompt to continue

**Steps to replicate**
* Run gauge specs
* Use Ctrl+C to stop the execution.
* Now try other commands. even `clear` does not respond

>Note: Observed on Windows 10
**Version**
```
Gauge version: 0.9.8.nightly-2018-01-10
Commit Hash: 1c656c4

Plugins
-------
js (2.1.0.nightly-2018-01-11)
```

**Comment by NicholasEF** [comment]
Running from the VSCode plugin, I discovered that the very small status bar at the bottom of the editor displays a 'Running' status when a test is kicked off, and it can be clicked to stop execution. Not sure if it is doing a Ctrl-C under the hood or what, but might be helpful.

<img width="304" alt="stop" src="https://user-images.githubusercontent.com/13222879/51067689-2cc9fe80-15da-11e9-86e6-b94d1c9bdc88.png">

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.

**Comment by alvesbm** [comment]
It still needs fixing when running gauge+python
