### ISSUE TITLE
[Windows] Verbose mode should show details in readable format

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#918]
**Expected behavior**
Should be able to read details printed on command line in verbose mode

**Actual behavior**
The messages get printed as shown in the image below
<img width="960" alt="verbosemode" src="https://user-images.githubusercontent.com/6310197/34948567-895efa1a-fa33-11e7-8688-536dbf4eb6bf.png">

**Steps to replicate**
* Occurs on Appveyor build - https://ci.appveyor.com/project/getgauge/gauge-lsp-tests

**Version**
```
Gauge version: 0.9.8.nightly-2018-01-10
Commit Hash: 1c656c4
Plugins
-------
html-report (4.0.3)
js (2.1.0)
xml-report (0.2.0)
```

**Comment by ocary** [comment]
What happens if you add the `--simple-console` flag?

**Comment by sriv** [comment]
please use `--simple-console` flag as @ocary suggested, on terminals that do not support ascii. 

closing this, feel free to reopen if issue persists.
