### ISSUE TITLE
Message on goto definition of unimplemented step

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#919]
_From @sguptatw on January 16, 2018 5:7_

**Expected behavior**
* The message should have the `step text`

**Actual behavior**
It has `* step text`. 

**Steps to replicate**
* Goto definition on an unimplemented step

**Version**
```
Gauge version: 0.9.8.nightly-2018-01-15
Commit Hash: 15c9822

Plugins
-------
js (2.1.1.nightly-2018-01-15)
```

_Copied from original issue: getgauge-contrib/gauge-js#100_

**Comment by Apoorva-GA** [comment]
This is because refactoring considers the whole step as a word.
If we omit the `*` refactoring will consider everything else like comments.
