### ISSUE TITLE
If refactoring is unsuccessful then it should not change specification or the impl file

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#932]
**Actual behavior**
The specification gets changed

**Steps to replicate**
* Create a new `gauge-js` project
* Refactor `Vowels in English language are "aeiou"` to `Vowels in English language are "aeiousdf" <file:specs/something>`
>Note: specs/something is a valid file

Refactoring fails - It changes the spec file content
```
Gauge version: 0.9.8.nightly-2018-01-30
Commit Hash: 2ed02d8

Plugins
-------
js (2.1.1.nightly-2018-01-16)
```

Bug on story - https://github.com/getgauge/gauge-vscode/issues/81

**Comment by Apoorva-GA** [comment]
Should be able to successfully refactor with special parameters.

Fix should be available in gauge nightly >= 15/02/12

**Comment by sguptatw** [comment]
Blocked 'cause of https://github.com/getgauge/gauge/issues/943
