### ISSUE TITLE
Gauge does not support Refactoring an alias. This should not trigger refactoring

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#933]
**Actual behavior**
It is changing the spec but no refactoring occurs

**Steps to replicate**
* Create a `gauge-js` project
* Create a step with alias
Try refactoring it. It changes spec and implementation file remains as is

**Version**
```
Gauge version: 0.9.8.nightly-2018-01-30
Commit Hash: 2ed02d8

Plugins
-------
js (2.1.1.nightly-2018-01-16)
```

Bug on story - https://github.com/getgauge/gauge-vscode/issues/81

**Comment by nehashri** [comment]
should be available in gauge-js nightly >= 7-2-18.
