### ISSUE TITLE
Refactoring with keyword table

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#934]
**Suggested behavior**
Yet to be discussed

**Actual behavior**
The value of the inline table is replaced with `<table>` in the refactored text

**Steps to replicate**
* Consider an `unimplemented` step
```
* The word <table> has "3" vowels \ sdfdsf
|sdfsdf|
|sdfsdf|
```
* Try refactoring to `The word <table> has "3" vowels \ sdf` in IDE.
* This replaces step with 
```
The word <table> has "3" vowels \ sdf <table>
```
**Version**
```
Gauge version: 0.9.8.nightly-2018-01-30
Commit Hash: 2ed02d8

Plugins
-------
js (2.1.1.nightly-2018-01-16)
```

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
