### ISSUE TITLE
Can gauge-java integrate with Junit/TestNG?

### ISSUE THREAD

**Issue by missley** [getgauge/gauge#937]
now, we use maven to integrate with gauge, but when programe has errors, is difficult to debug and resolve it.
can gauge support Junit/TestNG, then is easier to debug the spec/fixture?

**Comment by sriv** [comment]
gauge-java is a runner on its own. So, no, we do not have a way to integrate it with testng/junit or any other runner.

That being said, there is support to debug gauge-java specs using intellij idea. Please check [here](https://docs.gauge.org/using.html#debugging)

Feedback/issue reports are always welcome. If they are java specific, please log them against: https://github.com/getgauge/gauge-java.

**Comment by sriv** [comment]
gauge-java is a runner on its own. So, no, we do not have a way to integrate it with testng/junit or any other runner.

That being said, there is support to debug gauge-java specs using intellij idea. Please check [here](https://docs.gauge.org/using.html#debugging)

Feedback/issue reports are always welcome. If they are java specific, please log them against: https://github.com/getgauge/gauge-java.
