### ISSUE TITLE
[Windows] Installer default path should be corrected

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#941]
**Expected behavior**
It should be `C:\Program Files\Gauge\bin`

**Actual behavior**
It is `C:\Program Files\Gauge\bin\bin\bin\bin\`

**Steps to replicate**
* Download windows installer `gauge-0.9.8.nightly-2018-02-13-windows.x86_64.exe`
* Start installation
> Note: the default path is `C:\Program Files\Gauge\bin\bin\bin\bin\`

**Version**
```
gauge-0.9.8.nightly-2018-02-13-
windows.x86_64
```

**Comment by sriv** [comment]
fix should be available in nightly >= 14/2/2018
