### ISSUE TITLE
[Windows] Should not get security warning while trying to install Gauge

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#942]
**Actual behavior**
Getting the following warning while trying to install

<img width="400" alt="windowsdefender" src="https://user-images.githubusercontent.com/6310197/36241542-fec1a9c6-123c-11e8-8082-e0afa8f34c94.png">

**Steps to replicate**
* Try installing the windows nightly 64 bit `Gauge version: 0.9.8.nightly-2018-02-14`

**Version**
```
Gauge version: 0.9.8.nightly-2018-02-14
```

**Comment by Apoorva-GA** [comment]
`Windows App Certification Kit`  results says that:
-  we need to sign the uninstall.exe
- `installLocation` value should be provided.

Once these problems are fixed we can upload the XML result of a successful application certification [to](https://sysdev.microsoft.com.) A few days later, SmartScreen will be aware of the digital signature used for the certified program and will no longer warn the users on download.

**Comment by sguptatw** [comment]
Now, the installers are removed and single binary is used. We do not get any warning while using the binary from the command line. However when Gauge project is opened in VSCode, getting the following error.

![Firewall.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46ce9d88269582a583abf301b44fff9e2c4533317346f67d2581bb79b9477d520c0a1aac455e5f44f8a88a78a3b42e6c981e5ab38532022d8c6853beb2901eb70bbb25894e85beb98e44c0e83a25f5c6.png)

> Cancelling this does not cause issues to run Gauge commands.

**Comment by sriv** [comment]
Gauge binaries are now signed with SHA256 and a timestamp. Please see if this fixes this issue @sguptatw

**Comment by sguptatw** [comment]
Working as expected in
```
Gauge version: 0.9.8.nightly-2018-03-14
Commit Hash: 0ac4700
```
