### ISSUE TITLE
If a concept name already exists, should not allow another concept to be refactored to the same name

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#944]
**Actual behavior**
Another concept is allowed to be refactored to the same name

**Steps to replicate**
* Create a concept `Concept1`
* Create a concept `Concept2`
* Use Concept2 in a spec
* Refactor `Concept2` to `Concept1`
> Note: This is a usability issue
This refactoring is successful. This has changed all the spec files using this concept. Hence one/more parse error.

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
