### ISSUE TITLE
Change in a spec file does not have to publish diagnostics for all files

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#945]
**Expected behavior**
Should publish diagnostics for all files when the change can impact any other files

A change in js/concept file can impact diagnostics of other files. However a change in spec file does not impact diagnostics of other files.
So it should not publish diagnostics for other files

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
