### ISSUE TITLE
With both machine-readable and verbose parameters step level reporting is not output

### ISSUE THREAD

**Issue by ocary** [getgauge/gauge#948]
With both machine-readable and verbose parameters step level reporting is not output

As the IntelliJ plugin adds `machine-readable` to any spec, it is not possible to get step level output to the test runner in IntelliJ even if _verbose_ is added as a parameter.   IntelliJ 2017.3.5 and IntelliJ-Gauge plugin v3.9

This was not an issue in Gauge 0.9.3, Gauge-Java 0.6.5, IntelliJ plugin 3.4 and IntelliJ 2017.1.5  last known working versions where step-level reporting was output with the `verbose `parameter in IntelliJ.   Example below takes IntelliJ out of the equation, though I cannot say for sure what the output was at a command line (non-IntelliJ) in Gauge 0.93 + Java 0.6.5

### Expected behavior
When `verbose` is specified, step level reporting is expected in the console output.

In IntelliJ when a spec is run, this step level output would be human-friendly to read.

### Actual behavior
When both `verbose` and `machine-readable` are specified, step level reporting is not included in the console output

### Steps to reproduce
1.  run command:   `gauge run --machine-readable --verbose specs/example.spec`
2.  observe in output that individual steps are not output.

Sample output when both machine-readable and verbose are specified
```
C:\dev\GaugeJavaInit>gauge run --machine-readable --verbose specs/example.spec
{"type":"suiteStart"}
{"type":"specStart","id":"C:\\dev\\GaugeJavaInit\\specs\\example.spec","name":"Specification Heading","filename":"C:\\dev\\GaugeJavaInit\\specs\\example.spec","line":1}
{"type":"scenarioStart","id":"C:\\dev\\GaugeJavaInit\\specs\\example.spec:13","parentId":"C:\\dev\\GaugeJavaInit\\specs\\example.spec","name":"Vowel counts in single word","filename":"C:\\dev\\GaugeJavaInit\\specs\\example.spec","line":13,"result":{"time":0}}
{"type":"scenarioEnd","id":"C:\\dev\\GaugeJavaInit\\specs\\example.spec:13","parentId":"C:\\dev\\GaugeJavaInit\\specs\\example.spec","name":"Vowel counts in single word","filename":"C:\\dev\\GaugeJavaInit\\specs\\example.spec","line":13,"result":{"status":"pass","time":1}}
{"type":"scenarioStart","id":"C:\\dev\\GaugeJavaInit\\specs\\example.spec:21","parentId":"C:\\dev\\GaugeJavaInit\\specs\\example.spec","name":"Vowel counts in multiple word","filename":"C:\\dev\\GaugeJavaInit\\specs\\example.spec","line":21,"result":{"time":0}}
{"type":"scenarioEnd","id":"C:\\dev\\GaugeJavaInit\\specs\\example.spec:21","parentId":"C:\\dev\\GaugeJavaInit\\specs\\example.spec","name":"Vowel counts in multiple word","filename":"C:\\dev\\GaugeJavaInit\\specs\\example.spec","line":21,"result":{"status":"pass","time":0}}
{"type":"specEnd","id":"C:\\dev\\GaugeJavaInit\\specs\\example.spec","name":"Specification Heading","filename":"C:\\dev\\GaugeJavaInit\\specs\\example.spec","line":1,"result":{"status":"pass","time":0}}
{"type":"suiteEnd","result":{"status":"pass","time":0}}
Successfully generated html-report to => C:\dev\GaugeJavaInit\reports\html-report\index.html
```

### Gauge version
```
Gauge version: 0.9.7
Commit Hash: bc9784c

Plugins
-------
csharp (0.10.1)
flash (0.0.1)
html-report (4.0.3)
java (0.6.6)
screenshot (0.0.1)
xml-report (0.2.0)
```

**Comment by ocary** [comment]
The problem were having is that after moving from Gauge 0.9.3 to 0.9.7, the `--verbose` tag does not work as expected in IntelliJ.   The IntelliJ plugin is adding `--machine-readable` and there is no way around.   When specifying `--machine-readable` and `--verbose`, I'd expect the step level reporting to still be output, but to be shown in JSON format like the other messages.  The IntelliJ Gauge plugin would be responsible for taking this and presenting it in the IntelliJ test runner in a human-friendly format.

Given our QA staff uses the step level reporting to track progress of longer running specs and debug failing specs, not being able to  get step level reporting in IntelliJ is definite problem.

**Comment by nehashri** [comment]
This issue was moved to getgauge/Intellij-Plugin#315
