### ISSUE TITLE
Support for new line between a Step text and a table parameter

### ISSUE THREAD

**Issue by apoorvam** [getgauge/gauge#95]
Currently there should be no new line between step and param table. But we should also check for a newline between them.
This should be acceptable:

```
* Step that takes a table 

     | Product | Description                  |
     | Gauge   | BDD style testing with ease  |
```

This makes preview better.

Needs changes on these:
- [x] Gauge Core parser changes.
- [x] https://github.com/getgauge/Intellij-Plugin/issues/145
- [x] https://github.com/getgauge/Intellij-Plugin/issues/147
- [x] https://github.com/getgauge/gauge-visualstudio/issues/136

**Comment by sguptatw** [comment]
# The following issues are present in IntelliJ.

## List of issues

- [ ] #Intellij-Plugin/issues/145
- [ ] #Intellij-Plugin/issues/147

**Comment by kashishm** [comment]
@sguptatw All the issues mentioned in the checklist are fixed. Please close this issue if it's fixed

**Comment by sguptatw** [comment]
I have raised a separate issue to track VS highlight -  https://github.com/getgauge/gauge-visualstudio/issues/169
