### ISSUE TITLE
Allow writing multi-line specification title and scenarios

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#953]
_From @f7g on February 16, 2018 21:13_

### Enhancement
Allow writing multi-line specification title and scenarios because sometimes they could get really long.

### Gauge version
```
0.9.7
```

_Copied from original issue: getgauge/gauge-csharp#120_

**Comment by zabil** [comment]
Refer

https://github.com/getgauge/gauge/issues/265#issuecomment-411675671

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
