### ISSUE TITLE
LSP features not available should not comeup

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#954]
_From @sguptatw on February 7, 2018 6:4_

**Actual behavior**
Currently VSCode IDE features is supported for js, ruby and python. LSP Feature options is coming up for gauge projects with language runners not compliant with LSP.

**Steps to replicate**
* Create a `gauge-dotnet` project
* Open a spec file
> Note: Code Lens debug appears.

**Version**
```
Gauge version: 0.9.8.nightly-2018-02-02
Commit Hash: bff4f46

Plugins
-------
ruby (0.4.3.nightly-2018-02-07)
```

_Copied from original issue: getgauge/gauge-vscode#133_

**Comment by nehashri** [comment]
Gauge should enable lsp features that require the runner only if runner supports lsp. LSP features that do not require the runner can be enabled even if runner does not support LSP or is not started. 

LSP features that require the runner should be enable only when runner after runner is started processing the requests. However some features can work even if runner is not up, though they may not need runner to be up for better user experience.

LSP features that require the runner to be functional are 
- Goto definition.
- Rename
- Generate stub
- debugging

LSP features that can work partially even if runner is not up are
- code completion
- publish diagnostics (publish only parse errors).
These features should not fail to execute if runner is not up. 

Other LSP features should work well even if runner is not up.

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
