### ISSUE TITLE
Running specs before parallel execution

### ISSUE THREAD

**Issue by jonathangiber** [getgauge/gauge#962]
New feature 

There are some tests that can't run in parallel, thus, I would like to run them after a group of spec that run in parallel and get all the results in one report.

**Comment by nehashri** [comment]
@jonathangiber Can you give us an example why you would like to run tests in serial after a parallel run?

**Comment by jonathangiber** [comment]
@nehashri sure, I'm running many tests, some of them cannot be run in parallel mode (I can explain why if needed). So basically, I would like to get 1 html report with all the tests that I need to run, this is not possible since if I run two scripts one after another (for example a parallel run and after that a normal run), I will get 2 reports.

Thanks,

**Comment by nehashri** [comment]
@jonathangiber Please do elaborate on why you are running some tests in serial while some in parallel.

**Comment by jonathangiber** [comment]
Basically I would like to run all of them in parallel, but since we have some tests related to okta, those cannot run in parallel. That's why I would like to run those on serial.

**Comment by nehashri** [comment]
@jonathangiber Now I see why you need this feature. 
Unfortunately, we do not have the bandwidth to prioritize this right now. If you would really like to see one report, you may want to consider writing something custom to combine [json](https://github.com/apoorvam/json-report) reports.

**Comment by jonathangiber** [comment]
@nehashri understood, thank you very much

**Comment by sriv** [comment]
Reopening this. I still feel this is a valid feature request.

Users can choose to configure different runs such as:

- filter by tags
- filter by env.

The report can be independantly generated, however there could also be a way to merge two reports when it makes sense to view them together.

**Comment by j-morsum** [comment]
This is certainly something that would be useful for me. 

I have a few tests where the number of items are checked in two different places to see if they match. However if I have other tests running in parallel, the tests fail recurrently because between the 1st and 2nd checks a new item is created by a test running in parallel. 

A possible alternative, as was mentioned, is the ability of merging reports from different runs.

**Comment by sriv** [comment]
Here's a thought - what do you (@jonathangiber, @j-morsum ) feel about this:

- introduce a project-level new run configuration file (ex. `gauge-run.yml` / `gauge-run.json`) which can hold rules to execute.
- gauge shall honour the config file to figure out how the execution has to be orchestrated.

The question is - what all could such a config dictate?

**Comment by dudicp** [comment]
Hi,

Another possible option for your consideration is to add this settings to the spec file i.e. 

`settings: parallel (default) / pre:[priority] / post:[priority]
`
That way, not need to maintain another configuration file and duplicate spec/scenario names to this file.
The priority enable configure the order of the tests running pre/post the parallel tests.

What do you think?

**Comment by jonathangiber** [comment]
@sriv 
Another possibility I can think of is having a reserved tag keyword e.g. prerun/postrun that will trigger the spec to run in serial before or after the parallel run, same idea as the previous comment, to avoid another config file.

**Comment by sriv** [comment]
Good ideas, thank you @jonathangiber and @dudicp 

My only concern with the spec file containing this - it's is a "runtime" config, and I somehow feel this is not related to how one would express the test itself. 

@zabil - what do you think? There are two school of thoughts.

**Comment by j-morsum** [comment]
For me one of the problems using the specs files is losing the ability to run the tests based on the tags. So that would mean that the whole spec needs to run in serial and not only some scenarios. 

I would prefer to have a flag (e.g. --pre / --post) which would receive a tag or a spec file to run the scenarios in serial before or after the parallel execution.

**Comment by jonathangiber** [comment]
@j-morsum that sounds good for me too

**Comment by zabil** [comment]
Like @sriv points out, it's better have run time information outside the spec files. 
@j-morsum suggestion looks good.

Call it `--setup` and `--teardown` which is available for both serial and parallel runs?

**Comment by jonathangiber** [comment]
Any chance to prioritize it?

**Comment by fadc80** [comment]
I think to really benefit from parallel execution your tests should not
interfere with each other. If you start to have many order execution rules,
then your tests can become hard to mantain. In the worst case, you may end
up with tests that doesn't run in parallel at all. Couldn't you redefine
your tests to make them harmless to each other? I had a similar issue here,
but the solution was simple. As I was running my tests under the same user,
they eventually failed. In this case, I had just to make sure each test was
using its own user.

[ ]'s

Em Qua, 30 de jan de 2019 13:15, jonathangiber <notifications@github.com
escreveu:

**Comment by dudicp** [comment]
@fadc80, I defiantly agree with your approach however sometimes it's not applicable.
Specifically for global settings which affects the entire state of the system, for example, in our system you might configure MFA for authentication globally for all users in the organization, enabling this feature obviously affects the rest of the tests and it will be nice to test it pre/post the other tests.

**Comment by zabil** [comment]
Here's a proposal.

Add an option to `--parallel` for filtering by tags.
For e.g.

```
$ gauge run specs  --parallel "atag"
```

This will first run all scenarios without the tag `atag` serially, and then run in parallel scenarios with the tag `atag`.

This can be used with other tags for example

```
$ gauge run --tags "auth" specs --parallel "atag"
```
Which will run scenarios tagged `auth` serially before running `atag` in parallel.


In case the tags are repeated for e.g.

```
$ gauge run --tags "atag" specs --parallel "atag"
```

It ignores the --parallel option for "atag" with a warning.

#### Open Question
* Support for tag filters on `--parallel` option.

**Comment by dudicp** [comment]
Looks good. Thanks!

BTW, what will be the default behavior when "--parallel" argument not specified? will all specs run serially?

**Comment by zabil** [comment]
Yes.

The default behaviour will be the same as now. i.e. It will run serially when unless `--parallel` flag is added.

**Comment by ajoecker** [comment]
though I like the approach, I think intuitively the `parallel` flag is harder to undestand, what the execution order is. 

It is clear, that the following tags are run in parallel, but before or after everything else ?
It might be ok, if documentation is sufficient, but then still one would need to look it up, instead of understand it right away.

Also, are there cases, where the parallel tests shall run **before** the serial ones ? 
Also, can I run multiple tags in parallel (like `--parallel tag1, tag2` to execute all tests with either one of them ?)

**Comment by zabil** [comment]
> but before or after everything else ?

It is after everything else. Because it's an option to the run tag. 

```
gauge run specs                   // serial
gauge run specs --parallel        // will run everything in parallel
gauge run specs --parallel "tags" // only specific tags in parallel after running everything else in serial
```

> Also, are there cases, where the parallel tests shall run **before** the serial ones ?

Yes there might be cases. I think it's best to come up with an optional flag for `run` which can also specify the default order of execution. For e.g.

> Also, can I run multiple tags in parallel (like `--parallel tag1, tag2` to execute all tests with either one of them ?)

Yes, you can. `--parallel "tag1, tag2"` will run scenarios tagged with `tag1` and `tag2` in parallel

**Comment by BugDiver** [comment]
There are few tech issues with  @zabil's proposal for providing options to `--parallel` 

## Issues
Since `--parallel` is a boolean flag it won't be possible to give string options to it. Making it a string flag will also not work the scenario when we want to execute all the specs in parallel, cause string flags can't be used without a value.

## Solution
Let the `--parallel` flag be as it is (boolean).
Add another string flag `--filter` (it can be changed to a better name) which takes `tag` values

So this
```
gauge run specs                   // serial
gauge run specs --parallel        // will run everything in parallel
gauge run specs --parallel "tags" // only specific tags in parallel after running everything else in serial
```
can be something like
```
gauge run specs                   // serial
gauge run specs --parallel        // will run everything in parallel
gauge run specs --parallel --filter "tags" // only specific tags in parallel after running everything else in serial
```
If the filter option is used without parallel flag give an error saying
`Invalid Command. flag --filter can be used only with --parallel`

**Comment by jonathangiber** [comment]
Just a question regarding your solution @BugDiver if I understand it well.

Lets say I have many specs tagged "in-progress". So I make a run, for example: gauge run specs --parallel --filter "!in-progress & !serial". So basically after everything runs in parallel, "in-progress" and "serial" tags will run in serial but I would like to exclude at all those who are "in-progress". 

Is there anyway to exclude those with this solution proposed?
Thanks!

**Comment by nehashri** [comment]
@jonathangiber you should still be able to use the `--tags` flag to exclude the specs from serial and parallel runs.

**Comment by nehashri** [comment]
@jonathangiber @j-morsum @dudicp @fadc80 We have come up with one approach for this feature as a first cut. 
We are thinking of creating a new instance of the language runner for the specs that need to be run in serial. The specs that need to be run in parallel is run is a separate instance of language runner after the serial execution finishes. 

Pros :
* Simpler and easier solution to implement. 
* Easier to separate the serial and parallel runs.

Cons :
* Multi-threaded parallel execution will not work well. The specs run in serial will run in a completely different instance than that of the parallel runner. State and context will not be shared across the specs run in serial and parallel.
* Performance may be affected in some language runners, as we are starting runners at two points.

Please let us know if any of these pros or cons will not work well for your usecase. We are trying to understand what works well for you as a first cut for this feature and implement that first.

**Comment by BugDiver** [comment]
The flag name `--filter` could be quite confusing sometime. We are thinking to change it to `--only` since it feels more aligned with the use case.
Examples:
* `gauge run specs --parallel --only "tag1 & tag2"`
* `gauge run specs --tags "ready" --parallel --only "parallelizable"`

@jonathangiber @j-morsum @dudicp @fadc80  What do you folks thinh?

**Comment by nehashri** [comment]
@jonathangiber @j-morsum @dudicp @fadc80 This feature is available with Gauge nightly. Can you please use it and let us know if this works for your projects.

Refer [this](https://docs.gauge.org/latest/installation.html#alternate-installation-methods) to install Gauge nightly. You may have to uninstall your current version of Gauge before installing the nightly.

**Comment by jonathangiber** [comment]
Amazing, many thanks! Going to try it today

**Comment by jonathangiber** [comment]
Working as expected, many thanks

**Comment by Debashis9012** [comment]
Able to define the test which we want to run specifically in parallel by using "--parallel" tags and other will run in serial.
This enhancements has been verified with the below versions:
version: 1.0.5.nightly-2019-04-04.

**Comment by iskoc9002** [comment]
Hi everyone,
I've a maven gauge project. My spec include 2 different scripts. First one is, Admin is creating meeting. Second one, Members vote agenda item(s) at the same time. So, I want to run first script. Then second scripts for 10 different users at the same time.

So, How can I do it with this solution. I'didn't do it.

**Comment by Vishnu1067** [comment]
@sriv @nehashri Hi, I am using mvn gauge:execute command and wanna run `tag: dataprepation` beforeSuite. How can i use this feature with mvn gauge command? I already set env  as `allow_filtered_parallel_execution=true`. Please help on this.

**Comment by Vishnu1067** [comment]
@sriv @nehashri Any help?

**Comment by sriv** [comment]
@Vishnu1067 - so this feature lets you choose which specs can be run in parallel, and thereby lets you choose specs that need to be run in serial.

Something like this:

```
mvn test-compile gauge:execute -DinParallel=true -Dflags="--only=parallel"
```

will execute specs without `parallel` tag first and then execute specs with `parallel` tag in parallel.

So in your usecase, I guess you need to flip your tag definition, i.e. you need to whitelist specs that need to be parallelized.

PS - gauge-maven plugin does not support the `--only` flag yet, so you need to use the fallback `flags` property.
