### ISSUE TITLE
[Revert] - Remove windows installer.

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#963]
The windows exe installer should be removed. We should encourage users to use the zip and add gauge to a given path.

We should also be changing choco installer to use the zip and gauge.exe to default path.

**Comment by BugDiver** [comment]
The windows installers are removed. Only zip installers are created. Choco has been updated to use zip installers instead of `exe`.

**Comment by zabil** [comment]
From our user research most of the users use windows and struggle to use zip or chocalatey. For this reason we need to bring back our windows installers.

**Comment by sguptatw** [comment]
Unable to run the generated artifact https://bintray.com/gauge/Gauge/Nightly/1.0.2.nightly-2018-09-21.

- It does not have an extension .exe
- Even though I manually add the extension, not able to run it on Windows.

**Comment by nehashri** [comment]
Please check with latest nightly 25-09-2018
