### ISSUE TITLE
Gauge.writeMessage texts are not displayed in HTML Report after Gauge update.

### ISSUE THREAD

**Issue by nataraj93** [getgauge/gauge#970]
### Expected behavior
Messages should be printed for corresponding scenarios in html-report while using Gauge.writeMessage API.

### Actual behavior
After components update only scenario heading is displayed, detailed message of execution are not displayed.

### Existing Components: 

- Gauge: v0.9.5
- Gauge-Java: v0.6.4
- Gauge-Html-Report: v0.4.3

### Updated Components:

- Gauge: v0.9.7
- Gauge-Java: v0.6.6
- Gauge-Html-Report: v0.4.3

### Steps to reproduce

1. Run any spec with older Gauge components as mentioned above. 
2. Collect the reports.
3. Update the respective components.
4. Now run any spec and view report the detailed messages are not displayed.
5. Reverting back to older components does not resolve this behavior.

Refer screenshot of reports.

**Expected Report:**
![expected_report](https://user-images.githubusercontent.com/37285657/37269006-a6ebbd84-25ee-11e8-80d3-6cf2684046f4.png)

**Actual Report:**
![actual_report](https://user-images.githubusercontent.com/37285657/37269010-abc69162-25ee-11e8-9b51-053fa0feeddd.png)

**Comment by sriv** [comment]
valid issue, able to replicate. investingating.

**Comment by nehashri** [comment]
@nataraj93 Can you please provide some more information?
Where exactly are you adding the messages? (for eg. In `@Step` or `@BeforeSuite` methods). A code snippet or a sample project to replicate the issue would be helpful.

**Comment by nataraj93** [comment]
@nehashri Sure,
A scenario which has Gauge.writeMessage() in `@Step` would recreate this behaviour. For e.g. 

`@Step("Print Version Details ")`
`public void printVersionDetails(){`
`    Gauge.writeMessage("Env1 Version: " + getEnv1Version());`
`    Gauge.writeMessage("Env2 Version: " + getEnv2Version());`
`}`
When this step is executed versions of Env1, Env2 should be printed under details of “Print Version Details” scenario.

**Comment by nehashri** [comment]
@nataraj93 Can you execute`gauge version` on the command line and paste the contents here. It would help us debug the issue further.

**Comment by nataraj93** [comment]
@nehashri Yes, the issue occurred after updating Gauge. 

**BEFORE UPDATE:**

C:\Users\xyz>gauge version
Gauge version: 0.9.5
Commit Hash: 51cfe8d

Plugins
-------
html-report (4.0.2)
java (0.6.6)
json-report (0.2.1)
screenshot (0.0.1)
xml-report (0.2.0)

**AFTER UPDATE:**

C:\Users\xyz>gauge version
Gauge version: 0.9.7
Commit Hash: bc9784c

Plugins
-------
html-report (4.0.3)
java (0.6.6)
json-report (0.2.1)
screenshot (0.0.1)
xml-report (0.2.0)

**Comment by nehashri** [comment]
@nataraj93 Unfortunately I am not able to reproduce this issue. There may some version mismatch or something on your machine. 
Are you using any custom theme path from html-report (`GAUGE_HTML_REPORT_THEME_PATH` env variable)? 
If not can you try uninstalling gauge and its plugins and try to install again?

**Comment by nataraj93** [comment]
@nehashri  No, I am not using any custom theme path but we do use `gauge_reports_dir` to generate report on a custom location. Let me reinstall all components and get back.

**Comment by EvanWoah** [comment]
I am experiencing this as well. 
Gauge 0.9.7
csharp 0.10.1
html-report 4.0.3

Was also experiencing with Gauge 0.9.5

**Comment by nataraj93** [comment]
@nehashri I tried reinstalling on different systems with same version as mentioned above and the detailed view in report is not displayed. On a clean system (i.e.) where gauge is installed for 1st time with version 0.9.7 and reverted back to version 0.9.5 then test ran on Gauge 0.9.5 the issue was reproducible.

**Comment by sriv** [comment]
@nataraj93, @evanwoah can you try using the latest gauge nightly: https://bintray.com/gauge/Gauge/Nightly/_latestVersion and see if you still face this issue?

**Comment by sriv** [comment]
@nataraj93, @evanwoah can you try using the latest gauge nightly: https://bintray.com/gauge/Gauge/Nightly/_latestVersion and see if you still face this issue?

**Comment by sriv** [comment]
@nataraj93, @evanwoah can you try using the latest gauge nightly: https://bintray.com/gauge/Gauge/Nightly/_latestVersion and see if you still face this issue?

**Comment by EvanWoah** [comment]
@sriv yes nightly works, WriteMessage() outputs to the HTML report! Thank you.

**Comment by sguptatw** [comment]
@natraj93 Kindly confirm if using the latest gauge nightly solves this issue.

**Comment by nataraj93** [comment]
@sguptatw yes, issue is not reproducible with nightly build.
