### ISSUE TITLE
Parallel execution errors out

### ISSUE THREAD

**Issue by ocary** [getgauge/gauge#980]
**This is found on code newer than Gauge 0.9.7.**

### Expected behavior
Gauge specs to run without error with parallel enabled

### Actual behavior
Gauge process errors out.

In the basic java example provided via` gauge init java`, the error is in the screenshot attached.

If the Gauge suite is Spring based, the error is `java.io.FileNotFoundException:  class path resource [applicationContext-suite.xml] cannot be opened because it does not exist`

### Steps to reproduce
1.  Initialize a new Java instance via `gauge init java`
2.  Run` gauge run --parallel specs`
3.  Observe the run errors out.

### Workaround
Once a run has been done that errors out, go to the parent directory of the specs directory and rename `gauge_bin` to `gauge-bin` and re-run the specs.

### Possible cause
https://github.com/getgauge/gauge/commit/2317a523d7f03cecc513d47452e7a5c226c7c11f

### Gauge version
```
Gauge version: 0.9.8     <--  I'm not sure what code the gauge.exe I have is based upon - once I find out on Tuesday, I'll update this.
Commit Hash: 0ac4700

Plugins
-------
csharp (0.10.1)
flash (0.0.1)
html-report (4.0.3)
java (0.6.6)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

### Error screenshot
![parallelerror](https://user-images.githubusercontent.com/6934721/37632430-2a480764-2bbc-11e8-9f52-9b959db843ac.png)

**Comment by sriv** [comment]
@ocary - good catch, thanks for the analysis. I pushed a fix.

`gauge-bin` v/s `gauge_bin` happened because `gauge-csharp` uses the `gauge-bin` folder, I am changing it to be more consistent with other runners.

**Comment by sriv** [comment]
fix should be in nightly >= 20/03/2018

**Comment by ocary** [comment]
I did a basic parallel run with the new code, and no errors seen.  Thank you for the fast fix!
