### ISSUE TITLE
[Feature] Allow to set specification folder as env variable, such as reports directory

### ISSUE THREAD

**Issue by jackperalta** [getgauge/gauge#984]
### Expected behavior
It should be possible to define the location of the specification as env variable in the properties file or via command line interface. This allows for customized spec locations to make it easier to execute them, by not forcing anyone to give the custom location with each run.
Especially when one handles multiple projects with different custom locations.
It must be guaranteed, that current behavior is not changed, so that if no env variable is given, the current default `specs` is used.
Also when given a location via command line, e.g. `gauge run somewhereElse`, that this is selected over a variable defined in the properties files

### Actual behavior
Currently one cannot define such env variable

**Comment by nehashri** [comment]
should be available in nightly >=  27-03-18

**Comment by nehashri** [comment]
More details on the feature: 
There can be multiple spec directories in a project. Providing a way to specify this for all runs is useful as the user can then run only `gauge run` command. 
An env variable has been introduced `gauge_specs_dir` which allows a user to specify a comma separated list of spec directories. If the env variable is not specified the directory `specs` will be considered by default.

**Comment by sguptatw** [comment]
**Question**
What should be the behavior of `gauge run` when gauge_specs_dir has multiple spec directories given?

**Comment by sriv** [comment]
>  What should be the behavior of `gauge run` when `gauge_specs_dir` has multiple spec directories given?

I guess it should run all the specs from all the directories specified. That is the behaviour if you specify multiple specs directory from cli. ex `gauge run specs specs1` runs specs from both `specs` and `specs1`
