### ISSUE TITLE
Links on CONTRIBUTING.md do not work

### ISSUE THREAD

**Issue by moijes12** [getgauge/gauge#988]
### Expected behavior
Clicking on the links for the contributing guidelines and licence agreement on the CONTRIBUTING.md page should take me to the respective pages.

### Actual behavior
An *Access Denied* page is displayed as below

```xml
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
    <RequestId>1FB140A7FA6927F5</RequestId> 
    <HostId>
    IsvWnaTGu6WpnB/xF4U298q2H6cLgd9fN51ItJ1ndAgj1Qm7uudgFV2QVV6rbXQV/sA73QGp4rU=
    </HostId>
</Error>
```

### Steps to reproduce
1. Go to page https://github.com/getgauge/gauge/blob/master/CONTRIBUTING.md
2. Go to the section for the contribution process https://github.com/getgauge/gauge/blob/master/CONTRIBUTING.md#contribution-process 
3. Click on the link *here* or *Contributors Licence Agreement*

**Comment by zabil** [comment]
Fixed via 566fc289e36bfdce0fbfc6d4c0c75a44c202f47b

Thanks for reporting this!

**Comment by moijes12** [comment]
The link https://gauge.org/contribute/ still returns an AccessDenied

**Comment by sriv** [comment]
Fixed contribute link as well. It should be https://gauge.org/contribute.html

**Comment by moijes12** [comment]
Adding the commit link https://github.com/getgauge/gauge/commit/fec8fd2859978c58489797feef7bbb81a56204ff
