### ISSUE TITLE
Property to configure log directory creation

### ISSUE THREAD

**Issue by JAthertonKent** [getgauge/gauge#99]
The application logs are created by default at ./logs relative to the project root. It would be great to have a property to configure where the application logs are created.

**Comment by ApoorvaM** [comment]
Application logs can be now configured in default.properties as:
logs_directory = PATH_FOR_LOGS
By default, this will be at ./logs relative to project root.

Fixed in [commit](https://github.com/getgauge/gauge/commit/7d163674d41b2f1feb943a0e4dd340947f05b2d4).
