### ISSUE TITLE
Request timeout when request is sent just after starting runner [Flaky]

### ISSUE THREAD

**Issue by riju91** [getgauge/gauge#990]
When a gauge api which requires runner is called right after starting gauge in daemon mode, sometimes the request times out. The error message is as follows

```
Error while connecting to runner : Request timed out for Message with ID => 3 and Type => ImplementationFileListRequest
```

### Expected behavior
Request should not timeout

### Actual behavior
Sometimes request is timing out when the request is sent right after starting gauge in daemon mode, if we add 10ms of sleep this does not occur

### Steps to reproduce
1. open gauge-lsp-tests on branch stubimpl
2. run command: ```gauge run specs/generateStubs/generateStubs.spec:10```

### Gauge version
```
Gauge version: 0.9.8
Commit Hash: 506987e

Plugins
-------
html-report (4.0.3)
java (0.6.6)
js (2.2.0)
python (0.2.6)
ruby (0.4.3)
screenshot (0.0.1)
xml-report (0.2.0)
```

**Comment by sguptatw** [comment]
Working as expected
```
Gauge version: 0.9.9.nightly-2018-05-04
Commit Hash: 886dc10

Plugins
-------
js (2.3.0.nightly-2018-05-04)
```
