### ISSUE TITLE
No X11 DISPLAY variable was set

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#996]
**Expected behavior**
Gauge should be able to capture the screenshot

**Actual behavior**
No X11 DISPLAY variable was set, but this program performed an operation which requires it.

**Observed on**
* CI [Linux FT of Java](https://build.getgauge.io/go/tab/build/detail/Java-FT/1299/specs/1/linux)
> The message is
Failed to take regular screenshot: 
        No X11 DISPLAY variable was set, but this program performed an operation which requires it.

**Comment by sriv** [comment]
is this still relevant @sguptatw ?

**Comment by sguptatw** [comment]
Not relevant anymore
