### ISSUE TITLE
[LSP] document symbol should give list even when steps are not implemented

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#999]
**Expected behavior**
The list of document symbols should be given even when there are no step implementation folder or no step implementations.

**Actual behavior**
Getting invalid parse errors

**Steps to replicate**
* Create a `gauge-js` project
* Delete the implementation folder
* Invoke the command palette with symbol search
> The lsp logs contain parse error for the result
```
20:58:18.676 --> request #1: textDocument/documentSymbol: {"textDocument":{"uri":"file:///...FT/gauge-lsp-tests/data/test-explorer/example.spec"}}
20:58:18.676 request #1: textDocument/documentSymbol: parsing failed for ...\FT\gauge-lsp-tests\data\test-explorer\example.spec. [[ParseError] ...\FT\gauge-lsp-tests\data\test-explorer\example.spec:1 Spec does not have any elements => '']
```

**Comment by BugDiver** [comment]
Working as expected with these versions
```
Gauge version: 0.9.9
Commit Hash: cf46420

Plugins
-------
js (2.3.1) # 9dd8fa0

Gauge-VSCode
0.0.6  # 607aa46

```
@sguptatw  Please verify it.
